### ISSUE TITLE
Service worker returning outdated index.html

### ISSUE THREAD

**Issue by andycwk** [angular/angular#27701] opened 2018-12-17 12:54 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Description

I have a problem with the Angular service worker returning an old version of index.html (from the date the service worker was installed) that is driving me bonkers!

Basically on a fresh startup of the browser (chrome) the old index.html is being served by the service worker resulting in a defunct mainxxx.js being loaded and due to the IIS rewrite rule I have in play to support deep linking, mainxxx.js returns back with the contents of index.html (side effect of service worker returning wrong index.html in first place)

When I soft or hard refresh the browser tab, the correct index.html is loaded and all is fine... that is, until I close the browser and start again at which point the old index.html is served up again :O

I am a side-by-side deployment strategy, which basically means that a new folder is created every time ther eis a new deploy and the web hosting is then pointed at this new folder, thus the old files are not available while hosting the new deploy!

As you can see from the screenshot below (sorry about the redaction), I have turned off caching via the cache-control header for the index.html page and other service worker related files..

![devtools](https://user-images.githubusercontent.com/2248787/50085429-edcea600-01f1-11e9-9524-039ebf55db12.png)

The below is a copy of my ngsw-config.json
`{
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/favicon.ico",
        "/index.html",
        "/*.css",
        "/*.js"
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"
      ]
    }
  }]
}`

## 🔬 Minimal Reproduction

Not sure how I can easily replicate as it requires publishing a few different versions etc!

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.0.6
Node: 10.10.0
OS: darwin x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.10.6
@angular-devkit/build-angular       0.10.6
@angular-devkit/build-optimizer     0.10.6
@angular-devkit/build-webpack       0.10.6
@angular-devkit/core                7.0.6
@angular-devkit/schematics          7.0.6
@angular/cli                        7.0.6
@angular/http                       7.1.3
@angular/language-service           7.1.3
@angular/platform-browser           7.1.3
@angular/platform-browser-dynamic   7.1.3
@angular/pwa                        0.8.8
@angular/router                     7.1.3
@angular/service-worker             7.1.3
@ngtools/webpack                    7.0.6
@schematics/angular                 0.8.8
@schematics/update                  0.10.6
rxjs                                6.3.3
typescript                          3.1.6
webpack                             4.19.1

</code></pre>

**Anything else relevant?**
I've only testing in chrome so far.
- I've tried with an incognito tab mode where everything works as required
- Clearing down the service work cache works.. but not suitable for end users
- uninstalling the service worker works.. but not suitable for end users

It's also been suggested via my overflow question that having the dev tools (inspector) window open could be causing the issue, though this is happening in production where the user does not have the dev tools open!

**Comment by gkalpak** [comment] 2018-12-17 14:00
Hard to investigate this without a reproduction (or at least access to a live site demonstrating the issue).
What does `/ngsw/state` show on a broken client?

**Comment by andycwk** [comment] 2018-12-17 14:09
Hi, yeh sorry, as a developer myself I appreciate what your saying - I think at this stage I'm looking for some pointers that might help me to help you pin the issue (or my bad config) down :(

the ngsw state on a broken client looks like the following (this is directly after hitting the url on a fresh browser run)..

`
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://xxxxxx/main.4bbcd74df60e2a89d8f6.js: expected 19f6687ffbfc46b3b7eda5ad988064378cb50b7f, got ab82cc1c1934c30fa50c61286ad7765a7034eec0 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://xxxxxx/main.4bbcd74df60e2a89d8f6.js: expected 19f6687ffbfc46b3b7eda5ad988064378cb50b7f, got ab82cc1c1934c30fa50c61286ad7765a7034eec0 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://xxxxxx/ngsw-worker.js:692:35)
    at Generator.next (<anonymous>)
    at fulfilled (https://xxxxxx/ngsw-worker.js:312:62))
Latest manifest hash: cab2f2909e01c6342a4a955a157946608a1f8899
Last update check: 7s696u

=== Version cab2f2909e01c6342a4a955a157946608a1f8899 ===

Clients: 

=== Idle Task Queue ===
Last update tick: 13s408u
Last update run: 8s406u
Task queue:


Debug log:

[13s426u] Ignoring invalid request: 'only-if-cached' can be set only with 'same-origin' mode Driver.fetch(https://xxxxxx/, cache: only-if-cached, mode: no-cors)`

I'll check with my client if I can share the url for the UAT site with you guys.. but is there a private channel I can use instead of sharing with the world?

**Comment by gkalpak** [comment] 2018-12-17 15:39
There doesn't seem to be anything unexpected there. Basically, the SW is correctly entering a degraded (`EXISTING_CLIENTS_ONLY`) state (since it is getting a 200 request for a hashed file but with different than expected content). What this means is that:

1. Other clients (e.g. opening a second tab or reloading the current tab) should not be handled by the SW (but passed through to the network).
2. The latest manifest should be fetched, so clients would be served by that in the future.

But thay is what should happne theoretically :grin: The actual behavior might defer (e.g. due to a bug).

Feel free to send more info to my e-mail.

##
BTW, I would highly recommend not serving `index.html` for requests to files (e.g. URLs whose last path segment contains a dot (`.`)), because that can cause all sorts of funny issues (with and without SW).

**Comment by andycwk** [comment] 2018-12-17 15:46
Cheers... 

I'm just waiting for approval from the client, but regarding the warning about the rewrite rule... duly noted - I'll head over and change the rule now 👍 

I'll also report back just in case the new rule ends up tweaking the behaviour of the service worker too, especially as the old mainxxx.js will return a 404 after the change :P

**Comment by gkalpak** [comment] 2018-12-17 15:56
You might want to leave the current behavior until we get to the bottom of it :wink:

**Comment by andycwk** [comment] 2018-12-17 16:58
Yeh... had a little play with the rewrite rule and it didn't help out anyway :P

**Comment by JamesJansson** [comment] 2019-11-09 14:07
If you are getting this error, and your app was a progressive web app under an older version of angular, the ngsw-config.json format has been updated. You need to ensure that your '*.js' and '*.css' files are included in your ngsw-config.json file (they might say `/*.bundle.js`, `/*.bundle.css` or `/*.chunk.js`)
```
{
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/favicon.ico",
        "/index.html",
        "/manifest.json",
        "/*.css",
        "/*.js"
      ]
    }
  }, {
    "name": "assets",
    "installMode": "lazy",
    "updateMode": "prefetch",
    "resources": {
      "files": [
        "/assets/**"
      ]
    }
  }]
}
```

https://stackoverflow.com/questions/49142968/caching-of-index-html-in-angular-service-worker/50753863#50753863

**Comment by gkalpak** [comment] 2020-05-26 14:22
I am going to close this, since we don't have a reproduction. It doesn't seem that there is a bug in Angular here; it is just a matter of identifying what is causing the problem (in the app or the infrastructure). E.g. it could be that an FTP server or a CDN modifies the content of some files.

There is also a chance that this is caused by #28114, in which case this is a duplicate.

**Closed by gkalpak** 2020-05-26 14:22 UTC
Labels: comp: service-worker, state: Needs repro, triage #1, type: bug/fix, type: support
