### ISSUE TITLE
aio + docs/api: enforce sentence structure

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22760] opened 2018-03-14 10:22 UTC
See https://github.com/angular/angular/issues/22138#issuecomment-367825807

**Comment by jenniferfell** [comment] 2018-08-29 14:38
Looks like a duplicate of https://github.com/angular/angular/issues/21034

**Comment by jenniferfell** [comment] 2018-08-29 14:40
Closing as duplicate

**Closed by jenniferfell** 2018-08-29 14:40 UTC
Labels: comp: docs-infra, comp: docs/api, effort1: hours, freq1: low, type: feature
