### ISSUE TITLE
Regression: ERROR in Symbol UISref declared in ... is not exported from @uirouter/angular

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular#36991] opened 2020-05-08 01:13 UTC
# 🐞 bug report

### Affected Package

The issue is possibly caused by package `@angular/compiler-cli`

### Is this a regression?

This is a regression between Angular `9.1.4` and `9.1.5`

### Description

When compiling the UIRouter [sample-app-angular](https://github.com/ui-router/sample-app-angular) app, the compiler complains: 

```
$ ng build --prod --source-map
Compiling @angular/core : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @uirouter/core : module as esm5
Compiling @angular/common : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @uirouter/angular : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015

ERROR in Symbol UISref declared in /private/tmp/sample-app-angular/node_modules/@uirouter/angular/directives/uisref.d.ts is not exported from @uirouter/angular (import into /private/tmp/sample-app-angular/src/app/app.component.ts)
error Command failed with exit code 1.
```

## 🔬 Minimal Reproduction
```
git clone https://github.com/ui-router/sample-app-angular.git
cd sample-app-angular
git checkout angular-9.1.4

# Test against Angular 9.1.4 🙂👍
yarn && yarn build && yarn test

# Update from 9.1.4 to 9.1.5 😩👎
sed -e 's/=9.1.4/=9.1.5/g' -i '' package.json
yarn && yarn build && yarn test
```

## 🔥 Exception or Error

```
ERROR in Symbol UISref declared in /private/tmp/sample-app-angular/node_modules/@uirouter/angular/directives/uisref.d.ts is not exported from @uirouter/angular (import into /private/tmp/sample-app-angular/src/app/app.component.ts)
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.4
Node: 12.16.3
OS: darwin x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cli                      9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

Downgrading only `@angular/compiler-cli@9.1.4`(but keeping the other angular libraries at `9.1.5`) works.

**Comment by gkalpak** [comment] 2020-05-08 13:56
Potential duplicate of #36992.

**Comment by petebacondarwin** [comment] 2020-05-08 16:05
I can confirm that the artifacts from https://github.com/angular/angular/pull/37008 resolve this issue, so marking as a duplicate of #36992.

**Closed by petebacondarwin** 2020-05-08 16:05 UTC
