### ISSUE TITLE
angular Hydration (provideClientHydration()) issue with ng-template

### ISSUE THREAD

**Issue by ashishnarelia** [angular/angular#51798] opened 2023-09-15 11:48 UTC
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

Yes

### Description

in my application i am using "ngbAccordion" and inside this accordion I have ng-template . when application opens on browser with ssr the content inside ng-template render twice. see below HTML -> 
```
<div ngbAccordion>
    <div ngbAccordionItem [collapsed]="false">
        <h3 ngbAccordionHeader>
            <button ngbAccordionButton class="fw-bold">question 1</button>
        </h3>
        <div ngbAccordionCollapse>
            <div ngbAccordionBody>
                <ng-template>
                    <span>Answer 1</span>
                </ng-template>
            </div>
        </div>
    </div>
    <div ngbAccordionItem>
        <h3 ngbAccordionHeader>
            <button ngbAccordionButton class="fw-bold">question 2</button>
        </h3>
        <div ngbAccordionCollapse>
            <div ngbAccordionBody>
                <ng-template>
                    <span>Answer 2</span>
                </ng-template>
            </div>
        </div>
    </div>
</div>
```

I have added provideClientHydration() inside app module.

### Please provide the environment you discovered this bug in (run `ng version`)

Angular veriosn 16

**Comment by pkozlowski-opensource** [comment] 2023-09-15 12:18
@ashishnarelia there is not enough information for us here to diagnose the problem. Please share a minimal reproduction scenario, otherwise it is not actionable for us.

**Comment by ashishnarelia** [comment] 2023-09-15 12:41
content inside ng-template rendering twice on browser by using the angular ssr provideClientHydration(). 
this is the HTML inside my component 
<div ngbAccordion>
    <div ngbAccordionItem [collapsed]="false">
        <h3 ngbAccordionHeader>
            <button ngbAccordionButton class="fw-bold">question 1</button>
        </h3>
        <div ngbAccordionCollapse>
            <div ngbAccordionBody>
                <ng-template>
                    <span>Answer 1</span>
                </ng-template>
            </div>
        </div>
    </div>
    <div ngbAccordionItem>
        <h3 ngbAccordionHeader>
            <button ngbAccordionButton class="fw-bold">question 2</button>
        </h3>
        <div ngbAccordionCollapse>
            <div ngbAccordionBody>
                <ng-template>
                    <span>Answer 2</span>
                </ng-template>
            </div>
        </div>
    </div>
</div>

here "<span>Answer 1</span>" is displaying twice on browser. "<span>Answer 1</span>" is inside the <ng-template>.

**Comment by AndrewKushnir** [comment] 2023-09-16 01:51
@ashishnarelia could you please provide a minimal repro (using an empty app generated via `ng new` and the minimum amount of code needed to reproduce the problem) in a form of a Github repository, so that we can replicate the problem and perform the necessary investigation? Thank you.

**Comment by ashishnarelia** [comment] 2023-09-18 06:34
please check repo url below
https://github.com/ashishnarelia/angular-16-issue.git

**Comment by AndrewKushnir** [comment] 2023-09-19 02:15
@ashishnarelia thanks for providing a repro, this is very helpful!

I've performed an investigation and it looks like the problem is located in the accordion directive:

https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/accordion/accordion.directive.ts#L77-L79

The contents of a created embedded view is being inserted into the DOM using direct manipulation. As a result, Angular is not aware of this operation and no hydration happens. You can find more info in the hydration guide: https://angular.io/guide/hydration#direct-dom-manipulation

As a possible solution, the `NgbAccordionBody` directive can be updated to become a component with a template that would contain an `<ng-container>` that would act as an anchor for the content insertion. Here is a possible shape of the component (note: it's simplified, but it illustrates the idea):

```
@Component({
  selector: '[customAccordionBody]',
  template: '<ng-container #ref />',
  host: { '[class.accordion-body]': 'true' },
})
export class NgbAccordionBody {
  @ViewChild('ref', {read: ViewContainerRef}) vcr!: ViewContainerRef;
  @ContentChild(TemplateRef, { static: true }) private _bodyTpl!: TemplateRef<any>;

  ngAfterViewInit(): void {
    if (this._bodyTpl) {
      this._createViewIfNotExists();
    }           
  }     

  ngOnDestroy(): void {
    this._destroyViewIfExists();
  }     

  private _destroyViewIfExists(): void {
    this.vcr.clear();
  }     

  private _createViewIfNotExists(): void {
    this.vcr.createEmbeddedView(this._bodyTpl);
  }     
}
```

I've tested that with this approach there is no content duplication happens and all nodes are hydrated correctly.

Closing this ticket, since an update needs to happen on the ng-bootstrap side. Please open an issue in the ng-bootstrap GitHub repository.

**Closed by AndrewKushnir** 2023-09-19 02:15 UTC
Labels: needs reproduction, area: core, core: hydration
