### ISSUE TITLE
Missing link to page 

### ISSUE THREAD

**Issue by angemariya** [angular/angular#53066] opened 2023-11-20 20:22 UTC
### Describe the problem that you experienced

On the page https://angular.dev/tutorials/learn-angular/updating-the-component-class is missing the link to page with description of Typescript Type Inference

"The `city` property is of type `string` but you can omit the type because of [type inference in TypeScript](https://angular.dev/typescript.org/type-inference)."

### Enter the URL of the topic with the problem

https://angular.dev/typescript.org/type-inference

### Describe the actions that led you to experience the problem

Click on achor [type inference in TypeScript](https://angular.dev/typescript.org/type-inference).

**Comment by JoostK** [comment] 2023-11-20 20:31
Thanks for the report, this is a duplicate of #52553 for which the fix is pending deployment.

**Closed by JoostK** 2023-11-20 20:31 UTC
