### ISSUE TITLE
External link icon for hyperlinks is causing formatting issues

### ISSUE THREAD

**Issue by aikidave** [angular/angular#41787] opened 2021-04-23 15:07 UTC
# 📚 Docs or angular.io bug report

### Description
At certain screen sizes, the external link icon for hyperlinks is being bumped down a line, causing the text on the screen to format incorrectly.

### What's the affected URL?**
Any page that has an external hyperlink.

### Reproduction Steps**
Open a link, such as https://angular.io/guide/reviewing-content.

Reduce the screen size.

### Expected vs Actual Behavior**
External link icon remains connected to hyperlink text

## 📷Screenshot
![external-link-icon](https://user-images.githubusercontent.com/30159843/115891373-dd0a4c80-a40a-11eb-8a5d-cc5e322ecf58.png)

**Comment by petebacondarwin** [comment] 2021-04-23 15:09
Duplicate of https://github.com/angular/angular/issues/41774

**Closed by petebacondarwin** 2021-04-23 15:09 UTC
