### ISSUE TITLE
Two way binding implementation not working properly

### ISSUE THREAD

**Issue by SathishKumarRajendran** [angular/angular#38841] opened 2020-09-14 15:55 UTC
# 🐞 Bug report

### Command 

- [x] serve

### Is this a regression?

No

### Description

We are providing two way binding support for dropdown component, While selecting dropdown value two binding working fine. But while enable `showcheckbox` property in our dropdown control two binding not working.

**Validation Details:**

1. Without our `showcheckbox` property

In our component, here is triggering the `this.propagateChange` 

![image](https://user-images.githubusercontent.com/53341125/93097829-b3928100-f6c3-11ea-8379-57579a1ea559.png)

At first calling setvalue with parameter `{ emitModelToViewChange: false }` from update control method, refer below image

![image](https://user-images.githubusercontent.com/53341125/93099098-4384fa80-f6c5-11ea-9a41-6028d7a93152.png)

Then called setvalue with parameter `{ emitViewToModelChange: false }`,  to call writevalue method and working fine.

![image](https://user-images.githubusercontent.com/53341125/93101128-88aa2c00-f6c7-11ea-9322-0217451ba2f1.png)

2. With our  `showcheckbox` property,

![image](https://user-images.githubusercontent.com/53341125/93102372-0c184d00-f6c9-11ea-8ae4-81bd1a2c7be3.png)

![image](https://user-images.githubusercontent.com/53341125/93102759-687b6c80-f6c9-11ea-9eff-51967f48b624.png)

here this `{ emitViewToModelChange: false }` parameter with setvalue is not called in while enabling our `showcheckbox` property. So writevalue method is not calling, this is the issue we facing in our component.

## 🔬 Minimal Reproduction

**Working sample:**

github sample - https://github.com/SathishKumarRajendran/twowaybind-working

- npm i
- ng serve 

**Steps to reproduce issue:** 

Replace below line to below Code snippet line.

https://github.com/SathishKumarRajendran/twowaybind-working/blob/master/src/app/app.component.ts#L10

`<ejs-dropdowntree  #dropdown name="first" [(ngModel)]='value' id='dropdownTree' [fields]='fields' (change)= "onChange($event)" [showCheckBox]='true' ></ejs-dropdowntree>`

## 🔥 Exception or Error

No

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 10.15.1
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by nutza249949** [comment] 2020-09-14 17:16
m

**Comment by SathishKumarRajendran** [comment] 2020-09-18 03:19
Could you please suggest any solution on this

**Comment by petebacondarwin** [comment] 2020-09-18 06:22
@SathishKumarRajendran - are you the developer of the `ejs-dropdowntre`? Or are you just using it in your project?

**Comment by SathishKumarRajendran** [comment] 2020-09-22 09:32
Hi @petebacondarwin  
>are you the developer of the ejs-dropdowntre?

Yes I am the developer.

**Comment by petebacondarwin** [comment] 2020-09-22 12:47
I haven't been able to debug in and prove this but I think the problem is that you are mutating the array of items when the value can be multivalued, rather than creating a new array. Therefore when Angular is told to change detect the value passed to the `ngModel` on the input, it doesn't see a change, since the old value and the new value are the same array.

**Comment by jelbourn** [comment] 2020-10-12 22:32
Closing this since it seems like it either resolved or working as expected in that this expects the array reference to change per Pete's comment.

**Closed by jelbourn** 2020-10-12 22:32 UTC
Labels: comp: core, comp: forms, state: works-as-expected
