### ISSUE TITLE
@angular/flex-layout module.d.ts causes error NG6002 in Angular 9 with Ivy enabled.

### ISSUE THREAD

**Issue by mycroft16** [angular/angular#35480] opened 2020-02-16 10:19 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/flex-layout@9.0.0-beta.29

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description

 A clear and concise description of the problem...
![image](https://user-images.githubusercontent.com/10989109/74602759-82889a00-5069-11ea-80e0-ea1399fc170d.png)

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-issue-repro2-yka2ok?file=src%2Findex.html

## 🔥 Exception or Error
<pre><code>
Date: 2020-02-16T10:00:11.507Z - Hash: d1ce2b53dac8b997d698
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 150 kB [initial] [rendered]
Time: 702ms
: Compiled successfully.
    
    ERROR in node_modules/@angular/flex-layout/typings/module.d.ts:16:22 - error NG6002: Appears 
in the NgModule.imports of AppModule, but could not be resolved to an NgModule class
    
    16 export declare class FlexLayoutModule {
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 13.8.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
No

**Comment by shubhamkokul** [comment] 2020-02-16 17:09
Facing the similar issue. Trying to find a way around thinking of downgrading the version and using it.

**Comment by FranzZemen** [comment] 2020-02-16 17:45
I was having the same issues adding some angular material modules.  I may have found a fix after realizing that on first compile of library/app, ng build is also updating node_modules code.  I cleaned node_modules (the top one in the workspace) and re-installed.  Then rebuild my lib & app.  No issues.  I think added another module, and issue reappeared.  Repeated clean & build, no issues.

So maybe when ng build is updating the node_modules code (in my case angular material) it's having a hard time "updating" it for new modules.

So...clean node_modules after adding modules that cause issues, and retry.

**Comment by FranzZemen** [comment] 2020-02-16 17:53
When get NG6002 with a module issue as above, delete the top node_modules in the workspace (where you should have installed it), and rebuild libraries/apps.

Seems like on first build, output is added to node_modules that gets occasionally confused.

This 'trick" works for me with problems incrementally added angular material modules to a library and app.

**Comment by mycroft16** [comment] 2020-02-16 20:35
@FranzZemen That seems to have done the trick. Aggravating though but glad the workaround is simple. Thanks for that. Os this symptomatic of a deeper problem that needs fixing or is this just par for the course with all the packages in node_modules?

**Comment by FranzZemen** [comment] 2020-02-16 21:04
@mycroft16 Once I got past my issue, it hasn't resurfaced with new modules (yet).  I'm thinking its an Ivy related glitch or something.  Many threads on this since 9 got released (and prior).  Pretty sure it will make it to a patch in the future.

**Comment by shubhamkokul** [comment] 2020-02-16 22:45
Worked for me as well thanks

**Comment by petebacondarwin** [comment] 2020-05-24 18:44
It is impossible to diagnose any deeper issue from the information given.
It looks like the node_modules got corrupted somehow and ngcc was not able to re-process some of the packages.
It seems that the standard workaround of cleaning out the node_modules folders and re-installing solved the problem.
Therefore I am closing this issue. If the problem re-occurs and you can provide a reproduction that we can debug, please open a new issue.

**Closed by petebacondarwin** 2020-05-24 18:44 UTC
Labels: comp: compiler, comp: ngcc, engine: ivy, severity5: regression
