### ISSUE TITLE
beta.1 ngModel/ngModelChange not working on select element in FireFox 43.0.4

### ISSUE THREAD

**Issue by dougludlow** [angular/angular#6573] opened 2016-01-19 22:52 UTC
I'm seeing an issue in `beta.1` that appears to be a regression from `beta.0`. `ngModel/ngModelChange` don't appear to work at all in Firefox, at least on selects. Here's a [plunkr demo](https://plnkr.co/edit/8Q2ZpXw9qEwCjiiuKGzJ?p=preview). You'll notice if you change the script src's to beta.0, the selects work as expected. Is there a breaking change that I'm missing? I don't see anything about `ngModel/ngModelChange` in the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-beta1-catamorphic-involution-2016-01-08).

```
import {Component} from 'angular2/core';

@Component({
	selector: 'my-app',
	template: `
		<h1>ngModel/ngModelChange not working on Firefox</h1>
		<select [ngModel]="name" (ngModelChange)="changed($event)">
			<option value=""></option>
			<option *ngFor="#n of names" [value]="n">{{n}}</option>
		</select>
		<pre>Name: {{name}}</pre>
 
		<select [(ngModel)]="name">
			<option value=""></option>
			<option *ngFor="#n of names" [value]="n">{{n}}</option>
		</select>
		<pre>Name: {{name}}</pre>
	`
})
export class AppComponent { 
	names: String[] = ['Alpha', 'Bravo', 'Charlie'];
	name: string;

	changed(event) {
		this.name = event;
	}
}
```

**Comment by neridonk** [comment] 2016-01-25 15:21
+1

**Comment by eostrom** [comment] 2016-01-27 02:50
Also in Firefox 45.0a2 (2016-01-22).

Could be b44d36cf955acd81a3e7285ab0e1acbffe8c8dcc. It removes a `(change)` binding from `select` so as not to call onChange twice, but maybe in Firefox that `(change)` was needed?

**Comment by eostrom** [comment] 2016-01-27 02:58
Confirmed, I re-added the missing line and my selects work again.

I'm not going to submit a PR because it would break #5969. @vsavkin, any thoughts?

**Comment by DenisKolodin** [comment] 2016-01-28 09:49
For 44.0 also doesn't work.

Temporary I've fix it locally with:
```
<select [ngModel]="value" (change)="value = $event.target.value">
```

Bug is actual for *select*.

**Comment by Sabartius** [comment] 2016-02-04 12:40
It doesn't even work in Chrome properly, if you automate your angular2 application with protractor. Something's fishy about these "input"-Events

**Comment by zoechi** [comment] 2016-02-04 12:55
@Sabartius could be related to #6311 - just a wild guess.

**Comment by Sabartius** [comment] 2016-02-04 13:28
@zoechi I'm not sure, but i'm very sure it's this change causing the trouble: https://github.com/angular/angular/commit/b44d36cf955acd81a3e7285ab0e1acbffe8c8dcc
I had a similar issue with input-fields and protractor after angular got changed to only rely on the input-event (see: #5730)

Somehow i've got a feeling, as if no one really uses protractor with angular2...

**Comment by jonnysamps** [comment] 2016-02-10 21:39
+1

**Comment by danielgerlag** [comment] 2016-02-10 23:38
+1

**Comment by dougludlow** [comment] 2016-02-11 00:37
Circling back around - I've confirmed that @DenisKolodin's workaround works. Thanks!

**Comment by dougludlow** [comment] 2016-02-11 00:42
https://plnkr.co/edit/JiuSdU?p=preview

**Comment by CaselIT** [comment] 2016-02-16 11:24
Also not working also on Edge 25

**Comment by frederikschubert** [comment] 2016-02-19 13:43
IE11 also has this problem.

**Comment by mirco312312** [comment] 2016-02-19 16:03
this fix worked with the current FF and IE versions: https://github.com/angular/angular/pull/7185

**Comment by behbc** [comment] 2016-02-23 17:11
+1 
You also can see this problem on the [live example](https://angular.io/resources/live-examples/forms/ts/plnkr.html) available on the Developer Guides / Form.

**Comment by zarkosusnjar** [comment] 2016-02-24 17:31
C'mon guys, one week without Firefox and automated testing...Fix is trivial, PR or not, just push it to beta.8

**Comment by e-oz** [comment] 2016-02-27 21:23
@zarkosusnjar this bug exists more than month, not 1 week.

**Comment by gajdot** [comment] 2016-02-29 09:18
+1 still present in Beta 7

**Comment by samridh90** [comment] 2016-03-04 00:28
Don't mean to pile on but I'm seeing this issue in Beta.7 with FF 44.0.2. Would be great to get a fix for this soon!

**Comment by pentium10** [comment] 2016-03-04 07:12
@vsavkin @mhevery @tbosch @alexeagle @petebacondarwin 
We need this applied immediately, what's holding you guys back? Let us know, as we want this to be applied this weekend, also how to apply the fix locally to the built library?

**Comment by PascalPrecht** [comment] 2016-03-04 07:15
> We need this applied immediately, what's holding you guys back?

I think there's tons of other stuff to do. Maybe you can speedup the process by send a pull request that fixes this?

**Comment by pentium10** [comment] 2016-03-04 07:24
There is a pull request submitted by @mirco312312 already see above.

**Comment by mirco312312** [comment] 2016-03-04 07:30
That fix only reverts a change that broke ngModel/ngModelChange on select-elements. Currently we deploy this fix by Hand. As the PR is currently blocked by failing tests (FF on Linux, IE+EDGE on Win8, couldn't reproduce this in 'real' browsers).

**Comment by e-oz** [comment] 2016-03-04 08:16
@pentium10 please don't forget it's free product and ng team has no obligations, especially about somebody's else deadlines. You can implement workaround, proposed by @DenisKolodin - works fine, even in minified code.

**Comment by mswehli** [comment] 2016-03-07 13:49
+1

**Comment by theodorejb** [comment] 2016-03-09 05:05
This is a pretty serious bug, and the labels say it should be easy to fix, but the issue has been open for over 7 weeks now. @vsavkin is #7185 not the right way to fix this? Is there anything we can do as a community to move this forward? @mhevery

**Comment by DHainzl** [comment] 2016-03-09 10:46
Using the workaround @DenisKolodin, I also found out that if you use it in a `*ngFor` and have the `ngControl` option set, changing any value also changes the last value of the iteration if the values are the same. See the following plunker (tested in Firefox):

http://plnkr.co/edit/g2tbjJMpOfRwz8ZhY3dj?p=preview

When changing the type of Emilia from "FirstName" to something different, the type of Max also changes. This also happens when the type of Example is the same as the type of Max and you change the type of Example to something different ...

**Comment by mmesko** [comment] 2016-03-09 13:37
I actually make this work. In need to be able to select department for my employee. This is sth I used:  ```
editEmployee(item){      
        this.selected.employeeName = item.employeeName;
        this.selected.salary = item.salary;
        this.convertToInt(this.selected.Department = this.department ? this.department.departmentNo :    item.departmentNo);
        this.convertToInt(this.selected.departmentNo =  this.selected.Department);

     this._employeeService.editEmployee(this.selected).subscribe(employees => this.getAll());
     
     }
```
and in my view it looks:

```
<form [hidden]="!showEditView" align="center">
       <div>
            <label for="editTitle">Department:</label><br>
            <select [(ngModel)]="selected.departmentNo"  #departmentNo="ngForm"  style="width: 180px" required  (keyup) = "0">
                 <option *ngFor="#department of departments"  [value]="department.departmentNo">{{department.departmentName}}, {{department.departmentLocation}}</option>
           </select> 
                      
        </div>
        <div>
            <label for="editAbrv">Employee name:</label><br>
              <input type="text" [(ngModel)]="selected.employeeName" ngControl="employeeName" #employeeName="ngForm" required (keyup) = "0">
              <div [hidden]="employeeName.valid || employeeName.pristine" class="alert alert-danger">Name is required</div>     
        </div>
        <div>
            <label for="editAbrv">Salary:</label><br>
             <input type="text" [(ngModel)]="selected.salary" ngControl="salary" #salary="ngForm" required (keyup) = "0" > 
             <div [hidden]="salary.valid || salary.pristine" class="alert alert-danger">Salary is required</div>    
        </div>
   
        <div>
            <a href="javascript:void(0);" (click)="editEmployee(selected); showEditView=false; " (keyup) = "0" title="Edit">
                Save
            </a>
            <a href="javascript:void(0);" (click)="showHideEdit($event); showEditView=false" >
                Cancel
            </a>
        </div>
</form>
```

I also had a problem with recognizing numbers as numbers (JS returned me strings) so I implemented:

```
    convertToInt(string){
       return parseInt(string);
    };
```

selected object looks like this:

```
 selected = {employeeNo:null, employeeName:'', departmentNo: null, salary:null, lastModifyDate:null, 
                         Department:{departmentNo:null, departmentName:'', departmentLocation:''}};
```

:)

**Comment by zoechi** [comment] 2016-03-09 17:24
@theodorejb "easy" also is an indication that the community could jump in. If this fix is important enough someone could take a stab and implement this "easy" fix and create a pull request.

**Comment by flore2003** [comment] 2016-03-09 17:54
@zoechi As far as I understand #7185 by @mirco312312 should fix this, but it is currently still failing the integration tests for some reason.

**Comment by e-oz** [comment] 2016-03-12 18:59
@robwormald @naomiblack please put this task on radar of team as candidate for the [hotlist: A2 Blocking](https://github.com/angular/angular/labels/hotlist%3A%20A2%20Blocking)

**Comment by DrewynV** [comment] 2016-04-05 00:28
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166454.
------------------------------------------------------------------------------------------------------------


[[a976a347caf96aa4515f0e019f0265e98e4a598c-673073395]]

**Comment by DrewynV** [comment] 2016-04-05 00:28
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166470.
------------------------------------------------------------------------------------------------------------


[[2857da7e5f58e8dbb82c7060719394845d4b3fc8-673073431]]

**Comment by suuuunto** [comment] 2016-04-06 16:55
1+

**Comment by JayByfordRewAtTorFx** [comment] 2016-04-12 11:20
re @DenisKolodin 's workaround also add another handler for keydown. i.e. (keydown)="doSomething($event)"

**Comment by KernowCode** [comment] 2016-04-12 11:22
Regarding @DenisKolodin 's workaround also add a handler for keydown. i.e. (keydown)="doSomethingWith($event)" so catch keypress changes most likely up and down arrows when selecting options

**Comment by e-oz** [comment] 2016-04-12 12:09
(keyup) is not a workaround, because <select> can be changed without keypresses at all.

**Comment by tchoulihan** [comment] 2016-04-14 23:41
This is an issue for me in firefox, does anyone know of a workaround?

**Comment by e-oz** [comment] 2016-04-14 23:44
@tchoulihan I use this one: https://github.com/angular/angular/issues/6573#issuecomment-176091804

**Comment by tchoulihan** [comment] 2016-04-15 15:26
@e-oz Thank you so much. of course the `changeValue(target)` function needs to be written to set the correct value, but at least its a workaround.

**Comment by jderose9** [comment] 2016-04-19 16:05
Having the same issue on Android 4.4.4 WebView. The ngModelChange handler never fires.

**Closed** 2016-04-22 21:45 UTC
Labels: comp: core/forms, effort1: easy (hour), P1: urgent, type: bug

**Comment by e-oz** [comment] 2016-04-22 22:04
Thank you very much! 👏🎉☀️

**Comment by ruwhan** [comment] 2016-05-04 06:32
just notice this when trying to test my web app on Firefox.

**Comment by awerlang** [comment] 2016-05-04 12:37
@ruwhan just update to beta.16 (see https://github.com/angular/angular/commit/c3daccd83b86e453ce538fa7f75c4cff2564a836). this issue is already closed, btw.
