### ISSUE TITLE
FormControl valueChanges should emit null instead of previous value on control.disabled()

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#37788] opened 2020-06-27 08:51 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 I don't think so

### Description

when a control is disabled it's new value is null, bit the valueChanges event doesn't emit with null, but rather with the previous value. This is inconsistent IMHO.

It is specially problematic when using nested forms.
My ugly workaround looks like this:
```
this.editForm.valueChanges.subscribe(value => this.value = this.editForm.disabled ? null : value);
```

Once this is confirmed as a bug I would really like to contribute with the simple code change and relative tests, please allow me to do so. Thanks :)
## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-fjxciy

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.4
Node: 10.16.3
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.4
@angular-devkit/core         9.0.4
@angular-devkit/schematics   9.0.4
@angular/cdk                 9.0.1
@ngtools/webpack             9.0.4
@schematics/angular          9.0.4
@schematics/update           0.900.4
rxjs                         6.5.3
typescript                   3.7.5
webpack                      4.41.2

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment] 2020-06-27 10:16
I don't think there is a bug here, as disabling a form control does not affect its value in any way. So the _previous_ value is just the _current_ value.

You mention "when a control is disabled it's new value is null", can you elaborate on why you think this is the case?

**Comment by yelhouti** [comment] 2020-06-27 11:29
@JoostK thank you for the quick feedback, to answer you question 
> You mention "when a control is disabled it's new value is null", can you elaborate on why you think this is the case?
I should have said undefined instead of null, and I updated my stackblitz to show that.
I say that because when a "single" field is disabled it is not returned in the `.value` of it's parent form ex:
```
  editForm = this.fb.group({
    name: ['name1', [Validators.required]],
    data: ['data1', [Validators.required]]
  });
  //////
  console.log(this.editForm.value.data); // data1
  console.log(this.editForm.get('data').value); // data1
  this.editForm.get('data').disable();
  console.log(this.editForm.value.data); // undefined
  console.log(this.editForm.get('data').value); // data1
```
I would except that if editForm had a parent:
```
  parentForm = this.fb.group({
    child: this.editForm
  });
  console.log(this.parentForm.value.child); // {name: "name1", data: "data1"}
  console.log(this.parentForm.get('child').value); // {name: "name1", data: "data1"}
  this.parentForm.get('child').disable();
  console.log(this.parentForm.value.child); // {name: "name1", data: "data1"} (expected undefined)
  console.log(this.parentForm.get('child').value); // {name: "name1", data: "data1"}
```
Which is clearly inconsistent.
I can understand that `this.editForm.value.data` and `this.editForm.get('data').value` why one would like to have different result from those, but I think it's the source of the problem.
That said, we can still keep that behavior and change the child FormGroup to match the basic FormControl. What do you think?

**Comment by indraraj26** [comment] 2020-06-27 14:38
After all your parentForm formgroup would look like this, I would not expect undefined as we are just disabling the controls
```
this.parentForm = new FormGroup({
      child: new FormGroup({
        name: new FormControl('name1'),
        data: new FormControl('data1')
      })
    })
```

**Comment by JoostK** [comment] 2020-06-27 15:26
@yelhouti Oh well that looks very inconsistent, indeed. In fact, it looks like togging the disabled state of the parent form allows a disabled child control to reappear, where it would be hidden before.

I don't think that it's necessarily bad behavior that a group control won't be set to undefined when disabled, but I would expect all child controls to be undefined in that case (given that form controls seem to become `undefined` when disabled, I expect that behavior to be applicable if a parent is disabled).

My current view is that the issue you initially reported is not a bug, but the general behavior of `value` in combination with disabled state looks like a bug to me.

**Comment by yelhouti** [comment] 2020-06-28 13:32
@JoostK I reread my first issue and I agree it is not very clear, we also agree on the problem I think:
FormGroups should behave like FormControls when disabled:
value is undefined in controls to match the HTML spec (ie: disabled fields are not submitted). Do you mind me making a PR?

**Comment by JoostK** [comment] 2020-06-28 14:10
> FormGroups should behave like FormControls when disabled:

This is not what I meant, actually. See my previous response:
> I don't think that it's necessarily bad behavior that a group control won't be set to undefined when disabled

I think it's fine for form groups to behave differently than form controls. The surprising behavior occurs for form controls that are contained within a disabled group, making them implicitly disabled. As they are implicitly disabled, I wouldn't expect them to be included in value but they are today.

Regarding a PR, I'm afraid that changing this behavior one way or another will be a big breaking change, which means you'll probably have a hard time getting the PR approved and merged. Do feel free to work on a PR that you think will address the issue, as it might shed some more light on the issue and it gives a bit of insight into the magnitude of any breakages. But as I mentioned before, it may be challenging to get it merged.

**Comment by mlc-mlapis** [comment] 2020-06-28 15:18
Reading this conversation, it reminds me that the base of this is probably the non-existence of `readonly` property, as it has been since the issue, as #11447, isn't it?

**Comment by yelhouti** [comment] 2022-03-16 11:49
@ameryousuf you can work on this, I am a bit tight on time

**Comment by JeanMeche** [comment] 2024-05-10 13:06
The issue looks to be unrelated to valueChanges, but on the `FormGroup.value` itself : A FormGroup with a single element that is disabled still returns it's value. 

```
export class App {
  parentForm = new FormGroup({
    child: new FormGroup({
      name: new FormControl('name1'),
      data: new FormControl('data1'),
    }),
  });

  parentForm2 = new FormGroup({
    foo: new FormControl('data1'),
    child: new FormGroup({
      name: new FormControl('name1'),
      data: new FormControl('data1'),
    }),
  });

  constructor() {
    this.parentForm.controls.child.disable(); 
    this.parentForm2.controls.child.disable();
  }
}
```
Repro: https://stackblitz.com/edit/angular-vprwnt?file=src%2Fmain.ts

**Comment by JeanMeche** [comment] 2024-05-10 13:28
I'm closing this as a dupe of #15982. 
A disabled group is expected to return its value.

**Closed by JeanMeche** 2024-05-10 13:28 UTC
Labels: type: bug/fix, help wanted, freq1: low, area: forms, type: confusing, forms: Controls API, forms: disabling controls, P4

**Comment by yelhouti** [comment] 2024-05-10 14:04
@JeanMeche sorry bUt this is not the same thing. 
I understand that trying to to retreive the value of a disable field should return the value, but retrieving the parent show the value is a null which consistant with HTML spec.
the valueChanges however is not consistent with that.

**Comment by JeanMeche** [comment] 2024-05-10 17:31
Can you provide a stackblitz that shows that ?
