### ISSUE TITLE
InvalidCharacterError: Attribute name

### ISSUE THREAD

**Issue by tejainece** [angular/angular#7240] opened 2016-02-23 19:36 UTC
I am getting the following error:

InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '[[class.show]]' is not a valid attribute name.

Using angular2 version 2.0.0-beta.7.

**Comment by ericmartinezr** [comment] 2016-02-23 19:37
I've seen similar errors with invalid HTML. You have to provide a plnkr reproducing the issue.

**Comment by tejainece** [comment] 2016-02-23 21:15
If it helps, i dont get this error on 2.0.0-beta.0

**Comment by cdauth** [comment] 2016-03-16 22:02
I get this error when using Angular 2 attributes inside a `ngNonBindable` block:

    <div ngNonBindable>
        <a (click)="test()">Test</a>
    </div>

The reason is that the allowed characters for the first arguments of `setAttribute()` in the DOM standard are oriented on the XML standard, which does not allow any special characters, as opposed to the HTML standard. This inconsistency is documented [here](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27228).

I don't know what Angular 2 is using `setAttribute()` for, but I think a library that relies on attributes that violate the DOM standard should not use such DOM methods.

**Comment by pkozlowski-opensource** [comment] 2016-06-03 17:41
Here is a repro scenario with rc.1: https://plnkr.co/edit/Ae8avxnLYMGkkM12DMVL?p=preview

What is going on here is an equivalent of doing:

```javascript
 document.createElement('div').setAttribute('(click)', 'test');
```

Try it in your favourite browser and see it blow without Angular being involved. So the error comes from a browser and has nothing to do with Angular.

Now, why Angular uses `setAttribute`? It is used for "static attributes" by a renderer during initial display. It is a pity that browsers accept some attributes when specified in HTML but not when using `setAttribute` (try `el.innerHTML = '<div (click)="test()">Good</div>';` and see that browsers are totally cool with this!). I believe that this is a pb in HTML spec that was already reported.

Closing as not actionable on the Angular side.

**Closed by pkozlowski-opensource** 2016-06-03 17:41 UTC
Labels: hotlist: error messages

**Comment by hokkaido** [comment] 2016-09-13 08:28
@pkozlowski-opensource This behaviour (the use of setAttribute) makes creating Angular2 code examples from within an Angular2 application a really tedious affair. What options do we really have for this? Using inner-html?
