### ISSUE TITLE
Improve NgForm/NgControl confusing syntax naming choice?

### ISSUE THREAD

**Issue by doliver3** [angular/angular#5997] opened 2015-12-18 07:22 UTC
Hi,

I just tried the latest beta. It is confusing to me and others I've spoken with why template variable binding to ngControl would - as visually written in the template - be binding to ngForm instead? (The current beta is requiring this according to documentation.) I believe one of the design goals of Angular was to make it clear in the template what is happening. Currently, this is not clear. The required template syntax for control binding within a form does not match what is actually occurring according to the documentation.

If one wants to refer to an ngControl on the form using a template local variable, why should the binding look like the following confusing syntax where the #name template variable is tied to an ngForm directive instead as shown on your documentation page https://angular.io/docs/ts/latest/guide/forms.html?

CONFUSING in the current beta:
 ngControl="name"  #name="ngForm"

BETTER:
 ngControl="name"  #name="ngControl"

Wouldn't a better syntax be to bind the template variable for the control to the ngControl which is actually then intent and effect of this syntax even as your documentation describes?

It would be even better if ngControl="name" would auto-create the #name template variable so only one attribute rather than 2 would be required but perhaps there is an interest in being highly explicit so possibly having both could make sense for the purpose of explicitness and perhaps tool binding (but it would be very nice to just be able to indicate ngControl='name' and be done.) 

Even so, if the #name should be tied to an ngControl, shouldn't the template reflect what is being done for clarity by using #name=ngControl rather than #name=ngForm?

If we have one form on the page and 3 controls inside it, shouldn't the form itself have the template variable set to 'ngForm' (#heroForm="ngForm") while the 3 controls should be set as shown on the template to 'ngControl' (ngControl="name"  #name="ngControl" --- ngControl="addressLine1"  #addressLine1="ngControl" --- ngControl="city"  #city="ngControl")?

#### as shown in documentation...
> Here we initialize a template local variable (name) with the value "ngForm" (#name="**ngForm**"). Angular recognizes that syntax and re-sets the name local template variable to the **ngControl** directive instance *[instead????]*. In other words, the name local template variable becomes a handle on the **ngControl** object for this input box.

I'm asking in this issue why when the documentation says that the syntax sets the instance to the ngControl directive, the syntax as written is actually showing #name="ngForm"  which intuits that Angular2 is setting the template instance variable to the ngForm?  To be consistent with what is actually happening, wouldn't the clearer syntax for an ngControl be #name="ngControl" ?

Here is the form syntax that the paragraph from the documentation is explaining when it says #name='ngForm' actually makes name point to the ngControl directive:
```html
<form (ngSubmit)="onSubmit()" #heroForm="ngForm">

<!-- Why ngForm? Why not ngControl? -->
<input type="text" class="form-control" required
  [(ngModel)]="model.name"
    ngControl="name"  #name="ngForm" >
<div [hidden]="name.valid" class="alert alert-danger">
  Name is required
</div>

<!-- now what if we have more controls on the form? 
Why ngForm? Why not ngControl? -->
<input type="text" class="form-control" required
  [(ngModel)]="model.addressLine1"
    ngControl="addressLine1"  #addressLine1="ngForm" >
<div [hidden]="addressLine1.valid" class="alert alert-danger">
  Address first line is required
</div>

<input type="text" class="form-control" required
  [(ngModel)]="model.name"
    ngControl="city"  #city="ngForm" >
<div [hidden]="city.valid" class="alert alert-danger">
  City is required
</div>
```

**Comment by oliverjanik** [comment] 2015-12-21 06:13
Absolutely agree, the whole forms part of Angular2 is indeed very confusing and feels like a step backwards from what we had in 1.5. 

I re-read the form guide 3 times and I still don't know how to
a) add custom validation to ngModel, or
b) take ControlGroup and update the values from JSON i get from the server.

Feels like a square wheel.

**Comment by ribizli** [comment] 2015-12-29 07:44
See this: https://angular.io/docs/ts/latest/api/core/DirectiveMetadata-class.html#!#exportAs
`exportAs` is `ngForm` in the ngForm directive, that's why `#name="ngForm"` is working.

**Comment by corinna000** [comment] 2016-01-05 21:16
I'm confused by the same thing. To try to separate out the `name` variable (which seemed overloaded to me in this example), I changed the local variable to `fooBar`. 

```html
        <input type="text" class="form-control" required
          [(ngModel)]="model.name"
            ngControl="fooBar" #fooBar="ngForm" >
        <div [hidden]="fooBar.valid" class="alert alert-danger">
          Name is required
        </div>
```
What I expect here is that ngControl points to the local variable `fooBar`, and that `fooBar.valid` would be true if the input had a value in it. 

Curiously, if I set `ngControl="name"` it actually works as I expected. I'm not really sure what `name` maps to now if it's not the local value of the control.

**Comment by corinna000** [comment] 2016-01-05 22:07
```html
<label for="name">Name</label>
<input type="text" class="form-control" required
  [(ngModel)]="model.name"
    ngControl="name"  #name="ngForm" >
<div [hidden]="name.valid" class="alert alert-danger">
  Name is required
</div>
```
It took a bit to work out that the value of `ngControl` does not have anything to do with the local value of input `#name`. Furthermore, the label is `for="name"` but the input does not have `id="name"`, which it probably should to work correctly. 

The label `name` is overloaded and it's hard to understand what's happening in this example.

**Comment by msimpson** [comment] 2016-01-28 17:32
@corinna000
I would advise that you read the following source code for [ng_control_name](https://github.com/angular/angular/blob/3191fd144016c0873de4e3e24f0d8695a7d101c2/modules/angular2/src/common/forms/directives/ng_control_name.ts), the actual `ngControl` directive. There you will see that the `ngControl` attribute's value is being bound to the `NgControl` class's `name` property (given to the `NgControlName` through extension). That property is then used to uniquely identify this control instance inside the parent form's `ControlGroup` (see [ng_form](https://github.com/angular/angular/blob/3191fd144016c0873de4e3e24f0d8695a7d101c2/modules/angular2/src/common/forms/directives/ng_form.ts)). The "label" name is indeed overloaded in this example, but feel confident that if you changed that value to "x" (i.e. `ngControl="x"`) that the form would still function.

**Comment by cagataycivici** [comment] 2016-03-19 14:06
I agree, I read the forms docs and got super confused because of this naming convention. ngControl="name" #name="ngControl" would have been a better choice.

**Comment by ericmartinezr** [comment] 2016-03-19 14:07
This issue is addressed over here https://github.com/angular/angular/issues/7236

**Comment by kara** [comment] 2016-06-28 23:12
Closing as this is a duplicate of #7236, as @ericmartinezr mentioned.

The new forms module replaces the `ngForm` export names with names matching the directive:

`ngModel` exports as "ngModel" (as of 0.1.1 and RC.3)
`ngModelGroup` exports as "ngModelGroup"

**Closed by kara** 2016-06-28 23:12 UTC
