### ISSUE TITLE
Click events and custom tags not being recognized for dynamic content coming from api response when injected into html using [innerHTML].

### ISSUE THREAD

**Issue by hinalshah91** [angular/angular#24977] opened 2018-07-19 07:14 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. (click) event doesn't work.
2. Swiper carousel is not getting initialized.

## Expected behavior

1. (click) event should work as it normally does.
2. Swiper carrousel should be initialized when it gets the swiper tag.

## Minimal reproduction of the problem with instructions

In the ts file:
`this.common.getPageTemplate(param).subscribe(
      response => {
        this.template = response;
})`

In the html file:
`<div [innerHTML]="template.description"></div>`

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-07-19 07:16
Duplicate of https://github.com/angular/angular/issues/11349

**Comment by vicb** [comment] 2018-07-20 18:41
Closing as work as expected.

There might be a way to do this later on when IVY is out - but you would have to ship the compiler.

**Closed by vicb** 2018-07-20 18:41 UTC
