### ISSUE TITLE
Use of [disabled] and [required] in reactive form

### ISSUE THREAD

**Issue by natcohen** [angular/angular#12263] opened 2016-10-13 07:28 UTC
```
[   ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[   ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It is currently impossible to use [required] and [disabled] in reactive forms

**What is the motivation / use case for changing the behavior?**
In many forms, some fields depend on other fields. With reactive forms it makes it extremely difficult and verbose to require or disable a field conditionally to another field

**Angular version:** 
2.1.0

I have read [here](https://angular.io/docs/ts/latest/cookbook/form-validation.html) that 

> A future version of reactive forms will add the required HTML validation attribute to the DOM element (and perhaps the aria-required attribute) when the control has the required validator function.

Does it mean that [required] and [disabled] will be supported in future versions? It is important for users to understand the limitations of reactive forms so they can take the best decision (reactive vs template) based on their (future) needs.

**Comment by DzmitryShylovich** [comment] 2016-10-13 07:41
Thanks for reporting this issue. However this issue is a duplicate of an existing issue https://github.com/angular/angular/issues/11271.

**Comment by natcohen** [comment] 2016-10-13 21:29
@DzimitryShylovich I know but the issue is closed and there is no clear path of the future... Will it be supported? Or should we migrate to the template model? It would be good to have more details!

**Comment by vicb** [comment] 2016-10-14 05:15
duplicate

**Closed by vicb** 2016-10-14 05:15 UTC
Labels: comp: forms

**Comment by natcohen** [comment] 2016-10-14 09:28
@vicb Did the team decide if someone will address this issue or did the team decid it will remain as is? A very short answer telling us what the plans are would really help us take the best decision...

**Comment by natcohen** [comment] 2016-10-20 19:51
@vicb Why nobody wants to give even a short answer?
