### ISSUE TITLE
Service workers - makes AJAX Progress Listener not Working

### ISSUE THREAD

**Issue by adnan-kamili** [angular/angular#24716] opened 2018-06-29 16:55 UTC
I am using Angular 6 and facing a similar issue as mentioned in the following issue:

https://github.com/w3c/ServiceWorker/issues/1141

The service worker times out after some time with 500 error for XHRUploads and no progress of course, though it works fine with service workers disabled 

Can I skip service worker for PUT requests as mentioned in the following comment:

https://github.com/w3c/ServiceWorker/issues/1141#issuecomment-301797690

**Comment by gkalpak** [comment] 2018-06-29 18:34
This is similar to #24683.

The problem is indeed that ServiceWorkers can't use `XMLHttpRequest`; they have to use `Fetch` which doesn't support upload progress (yet).

It is currently not possible to ignore specific requests.
(It might be possible to do that if we implement https://github.com/angular/angular/issues/20756#issuecomment-386315924, but that is currently in the backlog.)

**Comment by adnan-kamili** [comment] 2018-06-30 05:06
As a temporary fix, I created a copy of ngsw-worker.js and added following to ignore the PUT requests:

```javascript
onFetch(event) {
        const req = event.request;
        if (event.request.method === 'PUT') {
            return;
        }
        ...
```
Then I registered ngsw-worker-modified.js containing the fix.

I hope this approach won't have issues, as I don't expect `ngsw-worker.js` code to change often. How often should I sync `ngsw-worker.js` and `ngsw-worker-modified.js`, if it does change at all?

**Comment by gkalpak** [comment] 2018-06-30 13:52
> How often should I sync ngsw-worker.js and ngsw-worker-modified.js, if it does change at all?

As often as it changes :grin: It does change every now and then when we fix issues or add new features (but not very often indeed).

**Comment by mdrichardson** [comment] 2018-08-02 21:18
@adnan-kamili @mordka 

Thank you thank you thank you!

I had a similar issue where, rather than having a problem with PUT methods , the service worker broke calls to an external API. I fixed mine similarly.

To whitelist my API URLs, I opened `ngsw-worker.js` and changed `onFetch(event)` to:

    onFetch(event) {
        const req = event.request;
        // List of words in request URL to whitelist/bypass the service worker
        const whitelist = ['api', 'otherWhitelistWords...']
        // Check to see if request url contains any whitelisted words and skip the rest of onFetch if it does
        if (whitelist.some(word => req.url.toLowerCase().includes(word.toLowerCase()))) {
    	            return
        }
       ...
    }

You can automate fixing of `ng build:prod` by creating a `fix-sw.sh`:

    #!/bin/bash
    sed -i "/onFetch(event) {/,/const req = event.request;/c onFetch(event){const req=event.request;const whitelist=['api','otherWhitelistWords...'];if(whitelist.some(word=>req.url.toLowerCase().includes(word.toLowerCase()))){return}" ./dist/${PROJECTNAME}/ngsw-worker.js

then, in `package.json`, change your `build:prod` to:

    "build:prod": "ng build --prod && bash ./fix-sw.sh",

**Comment by gkalpak** [comment] 2018-09-17 11:40
Closing as a duplicate of #21191.

**Closed by gkalpak** 2018-09-17 11:40 UTC
Labels: comp: service-worker, severity2: inconvenient, type: feature

**Comment by TobiasGruberAT** [comment] 2019-01-09 12:20
@mordka Hey, thanks for your Shell example! It seems to work perfectly, but I just can't make it run on Apple, is there anything I would've to change?

Getting the error: 
`sed: 1: "../dist/client/ngsw-wor ...": invalid command code .`

**Comment by mordka** [comment] 2019-01-09 12:47
Hi @TobiasGruberAT I'm aware of this issue on Mac.
I ended up using `patch-package` tool and the following git patch. 
```
diff --git a/node_modules/@angular/service-worker/ngsw-worker.js b/node_modules/@angular/service-worker/ngsw-worker.js
index 51c431b..1216506 100755
--- a/node_modules/@angular/service-worker/ngsw-worker.js
+++ b/node_modules/@angular/service-worker/ngsw-worker.js
@@ -1896,6 +1896,10 @@ ${msgIdle}`, { headers: this.adapter.newHeaders({ 'Content-Type': 'text/plain' }
          */
         onFetch(event) {
             const req = event.request;
+            //PATCH to prevent caching certain kinds of requests
+            // - PUT requests which breaks files upload
+            // - requests with 'Range' header which breaks video in the library
+            if(req.method==="PUT"||!!req.headers.get('range'))return;
             // The only thing that is served unconditionally is the debug page.
             if (this.adapter.parseUrl(req.url, this.scope.registration.scope).path === '/ngsw/state') {
                 // Allow the debugger to handle the request, but don't affect SW state in any
```
It contains more clauses than you need, feel free to adjust.
