### ISSUE TITLE
Bug: @angular/form/RequiredValidator may need unregister required validator when onDestory 

### ISSUE THREAD

**Issue by maxisacoder** [angular/angular#19081] opened 2017-09-07 02:42 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

the following code

```
<div *ngIf = "exp1">
      <input  formControlName = "key" [required]="exp1"></input>
</div>
```
The corresponding formControl still have required validator when the exp1 is set to `false`, and `div` destroyed.

## Expected behavior

unregister required validator when `RequiredValidator` directive destoryed. 

## What is the motivation / use case for changing the behavior?

user can get right form state in FormControl or parent FormGroup

**Comment by kara** [comment] 2018-07-31 23:08
The `required` validator directive will work with reactive forms (though it's not recommended), but in the example above, the `ngIf` template is destroyed before the directive's binding can be checked to remove the validator. There's not much forms can do about this because validator directives can be implemented in any way. I'd recommend switching to using `setValidators` in the reactive form API instead.

**Comment by CSchulz** [comment] 2018-08-10 07:40
@kara would it not be possible to remove the validators during destroy of the form control? I think a discussion point would be remove all validators or only the newly added one.

**Comment by kara** [comment] 2018-08-10 16:35
@CSchulz  For reactive forms, the structure of the template is not the source of truth for form control state. So if the form control element is destroyed, this doesn't mean that the form control's validation will change. On the other hand, the required Validators directive is designed to work with template-driven forms, where the template does drive the form. For this directive, its removal from the DOM should remove itself from the form control.

**Comment by CSchulz** [comment] 2018-08-10 19:55
@kara You are right, so I think the best way would be to remove the template set validators only and keep existing validators which are set with the reactive form way. But this mean as far as I have seen it, we have to track the validators somehow.

**Comment by ver-1000000** [comment] 2018-08-22 02:30
Hi.

I tried to create a Reproduction Code and to register New Issue based on this, but since I found this related Issue, I will provide it as a related code.

https://stackblitz.com/edit/angular-qxbzks

Related Also: [Japanese community reaction on this matter](https://spectrum.chat/thread/79b1091c-348e-4fb8-8ce3-d25373a8396b)

**Comment by TFleury** [comment] 2018-11-23 11:03
Same as #14955

**Comment by mtraynham** [comment] 2019-03-28 18:20
Just encountered this in a different scenario.  I was following along with this blog on how to implement nested forms, a way to split up complex forms with ReactiveForms.
https://blog.angularindepth.com/angular-nested-reactive-forms-using-cvas-b394ba2e5d0d

There's a section in there on validation, which suggests the nested form component implement Validator to pass validation back up to the parent form, e.g. using:

```ts
        providers: [{
            provide: NG_VALIDATORS,
            useExisting: forwardRef(() => Type),
            multi: true
        }]
```

When using these nested forms with `*ngIf` or `[ngSwitch]`, which may remove the nested form control or use it with a different nested form, the validators build up overtime on the parent form as they are never removed from these controls.

Because the parent form control is hanging on to the validator of the nested form, it's actually hanging on to the whole component instance.  This actually seems like a pretty bad memory leak given the right circumstances.

**Comment by AndrewKushnir** [comment] 2020-05-25 20:40
Hi, as @TFleury mentioned, this issue looks like a duplicate of #14955, so I'm closing this ticket (the #14955 has a link to this issue to capture extra info and discussion in this thread). Please subscribe to #14955 for further updates/discussion. Thank you.

**Closed by AndrewKushnir** 2020-05-25 20:40 UTC
Labels: comp: forms, forms: validators, freq2: medium, severity1: confusing, state: confirmed, triage #1, type: bug/fix
