### ISSUE TITLE
ng i18n --ivy does not extract correctly HTML message with interpolation

### ISSUE THREAD

**Issue by bougnat12** [angular/angular#39241] opened 2020-10-13 13:16 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [X] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

the `ng i18n`command extracts message correctly.

### Description

I'm trying to use `ng xi18n --ivy` command with Angular 10.1.5 / CLI 10.1.5 packages to extract all my Typescript and HTML text for translation.

I have for example a label shared in four HTML templates. `ng xi18n` extract this label and add four location with the right interpolation.

`ng xi18n --ivy` generates a single location (false because it points on Typescript invalid code instead of HTML one) and interpolation is malformed. (single `{`instead of two `{{` and `?` misplaced).

## 🔬 Minimal Reproduction

For example, with this template code:

```html
<mad-modal-confirm i18n="@@MAD.confirmDeleteModalMsg" i18n-title="@@psSetupPanel.modalConfirmTitle" title="Delete Power Supply" size="md" id="deletePowerSupplyButton" (closed)="deletePowerSupplyConfirm($event)">
  Confirm delete {{uiName}}?
</mad-modal-confirm>
```

The `ng xi18n --output-path locale --format=xlf2` command will generate:

```xml
    <unit id="MAD.confirmDeleteModalMsg">
      <notes>
        <note category="location">app/components/setup/ps/setup-panel/ps-setup-panel.component.html:7,9</note>
        <note category="location">app/components/setup/wall/panel-setup/panel-setup.component.html:56,58</note>
        <note category="location">app/components/setup/vc/setup-panel/vc-setup-panel.component.html:10,12</note>
        <note category="location">app/components/setup/zone/detail/zone-detail.component.html:14,16</note>
      </notes>
      <segment>
        <source>
  Confirm delete <ph id="0" equiv="INTERPOLATION" disp="{{uiName}}"/>?
</source>
      </segment>
    </unit>
```

and the `ng xi18n --ivy --output-path src/locale --format=xlf2 --out-file=messages-ivy.xlf`command will generate:

```
    <unit id="MAD.confirmDeleteModalMsg">
      <notes>
        <note category="location">src/app/components/setup/zone/detail/zone-detail.component.ts:111</note>
      </notes>
      <segment>
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="{uiName}}?"/>?
</source>
      </segment>
    </unit>
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.6
Node: 12.18.4
OS: darwin x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cdk                    10.2.4
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-10-13 13:38
The fact that it only captures one of the locations is a bug. We should track that independently and fix it.

The incorrect `disp` attribute value is also a bug and is a duplicate of https://github.com/angular/angular/issues/39195.

The incorrect location path (`zone-detail.component.ts`) seems strange. It might be that source-mapping is turned off for the build? This is required in order to back-trace through from the built code to the original template. (Although I thought that the CLI would temporarily force it on for message extraction).

**Comment by alan-agius4** [comment] 2020-10-14 12:21
> The incorrect location path (zone-detail.component.ts) seems strange. It might be that source-mapping is turned off for the build? This is required in order to back-trace through from the built code to the original template. (Although I thought that the CLI would temporarily force it on for message extraction).

Indeed the CLI does forcefully turn this on.

**Comment by petebacondarwin** [comment] 2020-10-17 11:53
I have captured the first problem in #39314, the second problem is already captured in #39195.
The other issue looks like an issue with your setup.

I am going to close this issue. Please open a new one with a link to a git repository that reproduces the incorrect source location issue.

**Closed by petebacondarwin** 2020-10-17 11:53 UTC
Labels: comp: i18n

**Comment by petebacondarwin** [comment] 2020-10-19 15:44
First problem is now tracked in #39330

**Comment by kamilchlebek** [comment] 2020-10-22 09:12
> The incorrect location path (zone-detail.component.ts) seems strange. It might be that source-mapping is turned off for the build? This is required in order to back-trace through from the built code to the original template. (Although I thought that the CLI would temporarily force it on for message extraction).

@petebacondarwin 

It seems that switching `target` in `tsconfig.json` from `es2015` to `es5` causes incorrect `sourcefiles` to be listed.

es2015 (with or without --ivy) & es5 (without --ivy)
```
<context context-type="sourcefile">src/app/app.component.html</context>
<context context-type="linenumber">1</context>
```

es5 (with --ivy)
```
<context context-type="sourcefile">src/app/app.component.ts</context>
<context context-type="linenumber">11</context>
```

Here's the repo: https://github.com/kamilchlebek/i18n-ivy-es5

PS. I didn't want to create new issue, because I'm not sure whether using `target: es5` is recommended. We are testing a lot on ie11, so it's more convenient for us to use it.

**Comment by petebacondarwin** [comment] 2020-10-22 09:18
Thanks @kamilchlebek - I'll take a look. It is generally better to create new issues rather than post on closed ones.

**Comment by petebacondarwin** [comment] 2020-10-22 12:31
@kamilchlebek - I just cloned your repo and ran `ng xi18n --ivy` on it. I can confirm what you are seeing.
The problem is that the source-maps generated by the build for ES5 are not accurate as you can see in this [visualization](https://sokra.github.io/source-map-visualization/#base64,aW1wb3J0IHsgX19tYWtlVGVtcGxhdGVPYmplY3QgfSBmcm9tICJ0c2xpYiI7CmltcG9ydCB7IENvbXBvbmVudCB9IGZyb20gJ0Bhbmd1bGFyL2NvcmUnOwppbXBvcnQgKiBhcyBpMCBmcm9tICJAYW5ndWxhci9jb3JlIjsKdmFyIEFwcENvbXBvbmVudCA9IC8qKiBAY2xhc3MgKi8gKGZ1bmN0aW9uICgpIHsKICAgIGZ1bmN0aW9uIEFwcENvbXBvbmVudCgpIHsKICAgICAgICB0aGlzLnRpdGxlID0gJ2kxOG4nOwogICAgfQogICAgQXBwQ29tcG9uZW50LsOJwrVmYWMgPSBmdW5jdGlvbiBBcHBDb21wb25lbnRfRmFjdG9yeSh0KSB7IHJldHVybiBuZXcgKHQgfHwgQXBwQ29tcG9uZW50KSgpOyB9OwogICAgQXBwQ29tcG9uZW50LsOJwrVjbXAgPSBpMC7DicK1w4nCtWRlZmluZUNvbXBvbmVudCh7IHR5cGU6IEFwcENvbXBvbmVudCwgc2VsZWN0b3JzOiBbWyJhcHAtcm9vdCJdXSwgZGVjbHM6IDQsIHZhcnM6IDAsIGNvbnN0czogZnVuY3Rpb24gKCkgeyB2YXIgaTE4bl8wOyBpZiAodHlwZW9mIG5nSTE4bkNsb3N1cmVNb2RlICE9PSAidW5kZWZpbmVkIiAmJiBuZ0kxOG5DbG9zdXJlTW9kZSkgewogICAgICAgICAgICB2YXIgTVNHX0VYVEVSTkFMXzQ2NzcxNzU5MTEwMzAwMDY0MjckJF9fX19fX19fX19fX19fX19fX1VTRVJTX1BFVEVfREVWX0FOR1VMQVJfVE1QX0lTU1VFMzkyNDFfU1JDX0FQUF9BUFBfQ09NUE9ORU5UX1RTXzEgPSBnb29nLmdldE1zZygidGVzdCIpOwogICAgICAgICAgICBpMThuXzAgPSBNU0dfRVhURVJOQUxfNDY3NzE3NTkxMTAzMDAwNjQyNyQkX19fX19fX19fX19fX19fX19fVVNFUlNfUEVURV9ERVZfQU5HVUxBUl9UTVBfSVNTVUUzOTI0MV9TUkNfQVBQX0FQUF9DT01QT05FTlRfVFNfMTsKICAgICAgICB9CiAgICAgICAgZWxzZSB7CiAgICAgICAgICAgIGkxOG5fMCA9ICRsb2NhbGl6ZSh0ZW1wbGF0ZU9iamVjdF8xIHx8ICh0ZW1wbGF0ZU9iamVjdF8xID0gX19tYWtlVGVtcGxhdGVPYmplY3QoWyI6XHUyNDFGOTJhYjdjMDFmNWNjMDliNDQ5YzMwNWQzMmNjODhjMWRmNzQ4Njc4M1x1MjQxRjQ2NzcxNzU5MTEwMzAwMDY0Mjc6dGVzdCJdLCBbIjpcdTI0MUY5MmFiN2MwMWY1Y2MwOWI0NDljMzA1ZDMyY2M4OGMxZGY3NDg2NzgzXHUyNDFGNDY3NzE3NTkxMTAzMDAwNjQyNzp0ZXN0Il0pKSk7CiAgICAgICAgfSB2YXIgaTE4bl8yOyBpZiAodHlwZW9mIG5nSTE4bkNsb3N1cmVNb2RlICE9PSAidW5kZWZpbmVkIiAmJiBuZ0kxOG5DbG9zdXJlTW9kZSkgewogICAgICAgICAgICB2YXIgTVNHX0VYVEVSTkFMXzI5MDkzOTc4Mjk3NjI4OTI0OTkkJF9fX19fX19fX19fX19fX19fX1VTRVJTX1BFVEVfREVWX0FOR1VMQVJfVE1QX0lTU1VFMzkyNDFfU1JDX0FQUF9BUFBfQ09NUE9ORU5UX1RTXzMgPSBnb29nLmdldE1zZygidGVzdDIiKTsKICAgICAgICAgICAgaTE4bl8yID0gTVNHX0VYVEVSTkFMXzI5MDkzOTc4Mjk3NjI4OTI0OTkkJF9fX19fX19fX19fX19fX19fX1VTRVJTX1BFVEVfREVWX0FOR1VMQVJfVE1QX0lTU1VFMzkyNDFfU1JDX0FQUF9BUFBfQ09NUE9ORU5UX1RTXzM7CiAgICAgICAgfQogICAgICAgIGVsc2UgewogICAgICAgICAgICBpMThuXzIgPSAkbG9jYWxpemUodGVtcGxhdGVPYmplY3RfMiB8fCAodGVtcGxhdGVPYmplY3RfMiA9IF9fbWFrZVRlbXBsYXRlT2JqZWN0KFsiOlx1MjQxRjA5OTc0MmFlMWE5ZjMxMzFjNzgxZWU0NzE3NjllOTJhMDc2NmY1YzNcdTI0MUYyOTA5Mzk3ODI5NzYyODkyNDk5OnRlc3QyIl0sIFsiOlx1MjQxRjA5OTc0MmFlMWE5ZjMxMzFjNzgxZWU0NzE3NjllOTJhMDc2NmY1YzNcdTI0MUYyOTA5Mzk3ODI5NzYyODkyNDk5OnRlc3QyIl0pKSk7CiAgICAgICAgfSByZXR1cm4gW2kxOG5fMCwgaTE4bl8yXTsgfSwgdGVtcGxhdGU6IGZ1bmN0aW9uIEFwcENvbXBvbmVudF9UZW1wbGF0ZShyZiwgY3R4KSB7IGlmIChyZiAmIDEpIHsKICAgICAgICAgICAgaTAuw4nCtcOJwrVlbGVtZW50U3RhcnQoMCwgInNwYW4iKTsKICAgICAgICAgICAgaTAuw4nCtcOJwrVpMThuKDEsIDApOwogICAgICAgICAgICBpMC7DicK1w4nCtWVsZW1lbnRFbmQoKTsKICAgICAgICAgICAgaTAuw4nCtcOJwrVlbGVtZW50Q29udGFpbmVyU3RhcnQoMik7CiAgICAgICAgICAgIGkwLsOJwrXDicK1aTE4bigzLCAxKTsKICAgICAgICAgICAgaTAuw4nCtcOJwrVlbGVtZW50Q29udGFpbmVyRW5kKCk7CiAgICAgICAgfSB9LCBzdHlsZXM6IFsiIl0gfSk7CiAgICByZXR1cm4gQXBwQ29tcG9uZW50Owp9KCkpOwpleHBvcnQgeyBBcHBDb21wb25lbnQgfTsKLypAX19QVVJFX18qLyAoZnVuY3Rpb24gKCkgeyBpMC7DicK1c2V0Q2xhc3NNZXRhZGF0YShBcHBDb21wb25lbnQsIFt7CiAgICAgICAgdHlwZTogQ29tcG9uZW50LAogICAgICAgIGFyZ3M6IFt7CiAgICAgICAgICAgICAgICBzZWxlY3RvcjogJ2FwcC1yb290JywKICAgICAgICAgICAgICAgIHRlbXBsYXRlVXJsOiAnLi9hcHAuY29tcG9uZW50Lmh0bWwnLAogICAgICAgICAgICAgICAgc3R5bGVVcmxzOiBbJy4vYXBwLmNvbXBvbmVudC5jc3MnXQogICAgICAgICAgICB9XQogICAgfV0sIG51bGwsIG51bGwpOyB9KSgpOwp2YXIgdGVtcGxhdGVPYmplY3RfMSwgdGVtcGxhdGVPYmplY3RfMjsKLy8jIHNvdXJjZU1hcHBpbmdVUkw9YXBwLmNvbXBvbmVudC5qcy5tYXA=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYXBwLmNvbXBvbmVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIi4uLy4uLy4uL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIi4uLy4uLy4uL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBQSxPQUFPLEVBQUUsU0FBUyxFQUFFLE1BQU0sZUFBZSxDQUFDOztBQUUxQztJQUFBO1FBTUUsVUFBSyxHQUFHLE1BQU0sQ0FBQztLQUNoQjs0RUFGWSxZQUFZO3FEQUFaLFlBQVk7Ozs7Ozs7Ozs7Ozs7WUNQekIsNEJBQVc7WUFBWCxlQUFXO1lBQUksaUJBQU87WUFDdEIsNkJBQW1CO1lBQW5CLGVBQW1CO1lBQUssMEJBQWU7O3VCRER2QztDQVNDLEFBUEQsSUFPQztTQUZZLFlBQVk7a0RBQVosWUFBWTtjQUx4QixTQUFTO2VBQUM7Z0JBQ1QsUUFBUSxFQUFFLFVBQVU7Z0JBQ3BCLFdBQVcsRUFBRSxzQkFBc0I7Z0JBQ25DLFNBQVMsRUFBRSxDQUFDLHFCQUFxQixDQUFDO2FBQ25DIn0=,aW1wb3J0IHsgQ29tcG9uZW50IH0gZnJvbSAnQGFuZ3VsYXIvY29yZSc7CgpAQ29tcG9uZW50KHsKICBzZWxlY3RvcjogJ2FwcC1yb290JywKICB0ZW1wbGF0ZVVybDogJy4vYXBwLmNvbXBvbmVudC5odG1sJywKICBzdHlsZVVybHM6IFsnLi9hcHAuY29tcG9uZW50LmNzcyddCn0pCmV4cG9ydCBjbGFzcyBBcHBDb21wb25lbnQgewogIHRpdGxlID0gJ2kxOG4nOwp9Cg==,PHNwYW4gaTE4bj50ZXN0PC9zcGFuPgo8bmctY29udGFpbmVyIGkxOG4+dGVzdDI8L25nLWNvbnRhaW5lcj4KCgo=).

**Comment by kamilchlebek** [comment] 2020-10-22 12:42
@petebacondarwin Thank you for investigation. Then I think the easiest solution for me is to create `tsconfig.i18n.json` with:
```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "target": "es2015"
  }
}
```

**Comment by petebacondarwin** [comment] 2020-10-22 12:43
The workaround for you is to create a new `tsconfig.extract.json` that sets `target: es2015`. Then update the `angular.json` file to have a new build configuration that references this tsconfig and finally update the `extract-i18n` section in that file to use this new build config.

If this workaround is not usable for you please open a new issue so that I can track the work for fixing it.

**Comment by petebacondarwin** [comment] 2020-10-22 12:43
LOL! We had the same idea!

**Comment by bougnat12** [comment] 2020-11-16 16:11
I made some tests with last Angular 11 and I always have bad translation:

```xml
    <unit id="MAD.confirmDeleteModalMsg">
      <notes>
        <note category="location">src/app/components/setup/zone/detail/zone-detail.component.html:14,16</note>
        <note category="location">src/app/components/setup/wall/panel-setup/panel-setup.component.html:56,58</note>
        <note category="location">src/app/components/setup/vc/setup-panel/vc-setup-panel.component.html:10,12</note>
        <note category="location">src/app/components/setup/ps/setup-panel/ps-setup-panel.component.html:7,9</note>
      </notes>
      <segment>
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="e {{uiName"/>?
</source>
      </segment>
    </unit>
```

for the original text to translate:

```html
<mad-modal-confirm i18n="@@MAD.confirmDeleteModalMsg" i18n-title="@@psSetupPanel.modalConfirmTitle" title="Delete Power Supply" size="md" id="deletePowerSupplyButton" (closed)="deletePowerSupplyConfirm($event)">
  Confirm delete {{uiName}}?
</mad-modal-confirm>
```

I'm really disappointed because I like the new Angular 11 version but I cannot migrate my project with this show stopper.

**Comment by kamilchlebek** [comment] 2020-11-16 16:15
@bougnat12 There's an issue with multiline translations in angular 11. It's already reported here: https://github.com/angular/angular/issues/39671 

Fix is on the way

**Comment by petebacondarwin** [comment] 2020-11-16 17:01
@bougnat12 - you can check to see if #39671 is the same issue that you are experiencing by temporarily setting `preserveWhitespace: true` in your component and seeing whether the extraction looks better.

**Comment by bougnat12** [comment] 2020-11-17 10:14
@kamilchlebek Thanks. I will be patient...

@petebacondarwin We always had forced `"preserveWhitespaces": false` in our tsconfig.json file so I don't know what to do without any risk.

I have corrected the signaled warnings: it was mainly `<button>`, `<th>` or `<td>` markers so it's ok to write them on a same line.

**Comment by petebacondarwin** [comment] 2020-11-17 10:27
> We always had forced "preserveWhitespaces": false in our tsconfig.json file so I don't know what to do without any risk.

I was not suggesting this as a workaround. It was purely to help you check that your problem was the same one as reported (and fixed) here.

**Comment by bougnat12** [comment] 2020-11-17 10:36
> The workaround for you is to create a new `tsconfig.extract.json` that sets `target: es2015`. Then update the `angular.json` file to have a new build configuration that references this tsconfig and finally update the `extract-i18n` section in that file to use this new build config.
> 
> If this workaround is not usable for you please open a new issue so that I can track the work for fixing it.

I have created a new `tsconfig.i18n.json` file that sets `target: es2015`. But I don't understand how to update the `angular.json`file. Could you insert an example please?

I tried:

```json
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "mad-web-ui:build",
            "tsConfig": "src/tsconfig.i18n.json"
          }
        },
```

But it failed. I think I miss a step but I don't know how to correct this...

**Comment by petebacondarwin** [comment] 2020-11-17 10:58
I think you have to create a new build target first, with the new tsconfig. And then reference this new target in your `browserTarget` property of your `extract-i18n` target.

**Comment by bougnat12** [comment] 2020-11-18 14:14
> I think you have to create a new build target first, with the new tsconfig. And then reference this new target in your `browserTarget` property of your `extract-i18n` target.
@petebacondarwin Thanks for your directions! it was a little bit heavy (in my head at least ;-)) but I succeeded.

Because we cannot use es2015 target for our production build it's the best solution for us.

Best regards.

**Comment by bougnat12** [comment] 2020-11-18 14:23
> > We always had forced "preserveWhitespaces": false in our tsconfig.json file so I don't know what to do without any risk.
> 
> I was not suggesting this as a workaround. It was purely to help you check that your problem was the same one as reported (and fixed) at #39671.

It's not the same bug as I tried to explain. Spaces issues are solved by correcting my HTML code.

My main and blocking issue is about the **INTERPOLATION** part:

I made some tests with last Angular 11 and I always have bad translation:

```xml
    <unit id="MAD.confirmDeleteModalMsg">
      <segment>
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="e {{uiName"/>?
</source>
      </segment>
    </unit>
```

for the original text to translate:

```html
<mad-modal-confirm i18n="@@MAD.confirmDeleteModalMsg" i18n-title="@@psSetupPanel.modalConfirmTitle" title="Delete Power Supply" size="md" id="deletePowerSupplyButton" (closed)="deletePowerSupplyConfirm($event)">
  Confirm delete {{uiName}}?
</mad-modal-confirm>
```
Previously I had this result (as explained at the top of this issue):

```xml
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="{uiName}}?"/>?
```

The `?` character was duplicate and inside the **INTERPOLATION** `disp` part. It can be parsed but the translation asset is incorrect.

and now with Angular 11, I have:

```xml
        <source> Confirm delete <ph id="0" equiv="INTERPOLATION" disp="e {{uiName"/>?
```

Now, the `disp` part is incorrect and cannot be parsed correctly by my translation tool **Loco**. This is worse.

**Comment by petebacondarwin** [comment] 2020-11-18 14:37
Yes, I believe your invalid `disp` is caused by the same problem as #39671. It is the whitespace before the "Confirm delete" that is causing the the `disp` content become misaligned.

**Comment by bougnat12** [comment] 2020-11-19 09:23
> Yes, I believe your invalid `disp` is caused by the same problem as #39671. It is the whitespace before the "Confirm delete" that is causing the the `disp` content become misaligned.

OK thanks. I understand. It's due to the HTML code indentation most of the time. I'll try to correct simple cases as to go ahead:

```html
<button>
  LABEL
</button>
```

with

```html
<button>LABEL</button>
```

But maybe it will remain some complicated cases. Thanks for your help.

**Comment by petebacondarwin** [comment] 2020-11-19 09:56
Hopefully #39717 will resolve this for you @bougnat12
