### ISSUE TITLE
`@if` block inside the regular HTML element with `i18n` attribute breaks compilation

### ISSUE THREAD

**Issue by nyannyacha** [angular/angular#52767] opened 2023-11-10 02:07 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Consider the template below.

app.component.html
```html
<!-- OK -->
<span i18n>
  meow
  <span *ngIf="true; else elseBlock">meow?</span>
  <ng-template #elseBlock>
    <span>meow!</span>
  </ng-template>
</span>

<!-- Not OK -->
<span i18n>
  meow
  @if(true) {
    <span>meow?</span>
  } @else {
    <span>meow!</span>
  }
</span>
```

When the `@if` block is inside a regular HTML element having an `i18n` attribute, it will abort compilation with the following error message:
```
✘ [ERROR] Angular compilation emit failed. [plugin angular-compiler]

  TypeError: Cannot read properties of undefined (reading 'startName')
      at file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26452:37
      at Array.forEach (<anonymous>)
      at I18nContext.reconcileChildContext (file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26451:28)
      at TemplateDefinitionBuilder.i18nEnd (file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26948:30)
      at TemplateDefinitionBuilder.buildTemplateFunction (file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26748:18)
      at file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:27275:50
      at file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26729:60
      at Array.forEach (<anonymous>)
      at TemplateDefinitionBuilder.buildTemplateFunction (file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:26729:33)
      at compileComponentFromMetadata (file:///workspaces/barebones-nodejs/ng17/node_modules/@angular/compiler/fesm2022/compiler.mjs:28917:60)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0
Node: 18.18.2
Package Manager: npm 9.8.1
OS: linux x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by nyannyacha** [comment] 2023-11-10 08:23
Looking at `TemplateDefinitionBuilder`, It is looking good until drilled down to the `visitIfBlock`.

But here
https://github.com/angular/angular/blob/94096c6ede67436a349ae07901f2bb418bf9f461/packages/compiler/src/render3/view/template.ts#L1178-L1179
https://github.com/angular/angular/blob/94096c6ede67436a349ae07901f2bb418bf9f461/packages/compiler/src/render3/view/template.ts#L948-L960

and again here
https://github.com/angular/angular/blob/94096c6ede67436a349ae07901f2bb418bf9f461/packages/compiler/src/render3/view/template.ts#L287-L288


If my understanding is correct, `visitIfBlock` eventually makes a child builder, and the parent builder had its i18n context, but it invoked the `createEmbeddedTemplateFn` method without any of the i18n meta variables.

I think this could be a problem 🧐
What do you think about it? 😋

**Comment by pkozlowski-opensource** [comment] 2023-11-10 08:25
cc @crisbeto

**Comment by zip-fa** [comment] 2023-11-12 07:30
https://github.com/angular/angular/issues/52540

this is duplicate of my issue

**Closed** 2023-11-20 16:59 UTC
Labels: state: has PR, area: compiler, core: control flow
