### ISSUE TITLE
Can't resolve all parameters for ApplicationModule: (?).

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular#27531] opened 2018-12-07 05:34 UTC
# 🐞 bug report

### Description

This is my github sample repository [ [https://github.com/SridharSathaSivam/stackblitz-test]](https://github.com/SridharSathaSivam/stackblitz-test) which has simple image as a template.

when i try to run this in a stacblitz sample it throws this error: 

>  Unhandled Promise rejection:
> Can't resolve all parameters for ApplicationModule: (?).
> ; Zone:
> <root>
> ; Task:
> null
> ; Value:
> Error: Can't resolve all parameters for ApplicationModule: (?).
> Error: Can't resolve all parameters for ApplicationModule: (?).
> at syntaxError (https://vbwigzjp.github.stackblitz.io/turbo_modules/@angular/compiler@7.0.4/bundles/compiler.umd.js:2617:21)
> at CompileMetadataResolver._getDependenciesMetadata 

## 🔬 Minimal Reproduction

step1:  open stackblitz link [[ https://stackblitz.com/]( https://stackblitz.com/) ]

step2: add my repolink to that [[https://stackblitz.com/github/SridharSathaSivam/stackblitz-test]](https://stackblitz.com/github/SridharSathaSivam/stackblitz-test)

step3: Run sample  the you will get that error

**Comment by alexzuza** [comment] 2018-12-07 05:52
https://twitter.com/yurzui/status/1055491854488215552

**Comment by kumaresan-subramani** [comment] 2018-12-07 05:55
Hi @alexzuza , i have tried adding 

> `import 'core-js/es7/reflect';`

But  it wont work. is there any option

**Comment by alexzuza** [comment] 2018-12-07 05:57
> 
> 
> Hi @alexzuza , i have tried adding
> 
> > `import 'core-js/es7/reflect';`
> 
> But it wont work. is there any option

https://stackblitz.com/edit/github-5xs2qx?file=src/app/app.component.ts

**Comment by kumaresan-subramani** [comment] 2018-12-07 06:00
Hi @alexzuza , Thank you so much for this. i have tried wrongly

**Comment by kumaresan-subramani** [comment] 2018-12-07 06:00
Why i have add this?
is there any answer for this?

**Comment by alexzuza** [comment] 2018-12-07 06:07
This issue is duplicate for https://github.com/stackblitz/core/issues/758. 
Maybe Angular and Stackblitz teams need to decide on which side it should be fixed

**Comment by kumaresan-subramani** [comment] 2018-12-08 16:01
Hi @alexzuza , but still my sample is not wokring fine.

**My issue issue is:**
I have render one image in my sample
If i run  my sample locally, my sample working fine [ image rendered correctly]

> If i run sample like below steps:

_step1: open stackblitz link [ https://stackblitz.com/ ]

step2: add my repolink to that [https://stackblitz.com/github/SridharSathaSivam/stackblitz-test]

step3: Run sample the you will get that error_

> my sample is not working fine which means image is not loading properly

**Comment by kumaresan-subramani** [comment] 2018-12-09 05:01
Hi All,
anyone respond my question?

**Comment by alexzuza** [comment] 2018-12-09 05:11
> My sample is not working fine which means image is not loading properly

@kumaresan-subramani 
This issue has nothing to do with Angular. Please follow this issue https://github.com/stackblitz/core/issues/72

**Comment by kumaresan-subramani** [comment] 2018-12-09 05:15
Hi @alexzuza , my sample working fine in local but why it is not in stackblitz

**Comment by alxhub** [comment] 2018-12-11 23:00
This issue is on the Stackblitz side.

**Closed by alxhub** 2018-12-11 23:00 UTC
Labels: comp: core & compiler, type: bug/fix

**Comment by YogiHbK** [comment] 2019-04-23 14:04
> > Hi @alexzuza , i have tried adding
> > > `import 'core-js/es7/reflect';`
> > 
> > 
> > But it wont work. is there any option
> 
> https://stackblitz.com/edit/github-5xs2qx?file=src%2Fpolyfills.ts

its working thanks

**Comment by akopchinskiy** [comment] 2019-07-16 13:10
`import 'core-js/es7/reflect';`
It's not working.
`Module not found: Error: Can't resolve 'core-js/es6/reflect'`
`Module not found: Error: Can't resolve 'core-js/es7/reflect'`

`core-js  v3.1.4`

**Comment by ElYoussif** [comment] 2019-07-17 13:11
> > > Hi @alexzuza , i have tried adding
> > > > `import 'core-js/es7/reflect';`
> > > 
> > > 
> > > But it wont work. is there any option
> > 
> > 
> > https://stackblitz.com/edit/github-5xs2qx?file=src%2Fpolyfills.ts
> 
> its working thanks



> @sireyogie
> 
> `import 'core-js/es7/reflect';`
> It's not working.
> `Module not found: Error: Can't resolve 'core-js/es6/reflect'`
> `Module not found: Error: Can't resolve 'core-js/es7/reflect'`
> 
> `core-js v3.1.4`

Add this in your polyfills.ts file
import 'core-js/es/reflect';

**Comment by briosheje** [comment] 2019-08-09 14:45
Using `core-js` 3.2.0, angular 8.2.1 and polyfilling these:

```ts
// Internet Explorer 9 support
import 'ie-shim';

// IE9, IE10 and IE11 requires all of the following polyfills.
import 'core-js/es/symbol';
import 'core-js/es/object';
import 'core-js/es/function';
import 'core-js/es/parse-int';
import 'core-js/es/parse-float';
import 'core-js/es/number';
import 'core-js/es/math';
import 'core-js/es/string';
import 'core-js/es/date';
import 'core-js/es/array';
import 'core-js/es/regexp';
import 'core-js/es/map';
import 'core-js/es/weak-map';
import 'core-js/es/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

// Evergreen browsers require these.
import 'core-js/es/reflect';
```

I still encounter the issue, it seems there might be some limit scenarios where just importing reflect won't work, not sure whether I'm the only one encountering the issue.

**Comment by akopchinskiy** [comment] 2019-08-09 15:02
@briosheje Nobody uses IE nowadays.

**Comment by briosheje** [comment] 2019-08-09 15:19
@akopchinskiy is that related to the issue in any way? However, as a side note, some people still uses IE, in my case some customer does, but that's not the issue, the issue is that upgrading from angular 7 to angular 8 is being slightly harder than expected (to me), since I can't come up with a solution for that issue.

It's probably rather related to webpack, it's just to mention that the proposed solution might not work in all the cases, since in my case reflect is required, but I still get the error.

**Comment by philly-vanilly** [comment] 2019-08-23 14:26
I am getting this in a lib, not an app. It doesn't even have a polyfills file to add the polyfill to. I wish the error message was more descriptive
