### ISSUE TITLE
ng-content inside ngFor

### ISSUE THREAD

**Issue by Rabaia** [angular/angular#8828] opened 2016-05-25 08:42 UTC
Hello,

I'm using ng-content inside ngFor like this
` <li template="ng-for #item of listRows">
              <ng-content></ng-content>
          </li>`
but only one content appears . and as i saw in issue #4631 that i can use **ng-for-template** but i cant find it in angular2 r.c .  So is there a solution

**Comment by zoechi** [comment] 2016-05-25 09:57
directive names are case sensitive since quite some time. Use `ngForTemplate`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

Please close the issue because it is not a bug report or feature request.

**Comment by Rabaia** [comment] 2016-05-25 10:11
It's not working, see the attached photo
![capture](https://cloud.githubusercontent.com/assets/19566730/15536498/371f8d88-227a-11e6-834f-ee7c199859a4.PNG)

**Comment by zoechi** [comment] 2016-05-25 10:19
To me this still looks like a support question which should be discussed in another channel. I think a Plunker would be a good idea as well.

**Closed** 2016-05-25 12:48 UTC
