### ISSUE TITLE
Reactive Forms : array property being converted to object with form builder

### ISSUE THREAD

**Issue by trichetriche** [angular/angular#24538] opened 2018-06-15 13:30 UTC
## I'm submitting a...
<pre><code>[X] Bug report</code></pre>

## Current behavior

I have a payload : 

 

    payload = {
      id: 1,
      name: 'This is the payload',
      children: [
        { id: 1, name: 'Child 1' }
      ],
    };

I create a form group out of that : 

 

    this.form = this.fb.group(this.payload);

I then display the value of the form : 

 

    {{ form?.value | json }}

And the result is : 

 

    { "id": 1, "name": "This is the payload", "children": { "id": 1, "name": "Child 1" } }

As you can see, the `children` property went from an array, to an object.

## Expected behavior

I would like my array property to stay an array property.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-3hsfxf?file=src%2Fapp%2Fapp.component.html

## What is the motivation / use case for changing the behavior?

Well it kind of seems obvious ... I would like my model not to change, and if it does, I would like to know how to revert it. 

## Environment

6.0.0 on the stackblitz, but previous versions are affected

**Comment by kara** [comment] 2018-07-03 22:22
Dupe of https://github.com/angular/angular/issues/24182

**Closed by kara** 2018-07-03 22:22 UTC
Labels: comp: forms
