### ISSUE TITLE
Suggest feature: "ngForIn"

### ISSUE THREAD

**Issue by SoilChang** [angular/angular#16430] opened 2017-04-29 05:59 UTC
I'm submitting a "feature request"

FEATURE REQUEST: enable support "ngForIn"

currenly, *ngFor can only support "of" keyword which loops array like iterables. "in" keyword will throw a parsing error.

**What is the motivation / use case for changing the behavior?**
1.  "in" keyword is supported natively in JavaScript to iterate own (not inherited) property in objects. 
for example:  
  ```
   for(let key in object){
         console.log( object[key] );
    }
```

2.  Using object key to store information rather than array will achieve O(1) lookup time. If the order of the information does not matter, object is arguably better data structure in many cases. However, if we return JSON that stores data purely in object format, we cannot use ngFor to iterate it, at least not before we convert. 

3. This concept has been found in firebase
e.g.
```
{
    countries:["USA", "Canada"] 
}  

```
*ngFor="let  country of countries"
<p>  {{country }}  </p>   
 .......(current support)

==>>
```
{
    countries:{
         USA:true,
         Canada: true
   }
}
```

*ngFor="let country in countries"
<p>{{ country }}</p>
 ..... (requested feature)

These 2 will print exactly the same thing.

**Comment by trotyl** [comment] 2017-04-29 06:17
Duplicate of https://github.com/angular/angular/issues/2246 , and https://github.com/angular/angular/pull/11319 may be the solution being considered currently.

**Comment by pkozlowski-opensource** [comment] 2017-04-29 06:50
Thnx @trotyl , this is indeed a duplicate of the mentioned issues.

**Closed by pkozlowski-opensource** 2017-04-29 06:50 UTC
