### ISSUE TITLE
formatDate returns date off by 1 year

### ISSUE THREAD

**Issue by jtneal** [angular/angular#59303] opened 2024-12-24 18:29 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

Passing a date of `12/31/2024` to `formatDate` results in a formatted date of `12/31/2025`.

![Image](https://github.com/user-attachments/assets/3f6dac9e-56c5-4c76-93b6-d4be392b3ca7)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-x4tkvpyp?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
n/a
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Found in v18 but reproduced in v19 as well.
```

**Comment by JoostK** [comment] 2024-12-24 19:42
Duplicate of #49861; `YYYY` is the week-numbering year, not the calendar year.

**Closed by JoostK** 2024-12-24 19:42 UTC
