### ISSUE TITLE
Custom errors thrown in resolvers lose custom type (type is just Error in error handler)

### ISSUE THREAD

**Issue by itslenny** [angular/angular#25081] opened 2018-07-25 00:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Errors thrown in resolver lose their custom type. If I throw a `new MyCustomError('blah')` (extends Error) in the resolver it winds up being of type `Error` by the time it hits the custom error handler.

I can copy and paste the throw code to a component or service and it works as expected (`error instanceof MyCustomError === true`), but if I throw it from within the resolver the type is `Error` when it makes it to the error handler.

In creating the repro I also realized that errors thrown in a components constructor have the same behavior (they lose their custom type and revert to a default `Error` type)

## Expected behavior

An error thrown in the resolver should maintain it's type and arrive at the error handler as it was created / thrown.

## Minimal reproduction of the problem with instructions

[https://stackblitz.com/edit/angular-gitter-vvgys6](https://stackblitz.com/edit/angular-gitter-vvgys6)

## What is the motivation / use case for changing the behavior?

Ability to pass custom error objects and have them arrive at the error handler intact seems pretty important.

## Environment

<pre><code>
Angular version: 6.0.2

Browser:
- [ X ] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.2.0
- Platform:  OSX

**Comment by JiaLiPassion** [comment] 2018-07-25 00:43
@itslenny, this is a known issue, you can import `zone.js/dist/zone-error` to fix this one.

**Comment by JiaLiPassion** [comment] 2018-07-25 00:56
@itslenny, sorry I gave you the wrong information, the reason the `2nd page`, the error will not be `MyCustomError`, because if error is thrown in `resolve` stage, it will be a `uncaught promise rejection`, so the error will be wrapped, you can access the original error by `error.rejection`.

I have updated the `stackblitz` here, https://stackblitz.com/edit/angular-gitter-yorqdk?file=app%2Fglobal-error-handler.ts, it will work now.

**Comment by trotyl** [comment] 2018-07-25 01:43
Duplicate of https://github.com/angular/angular/issues/21964

**Comment by vicb** [comment] 2018-07-25 03:57
Closing as duplicate (thanks @trotyl)

**Closed by vicb** 2018-07-25 03:57 UTC
