### ISSUE TITLE
[Feature] Specify Custom Element Tags in Schemas

### ISSUE THREAD

**Issue by lucasbasquerotto** [angular/angular#23995] opened 2018-05-18 13:35 UTC
## I'm submitting a...

<pre><code>[x] Feature request</code></pre>

## Current behavior

Today, when using custom elements (webcomponents) in Angular **it will complain that it is not an Angular element**, to add in a `NgModule` or use [CUSTOM_ELEMENTS_SCHEMA](https://angular.io/api/core/CUSTOM_ELEMENTS_SCHEMA).

I can make it work with `CUSTOM_ELEMENTS_SCHEMA`, but I then **I don't receive validation errors when I type component names wrong** (even angular ones). _The price to pay is just too high._

## Expected behavior

I ask for a **feature to allow defining specific custom elements**, like:

```
export const MY_SCHEMAS = CUSTOM_ELEMENTS_SCHEMA.for([
    'my-component-1',
    'my-component-2',
    'my-component-3',
]);
```

and use it in any `NgModule` like:

```
@NgModule({
    ...
    schemas: [MY_SCHEMAS],
})
```

Then, if I write a custom component name like `my-conponent-1`, **I would receive an error**, just like what happens now with angular components.

**It would also validate angular components names** (just like it already does today, but even when using custom elements).

## What is the motivation / use case for changing the behavior?

Receive validations when using custom elements when writing in the Editor/IDE (with red squiggles) and also when building (with AOT), just like it validates today when not using custom elements.

## Environment

<pre><code>Angular version: 6</code></pre>

## Other Information:

There was a similar discussion in the following issue #11251 (although the issue was not about it specifically).

In this post (in the issue above):

https://github.com/angular/angular/issues/11251#issuecomment-244255512

a member from the Angular Team said:

> Element declared in your NgModule schemas prop - support is rather limited for now and this mostly offer a all or nothing filter. It will be improve in the next releases.

(later there are more posts saying about it, to allow a finer grained control over schemas and the like, including the last post, before the issue was locked)

But **the post is from 2016**, almost 2 years ago. I tried to find other issues about it (like some issue that is tracking this feature) but haven't found any.

**So, will this be implemented in Angular? Can I have some sort of feedback about how things are going related to this implementation?**

In any case, thanks for the great work! [Angular6](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4) had many great features, like tree-shakeable providers and using RxJS v6. Waiting for Ivy now :)

**Comment by trotyl** [comment] 2018-05-19 06:04
Duplicate of https://github.com/angular/angular/issues/12045

**Comment by pkozlowski-opensource** [comment] 2018-05-19 06:17
Yep, this is duplicate of #12045 - thnx @trotyl !

**Closed by pkozlowski-opensource** 2018-05-19 06:17 UTC
