### ISSUE TITLE
RequestAnimationFrame breaks PWA

### ISSUE THREAD

**Issue by Laurensvdmaas** [angular/angular#24468] opened 2018-06-13 12:02 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When running an app with requestAnimationFrame, service worker won't be loaded.

## Expected behavior

Service worker to load.

## Minimal reproduction of the problem with instructions
1. Checkout https://github.com/Laurensvdmaas/pwa-bug.git (branch: bug)
2. npm install
3. npm run build:ssr && npm run serve:ssr

In app.component.ts is a function `frame` if you turn this off and rerun the steps above you can see the service worker will load correctly.

## What is the motivation / use case for changing the behavior?
Running animations with requestAnimationFrame is crucial.

## Environment

<pre><code>
Angular version: 6.0

Browser:
- [x] Chrome (desktop) version 67

 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Mac

Others:

</code></pre>

**Comment by Laurensvdmaas** [comment] 2018-07-27 14:21
Small update on the bug:
I'm using an own custom function to determine if it's browser/server (was too lazy to import platform ID etc etc):
`return typeof window != 'undefined'`

Using Angular's recommended way if determining browser/server works, so this issue can be closed!

**Comment by Laurensvdmaas** [comment] 2018-07-27 14:24
Update on the bug:
Also doesn't work with `setInterval`

**Comment by gkalpak** [comment] 2018-07-27 14:56
This happens because the app never "stabilizes" (i.e. there are always async tasks pending, captured via Zones). (The SW will wait for the app to stabilize, before registering itself.)

This is essentially a duplicate of #20970. See there for more details and possible workarounds.
There is also a PR that adds support for different registration strategies (but not sure what its status is): #21842.

**Closed by gkalpak** 2018-07-27 14:56 UTC
Labels: comp: animations, freq1: low, severity3: broken, type: bug/fix
