### ISSUE TITLE
distribute bundle with dependencies included

### ISSUE THREAD

**Issue by yfain** [angular/angular#2675] opened 2015-06-22 14:05 UTC
I have an app that is pre-transpiled into ES5 with TypeScript compiler.  But unless I include the traceur-runtime in the html file below the app gives a runtime error "$traceurRuntime is undefined". The code in angular2.dev.js (Alpha 27) uses  $traceurRuntime in multiple places (e.g. line 7250), but it should include traceur internally, if needed,  and not force me to do it.

```
<!DOCTYPE html>
<html>
  <head>
    <title>Bringing Together Typescript and Angular 2</title>
    <script src="https://github.jspm.io/jmcriffey/bower-traceur-runtime@0.0.87/traceur-runtime.js"></script>
    <script src="https://jspm.io/system@0.16.js"></script>
    <script src="https://code.angularjs.org/2.0.0-alpha.27/angular2.dev.js"></script>
  </head>
  <body>
    <hello-world></hello-world>
    <script>
      System.config({
        baseURL: './js/'
      });

      System.import('main');

    </script>
  </body>
</html>
```

angular2.dev.js uses traceur runtime internally and forces app developer to include it in the app.

**Comment by jeffbcross** [comment] 2015-06-22 20:32
Agreed, it would be nice to have a bundle which explicitly includes dependencies. FWIW the `$traceurRuntime` dependency will go away when #2335 is resolved, but other polyfills will still be required (Map, Promise, etc). In addition to that, we currently have a dependency on `RxJS` for observables, which is included in the angular2.dev.js bundle. 

Here are the use cases and goals to support as I see it:
 * Provide an easy path to quickly get started without worrying about what dependencies need to be included (particularly useful for one-off code samples and reproductions, like a [plunk](https://plnkr.co)
 * Allow using own, compatible version of libraries like RxJS alongside the dev bundle, as well as omit polyfills if target environment doesn't require them.
 * Keep byte size of default dev bundle low, since, realistically, it will probably be used in production

Proposal:
 * angular2.dev.js bundle contains Angular bundled without dependencies (No Traceur, no polyfills, no Rx)
 * angular2-with-dependencies.dev.js bundle contains Angular bundle plus required polyfills and Rx.
 * All examples in official docs will use the angular2-with-dependencies.dev.js

@alexeagle since you're working on bundle this week, do you have any thoughts on this?

(Changed issue name from "angular2.dev.js forces me to include traceur in my app", to "distribute bundle with dependencies included")

**Comment by mhevery** [comment] 2015-06-30 11:23
The final distribution strategy is still very much in flux, and should solidify as we get closer to release. 

I am going to close this as it is a known issue which will be addressed later as part of the final release design.

**Closed by mhevery** 2015-06-30 11:23 UTC
Labels: comp: build/dev-productivity, P4: nice to have, type: feature
