### ISSUE TITLE
BrowserAnimationsModule 6.X fail on Android 4.4 and Android 5.0

### ISSUE THREAD

**Issue by jpierront** [angular/angular#25563] opened 2018-08-18 20:59 UTC
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
JS errors occurs  on Android 4.4 and 5.0.
* TypeError: Cannot read property 'trim' of undefined at applyKeyframeAnimation
* Cannot read property 'split' of undefined at removeKeyframeAnimation

## Expected behavior
It should works. (Like with Angular 5.X)

## Minimal reproduction of the problem with instructions
Just try to animate something.

* https://stackblitz.com/edit/angular-animation-load-data-rxtbca => Click on "Go to two"
* https://material.angular.io/components/dialog/overview => Pick One" + Try to close the popup.

## What is the motivation / use case for changing the behavior?
It should works on this device type.

## Environment

<pre><code>
Angular version: 6.1.3

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 4.4 / 5.0
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.4.0
- Platform:  Android

Others:
There is no crash when you use NoopAnimationsModule instead of BrowserAnimationsModule ... but there is no animation ;-)
</code></pre>

**Comment by e01010100** [comment] 2018-08-23 17:54
Likely related to issue #24094

**Comment by pleinonen** [comment] 2018-11-19 05:42
I see hundreds of these exceptions weekly in our app in production. In addition to above mentioned Android devices, these old browsers seem to have this problem (in parenthesis number of crashes last 5 days):

- Chrome 36.0.1985.534 (62)
- Chrome 42.0.2311.111 (2)
- Chrome 39.0.2171.93 (11)

**Comment by JoostK** [comment] 2020-10-25 19:25
Closing as duplicate of #24094.

**Closed by JoostK** 2020-10-25 19:25 UTC
Labels: P2, comp: animations, freq4: critical, regression, type: bug/fix
