### ISSUE TITLE
IVY Problem - ngModel not working properly

### ISSUE THREAD

**Issue by fkolar** [angular/angular#33023] opened 2019-10-07 10:02 UTC
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x ] serve

```

### Is this a regression?
YES

### Description

After migrating to IVY some of the component stopped working or have weird behavior. where we get `ngModel' since it isn't a known property of 'fd-time-picker`

Normally you make sure that you have imported corect Module but this is not the case as when turning IVY off it works. 

What is strage, when using this custom component which produces the error:

```html
<fd-time-picker [compact]="true" [ngModel]="time" style="width: 300px;">
</fd-time-picker>
```

Removing `compact` or `style` binding from the template removes also the problem. So there must be some conflict. 

## 🔬 Minimal Reproduction

https://github.com/JKMarkowski/angular-ivy-issue-example

## 🔥 Exception or Error
<pre><code>
Template error: Can't bind to 'ngModel' since it isn't a known property of 'fd-time-picker'.
createUnknownPropertyError — core.js:12759
validateAgainstUnknownProperties — core.js:12698
elementPropertyInternal — core.js:12603
ɵɵproperty — core.js:19773
AppComponent_Template
executeTemplate — core.js:12177
checkView — core.js:13615
componentRefresh — core.js:13359
refreshChildComponents — core.js:11858
refreshDescendantViews — core.js:11757
renderComponentOrTemplate — core.js:12148
tickRootContext — core.js:13507
detectChangesInRootView — core.js:13543
detectChanges — core.js:15178
tick — core.js:41055
_loadComponent — core.js:41106
bootstrap — core.js:41029
forEach
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.8
Node: 11.0.0
OS: darwin x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cli                      8.3.8
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by trotyl** [comment] 2019-10-07 10:14
Please check Ivy issue in `@next` version rather than `@latest`.

**Comment by JKMarkowski** [comment] 2019-10-07 10:36
Hi @trotyl, in the `next` version it works ok.

**Comment by AndrewKushnir** [comment] 2019-10-08 01:05
@fkolar could you please confirm if the issue is resolved with the most recent @next version (if so, we'll close the ticket)? Thank you.

**Comment by fkolar** [comment] 2019-10-08 06:03
As @JKMarkowski  confirmed it does work in version @next ( 9.0.0-next.8)

**Comment by pkozlowski-opensource** [comment] 2019-10-08 06:15
OK, we can close this one then!

**Closed by pkozlowski-opensource** 2019-10-08 06:15 UTC
Labels: comp: core

**Comment by fkolar** [comment] 2019-10-08 06:23
Does it mean we are not goign to fix this in the version 8. @pkozlowski-opensource ? 

The problem is still there ? We cannot close this! 

You have documentataion about this in Angular 8. 
https://angular.io/guide/ivy.

Why would you guide users to opt-in IVY and letting them to jump into something that has problems.

**Comment by pkozlowski-opensource** [comment] 2019-10-08 06:26
> Does it mean we are not goign to fix this in the version 8

Yep, sorry, the fix will be available only in version 9.

**Comment by fkolar** [comment] 2019-10-08 06:28
Maybe we should update documentation?

**Comment by montella1507** [comment] 2019-11-07 07:18
Documentation should be updated, this:

"To preview Ivy, use @angular/core@next version of Angular (8.1.x), rather than @angular/core@latest (8.0.x), as it contains all the latest bug fixes and improvements."

is terrible missleading. Fixes for IVY has been never ported back.
