### ISSUE TITLE
404 on https://angular.dev/versions

### ISSUE THREAD

**Issue by RustyF** [angular/angular#53777] opened 2024-01-03 11:04 UTC
### Describe the problem that you experienced

404

### Enter the URL of the topic with the problem

https://angular.dev/versions

### Describe what you were looking for in the documentation

To view Angular version compatibility

### Describe the actions that led you to experience the problem

Clicking link from https://angular.dev/tools/cli/setup-local  

### Describe what you want to experience that would fix the problem

Goes to right page

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/277341/ed997f0c-1d11-4374-8ab0-51a41cf248e7)

**Comment by RustyF** [comment] 2024-01-03 11:05
I think the link should be https://angular.dev/reference/versions

**Comment by JoostK** [comment] 2024-01-03 11:19
Thanks for the report, this is a duplicate of #52562 for which the fix is pending deployment.

**Closed by JoostK** 2024-01-03 11:19 UTC
