### ISSUE TITLE
ngClass error

### ISSUE THREAD

**Issue by SoeLTun** [angular/angular#15533] opened 2017-03-27 20:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
if more than 10 conditions in [ngClass] object, angular throw errors same as *ngFor = "let i of [1, 2, 3, .......11]"
**Expected behavior**
it should handle without throwing error

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
try to validate when parsing the template without defining the object  in .ts file.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
 
* **Language:**TypeScript ES5
* **Node (for AoT issues):** `node --version` =   v6.2.0

**Comment by DzmitryShylovich** [comment] 2017-03-27 20:14
Duplicate of https://github.com/angular/angular/issues/12233

**Comment by pkozlowski-opensource** [comment] 2017-03-27 20:35
It is duplicate of #12233 indeed, thnx @DzmitryShylovich

**Closed by pkozlowski-opensource** 2017-03-27 20:35 UTC
