### ISSUE TITLE
Getting error while importing js file from assets folder and using in angular component  Angular 8.0.x

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular#31621] opened 2019-07-18 11:26 UTC
I have a external .js file which i downloaded and placed into my assets folder.
After following steps from [here](https://github.com/angular/angular-cli/wiki/1-x-stories-global-scripts), still no success.

Steps performed to add js file in angular project;
1) Adding relative path of js file  to script [] in angular.json

2) Creating typyings.d.ts under src folder  
declare var myJs: any;

3) Import in component
import * as myJs from 'myJs'

Getting error; undefined

Stakcblitz url: https://stackblitz.com/edit/angular-lollipop-chart
Github repo: https://github.com/narendrasinghrathore/angular-lollipop-chart

Regards

```
"dependencies": {
  "@angular/animations": "^8.1.2",
  "@angular/common": "^8.1.2",
  "@angular/compiler": "^8.1.2",
  "@angular/core": "^8.1.2",
  "@angular/forms": "^8.1.2",
  "@angular/platform-browser": "^8.1.2",
  "@angular/platform-browser-dynamic": "^8.1.2",
  "@angular/router": "^8.1.2",
  "@types/jasmine": "^3.3.13",
  "@types/jasminewd2": "^2.0.6",
  "@types/node": "^12.6.8",
  "d3": "^5.9.7",
  "rxjs": "^6.5.2",
  "tslib": "^1.10.0",
  "zone.js": "^0.9.1"
},
```

**Comment by trotyl** [comment] 2019-07-18 13:54
Duplicate of https://github.com/angular/angular-cli/issues/15115

**Closed** 2019-07-18 13:57 UTC
