### ISSUE TITLE
Error Template parse, <div> with <p>

### ISSUE THREAD

**Issue by languorous001** [angular/angular#7572] opened 2016-03-12 14:14 UTC
I don't no this is a bug, but I try to help.

`<div class="navbar-right">
        ................
</div>`

Using div is not error. But I try using tags p

`<p class="control">
       <div class="navbar-right">..........</div>
</p>
`

it error template parse: Unexpected closing tag "p".
I using bulma.io

**Comment by ericmartinezr** [comment] 2016-03-12 14:17
See https://github.com/angular/angular/issues/6648

**Comment by languorous001** [comment] 2016-03-12 14:29
thank a lot.

**Comment by pkozlowski-opensource** [comment] 2016-03-12 18:03
Closing as duplicate of #6648, thnx @ericmartinezr !

**Closed by pkozlowski-opensource** 2016-03-12 18:03 UTC
