### ISSUE TITLE
Implement Library import in Directive Processor

### ISSUE THREAD

**Issue by jrote1** [angular/angular#3226] opened 2015-07-23 15:11 UTC
When will the following method be implemented as it restricts the splitting up of code in Dart.

    Object visitPartOfDirective(PartOfDirective node) {
       // TODO(kegluneq): Consider importing [node.libraryName].
       logger.warning('[${assetId}]: '
           'Found `part of` directive while generating ${DEPS_EXTENSION} file, '
           'Transform may fail due to missing imports in generated file.');
       return null;
     }

**Comment by matanlurey** [comment] 2015-07-23 19:23
Closing as duplicate of #1817.

**Closed by matanlurey** 2015-07-23 19:23 UTC
