### ISSUE TITLE
Windows Build fails even in git bash

### ISSUE THREAD

**Issue by youssefsharief** [angular/angular#17894] opened 2017-07-01 05:58 UTC
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Windows fails when building build.sh

Cannot find module './src/common/angular1'
Cannot find module './src/common/downgrade_component'
Cannot find module './src/common/downgrade_injectable'.
Cannot find module './src/common/version'.
Cannot find module './src/static/upgrade_component'.
Cannot find module './src/static/upgrade_module'.

**Comment by wizarrc** [comment] 2017-07-02 18:07
Same here. I even tried downgrading node and npm to versions specified in the DEVELOPER.md doc, which btw are below LTS.

**Comment by wizarrc** [comment] 2017-07-02 18:13
May be related to #16846 where it talks about build.sh requires full Linux environment.

**Comment by wizarrc** [comment] 2017-07-02 19:34
A workaround would be to:
1. navigate to `angular\packages\upgrade\static>` in command prompt
2. rename `src` to something like `src.old`
3. create symlink `mklink /J "src" "..\src"`

Step 3 requires administrator elevation except for later version of Windows 10 I believe.

I haven't figured out how to add that to the `create-symlinks.sh` scripts file yet. Shouldn't be too hard though.

That got me a bit further.

**Comment by kumvem** [comment] 2017-09-05 02:36
@wizarrc Did you solve the build issue? I followed similar steps to solve build issues. stuck in the following warning message. 

WARN: Side effects in initialization of unused variable Renderer2Interceptor [C:/kumaran/open-source/angular/angular/dist/packages-dist/core/bundles/core.umd.js:5369,4]
/c/kumaran/open-source/angular/angular/dist/packages-dist/core/bundles/core.umd.js.map
/c/kumaran/open-source/angular/angular/dist/packages-dist/core/bundles/core-testing.umd.js
WARN: Side effects in initialization of unused variable pendingTimers [C:/kumaran/open-source/angular/angular/dist/packages-dist/core/bundles/core-testing.umd.js:452,8]

**Comment by wizarrc** [comment] 2017-09-05 04:49
@kumvem never got it to work, I gave up for now, hoping others could startup where I failed.

**Comment by snerks** [comment] 2017-09-17 15:31
I followed the steps provided by @wizarrc, above (thanks!), with similar results.

As an additional step, I tried the suggestion, in #12454, to remove a call to `grep` in `build.sh`:

Search for the line:
`) 2>&1 | grep -v "as external dependency"`

_In my build.sh file, it was near line 440._

Truncate the line, to remove the `grep` call, such that it now reads:

`) 2>&1`

Launch the `MINGW64` version of `bash.exe` as Administrator:
Navigate to the project root folder
`./build.sh`

Takes a while - but the build completes.

I do not know if there is a negative effect caused by removal of the `grep` call.

**Comment by StephenFluin** [comment] 2018-12-28 20:05
We definitely want to do better for Windows users. If you've been following along, things have gotten better over the last few months (fewer / different types of errors), but there's still more to go before our Windows support for building Angular is on par with Linux/Mac. Currently we're working on migrating more of our build and test infrastructure into being managed by Bazel so that it relies less on OS-specific binaries and packages, but we're not there yet.

**Comment by manklu** [comment] 2018-12-29 17:57
@gauravmahto There are several free virtualization possibilities. Getting a linux environment until a native Windows build is supported, is no big deal.

**Comment by gauravmahto** [comment] 2018-12-30 06:07
@manklu I know that getting a virtual Linux environment is no big deal and that's exactly what I've been trying to accomplish from past 2 days. But you see that this is not about just setting up a Linux environment as one should be aware of intricacies of such environment; one that they are not familiar of. For e.g.: A windows may not be aware of how to be productive in a Linux environment and more importantly, the how to properly set up such environment so that they can easily build, test and debug the software.

What I'm trying to say is it is very hard for a Windows user to help and contribute to such an awesome framework just because it is not so easy to start with.

If anyone stumbles upon this thread, [here](https://github.com/gauravmahto/angular-docker) is what I was able to accomplish using Docker. Basically, now I'm able to build the Angular from sources but some tests are failing.

**Comment by gkalpak** [comment] 2018-12-30 09:31
I know [docs/DEVELOPER.md][1] is still mentioning `build.sh` and `test.sh`, but I am not sure they still work.
I am on Windows too and the way I build and test Angular is by using the [Windows Subsystem for Linux][2] and running the bazel commands described in [docs/BAZEL.md][3] (plus running [scripts/build-packages-dist.sh][4] if I need to build all packages as they are published to npm).

[1]: https://github.com/angular/angular/blob/master/docs/DEVELOPER.md
[2]: https://docs.microsoft.com/en-us/windows/wsl/install-win10
[3]: https://github.com/angular/angular/blob/master/docs/BAZEL.md
[4]: https://github.com/angular/angular/blob/master/scripts/build-packages-dist.sh

**Comment by gauravmahto** [comment] 2018-12-31 09:39
@gkalpak This is good information. A huge thanks to you for pointing me in the right direction. 🥇 

Also, thank you for adding the TODO item.

Wishing everybody a joyous happy new year.

**Comment by gkalpak** [comment] 2019-03-27 14:04
I am going to close this, since `build.sh` (the script mentioned originally) has since been removed and we have moved on to bazel.
There are probably more issues there, but they are different than the ones reported here. If you are running into problems with the bazel-based setup, please open a new issue.

**Closed by gkalpak** 2019-03-27 14:04 UTC
Labels: comp: build & ci, freq1: low, severity3: broken

**Comment by s-gbz** [comment] 2019-05-10 13:48
@gkalpak is `scripts/build-packages-dist.sh` supposed to work? It doesn't for me, because `command "." could not be found`

**Comment by gkalpak** [comment] 2019-05-13 09:27
No, I don't think it is supposed to work on Windows. We are in the process of adding Windows to the platforms we test on CI (see the [.codefresh/][1] directory for more details on what we have atm), but we have still work to do.

For now, I am either using [WSL][2] (which is easy to set up, but slow - but also [about to get much faster][3]) or a linux-based docker image to build and run bazel stuff.

[1]: https://github.com/angular/angular/tree/cb6dea473f7abaf1925ea34a3dfdbbfe36465689/.codefresh
[2]: https://docs.microsoft.com/en-us/windows/wsl/install-win10
[3]: https://devblogs.microsoft.com/commandline/announcing-wsl-2/

**Comment by gkalpak** [comment] 2019-05-13 09:29
In case it helps, this `Dockerfile` works for me:

```docker
FROM circleci/node:10-browsers
EXPOSE 4200 9876
USER root
RUN npm config --global set user root
```
