### ISSUE TITLE
Recursion of components (and circular imports) doesn't work in Ivy built libraries

### ISSUE THREAD

**Issue by darress** [angular/angular#35602] opened 2020-02-21 06:02 UTC
# 🐞 bug report

### Affected Package
Probably @angular/compiler

### Is this a regression?
The first version I detected the bug in is 9.0.0.

### Description
If I use recursion of components in an Ivy-built library, children will be not rendered.
It only appears when built with `--prod`.

Relevant code:
```typescript
@Component({
  selector: 'lib-recursive-list',
  template: `
    <lib-recursive-item *ngFor="let item of list" [model]="item"></lib-recursive-item>
  `,
  styles: []
})
export class RecursiveListComponent {
    @Input() list: RecursiveModel[];
}

@Component({
  selector: 'lib-recursive-item',
  template: `
    <div style="padding-left: 10px;">
        <div>{{model.name}}</div>
        <lib-recursive-list [list]="model.children"></lib-recursive-list>
    </div>
  `,
  styles: []
})
export class RecursiveItemComponent {
    @Input() model: RecursiveModel;
}
```

## 🔬 Minimal Reproduction
https://github.com/darress/angular9_lib_bugs/tree/recursion

Build the library with `ng build my-lib`, then build the app with `ng build`, it will work as expected.
However if built with `ng build --prod`, only the two parents will be rendered, not the children.

## 🔥 Exception or Error
No exceptions or errors.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.14.2
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cli                       9.0.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
Reproducable with Chrome and Firefox. Tested under Windows 10.

**Comment by alan-agius4** [comment] 2020-02-21 18:21
Note: —prod is a view engine built not an ivy built.

**Comment by darress** [comment] 2020-02-22 05:05
> Note: —prod is a view engine built not an ivy built.

Isn't --prod a shorthand for --configuration=production? Do I have something in my production configuration that makes it a view engine build? I intended to configure a production Ivy build. Can you please give me a link to a documentation where this is explained?

**Comment by alan-agius4** [comment] 2020-02-22 06:58
Sorry I misread the command I realised that the `—prod` option is being run on the application.

**Comment by alxhub** [comment] 2020-02-25 23:26
Reproduces as reported, and the cause is exactly what I expected to find.

1) when ngtsc compiles the library, the cycle detector rejects the import from `RecursiveItemComponent` for the `directiveDefs` of `RecursiveListComponent` as it would create a cycle.

2) instead, ngtsc deopts to a side-effectful `ɵɵsetComponentScope` call next to `MyLibModule`.

3) because the module is in a _library_, it gets built by CLI with a `package.json` which says `sideEffects: false`

4) Terser dutifully strips the `ɵɵsetComponentScope` call when processing the library code

5) One of the components is missing its `directiveDefs` at runtime.

I can think of only one real solution here: ngtsc needs to be modified to be okay with cycles externally, since external tooling can handle them. We would need to generate wrapped `directiveDef` arrays for _both_ components in this case, as we don't know in what order these files will be imported. This is pretty tricky to keep track of, and also has an impact on incremental build since the addition of a cycle could require the emit of new files.

A workaround is to set `sideEffects: true` in the library `package.json`, which tells the optimizer not to remove top-level calls (among other things).

**Comment by alxhub** [comment] 2020-02-25 23:41
Also @darress, thank you for the small and useful reproduction, it allowed me to verify what I thought was happening very easily.

**Comment by darress** [comment] 2020-02-26 04:26
Thank you @alxhub for the workaround, we can go full Ivy now!

**Comment by darress** [comment] 2020-02-26 09:43
If you have 2 components in the library, A and B, and you include B in A, but use a static method of A in B (or exported funtion/class/anything), the same problem occurs.

```typescript
// my-lib.component.ts
@Component({
  selector: 'lib-my-lib',
  template: `
      <lib-other></lib-other>
  `,
  styles: []
})
export class MyLibComponent{}
export function getSomething() {
  return `something`;
}

// other.component.ts
@Component({
  selector: 'lib-other',
  template: `
    <div>{{someInput}}</div>
  `,
  styles: []
})
export class OtherComponent {
  someInput = getSomething();
}
```

Reproduction is here:
https://github.com/darress/angular9_lib_bugs/tree/import_recursion

This is maybe a more minimal reproduction of the problem.

**Comment by Phil147** [comment] 2020-02-28 10:20
Hi @alxhub 
thanks for the great explanation. We are running into a similar problem and I think this might be related to this issue but I'd also like to get confirmation if this case is actually supported or it just worked by accident.

We are also suffering from dropped code and your solution to add `sideEffects: true` also helped here. You can find a reproduction sample here: https://github.com/Phil147/ng9-dropped-code

In Angular 8 you could mitigate circular dependency warnings by creating a base class, use it for the DI but still import the "real" class to use it for a type and cast the property, e.g.
```ts
import {TabGroupBase} from './tab-group-base';
import {TabGroupComponent} from './tab-group';

constructor(private tabGroup: TabGroupBase) {
   (tabGroup as TabGroupComponent).something = 'abc';
}
```
What I am not sure if this is intended behavior and supported?

Reproduction steps:
+ run `ng build mylib` to build the library with ivy (it's not happening with VE+ngcc)
+ run `ng serve webapp --prod` to run the prod build and serve the app
+ go to http://localhost:4200 and you will see a blank page.

If you look into the reproduction sample the problem happens when we introduced a third component (`tab-header-outlet`), that also imports `TabGroupBase` and `TabGroupComponent`, then suddenly the `TabGroupComponent` stopped working, that `ngFor` and `ngIf` in the template didn't work anymore. Could you have a look if this is related to the issue? If not I am happy to open a new one :)

What is really interesting if you build against the library source code and not the dist folder, this problem does not happen. I created a configuration that runs against the source code and uses the same configuration as `--prod` including the build optimizer
+ run `ng serve webapp -c fromsource`
+ go to http://localhost:4200 and you the components render just fine
I am wondering what is different in this situation?

**Comment by alxhub** [comment] 2020-03-03 23:16
@Phil147 indeed, this is an instance of the same problem.

> What is really interesting if you build against the library source code and not the dist folder, this problem does not happen.

Indeed, because the application is built with `sideEffects: true` by default :)

**Comment by Wintermoose** [comment] 2020-03-04 09:39
We have similar issue in a bit more complex scenario than direct recursion (it's parent / children relation between components, registered through shared service: think sidebar with configurable widgets). There is no circular dependency on the source level, but I guess it happens once the templates are compiled.

Configuring the sideEffects (in our case through a file list, as the library contains multiple entry points) seems to solve it, for now.

**Comment by vthinkxie** [comment] 2020-03-16 10:35
Hi @alxhub 
we meet this problem too https://github.com/ng-packagr/ng-packagr/issues/1576
it is hard to figure what happened after building the lib

**Comment by Phil147** [comment] 2020-04-14 19:09
I agree with @vthinkxie this bug is hard to understand and it happens frequently in common situations. Right now it doesn't seem to have a high impact but as soon as libraries are supposed to be shipped with ivy, which I understand is the recommended approach from version 10 on, this will have a huge impact.
The bug I described above could be mitigated for us with a base class but we also run into this problem in another case where I don't understand why it happens and I can't find a solution except using `sideEffects: true` which seems a terrible workaround once we are supposed to ship the library with ivy.

**Comment by elesueur** [comment] 2020-04-14 19:12
I too have hit this issue and found it very difficult to debug.

I am interested to know how to _not_ build my libraries with the Ivy compiler and use the View Engine that is mentioned. I have not seen how to make changes to angular.json or the library's tsconfig to disable Ivy... can someone help there?

**Comment by Hypercubed** [comment] 2020-04-14 19:39
@elesueur I think it is not an issue if you set `"buildOptimizer": false`.

**Comment by Phil147** [comment] 2020-04-14 20:03
Hi @elesueur 
to build your library with view engine your tsconfig needs `enableIvy: false` in the `angularCompilerOptions`, see here: https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9

**Comment by AndreiVajnaII** [comment] 2020-04-15 06:39
@elesueur Normally, if you created the library with Angular 9, or if you migrated your project to Angular 9 correctly, the angular.json configuration for your library should look like this:

```
      "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/my-lib/tsconfig.lib.json",
            "project": "projects/my-lib/ng-package.json"
          },
         "configurations": {
            "production": {
              "tsConfig": "projects/my-lib/tsconfig.lib.prod.json"
            }
          }
```

Where the prod tsconfig disables Ivy:

```
{
  "extends": "./tsconfig.lib.json",
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```

So you can now build your library `ng build my-lib --prod` with Ivy disabled.

**Comment by elesueur** [comment] 2020-04-15 13:42
@AndreiVajnaII perfect, thank you for clarifying this - exactly what I was looking for.

**Comment by zuzusik** [comment] 2020-10-30 05:01
We have encountered this recently. 

We have moved a part of our app to a library and as our app is built with Ivy, we consumed Ivy library version as well. It was very much confusing experience when in prod mode the library turned out broken where it was working flawlessly in dev mode. The worst thing that there are zero clues how to debug and where to dig - fail happens silently and verbose mode is not much of a help - the output of terser is very cryptic - it's not clear at all what is being shaken off and why. After hours of googling was lucky to found this issue...

With that said, I believe `--verbose` mode should provide meaningful information about things being removed from the build. That would make it much easier to troubleshoot issues like this. I have already raised this once in another issue (start reading from https://github.com/angular/angular/issues/37102#issuecomment-628782822), but that seems didn't go anywhere.

Also, I agree this issue shouldn't be marked as low frequency and second priority - this is pretty much a fundamental issue with libraries Ivy builds and Ivy builds are promoted as main way to build libraries going forward.

**Comment by Pizzicato** [comment] 2021-01-21 08:16
Something quite strange is happening to me in the same situation that the OP explained, using Angular 11.05: When compiling the whole app I don't get any errors or warnings, actually everything works well. The problem is that when I make any change in the component equivalent to the `RecursiveItemComponent`, the module that contains it is recompiled and I get a circular dependency warning and then a browser error: `ReferenceError: can't access lexical declaration `XXX' before initialization error`  (Firefox).

This happens even when setting `sideEffects: true` in `package.json`.

I finally decided to remove the `RecursiveItemComponent` since it's very small, and move the code to the parent component, creating a direct recursion instead and everything seems to be OK. Obviously, this is not a fix.

**Comment by JoostK** [comment] 2021-01-21 10:28
@Pizzicato you are correct, that is a known issue in incremental rebuilds. The compiler correctly updates all necessary files, but some updates don't end up in the generated Webpack bundle. This is being tracked in #39431 and angular/angular-cli#18707.

**Comment by dblVs** [comment] 2021-08-18 14:27
Is there a possibility to have a design session with either @alxhub or @IgorMinar to investigate solutions and implement it?

**Comment by IgorMinar** [comment] 2021-08-19 03:58
This does appear like a bad issue that should be treated as a regression and fixed. From the discussion above it's not clear what is the root case for this issue. Is it some kind of CLI optimization or is the problem in how the compiler generates the code?

**Comment by IgorMinar** [comment] 2021-08-19 03:59
Let's agree on the root case before we determine what the next steps here are.

**Comment by Pmyl** [comment] 2021-08-19 16:58
Does this workaround still works?
Correct me if I'm wrong but I think [this commit](https://github.com/angular/angular/commit/322951af495ef33d20de751de1854ebbe2c5ea49) now ensures to emit a compilation error on cyclic dependencies.

If the workaround doesn't work anymore shouldn't this issue receive a priority review to bumb it to P1 or P0 [following this comment's logic](https://github.com/angular/angular/issues/35602#issuecomment-719666614)?

**Comment by zuzusik** [comment] 2021-08-19 18:05
`"sideEffects": true,` workaround still works for us, we are on Angular `12.1.2`

**Comment by hadsy** [comment] 2021-08-19 21:50
> > Does this workaround still work?
> 
> `"sideEffects": true,` workaround in library's `package.json` still works for us, we are on Angular `12.1.2`

hmmm, adding `"sideEffects": true` to my library package.json has zero effect for my project, the same issue happens.
Only when I change compilationMode to "full" from "partial" in tsconfig.lib.prod.json does it successfully build, which doesn't help much.

**Comment by dblVs** [comment] 2021-08-20 13:25
In this [super small repo](https://github.com/dblVs/circular-dep-playground), even `"sideEffects": true` doesn't help as it's not being built. 
[Here](https://github.com/dblVs/circular-dep-playground/runs/3382297138?check_suite_focus=true#step:3) is the build which runs ng build and fails with the NG3003 error. Although that error is documented, shouldn't that be a acceptable use-case?
P.S @zuzusik am I doing something wrong with the `"sideEffects"` flag ?

**Comment by zuzusik** [comment] 2021-08-20 14:38
@dblVs it might be different use case (or something has changed in Angular recently), because in our case we weren't seeing any error messages - in our case components were _silently_ tree-shaken in production build.

**Comment by JoostK** [comment] 2021-11-16 21:03
> Does this workaround still work?
Correct me if I'm wrong but I think this commit now ensures to emit a compilation error on cyclic dependencies.

Ivy's partial compilation mode does not allow for the compiler to introduce cyclic import statements, it will report [error NG3003](https://angular.io/errors/NG3003) instead.

This issue can only occur for full compilation mode, however libraries have to be compiled using partial compilation which has been available since Angular 12.0. As such I will close this issue.

**Closed by JoostK** 2021-11-16 21:03 UTC
Labels: type: bug/fix, regression, engine: ivy, comp: compiler, state: confirmed, triage #1, design complexity: major, P2

**Comment by zuzusik** [comment] 2021-11-16 21:28
@JoostK it seems like error NG3003](https://angular.io/errors/NG3003) you referenced contains contradicting information to following statement of yours:

> This issue can only occur for full compilation mode, however libraries have to be compiled using partial compilation which has been available since Angular 12.0. As such I will close this issue.

here is what the page above says:

![Screen Shot 2021-11-16 at 4 26 20 PM](https://user-images.githubusercontent.com/4233080/142068498-61fc52e6-5d70-469e-84e8-cd969d91734d.png)

considering this, I might assume that this error can also happen in partial compilation mode - can you please clarify?

**Comment by JoostK** [comment] 2021-11-16 21:33
> considering this, I might assume that this error can also happen in partial compilation mode - could you please clarify?

@zuzusik The error will _only_ be reported in partial compilation mode. I am not sure where you see a contradiction, but to clarify: by "this issue can only occur for full compilation mode", I was referring to the problem of "recursion of components (and circular imports) doesn't work with Ivy built libraries" as per this issue's title.

Please let me know if things are still unclear.

**Comment by zuzusik** [comment] 2021-11-16 21:39
@JoostK ok, so "recursion of components (and circular imports) doesn't work with Ivy built libraries" can only occur in full compilation mode, but libraries should be built in partial compilation mode, but according to error page above in partial compilation mode that same situation ("recursion of components (and circular imports)") leads to throwing an error 

so now I don't see how applying partial compilation to libraries would solve this issue? it seems like it wouldn't solve it, but just would make it visible as it would throw an error? is this what you meant?

**Comment by JoostK** [comment] 2021-11-16 21:59
> so now I don't see how applying partial compilation to libraries would solve this issue? it seems like it wouldn't solve it, but just would make it visible as it would throw an error? is this what you meant?

@zuzusik Yes, that is what I meant. Partial compilation surfaces this pitfall by means of an error. This does mean that a library may need to be refactored to avoid the cycles, please see https://github.com/angular/angular/issues/43227#issuecomment-904173738 for the reasoning behind this approach.

**Comment by zuzusik** [comment] 2021-11-16 21:59
@JoostK got it, thanks for clarifying! 👍
