### ISSUE TITLE
Issue with Regexp on mobile safari 7 (DatePipe error on Browser Stack)

### ISSUE THREAD

**Issue by vicb** [angular/angular#12597] opened 2016-10-28 17:33 UTC
Browser Stack reports: `DatePipe supports should support date FAILED`

Thanks to @DzmitryShylovich to point to the [probable culprit](https://github.com/angular/angular/pull/12418#discussion_r84394435):

Sometimes date pipe test fails with the following error http://prnt.sc/cu6pfs
That's the only regexp used in date pipe.
Probably related to andyearnshaw/Intl.js#231

/ref https://travis-ci.org/angular/angular/jobs/171323976#L804

**Comment by vicb** [comment] 2016-10-29 02:27
The issue in Intl.js should be fixed by https://github.com/andyearnshaw/Intl.js/pull/244

**Comment by DzmitryShylovich** [comment] 2016-11-19 18:20
Pr was merged.

**Comment by pkozlowski-opensource** [comment] 2016-12-12 13:14
> Pr was merged. 

It was indeed but there was no release that contains this fix which means that we can't verify the fix. Let's keep this issue open till we can switch to `v1.2.6` and verify the fix.

**Comment by DzmitryShylovich** [comment] 2016-12-12 13:19
> Browser Stack reports: DatePipe supports should support date FAILED

I haven't seen that error for several weeks

**Comment by nicoespeon** [comment] 2017-01-05 15:00
Hi there 👋 

Got an issue today that I think is related to this one.
I updated my current project to Angular v2.4.1, upgrading a bunch of dependencies like Rx.js doing so.

Then I got some tests failing with that kind of error message: 

```
Error: Error in ./VisaComponent class VisaComponent - inline template:25:46 caused by: Invalid regular expression: unmatched parentheses (line 663)
```

Turns out it's caused by the date pipe I'm using (`date:'dd/MM/yyyy'`) when I trigger `fixture.detectChanges();` in my tests.
I do import `intl` v1.2.5 and never got this issue before.

I'm not sure why this is happening now, after upgrading to v2.4.1. But root cause looks a lot related to this issue to me.

Anyone is having the same issue?
Guess there is nothing I can really do until the patch is released, right?

Thanks a lot 👍

**Comment by DzmitryShylovich** [comment] 2017-02-03 00:03
@pkozlowski-opensource do we still need to verify? :)

**Comment by pkozlowski-opensource** [comment] 2017-02-03 08:40
Yes. I will close this issue when the new version of the Intl API polyfill is released and we switch to using it.

**Comment by Shireilia** [comment] 2017-02-10 15:04
I have the same issue than @nicoespeon on Safari (though it's not on the tests, but while running the app), and i do import intl 1.2.5 as well.

Rollback to 1.2.4 fixed the issue for me, so you should try it @nicoespeon :)

**Comment by vovikdrg** [comment] 2017-02-14 02:38
Same problem 
@angular/cli: 1.0.0-beta.31
node: 6.9.5
os: win32 x64
@angular/common: 2.4.7
@angular/compiler: 2.4.7
@angular/core: 2.4.7
@angular/forms: 2.4.7
@angular/http: 2.4.7
@angular/platform-browser: 2.4.7
@angular/platform-browser-dynamic: 2.4.7
@angular/router: 3.4.7
@angular/cli: 1.0.0-beta.31
@angular/compiler-cli: 2.4.7

Rollback intl 1.2.4 solve it

**Comment by Zefling** [comment] 2017-03-07 17:00
Same problem on Safari 9.1 with intl 1.2.5, but it's Ok with 1.2.4.

**Comment by michaelbromley** [comment] 2017-11-23 16:28
@pkozlowski-opensource am I correct in thinking that this issue is resolved with the move from Intl to CLDR in Angular 5? 

I just upgraded and my issue was resolved (phantomjs failing due to intl API stuff).

**Comment by pkozlowski-opensource** [comment] 2017-11-23 16:34
@michaelbromley I would say so but I will let @ocombe confirm

**Comment by ocombe** [comment] 2017-11-23 16:43
Yes!

**Closed by ocombe** 2017-11-23 16:43 UTC
Labels: comp: common, flag: can be closed?, freq3: high, severity3: broken, state: Blocked
