### ISSUE TITLE
Feature Request: Drag and drop of tiles as part of Angular CDK

### ISSUE THREAD

**Issue by rahulsahay19** [angular/angular#22816] opened 2018-03-16 05:19 UTC
Hi Team,

Just a question, last year in angular mix, it was announced that features like drag and drop feature and gesture capturing will be part angular component development kit. Just wanted to understand, whether it will be part of the release planned in april 6.

Here is the link which I am referring to https://www.youtube.com/watch?v=kYDLlfpTLEA. If this is not the right place to ask question, then kindly redirect me to correct forum.

Thanks,
Rahul

**Comment by trotyl** [comment] 2018-03-16 05:29
Wrong repo, CDK is part of [Angular Material](https://github.com/angular/material2).

**Comment by rahulsahay19** [comment] 2018-03-16 05:36
@trotyl But, those features aren't having angular material dependency. That was announced in the conf!

**Comment by trotyl** [comment] 2018-03-16 05:53
`@angular/cdk` is [one of the mono packages](https://github.com/angular/material2/tree/master/src/cdk) in Angular Material.

**Comment by CaerusKaru** [comment] 2018-03-16 07:28
Duplicate of https://github.com/angular/material2/issues/8963

**Comment by rahulsahay19** [comment] 2018-03-16 08:40
@CaerusKaru Thanks!

**Closed** 2018-03-18 01:31 UTC
