### ISSUE TITLE
.hasError() on control can't seem to handle boolean values from custom errors?

### ISSUE THREAD

**Issue by ChristopheVanassche** [angular/angular#51438] opened 2023-08-21 13:13 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

Yes

### Description

We're having this application where we check if a name is unique. It seems the .hasError() function can't seem to handle boolean values as a control error-value. I've reproduced the problem here: [Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-de5tar?devToolsHeight=33&file=src%2Fmain.ts)

When setting a boolean value as error-value, the hasError function returns false, even if the error is there.

King regards

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-de5tar?devToolsHeight=33&file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.8
Node: 18.10.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 16.1.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1601.8
@angular-devkit/build-angular      16.1.8
@angular-devkit/core               16.1.8
@angular-devkit/schematics         16.1.8
@angular/cdk                       16.1.7
@angular/material                  16.1.7
@angular/material-moment-adapter   16.1.7
@schematics/angular                16.1.8
rxjs                               7.5.5
typescript                         4.9.3
zone.js                            0.13.1
```

**Comment by JeanMeche** [comment] 2023-08-21 17:30
This issue reminds me of #45556 which points to #24344.

It was deemed too breaky to be fixed.

**Comment by JoostK** [comment] 2023-10-29 16:14
Closing as duplicate of #24344

**Closed by JoostK** 2023-10-29 16:14 UTC
Labels: area: forms
