### ISSUE TITLE
Allow custom decorators that use lifecycle hooks in AoT - these are our version of hooks, but we can't use them

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#30497] opened 2019-05-15 23:55 UTC
When writing a custom decorator, lifecycle methods you patch are removed in AoT because the compiler doesn't check that custom decorators are using them.

This results in an inability to create custom decorators with any meaningful component specific behaviour.

React uses hooks to help patch into setup/teardown of your functional components, decorators are Angulars form of hooks. It would be super useful to have this functionality in Angular.

**Comment by ChristopherKiss** [comment] 2019-05-16 00:40
@alshdavid,

It looks like the onChanges life cycle works, but ngOnInit doesn't. Using a production build running with AoT, in the console I can see `required` and `on changes`, but not `init`. Switching to JIT development I correctly see the `init` messages.

Would be great to have this fixed.

```
export function RequiredInput<TValue>(defaultValue?: TValue) {
    return function<TInstance extends { [P in TKey]: TValue }, TKey extends keyof TInstance>(
        propertyClass: TInstance & Target,
        propertyKey: TKey & string
    ) {
        console.log('required');
      
        const originalInit = propertyClass.ngOnInit;
        const originalChanges = propertyClass.ngOnChanges;

        propertyClass.ngOnChanges = function(changes: SimpleChanges) {
            console.log('on changes');
             if (originalChanges) {
                 originalChanges.apply(this, [changes]);
             }
        };

        propertyClass.ngOnInit = function() {
            console.log('init');
            if (originalInit) {
                 originalInit.apply(this);
            }
        };
    };
}
```

**Comment by alshdavid** [comment] 2019-05-16 00:54
If it's hard for the compiler to statically analyse a custom decorator to determine what lifecycle methods are being patched, perhaps a basic solution like using comments which target the compiler will be a simple temporary solution.

eg
```typescript
// @AoT [ 'ngOnInit', 'onDestroy' ]
export function RequiredInput<TValue>(defaultValue?: TValue) {
    ...
}
```

**Comment by trotyl** [comment] 2019-05-16 03:12
Duplicate of https://github.com/angular/angular/issues/16023

**Comment by alxhub** [comment] 2019-05-28 22:19
I have some good news!

In Ivy, lifecycle hooks are purely a runtime concern. They're read off the prototype of the component as soon as the first instance is created, which means that if a decorator adds hooks to the prototype then Ivy will notice them.

**Comment by stupidawesome** [comment] 2019-05-29 01:19
@alxhub Should this be working in 8.0? I enabled Ivy and tried adding hooks with decorators using `renderComponent()` and `platformBrowserDynamic().bootstrapModule()` but it still doesn't work in AoT.

**Comment by trotyl** [comment] 2019-05-29 06:32
@alxhub 

> They're read off the prototype of the component as soon as the first instance is created

This is not true, lifecycle hooks are determined in [`defineComponent()`](https://github.com/angular/angular/blob/e688e02ee442658c754d813e84a9908baf874520/packages/core/src/render3/definition.ts#L266-L272), which happen when the constructor is created, not the instance.

> lifecycle hooks are purely a runtime concern.

However, decorators<super>*</super> are also purely a runtime concern, as explained in https://github.com/angular/angular/issues/16023#issuecomment-425623727, decorators runs after static properties, can be reproduce easily in [TypeScript playground](https://www.typescriptlang.org/play/index.html#src=function%20Component()%20%7B%0D%0A%09return%20(ctor)%20%3D%3E%20%7B%0D%0A%09%09alert('Decorator%20execution')%0D%0A%09%09return%20ctor%0D%0A%09%7D%0D%0A%7D%0D%0A%0D%0Afunction%20defineComponent()%20%7B%0D%0A%09alert('Static%20property%20execution')%0D%0A%09return%20null%0D%0A%7D%0D%0A%0D%0A%0D%0A%40Component()%0D%0Aclass%20MyComponent%20%7B%0D%0A%09static%20ngComponentDef%20%3D%20defineComponent()%0D%0A%7D%0D%0A).

<sub>The [current decorator proposal](https://github.com/tc39/proposal-decorators/) has changed to compile-time semantics, but what implemented in TypeScript is still the obsolete stage-0 proposal.</sub>

**Comment by ChristopherKiss** [comment] 2019-05-29 07:43
@trotyl,

So it looks like this is blocked until Typescript updates the decorator implementation? Which doesn't look like it's in a release plan yet: https://github.com/Microsoft/TypeScript/wiki/Roadmap#future

**Comment by trotyl** [comment] 2019-05-29 08:02
> So it looks like this is blocked until Typescript updates the decorator implementation?

@ChristopherKiss I really don't know, the decisions are made by Angular team, I have no way to change their mind.

**Comment by mhevery** [comment] 2020-02-15 00:46
Here is how it should work in Ivy: https://ng-run.com/edit/TIbZM8JylZuhdZCM5KdO

Unfortunately this works only in JIT mode (but fails in AOT mode). The issue is that in AOT mode the `@Component` decorator is converted into `defineComponent` assignment which runs before the decorator has a chance to run. As a result the `defineComponent` collects the lifecycle hooks before the custom decorator has a chance to run.

**Comment by klemenoslaj** [comment] 2020-04-02 17:10
@mhevery Will this be supported by AOT in the future?
If so, maybe we could take the risk and use `target.ɵcmp` until then.

**Closed** 2020-07-15 23:22 UTC
Labels: comp: core, freq1: low, severity2: inconvenient, type: feature
