### ISSUE TITLE
Still: "ERROR in Unable to write a reference to" building with Ivy

### ISSUE THREAD

**Issue by elca-lan** [angular/angular#36385] opened 2020-04-02 07:38 UTC
# 🐞 bug report

Actually the same bug report as https://github.com/angular/angular/issues/33850

That issue has been closed and references a PR (https://github.com/angular/angular/pull/33828), but the PR was never merged, but also closed? There seems to be an _awful_ lot of "auto closing" going on and since those issues are locked, there is not much I can do about it except create yet another issue.

**Comment by petebacondarwin** [comment] 2020-04-02 07:47
@elca-lan - the messages on Github are a bit confusing, sorry. When we merge a PR we actually use a script that rebases it and adds a "PR Close #XXXX" comment to the commit that automatically closes it on Github. The script also rebases the PR on the patch branch if necessary and merges it there too.

Note that on the PR you mention there is :

> alxhub closed this in 5172074 on 19 Nov 2019

This links you to the commit on master from this PR that causes this PR to be closed.

And then further down we have the same commit mentioned:

> alxhub added a commit that referenced this pull request on 19 Nov 2019

which is the commit being merged to the patch branch (9.0.x).

And, of course, the commits also mention the issue, which causes it to be closed too.

So you can see that the code from this PR was merged and released as part of 9.1.0-next.0 and 9.0.0

**Comment by petebacondarwin** [comment] 2020-04-02 07:48
So if you are still getting this error then perhaps there is another cause. Can you please check what versions you are using and create a reproduction for us to investigate?

**Comment by elca-lan** [comment] 2020-04-02 07:54
Hmm... interesting. Definitely a bit confusing 😛, but thank you for the explanation @petebacondarwin . This then seems to have been merged in November, long before the 9.0.0 release - I am currently on 9.0.2. But the referenced commit has only been tagged in 9.1.0 versions. Does that mean that I have to upgrade to 9.1.0 first?

**Comment by petebacondarwin** [comment] 2020-04-02 08:02
The "fix" commit actually appears twice:

* https://github.com/angular/angular/commit/14156bd26265fcc18fa3635566c65af37dd7a6a9 (on 9.0.x)
* https://github.com/angular/angular/commit/850aee2448e01e4d43582fbf605eb8d7ef5b7370 (on master)

The first of these actually appears in the 9.0.0 release.

**Comment by elca-lan** [comment] 2020-04-02 08:07
Then I guess I'll have to work on a minimalist repro. Which is going to be difficult because our project is _huge_. But I guess you can close this issue and I will create a new one with a repro and everything as soon as I can make one.

**Comment by petebacondarwin** [comment] 2020-04-02 08:09
OK - thanks for the understanding. I hope we can get to the bottom of your problem.

**Comment by JoostK** [comment] 2020-04-02 13:26
Your problem might be related to #33177, which was a precursor to the PR you mentioned. However, that needs a compiler option to be enabled. Depending on whether the issue occurs in a library or in your application, this option would have to be configured in your application's `tsconfig.json` or in ngcc's configuration of a specific library.

I am just guessing here as there's little information to go on, but maybe this helps in finding a solution.

**Comment by petebacondarwin** [comment] 2020-04-15 09:14
Closing this issue. Please open a new one with a reproduction when you have one @elca-lan .

**Closed by petebacondarwin** 2020-04-15 09:14 UTC
Labels: comp: compiler, flag: can be closed?, state: Needs repro, type: bug/fix

**Comment by viceice** [comment] 2020-05-08 05:06
Writing here, because #33850 is locked.

I seeing this error since v9.1.5 now, trying to create a simple reproduction
