### ISSUE TITLE
Successful http responses (e.g. 201) returned as errors

### ISSUE THREAD

**Issue by sebek64** [angular/angular#19555] opened 2017-10-04 14:38 UTC
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
HttpClient observables returns 201 (and probably other 20X except 200) http status as error.

## Expected behavior
Status < 300 should be returned as next, not error.

## Minimal reproduction of the problem with instructions
I can prepare a plunker if desired (or unable to reproduce) - tell me if needed.

## What is the motivation / use case for changing the behavior?
This is a regression between 4.3 -> 4.4. In 4.3.6, it is correct, in 4.4.4, it is not.
It may be related to another 4.3 -> 4.4 HttpClient regression: https://github.com/angular/angular/issues/19103.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [X] Chrome (desktop) version 61
 
For Tooling issues:
- Node version: 6.11.3  
- Platform:  Linux

</code></pre>

**Comment by jrmlstf** [comment] 2017-10-04 16:02
Same problem for me with a 201 using 4.4.4.

**Comment by anthonyreilly** [comment] 2017-10-04 19:05
I ran into the same issue after upgrading to 4.4.4, but it was because I was returning 201 with no response content (just like a 204/no content), and per spec it should. One of the error messages I was getting in the console was "Http failure during parsing".

Once I included a response body the 201 was handled normally - so it wasn't really an error in my case, it was adhering more closely to the spec. It's arguable if this should cause an error, or just accept it and treat it as an empty response.

**Comment by sebek64** [comment] 2017-10-04 19:15
Yes, this is my case too. I didn't realize that "201 Created" should return the created object. We have such an api that just returns Location: ... header and no body.

Per 2616, the body SHOULD be included, not MUST. So I guess the client library should not treat this case as error, especially when using observe: "response".

**Comment by Toub** [comment] 2017-10-05 07:02
Same problem here, /logout broken due to this bug...

**Comment by victornoel** [comment] 2017-10-05 10:50
I don't think that's a bug per se: the httpclient by default expects some json in the body, if you don't want that, then use the `responseType` property in the http method option (see for example: https://github.com/angular/angular/issues/18680#issuecomment-330425866).

**Comment by sebek64** [comment] 2017-10-05 13:39
@victornoel Thank you, adding responseType: "blob" fixed the problem for me. Anyway, it is a bit counterintuitive, I would expect to get null for responseType: "json" and no or empty response. Yes, the content-type: application/json header is missing in the response headers, so strictly speaking, angular is correct, but I guess it is better to be slightly incorrect in this case.

**Comment by bluepixbe** [comment] 2017-10-20 06:42
same problem here. e.g. with status code 201 and empty body

**Comment by sebek64** [comment] 2017-10-20 11:49
Another argument for the more liberal behavior is the following case: server returns successful response empty, but error response with a json. Now, the only option is to use responseType: text and manually parse error response. I'd rather use responseType: json, let angular parse the error response, and get null as body.

**Comment by victornoel** [comment] 2017-10-20 12:03
@sebek64 actually this has been implemented in 4.4.6 :)

**Comment by sebek64** [comment] 2017-10-20 12:08
@victornoel No, 4.4.6 is still broken, since you can either pass responseType: string (but then, you don't get json parsed on error), or responseType: json (but then, you don't get "next" on 201 successful response).

**Comment by trotyl** [comment] 2017-10-20 12:11
Duplicate of #18680 and #19413.

**Comment by victornoel** [comment] 2017-10-20 12:32
@sebek64 ah ok, thx :)

**Comment by maximelafarie** [comment] 2017-11-14 00:16
Something planned to fix that? I always have this error with Angular 5.0.0 with 201 and empty body response.

**Comment by davidrdz93** [comment] 2017-11-27 12:23
Same problem with angular 5.0.0, http 201 response code is being considered an error!

**Closed** 2017-11-29 18:12 UTC
Labels: comp: common/http, freq1: low, severity5: regression, type: bug

**Comment by demeureguillaume** [comment] 2017-11-30 13:25
Same problem with HttpClient (Angular 5.0.3) when receiving an HTTP 201 with text plain body

Did you already know when this fix will be delivered in stable version?

Thanks in advance for your support

**Comment by YShane** [comment] 2017-12-23 22:20
Same error here. This is honestly some amazing behaviour.

**Comment by samcontesse** [comment] 2017-12-24 09:12
In the meantime, you could use an interceptor to catch the error and return it as a normal response. This can maybe help you : https://gist.github.com/samcontesse/ed2a540c739514667d46195ff605e9c5

**Comment by BrunoQuaresma** [comment] 2018-01-29 18:57
Same error here... There are any updates on it?

**Comment by lasimone** [comment] 2018-05-04 11:48
This is still occurring in Angular 5.2.2, are there any updates? I am getting a status code of 200 but an error in addition.

**Comment by imchaitanya9** [comment] 2018-05-17 12:32
I was also having the same issue, my below code:
`public mymethod(data: myObject): Observable<any> {
    const url: string = 'myURL';
    const headers = new Headers();
    headers.append('Content-Type', 'application/json');
    headers.append('Authorization', `bearer myToken`);
    const options = new RequestOptions({ headers: headers });
    return this._http.post(url, data, options);
       .map(this.extractDataJSON)
      .catch(this.handleErrorObservable);
  }
  }`

I was handling my data using .map and .catch methods. 
I removed both. my issue is solved.

**Comment by rodrigoguariento** [comment] 2018-06-11 16:18
I had the same problem, but I realized that my back-end was returning wrong JSON format.

**Comment by romanshutsman** [comment] 2018-11-23 13:01
FIXED on BACKEND

In my case: back-end which is written on C# hadn't been  enable CORS: 
> `config.EnableCors();`
and
>  `[EnableCors(origins: "*", headers: "*", methods: "*")]`
import from `using System.Web.Http.Cors;`
