### ISSUE TITLE
ngModel - moving cursor at the end

### ISSUE THREAD

**Issue by JurajMlich** [angular/angular#6287] opened 2016-01-06 06:32 UTC
Yesterday, I saw a bug in the behaviour of inputs with ngModel set. When you have some text in the input already and you put the cursor before that text and start typing really fast (press all buttons of your keyboard), the cursor jumps to the end of the string. The issue also occurs in textareas making them unusable.

http://plnkr.co/edit/KJeHOPtDW2J7CBLFZsPb?p=preview

Without fixing this, inputs and textareas are unusable since writing something in the middle of the content is an important feature.

Tested browsers: Chrome 47.0.2526.106 (64-bit), Firefox 43.0.3

**Comment by pe8ter** [comment] 2016-01-06 07:19
[Recreated with Beta-0](http://plnkr.co/edit/ZWiQqw3nR8xS1MRrpTry?p=preview).

**Comment by radek-holy** [comment] 2016-01-06 09:21
I guess this is a duplicate of https://github.com/angular/angular/issues/5808.

**Comment by JurajMlich** [comment] 2016-01-06 09:27
@radek-holy yea, it may be caused by that... anyway, it should be fixed as soon as possible and #5808 looks like being ignored

**Comment by radek-holy** [comment] 2016-01-06 09:42
Hm, after reading that again, I am not that sure any more.
Also looks related to https://github.com/angular/angular/issues/3075.

Yeah, I agree with you.

FTR, I hit this bug while trying to debug https://github.com/angular/angular/issues/6114. I believe it's related.
And BTW, to improve the reproducibility, I recommend to run enough busy loops (e.g. `python -c "while(True):pass"`. You don't have to be that fast then.

**Comment by robwormald** [comment] 2016-01-06 09:57
i'm going to close this as a duplicate of #5808. let's track it over there.

**Closed by robwormald** 2016-01-06 09:57 UTC
