### ISSUE TITLE
Custom validations error

### ISSUE THREAD

**Issue by forforeach** [angular/angular#3847] opened 2015-08-26 13:02 UTC
Hi,

I'm trying to implement a number of custom validation directives. Everything goes good until I put more then 3 directives on same element. When I put four or more validators, I start to receive an error 
`EXCEPTION: Cannot instantiate cyclic dependency! (function (cd, renderer, elementRef) { -> NgControl)`
It not happens immediately, but on the second entrance to a page. 
Here is a plunkr with example: http://plnkr.co/edit/305RbFlIFCBnvJtotEA0?p=preview
Page 1 and page 2 are the same except that the first page's input has only 3 validation directives while the second's has 5.

Scenario:
Open the plunkr -> go to page 2 -> return to page 1 -> go to page 2 again
Now open a console and you'd be able to see an error.

Thanks,
Dima

**Comment by forforeach** [comment] 2015-08-28 12:22
Anybody?

**Comment by pkozlowski-opensource** [comment] 2015-08-28 12:25
@forforeach you will greatly maximize your chances of answer if you trim down your plunker to the absolute minimum needed to reproduce the pb. Yours is substantial atm. Please remove all the stuff that is not essential (ex.: do you routing to trigger the pb?)

**Comment by forforeach** [comment] 2015-08-30 07:05
First of all, thanks for your response. Secondly, I don't see how can I squeeze my plunkr. The only place I can think of, is a number of validation directives. Now there are 6, I can remove 2 and stay with 4. Updated plunkr is here: http://plnkr.co/edit/305RbFlIFCBnvJtotEA0?p=preview

In addition I can explain what happens there: 

1. There are 4 validation directives, which do nothing. I need them in order to set 4 different validators on an input.

2. There are two pages that reveal validation directives to their views and form directives for ng-form-control binding. Each of them creates one Control and binds it against the appropriate input.

3. There is an app controller that includes small navigation pannel and router-outlet in order to switch between 2 pages. 

And the scenario, as I said before, is to visit a second page twice. On a second entrance you could be able to see an error in a console. (That's the reason that I cannot remove routing. The error happens only after second navigation). It happens only when you have more than 3 validation directives on the same input. Thus, you navigate to the first page, you don't get an error.

**Comment by pkozlowski-opensource** [comment] 2015-08-30 07:43
>  Secondly, I don't see how can I squeeze my plunkr

Example: do you routing to reproduce your problem?

**Comment by pkozlowski-opensource** [comment] 2015-08-30 07:43
@forforeach thnx for the update!

**Comment by pkozlowski-opensource** [comment] 2016-08-31 12:30
I can't reproduce it with the RC5: https://plnkr.co/edit/HDEd7nVMdAMjcz3G9MG9?p=preview
(I didn't use routing but ngIf instead to create / destroy input + its validators which should be equivalent to routing situation).

@forforeach one thing I've noticed is that your providers were no marked as `multi: true` which would be a potential source of problems.

I'm going to go ahead and close this one but if you can reproduce it with the latest code level please re-open. Thnx!

**Closed by pkozlowski-opensource** 2016-08-31 12:30 UTC
Labels: comp: core/di, effort1: easy (hour), P2: required, type: bug
