### ISSUE TITLE
Recursive components fail on recompilation

### ISSUE THREAD

**Issue by algcifaldi** [angular/angular#39458] opened 2020-10-27 19:13 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Yes, the previous version in which this bug was not present was @angular/compiler 9.1.9

### Description

In an app with two components that reference one another recursively, recompilation after modifying a component in the module will result in a console error and components from that module missing from the UI.

When comparing the compiled code between the initial compile and one triggered by a modification, I notice that the `ɵɵsetComponentScope` calls for the recursive components referenced first by the app are missing.

I've been following these two related issues, https://github.com/angular/angular/issues/38362 and https://github.com/angular/angular/issues/35602, but they both squarely point to being related to using the `--strict` option, which our app does not use. This means we also cannot work around this issue by using the `"sideEffects": true` suggestion as it does not apply.

The issue was difficult to track down and without a workaround makes for a truly painful development experience. Any help would be very appreciated.

## 🔬 Minimal Reproduction

I've created a minimal repository with steps to reproduce the issue we're seeing in our application here: https://github.com/algcifaldi/repro-not-strict

## 🔥 Exception or Error
<pre><code>Can't bind to 'ngIf' since it isn't a known property of 'app-a'.</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>10.0.4</code></pre>
We also continue to hit this issue after upgrading our app to `10.1.6`.

**Anything else relevant?**

**Comment by alan-agius4** [comment] 2020-10-27 19:23
Looks like a duplicate of https://github.com/angular/angular/issues/39431

**Comment by JoostK** [comment] 2020-10-27 20:02
> Looks like a duplicate of #39431

Yeah, I can confirm after playing with the reproduction. It does confirm my suspicion that this is a problem regardless of lazy modules.

**Comment by JoostK** [comment] 2020-10-28 19:51
I linked your repo in #39431 and close this one as a duplicate.

**Closed by JoostK** 2020-10-28 19:51 UTC
Labels: comp: compiler

**Comment by algcifaldi** [comment] 2020-10-28 23:13
Awesome, thanks for taking a look. I'll track the main thread
