### ISSUE TITLE
Directives don't clear provided NG_VALIDATORS when destroyed

### ISSUE THREAD

**Issue by thefliik** [angular/angular#34538] opened 2019-12-23 02:12 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

No

### Description

If a directive adds a custom validator to a form control via the `NG_VALIDATORS` provider, and that directive is destroyed (e.g. because an `ngIf` hides the directive/component), it is expected that the custom validator is removed from the form control. In reality, the custom validator is not removed from the form control.

I *think* the underlying cause of this is the same as #20007. However, the problem is not just one of a memory leak:

1. If a directive defines a custom validator and that directive is destroyed, the form control should no longer undergo the validation associated with the directive (but it does).
2. If a directive's validation is, itself variable (i.e. the directive might require a control to be `true` or `false`, depending on the *directive's* inputs), then a form control can end up with multiple versions of the directive's validators. One version requiring the control to be `true`, the other version requiring the control to be `false`. In this case, the control will always be invalid. 

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/forms-issue-reproduction?file=src%2Fapp%2Fapp.component.html

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.2
Node: 10.16.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.2
@angular-devkit/core         8.3.2
@angular-devkit/schematics   8.3.2
@schematics/angular          8.3.2
@schematics/update           0.803.2
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

- Related: https://github.com/angular/angular/issues/20007

**Comment by AndrewKushnir** [comment] 2020-12-16 18:06
Closing this issue since it has the same root cause as #20007 and should be resolved by #39235. Thank you.

**Closed by AndrewKushnir** 2020-12-16 18:06 UTC
Labels: P2, comp: forms, forms: validators, state: confirmed, triage #1, type: bug/fix
