### ISSUE TITLE
Exclude push event from ngsw-worker.js

### ISSUE THREAD

**Issue by shabbir-dhangot** [angular/angular#26413] opened 2018-10-12 11:43 UTC
_**EDIT**(@gkalpak): Related to issue #24387._

##

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have my own service worker that listening push event. While building **ngsw-worker.js** auto generated and having push event available. Due to this website is showing notification **two times**. One from my service worker and another from ngsw-worker.js file.

Currently I have to comment that code each time I am building dist folder. Is there any option available that will automatically not include this push event listener?

`this.scope.addEventListener('push', (event) => this.onPush(event));`  

## Expected behavior

There should be option to not include this event. 

## Minimal reproduction of the problem with instructions
Problem required no plunkr. Its happening with PWA service worker js file. 

## Environment

<pre><code>
Angular version: latest

Browser:
- [x] Chrome (desktop) version all
- [x] Chrome (Android) version all
- [x] Chrome (iOS) version all
- [x] Firefox version all
- [x] Safari (desktop) version all
- [x] Safari (iOS) version all
- [x] IE version all
- [x] Edge version all

**Comment by shabbir-dhangot** [comment] 2018-10-12 13:41
@gkalpak  Can it be open?
This is much needed feature who has already developed website. I am using firebase service-worker from months and that is having active notification listener.

Due to dual notification listener user is receiving notification twice. I appreciate if you introduce this option soon.

Currently managing with commenting line every-time.

**Comment by gkalpak** [comment] 2018-10-12 13:56
OK, it sounds reasonable, I guess (especially if you don't control the other SW).
Maybe we could have a method on `SwPush` to disable handling of `push` events.

(Not a high priority, though. Contributions welcome :wink:)

**Comment by shabbir-dhangot** [comment] 2019-01-22 07:43
@gkalpak  I able to comment line using sed below command post ng build --prod

<pre>
<code>
ng build --prod && pushline=\"this.scope.addEventListener('p\" && replaceline=\"\/\/this.scope.addEventListener('p\" && sed -i \"s/$pushline/$replaceline/g\" dist/ngsw-worker.js
</code>
</pre>

**Comment by johanchouquet** [comment] 2020-04-23 10:13
Hello there,

Do you plan on working on that feature anytime soon ?

I think that a lot of people want to **build PWAs using FCM for push notifications, and they also want to use angular service worker.**

It seems that a _Workbox + FCM_ solution is possible, but there are no examples out there of how to do that. **So, it's a big blocker to the adoption of Angular Service Worker.**

What you think ?

**Comment by webmaxru** [comment] 2020-04-23 10:22
Hello! Just FYI: this part of my PWA workshop explains how to add Push support to Workbox-driven service worker. And the demo app is based on Angular (link to the repo is included in this doc): https://docs.google.com/document/d/10IOJ53cJR3opRYfpSKlRBYUnoeAHZOnLCBfW0mjA790/edit#heading=h.z6oes5esmix1

**Comment by johanchouquet** [comment] 2020-04-23 10:30
Hi @webmaxru! Thanks for the link. I'll look at that for sure !

**Comment by lpghartz** [comment] 2020-05-07 15:40
This is still a pretty serious issue, partly because the implementation of push handling in ngsw is extremely limited. Because push events are broadcast to the SwPush instance in the browser, if the app is active, you can't handle a push differently for active vs inactive apps. (For example, to trigger an action or show the notification in-app when the app is active, vs showing the desktop notification when it isn't.)

A DIY service worker can have that logic present in it to say "this was dispatched to the application, don't call showNotification(...)". 

There's different ways this could be handled, but it seems all of the similar bug reports are from people trying to solve that underlying problem -- if you use SwPush, you can't prevent the native push, and if you use your own service worker, you get doubled up native notifications. 

Given the scenarios people have are pretty varied, being able to simply turn off push support in ngsw seems like the better option, but at a minimum it seems like the ngsw implementation needs a way to tell it "if I have any clients, so this broadcast is going to hit an instance of my application, don't show this notification".  Basically, if the broadcast() call in handlePush() actually posts any messages, don't execute the code following it. 

We've been trying to use Angular PWA, but this limitation is turning into a hard block for us, because the user experience for anything but the most trivial uses of push is just bad. 

Something is fundamentally broken with the architecture if common use patterns are requiring people to hand edit the build output.

**Comment by BoomDev** [comment] 2020-07-06 16:42
Just wanted to add that being able to not show a notification if the app is already open is one of [Google's recommended best practices](https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications#when_to_show_notifications)...

> it is easier to do it in the push handler inside your service worker
... unless you're using Angular's service worker.

**Comment by WaseemRakab** [comment] 2020-09-07 13:08
im looking forward to this issue also...
any update on this??

**Comment by ciekawy** [comment] 2020-10-12 06:27
I just got here looking for a solution and I'm so surprised there is no real one for so long and there are articles on the web and SO answers suggesting to comment out lines in `ngsw-worker.js` - I think this shows how important this issue is...

**Comment by markgoho** [comment] 2021-06-25 17:35
@jessicajaniuk is there a chance the automated process got this one wrong? The issue is from 2018 and has 6 thumbs up and 3 hearts on the original comment. Does the algorithm count other reactions besides 👍🏻 and does it scan for unique reactions across the whole thread of comments or just the initial comment? 

It's possible that if this were a brand new issue, it might have gotten the required 20 👍🏻 but this one is so old that nobody thought to go back and provide the additional 👍🏻 to get it to "count".

I'm not asking for this to be reconsidered, only to be used as way of asking "is the process working the way we intended it to?"

**Comment by jessicajaniuk** [comment] 2021-06-25 18:00
Hi @markgoho! Thanks for the question. I can understand your confusion here. The voting process looks solely at the issue description and does not look at all the comments within the issue. So in that case, this feature request only got 6 👍🏻  votes. Since we just started this new voting process, it's safe to say a lot of feature requests that have been around a while are getting closed with this situation. You are welcome to submit a new feature request to see if we get more votes going forward, since there will be less noise in the feature request queue.

**Comment by markgoho** [comment] 2021-06-25 18:11
thanks for this clarification regarding what exactly the bot is counting @jessicajaniuk 

regarding your suggestion to submit a new feature request, it seems like this might create a lot of duplicate issues simply to gather votes, e.g. this particular issue didn't get enough votes, so I'm creating a new issue with the same feature request?

do you think there might be a better way to approach this scenario? perhaps a "reset button" of sorts where a feature request is put back on the queue with a fresh 20-day timer? maybe it has to have been 3 months or something before a reset can happen (just thinking out loud here)

**Comment by jessicajaniuk** [comment] 2021-06-25 18:26
I hear you on the noise issue, but I still think that creating a new request makes the most sense. There's no real way for us to have a reset option. So creating a new request and going through the voting process again is really the best choice. We'll have the strongest signal there. We don't expect most of these requests to receive new open issues. If you feel strongly about this feature, please do create a new feature request issue.

**Comment by gkalpak** [comment] 2022-06-25 15:29
By design, the Angular Service worker does not support tweaking/disabling specific features - it was designed to be a drop-in SW and is necessarily limited in its functionality/configurability as a result.

We have #21197 to consider adding custom extension points, but for now other service worker implementations (e.g. Workbox) are a better option for user-defined behavior in the SW.

##
For really simple cases, such as disabling a specific event, you could also define your own service worker script that imports `ngsw-worker.js` at the end and add an event listener for the event you want to disable that prevents propagation of the events to over listeners (such as those defined in `ngsw-worker.js`.

I.e. something like:

```js
// my-sw.js
self.addEventListener('push', evt => evt.stopImmediatePropagation());
importScripts('./ngsw-worker.js')
```

##
I am going to close this issue, since we do not intend to provide the option of disabling/modifying specific events in the near future. In the meantime, let's use #21197 to track adding custom extensions points in general.

**Closed by gkalpak** 2022-06-25 15:29 UTC
Labels: feature, effort2: days, comp: service-worker, insufficient votes, votes required
