### ISSUE TITLE
 RouterLinkActive does not work as expected.

### ISSUE THREAD

**Issue by deniszografski** [angular/angular#30046] opened 2019-04-23 09:30 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/router

### Is this a regression?
No

### Description
<img width="599" alt="Screenshot 2019-04-23 at 10 59 36" src="https://user-images.githubusercontent.com/14232040/56568267-ed3a8780-65b6-11e9-9c80-56d7adb74dcf.png">

<img width="599" alt="Screenshot 2019-04-23 at 10 59 36" src="https://user-images.githubusercontent.com/14232040/56570397-2bd24100-65bb-11e9-9c22-e5eb255f2d02.png">

It would be great if you could add an option to set **active** link ( routerLinkActive ) to parent menu item in navigation while user is in edit route.

## 🔬 Minimal Reproduction

Angular.io official live example app from [https://angular.io/guide/router](https://angular.io/guide/router):
https://angular.io/generated/live-examples/router/stackblitz.html

1. Select Heroes in menu
2. Select one hero
3. You are now in edit mode / route and Hero in menu should have **active** state

## 🔥 Exception or Error
No errors.
## 🌍  Your Environment

**Angular Version:**
<pre><code>7.2.13</code></pre>

Chrome: Version 73.0.3683.103 (Official Build) (64-bit)
OS: macOS Mojave - 10.14.4

**Comment by jasonaden** [comment] 2019-05-09 22:21
This looks like it's working as designed. I think that example is being done in a way where the `routerLinkActive` would have a hard time determining to mark `Heroes` as `active` while on the edit page. Edit and the listing page are siblings. If edit were a child of the listing, it would make more sense.

I'm going to close this as it appears to be working as intended. If you think there's still a problem here or there's more to discuss, please open a new issue and fill in any additional details.

**Closed by jasonaden** 2019-05-09 22:21 UTC
Labels: comp: router
