### ISSUE TITLE
input's initialValue value ignored with withComponentInputBinding()

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#54738] opened 2024-03-06 21:25 UTC
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

No

### Description

Hi.
When `withComponentInputBinding()` provided with router, initialValue from signal input is ignored

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-snfkia?file=src%2Ftest.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
latest
```

**Comment by atscott** [comment] 2024-03-06 21:39
Duplicate of https://github.com/angular/angular/issues/52946

**Closed by atscott** 2024-03-06 21:39 UTC
