### ISSUE TITLE
NG 13 update to NG 14/15: Throttling navigation to prevent the browser from hanging

### ISSUE THREAD

**Issue by patrickritskes** [angular/angular#48397] opened 2022-12-08 08:50 UTC
### Which @angular/* package(s) are the source of the bug?

animations, common, compiler, core, forms, platform-browser-dynamic, platform-browser, router, service-worker, zone.js

### Is this a regression?

Yes

### Description

Started this app 5 years ago with Angular 2, till Angular 13 the dynamic routes lazy loaded works fine (with canActivate DynamicPathGuard), after a upgrade/update to NG 14/15 the browsers keeps hanging in a infinite loop here!
Can't see what I'm missing here, of if there a breaking changes!

Within the attached stackblitz for reproduction:
within the package.json the Angular Core is set to 13.2.0 as starter, you can see that everything works fine when you navigate.

Try updating the package.json to 14.2.0 or 15.0.2 and you see the routing doesn't work anymore, and the browser freezes after a while!

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/dynamic-routes-lazy-loaded-pydumm?file=package.json

### Please provide the exception or error you saw

```true
Throttling navigation to prevent the browser from hanging
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.2
Node: 14.20.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.0
typescript                      4.8.2
```

### Anything else?

Within the attached stackblitz for reproduction:
within the package.json the Angular Core is set to 13.2.0 as starter, you can see that everything works fine when you navigate.

Try updating the package.json now to 14.2.0 or 15.0.2 and you see the dynamic lazy loaded routing doesn't work anymore, and the browser freezes after a while!

**Comment by atscott** [comment] 2022-12-08 18:08
So the reason this happens is that you _are_ creating an infinite navigation loop in `DynamicPathGuard`. If the last path has `dynamic` in it, reject the navigation, and navigate again to the same path in a timeout. `dynamic-path.ts` is [violating the public API](https://github.com/angular/angular/blob/main/docs/PUBLIC_API.md) by casting the route to `any` and accessing a property marked as `@internal`. `_loadedConfig` no longer exists in recent versions. 

Closing as this is not a bug in Angular.

**Closed by atscott** 2022-12-08 18:08 UTC
Labels: area: router

**Comment by atscott** [comment] 2022-12-09 05:14
For what it’s worth, here’s the new internal property: https://github.com/angular/angular/blob/main/packages/router/src/utils/config.ts#L35

just fyi though, while it’s maybe unlikely to change again soon, it totally could and isn’t supported by our public api policy. I’d recommend writing a test case that would break if this property moves again so you at least know immediately where to look.

**Comment by patrickritskes** [comment] 2022-12-09 09:48
Hi @atscott,
Thanks for your reply and reviewing this issue!

As a developer: how do I know when this kind of API features are changing/gonna change?

It's easy to say, just write a test case to see if this setup gonna work in the future, especially when you are on your own in a very big application! We had a developer which had interested in Cypress, but is gone in the mean time!
I know I can't keep up with the semi-annual updates every time, will this change in the future?

How would you suggest to rewrite the `DynamicPathGuard`?

**Comment by atscott** [comment] 2022-12-09 16:53
> how do I know when this kind of API features are changing/gonna change?

There won't be any good signals outside of a test for things like this since the code deliberately ignores the real type by casting to `any`

> We had a developer which had interested in Cypress, but is gone in the mean time!

This test doesn't need to be an e2e test. In fact, an e2e test wouldn't give you what you want in this case other than a signal that something broke. What you should do for cases where you're circumventing visibility restrictions in a way that TypeScript won't detect would be to write a unit test that checks to ensure the property is still there.

```
it('has a _loadedConfig property', async () => {
  // Note that _loadedConfig is @internal in Angular. This test will fail and give an early indication that we need to update our code if Angular upstream changes the property name in some way.
    const router = TestBed.inject(Router);
    router.resetConfig([{ path: '', loadChildren: () => [] }]);
    await router.navigateByUrl('/');
    expect((router.config[0] as any)._loadedConfig).toBeDefined();
  )
});
```

**Comment by patrickritskes** [comment] 2022-12-12 07:45
Hi @atscott,

Thanks a lot for your reply, and your code example for the test!

And what kind of refactor do you like to see for the DynamicPathGuard?
I really have no clue how to refactor this part!

Thanks a lot in advance!

**Comment by atscott** [comment] 2022-12-12 15:47
> And what kind of refactor do you like to see for the DynamicPathGuard?

I would suggest asking for recommendations on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
