### ISSUE TITLE
To Create Modules, or Not to Create Modules -- Best Practice Guidance

### ISSUE THREAD

**Issue by mylifeandcode** [angular/angular#56754] opened 2024-06-28 13:54 UTC
### Describe the problem that you experienced

The current version of the style guide at [angular.dev](https://angular.dev/style-guide#app-root-module), on the topic of the app's root module, states "New applications should use standalone components, directives, and pipes instead." Yet other parts of the documentation seem a little more ambiguous. Should modules no longer be created? Is there never a use case for them? Feature modules provide value -- but is this value attainable via standalone components through a different mechanism?

### Enter the URL of the topic with the problem

[https://angular.dev/style-guide#app-root-module](https://angular.dev/style-guide#app-root-module)

### Describe what you were looking for in the documentation

Clarity on whether or not there are cases or best practice scenarios for the creation of new modules, or if the new standalone approach should _always_ be the case.

### Describe the actions that led you to experience the problem

I was looking for information on how to lazy load standalone components. I _did_ find this information, but became more confused about whether or not the practice of having feature modules was still valid in some scenarios.

### Describe what you want to experience that would fix the problem

Clearer best practices on standalone components vs feature modules.

### Provide any additional information here in as much as detail as you can

Just a "thank you". I've been using Angular for years and love it. In my role, I often have to evaluate, and re-evaluate, front end technologies. So far, I haven't been able to justify moving away from Angular.

**Comment by msmallest** [comment] 2024-06-28 17:00
Clearer/more consistent guidance on valid use cases of modules would definitely be nice. Most doc pages I have seen do a good job on this, but certain places I have seen before like [mylifeandcode](https://github.com/mylifeandcode) is referring to do give some ambiguity. 

In my opinion, two key things I think any guide on modules vs standalone should mention as a convention. Apologies if these points are already provided somewhere in the docs, but my point with the topic of this issue stands on the consistency of these points being mentioned or at least linked to on any given article mentioning standalone vs module.

- Equivalent standalone bootstrapping syntax. 
    - When modules vs standalone comes up in forums, in my experience this is one of the biggest questions people have. They will be following an old guide and the question asker will say something like "I get that I can make components/pipes/directives standalone, but I have no idea how I would do this thing that had to be in the root module". A good example page I know is out there is the standalone migration schematic page: https://angular.dev/reference/migrations/standalone#switch-to-standalone-bootstrapping-api
- New features which require standalone, such as deferrable views. 
    - Well, at least the caveat of ["You can use standalone and NgModule-based dependencies inside of a @defer block, however **only standalone components, directives, and pipes can be deferred**."](https://angular.dev/guide/defer#behavior-with-ngmodule) This one is a bit more subtle, as I have an idea of which new features require standalone but that is from keeping up with blog posts and whatnot. 
    - To be fair, I have worked on features that require standalone in only standalone apps, but I am not sure if there is explicit warnings or indicators in module apps that use features intended for standalone. In my experience these features mention the requirement of `standalone` on a page by page basis, but I am not sure if there is a blanket list of features. I think if that is not a page, it would be a good one to include, and I would be happy to make a PR to do so if I had some help making a definite list. 
    - I think as this standalone required feature paradigm becomes more common of a requirement, that is even more grounds for a definite more consistent stance across most pages, or at least linked to on pages that may mention some use cases of modules.

**Comment by mylifeandcode** [comment] 2024-06-28 18:05
Thanks for the feedback @msmallest! I try to follow the best practices, but in this scenario, I'm wondering: if I created a new application, would I never, _ever_ do so with modules again? It's that sort of guidance I'd love for the official docs to contain, helpful as they are.

**Comment by msmallest** [comment] 2024-06-28 19:04
My understanding of best practices of the Angular team and most of the community is to go fully standalone unless you have a really, really good reason to use modules. People really disagree if such a "good use case" of modules exist anymore. For said reason, in my opinion and many others' you probably aught to just use standalone unless you and your team have had a discussion on use cases where ngModules may be more appropriate.

- For example, some libraries now offer both modules and individual imports. In Angular Material, form elements such as a dropdown are made of various pieces that traditionally were bundled together in a module. For example, `MatInputModule` encompasses not just the input but also the label and error for the inputs, among other things which may not be necessary for certain use cases. So someone could opt to import `MatInput` and `MatLabel` and `MatError` rather than the whole `MatInputModule`. 
- However, many people such as my team consider that to be too annoying and confusing to be worth it, so we import the whole `MatInputModule`. And in a similar vein as libraries, app developers or teams with their own internal libraries may simply value colocation of components/directives/pipes in a module for certain features. However, if we made our own component which was not standalone, then we couldn't get the full benefits of `@defer`. 
- As a whole, my team uses almost entirely standalone but in a few cases have agreed upon using modules still. However, we acknowledge that some features in the future may not support modules. 
- For other people, that caveat of future features restriction as well as the optimization benefits are a sole decider to not use modules at all

Overall, most people will for good reason say to commit to standalone unless you have a very good reason.

**Comment by bleistift-zwei** [comment] 2024-06-29 18:35
FWIW, here’s my reason why I don’t use standalone components much. If this isn’t helpful for the discussion, I’ll delete the comment again.

My use case is CRUD functionality for lots of business objects (e.g., customers). I mostly write tables of customers, details pages of individual customers and forms to edit customers.

Over the years I’ve created lots of helper components that I use most of the time – a table that sort itself; a button that changes state when an async operation is under way; a component to unwrap an error message and show something helpful to the user, and so on.

If I went full-on standalone component, I would import all these things in about every third business component I’m writing, probably more often (for instance, the customers list view, customer details view and customer edit view all have async operations that need the button). Since importing dependencies is a manual process (at least VSCode doesn’t have auto-imports for directives I use in the component templates), standalone components would be very annoying.

Generating a feature module (for the customer CRUD functionality) and adding the helper modules as imports there is much less cumbersome than writing the dependencies for each and every component myself. This is especially true since the Angular CLI will automatically add all feature components to that module.

**Comment by mylifeandcode** [comment] 2024-07-01 12:43
@bleistift-zwei thanks for the input. I find the module approach to be ideal (for example, I have an admin module which is kept behind a route guard and lazily loaded), so switching over to standalone components is a drastic change in thinking for me. But it's these differences in perspective that lead me to really want an official best practice from the Angular team itself.

**Comment by JeanMeche** [comment] 2024-07-01 20:37
We're currently rewriting the style guide for a more up-to-date content. Stay tuned for some news in the near future. 

I'll close this as a duplicate of the umbrella issue #54284.

**Closed by JeanMeche** 2024-07-01 20:37 UTC
Labels: area: adev

**Comment by mylifeandcode** [comment] 2024-07-02 18:21
Thanks @JeanMeche !
