### ISSUE TITLE
New Lazy Load Module syntax in v8 after update causes compile error

### ISSUE THREAD

**Issue by bobskigit** [angular/angular#30799] opened 2019-06-01 12:20 UTC
### Is this a regression?

Not Applicable as new feature

### Description

I've upgraded a large angular project (using ngupdate) to v8 but the new lazy load method causes an error during compile.

Previous module load was

 {
    path: 'break',
   canActivate: [AuthGuard],
   loadChildren: './inventory/inventory.module#InventoryModule'
  },

**Converted to** 

 {
    path: 'break',
   canActivate: [AuthGuard],
   loadChildren: () => import('./inventory/inventory.module').then(mod => mod.InventoryModule)
  },
 

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/app-routing.module.ts 56:28
Module parse failed: Unexpected token (56:28)
You may need an appropriate loader to handle this file type.
|         path: 'break',
|         canActivate: [AuthGuard],
>         loadChildren: () => import('./inventory/inventory.module').then(mod => mod.InventoryModule)
|     },

</code></pre>

## 🌍  Your Environment

{
  "name": "raven4-ui",
  "version": "1.7.2",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "^8.0.0",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/platform-server": "^8.0.0",
    "@angular/pwa": "^0.800.0",
    "@angular/router": "^8.0.0",
    "@angular/service-worker": "^8.0.0",
    "@fortawesome/fontawesome-free": "^5.8.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@schematics/angular": "^8.0.0",
    "@types/socket.io-client": "^1.4.32",
    "angular-gtag": "^1.0.3",
    "angular-in-memory-web-api": "^0.8.0",
    "core-js": "^3.1.3",
    "devextreme": "^19.1.3",
    "devextreme-angular": "^19.1.3",
    "devextreme-intl": "^19.1.3",
    "file-saver": "^2.0.2",
    "guid-typescript": "^1.0.9",
    "jshint": "^2.10.2",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "ngx-img-fallback": "^1.3.3",
    "ngx-moment": "^3.4.0",
    "ngx-socket-io": "^2.1.1",
    "ngx-translate-testing": "^2.0.0",
    "npm-cli": "^0.1.0",
    "rxjs": "^6.5.2",
    "socket.io": "^2.2.0",
    "tslib": "^1.9.3",
    "tslint": "^5.16.0",
    "typescript": "^3.4.5",
    "xlsx": "^0.14.3",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.800.1",
    "@angular/cli": "^8.0.1",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^12.0.3",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.2",
    "ts-node": "^8.2.0",
    "webpack-bundle-analyzer": "^3.3.2"
  }
}

**Comment by trotyl** [comment] 2019-06-01 12:29
Duplicate of https://github.com/angular/angular-cli/issues/14566

**Closed** 2019-06-04 22:18 UTC
