### ISSUE TITLE
Unexpected behavior when querying for TempplateRef

### ISSUE THREAD

**Issue by sd-git** [angular/angular#56713] opened 2024-06-26 14:22 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using combination of ng-template and ng-container with ngTemplateOutlet, contentChildren return unexpected results (more TemplateRef items when it should)

The best way to see/understand the issue is to look at the minimal example.
There is one line with ng-container to be uncommented to trigger this issue.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-xxnvsg?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.5
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.5
@angular-devkit/build-angular   18.0.5
@angular-devkit/core            18.0.5
@angular-devkit/schematics      18.0.5
@angular/cli                    18.0.5
@schematics/angular             18.0.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by pkozlowski-opensource** [comment] 2024-06-26 14:42
Thnx for reporting - it does look like a bug that needs more investigation.

**Comment by pkozlowski-opensource** [comment] 2024-07-10 12:11
A simpler reproduction scenario: https://stackblitz.com/edit/stackblitz-starters-zcd4i8?file=src%2Fmain.ts

**Comment by pkozlowski-opensource** [comment] 2024-07-10 12:31
OK, so this "works as designed", although definitively _not_ "as expected". 

What is going on here is that `<ng-template>` is special and somewhat "transparent" to the `{ descendants: false }` option. This is mostly done to support cases like `<ng-template [ngIf]="cond"><ng-template></ng-template></ng-template>` or, more importantly: `<ng-template [ngIf]="cond"><div #target></div></ng-template>`. See: https://stackblitz.com/edit/stackblitz-starters-yndzup?file=src%2Fmain.ts 

Interestingly, this scenario is even more "broken" with the built-in control flow, as seen in the stackblitz. 

It is not clear to me yet what is the best fix here as there is some ambiguity over _what_ should match, needs more thinking. At this point I can confirm that we've got a minimal reproduction scenario and this can be very confusing.

**Comment by pkozlowski-opensource** [comment] 2024-07-10 15:05
Discussing it more we've decided to fix the 

```
<needs-ng-template>
      @if (true) { <!-- <ng-template> -->
        <ng-template></ng-template>
      }
</needs-ng-template>
```

**Comment by pkozlowski-opensource** [comment] 2024-07-11 09:42
This is really a duplicate of the existing issue #13893 - I will add more context about the built-in control flow in there. 

Duplicate of #13893

**Closed by pkozlowski-opensource** 2024-07-11 09:42 UTC
Labels: area: core, core: queries, P3, bug
