### ISSUE TITLE
Make more descriptive errors for directives' errors in AOT build

### ISSUE THREAD

**Issue by IgorKurkov** [angular/angular#32640] opened 2019-09-12 16:51 UTC
angular/angular-cli#11187 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
AOT show errors of internal directives like HostListener, HostBinding in not so descriptive way like
 `(1,1): : Directive IntroComponent, Expected 0 arguments, but got 1`
BTW (1,1) line in the message is also invalid, as I understand it check values inside directives after optimizations. The reason for this issue was a lot of questions on StackOverflow with no solution due to not so clear error message.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
I suggest doing more descriptive error messages for errors like 
`(25,34): : Directive HostListener inside IntroComponent, Expected 0 arguments, but got 1`
and check them before angular optimizations

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by JoostK** [comment] 2020-11-07 21:38
Closing as a duplicate of #21329.

**Closed by JoostK** 2020-11-07 21:38 UTC
Labels: comp: compiler, feature
