### ISSUE TITLE
routerLinkActive CSS class not getting added in case links are generated using lists and routerLink value is coming from a Service

### ISSUE THREAD

**Issue by manjari09** [angular/angular#41643] opened 2021-04-15 11:36 UTC
Hello Team,

I want to highlight the active link in my application and for this I am also using routerLinkActive and routerLinkActiveOptions. I have my anchor links getting generated from a list - 
```
<a
            *ngFor="let navItem of navigation"
            class="header-item"
            [routerLink]="['./']"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: false }"
            (click)="navigationService.navigateTo(navItem)"
          >
            {{ navItem.navName }}
          </a>
```
I have a requirement to add a border-bottom when the link is active. I tried searching with an empty `routerLink` and that's what I have added as well, but it is adding the class even when the link is not clicked.
Kindly help.

**Comment by atscott** [comment] 2021-04-15 16:13
Closing as working as intended. `routerLinkActive` is intended to work in conjunction with `routerLink`. Because your `routerLink` does not reflect the route that your service will navigate to, this will not work. You should update the input of the `routerLink` to use whatever URL the navigationService is going to navigate to; possibly add `navigationService.getNavigationUrl(navItem)`

**Closed by atscott** 2021-04-15 16:13 UTC
Labels: comp: router
