### ISSUE TITLE
Angular 2 "ng build --prod" errors

### ISSUE THREAD

**Issue by maiziheimei** [angular/angular#20591] opened 2017-11-22 19:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

angular 2 + material project works fine on localhost;
project "ng build" works, but "ng build --prod" has the following errors,
<img width="1258" alt="screen shot 2017-11-22 at 20 10 04" src="https://user-images.githubusercontent.com/25683284/33145570-2c701ce0-cfc1-11e7-8b50-ed2510ea28b9.png">

## Expected behavior

wish "ng build --prod" build successfully.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by ericmartinezr** [comment] 2017-11-22 19:12
https://github.com/angular/angular/issues/20095

**Comment by aravindfz** [comment] 2017-11-23 06:25
Can we close this as it is duplicate of the above mentioned @gkalpak

**Comment by maiziheimei** [comment] 2017-11-23 11:01
Yes, this issue can be closed . It solved by updating typescript's version

**For Exact version
npm install typescript@2.0.10 --save
**For latest release
npm install typescript@latest --save

**Closed** 2017-11-23 11:12 UTC
