### ISSUE TITLE
FEATURE: import 'types' in templates using new block syntax

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#53553] opened 2023-12-13 17:11 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

New Angular block syntax is awesome and it is something that runs at compile time.

Would it be possible to have i dont know lets call it `import` statement. This statement will allow to import 'types' like enums or other static types that would be good to have inside templates. Right now when you want to use Enum inside template you have to assign it to some components property. But something like this would be useful.

```
@import {AwesomeEnum} from './myRelativePath';
or
@import {AnotherAwesomeEnum} from 'my-lib';
```

### Proposed solution

Since templates are compiled into code that sits next to components code this new block syntax would just add another import into same file and it should not have any problem to work. 

### Alternatives considered

Dont have alternatives.

**Comment by xXNickznXx** [comment] 2023-12-20 02:17
Isn't this more or less a duplicate of this issue? https://github.com/angular/angular/issues/25963
And it's a cleaner solution as it only requires one import statement when used in TS too

**Comment by pkozlowski-opensource** [comment] 2024-01-03 10:29
Yes, this is exact duplicate of https://github.com/angular/angular/issues/25963 which describes the underlying problem. The new block syntax might or might not be the solution there - but we will tackle the exact design when focusing on #25963 - in any case we are very much aware of the pain point here.

**Closed by pkozlowski-opensource** 2024-01-03 10:29 UTC
Labels: feature, area: core, core: basic template syntax, feature: votes required
