### ISSUE TITLE
Lazy load auxilary #10981

### ISSUE THREAD

**Issue by vottens** [angular/angular#24562] opened 2018-06-18 14:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When i navigate to a child auxilary route within an lazy loaded route i receive the error:
Error: Cannot match any routes. URL Segment: 'aux-route-name'

## Expected behavior

I would like to do the following:

**lazy.module.ts**

```
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { NgModule } from '@angular/core';
import { LazyComponent } from './lazy.component';
import { Aux1Component } from './aux1/aux1.component';
import { Aux2Component } from './aux2/aux2.component';
import { Aux3Component } from './aux3/aux3.component';

const routes = [
  {
    path: '',
    component: LazyComponent,
    children: [
      {
        path: 'aux1',
        component: Aux1Component,
        outlet: 'aux'
      },
      {
        path: 'aux2',
        component: Aux2Component,
        outlet: 'aux'
      },
      {
        path: 'aux3',
        component: Aux3Component,
        outlet: 'aux'
      }
    ]
  }
];

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(routes),
  ],
  declarations: [
    LazyComponent,
    Aux1Component,
    Aux2Component,
    Aux3Component,
  ],
  exports: [
    LazyComponent,
    Aux1Component,
    Aux2Component,
    Aux3Component,
    RouterModule
  ]
})
export class LazyModule { }
```

## Minimal reproduction of the problem with instructions

Failing (nameless route):
https://stackblitz.com/edit/lazy-load-auxilary-failing

Workaround:
https://stackblitz.com/edit/lazy-load-auxilary-workaround

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [X] Chrome (desktop) version 67.0.3396.87
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.2
- Platform:  Windows 10

Others:

</code></pre>

**Comment by trotyl** [comment] 2018-06-19 02:49
Aux lazy loading was fixed in `6.1.0-beta.1`, while your demo version is below this one. Please fix your repro first.

**Comment by vottens** [comment] 2018-06-19 07:11
If fixed the repo, it is now based on 6.1.0-beta.1, the issue stays the same. I had of course checked this beforehand.

**Comment by trotyl** [comment] 2018-06-19 10:15
I changed your demo to use eager loading and it still raise the same error:

https://stackblitz.com/edit/lazy-load-auxilary-pbljur?file=app%2Fapp.module.ts

No idea how is this related to lazy loading.

**Comment by vottens** [comment] 2018-06-19 10:42
If you change lazy.component.html to:
`
<a [routerLink]="['/']">
  home
</a>
&nbsp;
<a [routerLink]="[{ outlets: { aux: ['aux1'] } }]">
  aux1 route
</a>
&nbsp;

<a [routerLink]="[ { outlets: { aux: ['aux2'] } }]">
  aux2 route
</a>
&nbsp;

<a [routerLink]="[ { outlets: { aux: ['aux3'] } }]">
  aux3 route
</a>

<router-outlet name="aux"></router-outlet>

`

Than the routing works.

**Comment by vottens** [comment] 2018-06-19 10:43
But now it is not lazy loaded

**Comment by codefactorydevelopment** [comment] 2018-06-19 12:33
This is exactly my problem too.

**Comment by vottens** [comment] 2018-06-19 12:44
I'm glad that i'm not the only one :)

**Comment by gmfun** [comment] 2018-06-21 17:24
Made this reproduce the issue
https://stackblitz.com/edit/lazy-load-auxilary-wy2zci?file=app/app.module.ts

the '/' url
https://lazy-load-auxilary-wy2zci.stackblitz.io
throws an error
`TypeError: Cannot read property 'routes' of undefined`

But lazy loaded route in different outlet works fine.
https://lazy-load-auxilary-wy2zci.stackblitz.io/(aux:lazy)

If I remove the lazy loaded route, the '/' url works fine.

**Comment by vottens** [comment] 2018-06-22 10:12
@jasonaden Is the description of this problem clear enough for you to get started? Otherwise I can give you more information if needed ...

**Comment by MauroSalvadori** [comment] 2018-07-05 14:17
We are facing exactly the same problem already from months... still now no lucky to find a workaround if not eager loading the module. This is a "must have" feature!

**Comment by adrienlamotte** [comment] 2018-07-16 14:15
I'm facing the same problem, but I'm using a workaround.
@vottens Here is a fork of your stackblitz : https://stackblitz.com/edit/lazy-load-auxilary-1eyvfr

I just changed the lazy loaded routes to not use an empty path...

```
const routes = [
  {
    path: 'fix', // <--- Here
    component: LazyComponent,
    children: [
      {
        path: 'aux1',
        component: Aux1Component,
        outlet: 'aux'
      }
    ]
  }
];
```

**Comment by jasonaden** [comment] 2018-07-17 22:43
@vottens Thanks. A bit more info would be great on this one. I took a quick look at the linked reproduction, but wasn't immediately clear on what the problem is and how it seems it should work.

Maybe just add some info like that and hopefully it can be a quick fix.

**Comment by thierryQuantech** [comment] 2018-07-19 09:29
I tried finding a temporary fix by adding another "hidden" lazy-loaded module which loads the outlets. This **did not work**, but I wanted to document it in case someone else would have thought it might fix the problem. The following should give you the idea: 
`
  {
    path: 'lazy',
    loadChildren: '../lazy/lazy.module#LazyModule',
  },
  {
    path: 'aux1',
    component: Aux1Component,
    outlet: 'aux'
  },
  {
    path: 'aux2',
    component: Aux2Component,
    outlet: 'aux'
  },
  {
    path: 'aux3',
    component: Aux3Component,
    outlet: 'aux'
  }
[...]
export class HiddenModule { }
`

this did not help

**Comment by michalstepien** [comment] 2018-07-19 18:37
can anyone confirm if such routing will work?
`const routes = [ { 
 path: 'lazy', 
 loadChildren: '../lazy/lazy.module#LazyModule', 
 outlet: 'aux' 
} ]`

**Comment by Nilpointer** [comment] 2018-07-25 08:55
@adrienlamotte I can confirm not using empty path in lazy loaded module routing is working.

**Comment by vottens** [comment] 2018-07-25 10:09
Hi Guys, sorry for not responding for so long, i was on holiday! I can confirm as well that using a named route instead of a nameless route fixes the issue. I still think it would be nice to have the abillity to use a nameless route in this situation. Maybe this is a easy fix? @jasonaden I added a link to a failing and to a working version of my stackblitz app

**Comment by vottens** [comment] 2018-07-25 10:13
Failing (nameless route):
https://stackblitz.com/edit/lazy-load-auxilary-failing

Workaround:
https://stackblitz.com/edit/lazy-load-auxilary-workaround

**Comment by jasonaden** [comment] 2018-08-23 22:16
@vottens Thanks for the failing and the workaround.

I'm moving this issue into our backlog so it can be prioritized. Right now I'm pretty heads-down on some other fixes, but hopefully this can get pulled in in the not-too-distant future.

**Comment by TGC79** [comment] 2019-01-23 21:51
Caused by #10726 which should be reopened since the fix for it was reverted.

Issue was first reported on Angular 2.0.0-rc.5.

**Comment by DaSchTour** [comment] 2020-01-27 08:24
This is still an issue. Don't close this like https://github.com/angular/angular/issues/10726

**Comment by atscott** [comment] 2020-05-27 15:03
Based on the discussion in this thread, this appears to be a duplicate of #10726. As mentioned, the fix for that issue was reverted so I have reopened and unlocked the conversation there. Closing this one so we don't have multiple issues tracking the same bug.

**Closed by atscott** 2020-05-27 15:03 UTC
Labels: comp: router, freq3: high, jira-sync, severity3: broken, type: bug/fix
