### ISSUE TITLE
Page link is broken

### ISSUE THREAD

**Issue by brahmajitammana** [angular/angular#53610] opened 2023-12-17 13:16 UTC
### Describe the problem that you experienced

In step 1, there is an inline link on text called " [type inference in TypeScript](https://angular.dev/typescript.org/type-inference)."

It is currently navigating to https://angular.dev/tutorials/learn-angular/updating-the-component-class instead of actual one (which is missing)

### Enter the URL of the topic with the problem

https://angular.dev/tutorials/learn-angular/updating-the-component-class

### Describe what you were looking for in the documentation

We need to fix the documentation link

**Comment by JoostK** [comment] 2023-12-17 13:18
Thanks for the report, this is a duplicate of https://github.com/angular/angular/issues/52553 for which the fix is pending deployment.

**Closed by JoostK** 2023-12-17 13:18 UTC
