### ISSUE TITLE
ContentChild(NgModel) doesn't work anymore

### ISSUE THREAD

**Issue by Granaat** [angular/angular#35294] opened 2020-02-10 11:54 UTC
# 🐞 Bug report

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: v8

### Description
The following contentchild code doesn't seem to work anymore.
It should fetch an input item from a dynamically loaded component.

@ContentChild(NgModel) model !: NgModel 

## 🔬 Minimal Reproduction
<pre><code>
<ng-container #container></ng-container>

@ViewChild('container', { read: ViewContainerRef, static: true }) private container !: ViewContainerRef
  @ContentChild(NgModel) model !: NgModel

ngOnInit() {
...
// insert dynamic component into container
this.generateComponent(this.newFormItem.type)
...
}

 ngAfterContentInit() {
// -> ERROR
    this.formModel = this.model.control
}
</code></pre>

## 🔥 Exception or Error
<pre><code>
typeError: Cannot read property 'control' of undefined
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.8.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      8.2.3
@angular/cli                      9.0.1
@angular/http                     7.2.15
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-02-10 13:25
It is, most likely, a duplicate of #34768 but we can't be sure without a reproduce scenario / seeing a template being queried. 

Please provide a reproduce scenario so we can investigate / advise.

**Comment by pkozlowski-opensource** [comment] 2020-02-12 10:26
We haven't heard back with the reproduce scenario so I'm going to close this one as a duplicate of #34768

**Closed by pkozlowski-opensource** 2020-02-12 10:26 UTC
Labels: comp: ivy, state: Needs repro
