### ISSUE TITLE
angular 9 / Ivy => async 'as' leads to error

### ISSUE THREAD

**Issue by mpalourdio** [angular/angular#34405] opened 2019-12-14 07:40 UTC
# 🐞 bug report

### Affected Package
https://github.com/mpalourdio/ng2

### Is this a regression?
Yes, the previous version in which this bug was not present is angular8@latest.

### Description

```html
<div id="app" *ngIf="(applicationsList$ | async) as applicationsList">
    <app-search-filter [(applicationsList)]="applicationsList"></app-search-filter>
</div>
```

`yarn start`

Error :  `Property 'applicationsList' does not exist on type 'ChildComponent'. Did you mean 'applicationsList$'?`

**Disabling Ivy** leads to

`ERROR in Cannot assign value "$event" to template variable "applicationsList". Template variables are read-only.`

## 🔬 Minimal Reproduction

- clone https://github.com/mpalourdio/ng2
- run ` ng update @angular/cli @angular/core --next`
- yarn start

## 🔥 Exception or Error
<pre><code>
 Property 'applicationsList' does not exist on type 'ChildComponent'. Did you mean 'applicationsList$'?
</code></pre>

**Disabling Ivy** leads to

`ERROR in Cannot assign value "$event" to template variable "applicationsList". Template variables are read-only.`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.13.0
OS: linux x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

---
**EDIT (by gkalpak)**

Adding the conclusions from https://github.com/angular/angular/issues/34405#issuecomment-566134215 (after the discussion below) here for visibility:

> The issue is that this breaking change is not (clearly) documented, so let's keep this open to track that :smiley:
>
> Action items:
> - [ ] Figure out what the breaking change is exactly (incl. how template variables created via `as` are different from other template variables).
> - [ ] Document that.

**Comment by alexzuza** [comment] 2019-12-14 15:38
Looks like it was made intentionally according to [Ivy Compatibility Guide](https://next.angular.io/guide/ivy-compatibility)

> It is now an error to assign values to template-only variables like item in ngFor="let item of items" (previously, the compiler would ignore these assignments).

**Comment by mpalourdio** [comment] 2019-12-14 16:10
Thanks for the answer. Looks like a rough BC break, as this pattern looks very common to me. Anyway, how are we supposed to refactor this kind of code ?

And as I said, it does not look like ivy specific, as disabling Ivy pops an error too regarding tempalte variable assignment.

Thanks again for feedback.

**Comment by gkalpak** [comment] 2019-12-14 17:28
It is not clear what you are trying to achieve (i.e. what the expected/ideal behavior would be) with `[(applicationsList)]="applicationsList"`.

Just to be clear, the error is not related to `async ... as` (as mentioned in the title), but to the following bit of code:

```html
<app-search-filter [(applicationsList)]="applicationsList"></app-search-filter>
```

This is syntactic sugar for a [two-way binding][1]. It is equivalent to:

```html
<app-search-filter [applicationsList]="applicationsList" (applicationsListChange)="applicationsList = $event"></app-search-filter>
```

It's this second part (`(applicationsListChange)="applicationsList = $event"`) that seems to be causing the error. It is not clear what you are trying to achieve by setting the template `applicationList` variable to the filtered result of itself. Maybe the example you gave is contrived and does not reflect the actual usecase. Could you, please, clarify the usecase?

(Finally, as mentioned in the guide, the compiler would previouly ignore the assignments, so this change will not break something the used to work before. It will only turn silent failing at runtime to hard failing at compile time.)

[1]: https://angular.io/guide/template-syntax#two-way-binding-

**Comment by JoostK** [comment] 2019-12-14 22:24
The error in Ivy was incorrect, this has been resolved in #34339 (which just missed the rc.6 release).

Other than that: what @gkalpak said :-)

**Comment by mpalourdio** [comment] 2019-12-14 23:59
> It's this second part (`(applicationsListChange)="applicationsList = $event"`) that seems to be causing the error. It is not clear what you are trying to achieve by setting the template `applicationList` variable to the filtered result of itself. Maybe the example you gave is contrived and does not reflect the actual usecase. Could you, please, clarify the usecase?
> 
Indeed, this repository is just a sandbox to experiment misc things quick and dirty. The full code is irrelevant (even if working with angular 8) and clumsy.

The main idea is just giving the aliased ('as') observable (an array of strings) from a parent component to a child component, filtering the array in the child component, and with the 'banana in the box', displaying the filtered array in the parent component. This is something that works today with ng8, it does not fail silently at runtime as you suppose it does. Again, It's not a real world app, but it just works.

>. It will only turn silent failing at runtime to hard failing at compile time.)

It just does not fail at runtime today :)

**Comment by JoostK** [comment] 2019-12-15 00:16
Thanks for clarifying. That sounds weird, though. Could you show how the filtering is done? What is important here is whether that is done by mutating an array or by creating a new one.

**Comment by mpalourdio** [comment] 2019-12-15 00:19
This is done here : https://github.com/mpalourdio/ng2/blob/7f3a9b6114c04b37c664fe55a73ee1bd06fa061d/src/app/search-filter/search-filter.component.ts#L33

Feel free to just clone this repo, running it on ng8 (current yarn.lock), and upgrading it to angular@next if needed.

**Comment by JoostK** [comment] 2019-12-15 00:31
@mpalourdio I am _amazed_ this ever worked!

**Comment by mpalourdio** [comment] 2019-12-15 00:37
That's what makes angular amazing :). Apart the very poor code quality, what is fondamentally wrong here?

**Comment by gkalpak** [comment] 2019-12-16 15:22
I created this [StackBlitz project][1] and it does indeed work with v8 💥
Maybe the variables created via `as` were treated differently than other template-only variables in v8.

So, this sounds like a breaking change that needs to be documented. @JoostK, do you know what's the case for template variables created via `as` in v8 vs v9?

##
> Apart the very poor code quality, what is fundamentally wrong here?

@mpalourdio: This seems like a big anti-pattern (and I hope it is not as common as you say 😅).

The main issue I see is that the `[(...)]` binding indicates a two-way-binding relation. Typically, the expectation is that the value is passed into the child-component (the `[...]` part of the binding) and the child component reacts to this.

So, my expectation when I first looked at the component (and the reason I immediately thought "this can't be right" :grin:) was that `applicationList` goes into the child-component (due to the `[...]` part of the binding), then gets filtered inside the child-component and emitted back, the filtered list gets assigned to the template `applicationList` variables (via the `(...)` part of the binding), then the filtered `applicationList` gets back into the child-component (via the `[...]` part of the binding), where it gets filtered again and emitted back, etc.

The only reason the component works in this case is that it uses the `[...]` binding to initialize its internal state and does not react to changes in the input value. This is, of course, an implementation detail of the child-component and the consumer (parent component) shouldn't have to know about it. Hence, from the consumer's perspective, using `[(...)]` looks very unintuitive.

In addition, you open yourself up to all sorts of subtle bugs, such as:

- If `applicationList$` emits another array, the `search-filter` component will still be using the original list, giving incorrect results.

Of course, you can work around them, but the point is that the parent-component behavior may change due to the implementation of a child-component and detailed knowledge of the child-component's implementation is needed in order to make the parent-component/template work as intended.

[1]: https://stackblitz.com/edit/ng-issue-34405

**Comment by mpalourdio** [comment] 2019-12-16 15:37
That's really clear for me! Thanks a lot for these great explanation, and for taking time to investigate. So far, again, that's really a quick and dirty project and I wanted to give feedback on the migration path.

Feel free to close this issue, as it's really not an issue ('cause I am the issue :p).

Thanks again!

**Comment by gkalpak** [comment] 2019-12-16 16:24
The issue is that this breaking change is not (clearly) documented, so let's keep this open to track that :smiley:

Action items:
- [ ] Figure out what the breaking change is exactly (incl. how template variables created via `as` are different from other template variables).
- [ ] Document that.

**Comment by danielehrhardt** [comment] 2020-01-20 23:08
![image](https://user-images.githubusercontent.com/19570043/72763031-1f2e5800-3be2-11ea-9359-8832ae2534ae.png)

`<app-property-video *ngIf="property.name == 'video'" [(ngModel)]="property"></app-property-video>
`

**Comment by surenrao** [comment] 2020-01-30 18:21
Will [NgTemplateOutlet](https://next.angular.io/api/common/NgTemplateOutlet) need updating ?
Specially for part `<ng-container *ngTemplateOutlet="svk; context: myContext"></ng-container>
<ng-template #svk let-person="localSk"><span>Ahoj {{person}}!</span></ng-template>`  how is this going to be effected? cause i am getting `ERROR in Cannot assign value $event" to template variable "person". Template variables are read-only`

**Comment by andzejsw** [comment] 2020-02-07 14:04
I am just replacing these places with method calls, where i am setting needed vars.

**Comment by Gztabo21** [comment] 2020-03-06 14:51
hola en mi caso mi error era por que tenia esto asi :
<mat-option *ngFor="let terminal of terminals"  [(value)]="terminal">{{terminal.Name}}</mat-option>
lo que hice  para solventar fue cambiar el value a la siguiente manera:
<mat-option *ngFor="let terminal of terminals"  value="{{terminal}}">{{terminal.Name}}</mat-option>

hello in my case my mistake was because I had this like this:
<mat-option * ngFor = "let terminal of terminals" [(value)] = "terminal"> {{terminal.Name}} </mat-option>
What I did to solve was to change the value as follows:
<mat-option * ngFor = "let terminal of terminals" value = "{{terminal}}"> {{terminal.Name}} </mat-option>

**Comment by DomEscobar** [comment] 2020-05-08 10:52
Im curious if this is an anti-pattern, how do you do this instead?

![image](https://user-images.githubusercontent.com/29872817/81398997-96a0dc80-912a-11ea-88ed-b0b1ee951be1.png)

thanks you

**Comment by Splaktar** [comment] 2020-05-21 00:31
> Will [NgTemplateOutlet](https://next.angular.io/api/common/NgTemplateOutlet) need updating ?
> Specially for part
> 
> ```
> <ng-container *ngTemplateOutlet="svk; context: myContext"></ng-container>
> <ng-template #svk let-person="localSk"><span>Ahoj {{person}}!</span></ng-template>
> ```
> 
> how is this going to be effected? cause i am getting `ERROR in Cannot assign value $event" to template variable "person". Template variables are read-only`

No, this is not related to this issue as it does not use the `async` pipe. Template variables are read-only by design in Ivy.

**Comment by Splaktar** [comment] 2020-05-21 00:37
> Im curious if this is an anti-pattern, how do you do this instead?
> 
> here is a stackblitz (look console output)
> https://stackblitz.com/edit/angular-ivy-taatzh

1. You can make your card a separate, dumb component that has an input that takes `deviceGroup`.
1. You can resolve the Observable in a component or service and provide that reference to the template instead.
1. With Reactive Forms, you can resolve the Observable in a component or service and use that to set the value of the `FormControl`

Basically, you just need to stash that value somewhere other than a template variable.

**Comment by jelbourn** [comment] 2020-10-19 20:55
Closing since it seems like this was a change for v9 and we're already pretty far out from that and it seems like this haven't been an issue that has affected a large number of users.

**Closed by jelbourn** 2020-10-19 20:55 UTC
Labels: comp: core, core: binding & interpolation, engine: ivy
