### ISSUE TITLE
Create guide for debugging with ng

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35401] opened 2020-02-13 03:36 UTC
# 📚 Docs or angular.io bug report

### Description

See details here of some
Things we can do https://dev.to/azure/debug-angular-9-in-60-seconds-5h8k

**Comment by kapunahelewong** [comment] 2020-02-13 21:31
Nice article! Thank you, @johnpapa!

**Comment by aikidave** [comment] 2021-05-26 21:44
Thanks @johnpapa! I will look into adding this as a tutorial or topic!

**Comment by mgechev** [comment] 2022-03-21 23:44
Looks like duplicate of https://github.com/angular/angular/issues/35407#issuecomment-1074530265.

**Closed by mgechev** 2022-03-21 23:44 UTC
Labels: feature, comp: docs, freq2: medium, P4, insufficient votes, votes required
