### ISSUE TITLE
ADD. CONTENTEDITABLE. SUPPORT.

### ISSUE THREAD

**Issue by kassimir** [angular/angular#25507] opened 2018-08-15 18:45 UTC
It's been so many years now, and this still isn't supported. The current workarounds focus on the ngModel aspect of this not working, but I need to be able to toggle contenteditable based on certain variables. But I can't. Because this is STILL not supported.

**Comment by pkozlowski-opensource** [comment] 2018-08-16 09:49
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #9796. Please subscribe to that issue for future updates.

**Closed by pkozlowski-opensource** 2018-08-16 09:49 UTC

**Comment by kassimir** [comment] 2018-08-16 10:12
That’s not actually what this issue is about. See how that issue is in regards to ngModel, but mine explicitly states it’s not about ngModel? About how I just need to toggle contenteditable based on certain criteria? Basically just add a contenteditable binding. Boom. Problem solved.

**Comment by pkozlowski-opensource** [comment] 2018-08-16 10:17
> About how I just need to toggle contenteditable based on certain criteria? Basically just add a contenteditable binding. Boom. Problem solved.

I'm confused. Are you saying that `[contentEditable]="condition"` doesn't work for you? Or that you've figured it out?

We can avoid those types of misunderstandings by following the issue template. If you still see the bug please provide a minimal reproduce scenario in stackblitz or similar.

**Comment by kassimir** [comment] 2018-08-17 14:28
That is correct. That's why it's stated in my initial comment. The template is really unnecessary, since I adequately explained the issue:

> The current workarounds focus on the ngModel aspect of this not working, but I need to be able to toggle contenteditable based on certain variables. 

I don't know why I would need an entire template for that one line that 100% explains the problem.

**Comment by pkozlowski-opensource** [comment] 2018-08-17 15:05
@kassimir could you please provide a minimal reproduce scenario your problem in a stackblitz? I can't reproduce here: https://stackblitz.com/edit/angular-xhlstl?file=src%2Fapp%2Fapp.component.ts
