### ISSUE TITLE
docs: Components with ChangeDetectionStrategy.OnPush are marked for check by events as well

### ISSUE THREAD

**Issue by davityle** [angular/angular#12865] opened 2016-11-14 19:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When listening to a native event such as `(window:mousemove)` the component is marked for check. 

**Expected behavior**

> When using OnPush detectors, then the framework will check an OnPush component when any of its input properties changes, when it fires an event, or when an observable fires an event

**Note:** It says that the angular will only check it if an input changes, it fires an output, or an observable fires an output. I can see how this could be considered an `observable` but I wouldn't think of a native event as `observable`.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/CEDANBqgbbKkBHSkHnDk?p=preview

**What is the motivation / use case for changing the behavior?**
If a component wants to listen to a native event it has to manually listen to that event using browser apis if it wants to avoid the change detector. This isn't great.

**Please tell us about your environment:**

* **Angular version:** 2.0.X
2.0.2, 2.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by awerlang** [comment] 2016-12-17 22:52
A detached change detector provides you a way to customize this process.
Just `detach()` and then call `detectChanges()` whenever you see fit.

See https://plnkr.co/edit/QdRqYoa7QPB6P4MrPSH5?p=preview

Does that help?

**Comment by davityle** [comment] 2016-12-21 20:38
I'm seeing some really weird behavior when using components that `detach()` their change detectors in components that do not use `detach()`. https://plnkr.co/edit/ygurb3bZ48QWRWT0jhrP?p=preview is a plunker demonstrating some of that weird behavior. 

As you can see in the plunker, if a component (with ChangeDetectionStrategy.OnPush) has a child component that detaches its changedetector and doesn't feed an input to that child then the child will never update. If it has an input to the child then the child will update but will only update for a small portion of the number of actual events. It will also still cause it's parent changedetector to be run.

**Comment by awerlang** [comment] 2016-12-21 21:38
> If it has an input to the child then the child will update but will only update for a small portion of the number of actual events.

I think that's a bug. Because as stated in the docs:

> The detached change detector will not be checked until it is reattached.

**Comment by davityle** [comment] 2016-12-22 05:40
Should I open a new issue?

**Comment by awerlang** [comment] 2016-12-22 14:42
I would, as it's a different request.

**Comment by vsavkin** [comment] 2016-12-22 21:22
It looks like the docs aren't correct.

Angular will call markForCheck when a component's inputs change, any of its host listeners is invoked, or an event in its template is fired.

**Comment by awerlang** [comment] 2016-12-22 21:35
> Angular will call markForCheck when a component's inputs change, any of its host listeners is invoked, or an event in its template is fired.

That's a regular OnPush component, right? 

What about for a component with a detached change detector? At the moment, it seems that it is not checked for `host listeners is invoked, or an event in its template is fired`. Only when a component have inputs, have been changed or not, they are checked.

Just wondering if that makes sense, an OnPush strategy AND a detached change detector.

**Comment by awerlang** [comment] 2016-12-22 21:48
Removing OnPush strategy seems to fix that weirdness @davityle mentions at https://github.com/angular/angular/issues/12865#issuecomment-268633056. Still, detached & angular listener don't play as documented.

https://plnkr.co/edit/SrLiVvO0nofHuv85ETaZ?p=preview

**Comment by tbosch** [comment] 2017-04-10 23:08
Also see https://github.com/angular/angular/issues/9720

**Comment by tbosch** [comment] 2017-04-12 15:28
Changing to be a docs issue.

**Comment by wardbell** [comment] 2017-06-24 00:13
There is no documentation of `OnPush` strategy in the guides yet.

**Comment by kapunahelewong** [comment] 2018-02-05 19:47
A writer will need to work with an engineer to document this correctly. Probably needs a higher level conversation and PM planning as the level of effort will be notable. fyi @jenniferfell

**Comment by jenniferfell** [comment] 2018-05-08 23:33
docsarea=changedetection
https://angular.io/guide/testing
https://angular.io/api/core/ChangeDetectionStrategy
https://angular.io/api/core/ChangeDetectorRef

**Comment by zuzusik** [comment] 2018-11-07 12:20
it would be really nice to have proper docs/guides for ChangeDetectionStrategy

**Comment by aikidave** [comment] 2021-05-21 18:14
Duplicate of 33731

**Comment by petebacondarwin** [comment] 2021-05-21 18:39
@aikidave should this be closed then?

**Comment by aikidave** [comment] 2021-05-21 18:42
Yes, I'll close this. (Thought duplicating did that automatically. My mistake!)

**Closed by aikidave** 2021-05-21 18:42 UTC
Labels: P4, comp: docs, comp: docs/api, feature, freq2: medium, subtype: docs-clarification, subtype: docs-completeness
