### ISSUE TITLE
docs: API reference should also include global/ambient object names included in sfx bundles

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#3651] opened 2015-08-14 20:27 UTC
For example, [this bundle](https://code.angularjs.org/2.0.0-alpha.34/angular2.sfx.dev.js) exports the "angular2/angular2" module as `ng`, but if I'm a user looking at the [`ComponentAnnotation`](https://angular.io/docs/js/latest/api/annotations/ComponentAnnotation-class.html) docs, I have no idea how to get a hold of that annotation if I'm not using a module loader.

CC: @wardbell @naomiblack

**Comment by wardbell** [comment] 2015-08-15 01:17
No kidding! I was bit by it already.

I'm featuring `ng` in Getting Started Dev Guide for JS.

That's not enough. Need in API everywhere. Perhaps sufficient in the API examples?

**Comment by jeffbcross** [comment] 2015-08-19 00:05
@wardbell are you suggesting the ES5 version of examples would be based on the global `ng` object, without using any sort of module imports? Or would there be multiple versions of ES5 examples showing using ES5 with/without module systems?

**Comment by wardbell** [comment] 2015-08-19 03:58
Great question. The simplest, one file example doesn't need a module system. 

Could use advice on the ng2 modularity story for ES5 devs when things get more advanced. Now that there is no `angular.module` AFAIK.

Regardless, most devs will access Angular functionality from the `ng` root.

Are you thinking we should teach *systemjs* for ES5? That's intriguing!

**Comment by PascalPrecht** [comment] 2015-08-19 06:47
I think at some point there has to be a chapter that explains how to use
any module loader with ng2. Because that's what most of the ppl struggle
with (me too)

**Comment by pkozlowski-opensource** [comment] 2015-08-19 07:40
> I think at some point there has to be a chapter that explains how to use
any module loader with ng2

Wooohooo, this would be a separate book atm :-) More seriously: hopefully work on  https://github.com/whatwg/loader will progress and we are going to have solid polyffils, so this will be a solution we could recommend

**Comment by mhevery** [comment] 2015-08-19 16:59
I think all examples should be written with `ng.Foo` style. That way they will work both with `sfx` as well as with `import * as ng from 'angular2/core'`.

**Comment by wardbell** [comment] 2015-08-23 23:56
@mhevery I liked your suggestion until I tried to apply it.

For example, our current Getting Started sample reads:

     import {Component, View, bootstrap} from 'angular2/angular2';
     @Component({
        selector: '...'
     })
    @View({
        template: ...
    })
    class AppComponent { }

    bootstrap(AppComponent);

That is much less noisy than

     import * as ng from 'angular2/angular2';
     @ng.Component({
        selector: '...'
     })
    @ng.View({
        template: ...
    })
    class AppComponent { }

    ng.bootstrap(AppComponent);

Are you really recommending the latter style for TS development?

**Comment by PascalPrecht** [comment] 2015-08-24 06:43
> Where should folks register their components, services, etc?

I think even in ES5 services, directives and components should be registered at the place they are needed, just like we'd do in ES6/TS. So if we need a service instance in `ComponentA`, then `ComponentA` needs to define a bindings for that type of service, unless it's defined somewhere in a parent component/injector.

This of course doesn't solve the problem of polluting the global scope, which is why one would prolly simply go with an iife (immediately-invoked function expression), as we do nowadays anyways.

So I don't think everything needs to be defined on an `AppComponent`.

My 0.02$

**Comment by IgorMinar** [comment] 2015-08-24 16:46
For ES5 one can define DI modules for 3rd party components just like you would in ES6 - as arrays:

```
var myModule = [SomeConstructor, ng.bind(OtherConstructorOrObjectToken).toFactory(otherFactoryFunction), ... ]
```

This doesn't solve the issue of global namespace pollution and code-loading, which is usually handled by amd/cjs modules. My preference is to avoid picking winners here, since people will usually use whatever they are already comfortable with. We should document one example of using DI with each of amd/cjs and leave it at that.

--- 

With regards to using the `ng` namespace for ES6 code, I feel weird about it that as well. The nice benefits are that you have just one import and then you are all set + auto-completion from the ng namespace works nicely. The downside is that code is bloated.

**Comment by mhevery** [comment] 2015-08-24 17:49
@wardbell Yes, I was suggesting that, but I am open to counter-suggestions. The nice thing is that the code samples look identical whether you use ambient or import statements. If you think that having explicit imports is better, (and the complication of having different code example for ambient vs import is something we can handle) then I am fine with that as well.

**Comment by wardbell** [comment] 2015-08-30 19:17
By "different code examples" I assume you mean different between TS/ES6 and ES5.

In my experience so far, I believe that different examples are inevitable for other reasons.

The idioms are so different between these language communities that attempts at single sourcing will be counter productive.

For example, although `var` would work for both most of the time, I'm trying to teach myself to use `let` wherever possible. I'd want to discourage `var` in ES6.

Other morr compelling examples would include the different treatment of `this` and the ability to hide private variables in ES5 which is lost in ES6 classes (hence the annoying profusion of underscored vars in TS code)

The goal of presenting Dev Guide examples in two (ok, three) languages is to cater to the comfort of those communities. Writing all examples in Esperanto will just annoy everyone ;-)

Accordingly, I'm.striving for stylistic consistency WITHIN language communities; not as much ACROSS them.

**Comment by PascalPrecht** [comment] 2015-08-31 06:56
> For example, although var would work for both most of the time, I'm trying to teach myself to use let wherever possible. I'd want to discourage var in ES6.

I recently sent a PR to some A2 tests where I replace anonymous ES5 functions with fat arrow functions. It has been removed because non of these tests needed lexical scope and would therefore only introduce a perf overhead. I don't know if this is just true for transpiled ES6 code or also in native ES6, but I think same would be true for `var` vs `let`.

@mhevery do you know if using `let` and fat arrow functions where not needed introduces a perf penalty in native ES6? Maybe we shouldn't then use `let` all over the place in the docs, since it wouldn't be a good practice per se.

**Comment by mhevery** [comment] 2015-08-31 19:44
@PascalPrecht `=>` only causes pref if there is `this` referenced in it.

**Comment by PascalPrecht** [comment] 2015-08-31 21:34
In both, transpiled and native ES6?

**Comment by wardbell** [comment] 2015-09-04 09:13
@PascalPrecht @mhevery I don't think perf should influence our usage of `=>` or `let` unless (and until) we're talking about a confirmed hot path.  `let` is a good thing. So is `=>`.

The point of these constructs is to improve readability, avoid stupid hoisting errors, and simplify `this` treatment. Those interests should dominate.

Similar arguments have been made against captures. Hey, captures are wonderful ... until that rare occasion when they aren't because of perf in a hot path.  IMO, this caveat is not a sufficient reason to prohibit captures ... or `=>` and `let`.

**Comment by PascalPrecht** [comment] 2015-09-07 13:39
@wardbell I agree with you. I'd still like to know if that's a perf penalty only when we transpile code, or also when it's used natively.

**Comment by wardbell** [comment] 2015-09-07 16:00
Oh yes. And how much of a penalty? How many loops before the difference hits, say,10ms? Knowledge is good.

**Comment by jeffbcross** [comment] 2015-09-08 04:38
AFAIK `let` is pretty well-optimized by TypeScript, and doesn't need to be discouraged for application developers. Regarding fat arrow and `this`, I can't remember details, but I've seen significant negative results in macro benchmarks using `someFunction.bind(ctx)`, but I think TypeScript compiler is good about choosing the optimal fat arrow transpilation approach based on context. For example, if I put this block into the [TypeScript playground](http://www.typescriptlang.org/Playground), 

```typescript
var a = () => {
	this.bar = 'baz';
}
```

it transpiles to:

```javascript
var _this = this;
var a = function () {
    _this.bar = 'baz';
};
```
which seems pretty safe to me...

So in the docs, I don't think we need to worry about _not_ using let and fat arrow. In angular itself, especially in hotter parts like compiler, di, change detection, it's more important to optimize. @PascalPrecht's PR #1761 was changing DI itself, not tests, which is why it was a concern :). There are lots of optimizations in core that wouldn't be recommended as best practices for most users, like take a look at [this file](https://github.com/angular/angular/blob/70f6a46f1cbe090c946fd5ffea13f78be216ac05/modules/angular2/src/core/change_detection/proto_change_detector.ts).

**Comment by PascalPrecht** [comment] 2015-09-08 20:46
@jeffbcross thanks for clarifying this. By your comment I assume then that this is only a perf penalty when transpiling.

**Comment by gkalpak** [comment] 2015-09-09 01:33
I am still not sure why there is perf penatly. 
Is `var _this = this;` that expensive ? (I am geniously curious.)

**Comment by jeffbcross** [comment] 2015-09-09 05:52
@gkalpak sorry, I was saying that should _not_ be expensive. But I'm not sure if there are cases where fat arrow isn't transpiled to such efficient code. I.e. it may be transpiled to `a.bind(this)`.

**Comment by gkalpak** [comment] 2015-09-10 06:52
@jeffbcross, I see. Thx for clarifying.

I've never seen it transpiled to `a.bind(this)`, but usually don't look at the transpiled code of complex scripts :)
Definitely something to keep an eye on in hot paths.

**Comment by albertosantini** [comment] 2015-09-26 15:14
I am sorry but I still miss about components, services, etc. registration in ES5 without polluting the global scope.

After reading - a few times - @PascalPrecht and @IgorMinar comments above, I don't get yet the solution.

I have the following tiny working example:

```
// app.js
(function () {
    var helloComponent;

    function helloService() {}
    helloService.prototype.greeting = function () {
        return "Hello";
    };

    helloComponent = ng
        .Component({
            selector: "hello",
            bindings: [helloService]
        })
        .View({
            template: "{{greeting}} world!"
        })
        .Class({
            constructor: [helloService, function Hello(helloSrv) {
                this.greeting = helloSrv.greeting();
            }]
        });

    ng.bootstrap(helloComponent);
}());
```

So far it is ok, but I would like that example refactored in this way:

```
// hello.service.js
(function () {
    function helloService() {}
    helloService.prototype.greeting = function () {
        return "Hello";
    };

    // How to register the "service"?
}());

// app.js
(function () {
    var helloComponent;

    // How to get "helloService"?

    helloComponent = ng
        .Component({
            selector: "hello",
            bindings: [helloService]
        })
        .View({
            template: "{{greeting}} world!"
        })
        .Class({
            constructor: [helloService, function Hello(helloSrv) {
                this.greeting = helloSrv.greeting();
            }]
        });

    ng.bootstrap(helloComponent);
}());
```

It seems I cannot understand how to port `.module` in `angular2` with ES5.

The above suggestion `For ES5 one can define DI modules for 3rd party components just like you would in ES6 - as arrays:` is a true mystery for me.

The following snippet would be in `angular1` way.

```
// hello.service.js
(function () {
    angular
        .module("foo")
        .factory("helloService", helloService);
    
    function helloService () {
...
}());

// app.js
(function () {
    angular
        .module("foo")
        .controller("MyController", MyController);

    MyController.$inject = ["helloService"];
    function MyController(helloService) {
...
}());
```

For ES5, it seems it is missing a mechanism in DI to register and to get instances of the components. I played with Injector, Injectable API and so on without success.

Thanks a lot for any hint.

**Comment by wardbell** [comment] 2017-06-24 00:34
Closing as old

**Closed by wardbell** 2017-06-24 00:34 UTC
Labels: comp: docs, effort1: easy (hours), hotlist: angular-core-team, type: bug
