### ISSUE TITLE
Provide a validation function at ngForm

### ISSUE THREAD

**Issue by hstarorg** [angular/angular#19820] opened 2017-10-20 02:07 UTC
## I'm submitting requirement
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I must use loop to manual control the form validate in ts code .
```ts
if (this.tempForm.invalid) {
  Object.keys(this.tempForm.controls).forEach(k => {
    // this.tempForm.controls[k].updateValueAndValidity();
    this.tempForm.controls[k].markAsDirty();
  });
  return;
}
```
## Expected behavior
Provide a validate function.

```
// Want to use 
this.tempForm.forceValidate()
```

## Environment

<pre><code>
Angular version: 4.x

**Comment by trotyl** [comment] 2017-10-20 02:20
Possibly duplicate of #6170.

**Comment by hstarorg** [comment] 2017-10-20 10:09
Is there has a plan to support this?

**Comment by jasonaden** [comment] 2017-11-11 00:16
@hstarorg I don't know if there's a plan to explicitly support this behavior. I suggest getting in touch with Developer Relations ([@robwormald](https://twitter.com/robwormald) or [@stephenfluin](https://twitter.com/stephenfluin)) and make sure it's on their radar.

I'm closing this as a duplicate.

**Closed by jasonaden** 2017-11-11 00:16 UTC
