### ISSUE TITLE
ngOnChanges not being called on child of dynamically created component.

### ISSUE THREAD

**Issue by thomaspink** [angular/angular#25962] opened 2018-09-14 09:18 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When dynamically creating components, manually changing a property of a child component of that created component and then triggering changeDetection, `ngOnChanges` on this child component does not get called. The strange thing, the template does gets updated.

<pre><code>
app.component
-> outer.component // will be created dynamically by a portal(outlet)
---> inner.component // is a child of outer, we are setting a property manually here
</code></pre>

## Expected behavior
`ngOnChanges` should be called when a property has been changed and the CD has been run.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ubaqh9

I created 4 cases.
* **Case 1**: Setting text directly on inner component and triggering change detection on the app component. `ngOnChanges` in inner component does **NOT** get called
* **Case 2**: Setting text directly on inner component and triggering change detection on the outer component. `ngOnChanges` in inner component does **NOT** get called
* **Case 3**: Setting text on the outer component so text binding should resolve and triggering change detection on the outer component. `ngOnChanges` in inner component **DOES** get called -> OK
* **Case 4**: Setting text directly on inner component and triggering change detection also on the inner component. `ngOnChanges` in inner component does **NOT** get called

## What is the motivation / use case for changing the behavior?
We got this usecase where we have to create components dynamically and set some properties of their child components. This change of the property should run some logic in `ngOnChanges` method.

## Environment

<pre><code>
Angular version: 6.1.0
</code></pre>

**Comment by thomaspink** [comment] 2018-09-14 09:18
cc @lukasholzer

**Comment by alexzuza** [comment] 2018-09-15 03:10
`NgOnChanges` hook will be called only if you change props on parent component so it works as intended for me.

**Comment by thomaspink** [comment] 2018-09-17 08:50
If this behaviour is intended, then the documentation is not clear for me.

Angular docs:

> A callback method that is invoked immediately after the default change detector has checked data-bound properties if at least one has changed, and before the view and content children are checked.

When reading this, all requirements for a `NgOnChanges` method call are fulfilled:
* change detector checks in the example
* data-bound property has been changed (manually and not by the parent)
* change happens before view and content children are checked

What would be the proposed solution? Ignore `NgOnChanges` hook and use getter/setter for all input properties?

**Comment by SerkanSipahi** [comment] 2019-11-14 13:05
@mhegazy is this already fixed in ivy?

**Comment by amitport** [comment] 2020-02-12 20:08
@mhevery @SerkanSipahi not fixed by Ivy

**Comment by kumaresan-subramani** [comment] 2020-02-19 17:13
HI @amitport , 
i am also facing  same issue in angular 9 IVY before IVY it is working fine but now due to this [issue](https://github.com/angular/angular/issues/31495), i go for new way instead of using decorator i have created new instance for my class and used.

But here "ngonchanges" hook for my directives are not get triggered, can you please explain your workaround in detail

**Comment by amitport** [comment] 2020-02-19 17:51
@kumaresan-subramani it's a more of a refactor than a workaround. I'm not relying on Angular change detection, I manage an observable that **my code triggers** when there are changes, make assignments and call `changeDetectorRef.detectChanges()` if needed.

**Comment by kara** [comment] 2020-05-26 23:33
@thomaspink Thanks for creating such a detailed repro! The behavior you describe is "working as intended", but I can see how it might be confusing. The gist of it is that `ngOnChanges` is called when a component's input *bindings* are changed through the template (as opposed to when the  input property is changed directly). In other words, it's the value that goes into the `[text]="innerText"` input binding that must change (`outer.innerText`), not the value of the property that "receives" the input (`inner.text`). If you change `inner.text` directly, you're circumventing the binding entirely, which is where the mechanism for tracking `ngOnChanges` lives.

I agree that this is not well-documented yet, and given how it's a bit counterintuitive, we should probably revisit the original decision to limit `ngOnChanges` to bindings only. But because others have voiced the same concern, we have a few open issues that cover this use case already. See 
https://github.com/angular/angular/issues/35614 and https://github.com/angular/angular/issues/22567. To keep things simple, let's continue to track the issue there.

**Closed by kara** 2020-05-26 23:33 UTC
Labels: comp: core, core: dynamic view creation, core: lifecycle hooks, freq1: low, severity3: broken, triage #1, type: bug/fix
