### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'pointer-events')

### ISSUE THREAD

**Issue by tmeghe** [angular/angular#44927] opened 2022-02-01 15:59 UTC
### Which @angular/* package(s) are the source of the bug?

animations, platform-browser

### Is this a regression?

Yes

### Description

I have in a component the portion of code below :

```
const groupElement = this.renderer.createElement('g', 'http://www.w3.org/2000/svg') as ElementRef;
this.renderer.setStyle(groupElement, 'pointer-events', 'none');
```

groupElement exists.

The Renderer2 setStyle method give the error mentioned in this issue. Before the 13.2.1 upgrade the code was working.

Cheers,
Thomas

### Please provide the exception or error you saw

```true
core.mjs:6468 ERROR TypeError: Cannot set properties of undefined (setting 'pointer-events')
    at EmulatedEncapsulationDomRenderer2.setStyle (platform-browser.mjs:624:13)
    at BaseAnimationRenderer.setStyle (animations.mjs:285:23)
    at SvgGroupComponent.loadContourComponent (svg-group.component.ts:1094:19)
    at Object.next (svg-group.component.ts:287:20)
    at source.subscribe._OperatorSubscriber__WEBPACK_IMPORTED_MODULE_2__.OperatorSubscriber.isUnsub (tap.js:17:1)
    at OperatorSubscriber._next (OperatorSubscriber.js:9:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)
    at combineLatest.js:42:1
    at OperatorSubscriber._next (OperatorSubscriber.js:9:1)
    at OperatorSubscriber.next (Subscriber.js:31:1)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.1
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 13.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.1
@angular-devkit/build-angular   13.2.1
@angular-devkit/core            13.2.1
@angular-devkit/schematics      13.2.1
@angular/cli                    13.2.1
@angular/flex-layout            13.0.0-beta.37
@schematics/angular             13.2.1
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by JoostK** [comment] 2022-02-01 16:07
Duplicate of #44883. This has been fixed in the next patch (released later this week). You should be using `'svg'` instead of a full namespace URI though, which allows the code to start working again.

**Closed by JoostK** 2022-02-01 16:07 UTC

**Comment by tmeghe** [comment] 2022-02-01 16:10
Indeed, it works. I apologize for the duplicate.
