### ISSUE TITLE
@Input and @Output annotations are not carried from subclasses

### ISSUE THREAD

**Issue by TedSander** [angular/angular#5415] opened 2015-11-20 19:34 UTC
It would be nice if `@Input` and `@Output` annotations are carried from subclassed components. Currently this doesn't work with Transformers because it only looks at the local file.

I'm guessing we may not need to parse the Subclass directly, but might be able to look up the information that is saved from it's parent.

**Comment by PascalPrecht** [comment] 2015-11-20 19:39
AFAIK no decorations are inherited when extending classes that are decorated.

**Comment by gkirill** [comment] 2015-11-29 05:07
@PascalPrecht I think it is not entirely true. Here is piece of code that proves that `@Input` decorated property is inherited correctly (alpha 46):

```TypeScript
import {bootstrap, Component, Input, Output, NgFor, EventEmitter} from 'angular2/angular2';

abstract class DataComponent<T> {
    @Input()
    data: T;
}

interface TodoData {
    todos: TodoEntryData[];
}

interface TodoEntryData {
    content: string;
}

@Component({
    selector: 'todo-entry',
    template: `
        <div>{{data.content}}</div>
    `,
    directives: []
})
class TodoEntryComponent extends DataComponent<TodoEntryData> {
    // Here @Input data is inherited
}

@Component({
    selector: 'todo',
    template: `
        <div>
            <todo-entry *ng-for='#entry of data.todos' [data]='entry'></todo-entry>
        </div>
    `,
    directives: [NgFor, TodoEntryComponent]   
})
class TodoComponent extends DataComponent<TodoData> {
    data: TodoData = {
        todos: [
            {
                content: 'Task 1'   
            },
            {
                content: 'Task 2'
            }
        ]
    }
}

bootstrap(TodoComponent);
```

However, this does not seem to work consistently. E.g. If I try mixing an inherited decorated property and directly defined property, then I am getting errors. In the example below I am adding `@Output` decorated property to `TodoEntryComponent` class.. and get an error:

```TypeScript
import {bootstrap, Component, Input, Output, NgFor, EventEmitter} from 'angular2/angular2';

abstract class DataComponent<T> {
    @Input()
    data: T;
}

interface TodoData {
    todos: TodoEntryData[];
}

interface TodoEntryData {
    content: string;
}

@Component({
    selector: 'todo-entry',
    template: `
        <div>{{data.content}} <button (click)='doDelete()'>Delete</button></div>
    `,
    directives: []
})
class TodoEntryComponent extends DataComponent<TodoEntryData> {
    
    @Output()
    delete = new EventEmitter<TodoEntryData>();

    doDelete() {
        this.delete.next(this.data);
    }
}

@Component({
    selector: 'todo',
    template: `
        <div>
            <todo-entry *ng-for='#entry of data.todos' [data]='entry' (delete)='onDeleted($event)'></todo-entry>
        </div>
    `,
    directives: [NgFor, TodoEntryComponent]   
})
class TodoComponent extends DataComponent<TodoData> {
    data: TodoData = {
        todos: [
            {
                content: 'Task 1'   
            },
            {
                content: 'Task 2'
            }
        ]
    }
    onDeleted(event) {
        console.log(event);
    }
}

bootstrap(TodoComponent);
```

This is what I get when try to run this code:

```
EXCEPTION: TypeError: Cannot read property 'content' of undefined in [null]
EXCEPTION: TypeError: Cannot read property 'content' of undefined in [null]
ORIGINAL EXCEPTION: TypeError: Cannot read property 'content' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'content' of undefined
    at AbstractChangeDetector.ChangeDetector_TodoEntryComponent_0.detectChangesInRecordsInternal (eval at <anonymous> (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:31002:14), <anonymous>:31:27)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30789:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30772:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30842:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30776:12)
    at AbstractChangeDetector._detectChangesContentChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30836:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30773:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30842:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30776:12)
    at AbstractChangeDetector.detectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30761:12)
ERROR CONTEXT:
_Context {element: button, componentElement: todo-entry, context: TodoEntryComponent, locals: Object, injector: null…}
EXCEPTION: TypeError: Cannot read property 'content' of undefined in [null]
EXCEPTION: TypeError: Cannot read property 'content' of undefined in [null]
ORIGINAL EXCEPTION: TypeError: Cannot read property 'content' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'content' of undefined
    at AbstractChangeDetector.ChangeDetector_TodoEntryComponent_0.detectChangesInRecordsInternal (eval at <anonymous> (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:31002:14), <anonymous>:31:27)
    at AbstractChangeDetector.detectChangesInRecords (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30789:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30772:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30842:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30776:12)
    at AbstractChangeDetector._detectChangesContentChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30836:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30773:12)
    at AbstractChangeDetector._detectChangesInViewChildren (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30842:14)
    at AbstractChangeDetector.runDetectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30776:12)
    at AbstractChangeDetector.detectChanges (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:30761:12)
ERROR CONTEXT:
_Context {element: button, componentElement: todo-entry, context: TodoEntryComponent, locals: Object, injector: null…}
```

This seems to be happening because `@Input data` property is not recognized when there is `@Output` decorated property on the child class. But if I define `@Input data` explicitly on `TodoEntryComponent` then, all seems to be working as expected.

```TypeScript
class TodoEntryComponent {

    @Output()
    delete = new EventEmitter<TodoEntryData>();

    @Input()
    data: TodoEntryData;

    doDelete() {
        this.delete.next(this.data);
    }
}
```

Error also goes away if I move `@Output` to the parent class.

It would really be nice, if we could mix inherited and explicitly defined decorated properties.

**Comment by gevgeny** [comment] 2016-02-24 14:13
Same problem for me.

**Comment by alxhub** [comment] 2016-03-08 00:22
I think this is due to the way metadata works. The metadata field from the superclass is implicitly visible on the subclass, but if any annotated fields are defined on the subclass the resulting metadata definition shadows the one from the superclass, causing the superclass fields to break.

**Comment by poke** [comment] 2016-03-09 17:07
Is there any way we can work around this limitation? Maybe by defining the input binding per code in the base class’s constructor?

**Comment by TedSander** [comment] 2016-03-09 18:04
A workaround is to use the inputs, and outputs properties on the Component annotation itself. The pattern we use is to use the annotation values for anything in subclasses and the annotations for anything in the current class.

For example:
```dart
@Component(
  selector: 'foo',
  templateUrl: 'foo.html',
  inputs: const ['bar'],
  outputs: const ['baz'])
class FooComponent extends BarComponent {}
```

**Comment by KlausConrado** [comment] 2016-03-13 16:13
+1
Think that's essential to share behaviors between similar components.

**Comment by user414** [comment] 2016-03-21 11:36
Also having the same problem with ```@ViewChild```, interesting to note that it was working for me before in beta 6 and when I updated to beta 11 it stopped working. Not sure if that applies to input and output as well but viewchild for sure.

**Comment by user414** [comment] 2016-03-21 11:38
So perhaps just reverting whatever commit broke this from beta 6 to 11 would be enough to restore this feature.

**Comment by user414** [comment] 2016-03-21 12:54
Well this is interesting, was trying to put together a plunker to show the problem and a simple example with viewChild actually works in beta 11.

http://plnkr.co/edit/KO1TK4usclI9dZklQi96?p=preview

Have to fix this so will investigate further, I am not using systemjs unlike the plunker I am using based on the angular2 webpack template, something else must have caused the generated js to be different. Once I figure it out will post back.

**Comment by user414** [comment] 2016-03-21 14:38
Found out what cause it for us, the webstarter pack project template I was using changed to zone-js for polyfill instead of es6-shim etc... If I restore the es6-polyfill instead of zone-js the inheritance works. Will investigate little more and file proper issues with those projects.

**Comment by poke** [comment] 2016-03-21 16:25
@user414 Note that your example is unrelated to this issue. This one is about the fact that using decorators in a subtype effectively overwrites all decorators of the parent type.

**Comment by user414** [comment] 2016-03-21 17:03
@poke Thanks for the clarification, it was unclear to me if the OP issue, and in light of other comments,  was that they were not inherited at all, or just overwrites. I modified the plunker to show that issue just for reference

http://plnkr.co/edit/KO1TK4usclI9dZklQi96?p=preview

Just uncomment the viewChild in the children and it gives the error. Thanks for pointing that out didn't realize that it was also an issue. As far as my issue, still a little puzzled as to how a switching a polyfill (zone-js) could have such a strange side effect... Still looking but might just revert back to using es6-shim instead.

**Comment by alindsay55661** [comment] 2016-04-20 14:52
@alxhub You marked this as P4: nice to have, which indicates this bug isn't critical. Do you have a suggested work around in the meantime?

**Comment by poke** [comment] 2016-04-20 14:56
@alindsay55661 [See above](https://github.com/angular/angular/issues/5415#issuecomment-194427292); you can use the component annotation to declare your inputs and outputs.

The alternative, which is what I’m using, is to simply redeclare the members in the inheriting component, adding the annotations to the properties there again.

**Comment by zloirock** [comment] 2016-04-20 15:06
> As far as my issue, still a little puzzled as to how a switching a polyfill (core-js) could have such a strange side effect... 

`core-js` has a correct behavior here. TypeScript classes !== ES6 classes, with `A extends B {}` `B` isn't `A` prototype, so `Reflect` metadata methods should not return `B` metadata for `A` constructor. `reflect-metadata` package has a strange fallback for TypeScript classes, but it can't be called polyfill because it will not work if this API will be implemented natively.

**Comment by alindsay55661** [comment] 2016-04-20 15:08
> The alternative, which is what I’m using, is to simply redeclare the members in the inheriting component, adding the annotations to the properties there again.

Not sure this is an alternative as it pretty much moots the point of inheritance. I'll give the component annotation a shot, thanks.

**Comment by user414** [comment] 2016-04-20 15:55
End up needing to work around this, is there a similar solution for other annotation like ViewChild?

**Comment by poke** [comment] 2016-04-20 16:37
> TypeScript classes !== ES6 classes, with A extends B {} B isn't A prototype

Not sure how you arrive at this, given that ES6 classes are just syntactic sugar as well (so it’s possible to write equivalent code in ES5).

And looking at [what the TypeScript compiler generates](https://www.typescriptlang.org/play/#src=class%20A%20%7B%7D%0D%0Aclass%20B%20extends%20A%20%7B%7D), it does look like the prototype is set properly.

**Comment by zloirock** [comment] 2016-04-20 16:50
> Not sure how you arrive at this, given that ES6 classes are just syntactic sugar as well (so it’s possible to write equivalent code in ES5).

Wrong. ES6 classes - syntax sugar for prototype model but that doesn't mean they can be transpiled to ES5 completely. As I wrote, for `A extends B {}` `B` should be `A` prototype. That requires `__proto__` or `Object.setPrototypeOf`. In your example missed `Object.setPrototypeOf(A, B). `babel` uses it, TypeScript - not. Many other parts of ES6 classes hasn't ES5 equals.

**Comment by awerlang** [comment] 2016-04-20 19:06
The difference found in class implementations for ES6 and TypeScript and the reason for the current behaviour of TypeScript is discussed at https://github.com/Microsoft/TypeScript/issues/1601.

However, due to https://github.com/Microsoft/TypeScript/issues/1622 it is possible to override TypeScript `__extends` to match ES6 behavior. So, it can be a per-project choice, actually.

**Comment by user414** [comment] 2016-04-20 20:24
After digging in the code a little I found a workaround for all ViewChild/ViewChildren and others like ContentChild that use to use the old queries. 

```
@Component({
   ....
    queries: { viewChildren: new ViewChildren(MyComponent)}, 
  ...
})

export class MyClass {
...
private viewChildren: QueryList<MyComponent>;
...  
} 
```

I'm not sure if this will be supported in the future since Query has been deprecated a little while ago perhaps that just code that wasn't clean up yet

https://github.com/angular/angular/blob/master/modules/angular2/src/core/metadata.dart#L137

but for now it works. Not sure if we will use this in the end, for one I'm uncertain about if this will be deprecated as well, but wanted to share nonetheless.

On a side note perhaps we can adjust the title since it affect other, and seemingly all, annotation not just input and output.

**Comment by user414** [comment] 2016-05-22 20:14
@zloirock After partially reading the long typescript thread posted by @awerlang, it does seem to say that the behavior typescript exhibit is by design, so since typescript won't change will core-js match their behavior?

**Comment by zloirock** [comment] 2016-05-23 09:19
@user414 I don't think adding a fallback for TypeScript non-ES-compliance classes is a good idea. If in the future reflection metadata API will be implemented in JS engines - polyfills will use native implementation, they will not have this fallback and it will break cases like this.

**Comment by user414** [comment] 2016-05-23 11:52
@zloirock I can't say I agree with you. Their reasoning is that since __proto__ is an ES6 construct, as is Object.setPrototypeOf you cannot say that it is non es5 compliant when you target es5 since it's not part of ES6. If you want ES6 compliance then target ES6 and you will have it. Your argument about the future becomes moot in my view, since in that long distance future where metadata reflection will be in all JS engines then we can all simply target ES6 and forget about ES5 compliance and this issue you describe will not arise. The reasoning extends to when we reach ES73 specs and all JS engines have metadata reflection in them if when you target ES5 it breaks code, since you are targetting ES5 and the only thing that it remotely guarantees is ES5 compliance, the rest we can only hope that the best design decision were taken in order to provide the widest compatibility in the future, while not compromising the present. 

Now in this report there is 2 separate issue the OP issue which is that when there is annotation in a subclass and parent class they both get wiped out and my issue which is when there's annotation in a parent class with core-js it is ignored. Now I think the important part in all of this is the end result. I think we can all agree that when A extends B well that's what it should do and any implementation should strive to make it behave as such. Typescript was meant to abstract from all those JavaScript issues and give us the features that we all now should be there now. In that sense the behaviour in the implementation of es6-shim/reflect is IMHO more in line with the expected behaviour of A extends B then core-js.

**Comment by zloirock** [comment] 2016-05-23 16:02
@user414 sorry, it's a useless discussion. Looks like you don't understand what is polyfill and what is ES-compliance class.

**Comment by kemsky** [comment] 2016-05-24 15:17
Any progress here? It seems to be unnecessary limitation which leads to increase of redundant code.

**Comment by Vexra** [comment] 2016-06-28 07:54
Is this going to get implemented? Not being able to inherit viewchilds is a real bummer. I know that this is a rather rare use case for most projects, but we're in a situation where this happens very frequently. Having to add the same member to each and every child is kinda tedious and badly maintainable.

**Comment by jerome-franco** [comment] 2016-07-27 06:54
As of RC4, Input and Output decorators seem to be inherited when extending a class. The only time that it isn't is when you add a decorator in your subclass.

This does seem to work:
```typescript
import { Component, Input, Output, EventEmitter } from '@angular/core';

export class BaseClass { 
  @Input() baseInput: Object;
  @Input() baseOutput = new EventEmitter();

  constructor() { }

  generate(): void {
   
  }
}

@Component({
  moduleId: module.id,
  selector: 'sub-class',
  template: '<div></div>'
})
export class SubClass extends BaseClass {
  // @Input() ownInput: Object;

  ngOnInit() {    
    this.generate();
  }
}
```
However, decorators will not be carried out once you uncomment `// @Input() ownInput: Object;`.

**Comment by kemsky** [comment] 2016-07-29 23:05
It is possible with typescript: set `noEmitHelpers: true` in tsconfig.json, copy TS helpers from tsc.js#26682, patch `__decorate`  function to copy  shadowed `propMetadata`, patch `__extends` function to call `setPrototypeOf`.  

```
function __decorateFn(decorators, target, key, desc)  {
    var metadata = Reflect.getMetadata('propMetadata', target);
    ....
    if(metadata !== null)   {
        var newmetadata = Reflect.getMetadata('propMetadata', target);
        if (newmetadata !== metadata)  {
            Object.assign(newmetadata, metadata);
        }
    }
    return ...;
}
```
```
function __extendsFn(d, b)  {
    ....
    Object.setPrototypeOf(d, b);
}
```
We could have something similar to `enableProdMode()` to enable deep metadata lookups it would be much cleaner solution.

**Comment by emilioyn** [comment] 2016-08-02 14:10
@stephanjust same thing here. It's very useful if you're creating reusable UI components and needs to inherit common properties.

**Comment by schungx** [comment] 2016-08-03 01:13
@kemsky,, such functionality would help a whole lot.  OO-style view components are very powerful and easy to maintain, and not having properties carry across the inheritance makes it much more difficult than necessary.

**Comment by dszmaj** [comment] 2016-08-03 15:52
it seems to be the problem with all abstract class decorators

HostBinding confirmed here

**Comment by mikolaj-milewski** [comment] 2016-08-08 23:21
+1
Like said before, an essential need.

**Comment by mlaval** [comment] 2016-10-04 16:10
We are tracking inheritance-related issues in #11606

**Closed by mlaval** 2016-10-04 16:10 UTC
Labels: P4: nice to have, type: bug

**Comment by dgroh** [comment] 2016-10-11 14:26
I also need this, otherwise we have to replicate the same `@ViewChild` throughout our entire application. This was for sure working until RC4

**Comment by renehamburger** [comment] 2016-10-13 13:14
Putting @TedSander's and @user414's comments together, the following example shows how `@Input`, `@Ouput` and `@View/ContentChild(ren)` metadata can be inherited even now with a small workaround while we're waiting for the proper solution in #11606:

```ts
class BaseComponent {
  // Decorators are not currently inherited but are left in to put the compiler at ease
  @ViewChild(SomeComponent) comp;
  @Input() someInput;
  @Output() someOutput = new EventEmitter();

  // To be added to the child component's Component metadata
  static metaData = {
    queries: {
      comp: new ViewChild(SomeComponent)
    },
    inputs: ['someInput'],
    outputs: ['someOutput']
  };
}

@Component(Object.assign({
  selector: 'my-component',
  templateUrl: 'my-component.html
}, BaseComponent.metaData))
class MyComponent extends BaseComponent {
  constructor() {
    super();
  }
}
```

**Comment by sathishece170** [comment] 2019-06-04 14:14
@renehamburger - Will this work in angular 6 as i have tried your suggestion but getting passed as undefined still?

**Comment by rene-leanix** [comment] 2019-06-05 13:12
@sathishece170, the corresponding issue #11606 was resolved in [November 2016](). Is it possible that you are encountering [this open issue](https://github.com/angular/angular/issues/25249)?
