### ISSUE TITLE
Form handling: wrong behaviour for input fields with dynamically type

### ISSUE THREAD

**Issue by maku** [angular/angular#16580] opened 2017-05-05 11:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When setting the input type via a property the resulting value of a FormControl/FormGroup after input change is not correct

e.g.

```
inputType = 'number';
formControl = new FormControl(789);

<input [type]="inputType" [formControl]="formControl"> 

```
After updating the value in the input field the value of the formControl is a string and NOT a number.
When setting via type="number" the value is correct (a number).

**Expected behavior**
To get the value of the form control in the correct type

**Minimal reproduction of the problem with instructions**

In this plunker the wrong behaviour is shown:
https://plnkr.co/edit/i9Spc10kUCIwtGYx8Vkn?p=preview

**Please tell us about your environment:**

* **Angular version:** 4.1.1

* **Browser:** all
 
* **Language:** TypeScript 2.2

**Comment by trotyl** [comment] 2017-05-06 10:43
Duplicate of https://github.com/angular/angular/issues/7329.

Full duplications list: https://github.com/angular/angular/issues/7329, https://github.com/angular/angular/issues/8392, https://github.com/angular/angular/issues/9837, https://github.com/angular/angular/issues/12025, https://github.com/angular/angular/issues/13243, https://github.com/angular/angular/issues/15837.

**Closed** 2017-05-06 12:34 UTC
Labels: comp: forms

**Comment by maku** [comment] 2017-05-07 14:24
I find it really strange that this problem is already known for a rather long time and no fix is available...
