### ISSUE TITLE
Impure pipe and pure pipe

### ISSUE THREAD

**Issue by krishnaponkiya** [angular/angular#54068] opened 2024-01-25 10:54 UTC
### Describe the problem that you experienced

When we are reading documents of angular that time i can't see pure and impure pipe apis in document and when we click on pipe API it is not showing anything

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Looking for impure and pure pipe documentation 

### Describe the actions that led you to experience the problem

When i read the document this two api is not showing in api list.

**Comment by JoostK** [comment] 2024-01-25 11:44
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968. The fix is still awaiting deployment.

**Closed by JoostK** 2024-01-25 11:44 UTC
