### ISSUE TITLE
docs: missing API documentation for Forms members

### ISSUE THREAD

**Issue by dev054** [angular/angular#17088] opened 2017-05-29 14:34 UTC
**I'm submitting a ...**  (check one with "x")

- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**

Almost all methods of `AbstractControl` aren't being shown on https://angular.io/docs/ts/latest/api/forms/index/AbstractControl-class.html

Full list:

```

setValidators(newValidator: ValidatorFn|ValidatorFn[]): void  

setAsyncValidators(newValidator: AsyncValidatorFn|AsyncValidatorFn[]): void

clearValidators(): void

clearAsyncValidators(): void

markAsTouched({onlySelf}: {onlySelf?: boolean} = {}): void

markAsUntouched({onlySelf}: {onlySelf?: boolean} = {}): void

markAsDirty({onlySelf}: {onlySelf?: boolean} = {}): void

markAsPristine({onlySelf}: {onlySelf?: boolean} = {}): void

markAsPending({onlySelf}: {onlySelf?: boolean} = {}): void

disable({onlySelf, emitEvent}: {onlySelf?: boolean, emitEvent?: boolean} = {}): void

enable({onlySelf, emitEvent}: {onlySelf?: boolean, emitEvent?: boolean} = {}): void

setParent(parent: FormGroup|FormArray): void

updateValueAndValidity({onlySelf, emitEvent}: {onlySelf?: boolean, emitEvent?: boolean} = {}):
    void

setErrors(errors: ValidationErrors|null, {emitEvent}: {emitEvent?: boolean} = {}): void      

get(path: Array<string|number>|string): AbstractControl

getError(errorCode: string, path: string[] = null): any

hasError(errorCode: string, path: string[] = null): boolean

get root(): AbstractControl
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**
-- 

**What is the motivation / use case for changing the behavior?**
--

**Please tell us about your environment:**
--

* **Angular version:** 4.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
All

* **Node (for AoT issues):** `node --version` =

**Comment by paullessing** [comment] 2017-05-30 17:26
This also affects 2.4.0.

**Comment by paullessing** [comment] 2017-05-30 17:29
This is a duplicate of angular/issues/16255, although this contains more information.

**Comment by gkalpak** [comment] 2017-08-11 21:19
All methods are shown now (afaict).

**Closed by gkalpak** 2017-08-11 21:19 UTC
Labels: comp: docs, comp: forms
