### ISSUE TITLE
Expands All HTML using BrowserAnimationsModule

### ISSUE THREAD

**Issue by longhoang2984** [angular/angular#19166] opened 2017-09-13 06:07 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With any project using BrowserAnimationsModule, I call a variable with error 'Undefined', The browser will show all HTML of components which I navigated to
<img width="1278" alt="screen shot 2017-09-13 at 12 59 18" src="https://user-images.githubusercontent.com/11419002/30361868-7a7d3c26-9883-11e7-88a1-8122ac1a3dfc.png">
<img width="1276" alt="screen shot 2017-09-13 at 12 59 37" src="https://user-images.githubusercontent.com/11419002/30361870-7a87f2c4-9883-11e7-921f-6676160ee027.png">

The BrowserAnimationsModule import from '@angular/platform-browser/animations';
Source code: https://github.com/Ismaestro/angular4-example-app

## Expected behavior

Only show HTML of current component

<img width="1280" alt="screen shot 2017-09-13 at 13 03 31" src="https://user-images.githubusercontent.com/11419002/30362015-04b2069c-9884-11e7-9b3c-dbd74b321d78.png">

## Minimal reproduction of the problem with instructions

Error code:
<img width="1280" alt="screen shot 2017-09-13 at 13 00 56" src="https://user-images.githubusercontent.com/11419002/30361897-a3182722-9883-11e7-9b37-f625411309e2.png">

## What is the motivation / use case for changing the behavior?

I comment the BrowserAnimationsModule to resolved my problem.

<img width="1280" alt="screen shot 2017-09-13 at 13 02 47" src="https://user-images.githubusercontent.com/11419002/30362041-1fb02442-9884-11e7-9375-3ec48bfcc959.png">

## Environment

<pre><code>
Angular version: 4.3.5

Browser:
- [ x] Chrome (desktop) version XX
- [x ] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [x ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: 6.10.3  
- Platform:  All

Others:

</code></pre>

**Comment by matsko** [comment] 2017-09-18 19:17
I think that what should happen here is that the animation code should properly recover when any errors are encountered.

**Comment by Agrumas** [comment] 2017-09-21 09:41
@matsko Confusing thing is that it is enough just to import `BrowserAnimationsModule` and content gets duplicated on any error. Example https://plnkr.co/edit/DUW1tDdeRZgKaBdLu1nN?p=preview
Duplicate of #19093

**Comment by jasonaden** [comment] 2017-11-30 21:20
Closing as duplicate of #19093.

**Closed by jasonaden** 2017-11-30 21:20 UTC
Labels: comp: animations, severity2: inconvenient
