### ISSUE TITLE
How to handle Notification click events (cannot find docs)

### ISSUE THREAD

**Issue by petivagyok16** [angular/angular#22311] opened 2018-02-19 13:48 UTC
## I'm submitting a...
[X] Documentation issue or request

## Current behavior

Currently, its not clear how to handle [notification clicks](https://developers.google.com/web/fundamentals/codelabs/push-notifications/?hl=en#notification_click) with angular service worker.

## Expected behavior

Finding a source how to handle notification clicks in web push in PWA would be great! :) thanks

## Minimal reproduction of the problem with instructions

Just send a push notification with actions like
```js
let notificationData = {}
  notificationData.notification = {
    title: notification.title,
    actions: [{
      action: 'openapp',
      title: 'Open App'
    }],
    body: notification.body,
```

and clicking on Open App in the push notification wont work.

## What is the motivation / use case for changing the behavior?

It's a widely requested feature .

## Environment

<pre><code>
Angular version: 5.2.5

Browser:
- [x] Chrome (desktop) version 64

For Tooling issues:
- Node version: 9.3 
- Platform:  
Mac

**Comment by kapunahelewong** [comment] 2018-02-22 16:18
fyi @chembu and @jenniferfell

**Comment by bolajipemipo** [comment] 2018-03-09 21:59
Hello, anyone on this? 

The app is in Beta stage and users are sort of complaining already. Have really relied on Angular SW. Would really be glad if a solution comes out soon. 

Thanks.

**Comment by umutc** [comment] 2018-03-17 22:57
Hello everybody

  I wrote an an App as Angular 5 PWA.  When I sent a web-push, the notification comes both Android PWA and Mac Chrome PWA. 
  When I click the notification on Mac :  If chrome opened and not focused, focusing the chrome's current page. If chrome closed not opening a new chrome window as app.magistum.com.
  When I click the notification on Android device nothing happens.

  I thing at least the magistum.apk or app.magistum.com should open when I click the notification.

Best regards.

Payload: 
`
{
    "notification": {
        "title": "Hello!",
        "body": "Magistum transform your school.",
        "icon": "assets/main-page-logo-small-hat.png",
        "vibrate": [
            100,
            50,
            100
        ],
        "data": {
            "created_at": 1521327416
        },
        "actions": [
            {
                "action": "explore",
                "title": "Go to the site"
            },
            {
                "action": "go_to_homework",
                "title": "Go to homework"
            }
        ]
    }
}
`

**Comment by u-ryo** [comment] 2018-03-19 09:04
Handling the 'notificationclick' event hasn't seem implemented in the current(=5.2.0) Angular5 yet.
I posted a workaround on another issue https://github.com/angular/angular/issues/20956#issuecomment-374133852

**Comment by chembu** [comment] 2018-06-08 13:36
Right now we only support displaying the notifications, not interacting
with them.

Thanks,
Sreevani

**Comment by choopage** [comment] 2018-06-13 03:03
@u-ryo thanks for the workaround in https://github.com/angular/angular/issues/20956 and this repo https://github.com/u-ryo/angular-swpush to reference for the workaround. A point to note, **the swPush without built-in notification click_action is like a bird without wings**. **Using a workaround is like giving the bird an artificial wings, but why**? 

@chembu would appreciate if you could extend the swPush with built-in notification click_action. Many thanks.

**Comment by chembu** [comment] 2018-06-13 17:06
@alexhub: there is a feature request for extending the swPush with built-in
notification click_action. I can update the docs once the feature is
implemented.

**Comment by gkalpak** [comment] 2018-09-17 11:58
Closing as duplicate of #20956.

**Closed by gkalpak** 2018-09-17 11:58 UTC
Labels: comp: docs, comp: service-worker, freq3: high, subtype: docs-completeness, type: feature
