### ISSUE TITLE
Angular 5.2 with TypeScript 2.6 with strictFunctionTypes yield VirtualTimeScheduler.d.ts(22,22): error TS2415: Class 'VirtualAction<T>' incorrectly extends base class 'AsyncAction<T>'.

### ISSUE THREAD

**Issue by nblavoie** [angular/angular#21486] opened 2018-01-11 20:38 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I try to compile my Angular 5.2 (TypeScript 2.6) with rxjs 5.5.6, I'm getting the following error : 

```
ERROR in node_modules/rxjs/scheduler/VirtualTimeScheduler.d.ts(22,22): error TS2415: Class 'VirtualAction<T>' incorrectly extends base class 'AsyncAction<T>'.
  Types of property 'work' are incompatible.
    Type '(this: VirtualAction<T>, state?: T | undefined) => void' is not assignable to type '(this: AsyncAction<T>, state?: T | undefined) => void'.
      The 'this' types of each signature are incompatible.
        Type 'AsyncAction<T>' is not assignable to type 'VirtualAction<T>'.
          Property 'index' is missing in type 'AsyncAction<T>'.
```

## Expected behavior
The build command should pass.

## Minimal reproduction of the problem with instructions
1. Create a new Angular 5.2 application with angular-cli 1.6.
2. Add `"rxjs": "^5.5.6"` to package.json.
3. Install packages.
4. Add `"strictFunctionTypes": true` to tsconfig.json.
4. yarn start
5. Error.

## Environment

<pre><code>
` "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@angular/service-worker": "^5.2.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.9",
    "angular-tslint-rules": "^1.1.0",
    "angular2-datatable": "^0.6.0",
    "angular2-moment": "^1.7.1",
    "chart.js": "^2.7.1",
    "core-js": "2.5.3",
    "moment": "^2.20.1",
    "ng2-nouislider": "^1.7.7",
    "ng2-table": "^1.3.2",
    "ng2-toastr": "^4.1.2",
    "ngx-bootstrap": "^2.0.0-rc.0",
    "ngx-progressbar": "^2.1.1",
    "ngx-webstorage": "^2.0.1",
    "nouislider": "^10.1.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.5.6",
    "serializer.ts": "0.0.12",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "2.8.3",
    "@types/node": "9.3.0",
    "angular2-template-loader": "^0.6.2",
    "barrelsby": "0.0.8",
    "codelyzer": "^4.0.2",
    "electron": "^1.8.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "2.0.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.3",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.2",
    "ts-node": "4.1.0",
    "tslint": "^5.9.1",
    "typescript": "^2.6.2"
  },`

In `tsconfig.json` file :

`{
  "compileOnSave": true,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": false,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "strictNullChecks": true,
    "alwaysStrict": true,
    "noEmitOnError": true,
    "strictFunctionTypes": true
  },
  "exclude": [
    "test.ts",
    "wallabyTest.ts",
    "**/*.spec.ts"
  ]
}
`

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v9.2.0
- Platform:  Mac

</code></pre>

**Comment by devoto13** [comment] 2018-01-11 22:07
Shouldn't this be reported in RxJS repo instead?

**Comment by robwormald** [comment] 2018-01-11 22:14
> Shouldn't this be reported in RxJS repo instead?
Almost certainly yes.

**Comment by ericmartinezr** [comment] 2018-01-11 22:25
Found it was already reported https://github.com/ReactiveX/rxjs/issues/3031

**Comment by robwormald** [comment] 2018-01-11 22:28
closing as a duplicate of https://github.com/ReactiveX/rxjs/issues/3031

**Closed by robwormald** 2018-01-11 22:28 UTC
