### ISSUE TITLE
Route Resolve creates new instance of service

### ISSUE THREAD

**Issue by kdorion** [angular/angular#13594] opened 2016-12-20 19:44 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In a lazy loaded module, I use a route resolver that uses a service provided at the module level. The resolve creates a new instance of that service. Before angular 2.2.x, it wasn't creating a new instance.

**Expected behavior**

Reuse the same service instance provided by the lazy module in the resolve.
It shouldn't create a new instance of the service just like in angular 2.1.x

**Minimal reproduction of the problem with instructions**

Both are the same exact plnkr, using different angular versions.
NOT WORKING AS EXPECTED HERE: See plnkr using angular > 2.1 : http://plnkr.co/edit/kel9mq1CNR7Soaq3rNpH?p=preview
WORKING AS EXPECTED HERE: See plnkr using angular 2.1.0 : http://plnkr.co/edit/BU4AdonFYViRZyKDHj1T?p=preview

**What is the motivation / use case for changing the behavior?**

If data is stored in the service, it's not accessible within the resolve. OR if you store data from the resolve, it won't be accessible in components because it is not the same service instance.

**Please tell us about your environment:**

angular-cli: 1.0.0-beta.22-1
node: 4.5.0
os: linux x64

* **Angular version:** 2.0.X

It is a new issue.
Issue since Angular 2.2.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

**Comment by DzmitryShylovich** [comment] 2016-12-20 19:45
Duplicate of https://github.com/angular/angular/issues/12869?

**Comment by kdorion** [comment] 2016-12-20 19:49
I've been searching since yesterday morning about this issue and never saw that ticket. Yep, seems to be a duplicate.

**Closed** 2016-12-21 02:24 UTC
