### ISSUE TITLE
Link with wrong URL on Angular CLI page

### ISSUE THREAD

**Issue by casperschou** [angular/angular#23381] opened 2018-04-14 10:45 UTC
On the https://cli.angular.io/ site, the bottom "Learn Angular"-link is linking to https://wwww.angular.io (one too many W's)

**Comment by dreamid27** [comment] 2018-04-15 10:42
so details haha , nice one !

**Comment by trotyl** [comment] 2018-04-15 14:07
Duplicate of https://github.com/angular/microsites/issues/15

<sub>(And actually wrong repo)</sub>

**Comment by IgorMinar** [comment] 2018-04-16 07:08
oops. we should fix this.

**Comment by jainanuj0812** [comment] 2018-04-17 09:04
https://github.com/angular/design-love/pull/12

Pull request is not merged yet. :)

**Comment by jenniferfell** [comment] 2018-04-21 01:37
@IgorMinar Can you confirm that design-love is where this should be fixed and if so, please help with the PR mentioned above. Thanks!

**Comment by jenniferfell** [comment] 2018-04-21 01:39
Notes to myself (trying out some potential labels or search keywords)
docarea=other
prexists=true

**Comment by dariobraun** [comment] 2018-07-31 07:33
The link seems to be fixed so this issue can be closed.

**Closed** 2018-07-31 07:48 UTC
Labels: comp: docs, freq3: high, severity3: broken, type: bug/fix
