### ISSUE TITLE
Angular shouldn't encode '+' as "%2B" in location bar upon navigation events (page back/forward)

### ISSUE THREAD

**Issue by haqer1** [angular/angular#32101] opened 2019-08-12 08:46 UTC
# 🐞 bug report

### Affected Package
 The issue is probably caused by package @angular/router

### Description
 
Navigated back to /some/thing+ page.

URL displayed in location bar: /some/thing%2B

URL that should be displayed (original, because encodeURI(window.location.href) == window.location.href, etc.): /some/thing+

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 10.14.1
OS: linux x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**My personal work-around currently employed**

```javascript
// SomeClass (non-TS)
Object.defineProperty(SomeClass, "normalizeUnnecessaryUrlEscapesCausedByAngular", {
	value: function(popStateUri) {
		var href = popStateUri ? popStateUri : SomeClass.currentHref();
		if (SomeClass.PLUS_HEX_REGEX.test(href)) {
			var href2 = href.replace(SomeClass.PLUS_HEX_REGEX, SomeClass.PLUS);
			if (SomeClass.logger.isDebugEnabled())
				SomeClass.logger.debug("normalizeUnnecessaryUrlEscapesCausedByAngular: " +href+ " vs. " +href2+ " vs. " +popStateUri);
			history.replaceState(history.state, document.title, href2 /* "/some/thing+" */);
		}
	},
	writable: false
});

// AppComponent
import { AppIntegrationFacade } from '../../../../common/classes/AppIntegrationFacade';
export class AppComponent implements OnInit {
  ngOnInit() {
    this.subscribeToEvents();
  }
  private subscribeToEvents() {
    this.router.events.subscribe(val => {
      if (val instanceof NavigationEnd) {
        AppIntegrationFacade.normalizeUnnecessaryUrlEscapesCausedByAngular(val.urlAfterRedirects);
      }
    });
  }
}

// AppIntegrationFacade
import { environment /*...*/ } from '../../projects/something/src/environments/environment';
export class AppIntegrationFacade {
  public static normalizeUnnecessaryUrlEscapesCausedByAngular(url: string) {
    SomeClass.normalizeUnnecessaryUrlEscapesCausedByAngular(url);
  }
}
```

**Comment by haqer1** [comment] 2019-08-12 08:56
The work-around is not the best solution (because of minor cosmetics, & extra coding & testing involved). It would be better if Angular didn't do the escaping & didn't require a work-around (like the one mentioned above).

**Comment by atscott** [comment] 2020-05-29 19:10
Marking as duplicate of #32101, as the scope is more appropriate.

**Closed by atscott** 2020-05-29 19:10 UTC
Labels: comp: router, freq1: low, severity3: broken, triage #1, type: bug/fix

**Comment by haqer1** [comment] 2020-06-01 08:29
> Marking as duplicate of #32101, as the scope is more appropriate.

I'm confused, this says that this issue (#32101) is marked as duplicate of itself (which means it's not really a duplicate).

**Comment by atscott** [comment] 2020-06-01 14:27
> > Marking as duplicate of #32101, as the scope is more appropriate.
> 
> I'm confused, this says that this issue (#32101) is marked as duplicate of itself (which means it's not really a duplicate).

Copy-paste error. Meant to be #32102.

**Comment by haqer1** [comment] 2020-06-03 10:52
I see, this is marked as duplicate of #32102: OK (D'accord, Pekâlâ).
