### ISSUE TITLE
Dependency Injection - consider alternative for resolving TypeScript interfaces 

### ISSUE THREAD

**Issue by ShawnTalbert** [angular/angular#36336] opened 2020-03-31 00:37 UTC
### Relevant Package

This feature request is for @angular/core

### Description
DI can't handle TypeScript interfaces

### Describe the solution you'd like
I noticed Aurelia has an interesting solution using `Symbol`s for unique injection tokens to allow slick resolving of interfaces.

Described [here](https://docs.aurelia.io/app-basics/dependency-injection#using-interfaces)

### Describe alternatives you've considered
the current workaround is to use TypeScript abstract classes.

**Comment by nzacca** [comment] 2020-03-31 00:48
@ShawnTalbert Did you consider using an `InjectionToken`?

Ref: https://angular.io/api/core/InjectionToken

**Comment by ShawnTalbert** [comment] 2020-03-31 01:45
Thanks @nzacca. Yes, I looked briefly at InjectionToken and I presume it would be an ingredient in the solution? 

My point is it feels like Aurelia's approach fairly cleanly hides the details from the application programmer and it would be nice if Angular could provide a similar (or better!) API.

I like how they have done rather minimal boilerplate and it allows a traditional IFoo -> Foo type registration, as shown at the end of the section linked above.

As far as I can tell, Angular's answer to this erased-interface problem is abstract classes. I'm hoping they will consider this technique and/or improve upon it to give us a more natural feeling interface-to-concrete DI experience.

**Comment by Airblader** [comment] 2020-03-31 06:47
I've read that article and cannot find anything that seems more minimal than what Angular currently offers; Angular calls it InjectionToken, that page says DI.createInterface. Both have a generic to reference the actual type. Can you elaborate on where exactly you see the benefit? Is it about how the singleton is directly registered on the token?

On a side note, I've never done so but you should be able to use Symbols for DI in Angular as well if you prefer.

**Comment by petebacondarwin** [comment] 2020-03-31 07:28
I concur with @Airblader - you can see the minimal example here: https://next.angular.io/api/core/InjectionToken#plain-injectiontoken

To put it in context here is the Aurelia example from the guide posted earlier and the equivalent Angular example:

**Aurelia**
```ts
import { DI } from 'aurelia';

export const IProfileService = DI.createInterface<IProfileService>();
interface IProfileService { ... }

class ProfileService implements IProfileService {
    // ...implementation...
}

class SomeClass {
  inject = [IProfileService];
  constructor(service: IProfileService) {
        // ...implementation...
    }
}
```

**Angular**
```ts
import { Injectable, InjectionToken, Inject } from '@angular/core';

const IProfileService = new InjectionToken<IProfileService>('IProfileService');
interface IProfileService { ... }

@Injectable()
class ProfileService implements IProfileService {
    // ...implementation...
}

class SomeClass {
  constructor(@Inject(IProfileService) service: IProfileService) {
        // ...implementation...
    }
}
```

I hope that is enough to get you started @ShawnTalbert. Closing this issue as Angular already provides this feature.

**Closed by petebacondarwin** 2020-03-31 07:28 UTC
Labels: comp: core, core: di

**Comment by Airblader** [comment] 2020-03-31 07:52
@petebacondarwin 

The one difference I could imagine they meant is the `withDefault` here:

```
export const ITaskQueue = DI.createInterface<ITaskQueue>()
  .withDefault(x => x.singleton(TaskQueue));
```

However, that is unrelated to interfaces versus Symbols, which is what the issue is about, so I'm not sure.

**Comment by JoostK** [comment] 2020-03-31 09:39
@Airblader You can even do that in Angular!

```ts
import { Component, InjectionToken, Injectable, Inject, inject } from '@angular/core';

const IProfileService = new InjectionToken<IProfileService>('IProfileService', {
  factory: () => inject(ProfileService),
});
interface IProfileService {
  name: string;
}

@Injectable({ providedIn: 'root' })
class ProfileService implements IProfileService {
    name = 'Angular';
}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  constructor(@Inject(IProfileService) public s: IProfileService) {
  }
}
```

What's even more fun is that in AOT mode, it works even without the `@Inject` decorator as the compiler will consider the `InjectionToken` as value declaration of `IProfileService` and it's more than happy to accept that as a valid token. This cannot work in JIT however as the type metadata emits the `IProfileService` interface type as `Object`.

**Comment by Airblader** [comment] 2020-03-31 09:40
> You can even do that in Angular!

Oh, right. I totally forgot this exists. Thanks!
