### ISSUE TITLE
Option to have component tag be rendered as plain html

### ISSUE THREAD

**Issue by stepanzarubin** [angular/angular#15064] opened 2017-03-10 13:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] feature request
```

**Current behavior**

Angular will always find and render component tag.
e.g. `<my-component-tag>`

**Expected behavior**

I would like to have an option to have component tag be ignored and just kept as a plain html.
e.g. `<my-component-tag plainHtml>`

**What is the motivation / use case for changing the behavior?**

A lot of external components are not compatible to other external directives, components.
And in order to get same html structure and get things working  I would like to be able to create it manually.

Thanks.

**Comment by DzmitryShylovich** [comment] 2017-03-10 14:37
```
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@NgModule({
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule {}
```
and angular will ignore all unknown elements in templates

**Comment by ericmartinezr** [comment] 2017-03-10 14:42
An alternative to @DzmitryShylovich 's answer is to use `ngNonBindable`

For example 

```
<ng-container ngNonBindable>
   <my-cmp></my-cmp>
    </ng-container>
```

**Comment by stepanzarubin** [comment] 2017-03-10 15:41
@DzmitryShylovich , @ericmartinezr 
Thanks, I will give it a try, but not sure if it will work, because I want to generate separately opening and a closing tags of a component like these:

```
<my-cmp>
<div>
 ... these contents inside has to be bindable, have ngModel inside
</div>
</my-cmp>
```

`<my-cmp>` and `</my-cmp>` have to be ignored (I am afraid that there is a validation check of open/close tags).

**Comment by DzmitryShylovich** [comment] 2017-03-10 16:06
@stepanzarubin have you tried `ng-content`?

**Comment by DzmitryShylovich** [comment] 2017-03-11 22:07
Duplicate of https://github.com/angular/angular/issues/6194 :)

**Closed** 2022-02-01 00:57 UTC
Labels: feature, comp: core, core: directive matching, insufficient votes, votes required
