### ISSUE TITLE
Provide something like AbstractControl.valueChanges that starts with current value on subscription

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#20314] opened 2017-11-09 22:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I subscribe to AbstractControl.valueChanges nothing happens. After value changes my callback is called.

## Expected behavior
I would love a different observable that works almost like valueChanges, but when I subscribe it immediately emits current value.

Doing
```
value$ = form.valueChanges.startWith(form.value)
```
is not enough to solve it, because it will emit the value from the time of value$ creation, not from the time of subscription.

## What is the motivation / use case for changing the behavior?
I want to be able to subscribe to changes of the form later in the component lifecycle. If I subscribe to valueChanges early (eg. constructor or ngOnInit) I get the desired behavior. But if I need to subscribe later, there is no easy way to create an observable that starts with the current value.

**Comment by Toxicable** [comment] 2017-11-09 23:51
duplicate of https://github.com/angular/angular/issues/14542

**Comment by jasonaden** [comment] 2017-11-09 23:56
Closing as duplicate. Subscribe to #14542 for updates.

**Closed by jasonaden** 2017-11-09 23:56 UTC
