### ISSUE TITLE
Memory leak issue due to Renderer2's .createElement() method

### ISSUE THREAD

**Issue by Shijir** [angular/angular#26954] opened 2018-11-05 23:58 UTC
# 🐞 bug report

### Affected Package

I think the variable that's responsible for keeping the traces of removed DOM objects is here: https://github.com/angular/angular/blob/master/packages/core/src/view/services.ts#L722

### Is this a regression?

I don't believe so.

### Description

There are cases where users need to add and remove DOM elements using Angular's Renderer2. However, when DOM elements are created using Renderer2's .createElement(), it is leaving the traces the DOM elements in the JS heap memory even after the removal of those DOM elements from the DOM tree using Renderer2's .removeElement().

The cause of this problem, I believe, is due to the fact that Angular assigns those newly created elements to variables that are not reset when the elements are removed from the DOM tree.

## 🔬 Minimal Reproduction

I have created this stackblitz to reproduce the issue: https://stackblitz.com/edit/angular-gitter-with-memory-leak. You can add and remove an `<input .../>` element by clicking on the toggle button. Or you can automatically generate 10000 clicks so that you will see a noticalbe spike in the JS heap memory. 

Also, I have created another stackblitz where the **only difference from the previous stackblitz is that I have replaced the `Renderer2`'s `.createElement()` method with `document.createElement()`**. Please take a look here: https://stackblitz.com/edit/angular-gitter-with-no-memory-leak. This stackblitz live demo will show no memory leakage.

## 🔥 Exception or Error
Initial preview of the demos (See the live JS memory numbers):
<img width="1437" alt="screenshot 2018-11-05 14 58 21" src="https://user-images.githubusercontent.com/3958008/48033896-169f4e00-e112-11e8-8c03-aeea7726e8f8.png">

After multiple clicks on the "start test" button:

 
<img width="1437" alt="screenshot 2018-11-05 15 06 15" src="https://user-images.githubusercontent.com/3958008/48034122-ec01c500-e112-11e8-90a0-6fbc82cb7e06.png">

After clicking on the "start test" multiple times, you can see that the live JS memory number spiked in https://angular-gitter-with-memory-leak.stackblitz.io while the one in https://angular-gitter-with-no-memory-leak.stackblitz.io/ stayed almost similar to where it started initially.

## 🌍  Your Environment

**Angular Version:**

I've reproduced the bug in both Angular@v7.0.0^ and Angular@v6.0.0^

**Comment by manklu** [comment] 2018-11-06 07:05
If you create a node with Renderer2 you should destroy it if no longer needed.

```javascript
  removeButton(): void {
    this.renderer.removeChild(document.body, this.dynamicInput);
    this.renderer.destroyNode(this.dynamicInput)
    this.dynamicInput = null;
  }
```

**Comment by manklu** [comment] 2018-11-06 17:52
@pkozlowski-opensource In this case it's the debug info, but in the general case it depends on the renderer implementation.

**Comment by Shijir** [comment] 2018-11-06 18:14
@pkozlowski-opensource thank you. As you suggested, I tried the app in the production mode, and now I see those memory leakages are gone. However, I still think it could create issues for people who have a large number of unit tests. 

@manklu thanks for the suggested solution. I am a bit apprehensive of using `this.renderer.destroyNode()` as it's not included in Renderer2's public api. As such, it could create other problems during AoT or in the production mode. And actually someone has already faced that problem: https://stackoverflow.com/questions/44465653/what-is-the-correct-way-to-destroy-an-element-created-with-renderer2

**Comment by pkozlowski-opensource** [comment] 2018-11-06 18:35
@Shijir thnx for confirming that this is debug-only issue - it definitively is caused by the debug renderer (thus sticking the testing tag on it). 

@manklu you are totally right that if a custom renderer creates some "private" state connected with a node it, we would run into the same kind of memory leak issues.

I guess the best work-around for now is to create a utility function, sth like:

```
function removeNode(renderer: Renderer2, nativeNode: any) {
  renderer. removeChild(renderer. parentNode(nativeNode), nativeNode);
}
```

Not ideal but should get you going until we fix it...

**Comment by Shijir** [comment] 2018-11-06 18:57
@pkozlowski-opensource I think the culprit is in the [DebugRenderer2's createElement](https://github.com/angular/angular/blob/master/packages/core/src/view/services.ts#L721) method. It assigns the new created node element to an internal variables. So the workaround could be just resorting to the native `document.createElement()` method.

**Comment by pkozlowski-opensource** [comment] 2018-11-06 18:59
> So the workaround could be just resorting to the native document.createElement() method.

@Shijir this is definitively another work-around, yes. Provided that you just work with the DOM and don't need the Renderer's abstraction, of course.

**Comment by manklu** [comment] 2018-11-06 21:34
@Shijir 

> I am a bit apprehensive of using this.renderer.destroyNode() as it's not included in Renderer2's public api.

It's documented. https://angular.io/api/core/Renderer2#destroyNode
The only part I have overlooked is that it may be undefined.

**Comment by macjohnny** [comment] 2019-12-06 10:26
this should work even if destroyNode is undefined (i.e. in production mode):
```typescript
ngOnDestroy() {
    if (this.renderer.destroyNode) {
      this.renderer.destroyNode(this.spanElem);
    } else {
      this.renderer.removeChild(this.renderer.parentNode(this.spanElem), this.spanElem);
    }
}
```

**Comment by aeb-sia** [comment] 2019-12-09 09:36
Just ran into this issue as well. I'm calling both `destroyNode` and `removeChild` but still see the elements in memory dumps.

I also enabled ivy in angular 8 but am still seeing the issue, in both dev builds and generated prod builds

**Comment by mhevery** [comment] 2020-02-14 23:46
`DebugRenderer2` is no longer used with Ivy and therefore there is no need to retain references to the created DOM elements. Closing as resolved.

**Closed by mhevery** 2020-02-14 23:46 UTC
Labels: comp: core, comp: testing, fixed by Ivy, freq1: low, severity4: memleak, type: bug/fix, workaround2: non-obvious
