### ISSUE TITLE
Adding an ES2015/6/7 runtime. 

### ISSUE THREAD

**Issue by SanderElias** [angular/angular#14393] opened 2017-02-10 07:22 UTC
```
[ x] feature request
```

**Current behavior**
Angular (and all its dependencies) are compiled down to ES5

**Expected behavior**
Compile everything down to ES2015. I (and more and more Angular users) am only supporting evergreen browsers. Those all have 95%+ support of es6, heck most have even es2016, and es2017 features are getting close too!

**What is the motivation / use case for changing the behavior?**
Using ES6 over es5 has the following:
1. smaller runtime
2. less (to none) polyfills
3. faster execution. (I know not everything is faster now, actually for a lot of features it's actually opposite, but browsers are improving really fast, an ES6 support is getting faster and faster. This is high on the agenda of browser vendors)
4. did I mention SMALLER runtime yet?
5. easier to shake (I'm not too sure on this though.)
6. the happy feeling of using modern, up to date stuff
7. much smaller source maps, so faster for development too.
8. more readable code in the runtime

To be clear, what I want is an Angular runtime that targets ES2015+ instead of ES5. I know I can do this for my portion of a project, but what I want is to ship an entire ES6 app to the browser. When your target is modern browsers, you should ship modern JS.

**Comment by DzmitryShylovich** [comment] 2017-02-10 07:31
Not sure how it's related to angular.

Angular is written in typescript. So you can compile it to es2015 by adding `"target": "es2015"` in `tsconfig.json`

**Comment by SanderElias** [comment] 2017-02-10 08:01
@DzmitryShylovich That works for my part of the project, And that is assuming I'm also using typescript.
(while I do that, not all developers are on the TS bandwagon).

Then there is the testing. now all angular tests are run against the es5 version. If it were tested against the ES201(x) version, it will make clear what issues there are lurking in this area.

**Comment by SanderElias** [comment] 2017-02-10 08:10
@trotyl Can you explain your downvote?

**Comment by trotyl** [comment] 2017-02-11 15:21
> smaller runtime
I don't think ES6 is being fully supported currently in minify tools, even clojure compiler supports only a few ES6 syntax. How can you get smaller runtime with not minified ES6 code compare to minified ES5 code? Or is there any dark magic I don't know yet?

> less (to none) polyfills
Could you provide a little explain on this? AFAIK, the transpilation and polyfill are not coupled on TypeScript, and the transpilation process won't add polyfill, you need to add it yourself, so you don't need to include polyfill on modern browsers even if the code is transpiled.

**Comment by SanderElias** [comment] 2017-02-11 15:42
@trotyl Thanks for the explanation!

>I don't think ES6 is being fully supported currently in minify tools, even clojure compiler supports only a few ES6 syntax. How can you get smaller runtime with not minified ES6 code compare to minified ES5 code? Or is there any dark magic I don't know yet?

Well, compiling down to es5 blows the code up, and adds a fair amount of helpers. The minification is just something that will take some time. For now, its just [babili](https://github.com/babel/babili) that already does a pretty decent job, and this sort of thing will improve fast.

>Could you provide a little explain on this? AFAIK, the transpilation and polyfill are not coupled on TypeScript, and the transpilation process won't add polyfill, you need to add it yourself, so you don't need to include polyfill on modern browsers even if the code is transpiled.

Typescript transpile's to ES5 and uses some internal polyfills. Especially around classes. ~And around generators too~ *Just checked, those are not even available (anymore) if you compile to es5*, This are just 2 of them, but there are more.  But you are right, you can leave off some of the polyfills if you go to a modern browser, but not all of them.

**Comment by trotyl** [comment] 2017-02-11 16:07
> Typescript transpile's to ES5 and uses some internal polyfills.

I think you mean the [tslib](https://github.com/Microsoft/tslib/blob/master/tslib.js) or [ts-helpers](https://github.com/ngParty/ts-helpers/blob/master/index.ts) funcs. It can be a problem if generated for every single file (and sadly Angular did), since Angular supports TypeScript 2.1 now, it should get rid of this problem soon.

**Comment by SanderElias** [comment] 2017-02-11 16:12
>I think you mean the tslib or ts-helpers funcs. It can be a problem if generated for every single file (and sadly Angular did), since Angular supports TypeScript 2.1 now, it should get rid of this problem soon.

using es2015+ as target helps here too.
[here][1] is a sample of what I mean with TS blows up code. I know typescript 2 solves it a bit. Again, all problems are solvable, but when you are targetting modern browsers, why would you?

[1]:https://www.typescriptlang.org/play/index.html#src=async%20function%20testit(x)%20%7B%20%0D%0A%20%20%20%20let%20someValue%20%3D%20await%20new%20Promise((resovle)%20%3D%3E%20setTimeout(()%20%3D%3E%20resovle(x*2)%2C%20100))%0D%0A%20%20%20%20console.log(someValue)%3B%0D%0A%20%20%20%20return%20testit%0D%0A%7D%0D%0A%0D%0Aconst%20sample%20%3D%20async%20()%20%3D%3E%20%7B%20%0D%0A%20%20%20%20let%20result%20%3D%20await%20testit(10)%0D%0A%20%20%20%20console.log('end-result'%2Cresult)%0D%0A%7D%0D%0A

**Comment by DzmitryShylovich** [comment] 2017-02-18 07:56
Looks like they are working on es6 build https://github.com/angular/angular/pull/14467

**Comment by DzmitryShylovich** [comment] 2017-03-10 08:07
@SanderElias I believe this issue was resolved

**Comment by tbosch** [comment] 2017-04-10 18:42
Angular is already publishing ES2015 code on npm. However, JIT does not work with this.

Closing as a duplicate of https://github.com/angular/angular/issues/15127

**Closed by tbosch** 2017-04-10 18:42 UTC
