### ISSUE TITLE
Dependency compiled to ES5 during build process even though target is ES2015 and ngcc is run on postinstall

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#37903] opened 2020-07-03 05:46 UTC
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

Not that I'm aware of.

### Description

 A clear and concise description of the problem...
Our CI (Jenkins) gets stuck in the build process after upgrading to Angular 10. After some investigation it turns out that the issue it that when building our apps in parallel it they all trigger ngcc at the same time. A warning about parallel builds is shown for all apps but the one, and those apps never exists the process even though the build is complete. 
So the ngcc part is somehow causing the process to never finish. The main issue causing this I just discovered in the logs. If you look at the last line you can see that ngcc is compiling `@fortawesome/angular-fontawesome` into ES5, but the target of the applications are ES2015 and I'm running ngcc as a postinstall hook, so all modules are already compiled into ES2015.

```
web-app-prime 
 |
 | > web-app-prime@0.0.0-PLACEHOLDER webpack C:\Users\***\repo\monorepo-new\packages\web-app-prime 
 | > node --max_old_space_size=8192 node_modules\webpack\bin\webpack.js "--config" "config/webpack.prod.ts" "--bail"
 |
web-app-edit 
 |
 | > web-app-edit@0.0.0-PLACEHOLDER webpack C:\Users\***\repo\monorepo-new\packages\web-app-edit 
 | > node --max_old_space_size=8192 node_modules\webpack\bin\webpack.js "--config" "config/webpack.prod.ts" "--bail"
 |  
web-app-prime 
 |
 | Compiling @fortawesome/angular-fontawesome : module as esm5
```

As you can see it's compiled to ES2015:

```
> oas@6.0.1027 postinstall C:\Users\***\repo\monorepo-new
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

Compiling @fortawesome/angular-fontawesome : es2015 as esm2015 
```

## 🔬 Minimal Reproduction
https://github.com/JonWallsten/monorepo-new/tree/angular-10-repro
Start with a clean slate since the error goes away after first build.
1. npm run full-install
2. npm run build
3. Profit!

## 🔥 Exception or Error
<pre><code>
 | ERROR in ngcc is already running at process with id 33256.
 | If you are running multiple builds in parallel then you should pre-process your node_modules via the command line ngcc tool before starting the builds;
 | See https://v9.angular.io/guide/ivy#speeding-up-ngcc-compilation. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/monorepo-new/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.1
Node: 12.16.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
```json
"extends": "../../tsconfig.json",
"compilerOptions": {
    "target": "es2015",
    "outDir": "./dist",
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "typeRoots": [
      "./node_modules/@types",
      "../../node_modules/@types"
    ]
}
```
We also have one Angular.JS application in the mix, but it's clear it's not involved.

Edit: 
It seems like it's running on every build but the issue (and error) only appears when there's something to compile.
Note: The log in from another repo but with the same setup.
```
web-app-prime 
 | Another process, with id 34620, is currently running ngcc.
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
web-app-edit 
 | Another process, with id 34620, is currently running ngcc.
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
 | Another process, with id 47668, is currently running ngcc. 
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

**Comment by JonWallsten** [comment] 2020-07-03 08:19
@alan-agius4 : Thank for you prompt reply. I understand and accept that. But we're not currently in a position where we can rely solely on Angular-CLI. I guess we have to move over eventually, because this gets more complex for each release now. Anyway, thanks you pointing out the issue. I'll take a look at it.

**Comment by gkalpak** [comment] 2020-07-03 09:19
The repro repository doesn't seem to exist any more, but based on @alan-agius4's comment it sounds like the issue has been identified. To reiterate once more, in order for parallel builds to work correctly, the `--properties` used in the standalone `ngcc` command must match the `mainfields` in your webpack config.

I am going to close this issue, since there doesn't seem to be anything to be addressed, but let me know in case I missed something. Also, feel free to continue the discussion below if you have more questions or the proposed solution does not fix the problem for you.

**Closed by gkalpak** 2020-07-03 09:19 UTC
Labels: comp: ngcc

**Comment by JonWallsten** [comment] 2020-07-03 09:22
@gkalpak: It's private, that's why you can't see it but Alan can. I think the issue that still exists is the error messages produced  during the build process, complaining about ngcc is already running. I'm not sure why it's running at all since everything is compiled already.

**Comment by gkalpak** [comment] 2020-07-03 09:53
Aha! Well, I can't tell what is going on without looking at the code :grin:

**Comment by JonWallsten** [comment] 2020-07-03 10:22
@gkalpak : That's understandable. I'll send you an invite. It's a repo from our project, so I don't want to have out in the open.

**Comment by JonWallsten** [comment] 2020-07-03 10:57
@alan-agius4: Your solution worked fine. I'll check for changes in Angular's config next time. Thanks!

**Comment by gkalpak** [comment] 2020-07-03 11:40
So, are you still seeing unexpected behavior after applying the fix? If so, what is it and how can we reproduce it?

**Comment by JonWallsten** [comment] 2020-07-03 12:08
@gkalpap I still get the message about the look file mentioned in my edit in the OP. But maybe that's expected behavior?

**Comment by gkalpak** [comment] 2020-07-03 12:38
What commands are you running to see the error?

**Comment by JonWallsten** [comment] 2020-07-03 12:53
@gkalpak:
web-app-prime 
 |
 | > web-app-prime@0.0.0-PLACEHOLDER webpack-dev-server C:\Users\***\repo\oas-web\packages\web-app-prime 
 | > node --max_old_space_size=8192 ../../node_modules/webpack-dev-server/bin/webpack-dev-server "--config" "packages\web-app-prime\config\webpack.dev.ts" "--colors" "--hot"
 |
web-app-analyses 
 |
 | > web-app-analyses@0.0.0-PLACEHOLDER webpack-dev-server C:\Users\***\repo\oas-web\packages\web-app-analyses 
 | > node --max_old_space_size=8192 ../../node_modules/webpack-dev-server/bin/webpack-dev-server "--config" "packages\web-app-analyses\config\webpack.dev.ts" "--colors" "--hot"
 |
web-app-edit 
 |
 | > web-app-edit@0.0.0-PLACEHOLDER webpack-dev-server C:\Users\***\repo\oas-web\packages\web-app-edit 
 | > node --max_old_space_size=8192 ../../node_modules/webpack-dev-server/bin/webpack-dev-server "--config" "packages\web-app-edit\config\webpack.dev.ts" "--colors" "--hot"
 |
web-app-prime 
 | Another process, with id 25948, is currently running ngcc.
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
web-app-edit 
 | Another process, with id 25948, is currently running ngcc.
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
 | Another process, with id 25056, is currently running ngcc. 
 | Waiting up to 250s for it to finish. 
 | (If you are sure no ngcc process is running then you should delete the lock-file at C:/Users/***/repo/oas-web/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)

**Comment by gkalpak** [comment] 2020-07-04 14:42
I see. Yes, this behavior is expected.

##
To give some context:

Ngcc will write the lockfile as soon as it is invoked. Ngcc's work has two phases: First, it analyzes the entry-points and their dependencies and determines what compilation tasks need to be performed (and in what order). Then, it does the actual processing of the necessary entry-points.

So, even if it turns out that there is no actual compiling to be done, ngcc will still write a lockfile while analyzing the project. (FWIW, the analysis phase is pretty quick compared to the compilation phase and it is even faster if the dependencies and ngcc command-line options haven't changed since the last ngcc invocation (because ngcc stores metadata to speed up the analysis on subsequent invocactions).)
