### ISSUE TITLE
ng extract-i18n: Incorrect extraction of placeholders

### ISSUE THREAD

**Issue by niklausburren** [angular/angular#40670] opened 2021-02-02 16:42 UTC
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/localize

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.0

### Description

Since we have upgraded our Angular app from version 9.0.0 to 11.1.1 the extraction of translatable texts no longer works properly. 

`ng extract-i18n dashboard --format xlf --output-path projects/dashboard/src/i18n`

The placeholders in the extracted xlf file contains invalid characters:

`<x id="INTERPOLATION" equiv-text="&quot;\uFFFD0\uFFFD&quot;"/>` 

instead of

`<x id="INTERPOLATION" equiv-text="{{0}}"/>`

The texts with the placeholders come from our own translatable libraries, which we integrate into the app via a private gitlab registry.

```
<trans-unit id="5cb6a5c15d4320920fa326b29e631ec2197e63ae" datatype="html">
  <source>Der Benutzer &quot;<x id="INTERPOLATION" equiv-text="&quot;\uFFFD0\uFFFD&quot;"/>&quot; wurde bereits gelöscht.</source>
  <context-group purpose="location">
    <context context-type="sourcefile">node_modules/@sop/ui/__ivy_ngcc__/fesm2015/sop-ui.js</context>
    <context context-type="linenumber">3153</context>
  </context-group>
</trans-unit>
```

The same error was described in bug report #38711. According to @petebacondarwin, the bug should have been fixed in release 10.1.5. However, we can still observe the bug in version 11.1.1.

Is our extraction command configured incorrectly or does this error still exist in version 11.1.1?

## 🌍  Your Environment

**Angular Version:**
<pre><code>

"dependencies": {
    "@angular/animations": "^11.1.1",
    "@angular/cdk": "^11.1.1",
    "@angular/common": "^11.1.1",
    "@angular/compiler": "^11.1.1",
    "@angular/core": "^11.1.1",
    "@angular/forms": "^11.1.1",
    "@angular/localize": "~11.1.1",
    "@angular/material": "^11.1.1",
    "@angular/platform-browser": "^11.1.1",
    "@angular/platform-browser-dynamic": "^11.1.1",
    "@angular/router": "^11.1.1",
    "@aspnet/signalr": "^1.1.4",
    "@sop/infrastructure": "^0.2.0-pre0050",
    "@sop/material": "^1.4.0",
    "@sop/service-portal": "^0.2.0-pre0063",
    "@sop/ui": "^0.2.0-pre0058",
    "angular-oauth2-oidc": "^10.0.3",
    "angular-polyfills": "^1.0.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.8.3",
    "process": "^0.11.10",
    "rxjs": "^6.6.3",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1101.2",
    "@angular-devkit/build-angular": "~0.1101.2",
    "@angular-devkit/core": "^11.1.2",
    "@angular/cli": "^11.1.2",
    "@angular/compiler-cli": "^11.1.1",
    "@angular/language-service": "^11.1.1",
    "@ngx-i18nsupport/ngx-i18nsupport": "^1.1.6",
    "@ngx-i18nsupport/tooling": "^8.0.3",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^13.13.40",
    "codelyzer": "^6.0.0",
    "http-server": "^0.12.1",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.4",
    "karma-teamcity-reporter": "^1.1.0",
    "lodash": "^4.17.15",
    "ng-packagr": "^11.1.2",
    "npm-run-all": "^4.1.5",
    "start-server-and-test": "^1.12.0",
    "ts-node": "~8.6.2",
    "tslint": "~6.1.0",
    "tslint-teamcity-reporter": "^3.2.2",
    "typescript": "^4.1.3"
  }
</code></pre>

**Anything else relevant?**
We are developing our app on Windows 10 1909 using Visual Studio Code.

**Comment by petebacondarwin** [comment] 2021-02-02 19:30
In order to get the correct values in these extracted fields, the source-mapping must be working.
I wonder if there is a break in the sourcemap chain between your app and the original source templates of the library?
If you could provide me with some kind of reproduction I would be able to say more.

**Comment by niklausburren** [comment] 2021-02-05 08:52
@petebacondarwin Thank you for your reply. You can find an app in the repository `niklausburren/extract-i18n-test` that should allow you to reproduce the error. Execute the following command to extract the texts to `projects/dashboard/src/i18n:`

`npm run extract:i18n`

You will also find in the repository `niklausburren/sop-ui` the source code of the library `@sop/ui` from which the texts are not extracted correctly.

You should have received an invitation for both mentioned repositories

**Comment by petebacondarwin** [comment] 2021-02-07 15:45
Thanks @niklausburren - I'll take a look on Monday.

**Comment by petebacondarwin** [comment] 2021-02-08 13:25
Hi @niklausburren - I took at look at the demo project. The reason is the same as https://github.com/angular/angular/issues/40689#issuecomment-772622878

We do not support fine-grained source-mapping in ngcc, so libraries that have been processed by ngcc will lose their ability to map back accurately to the original text of the templates. This results in these extractions.

As I mention in that other issue, we are working on a replacement for ngcc, which should become widely available later this year.

**Comment by petebacondarwin** [comment] 2021-02-08 13:26
Closing as a duplicate of #40689

**Closed by petebacondarwin** 2021-02-08 13:26 UTC
Labels: comp: i18n, needs reproduction

**Comment by niklausburren** [comment] 2021-02-08 13:55
Thank you for your analysis. I'm not quite sure I understood your comment in #40689 correctly. That means i18n with libraries is not possible at the moment?

**Comment by petebacondarwin** [comment] 2021-02-08 14:50
You should be aware that the `equiv-text` property is entirely for the benefit of the translator, and does not affect the actual translation - it is purely informative. So the extraction and translation of library messages can still work. It is just that your translator does not get the nice information about the original text of the placeholders.  Is that enough to support you?

If you really want to know the text of the placeholders in your translation files then there are two options:

1. Wait for the new "linker" replacement to ngcc. This should get you back to the original level of support for these informational attributes
2. Run message extraction directly on the library itself, and then merge the library translation files with your application translation files.

**Comment by niklausburren** [comment] 2021-02-08 17:03
I was not aware that the equiv text is only for information for the translator. In this case it is not a problem for us.

Thank you for your support
