### ISSUE TITLE
Problem with Tour of heroes - Part 7 HTTP

### ISSUE THREAD

**Issue by dfinki** [angular/angular#19665] opened 2017-10-11 16:47 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Live Demo and provided code doesn't work.

## Expected behavior

Live Demo and provided code should work.

## Minimal reproduction of the problem with instructions
When trying to retrieve the data from the in-memory-web-api the data cannot be casted into an array of heroes. Also the live demo has the same issue.

https://angular.io/generated/live-examples/toh-pt6/eplnkr.html

The following code seems to be the problem:
<pre><code>
return this.http.get(this.heroesUrl)
             .toPromise()
             .then(response => response.json().data as Hero[])
             .catch(this.handleError);
</code></pre>
It was necessary for me to remove ".data" after "response.json()", resulting in the following code:
<pre><code>
return this.http.get(this.heroesUrl)
             .toPromise()
             .then(response => response.json() as Hero[])
             .catch(this.handleError);
</code></pre>

## What is the motivation / use case for changing the behavior?
People would get less frustrated when trying to finish the Tour of Heroes.

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) version 61
</code></pre>

**Comment by gkalpak** [comment] 2017-10-11 17:42
Duplicate of #19602 (see there for more info). We'll fix it asap.

**Closed by gkalpak** 2017-10-11 17:42 UTC
