### ISSUE TITLE
In ViewChild Decorator no examples found

### ISSUE THREAD

**Issue by SHUBHAMDAVE001** [angular/angular#57316] opened 2024-08-09 09:53 UTC
### Describe the problem that you experienced

In the viewChild Decorator usage noted tab, there is no examples listed but it is showing list of 2 examples.

![image](https://github.com/user-attachments/assets/42c7564d-2599-4848-a3b0-cf740a0253d7)

### Enter the URL of the topic with the problem

https://angular.dev/api/core/ViewChild?tab=usage-notes

### Describe what you were looking for in the documentation

I was looking for the examples for viewChild Decorator

### Describe the actions that led you to experience the problem

I was finding the doc for viewChild Decorator and then I switched to usage tab it shows 2 examples but there is no examples in it.

**Comment by JoostK** [comment] 2024-08-09 11:49
Thanks for the report, closing as a duplicate of #56321.

**Closed by JoostK** 2024-08-09 11:49 UTC
