### ISSUE TITLE
An ability to define an interface for a FormControl value

### ISSUE THREAD

**Issue by constantant** [angular/angular#29901] opened 2019-04-15 09:00 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
 I would like to get an ability to define an interface for a FormControl value. It will be very helpful in templates

### Describe the solution you'd like
 It should look like
```
export interface MyType {
  a: string;
  b: number;
}
@Component({
  template: `<div>{{control.value?.a}}</div>`
})
export class MyComponent {
  control: FormControl<MyType> = new FormControl<MyType>({
    a: 'some data',
    b: 1
  });
  group: FormGroup<MyType>= new FormGroup({
    a: new FormControl<string>,
    b: new FormControl<number>
  });
  array: FormArray<MyType[]>= new FormArray([
    {
      a: 'some data',
      b: 1
    }
  ]);
  fbControl: FormControl<MyType> = this.fb.control<MyType>({
    a: 'some data',
    b: 1
  });
  fbGroup: FormGroup<MyType> = this.fb.group<MyType>({
    a: ['some data'],
    b: [1]
  });
  fbArray: FormArray<MyType[]> = this.fb.array<MyType[]>([
    {
      a: 'some data',
      b: 1
    }
  ]);
  constructor(private readonly fb: FormBuilder){}
}
```

It will allow to get understanding which type a value has

```
<div>{{control.value?.a}}</div>
```

### Describe alternatives you've considered
 Some links:
https://stackoverflow.com/questions/55651907/how-to-define-an-interface-for-a-formcontrol-value
https://itnext.io/help-keep-angular-forms-type-safe-ca35f7b2edf8

**Comment by trotyl** [comment] 2019-04-15 10:43
Duplicate of https://github.com/angular/angular/issues/13721

**Comment by kara** [comment] 2019-04-16 22:13
Thanks for the issue, @constantant, but as @troytl mentions, we have an existing issue in #13721. Closing this as a duplicate.

**Closed by kara** 2019-04-16 22:13 UTC
