### ISSUE TITLE
ngIf cryptic error when a then block is set to a non template

### ISSUE THREAD

**Issue by 1heg0d** [angular/angular#16410] opened 2017-04-28 11:44 UTC
Edit (vicb) - the error is caused by the ngIf

```html        
<p *ngIf="user.removed; else activeBlock">User had been removed: {{user.removed | date : 'dd.MM.yyyy'}}</p>
<p #activeBlock>User is active</p>
```

The second `<p>` should be a `<ng-template>` but the error message does not help

Hi.
Probably i found an error.

I've used **ngIf block** inside **ngFor block** also inside **ngFor block** placed another **ngFor**.

Like this:

```html
<tr *ngFor="let user of users">
    <td>
        <p *ngFor="let login of users.logins">{{login}}</p>
    </td>
    <td>
        <p *ngIf="user.removed; else activeBlock">User had been removed: {{user.removed | date : 'dd.MM.yyyy'}}</p>
        <p #activeBlock>User is active</p>
    </td>
</tr>
```

And this throws error: **templateRef.createEmbeddedView is not a function**

I'm using this code now (instead previous):

```html
<tr *ngFor="let user of users">
    <td>
        <p *ngFor="let login of users.logins">{{login}}</p>
    </td>
    <td>
        <p *ngIf="user.removed">User had been removed: {{user.removed | date : 'dd.MM.yyyy'}}</p>
        <p  *ngIf="!user.removed">User is active</p>
    </td>
</tr>
```
Thanks for attention.

**Comment by tamasfoldi** [comment] 2017-04-28 12:19
Hi!

Try to put your `else` block into an `<ng-template></ng-template>` block as it shown in the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#enhanced-ngif-syntax)
Like this:
```
<tr *ngFor="let user of users">
    <td>
        <p *ngFor="let login of users.logins">{{login}}</p>
    </td>
    <td>
        <p *ngIf="user.removed; else activeBlock">User had been removed: {{user.removed | date : 'dd.MM.yyyy'}}</p>
        <ng-template #activeBlock>
           <p>User is active</p>
       </ng-template>
    </td>
</tr>
```

**Comment by 1heg0d** [comment] 2017-04-28 12:29
@tamasfoldi 
This is not solution, unfortunately.
If i delete the nested ngFor everything is working (#activeBlock in p tag).

**Comment by vicb** [comment] 2017-04-28 12:56
Please add a plunker that reproduce the issue. Without further details we will close the issue. Thanks.

**Comment by 1heg0d** [comment] 2017-04-28 15:28
@vicb 
https://embed.plnkr.co/Uvji8ookThtrjg9gflhN/

**else activeBlock** should be **ng-template**?

**Comment by aravindfz** [comment] 2017-05-01 08:53
The problem is because you are using `removed : null` when `{{null}}` is printed in HTML it throws that error

**Comment by titusfx** [comment] 2017-07-12 10:18
The conclusion is you CAN'T use ngIf then else without ng-template ? o.O

**Comment by chai-jay** [comment] 2017-09-26 22:10
@titusfx In short, yes. 

The *ngIf directive is a structural directive and expects you to pass `<ng-template>` for the `TemplateRef` in the [ngIf directive code](https://github.com/angular/angular/blob/ec56760c9ba530ee98117f9dd451b43c28d6de67/packages/common/src/directives/ng_if.ts#L148) to grab the referenced markup correctly, with the asterisk character * being a syntatic sugar. When you write `<div *ngIf="showThis">Test</div>`, it really becomes this:
```
<ng-template [ngIf]="showThis">
    <div>Test</div>
</ng-template>
```

And when you write this:
```
<div *ngIf="showThis; else thatTemplate>Test</div>
<ng-template #thatTemplate>
    <div>Else template</div>
</ng-template>
```
It gets desugared to something like this (I'm not 100% sure on this desugaring):
```
<ng-template [ngIf]="showThis" [ngIfElse]="thatTemplate">
    <div>Test</div>
</ng-template>
<ng-template #thatTemplate>
    <div>Else template</div>
</ng-template>
```

For more info, read these sections: https://angular.io/guide/structural-directives#what-are-structural-directives and https://angular.io/guide/structural-directives#the-asterisk--prefix.

**Closed** 2018-02-18 21:27 UTC
Labels: comp: common, comp: core & compiler, freq1: low, hotlist: error messages, severity1: confusing, type: bug/fix
