### ISSUE TITLE
Don't re-export non-local variable in promise.d.ts for TypeScript 1.8 compatability

### ISSUE THREAD

**Issue by krimple** [angular/angular#6773] opened 2016-01-29 14:49 UTC
Not sure if this is something auto-generated or not, but Typescript 1.8 doesn't allow things like:

export { Promise }

and I get this error on using tsc against an Angular 2 application using TypeScript 1.8.0

```bash
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: 
   Cannot re-export name that is not defined in the module.
```

Per https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#typescript-18

I would love to get TypeScript 1.8 support as it seems to have the ability to package up ES5 files alongside of TypeScript files, and could eliminate the need for WebPack in certain situations.

**Comment by pkozlowski-opensource** [comment] 2016-01-29 14:59
Duplicate of #6468

**Closed by pkozlowski-opensource** 2016-01-29 14:59 UTC
