### ISSUE TITLE
FormGroupDirective does not emit event on addControl

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#25388] opened 2018-08-08 15:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
FormControlName registers on the FormGroupDirective and a statusChanges is not triggered.

## Expected behavior
FormControlName registers on the FormGroupDirective and a statusChanges is triggered.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-ym2gjq

Check the "check me" check. The form statusChange keeps the valid value and the form has the correct invalid state.

This happens because the addControl method does not emit an event.

https://github.com/angular/angular/blob/master/packages/forms/src/directives/reactive_directives/form_group_directive.ts#L102

## Environment
Angular version: 6.1.2

**Comment by kara** [comment] 2018-08-14 23:09
Dupe of https://github.com/angular/angular/issues/20439

**Closed by kara** 2018-08-14 23:09 UTC
Labels: comp: forms
