### ISSUE TITLE
angular pwa not working offline on local IIS

### ISSUE THREAD

**Issue by BLecha** [angular/angular#29186] opened 2019-03-08 10:55 UTC
I trying to achive the following.

Angular pwa with angular version 6 and 7 works fine when I follow the online guides.
I create new ng app be it 6 or 7. Then I execute ng build --prod and then a go to the dist folder and run the command http-server -o And everything works fine as promised.

But when I cretate a local IIS (with the cert that google browser accepts) app by poiting it to my ng dist folder and I browse to https://localhost/test/pwatest the project work fine my manifest json work and the ngsw worker is registered. But when I go offline the tyrex appears. Nothing is fetched. I really google a lot and saw many people having this issue but this problem persists.

manifest.json
{ "name": "pwatest", "short_name": "pwatest", "theme_color": "#1976d2", "background_color": "#fafafa", "display": "standalone", "scope": "/", "start_url": "/", "icons": [ { "src": "assets/icons/icon-72x72.png", "sizes": "72x72", "type": "image/png" }, { "src": "assets/icons/icon-96x96.png", "sizes": "96x96", "type": "image/png" }, { "src": "assets/icons/icon-128x128.png", "sizes": "128x128", "type": "image/png" }, { "src": "assets/icons/icon-144x144.png", "sizes": "144x144", "type": "image/png" }, { "src": "assets/icons/icon-152x152.png", "sizes": "152x152", "type": "image/png" }, { "src": "assets/icons/icon-192x192.png", "sizes": "192x192", "type": "image/png" }, { "src": "assets/icons/icon-384x384.png", "sizes": "384x384", "type": "image/png" }, { "src": "assets/icons/icon-512x512.png", "sizes": "512x512", "type": "image/png" } ] }

ngsw-config.json

{ "index": "/index.html", "assetGroups": [ { "name": "app", "installMode": "prefetch", "resources": { "files": [ "/favicon.ico", "/index.html", "/*.css", "/*.js" ] } }, { "name": "assets", "installMode": "lazy", "updateMode": "prefetch", "resources": { "files": [ "/assets/**", "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)" ] } } ] }

index.html
`<!doctype html>

<title>Pwatest</title> Please enable JavaScript to continue using this application. ` what is the problem? I also tried adding the router to manifest.json no success.
By the way when I perform audit it shows Failures: Service worker does not successfully serve the manifest's start_url, Timed out waiting for fetched start_url.

**Comment by gkalpak** [comment] 2019-03-08 11:20
Duplicate of #29163.
@BLecha, please stop opening the same issue over and over :pray: Thx!

**Closed by gkalpak** 2019-03-08 11:20 UTC
