### ISSUE TITLE
angular router error when use CSSClass directive

### ISSUE THREAD

**Issue by gastrodia** [angular/angular#3170] opened 2015-07-21 07:55 UTC
my html is link this:

<li  *ng-for="#item of items">

	<a href="javascript:;">

        <i [class]="item.icon"></i>

	<span >{{item.title}}</span>

	</a>

</li>

and then angular router throw errors:

SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
STACKTRACE:
Error: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at Error (native) at BrowserDomAdapter.execute.BrowserDomAdapter.addClass

(http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:19559:31)

    at DomView.execute.DomView.setElementClass (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:14410:19)

    at $__0.execute.DomRenderer.setElementClass (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:23099:18)

    at execute.CSSClass._toggleClass (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:16035:26)

    at http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:16028:18

    at IterableChanges.execute.IterableChanges.forEachAddedItem 
(http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:9453:15)

    at execute.CSSClass._applyArrayChanges (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:16027:16)

    at execute.CSSClass.onCheck (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:15990:20)

    at AbstractChangeDetector.ChangeDetector_LeftSider_embedded_1.detectChangesInRecords (eval at <anonymous> (http://localhost:8020/resource/lib/angular2.0.0-alpha.28_router.dev.js:9068:20), <anonymous>:108:40)

**Comment by pkozlowski-opensource** [comment] 2015-07-21 07:58
@gastrodia please try with the latest release 2.0.0-alpha.31. You are testing against a almost 1-month old version and there is a lot of movement in the repo.

**Comment by gastrodia** [comment] 2015-07-21 08:36
Sorry, @pkozlowski-opensource I change to 2.0.0-alpha.31 and has the same error

**Comment by gastrodia** [comment] 2015-07-21 08:41
SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty. in [start active  in null]

STACKTRACE:
Error: SyntaxError: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty. in [start active  in null]

    at ChangeDetectionError.BaseException (http://localhost:8020/resource/lib/angular2.dev.js:7713:25)
    at new ChangeDetectionError (http://localhost:8020/resource/lib/angular2.dev.js:9004:66)
    at AbstractChangeDetector.execute.AbstractChangeDetector.throwError (http://localhost:8020/resource/lib/angular2.dev.js:19972:19)
    at AbstractChangeDetector.ChangeDetector_LeftSider_comp_0.detectChangesInRecords (eval at <anonymous> (http://localhost:8020/resource/lib/angular2.dev.js:9914:20), <anonymous>:116:16)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:8020/resource/lib/angular2.dev.js:19936:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8020/resource/lib/angular2.dev.js:19957:20)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:8020/resource/lib/angular2.dev.js:19940:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChangesInShadowDomChildren (http://localhost:8020/resource/lib/angular2.dev.js:19957:20)
    at AbstractChangeDetector.execute.AbstractChangeDetector._detectChanges (http://localhost:8020/resource/lib/angular2.dev.js:19940:18)
    at AbstractChangeDetector.execute.AbstractChangeDetector.detectChanges (http://localhost:8020/resource/lib/angular2.dev.js:19928:18)

**Comment by thelgevold** [comment] 2015-07-21 13:06
I have seen this issue when trying to bind an empty string to [class]. Changing it to undefined instead of blank string fixed it for me

**Comment by pkozlowski-opensource** [comment] 2015-07-21 13:16
@thelgevold could you please share a minimal reproduce scenario for " trying to bind an empty string to [class]"?

**Comment by thelgevold** [comment] 2015-07-21 21:48
@pkozlowski-opensource:
I am not sure if the empty string part is by design, but it does still fail in alpha.31 if an empty string is assigned to [class]. Below is a simple case where the error can be seen.
```
import {Component, View, CSSClass} from 'angular2/angular2';

@Component({
    selector: 'demo'
})

@View({
    template: '<div [class]="someClass">Test</div>',
    directives:[CSSClass]
})

//Your custom component logic goes here
export class CssEmpty {
    someClass = '';
}
```

**Comment by mhevery** [comment] 2015-07-22 22:44
please create a plnkr.co/edit example showing the error.

**Closed** 2015-07-22 22:45 UTC
