### ISSUE TITLE
Imported forChild()-routes overrides forRoot()-routes (depends on the order of imports)

### ISSUE THREAD

**Issue by Martin-Wegner** [angular/angular#12648] opened 2016-11-01 19:26 UTC
**I'm submitting a ...**
```
[x] bug report
```

**Current behavior**
If you import a module before the `AppRoutingModule-import` the `forChild()-routes` overrides all equal `forRoot()-routes` and the `default route` (e.g. `{ path: '', redirectTo: 'xxx', pathMatch: 'full' }`).

*Small example:* You have the following `forRoot()-routes`:

```
{ path: '', redirectTo: 'welcome', pathMatch: 'full' },
{ path: 'module2', loadChildren: (): Type<Module2Module> => Module2Module },
{ path: 'new', component: NewComponent }
{ path: 'welcome', component: WelcomeComponent },
```

A module which is loaded by `loadChildren` needs a `default route`. So the `forChild()-routes` of the module could be:

```
{ path: '', redirectTo: 'entry', pathMatch: 'full' },
{ path: 'entry', component: EntryComponent },
{ path: 'new', component: NewComponent }
{ path: 'search', component: SearchComponent }
```

Using `loadChildren` avoids conflicts because the `forChild()-routes` are all prefixed with `/module2/` (defined in the `forRoot()-routes`).

*Here the trouble starts:*

Now we want to use the `SearchComponent` from `Module2` in our app so we must import the whole `Module2Module` in our `AppModule`:

```
imports: [
  Module2Module,
  AppRoutingModule
],
```

Oh no, we imported the `Module2Module` before the `AppRoutingModule`... The `AppMpdule` `forRoot() default route` and the `forRoot() new route` are both overriden by the `Module2Module` `forChild()-routes` :(

If we change the order of the imports, then the `forRoot()-routes` will survive:

```
imports: [
  AppRoutingModule,
  Module2Module
],
```

**Expected behavior**
The order of imports should not make any difference.

**Minimal reproduction of the problem with instructions**
Right order (`forRoot()-import` before `forChild()-imports`):
http://plnkr.co/edit/jNqsr0EQKAigpuKdIbCK?p=preview

Wrong order (`forChild()-imports` before `forRoot()-import`):
http://plnkr.co/edit/papUJhvXCWoNSn81MPXa?p=preview

**What is the motivation / use case for changing the behavior?**
`forChild()-routes` should never override `forRoute()-routes`.

**Please tell us about your environment:**
Linux
- **Angular version:** 2.1.2
- **Browser:** All
- **Language:** TypeScript 2.0.6
- **Node (for AoT issues):** 6.9.1

**Comment by ijager** [comment] 2016-11-28 13:48
I ran into the same problem. I was following [this example](https://github.com/angular/angular/issues/10958#issuecomment-241171933) from @brandonroberts.

However, for me, the order of Module imports does not affect anything. The `forRoot()-routes` are getting overridden  by the `forChild()-routes` of the feature module anyway.

- **Angular version:** 2.2.3
- **Language:** Typescript 2.0.0

**Comment by siddharthaReddy** [comment] 2017-03-02 19:43
I am seeing similar problem with order of modules.  

Except that `loadChildren` as callback function doesn't work for me. I am using it as string which points to module file and class name reference. 

`forRoot()` routes:
```
{ path: '', pathMatch: 'full', redirectTo: 'pixel'},
{ path: 'pixel', component: PixelAppComponent, loadChildren: './products/iq-envoy/pixel.module#PixelAppModule'},
{ path: '**', pathMatch: 'full', component: PageNotFoundComponent}
```

**Comment by matheo** [comment] 2017-08-16 15:35
I just found that if you use `loadChildren` on your routing, you do not need to import the submodule into the App, let the router do it and all will be Ok.

**Comment by gheiler** [comment] 2017-09-08 11:56
Here is a workaround to this bug
[https://stackoverflow.com/questions/42127827/angular-2-routes-in-imported-module-override-current](https://stackoverflow.com/questions/42127827/angular-2-routes-in-imported-module-override-current)

**Comment by dereklin** [comment] 2017-12-29 07:32
loadChildren can only be used for lazily loaded modules in AOT mode.  I am facing the same issue when I try to organize my modules into a nice hierarchy with forRoot and forChild.  The routes defined in forRoot can't be matched because I have path: '' (empty path) in forChild...

This is Angular 5.1.2

**Comment by dereklin** [comment] 2017-12-29 18:33
I made a couple of comments here that's related to this issue:

https://github.com/angular/angular/issues/13848#issuecomment-354481084
https://github.com/angular/angular/issues/13848#issuecomment-354482707

Here is my repo: https://github.com/dereklin/nx-demo-jest/tree/wildcard-route-lazy-load-1

It shows the leaf route is overriding the one above it.

**Comment by dereklin** [comment] 2017-12-29 18:58
I have uploaded another branch to demo this problem: https://github.com/dereklin/nx-demo-jest/tree/parent-route-child-route

```
const routes: Routes = [
  // { path: 'f3', component: Feature3Component }, // having this here will make /f3 work
  {
    path: '',
    component: CoreComponent,
    children: [
      { path: '', redirectTo: 'f1', pathMatch: 'full' },
      { path: 'f1', component: Feature1Component },
      { path: 'f2', component: Feature2Component },
      { path: 'not-found', loadChildren: '@nx-demo-jest/not-found/src/not-found.module#NotFoundModule' },
      {
        path: '**',
        redirectTo: 'not-found',
        pathMatch: 'full'
      }
    ]
  }
];
````
If uncomment path: f3, /f3 works.

But having f3 in my app-routing.module.ts has no effect, f3 is not found:

```
const routes: Route[] = [
  { path: 'f3', component: Feature3Component }
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes),
    CoreModule,
    Feature3Module
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
````
I expect the child routes to be merged into the parent, and the parent routes should take precedence over the children; or return some compilation error when the routes are the same.

**Comment by atscott** [comment] 2020-05-26 16:39
Confirmed that this is still an issue in v9: https://stackblitz.com/edit/angular-8jhtfz?file=src%2Fapp%2Fapp.module.ts
Navigating to the base route (`''`) has different behavior depending on the order of the imports. When `Module2Module` is imported first, the redirect goes to `/entry` but should go to `/welcome`.

**Comment by shiv11x10** [comment] 2020-11-06 07:34
> I just found that if you use `loadChildren` on your routing, you do not need to import the submodule into the App, let the router do it and all will be Ok.



> I just found that if you use `loadChildren` on your routing, you do not need to import the submodule into the App, let the router do it and all will be Ok.

This is the solution that will work.

**Comment by atscott** [comment] 2020-11-06 17:40
Reprioritizing this as an inconvenience due to a lack of an error message. 
* The documentation is pretty clear on how to lazy [load feature modules](https://angular.io/guide/lazy-loading-ngmodules). Child modules should be imported through the router config, not in the `imports` list of the root module.

* #10958 tracks the feature request to hierarchical modules without lazy loading
* The behavior of routes being overwritten is working as expected - `ROUTES` is a multi provider and both `RouterModule.forRoot` and `RouterModule.forChild` will provide the routes you configure.
* That said, we could investigate providing a dev-mode error when `forChild` is provided in a place that uses the same injector as the `forRoot` call. This would be similar to the [existing guard for two calls to `forRoot`](https://github.com/angular/angular/blob/b9b91784581d37dc0b3975778184eb32cffa910f/packages/router/src/router_module.ts#L191-L195) -- ([example](https://github.com/angular/angular/commit/0eb570ce86f0c146908290f2d3608b0c66988947).
  * It might be the case that some devs _do_ want to use `forChild` just to provide more routes and understand that these could collide with existing routes. In this case, the error message could direct the user to instead use [provideRoutes](https://angular.io/api/router/provideRoutes)
  * This error would be a breaking change, especially for tests where devs don't care as much about the router setup/behavior and could very likely have this situation in the testing module ([internal tests](https://test.corp.google.com/ui#id=OCL:341058224:BASE:341059575:1604682554879:7347fcfa) have shown this to be the case in several places).
* Alternatively to the error message, the docs could potentially be even more clear about when and where to use `forChild`, mentioning to the two points from above: use `provideRoutes` instead when providing extra routes in the root and do not use forChild with forRoot.

**Comment by alxhub** [comment] 2022-02-08 00:51
Closing as won't fix - this is working as intended, and some applications do indeed use `forChild` to append additional routes even in the root injector.

**Closed by alxhub** 2022-02-08 00:51 UTC
Labels: hotlist: error messages, comp: router, state: confirmed, triage #1, router: lazy loading, P5
