### ISSUE TITLE
Call Angular functions by javascript, export class to native javascript

### ISSUE THREAD

**Issue by huangwei16800** [angular/angular#30490] opened 2019-05-15 17:25 UTC
can add this  property?  because i create a custom Elements by angular,  other web project can use web componet from angular elements, but i want export  class function also, in order to others webproject call angular class, pass this instance to angular elements componet.

**Comment by robwormald** [comment] 2019-05-29 20:42
I believe this is a duplicate of https://github.com/angular/angular/issues/22114 - is this what you're talking about @huangwei16800 ? If not, could you provide an example please?

**Closed by robwormald** 2019-05-29 20:42 UTC
Labels: comp: elements
