### ISSUE TITLE
strictTemplates not working with *ngFor

### ISSUE THREAD

**Issue by guilhermebentomarques** [angular/angular#40576] opened 2021-01-26 14:35 UTC
# 🐞 bug report

### Description

When strictTemplates is true in angularCompilerOptions, *ngFor type check seems to not work properly.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-wd42u1?file=src/app/app.component.html

## 🔥 Exception or Error
<pre><code>
Error in src/app/app.component.html (1:25)
Type 'TypeOne[] | TypeTwo[]' is not assignable to type 'TypeOne[] | Iterable<TypeOne> | (Iterable<TypeOne> & TypeOne[]) | (TypeOne[] & Iterable<TypeOne>)'.
Type 'TypeTwo[]' is not assignable to type 'TypeOne[] | Iterable<TypeOne> | (Iterable<TypeOne> & TypeOne[]) | (TypeOne[] & Iterable<TypeOne>)'.
Type 'TypeTwo[]' is not assignable to type 'TypeOne[]'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.0
Node: 12.18.2
OS: win32 x64

Angular: 11.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            7.3.10
@angular-devkit/schematics      7.3.10
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-26 15:18
It appears that we are unable to correctly compute the iterator type for ngFor when the type is a union of two collections.

I wonder if what you want is `items: (TypeOne|TypeTwo)[]` - this will work: https://stackblitz.com/edit/angular-ivy-cwicux?file=src%2Fapp%2Fapp.component.ts

**Comment by petebacondarwin** [comment] 2021-01-26 15:24
The context of the NgFor is given by:

```ts
class NgForOfContext<T, U extends NgIterable<T> = NgIterable<T>> { ... }
```

where `NgIterable` is  `Array<T>|Iterable<T>`.

The problem is that `U` has to represent the individual items being iterated over. But `T = X[]|Y[]` is not iterable, since what would `U` be? It cannot be inferred as `X|Y` since the type says that the whole array must be either `X[]` or `Y[]`.

**Comment by petebacondarwin** [comment] 2021-01-26 15:27
Although it appears that TS itself is able to make this leap: [TS Playground](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCkFNoG9oDcwgK5ILzQEYAGaAXwChRIYANaBADwBcEA7AExngiWQqqjQAmvWZtOcRCgpMAngAckAFWj4aAbQC6AHyFaA3OUoB7VhCbQAliwC2EAFzQV+dawQB3aDQAUASgA00G6ePr6ahuQAZsYATt7ApuZWttDGkckIdr4o5NB5GTYAdBjYCOSkQA)

**Comment by guilhermebentomarques** [comment] 2021-01-26 16:12
> It appears that we are unable to correctly compute the iterator type for ngFor when the type is a union of two collections.
> 
> I wonder if what you want is `items: (TypeOne|TypeTwo)[]` - this will work: https://stackblitz.com/edit/angular-ivy-cwicux?file=src%2Fapp%2Fapp.component.ts

@petebacondarwin this way worked. Thank you! Makes sense to let the ticket opened, corret?

**Comment by petebacondarwin** [comment] 2021-01-26 16:54
I think we can close this as the given use-case is uncommon is unlikely to be something we want to be able to support.
Thanks!

**Closed by petebacondarwin** 2021-01-26 16:54 UTC
Labels: P5, comp: common
