### ISSUE TITLE
CanActivate ignores skipLocationChange flag

### ISSUE THREAD

**Issue by gultyaev** [angular/angular#33834] opened 2019-11-14 21:00 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Not sure

### Description

 The problem is about returning a `createUrlTree` with `skipLocationChange: true`. I expect Angular not to change a URL but it does.

## 🔬 Minimal Reproduction

 https://github.com/gultyaev/can-activate-issue-repro

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.19
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Expected:** browser should silently navigate to `/login`
**Actual:** URL containes `/login`

Steps to reproduce are described in README.md of provided repo.

**Comment by atscott** [comment] 2020-05-29 16:24
This is actually working as intended but the docs could use more clarity. The original navigation's `skipLocationChange` value is used for the redirect. 
https://github.com/angular/angular/blob/bd7393fc6810f3cd2e7e347ba9183ab3dde746a8/packages/router/src/router.ts#L790

See relevant commits:https://github.com/angular/angular/commit/9c153cfb3e2a8a0e22ae64e8f872c1908b99333e, https://github.com/angular/angular/commit/f6667f82819552e12dadd31d475b363fa6d8cd87

**Comment by gultyaev** [comment] 2020-05-29 16:45
So there is no way to redirect to login page and then back without changing URL and adding new items in the navigation history?

**Comment by atscott** [comment] 2020-05-29 16:56
> So there is no way to redirect to login page and then back without changing URL and adding new items in the navigation history?

Not with returning a `UrlTree`, no. You could instead try triggering a new navigation with 
```
router.navigate('/login', {skipLocationChange: true});
return false;
```
This should cancel the current navigation and start a new navigation to the login page without changing the `URL`.

**Comment by atscott** [comment] 2021-03-17 21:54
Closing - now that the `createUrlTree` no longer accepts `skipLocationChange` as a configuration option, the confusion here should be resolved.

**Closed by atscott** 2021-03-17 21:54 UTC
Labels: P4, comp: docs, comp: router, freq2: medium, help wanted, router: guards/resolvers, router: navigation pipe, state: confirmed, triage #1, type: bug/fix
