### ISSUE TITLE
Feature: Ability to decorate injectables

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#14620] opened 2017-02-21 16:40 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm not aware of any way to decorate existing injectable so one could use old version inside new one.

**Expected behavior**
I would be nice to have some way to decorate injectables. Maybe new type of provider - `DecoratorProvider`, which could work like this:

```typescript
@Injectable()
class BetterFooService implements FooService {
  constructor(
    private fooService: FooService, // < not a cyclic dependency
    private otherService: OtherService) {}
  bar(): void {
    console.log('better bar');
    this.fooService.bar();
  }
}

const PROVIDER: DecoratorProvider =  { provide: FooService, useDecorator: BetterFooService };

@Directive({
  selector: '[myDirective]',
  providers: [PROVIDER]
})
class MyDirective {}
```

**Minimal reproduction of the problem with instructions**
Using FactoryProvider/ClassProvider to achieve similar effect causes `Connot instantiate cyclic dependency!` error:
https://plnkr.co/edit/YxGzVA1HNEjC1rXBmMQg?p=preview

**What is the motivation / use case for changing the behavior?**
Directive will have more freedom to modify behaviour of other components/directives.
Example use case:
Directive that decorates `ViewContainerRef` so it wraps every created component/embedded view in other component with animations. It could be used on `RouterOutlet` component to add animations when route changes.

**Please tell us about your environment:**

* **Angular version:** 2.4.7

* **Browser:** all

 
* **Language:** all

**Comment by DzmitryShylovich** [comment] 2017-02-21 16:53
just create a wrapper?

```
@Injectable()
class FooServiceWrapper implements FooService {
  constructor(private serviceToBeDecorated: FooService) {}
  bar(): void {
    console.log('better bar');
    this.serviceToBeDecorated.bar(); //Delegation
  }
}

@Directive({
  selector: '[myDirective]',
  providers: [{provide: FooService: useClass: FooServiceWrapper}]
})
class MyDirective {}
```
You don't need any new syntax for this :)

**Comment by dawidgarus** [comment] 2017-02-21 16:58
That's impossible. You get `Cannot instantiate cyclic dependency!` error.

**Comment by DzmitryShylovich** [comment] 2017-02-21 17:01
plunkr

**Comment by dawidgarus** [comment] 2017-02-21 17:12
Added plunkr

**Comment by DzmitryShylovich** [comment] 2017-02-21 17:20
https://plnkr.co/edit/kQ5QhgD79MnRs4qeEOU8?p=preview

**Comment by dawidgarus** [comment] 2017-02-21 17:35
Shame it doesn't when decoratee is provided on the same host element, like ViewContainerRef:
https://plnkr.co/edit/5hRcns4R96G5j3FRpBM8?p=preview

**Comment by DzmitryShylovich** [comment] 2017-02-21 17:46
ofc it doesn't work
```
@Injectable()
export class MyViewContainerRef {
  constructor(@SkipSelf() private vcRef: ViewContainerRef) {}
}
```
you cannot inject `ViewContainerRef` into a service. it doesn't make sense.

Take a look at https://youtu.be/EMjTp12VbQ8?t=1300

**Comment by DzmitryShylovich** [comment] 2017-02-21 18:04
Ok, if you want to decorate some built-in data structures such as `ViewContainerRef` there's currently no way to do it.
You can probably accomplish it using inheritance.

**Comment by kemsky** [comment] 2017-02-21 22:14
There are two issues that could be improved: 
1. You can not re-provide token on component level without loosing initial token value, token shadows itself in injector leading to cyclic dependency. You can provide new token, but it makes it mostly useless...

2. You can not provide factory to be evaluated at component level. Currently, global providers are resolved before component providers (and only one time), making it impossible to wrap component only services:

```typescript
//module
providers: [
{
    provide: MyElementRef, 
    useFactory: (ref)=> new MyElementRef(ref.nativeElement), 
    deps:[ElementRef]
}
]

//component
constructor(private elementRef:MyElementRef){
//elementRef is created by factory during component instantiation
}
```

**Comment by pkozlowski-opensource** [comment] 2018-10-29 15:10
Closing as a duplicate of #22064 since it has best name / description / discussion.

**Closed by pkozlowski-opensource** 2018-10-29 15:10 UTC
Labels: comp: core & compiler, type: feature
