### ISSUE TITLE
AOT Compiler requires public properties, while non-AOT allows private properties

### ISSUE THREAD

**Issue by cosminadrianpopescu** [angular/angular#37660] opened 2020-06-21 09:59 UTC
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description
 A clear and concise description of the problem or missing capability...

Here we are, 2 years [later](https://github.com/angular/angular/issues/11978), and the Ivy compiler seems to behave in the same way. Still I can't access private properties in templates (or at least protected). 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

I think the generated class for the View, should extend the factory component class, like this, making it at least possible to access protected properties.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

The alternative is very poor. I have to use a `BaseComponent` class, so all my components need to extend this class. Then, in the `BaseComponent` I have a getter, called `view`, like this: 

```
export class BaseComponent {
  public get view(): any {
    return this;
  }
}
...
\@Component(
...
template: `<div>{{view._name}}</div>
...
) export class MyComponent extends BaseComponent {
  private _name = 'X';
}
```

I think this is not very optimal. 

Did I miss something? Can Ivy compiler in Angular 9 access the private properties in the components?

**Comment by Javaman2** [comment] 2020-06-22 12:44
I too had to remove all private properties when migrating components to library.  A bit odd because the final JavaScript does not have private properties.

Visual Studio Code automatically makes refactored methods private. So this problem is at odds with default VSCode refactoring.

**Comment by LastDragon-ru** [comment] 2020-07-06 11:39
> Can Ivy compiler in Angular 9 access the private properties in the components?

>  I'm not sure why Angular team decide on not allowing private access, but that's only a design choice, not technical limitation.
> _https://github.com/angular/angular/issues/27760#issuecomment-489137602_

Look lite this is duplicate of #27760.

**Comment by alxhub** [comment] 2021-07-09 22:33
Some context for this feature request, for anyone who's interested:

In JIT compiled code, private properties can be bound from templates, yes. This is because after TypeScript compilation, access modifiers such as `private` are stripped away without any runtime effect on the code. There is no `private` as far as the runtime is concerned (since such fields aren't compiled into true ES `#private` fields).

Fundamentally, we have this restriction for historical technical (performance) reasons. In order to type-check templates, Angular needs to convert them into TypeScript code, and feed that code to the TypeScript compiler. If you're using the modern Angular Language Service, you can right click on a component's template and `View Type Check Block` to see the code we generate under the hood for template type-checking.

If we wanted to allow `private` property access from this Type Check Block (TCB) code, it would have to exist _inside the component class that the user wrote_. This means that we'd have to internally modify the user's code, feed it to TypeScript to check the TCB, then modify it back to remove the TCB code for emit and the next build iteration. This would be prohibitively expensive in terms of performance. Instead, TCB code lives in separate, hidden files that exist alongside component files . That way, we can inherit it across incremental builds, and it only needs to be updated and re-parsed when templates are changed.

There is a technical path for supporting `protected` fields in templates, by having the TCB exist inside a synthetic derived class which inherits from the component class. There are a lot of implications to a change like this, but I do think there's value in exploring the idea further.

**Comment by JoostK** [comment] 2022-05-22 17:41
An update on this request: binding to `protected` members from a template will be possible in v14, thanks to #45823.

**Closed by JoostK** 2022-05-22 17:41 UTC
Labels: feature, comp: compiler, core: basic template syntax, type: use-case, in backlog
