### ISSUE TITLE
Alpha.48 - Wrong import from rxjs

### ISSUE THREAD

**Issue by sateffen** [angular/angular#5695] opened 2015-12-08 08:47 UTC
Heyho,

I just want to leave a comment: I installed the lastest alpha from npm, and get an error with webpack:

`ERROR in ./~/angular2/src/facade/async.js
Module not found: Error: Cannot resolve module 'rxjs/operators/toPromise' in ...\angular2-test\node_modules\angular2\src\facade
 @ ./~/angular2/src/facade/async.js 13:0-35`

So the problem is [here](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts): The `import 'rxjs/operators/toPromise';` is wrong, the correct import would be `import 'rxjs/operator/toPromise';`.

With this change I can use the angular sources again.

**Comment by robwormald** [comment] 2015-12-08 09:02
hi @sateffen - this is a duplicate of https://github.com/angular/angular/issues/5693 which is a duplicate of https://github.com/angular/angular/issues/5643

it's corrected on master for the next release, apologies for the inconvenience!

**Closed by robwormald** 2015-12-08 09:02 UTC
