### ISSUE TITLE
i18n issue with fr-FR

### ISSUE THREAD

**Issue by tomtomcarter** [angular/angular#21040] opened 2017-12-15 09:54 UTC
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior
When you run ng serve (probably same issue with ng build) and then browse to a component that uses a custom attribut, which itself is using a pipe (PercentPipe)
I get the following error (in console) when I use the custom attribut :
ERROR Error: Missing locale data for the locale "fr".
Maybe I'm doing something wrong ?

## Expected behavior
I should not get the error.

## Minimal reproduction of the problem with instructions
From custom attribut ts file I have : 
- import { PercentPipe } from '@angular/common';
- constructor( @Inject(LOCALE_ID) public locale: string, [...])

From app/module.ts I have:
- in the import section:
`import { registerLocaleData } from '@angular/common';`
`import localeFr from '@angular/common/locales/fr';`
`import localeFrExtra from '@angular/common/locales/extra/fr';`
`registerLocaleData(localeFr, 'fr-FR', localeFrExtra);`

- in the `@NgModule` section I have
`providers: [`
`     ...,`
`    {`
`      provide: LOCALE_ID,`
`      useValue: 'fr-FR' `
`    }`
`]`

## Hint
Isn't the fr-FR files missing form the repo (angular/packages/common/locales/ and/or angular/packages/common/locales/extra) ?
Note that I don't have the issue if I use 'fr' only ; thus with the below in app/module.ts it's OK

`import { registerLocaleData } from '@angular/common';`
`import localeFr from '@angular/common/locales/fr';`
`registerLocaleData(localeFr, 'fr');`

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [x ] Chrome (desktop) version 59
 
For Tooling issues:
- Node version: v6.11.4
- Platform:  Windows 

</code></pre>

**Comment by ocombe** [comment] 2017-12-18 12:17
Can you provide a concrete example that reproduces the issue? Like a plunkr, stackblitz or github repo please?

**Comment by ocombe** [comment] 2017-12-19 09:48
With the cli, you can use the parameter `--locale` so that it auto imports the locale files for you, so instead of `ng serve` you would do `ng serve --locale fr` and it will import it, but if you want to use the locale id `fr-FR` instead of `fr`, you have to import it yourself like you did.
The `fr-FR` files are not missing from the locale files, CLDR uses `fr` instead, since `fr-FR` is the most used regional locale for french, it defaults to `fr`.
Same thing with `en-US` which defaults to `en`.

**Comment by ocombe** [comment] 2017-12-19 10:02
I'm going to close the issue here, and create a new one in the angular/cli repository since it seems to be a cli issue

**Comment by ocombe** [comment] 2017-12-19 10:17
Actually I tried to reproduce the issue, and cannot.
Are you using `--locale` with the cli ?

**Comment by ocombe** [comment] 2018-01-02 10:26
I'm closing this since there was no reply in 2 weeks.
If anyone else has the issue, let us know and please add an example to reproduce the issue.

**Closed by ocombe** 2018-01-02 10:26 UTC
Labels: comp: i18n, flag: can be closed?, severity5: regression, state: Need repro
