### ISSUE TITLE
ngModel and ngModelChange order are affecting the process

### ISSUE THREAD

**Issue by AmerAnsari** [angular/angular#46357] opened 2022-06-14 07:11 UTC
### Which @angular/* package(s) are the source of the bug?

compiler, forms

### Is this a regression?

No

### Description

When using (ngModelChange), it requires ngModel, ngModel is connected to a variable which using in the ngModelChange.

I notice if ngModel comes after ngModelChange, ngModelChange triggers earlier than the next attribute which is ngModel and I don't have the fresh data ngModelChange.

Yes, we can get the data from $event of ngModelChange="hello($event)" and fix this issue with other things, but sometimes we cannot do anything in some places.

So I'm looking if this is a bug and can be fixed or if it's intended.

**Comment by pkozlowski-opensource** [comment] 2022-06-14 07:29
This is a duplicate of the existing issue #11234

**Closed by pkozlowski-opensource** 2022-06-14 07:29 UTC
