### ISSUE TITLE
Unexpected "ExpressionChangedAfterItHasBeenCheckedError" thrown on form input "className" interpolation

### ISSUE THREAD

**Issue by kaikcreator** [angular/angular#35443] opened 2020-02-14 10:20 UTC
# 🐞 bug report

### Affected Package
The issue is probably caused by package @angular/forms
Probably related with #34804 

### Is this a regression?
This behaviour seems to happen only when using IVY

### Description
GIVEN we are using dev mode
AND there's an input and the `className` property of that input is being interpolated in the template
WHEN `NgModel` changes the Angular CSS state classes of that input
THEN a `ExpressionChangedAfterItHasBeenCheckedError` error is thrown.

## 🔬 Minimal Reproduction
Github repo: https://github.com/kaikcreator/ng-className-bug

Relevant code below:

**template**
```html
<div>
  <input type="text" id="name" required
    [(ngModel)]="model.name" name="name"
    #spy>
</div>

<p>CSS Angular classes applied to input: {{spy.className}}</p>
```

**component code (just for context, but not really relevant)**
```ts
import { Component } from '@angular/core';

interface Person {
  name: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  model: Person = {
    name: ''
  };
}
```

By the way, this code is almost identical to one of the Hero Form examples on the Angular Guide (https://angular.io/guide/forms). Same error occurs in that example when using IVY.

## 🔥 Exception or Error
<pre><code>
core.js:5845 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-dirty ng-touched ng-valid'. Current value: 'ng-dirty ng-touched ng-invalid'.
    at throwErrorIfNoChangesMode (core.js:8045)
    at bindingUpdated (core.js:19671)
    at interpolation1 (core.js:19815)
    at Module.ɵɵtextInterpolate1 (core.js:24114)
    at AppComponent_Template (app.component.html:7)
    at executeTemplate (core.js:11858)
    at refreshView (core.js:11705)
    at refreshComponent (core.js:13145)
    at refreshChildComponents (core.js:11436)
    at refreshView (core.js:11757)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 12.16.0
OS: darwin x64

Angular: 9.1.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by atscott** [comment] 2020-04-08 21:19
Minimal repro without forms: https://stackblitz.com/edit/angular-megwwb - Any non-static host binding will cause this error because host bindings from expando instructions are set after the text binding is evaluated https://github.com/angular/angular/blob/b40b5576df83745c42a45c6379038a51a90f8ac0/packages/core/src/render3/instructions/shared.ts#L451

**Comment by atscott** [comment] 2020-05-13 22:57
Hi @kaikcreator, without getting too much into the details of VE vs Ivy implementations, this error is expected when running with Ivy because host bindings are set after the template is executed.

Can you describe your use-case for this so we can figure out a suitable workaround? I wouldn't usually expect a production app to be printing out element attributes to the screen. Though if this is actually what you want, you can create a child component that does this (since child components will be processed after the host), for example:
```
@Component({
  selector: 'class-name-display',
  template: 'CSS Angular classes applied to input: {{el.className}}'
})
export class ClassNameDisplay {
  @Input() el: Element;
}
```

At the very least, I'll need to take a look at the forms doc and see what we can change so that it's not using a pattern that will result in `ExpressionChangedAfterItHasBeenCheckedError`

**Comment by atscott** [comment] 2020-05-19 19:15
Adding `working as expected` and `confirmed` state labels and keeping this bug open as a reference. 

In short, host bindings are set after the template executes so this error is expected when attribute values affected by host bindings are used in the template.

The forms tutorial is being updated in #36732 and will no longer include this pattern that would result in the `ExpressionChanged` error.

**Comment by atscott** [comment] 2020-09-11 17:03
Closing as duplicate of #32083

**Closed by atscott** 2020-09-11 17:03 UTC
Labels: comp: core, comp: docs, comp: forms, core: change detection, core: host and host bindings, engine: ivy, freq1: low, severity5: regression, state: confirmed, state: works-as-expected, triage #1, type: bug/fix
