### ISSUE TITLE
Fresh PWA does not work offline in Chrome

### ISSUE THREAD

**Issue by zelite** [angular/angular#31316] opened 2019-06-27 17:02 UTC
# 🐞 bug report

### Affected Package
@angular/pwa

### Is this a regression?

I don't know.

### Description

I created a new angular pwa application and deployed to Github Pages. The application does not work offline in the chrome browser. 

## 🔬 Minimal Reproduction

https://github.com/zelite/markdown-previewer
https://zelite.github.io/markdown-previewer

I created the application using the angular cli, and added material components and pwa schematic.
I deployed the app with the help of https://github.com/angular-schule/angular-cli-ghpages

## 🔥 Exception or Error
When offline, the application gets a 504 error.

<pre><code>
GET https://zelite.github.io/markdown-previewer/ 504 (Gateway Timeout)
</code></pre>

The Network Tab in the developer tools shows an error requesting the following url: https://zelite.github.io/markdown-previewer/ngsw.json?ngsw-cache-bust=0.6488919669820217

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.4
Node: 10.16.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/material                 8.0.1
@angular/pwa                      0.800.4
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

The application does not work offline in chrome, but it works on firefox.

**Comment by gkalpak** [comment] 2019-06-27 20:09
@zelite, how are you building the app? I noticed that all paths in `ngsw.json` have the full URL (`https://zelite.github.io/...`). That prevents the SW from identifying that it knows about the assets. (Basically, the SW sees a request for `https://zelite.github.io/markdown-previewer/foo` and (since it is on the same domain as its scope) it expects to find a cached asset under `/markdown-previewer/foo`. But it cann't find it, because the asset is cached under `https://zelite.github.io/markdown-previewer/foo`.)

**Comment by gkalpak** [comment] 2019-06-27 20:11
I am going to close this issue, since (at this point) it seems to be a configuration error, but please continue the discussion below.

**Closed by gkalpak** 2019-06-27 20:11 UTC
Labels: comp: service-worker

**Comment by zelite** [comment] 2019-06-28 03:17
I'm building with: 

```
ng build --prod --base-href "https://USERNAME.github.io/REPOSITORY_NAME/"
```


And deploying with: 

```
npx angular-cli-ghpages --dir=dist/[PROJECTNAME]
```

Then I edited the manifest to match the
Base href, otherwise the service worker was not even registering.

What's resource do you recommend to get help? Stackoverflow?

**Comment by gkalpak** [comment] 2019-06-28 12:53
Can you try with just `ng build --prod --base-href "/REPOSITORY_NAME/"`. I think that should work without any modifications.

#31082 will also improve handling of more base-href values, but not sure if it will allow using the full URL (including the origin).

StackOverflow and [gitter](https://gitter.im/angular/angular) are generally good places to ask for help.

**Comment by glemiere** [comment] 2019-07-02 00:03
As I said here https://github.com/angular/angular/issues/31273#issuecomment-507464121 you probably have an Apache server used as a proxy or used to serve your static dist.

So you should rename your `manifest.webmanifest` into `manifest.json`, modify `angular.json` accordingly as well as your manifest link in `index.html` the following way:

`<link rel="manifest" href="manifest.json" crossorigin="use-credentials">`

However I still have some issues after that, like `start_url` isn't found for some reason.

**Comment by pacoita** [comment] 2019-07-16 07:31
I had the same issue and I can confirm that the suggestion of @gkalpak  🎉  fixes the problem 🎉 :, allowing the service worker to serve the assets properly.

The property "start_url" in the `web manifest` file has still to be modified manually to match the baseHref though.

**Comment by gkalpak** [comment] 2019-07-16 07:58
@pacoita, could you open an issue on the [cli repo][1] about the `start_url`?
You shouldn't need to manually update it.

[1]: https://github.com/angular/angular-cli

**Comment by pacoita** [comment] 2019-07-16 08:47
@gkalpak sure, I will do it.
