### ISSUE TITLE
Value property is not binding properly when resetting the same value the value property

### ISSUE THREAD

**Issue by k10oo7** [angular/angular#30915] opened 2019-06-07 11:59 UTC
My use case is like, some input field is there and on change of the input field value, I am checking the value is within 0 to 100 range. If it goes beyond the range then I am reverting the value to default value i.e. 50.
Sample Code:
https://stackblitz.com/edit/angular-f5mh4m-yqpgcx
In the input field provide a value greater than 100. You can find that default value is not reflecting into the input field.

**Comment by trotyl** [comment] 2019-06-07 12:41
Duplicate of https://github.com/angular/angular/issues/6916, https://github.com/angular/angular/issues/9275, https://github.com/angular/angular/issues/13063

**Comment by mhevery** [comment] 2019-06-07 17:16
closing as doop

**Closed by mhevery** 2019-06-07 17:16 UTC
