### ISSUE TITLE
Angular 2- filename/path character limit on templates?

### ISSUE THREAD

**Issue by Tyree** [angular/angular#7926] opened 2016-04-06 11:19 UTC
I'm on Windows 7 64bit, running a local xampp server to host my application.
I have run into an issue and I'm not sure if it's a bug in angular (or perhaps system.js ???) or something in my environment.
I have a template named "contact-detail.template.html". The html (or text) within this template will not render on the page unless I shorten the filename even by just one character. Other templates have worked just fine up until now because the filenames are shorter.

The full path length through this file name is only 62 characters. I don't believe that's long enough to cause such a problem.

Has anyone else seen this issue come up? Is there a workaround or something in my environment causing it? I get no errors, so it's been difficult to troubleshoot. I already pulled out most of my hair just figuring out the length issue was the cause of the html not showing up.

Thanks!

**Comment by pkozlowski-opensource** [comment] 2016-04-07 14:33
There must be sth else going on since there are no limits in the frameworks code. Hard to say more without a minimal, live reproduction scenario. Closing till we've got one.

**Closed by pkozlowski-opensource** 2016-04-07 14:33 UTC

**Comment by Tyree** [comment] 2016-04-07 14:36
It was a stab in the dark to even ask here. I didn't figure such a limitation existed. I updated node.js to the latest and angular to beta 13 and now it's all working. So, it's hard to say what the issue was.
Thanks!

**Comment by damiandennis** [comment] 2016-04-07 18:59
This is a windows issue. https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx#maxpath
a solution is to mount an extended drive or use a VM.

**Comment by Tyree** [comment] 2016-04-07 19:05
First thing I thought of was a Windows path length issue, but I am only hitting 62 characters. Nowhere near the 260 character MAX_PATH limit. At any rate, it's working now. If it was a Windows limitation, it wouldn't have gone away by updating node and angular.
