### ISSUE TITLE
Initialization of content children with component

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#5154] opened 2015-11-05 23:04 UTC
Hi guys

I stumbled upon this and it kind of felt weird to me. Maybe you can explain the behavior or tell me what I'm doing wrong here. Given this example:

```javascript
@Component({
  selector: 'tab',
  template: `<ng-content></ng-content>`
})
class Tab {}

@Component({
  selector: 'tabs',
  template: `<ng-content select="tab"></ng-content>`,
  directives: [Tab]
})
class Tabs {
  @ContentChildren(Tab) tabs;

  afterContentInit() {
    console.log('Tabs', this.tabs);
  }
}

@Component({
  selector: 'app',
  template: `
    <tabs>
      <tab>I'm a Tab!</tab>
    </tabs>
  `,
  directives: [Tabs]
})
class App {}
```

I'd expect this to work but it turns out that the tab components are never initialized and the tabs query list will be empty in `afterContentInit`.

If I add `Tab` also into the `App` directives list, the example works, the components get initialized and the query list also contains the `Tab` component within the tabs `afterContentInit`.

Am I doing something wrong here? I'd expect the example to work without needing to add the `Tab` component into the directives list of the `App` component as I'd expect content is pulled into `Tabs` before it gets compiled there.

**Comment by ericmartinezr** [comment] 2015-11-05 23:24
Did you try with `ViewChildren` and `afterViewInit`? I think `ng-content` may be doing something in there. Also I think you must specify QueryList in `ContentChildren/ViewChildren`.

**Comment by gionkunz** [comment] 2015-11-06 00:01
Well, the children get created as content children with `ng-content`. I think `ViewChildren` is only used if your components template contains direct child directives. I think you don't need to specify `QueryList` as type annotations are optional.

**Comment by pkozlowski-opensource** [comment] 2015-11-06 10:06
@gionkunz could you please send a plunk with a minimal reproduction scenario? We do lack context here (ex. ng2 version used).

**Comment by pkozlowski-opensource** [comment] 2015-11-06 16:13
Oh, I see, this is the crux of your pb:

> If I add Tab also into the App directives list, the example works, the components get initialized and the query list also contains the Tab component within the tabs afterContentInit.
>
> Am I doing something wrong here? I'd expect the example to work without needing to add the Tab component into the directives list of the App component as I'd expect content is pulled into Tabs before it gets compiled there.

Nope, with the current system you need to list all directives that are used in your template. And `tab` is used in the app's template.

Having said this I agree that this is pain in a neck and we've got an issue for this already: 
https://github.com/angular/angular/issues/4733

@gionkunz I'm going to close this as a dupe of #4733 - let's move the discussion in there.

**Closed by pkozlowski-opensource** 2015-11-06 16:13 UTC

**Comment by gionkunz** [comment] 2015-11-08 09:10
Cool, good to know you guys track this already. Thanks for looking into it.

**Comment by robertbrower** [comment] 2016-04-13 11:20
If you define a component and child component in the same file then please put the child component above the parent component in that file, otherwise your query result will be empty. I learned this today.

**Comment by zoechi** [comment] 2016-04-13 12:45
@robertbrower that's not limited to `QueryList`. In TypeScript classes are not hoisted and if you reference a type that is only declared further down in your code it is unknown and will break your code. This is also for constructor injection or `directives: [...]` or everything else where type are required.

To work around you can use [forwardRef](https://angular.io/docs/ts/latest/api/core/forwardRef-function.html).  
See also http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html
