### ISSUE TITLE
Dependency Injection failing when a second decorator is in class

### ISSUE THREAD

**Issue by Jonatthu** [angular/angular#14600] opened 2017-02-20 17:43 UTC
```
[x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
I have a class which I want to inject within it's constructor properties, they are classes too with `@Injection()` decorator, 

```
@Injectable()
@remotedev({ name: 'STORE', onlyActions: true })
export class Store {
constructor(
    public alerts: AlertsStore,
    public client: ClientStore,
    public search: SearchStore,
    public searchListing: SearchListingStore
  ) {}
```
the other classes just have `@Injectable()` decorator and not a second decorator,
my index.ts to put the providers in the app module has the right order

```
export * from './alerts.store';
export * from './client.store';
export * from './search.store';
export * from './search-listing.store'
export * from './store';
```

and the providers looks like this

```
  providers: [
    AlertsStore,
    ClientStore,
    SearchStore,
    SearchListingStore,
    Store
  ],
```

and every property on the constructor is undefined. which is weird because on ionic 2 which is using `@angular 2.2.1` is working normally without problems, but a project generated with ng cli is not working which is beta 32, and has angular ^2.4.0, so I'm not sure why this is working in ionic 2 and this not.

**Expected behavior**
Inject each class on the constructor

**Minimal reproduction of the problem with instructions**
https://github.com/Jonatthu/angular-dependency-injection-failing

**What is the motivation / use case for changing the behavior?**
Works fine on ionic 2 and this should work as well, without problems.

* **Angular version:** 2.0.X
Angular CLI beta.32.2, ionic has angular 2.2.1 and @angular from angular-cli is 2.4.2 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:**  TypeScript

* **Node (for AoT issues):** `node --version` =   6.9.2

**Comment by DzmitryShylovich** [comment] 2017-02-24 21:39
Can't reproduce using a custom webpack build. Pls re-open this issue on https://github.com/angular/angular-cli/issues

**Comment by Jonatthu** [comment] 2017-02-24 21:51
@DzmitryShylovich Thanks! Just for curiosity can I have your custom webpack build? I will re-open this on ng-cli as well

**Comment by Jonatthu** [comment] 2017-02-24 21:52
https://github.com/angular/angular-cli/issues/4994

**Comment by DzmitryShylovich** [comment] 2017-02-24 21:53
@Jonatthu I tested using https://github.com/qdouble/angular-webpack2-starter

**Comment by DzmitryShylovich** [comment] 2017-02-24 21:54
@Jonatthu close this issue pls, thx

**Closed** 2017-03-01 06:41 UTC

**Comment by Jonatthu** [comment] 2017-03-02 14:51
@DzmitryShylovich 
Seems like this only happens if you are using the redux remotedev extensions on chrome and this 
https://github.com/zalmoxisus/mobx-remotedev

Can you test with this extension on chrome?
When I remove this extension from chrome it works, but activated not
