### ISSUE TITLE
DI outside of constructor

### ISSUE THREAD

**Issue by rafaelbatistamarcilio** [angular/angular#27293] opened 2018-11-27 15:43 UTC
Hy,

Why not make properties dependency injection like @Autowired in Spring Framework and use @Inject outside of constructors?

Today DI:

```
export class MyComponent {
     constructor(private myService: MyService, private mySecondService: MySecondService){}
}
```

Desired DI:

```
export class MyComponent {
     
      @Inject()
      private myService: MyService;

      @Inject()
      private mySecondService: MySecondService;
}
```

**Comment by thorn0** [comment] 2018-11-27 15:52
Duplicate of #6972.

An explanation from there:

> Constructors are cumbersome because object creation is cumbersome. Property injection would just move the problem somewhere else and Angular had to provide another definition about timings (what is initialized in what order).
That seems redundant and would make it more complex because there are the language requirements already (constructor, final fields, ...) and then additional framework requirements.
I wouldn't see this as improvement.

**Comment by jasonaden** [comment] 2018-11-27 18:39
Closing based on the above explanation.

**Closed by jasonaden** 2018-11-27 18:39 UTC
