### ISSUE TITLE
Using route.url.pop in canActivate causes page change

### ISSUE THREAD

**Issue by mebibou** [angular/angular#52013] opened 2023-10-04 10:56 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When migrating to angular 16, navigating to any page in my application was basically not working anymore. Page would just route back to the beginning of the app. After testing a few things, I found out this was the issue:
```
@Injectable({
  providedIn: 'root'
})
export class Guard  {
  canActivate(route: ActivatedRouteSnapshot) {
    const url = route.url.pop().path;
  }
}
```

After changing `route.url.pop()` to `route.url.slice().pop()`, the problem went away. Seems that since angular 16, the `url` is not immutable anymore? and just using `pop` will basically make the whole routing go haywire?

### Please provide the exception or error you saw

```true
No exception, just page keeps re-routing
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.4
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.2.7
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.4
@angular-devkit/build-angular   16.2.4
@angular-devkit/core            16.2.4
@angular-devkit/schematics      16.2.4
@angular/cdk                    16.2.6
@angular/cli                    16.2.4
@angular/google-maps            16.2.6
@schematics/angular             16.2.4
rxjs                            6.6.7
typescript                      5.1.6
zone.js                         0.13.1
```

### Anything else?

It was working fine on Angular 15

**Comment by atscott** [comment] 2023-10-04 13:27
Duplicate of https://github.com/angular/angular/issues/27528

**Closed by atscott** 2023-10-04 13:27 UTC
