### ISSUE TITLE
Bad performance on google lighthouse due to zone.js

### ISSUE THREAD

**Issue by arkajitEY** [angular/angular#53517] opened 2023-12-12 09:03 UTC
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

I'm running lighthouse report on my angular app which also uses spartacus storefront, getting high execution time on pollyfills.js, I am seeing zone.js is the only import in the polyfills.ts file.

polyfills.ts contains zone.js import only
```
/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js';  // Included with Angular CLI.
```
LightHouse report for reference:
https://i.stack.imgur.com/uFFiO.png

I tried updating the zone.js version to latest version but didn't reduce time.

any approach that can reduce the script evaluation time? 

### Anything else?

Angular CLI: 15.2.9
Node: 16.16.0

**Comment by alan-agius4** [comment] 2023-12-12 09:09
Duplicate of https://github.com/angular/angular-cli/issues/14871

**Closed by alan-agius4** 2023-12-12 09:09 UTC
