### ISSUE TITLE
The AoT compiler should support @Input or @Output from base classes

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#11060] opened 2016-08-25 08:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The runtime compiler works with `@Input` and `@Output` members declared in a base class, the AoT compiler doesn't.

**Expected/desired behavior**
The AoT compiler should work as well.

**Reproduction of the problem**

```ts
class Base {
  @Input() value: string;
}
@Component()
class Derived extends Base {
}
```
When I use `Derived` in a template it works at runtime. With AoT the compiler complains
```
Can't bind to 'value' since it isn't a known property of 'derived'.
```

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5

**Comment by Tragetaschen** [comment] 2016-08-25 08:12
As a workaround, I'm redeclaring the inputs and outputs in the component metadata: `@Component({ inputs: ["value"] })`

**Comment by RomanGotsiy** [comment] 2016-08-25 19:23
AoT doesn't support lifecycle from base class as well:

```js
class Base implements OnInit {
  ngOnInit() {
    console.log('log');
  }
}
@Component(...)
class Derived extends Base {
}
```
`ngOnInit` hook is not called for `Derived` component. Adding `implements OnInit` to `Derived` doesn't work too.

Should I open a separate issue for this?

**Comment by chuckjaz** [comment] 2016-08-25 20:07
Using inheritance for a component is a discouraged pattern and is not supported by AoT, therefore this is intended behavior. There are significantly more complicated issues that arise when you combine annotations with inheritance that are out of scope to resolve for 2.0.0.

Consider resubmitting or recasting as a feature request.

**Comment by kylecordes** [comment] 2016-08-25 20:10
@chuckjaz How about treating this item as a bug report, the bug being that the JIT compiler *does* allow this discouraged thing?

**Comment by chuckjaz** [comment] 2016-08-25 20:18
I would prefer another issue (or this one edited). It is confusing to have the text of the bug say one thing but we are using it to track another thing.

**Comment by Tragetaschen** [comment] 2016-08-25 20:35
I have moved the `x` to the next line.

The obvious meta question now is (given the other issues I ran into): What are the "supported" coding patterns for the AoT compiler and will it be an inclusive list or an exclusive one? Given that it's JavaScript at runtime, there's likely tons of stuff that will have expected semantics in the browser, but fail to compile AoT.

**Comment by chuckjaz** [comment] 2016-08-25 20:45
I am working on a document that is intended to describe what is supported. It will be an inclusive list of things that work with both JIT and AoT. I hope to have the first version available to review next week.

**Comment by zoechi** [comment] 2016-10-10 05:25
dup of https://github.com/angular/angular/issues/11606

**Comment by pkozlowski-opensource** [comment] 2016-10-11 14:58
This is tracked in #11606

**Closed by pkozlowski-opensource** 2016-10-11 14:58 UTC
Labels: comp: core & compiler, type: feature
