### ISSUE TITLE
Angular2 UpgradeComponent missing $injector

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular#12965] opened 2016-11-18 12:54 UTC
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I was following the Upgrade documentation to upgrade an Angular1 Component to Angular2:
https://angular.io/docs/ts/latest/guide/upgrade.html

When using `@angular 2.2.1`'s `UpgradeComponent`, it gives an error saying this.$injector is not found in `upgrade_component.js`

![screen shot 2016-11-18 at 12 01 42](https://cloud.githubusercontent.com/assets/2917613/20430650/7d42f6e4-ad8d-11e6-87b8-40d5636971b4.png)

Upon closer inspection... Line 97 of `upgrade_component.js` is `undefined`:
![screen shot 2016-11-18 at 12 02 59](https://cloud.githubusercontent.com/assets/2917613/20430678/a1144dde-ad8d-11e6-9ae5-f2c858ef1720.png)

**Minimal reproduction of the problem with instructions**
Minimal Demo is created using `angular-cli`, with only **one** filed added: https://github.com/dolanmiu/angular2-upgrade-test
https://github.com/dolanmiu/angular2-upgrade-test/blob/master/src/app/chart/chart.component.ts

The corresponding `.ts` file is here:
https://github.com/angular/angular/blob/master/modules/@angular/upgrade/src/aot/upgrade_component.ts#L121

**What is the motivation / use case for changing the behavior?**

I **need** to upgrade old existing Angular1 code into Angular2

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **Browser:** [all | Chrome]

 
* **Language:** [all | TypeScript]

* **Node (for AoT issues):** `node --version` =  6.9.1

**Comment by HJoost** [comment] 2016-11-23 10:24
Same problem here

**Comment by 3du4** [comment] 2016-11-30 08:22
@dolanmiu would be helpful if you can reproduce it in plunker because I am getting a similar issue but unsure is related to this one.

**Comment by dolanmiu** [comment] 2016-11-30 10:07
@3du4 I want to, but I don't know how to make a Plunkr with `@types/upgrade` :(

**Comment by 3du4** [comment] 2016-12-01 02:00
@dolanmiu 
What are you using for file mapping? webpack of systemjs? If you are using systemjs can I see your config file?

**Comment by 3du4** [comment] 2016-12-02 07:55
I am starting to think that my problem is related to this one.
My browser returns exactly the same error when I call an upgraded AngularJS directive from an Angular 2 component (template). I have created a plunker.

http://plnkr.co/edit/xWJTSq?p=preview

**Comment by dolanmiu** [comment] 2016-12-02 11:00
@3du4 Yes! that is exactly the error

```js
this.$compile = this.$injector.get($COMPILE);
```

`this.$injector` is **undefined**

Nice work

**Comment by dolanmiu** [comment] 2016-12-02 11:01
@3du4 I am using webpack.

**Comment by bastijns-jeroen** [comment] 2016-12-06 09:22
@dolanmiu 
I had the same issue but with SystemJs. If you read the upgrade docs carefully it states that you always have to take an angular 1 component as root and use a downgraded angular 2 component in it to bootstrap a hybrid A1/A2 app. From that angular 2 component you can normally use Angular 2 components.

The key is every time you go from a A1 context to an A2 context or the other way arround, you have to up or downgrade components to the parent context level. Once down or upgraded you can use other components living in the same A1 or A2 context.

**Comment by vladotesanovic** [comment] 2016-12-06 18:46
correct, you need to downgrade angular2 component and to bootstrap angular1 as well ( after bootstrapping angular 2 ).

Angular1: https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/anglarjs.ts#L88

Bootstrapping: https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/main.ts#L20

With this, i was able to load angular1 component ( ui-grid ) on angular2 and use @Input decorator to pass data from Angular 2 -> Angular 1.

Here is demo: http://ui-grid2.surge.sh/#/route1

For me, everything works fine when i am go from AppModule, but when i try to use angular1 inside lazy loaded module, i get exact error as you have.

``` this.$injector ``` is undefined in **HomeModule**, 

If you want to see error: http://ui-grid2.surge.sh/#/home/about

**Comment by petebacondarwin** [comment] 2016-12-19 11:14
So for many of the people in this thread, I believe the problem comes from providing a `bootstrap` component in your `AppModule`. For example, here https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/app/app.module.ts#L52

What happens in this case is that when we bootstrap the AppModule, via `platform.bootstrapModule(AppModule)` (https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/main.ts#L18) it immediately tries to boot up the `AppComponent`, instead of waiting for the Angular 1 bits to do their bootstrap.

We should not have any components in the `bootstrap` property of the `AppModule`.

**Comment by vladotesanovic** [comment] 2016-12-20 11:03
@petebacondarwin 
Ok, than we need to move AppComponent in entryComponents: 

```
entryComponents: [
    AppComponent
  ],
```

And use ngDoBootstrap like:

```
export class AppModule {
  ngDoBootstrap(appRef: ApplicationRef): void {
    appRef.bootstrap(AppComponent);
  }
}
```

?

**Comment by petebacondarwin** [comment] 2016-12-20 11:38
If you are using `upgrade/static` then you should only move the `AppComponent` to the `entryComponents` and not put anything inside `ngDoBootstrap`.

**Comment by vladotesanovic** [comment] 2016-12-20 13:22
correct @petebacondarwin

**Comment by petebacondarwin** [comment] 2016-12-21 11:18
Closing as I think that `upgrade/static` is working as expected. Please open another issue with a reproduction of the problem if you think there is a bug in `upgrade/static`.

**Closed by petebacondarwin** 2016-12-21 11:18 UTC
Labels: comp: upgrade/static, flag: can be closed?

**Comment by sebek64** [comment] 2017-01-02 19:38
I've encountered the same issue and spent half a day on it until I found what's wrong.

https://plnkr.co/edit/ocxuE39B7Aci8wmSNEJJ

Problem is with ngOnInit lifecycle method. When you put it on a ng2 service that injects upgraded services, factory for this upgraded service is called sooner (during bootstrapModule, not in upgrade.bootstrap as it should, so $injector is not available).

I cannot reopen this issue. I can report a new bug if you want.

**Comment by sebek64** [comment] 2017-01-03 11:04
Well, and there is another scenario in which $injector is undefined.

https://plnkr.co/edit/eq8VXrAnMWExTDdZJEF6

When we inject an upgraded service (e.g. $rootScope) into a downgraded service (in this example, MyService) and inject MyService into a run() block, then MyService is constructed with $injector still undefined.

**Comment by dolanmiu** [comment] 2017-01-03 11:10
I feel this needs to be re-opened

**Comment by sebek64** [comment] 2017-01-03 11:30
And another case is for $http interceptors:
 
`
config(function($httpProvider) {
      $httpProvider.interceptors.push(function(MyService) {...})
}));
`

When $http is used during an early phase (like with angular translate downloading translation files), then MyService is also instantiated with $injector undefined.

**Comment by sebek64** [comment] 2017-01-06 14:44
Well, since nobody from the angular team is interested in closed issues, I've resubmitted it as suggested: https://github.com/angular/angular/issues/13811
