### ISSUE TITLE
bug(router-builds) on initial load, async data doesn't display on routes until change detection is triggered

### ISSUE THREAD

**Issue by qdouble** [angular/angular#10079] opened 2016-07-14 18:05 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
On initial load, async data does not display on the view of routed components until change detection is triggered. 

You can see the bug here: https://plnkr.co/edit/YejWm5?p=preview
The get request is made onInit(), but the data won't be displayed to the view until you trigger change detection somehow. In the example, you can click the button which calls `markForCheck()`.

However, async data will show on the main view immediately: https://plnkr.co/edit/TbtQKU?p=preview
In the second example, you can see the async data will show right away on the main app component, but you have to trigger change detection for it to show on the component below.

I think this bug is specific to the router-builds version of the router as this behavior isn't present on the RC4 router and it doesn't occur when using @ngrx/router. I thing the bug was introduce to router-builds last Friday specifically.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-builds
 
* **Browser:** [all ] 
 
* **Language:** [all | TypeScript X.X]

**Comment by tomsdev** [comment] 2016-07-28 12:44
FYI as a temporary workaround you can force re-rendering of the component by injecting `ChangeDetectorRef` in your component and calling in your callback: `this.cdr.detectChanges();`

**Comment by qdouble** [comment] 2016-07-28 19:32
@tomsdev  that's not fully safe without using setTimeout()....

@vsavkin I also noticed there is a problem probably related to this one, with the data being updated when you press the back button. If you don't manually trigger change detection after pressing the back button, the view doesn't update properly.

**Comment by vsavkin** [comment] 2016-07-28 21:23
This is the reason: https://github.com/angular/angular/issues/10363. It is unrelated to the router. Closing this issue.

**Closed by vsavkin** 2016-07-28 21:23 UTC
Labels: comp: router

**Comment by gdi2290** [comment] 2016-07-29 14:09
the problem is with npmcdn and zonejs where it's loading the node version rather than the browser version

<img width="546" alt="screen shot 2016-07-29 at 7 07 25 am" src="https://cloud.githubusercontent.com/assets/1016365/17250873/200e3248-555b-11e6-986d-c4594e24a6e2.png">

related https://github.com/mjackson/npm-http-server/issues/29

**Comment by qdouble** [comment] 2016-07-29 16:35
@gdi2290 how do we change to the right version exactly? On local machine I'm actually using Webpack and not System JS.... I'm using the same imports as the angular2-webpack-starter repo and the issue persists

**Comment by gdi2290** [comment] 2016-07-29 16:39
if you're using webpack and the same inputs then yo should be good

**Comment by tbosch** [comment] 2016-08-01 09:16
@gdi2290 The version of `zone.js` is the same AFAIK. This example should work, and the bug that victor referred to was valid, and is now fixed.

**Comment by tbosch** [comment] 2016-08-01 11:10
This works now (when using `rawgit.com` and not `cdn.rawgit.com` to get the latest changes): https://plnkr.co/edit/xaSPIS?p=preview
