### ISSUE TITLE
Error NG6003 after upgrade from 9.0.5 to 9.0.6

### ISSUE THREAD

**Issue by ovchinnikov** [angular/angular#36216] opened 2020-03-24 08:20 UTC
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.5

### Description

Module has not been processed correctly by ngcc

## 🔬 Minimal Reproduction
1) clone repo https://github.com/ovchinnikov/test-app07
2) `npm install`
3) `npm run ngcc`

## 🔥 Exception or Error
<pre><code>

123 export declare class DxValidatorModule {
                         ~~~~~~~~~~~~~~~~~
node_modules/devextreme-angular/ui/vector-map/index.d.ts:621:22 - error NG6003: Appears in the NgModule.exports of DevExtremeModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (devextreme-angular/ui/vector-map) which declares DxVectorMapModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.


...
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.7
Node: 12.14.0
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.7
@angular-devkit/core         9.0.7
@angular-devkit/schematics   9.0.7
@schematics/angular          9.0.7
@schematics/update           0.900.7
rxjs                         6.5.3

</code></pre>

**Anything else relevant?**
The previous version in which this bug was not present was: 9.0.5
1) clone repo https://github.com/ovchinnikov/test-app05
2) npm install
3) `npm run ngcc` works as expected.

**Comment by petebacondarwin** [comment] 2020-03-24 10:53
This is indeed a regression due to https://github.com/angular/angular/pull/35756.
The `devextreme-angular/ui` folder is not an entry-point (has no package.json) and so we are no longer walking the folders below it looking for further secondary entry-points.

**Comment by petebacondarwin** [comment] 2020-03-24 11:35
Tracking at FW-2020. I expect work to start on a fix for this later this week.

**Comment by petebacondarwin** [comment] 2020-03-29 18:01
Just about squeezed in a fix before the start of next week :-)

**Closed** 2020-04-01 20:21 UTC
Labels: comp: ngcc, severity5: regression
