### ISSUE TITLE
Since beta.1 you can't create a component called AppView

### ISSUE THREAD

**Issue by rubyboy** [angular/angular#6393] opened 2016-01-11 07:16 UTC
I know it sounds weird, but when using AppView the app throws a "No Directive annotation found on e" error in the console and doesn't load the component.
Maybe it's a reserved component name. This worked well prior to beta.1

Here's a plunker to illustrate the problem: https://plnkr.co/edit/ap3oeiCryYy4UOykU1cI?p=preview
If you downgrade the version to "beta.0" or update the component name to anything that is not "AppView" (MyAppView, AppComponent, etc.) it works well.

**Comment by wesleycho** [comment] 2016-01-11 17:32
Interestingly, renaming the import does not seem to fix this issue: https://plnkr.co/edit/Vs2vQsDaYSgsEHgqm8cj?p=preview

Only renaming the component name itself fixes this.

**Comment by gdi2290** [comment] 2016-01-11 18:02
the problem is with the recent codegen feature so any of these will also conflict
```es6
[
  exports,
  styles,
  resolvedMetadataCache,
  /* App, (your Component name) */
  /* viewFactory_App0, (your viewFactory generated name) */
  AbstractChangeDetector,
  ChangeDetectionUtil,
  ChangeDetectorState,
  AppProtoView,
  AppProtoElement,
  ViewType,
  AppView,
  AppElement,
  flattenNestedViewRenderNodes,
  checkSlotCount
]
```
here's the outputed code if you want to kind of see what's going on
```es6
(function(exports,styles,resolvedMetadataCache,App,viewFactory_App0,AbstractChangeDetector,ChangeDetectionUtil,ChangeDetectorState,AppProtoView,AppProtoElement,ViewType,AppView,AppElement,flattenNestedViewRenderNodes,checkSlotCount
/**/) {

      var ChangeDetector_App_0 = function ChangeDetector_App_0() {
        AbstractChangeDetector.call(
            this, "App_0", 11,
            ChangeDetector_App_0.gen_propertyBindingTargets, ChangeDetector_App_0.gen_directiveIndices,
            5);
        this.dehydrateDirectives(false);
      }

      ChangeDetector_App_0.prototype = Object.create(AbstractChangeDetector.prototype);

      ChangeDetector_App_0.prototype.detectChangesInRecordsInternal = function(throwOnChange) {
        var l_context = this.context,l_name0,c_name0,l_interpolate1,l_literal2,c_literal2,l_arrayFn13,l_visibleHref4,l_isRouteActive5,l_literal6,c_literal6,l_arrayFn17,l_visibleHref8,l_isRouteActive9,l_url10;c_name0=c_literal2=c_literal6 = false;
        var isChanged = false;
        var changes = null;

        
        this.propertyBindingIndex = 0;
        
      l_name0 = l_context.name;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.name0, l_name0)) {
        c_name0 = true
        
        
        this.name0 = l_name0;
      }
    
        
        
      

        
        if (c_name0) { 
      l_interpolate1 = "Hello " + ChangeDetectionUtil.s(l_name0) + "";
    
      if (ChangeDetectionUtil.looseNotIdentical(this.interpolate1, l_interpolate1)) {
        
        
        
        this.notifyDispatcher(l_interpolate1);
        
      
        
        this.interpolate1 = l_interpolate1;
      }
     }
        
      changes = null;
      
      isChanged = false;
    
        
      

        this.propertyBindingIndex = 1;
        
      l_literal2 = "Index";
    
      if (ChangeDetectionUtil.looseNotIdentical(this.literal2, l_literal2)) {
        c_literal2 = true
        
        
        this.literal2 = l_literal2;
      }
    
        
        
      

        
        if (c_literal2) { 
      l_arrayFn13 = ChangeDetectionUtil.arrayFn1(l_literal2);
    
      if (ChangeDetectionUtil.looseNotIdentical(this.arrayFn13, l_arrayFn13)) {
        
        
        
        this.directive_1_0.routeParams = l_arrayFn13;
        
        isChanged = true;
      
        
        this.arrayFn13 = l_arrayFn13;
      }
     }
        
      changes = null;
      
      isChanged = false;
    
        
      

        this.propertyBindingIndex = 2;
        
      l_visibleHref4 = this.directive_1_0.visibleHref;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.visibleHref4, l_visibleHref4)) {
        
        
        
        this.notifyDispatcher(l_visibleHref4);
        
      
        
        this.visibleHref4 = l_visibleHref4;
      }
    
        
        
      

        this.propertyBindingIndex = 3;
        
      l_isRouteActive5 = this.directive_1_0.isRouteActive;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.isRouteActive5, l_isRouteActive5)) {
        
        
        
        this.notifyDispatcher(l_isRouteActive5);
        
      
        
        this.isRouteActive5 = l_isRouteActive5;
      }
    
        
      changes = null;
      
      isChanged = false;
    
        
      

        this.propertyBindingIndex = 4;
        
      l_literal6 = "Home";
    
      if (ChangeDetectionUtil.looseNotIdentical(this.literal6, l_literal6)) {
        c_literal6 = true
        
        
        this.literal6 = l_literal6;
      }
    
        
        
      

        
        if (c_literal6) { 
      l_arrayFn17 = ChangeDetectionUtil.arrayFn1(l_literal6);
    
      if (ChangeDetectionUtil.looseNotIdentical(this.arrayFn17, l_arrayFn17)) {
        
        
        
        this.directive_2_0.routeParams = l_arrayFn17;
        
        isChanged = true;
      
        
        this.arrayFn17 = l_arrayFn17;
      }
     }
        
      changes = null;
      
      isChanged = false;
    
        
      

        this.propertyBindingIndex = 5;
        
      l_visibleHref8 = this.directive_2_0.visibleHref;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.visibleHref8, l_visibleHref8)) {
        
        
        
        this.notifyDispatcher(l_visibleHref8);
        
      
        
        this.visibleHref8 = l_visibleHref8;
      }
    
        
        
      

        this.propertyBindingIndex = 6;
        
      l_isRouteActive9 = this.directive_2_0.isRouteActive;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.isRouteActive9, l_isRouteActive9)) {
        
        
        
        this.notifyDispatcher(l_isRouteActive9);
        
      
        
        this.isRouteActive9 = l_isRouteActive9;
      }
    
        
        
      

        this.propertyBindingIndex = 7;
        
      l_url10 = l_context.url;
    
      if (ChangeDetectionUtil.looseNotIdentical(this.url10, l_url10)) {
        
        
        
        this.notifyDispatcher(l_url10);
        
      
        
        this.url10 = l_url10;
      }
    
        
      changes = null;
      
      isChanged = false;
    
        
      
      }

      
        ChangeDetector_App_0.prototype.handleEventInternal = function(eventName, elIndex, locals) {
          var preventDefault = false;
          var l_context = this.context,l_onClick0_0,l_onClick0_1;
          
    if (eventName === "click" && elIndex === 1) {
      l_onClick0_0 = this.directive_1_0.onClick();

if (l_onClick0_0 === false) { preventDefault = true};
    }

    if (eventName === "click" && elIndex === 2) {
      l_onClick0_1 = this.directive_2_0.onClick();

if (l_onClick0_1 === false) { preventDefault = true};
    }
          return preventDefault;
        }
      

      

      

      ChangeDetector_App_0.prototype.hydrateDirectives = function(directives) {
      this.directive_0_0 = this.getDirectiveFor(directives, 0);
this.directive_1_0 = this.getDirectiveFor(directives, 1);
this.directive_2_0 = this.getDirectiveFor(directives, 2);
this.directive_3_0 = this.getDirectiveFor(directives, 3);
      
    }

      ChangeDetector_App_0.prototype.dehydrateDirectives = function(destroyPipes) {
        if (destroyPipes) {
          
          
        }
        this.name0 = this.interpolate1 = this.literal2 = this.arrayFn13 = this.visibleHref4 = this.isRouteActive5 = this.literal6 = this.arrayFn17 = this.visibleHref8 = this.isRouteActive9 = this.url10 = this.directive_0_0 = this.directive_1_0 = this.directive_2_0 = this.directive_3_0 = ChangeDetectionUtil.uninitialized;
    }

      ChangeDetector_App_0.gen_propertyBindingTargets = [ChangeDetectionUtil.bindingTarget("textNode", 6, null, null, null), ChangeDetectionUtil.bindingTarget("directive", 1, "routeParams", null, null), ChangeDetectionUtil.bindingTarget("elementAttribute", 1, "href", null, null), ChangeDetectionUtil.bindingTarget("elementClass", 1, "router-link-active", null, null), ChangeDetectionUtil.bindingTarget("directive", 2, "routeParams", null, null), ChangeDetectionUtil.bindingTarget("elementAttribute", 2, "href", null, null), ChangeDetectionUtil.bindingTarget("elementClass", 2, "router-link-active", null, null), ChangeDetectionUtil.bindingTarget("elementProperty", 4, "href", null, null)];

      ChangeDetector_App_0.gen_directiveIndices = [ChangeDetectionUtil.directiveIndex(0, 0), ChangeDetectionUtil.directiveIndex(1, 0), ChangeDetectionUtil.directiveIndex(2, 0), ChangeDetectionUtil.directiveIndex(3, 0)];
    
var appProtoEl0_App = AppProtoElement.create(
        resolvedMetadataCache,
        0,
        {'router-active':''},
        [RouterActive],
        {}
      );
var appProtoEl1_App = AppProtoElement.create(
        resolvedMetadataCache,
        1,
        {},
        [RouterLink],
        {}
      );
var appProtoEl2_App = AppProtoElement.create(
        resolvedMetadataCache,
        2,
        {},
        [RouterLink],
        {}
      );
var appProtoEl3_App = AppProtoElement.create(
        resolvedMetadataCache,
        3,
        {},
        [RouterOutlet],
        {}
      );
var appProtoEl4_App = AppProtoElement.create(
        resolvedMetadataCache,
        4,
        {},
        [],
        {}
      );
var appProtoView5_App0 = AppProtoView.create(resolvedMetadataCache, 1, [], {});
var renderType32_App = null;
var styles33_App = styles;

function viewFactory_App0(parentRenderer,viewManager,containerEl,projectableNodes,rootSelector,dynamicallyCreatedProviders,rootInjector){
  if (renderType32_App == null) {
        renderType32_App = viewManager.createRenderComponentType(0, styles33_App);
      }
  var renderer = parentRenderer.renderComponent(renderType32_App);
  var view = new AppView(
    appProtoView5_App0, renderer, viewManager,
    projectableNodes,
    containerEl,
    dynamicallyCreatedProviders, rootInjector,
    function() { return new ChangeDetector_App_0(); }()
  );
  checkSlotCount('App', 0, projectableNodes);
  var parentRenderNode = renderer.createViewRoot(view.containerAppElement.nativeElement);
  var render0_App = renderer.createText(parentRenderNode, '\n    ');
var render1_App = renderer.createElement(parentRenderNode, 'header');
var render2_App = renderer.createText(render1_App, '\n      ');
var render3_App = renderer.createElement(render1_App, 'nav');
renderer.setElementAttribute(render3_App, 'router-active', '');
var render5_App = renderer.createText(render3_App, '\n        ');
var render6_App = renderer.createElement(render3_App, 'h1');
var render7_App = renderer.createText(render6_App, '');
var render8_App = renderer.createText(render3_App, '\n        ');
var render9_App = renderer.createElement(render3_App, 'a');
renderer.listen(render9_App, 'click', function (event) { return view.triggerEventHandlers('click', event, 1); });
var render11_App = renderer.createText(render9_App, 'Index');
var render12_App = renderer.createText(render3_App, '\n        ');
var render13_App = renderer.createElement(render3_App, 'a');
renderer.listen(render13_App, 'click', function (event) { return view.triggerEventHandlers('click', event, 2); });
var render15_App = renderer.createText(render13_App, 'Home');
var render16_App = renderer.createText(render3_App, '\n      ');
var render17_App = renderer.createText(render1_App, '\n    ');
var render18_App = renderer.createText(parentRenderNode, '\n\n    ');
var render19_App = renderer.createElement(parentRenderNode, 'main');
var render20_App = renderer.createText(render19_App, '\n      ');
var render21_App = renderer.createElement(render19_App, 'router-outlet');
var render23_App = renderer.createText(render19_App, '\n    ');
var render24_App = renderer.createText(parentRenderNode, '\n\n    ');
var render25_App = renderer.createElement(parentRenderNode, 'footer');
var render26_App = renderer.createText(render25_App, '\n      WebPack Angular 2 Starter by ');
var render27_App = renderer.createElement(render25_App, 'a');
var render29_App = renderer.createText(render27_App, '@AngularClass');
var render30_App = renderer.createText(render25_App, '\n    ');
var render31_App = renderer.createText(parentRenderNode, '\n  ');
  var app4_App = new AppElement(appProtoEl0_App, view,
      null, render3_App, null);
var app10_App = new AppElement(appProtoEl1_App, view,
      app4_App, render9_App, null);
var app14_App = new AppElement(appProtoEl2_App, view,
      app4_App, render13_App, null);
var app22_App = new AppElement(appProtoEl3_App, view,
      null, render21_App, null);
var app28_App = new AppElement(appProtoEl4_App, view,
      null, render27_App, null);

  view.init(([]), [render0_App,render1_App,render2_App,render3_App,render5_App,render6_App,render7_App,render8_App,render9_App,render11_App,render12_App,render13_App,render15_App,render16_App,render17_App,render18_App,render19_App,render20_App,render21_App,render23_App,render24_App,render25_App,render26_App,render27_App,render29_App,render30_App,render31_App], [],
            [app4_App,app10_App,app14_App,app22_App,app28_App]);
  return view;
}
return viewFactory_App0
})
```
for this template
```html
    <header>
      <nav router-active>
        <h1>Hello {{ name }}</h1>
        <a [routerLink]=" ['Index'] ">Index</a>
        <a [routerLink]=" ['Home'] ">Home</a>
      </nav>
    </header>

    <main>
      <router-outlet></router-outlet>
    </main>

    <footer>
      WebPack Angular 2 Starter by <a [href]="url">@AngularClass</a>
    </footer>
```
cc @tbosch

**Comment by kylecordes** [comment] 2016-01-14 17:26
The typical answer to this problem is to make code generation mangle names in some way so that they don't conflict with any pre-existing internal names. (I have not looked at the specific code generation going on here.)

**Comment by zoechi** [comment] 2016-01-14 18:09
Or at least start the names with `Ng`. Such names were always considered to be from Angular itself.

**Comment by pkozlowski-opensource** [comment] 2016-08-06 09:37
Seems to be fixed in RC.4: https://plnkr.co/edit/auuLWZJFydnVCA4AqQz7?p=preview

**Closed by pkozlowski-opensource** 2016-08-06 09:37 UTC
