### ISSUE TITLE
CanMatch snapshot queryParams doesn't work

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#47417] opened 2022-09-13 06:07 UTC
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I want a sync access to `router.snapshot.queryParams` in `CanMatch` guard and it doesn't work:

```ts
{
          path: 'todos',
          canMatch: [() => {
            // the location is todos?foo=1
            console.log(inject(ActivatedRoute).snapshot.queryParams) // { }
            return true;
          }],
}
```

If I wrap it with a `setTimeout` it logs the correct value.

**Comment by JoostK** [comment] 2022-09-13 09:59
It seems illogical to me that `ActivatedRoute` would represent the route that is still being matched; it has _not_ yet been activated so `ActivatedRoute` does not reflect the navigation that is being matched. The `CanMatch` functions are called with `segments: UrlSegment[]`, is that what you're looking for?

**Comment by ArielGueta** [comment] 2022-09-16 07:25
I understand what you're saying, but I expect at least to get access to the "current" activated route.

**Comment by atscott** [comment] 2022-09-19 15:01
The current activated route is the current activated route. This is as @JoostK has described. Closing as working as intended.

FYI - you can get what you're looking for with `inject(Router).getCurrentNavigation().initialUrl.queryParams`

https://stackblitz.com/edit/angular-ivy-sgtr4a?file=src%2Fmain.ts,src%2Findex.html

**Closed by atscott** 2022-09-19 15:01 UTC
Labels: comp: router

**Comment by ArielGueta** [comment] 2022-09-20 15:30
@atscott thanks! Can you please explain why it called twice, please?

**Comment by atscott** [comment] 2022-09-20 16:17
@ArielGueta Yes. It's called twice because there are two stages at the beginning of the routing pipeline that need to call it. One which determines the final URL for the navigation (applyRedirects) and one that creates the `ActivatedRouteSnapshot`s for the navigation (recognize). Both of these match the URL to the `Route` configs. I'm working on combining these two operations, but it's quite a long process that includes several breaking changes and is being done over the course of several major versions.

**Comment by ArielGueta** [comment] 2022-09-23 06:49
Thanks!
