### ISSUE TITLE
ChangeDetector and NgForm false valid on template using OnPush and NgModel

### ISSUE THREAD

**Issue by vinagreti** [angular/angular#36640] opened 2020-04-15 16:23 UTC
# 🐞 bug report

### Affected Package

 FormsModule

### Is this a regression?

 no

### Description
When using `OnPuh` startegy, `NgForms` initially shows a false postive on the `Template` `valid status` even if the form is invalid (like when it has a required input).
If we subscribe to `statusChange` on the model we get the invalid state within the stream, but still not in the view.

I've opened this issue because I think `NgModel` should act like `@Input` and trigger change detection automatically when it has changes.
The change detection is triggered when the user interacts with the form through the `DOM` or the `NgModel` changes the value, but the ChangeDetector is failing to detect the initial state on the Template using `OnPush`.

## 🔬 Minimal Reproduction

 
https://stackblitz.com/edit/angular-jvwfw3

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.1
Node: 10.16.2
OS: linux x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

![image](https://user-images.githubusercontent.com/1353905/79354767-3778ef00-7f13-11ea-819f-fb88d0ea3f8c.png)

**Comment by souhailharrati** [comment] 2020-04-18 15:15
Hi @vinagreti 
A quick fix to fix the problem is
you can use the ChangeDetectorRef service to detect the change:

```
   constructor (private ref: ChangeDetectorRef) {}

  ngOnInit() {
    this.myForm.statusChanges.subscribe((status) =>{
      if (!(<ViewRef>this.ref).destroyed) {
        console.log('OnPush STATUS CHANGED', status);
        this.ref.detectChanges();
      }
    })

    this.myForm.valueChanges.subscribe((value) => console.log('OnPush VALUE CHANGED', value))
  }

 ngOnDestroy() {
    this.ref.detach();
  }
```

see this link: https://stackblitz.com/edit/angular-3jq39s

**Comment by vinagreti** [comment] 2020-04-22 02:28
@souhailharrati, thank you for your workaround!

Even having ways of working around this issue, it is still an issue. 
The state of both components are the same at the same time, but `OnPush` doesn't reflects the state as it should do.

My workaround was enabling `Default` mode on that specific component and wait for this issue to be solved.

**Comment by souhailharrati** [comment] 2020-04-22 21:44
@vinagreti Thank you I agree with you

**Comment by JeanMeche** [comment] 2022-11-09 12:07
@AndrewKushnir This bug is no reproducible anymore on 14. 

Demo :https://stackblitz.com/edit/angular-me9l9y?file=src%2Fapp%2Fapp.component.ts 

This can be closed.

**Comment by AndrewKushnir** [comment] 2022-11-09 16:51
@JeanMeche thanks for checking! I'm closing this ticket for now, please create a new one if the problem still exists.

**Closed by AndrewKushnir** 2022-11-09 16:51 UTC
Labels: type: bug/fix, area: forms, state: confirmed, P3
