### ISSUE TITLE
angular/elements: document-register-element fails with latest versions

### ISSUE THREAD

**Issue by ghost** [angular/angular#31995] opened 2019-08-04 16:22 UTC
# 🐞 bug report

### Affected Package
This issue is caused by package `@angular/elements`, specifically the document-register-element dependency.

### Is this a regression?
Yes, it worked for a previous version of the document-register-element dependency of `@angular/elements`.

### Description
When using the polyfill for Angular elements, I receive this error "Failed to construct 'HTMLElement': Please use the 'new' operator" (previously reported [here](https://github.com/angular/angular/issues/24556))

## 🔬 Minimal Reproduction

Added polyfill for document-register-element by using `ng add @angular/elements --project=$PROJECT_NAME`, which [adds a minimum version of 1.7.2 to package.json](https://github.com/angular/angular/blob/master/packages/elements/schematics/ng-add/index.ts#L34).

Changed TypeScript compiler target from ES2015 to ES5 to support older browsers and make use of the polyfill.

To test this I changed the package version to the exact version, ran `npm install`, and then ran `ng serve --prod` to see if the error showed up again.

The [document-register-element package versions](https://github.com/WebReflection/document-register-element/releases) tried:

| version | worked? |
|---------|---------|
| 1.14.1 | no |
| 1.14.0 | no |
| ... | (assuming no versions between worked) |
| 1.10.1 | no |
| 1.10.0 | no |
| 1.9.2 | no |
| 1.9.1 | no |
| 1.9.0 | no |
| 1.8.1 | yes |
| 1.8.0 | yes |
| 1.7.2 | yes |

## 🔥 Exception or Error
<pre><code>
"Failed to construct 'HTMLElement': Please use the 'new' operator"
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: linux x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0
@angular-devkit/build-angular     0.802.0
@angular-devkit/build-optimizer   0.802.0
@angular-devkit/build-webpack     0.802.0
@angular-devkit/core              8.2.0
@angular-devkit/schematics        8.2.0
@ngtools/webpack                  8.2.0
@schematics/angular               8.2.0
@schematics/update                0.802.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

The issue has been reported on document-register-element as well: https://github.com/WebReflection/document-register-element/issues/174

## Temporary Fix
The temporary fix is to change the versions required in package.json after adding the `angular/elements` package:

```json
"dependencies": {
    "document-register-element": ">=1.7.2 <=1.8.1"
}
```

A more permanent fix is to wait for document-register-element to patch their code, or to stick to the version range that works and revisit later in the future.

**Comment by rudolfolah** [comment] 2019-08-08 13:37
Looks like there isn't a fix on the document-register-elements side: https://github.com/WebReflection/document-register-element/issues/174#issuecomment-519490812

Not sure how to implement a fix for this aside from using the temporary fix.

**Comment by gkalpak** [comment] 2020-10-23 13:50
Closing as a duplicate of #24390.

**Closed by gkalpak** 2020-10-23 13:50 UTC
Labels: comp: elements
