### ISSUE TITLE
NGCC silently ignores some components

### ISSUE THREAD

**Issue by devoto13** [angular/angular#32895] opened 2019-09-28 20:02 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package `@angular/compiler-cli` and maybe `@angular/compiler`.

### Is this a regression?

Not sure, probably not a regression.

### Description

NGCC silently ignores some components, i.e. does not update the `.d.ts` files in the library, which results in completely misleading errors about missing components down the road, when Angular application attempts to use library compiled with NGCC. I've faced these errors, when attempting to upgrade [angular-fontawesome](https://github.com/devoto13/angular-fontawesome/tree/angular-9) (see last commit in the branch) to Angular 9.

NGCC should either compile ALL components or fail or at the very least print a warning that it was unable to compile certain components from the library for certain reason. This way library authors can either avoid using undesired behaviours or report clear issues here.

Two cases where `ngcc` silently skips components, which I've identified so far are:
- injecting `Renderer2` into a component
- injecting a directive into a component

## 🔬 Minimal Reproduction

https://github.com/devoto13/ngcc-skip-components-repro

Repository is created using schematics (each command is one commit):

```
$ ng new eval-lib
$ ng g lib test
# import component from the library into application
# inject `Renderer2` into library component (this leads to an error)
```

How to reproduce a bug:

```
# clone repo
$ npm i
$ ng build test --prod # build the library
$ ng build --prod # attempt to build the application using this library
```

Observe a misleading error about missing component. Observe that `dist/test/lib/test.component.d.ts` was not processed by NGCC and no clear error or warning was printed. Reverting latest commit in the repo will allow the application build to pass and application will run successfully.

## 🔥 Exception or Error
<pre><code>ERROR in src/app/app.component.html:1:1 - error TS8001: 'lib-test' is not a valid HTML element.

1 <lib-test></lib-test>
  ~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.0-next.6
Node: 12.7.0
OS: darwin x64
Angular: 9.0.0-next.8
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.6
@angular-devkit/build-angular      0.900.0-next.6
@angular-devkit/build-ng-packagr   0.900.0-next.6
@angular-devkit/build-optimizer    0.900.0-next.6
@angular-devkit/build-webpack      0.900.0-next.6
@angular-devkit/core               9.0.0-next.6
@angular-devkit/schematics         9.0.0-next.6
@angular/cli                       9.0.0-next.6
@ngtools/webpack                   9.0.0-next.6
@schematics/angular                9.0.0-next.6
@schematics/update                 0.900.0-next.6
ng-packagr                         5.5.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.41.0
</code></pre>

**Anything else relevant?**

**Comment by Splaktar** [comment] 2019-09-29 10:02
This looks similar to what we're seeing in Angular Material: https://github.com/angular/components/issues/17121

None of the `mat-tab-group` Inputs show up in the `ngComponentDef` generated from `ngcc`:

```ts
static ngComponentDef: ɵngcc0.ɵɵComponentDefWithMeta<MatTabGroup, "mat-tab-group", ["matTabGroup"], { 'color': "color", 'disableRipple': "disableRipple" }, {}, ["_tabs"]>;
```

So it looks `ngcc` is just ignoring a bunch of `@Input`s, especially when they are associated with `get/set` methods.
https://github.com/angular/components/blob/492fdcc40b3cfcadd825c29ba9f505c6e5794a50/src/material/tabs/tab-group.ts#L99-L137

**Comment by JoostK** [comment] 2019-09-30 07:13
I suspect this is primarily caused by the usage of ng-packagr 5.5.1, which generates bundles that ngcc has trouble with processing correctly. More info and a fix can be found in https://github.com/angular/angular/pull/32901.

In general, it is quite challenging for ngcc to detect when it fails to compile stuff that it should, as it typically doesn't even know that something was supposed to be compiled in the first place (otherwise it would have done so).

**Comment by JoostK** [comment] 2019-10-04 08:12
@devoto13 With the `9.0.0-next.9` release the bug you were seeing should have been resolved.

The cases you identified (injecting `Renderer` or a directive into a component) were indeed due to the way ng-packagr was updated to emit constructor parameters. Before #32901 this was a problem for ngcc, as it would fail to detect the class level decorator and therefore skip compilation of the component in full.

The problem with ngcc silently skipping stuff to compile remains, due to the challenge of detecting this situation I mentioned earlier. I don't really see how we can do anything about that, so I'll go ahead and close this issue.

Thanks for testing Ivy and if you encounter any more issues, please open a new issue!

**Closed by JoostK** 2019-10-04 08:12 UTC
Labels: comp: ngcc
