### ISSUE TITLE
Router does not support web components lifecycle

### ISSUE THREAD

**Issue by jpzwarte** [angular/angular#44443] opened 2021-12-11 12:55 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

elements, router

### Description

When using `@angular/elements` in combination with `@angular/router`, there is a problem with the router: when the custom elements is removed/destroyed (`disconnectedCallback()` or `ngOnDestroy()`), the `Router` instance remains active and is still listening for route changes.

You *could* call `this.router.dispose()` in the `ngOnDestroy()` of the `AppComponent`, but then the router is no longer usable when the `AppComponent` custom element is created again.

### Proposed solution

I would propose a `reset()` method on the router that changes the internal state of the router back to when it was first created. So the same state as just before you call `this.router.initialNavigation()`.

### Alternatives considered

This hack seems to work:

```typescript
ngOnInit(): void {
    const router = this.router as any;
    router.navigated = false;
    router.navigationId = 0;
    router.lastSuccessfulId = -1;

    this.router.initialNavigation();
  }

  ngOnDestroy(): void {
    const router = this.router as any;
    if (router.locationSubscription) {
      router.locationSubscription.unsubscribe();
      router.locationSubscription = undefined;
    }
  }

```

**Comment by atscott** [comment] 2021-12-16 19:20
Closing as duplicate of #36711

**Closed by atscott** 2021-12-16 19:20 UTC
Labels: comp: router, comp: elements
