### ISSUE TITLE
Angular 15 > Build Production > SyntaxError: Unexpected token: punc (() > Package @fortawesome

### ISSUE THREAD

**Issue by kwhjvdkamp** [angular/angular#48711] opened 2023-01-12 09:37 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other  (I expect @fortawesome)

### Is this a regression?

No

### Description

Performing 'production' build after upgrading to Angular 15.1.0 (from Angular 15.0.4):
> Optimization error [main.10d1eaf66434068a.js]: SyntaxError: Unexpected token: punc (()

Investigation through command
$ ng build MY-PROJECT-NAME --configuration=production --aot --named-chunks --verbose --build-optimizer=false --source-map
OUTPUT: 
Warning: [DedupeModuleResolvePlugin]: C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css -> C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css?ngGlobalStyle

### Please provide the exception or error you saw

```true
[webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: ResolverCachePlugin|normal|default|dependencyType=|esm|path=|C:\GitHubRepositories\MY-PROJECT-NAME\frontend|request=|C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular\material\prebuilt-themes\indigo-pink.css?ngGlobalStyle

WARNING in [DedupeModuleResolvePlugin]: C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css -> C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css?ngGlobalStyle

Error: [DedupeModuleResolvePlugin]: C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css -> C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@fortawesome\fontawesome-free\css\all.min.css?ngGlobalStyle
    at addWarning (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-diagnostics.js:12:31)
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular-devkit\build-angular\src\webpack\plugins\dedupe-module-resolve-plugin.js:65:58
    at Hook.eval [as callAsync] (eval at create (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:16)      
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:284:30
    at eval (eval at create (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:591:7
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:116:11
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:623:8
    at NormalModuleFactory.resolveRequestArray (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:988:34)
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:615:11
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:116:11
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:678:9
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\webpack\lib\NormalModuleFactory.js:859:5
    at finishResolved (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\enhanced-resolve\lib\Resolver.js:294:11)
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\enhanced-resolve\lib\Resolver.js:362:25
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\enhanced-resolve\lib\Resolver.js:434:24

ERROR in Optimization error [main.10d1eaf66434068a.js]: SyntaxError: Unexpected token: punc (()
    at js_error (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:554:11)
    at croak (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1278:9)
    at token_error (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1286:9)
    at unexpected (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1292:9)
    at function_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1728:17)
    at statement (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1477:24)
    at _embed_tokens_wrapper (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1343:26)
    at block_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:2182:20)
    at try_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:2222:20)
    at statement (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1517:24)

Error: Optimization error [main.10d1eaf66434068a.js]: SyntaxError: Unexpected token: punc (()
    at js_error (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:554:11)
    at croak (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1278:9)
    at token_error (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1286:9)
    at unexpected (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1292:9)
    at function_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1728:17)
    at statement (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1477:24)
    at _embed_tokens_wrapper (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1343:26)
    at block_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:2182:20)
    at try_ (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:2222:20)
    at statement (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\terser\dist\bundle.min.js:1517:24)
    at addError (C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular-devkit\build-angular\src\utils\webpack-diagnostics.js:16:29)
    at C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular-devkit\build-angular\src\webpack\plugins\javascript-optimizer-plugin.js:152:64
    at async Promise.all (index 3)
    at async C:\GitHubRepositories\MY-PROJECT-NAME\frontend\node_modules\@angular-devkit\build-angular\src\webpack\plugins\javascript-optimizer-plugin.js:155:21
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.0
Node: 18.12.1
Package Manager: npm 9.1.3
OS: win32 x64

Angular: 15.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/fire                   7.5.0
@schematics/angular             15.1.0
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by anisabboud** [comment] 2023-01-12 10:12
Related: https://github.com/angular/angular-cli/issues/24526 
Fix: https://github.com/angular/angular-cli/pull/24531

**Comment by pkozlowski-opensource** [comment] 2023-01-12 10:21
Thnx @anisabboud  - this is indeed duplicate of https://github.com/angular/angular-cli/issues/24526. Closing it here, please follow updates in the CLI repo.

**Closed by pkozlowski-opensource** 2023-01-12 10:21 UTC
