### ISSUE TITLE
AngularFireMessaging is not compatible with the Angular Service Worker

### ISSUE THREAD

**Issue by ConsultDarryl** [angular/angular#34352] opened 2019-12-11 15:29 UTC
# 🚀 feature request

This feature request is for @angular/pwa

### Description
If you are using the Angular Service Worker, you are not currently able to use AngularFireMessaging. If you'd like this feature please file an issue in either repository. Your alternatives are to use WorkboxJS or just simply use the Firebase Messaging Service Worker, which is detailed below.

### Describe alternatives you've considered
I am following these instructions but would prefer to have one SW to rule them all.
https://angularfirebase.com/snippets/how-to-use-a-firebase-fcm-service-worker-with-angular-s-ngsw-service-worker/

**Comment by spock123** [comment] 2019-12-12 09:37
Yeah I'm in the same situation, wanting to use Firebase (AnguilarFire) for messaging, finding it doesn't play well with the Angular Service Worker..

**Comment by AlexGoranov** [comment] 2019-12-13 13:46
Same issue.

**Comment by hcassar93** [comment] 2019-12-25 11:19
Same issue.

**Comment by davidzwa** [comment] 2019-12-31 11:55
In the same situation. Currently having to add my own .js to overrule the Angular SW, which is very against my principles (100% .TS)

**Comment by N-Andronopoulos** [comment] 2020-01-15 08:03
Related to #26413

**Comment by johanchouquet** [comment] 2020-04-17 13:42
Hi there,

What's the status of this issue please ?

Thanks a lot!

**Comment by floogulinc** [comment] 2020-05-05 18:23
Now that the Angular service worker has [its own support for push notifications](https://angular.io/api/service-worker/SwPush) will that allow for using FCM with it?

**Comment by dhrn** [comment] 2020-05-11 18:59
+1

**Comment by davidzwa** [comment] 2020-05-13 12:03
I found this recent blog https://blog.angular-university.io/angular-push-notifications/
with this github repo (note the branch) https://github.com/angular-university/angular-pwa-course/tree/1-notifications-finished.

I'd keep your implementation as FCM-less as possible: use a VAPID key and let SwPush figure out the rest:
> https://github.com/angular-university/angular-pwa-course/blob/1-notifications-finished/src/app/lessons/lessons.component.ts

I for one will be removing my firebase installs + sw override, because it is a great pain so far in Angular.

**Comment by obermoserkitz** [comment] 2020-06-26 09:21
Please add this feature

**Comment by razfriman** [comment] 2020-07-16 21:32
Would love this as well

**Comment by doczoidberg** [comment] 2020-07-17 20:26
I need this too

**Comment by RafaelKr** [comment] 2020-08-20 19:50
I like to kindly request feedback from the Angular team. Is there something the community could do to speed up the process?

**Comment by rnagarajan96** [comment] 2020-08-28 07:35
Following this will work for me. want to know this method is correct or not?
Link:
https://meumobi.github.io/ionic/firebase/2020/01/20/firebase-web-push-ionic.html

**Comment by GabrielGil** [comment] 2020-09-22 14:58
Hmm, that last tutorial didn't quite work in our case. 

I would like to show my support for this feature to be fully integrated with `@angular/pwa`.

**Comment by fcolasante** [comment] 2020-10-16 10:26
@GabrielGil Can you share your knowledge?

**Comment by mparpaillon** [comment] 2020-10-23 09:00
I managed to use NgSw and Firebase messaging (not AngularFireMessaging) but since firebase 7.18 a lot has changed

<img width="882" alt="Capture d’écran 2020-10-23 à 10 59 32" src="https://user-images.githubusercontent.com/1062115/96978615-d748b280-151e-11eb-809a-9d24007c1ad3.png">

If I manage to make it work I'll share it here.

**Comment by mparpaillon** [comment] 2020-10-28 18:16
OK I managed to make it work pretty well
- Grant permission + store token
- Revoke permission
- Background notifications
- Foreground notifications (show a toast/snack)
- Click to redirect (without reloading if a tab is already on the app, so no "navigateTo")
- Reset notifications if I go to a certain page without clicking the push notification itself
- Mute system (but that's specific since my app is a chat application)
- And PWA caching and update system still works (via ngsw)

I wanted to write an article about the process but I have a lot to do so here's a summary

I'm using Firebase messaging (but not AngularFireMessaging) to handle background and foreground notifications
I'm using NGSW for the caching and update system for the PWA

```json
{
  "firebase": "^7.24.0",
  "@angular/service-worker": "^10.2.0"
}
```

`app.module.ts`
```ts
import { NgModule } from '@angular/core';
import { ServiceWorkerModule } from '@angular/service-worker';
// ...
import { env } from '~env/environment';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    // ...
    ServiceWorkerModule.register('service-worker.js', {
      enabled: env.production,
      registrationStrategy: 'registerImmediately'
    }),
  ],
  bootstrap: [
    AppComponent
  ],
  providers: [
  ]
})
export class AppModule {}
```

Here I'm not sure about the `registerImmediately` and it's not required for this to work so make sure to choose the config you need.
Also that's where you register your (one and only) service worker. I've named mine `service-worker.js` and you can't name it `ngsw-worker.js`, you'll see why in a minute.

`app.component.ts`
```ts
import { Component, ChangeDetectorRef } from '@angular/core';
import { SwUpdate } from '@angular/service-worker';
import { PushProvider } from '~core/providers/push';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  updateAvailable = false;
  
  constructor(
    private cd: ChangeDetectorRef,
    private swUpdate: SwUpdate,
    private pushProvider: PushProvider
  ) {
    this.pushProvider.init();

    if (this.swUpdate.isEnabled) {
      this.swUpdate.available.subscribe(() => {
        this.updateAvailable = true;
        this.cd.detectChanges();
      });
    }
  }

  reload() {
    location.reload();
  }
}
```

`app.component.html`
```html
<nav class="updateBar" (click)="reload()" *ngIf="updateAvailable">
  Click here to install update
</nav>

<!-- ... ->
```

`providers/push.ts`
```ts
import { Injectable } from '@angular/core';
import { Router } from '@angular/router';
import * as firebase from 'firebase/app';
import 'firebase/messaging';
import { BehaviorSubject, Observable, Subject } from 'rxjs';
import { filter, switchMap } from 'rxjs/operators';
import { ToastProvider } from '~core/modules/toast/toast';
import { UserProvider } from '~core/providers/user';
import { env } from '~env/environment';
import { Payload } from '~shared/models/payload.model';


@Injectable({
  providedIn: 'root'
})
export class PushProvider {
  isBrowserPushCompatible = 'Notification' in window;
  canEnableNotification$: BehaviorSubject<boolean> = new BehaviorSubject(null);
  isPushEnabled$: BehaviorSubject<boolean> = new BehaviorSubject(false);

  constructor(
    private router: Router,
    private userProvider: UserProvider,
    private toastProvider: ToastProvider
  ) {  }

  init() {
    console.log('Init push provider');

    const isPushEnabled = firebase.messaging.isSupported()
      && Notification
      && Notification.permission === 'granted';

    this.isPushEnabled$.next(isPushEnabled);
    console.log('isPushEnabled', isPushEnabled);

    if (!firebase.messaging.isSupported()) return;

    console.log('Firebase messaging is supported');

    // Listening to any postMessage from the sw (only useful to redirect to a given uri)
    navigator.serviceWorker.addEventListener('message', event => {
      console.log('message', event);

      if (!event.data) return;
      if (!event.data.uri) return;
      if (event.data.type !== 'redirect') return;

      console.log('redirect', event.data.uri);
      this.router.navigate(event.data.uri.split('/'));
    });

    this.updateCanEnableNotification();

    this.watchMessage$().subscribe((message: Payload) => {
      const notif = message.notification;
      this.toastProvider.showPost(notif.title, notif.body, notif.icon, notif.data.uri);
    });
  }

  private watchMessage$(): Observable<Payload> {
    return this.isPushEnabled$.pipe(
      filter(isPushEnable => !!isPushEnable),
      switchMap(() => {
        console.log('Listening to Firebase messages');

        const message$: Subject<Payload> = new Subject();
        firebase.messaging().onMessage((res) => {
          console.log('Message from Firebase received');
          console.log(res);

          message$.next(res as Payload);
        });

        return message$.asObservable();
      })
    );
  }

  private updateCanEnableNotification() {
    console.log('Notification.permission', Notification.permission);

    const canEnableNotification = firebase.messaging.isSupported()
      && this.isBrowserPushCompatible
      && Notification.permission === 'default';

    this.canEnableNotification$.next(canEnableNotification);
    console.log('canEnableNotification', canEnableNotification);
  }

  getIsPushEnable$(): Observable<boolean> {
    return this.isPushEnabled$.asObservable();
  }

  getToken(): Promise<string> {
    return navigator.serviceWorker.getRegistration()
    .then(swr => {
      console.log('Service worker getRegistration', swr);

      if (!swr) {
        this.toastProvider.showError('No service worker found...');
        return null;
      }

      console.log('call getToken', env.firebaseConfig.vapidKey);

      // Ask for permission, returns token
      return firebase.messaging().getToken({
        vapidKey: env.firebaseConfig.vapidKey,
        serviceWorkerRegistration: swr
      });
    });
  }

  requestPermission(): Promise<void> {
    if (!firebase.messaging.isSupported()) return;

    return this.getToken().then(token => {
      console.log('getToken response', token);

      if (token) {
        this.toastProvider.showSuccess('You can now receive notifications');
        this.isPushEnabled$.next(true);
        this.updateCanEnableNotification();

        // Store token in database
        return this.userProvider.addToken(token);
      }

      console.log('No token');
    });
  }

  revokePermission(): Promise<void> {
    if (!firebase.messaging.isSupported()) return;

    this.toastProvider.showWaiting('Revoking permission...');

    return this.getToken().then(token => {
      console.log('token to revoke', token);

      return Promise.all([
        token ? this.userProvider.deleteToken(token) : Promise.resolve(),
        firebase.messaging().deleteToken()
      ]);
    })
    .then(() => {
      console.log('Revoked');

      this.isPushEnabled$.next(false);
      this.updateCanEnableNotification();
      this.toastProvider.showSuccess('You won\'t receive notifications here anymore');
    });
  }

  private getAll(tag: string): Promise<Notification[]> {
    const options = tag ? { tag } : {};

    return navigator.serviceWorker.ready
    .then(swr => swr.getNotifications(options));
  }

  reset(tag: string) {
    if (!firebase.messaging.isSupported()) return;

    return this.getAll(tag)
    .then((notifications) => {
      console.log('reset notifications', notifications);
      notifications.forEach(notification => notification.close());
    });
  }
}
```

## Backend
`service-worker.js`
```ts
// We import the service-worker generated by @angular/service-worker to handle all the caching for us
importScripts('ngsw-worker.js');

// Import and configure the Firebase SDK
// These scripts are made available when the app is served or deployed on Firebase Hosting
// If you do not serve/host your project using Firebase Hosting see https://firebase.google.com/docs/web/setup
// Version should match the one in the package.json apparently... Background push may not work if they don't
importScripts('/__/firebase/7.24.0/firebase-app.js');
importScripts('/__/firebase/7.24.0/firebase-messaging.js');
importScripts('/__/firebase/init.js');

// Not called as soon as I'm using SwPush for some reason
self.addEventListener('notificationclick', function(event) {
  console.log('notification click', event);

  const uri = event.notification.data.uri;

  console.log('uri', uri);

  event.notification.close();

  // This looks to see if the current is already open and focuses if it is
  event.waitUntil(clients.matchAll({
    type: "window"
  })
  .then(function(clientList) {
    const url = new URL('/', location).href;
    console.log('url', url)

    for (let client of clientList) {
      if (client.url.startsWith(url)) {
        console.log('focus then navigate');

        return client.focus().then((c) => {
          // Don't want to use navigateTo here because it reloads the PWA and that's poor UX
          c.postMessage({
            type: 'redirect',
            uri: uri
          });
        });
      }
    }

    const destinationUrl = url + '/' + uri;
    console.log('destinationUrl', destinationUrl)

    return clients.openWindow(destinationUrl);
  }));
});

// Should be after addEventListener notificationclick because bug on Firefox
// Source: https://stackoverflow.com/a/54100379/2719044
const messaging = firebase.messaging();
```

## Backend

```ts
```

## Other notes

- Your `service-worker.js` should be (I think) in your angular.json under your project `architect.build.options.assets`
- You may have to handle your old service-worker. To do that check the `safety-worker.js` generated by ngsw when you build. I had to run a postbuild script to create a copy of this file named as my previous sw to make sure it unregistered itself.
- You don't see any `firebase-messaging-sw.js` because you don't need one. When you call getToken you pass the Service worker you want to use so it doesn't need this one.
- Check the reset method in push provider. You can call it to clear the push notification by passing it the same tag you used when you created your notification payload

### Conclusion

I haven't included everything (like the mute system) because it was too specific to my codebase I think.
Hopefully this helps someone, because it was a real pain for me to come up with a working solution.

**Comment by gkalpak** [comment] 2020-10-28 18:32
Thx for sharing this, @mparpaillon ❤️

**Comment by mparpaillon** [comment] 2020-11-06 14:15
I've updated my walkthrough above so it doesn't break Firebase storage upload or callable functions anymore. I also handled users sign out (because they shouldn't receive notifications then) and revoking permission.

**Comment by matteobucci** [comment] 2020-12-21 13:49
> I've updated my walkthrough above so it doesn't break Firebase storage upload or callable functions anymore. I also handled users sign out (because they shouldn't receive notifications then) and revoking permission.

Is this supported also when working on local enviroments? I'm receiving a 404 on ngsw-worker.js but is also possible I'm doing something wrong.

**Comment by Tommertom** [comment] 2021-01-05 08:10
Hi

Got AngularFire to work with angular sw fairly easily using https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98

And the new API `getToken`. Not to forget the amendments to the manifest. But for the rest, peace of cake. In fact, I believe the readme should not say it is impossible. It just uses the default sw.

```

import * as firebase from 'firebase/app';
import 'firebase/messaging';
import { FirebaseApp } from '@angular/fire';

....

  constructor(
    private swUpdate: SwUpdate,
    private platform: Platform,
    private swPush: SwPush,
    private firebase: FirebaseApp,
    private testService: TestDataGeneratorService,
  ) { }

....

 const serviceWorkerRegistration = await navigator.serviceWorker.getRegistration();
    const messaging = this.firebase.messaging();
    console.log('MESSAGING SW', serviceWorkerRegistration);
    messaging.getToken({
      vapidKey:
        'BEYQVzBmAoN4......X0mpSy9sHSinAHyhBT534cwwrkr49A1qqNg-M',
      serviceWorkerRegistration  // this should be the fix for angularfire not working with ngsw
    }
    ).then((currentToken) => {
      console.log('TOKEN', currentToken);

      this.swPush.messages.subscribe(msg => console.log('push message', msg));
      this.swPush.notificationClicks.subscribe(click => console.log('notification click', click));

  ....
```

**Comment by rubenheymans** [comment] 2021-01-05 23:02
Don't we all need FCM in our PWA though? How come this is not working, they are 2 Google products.
How can we help to speed up this process?

**Comment by jaspervanmegroot** [comment] 2021-01-13 13:15
> Hi
> 
> Got AngularFire to work with angular sw fairly easily using https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98. And using the new API `getToken`. Not to forget the amendments to the manifest. But for the rest, peace of cake.
> 
> In fact, I believe the readme should not say it is impossible. It just uses the default firebase sw which you need to overrule.
> 
> Snippets of code:
> 
> ```
> package.json
>   "@angular/fire": "^6.1.4",
>   "firebase": "^7.0 || ^8.0",
>   "@angular/service-worker": "~10.0.0",
>       
>     
> 
> 
> import { FirebaseApp } from '@angular/fire';
> 
> ....
> 
>   constructor(
>     private swUpdate: SwUpdate,
>     private swPush: SwPush,
>     private firebase: FirebaseApp,
>   ) { }
> 
> ....
> 
>     const serviceWorkerRegistration = await navigator.serviceWorker.getRegistration();
>     const messaging = this.firebase.messaging();
>     console.log('MESSAGING SW', serviceWorkerRegistration);
>     messaging.getToken({
>       vapidKey:
>         'BEYQVzBmAoN4......X0mpSy9sHSinAHyhBT534cwwrkr49A1qqNg-M',
>       serviceWorkerRegistration  // this should be the fix for angularfire not working with ngsw
>     }
>     ).then((currentToken) => {
>       console.log('TOKEN', currentToken);
> 
>       this.swPush.messages.subscribe(msg => console.log('push message', msg));
>       this.swPush.notificationClicks.subscribe(click => console.log('notification click', click));
> 
>   ....
> ```

Do you maybe have an example on Github?

**Comment by Tommertom** [comment] 2021-01-13 18:33
> Do you maybe have an example on Github?

Sorry, no full working app example on shareable Github (private project), but if you create a Stackblitz, happy to look at where you getting stuck and add PWA code as intended in earlier post.

**Comment by dalepo** [comment] 2021-02-22 04:43
> Following this blog will work for me (by combining both angularSW and firebaseSW)
> Link:
> https://meumobi.github.io/ionic/firebase/2020/01/20/firebase-web-push-ionic.html

@rnagarajan96 Quoting from that blog:

> Adding Push config to the Web Manifest
> We need to add this arbitrary string to your manifest.webmanifest: "gcm_sender_id": "wont type this". This value is the same for every single apps in the world, it identifies Google FCM as sender of the notifications.

That is NOT true. The gcm_sender_id is the number from your own firebase project. Not sure if trying to malware people but that  is definitely not true and something to be careful.

**Comment by jornetsimon** [comment] 2021-02-23 07:05
To avoid any confusing regarding the deleted comment from yesterday, it is perfectly right to use a common value (e.g. _103953800507_) for _gcm_sender_id_ in the manifest.
[Source : Frank van Puffelen, Engineer at Firebase](https://stackoverflow.com/a/42231139/1444495)

**Comment by rewtelize** [comment] 2021-03-02 16:35
Hello all, can anyone tell me why AngularFireMessaging is not compatible with the Angular Service Worker and what's the impact of having both working simultaneously?

**Comment by Tommertom** [comment] 2021-03-02 17:00
> Hello all, can anyone tell me why AngularFireMessaging is not compatible with the Angular Service Worker and what's the impact of having both working simultaneously?

Reading for the responses before and the renewed README on AngularFire messaging you can see it IS compatible and works flawlessly with the Angular service worker. You just need to configure it to use it.

I cant comment on having two service workers besides each other, but plainly for messaging and e.g. offline support, there is no need to have two.

The AngularFire may do themselves a favour and posting a blog on blog.angular.io saying how cool it all works with the service worker

**Comment by rewtelize** [comment] 2021-03-05 07:20
First of all, thanks for your answer @Tommertom :)

But I'm working with Azure Notification Hub, and in order to create or update an installation/register based on any device, I need to send its device's token as a handle. Using AngularFireMessaging was easy because I could just call requestToken() and I got it. On the other hand, using Push API I got a PushSubscription object, which contains an endpoint, a pair of keys and an expirationTime. 

Is there a way to register a device using a PushSubscription object?

**Comment by Cironic** [comment] 2021-03-12 16:08
> 
> 
> Hi
> 
> Got AngularFire to work with angular sw fairly easily using https://medium.com/kabbage-engineering/angular-pwa-app-notification-using-firebase-cloud-messaging-d1b7bd171b98. And using the new API `getToken`. Not to forget the amendments to the manifest. But for the rest, peace of cake.
> 
> In fact, I believe the readme should not say it is impossible. It just uses the default firebase sw which you need to overrule.
> 
> Snippets of code:
> 
> ```
> package.json
>   "@angular/fire": "^6.1.4",
>   "firebase": "^7.0 || ^8.0",
>   "@angular/service-worker": "~10.0.0",
>       
>     
> 
> 
> import { FirebaseApp } from '@angular/fire';
> 
> ....
> 
>   constructor(
>     private swUpdate: SwUpdate,
>     private swPush: SwPush,
>     private firebase: FirebaseApp,
>   ) { }
> 
> ....
> 
>     const serviceWorkerRegistration = await navigator.serviceWorker.getRegistration();
>     const messaging = this.firebase.messaging();
>     console.log('MESSAGING SW', serviceWorkerRegistration);
>     messaging.getToken({
>       vapidKey:
>         'BEYQVzBmAoN4......X0mpSy9sHSinAHyhBT534cwwrkr49A1qqNg-M',
>       serviceWorkerRegistration  // this should be the fix for angularfire not working with ngsw
>     }
>     ).then((currentToken) => {
>       console.log('TOKEN', currentToken);
> 
>       this.swPush.messages.subscribe(msg => console.log('push message', msg));
>       this.swPush.notificationClicks.subscribe(click => console.log('notification click', click));
> 
>   ....
> ```

I tried building a porject like the one in the article that you posted. I struggle at the following point:
`if (!firebase.apps.length) {
      firebase.initializeApp(environment.firebase);
      navigator.serviceWorker.getRegistration().then(swr=> firebase.messaging().useServiceWorker(swr));
    }`

I saw you edited the constructor at the point quite a lot, but I can't figure out how to get it to work, even with your code snippets.
firebase.messaging().useServiceWorker(swr) in this line as swr is coming undefined inside getRegistration().then(swr).
if you could tell me how to fix the problem I would be really glad...

**Comment by gkalpak** [comment] 2021-03-12 22:39
@Cironic, this might happen because the SW might not have been registered yet (it depends on the [registrationStrategy][1]). You could listener to `controllerchange` events before retrieving the SW registration; something like:

```ts
import {fromEvent, of} from 'rxjs';
import {filter, map, startWith, switchMap, take} from 'rxjs/operators';

// ...
const swRegistration$ = fromEvent(navigator.serviceWorker, 'controllerchange').pipe(
    startWith(null),
    map(() => navigator.serviceWorker.controller),
    filter((c): c is ServiceWorker => !!c),
    // Uncomment the following line if you only need the first value. 
    // take(1),
    switchMap(() => navigator.serviceWorker.getRegistration()),
);

swRegistration$.subscribe(reg => /* Pass `reg` to Firebase messaging. */);
```

[1]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy

**Comment by Cironic** [comment] 2021-03-15 12:12
@gkalpak, I hope you can help me, since I don't really get how to use your code in the example of the medium article.
Since the problem occurs in the constructor.
```
export class AppComponent {
  displayToken: string;
  constructor(updates: SwUpdate, push: SwPush) {
    updates.available.subscribe(_ => updates.activateUpdate().then(() => {
      console.log('reload for update');
      document.location.reload();
    }));
    push.messages.subscribe(msg => console.log('push message', msg));
    push.notificationClicks.subscribe(click => console.log('notification click', click));
    if (!firebase.apps.length) {
      firebase.initializeApp(environment.firebase);
      navigator.serviceWorker.getRegistration().then(swr => firebase.messaging().useServiceWorker(swr));
    }
  }
  ```
  
  And maybe you can answer me another question:
  for Firebase messaging implementation is it correct to register the ngsw-worker as Serviceworker and not the firebase-messaging-sw?
  ```
  ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
  ```
   And I guess here I could use another registrationStrategy so I don't have to use your code?
   
   Sorry for all the questions, but you are my best bet right now to keep progressing on my project.

**Comment by gkalpak** [comment] 2021-03-16 16:14
> for Firebase messaging implementation is it correct to register the ngsw-worker as Serviceworker and not the firebase-messaging-sw?

I'not familiar with Firebase messaging tbh, but that is my understanding from a quick look at the article and the Firebase docs.

> And I guess here I could use another registrationStrategy so I don't have to use your code?

I don't think  any registration strategy would make it safe to not use my code 😛
The SW registration is always an async operation.

**Comment by gkalpak** [comment] 2021-04-07 17:58
AFAICT, the latest version of AnguarFireMessaging (AFM) _is_ compatible with the Angular ServiceWorker (NGSW). The AngularFire team is working on documenting how to configure AFM to work with NGSW. For more details see https://github.com/angular/angularfire/discussions/1923#discussioncomment-576401.

Based on that, I am going to close this issue. If there is anything else that needs to be fixed in the NGSW, please open a new issue.

**Closed by gkalpak** 2021-04-07 17:58 UTC
Labels: comp: service-worker, feature
