### ISSUE TITLE
18.1.0 adding reference tag in .d.ts files that refers to ngtypecheck.d.ts that don't exist

### ISSUE THREAD

**Issue by mchdu35** [angular/angular#56967] opened 2024-07-12 14:00 UTC
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.0.7

### Description

When building a library, le @angular/compiler-cli add tag at the beginning of each file .d.ts 

**Exemple :**
/// <reference path="datatabse.guard.ngtypecheck.d.ts"/>
The files on that path doesn't exists. The compilation produce no error but when using the library to build an application, the compiler produce a lot of errors : 

**Exemple :** 
node_modules/@compagny/mylib/myentrypoint/datatabse.guard.ngtypecheck.d.ts:1:22 - error TS6053: File 'C:/sources/project/node_modules/@compagny/mylib/myentrypoint/datatabse.guard.ngtypecheck.d.ts' not found.
/// <reference path="datatabse.guard.ngtypecheck.d.ts"/>

### Minimal Reproduction

Compile a little library in 18.1 and use it in another application. 

### Exception or Error

```text
node_modules/@compagny/mylib/myentrypoint/datatabse.guard.ngtypecheck.d.ts:1:22 - error TS6053: File 'C:/sources/project/node_modules/@compagny/mylib/myentrypoint/datatabse.guard.ngtypecheck.d.ts' not found.
/// <reference path="datatabse.guard.ngtypecheck.d.ts"/>
```

### Your Environment

```text
Windows 10, git, Angular 18.1 (migration from 16)
```

**Comment by JeanMeche** [comment] 2024-07-12 14:06
Duplicate of #56945

**Closed by JeanMeche** 2024-07-12 14:06 UTC
