### ISSUE TITLE
'cleanup.builder' stuck in infinite loop when build fails

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1847] opened 2015-05-12 20:57 UTC
This happens both locally and on [Travis](https://travis-ci.org/angular/angular/jobs/62268311).

You get something like this:

```
...
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 125 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 134 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 128 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 211 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 121 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 120 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 124 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 125 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 125 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 121 μs
[13:53:13] Starting 'cleanup.builder'...
[13:53:13] Finished 'cleanup.builder' after 129 μs
[13:53:13] Starting 'cleanup.builder'...
...
```

**Comment by vicb** [comment] 2015-05-12 21:36
Duplicate of #1833

**Closed by vicb** 2015-05-12 21:36 UTC
