### ISSUE TITLE
Passing special characters like '+' (plus) from Angular to backend

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [angular/angular#20376] opened 2017-11-12 15:52 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have a web app with angular front end running on Angular 4.3.6 with express.js handling routing at the back end. I am trying to query from angular using

```
getStuff(name: string): Observable<string> {
    return this.http.get<string>('/someroute', {
        params: new HttpParams().set('name', name)
    });
}
```

Now this name variable can contain something like `ABC+XYZ`, a string actually present in the server. This code actually sends this to the backend `/someroute?name=ABC+XYZ`

My express code is set up like

```
router.get('/someroute', (req, res, next) => {
    console.log(req.query.name)
}
```

`console.log()` outputs `ABC XYZ`. Express is converting the `+` as a space.

I tried Url Encoding the name parameter in angular like

`params: new HttpParams().set('name', encodeURIComponent(name))`

But this causes Angular to convert `%2B`(code for `+`) to `%252B`(`%25` is code for `%`).
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-11-12 16:02
Duplicate of #18261

**Comment by SayakMukhopadhyay** [comment] 2017-11-12 16:27
I am currently running 4.3.6. Was this fixed in future versions?

**Comment by trotyl** [comment] 2017-11-13 01:46
Of course not, that's an open issue.

**Comment by jasonaden** [comment] 2017-11-13 21:20
Closing as duplicate

**Closed by jasonaden** 2017-11-13 21:20 UTC

**Comment by adnanelamghari** [comment] 2019-07-02 14:04
you can use the encodeURIComponent() function.

full doc could be found here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
