### ISSUE TITLE
Proposal: Reactive Forms Accessiblity 

### ISSUE THREAD

**Issue by kyubisation** [angular/angular#18114] opened 2017-07-14 06:59 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With reactive forms, the validators are not reflected to the input fields. This is problematic for accessibility.

## Expected behavior
The common validators should reflect their validation to the input field.
E.g. Validators.required => <input required>

## What is the motivation / use case for changing the behavior?
For the project I'm currently working on, we have very strict accessibility rules. It would help, if angular itself could provide the functionality of reflecting the defined validators.
This solves the described issue in #9121

## Proposal
The idea is based around the Reflect Metadata API.
I would appreciate feedback.
If there is a consensus, I will implement this for a pull request.

### Add interpretable metadata to the validators

Use Reflect to add metadata to the validators. The metadata would be similar to the error object returned, when the validation fails.
Validators.compose (and also Validators.composeAsync) would aggregate the metadata of the given validators and define the metadata of the merged validator.

e.g.:
```ts
  /**
   * Validator that requires controls to have a non-empty value.
   */
  @AccessibilityMeta({'required': true})
  static required(control: AbstractControl): ValidationErrors|null {
    return isEmptyInputValue(control.value) ? {'required': true} : null;
  }

...

  /**
   * Validator that requires controls to have a value of a maximum length.
   */
  static maxLength(maxLength: number): ValidatorFn {
    const validator = (control: AbstractControl): ValidationErrors | null => {
      ...
    };
    defineAccessibilityMeta(validator, {'maxlength': maxLength});
    return validator;
  }
  
...

  /**
   * Compose multiple validators into a single function that returns the union
   * of the individual error maps.
   */
  static compose(validators: null): null;
  static compose(validators: (ValidatorFn|null|undefined)[]): ValidatorFn|null;
  static compose(validators: (ValidatorFn|null|undefined)[]|null): ValidatorFn|null {
    ...

    const mergedAccessibilityMeta = aggregateAccessibilityMeta(presentValidators);
    const validator = function(control: AbstractControl) {
      return _mergeErrors(_executeValidators(control, presentValidators));
    };
    defineAccessibilityMeta(validator, mergedAccessibilityMeta);
    return validator;
  }
```

### Create accessibility interpreter service

Implement a service, which maps the metadata to aria and validation attributes and also compares them with a whitelist of allowed attributes, based on input type.

e.g.:
{'required': true} -> required, aria-required
{'maxlength': 15} -> maxlength="15"

input[type=text]
{'required': true, 'min': 3} -> required, aria-required // 'min' has no purpose for text inputs

### Create directive for form control accessibility

Implement a new directive to render the appropriate attributes. This directive resolves the FormControl instance and the accessibility interpreter service.

#### a) Define new selector (formControlAccessibilty) in order to allow an opt-in scenario

e.g.:
```ts
@Directive({
  selector: 'input[formControlAccessibilty],textarea[formControlAccessibilty]',
})
export class FormAccessiblityDirective {
  @Input() type: string;
  
  ...
}
```

#### b) Reuse existing form control selectors

This could be added to its own module (e.g. FormsAccessiblityModule), together with the service, in order to make it opt-in.

e.g.:
```ts
@Directive({
  selector: 'input[formControlName],textarea[formControlName],input[formControl],textarea[formControl]',
})
export class FormAccessiblityDirective {
  @Input() type: string;
  
  ...
}
```

### Open Questions
What happens when the validators are replaced or cleared? One possible solution would be additional EventEmitters for validator and asyncValidator.

**Comment by Toxicable** [comment] 2017-07-14 07:25
I would hold off on this one for now.
Looking at #9119 which will totally change up the Validators API, from my understanding of this new API your Metadata idea wont work anymore wont work.
So perhaps come up with some alternatives that don't rely on Metadata or Decorators and go from there

**Comment by kyubisation** [comment] 2017-07-14 07:51
Looking at #9119 it is correct, that my proposal would not work with that.
However, there hasn't been any activity on that issue for more than half a year. Or are you aware of more information?
From my current understanding, there isn't much of an alternative. The information of what a validator does needs to be embeded in the validator somehow, as this information needs to be known at initialization of the input field and not after first validation.
Feel free to correct me if I misunderstood something.
But I guess I will have to implement this internally then and monkey patch the validators.

**Comment by Toxicable** [comment] 2017-07-14 08:04
@kyubisation I think there are plans for that proposal to go ahead.

cc @kara

**Comment by kyubisation** [comment] 2017-07-14 08:10
I see. Thank you for bringing it to my attention.

**Comment by Toxicable** [comment] 2017-07-14 08:58
@kyubisation from this: https://github.com/angular/angular/issues/17736#issuecomment-311507399 it appears it's in the design phase

**Comment by kara** [comment] 2019-01-23 00:08
This looks like a dupe of https://github.com/angular/angular/issues/9121, so let's continue the discussion there.

@kyubisation To answer your question, this does need design, but this is not currently prioritized for Angular 8. Probably more likely to be looked at after Ivy comes out because it might affect implementation.

**Closed by kara** 2019-01-23 00:08 UTC
Labels: comp: forms, type: feature
