### ISSUE TITLE
Issue in directing to a Specified URL directly

### ISSUE THREAD

**Issue by usersk12** [angular/angular#14943] opened 2017-03-06 07:04 UTC
I'm submitting an issue regarding redirection of route to specified screen.

The issue I'm facing is when I directly try to access the specified URL as below, the default URL is shown.

[Specified URL]
localhost:8080/ReferenceApplication/SecondScreen

[Default URL]
localhost:8080/ReferenceApplication/FirstScreen

I'm using following method to redirect to default screen in my application :

1. Following is my routing file:

export const ROUTES: Routes = [
	...
	{
			path: "FirstScreen",
			component: FirstScreenComponent,
	},
	{
			path: "SecondScreen",
			component: SecondScreenComponent,
	},
	{
			path: "",
			component: AppComponent,
	},
]

2. For redirection to default screen, i've written following code in AppComponent, I've set an initial screen and navigating to default screen as follows:

const INTIALIZE_SCREEN_ID = "FirstScreen";
@Component{..}
export class AppComponent {
    constructor(protected router: Router) {
        this.router.navigate([INTIALIZE_SCREEN_ID]);
    }
}

The above scenario worked fine till @angular/router version 3.4.3. For higher version, the issue comes. Kindly confirm, why this issue is arising and if it is not supported in @angular/router versions above 3.4.3 or not

** Supporting information

I switched to using 'redirectTo' for redirection. The issue was resolved. Kindly confirm, if it is correct method.

I used the above method when 'redirectTo' was not introduced in Angular 2. 
I'm using Windows 8.1 and Chrome 56.0 on Windows. The application is developed using TypeScript 2.0.3. The node version and npm versions are v6.9.4 and v3.10.10 respectively.

**Comment by DzmitryShylovich** [comment] 2017-03-06 10:12
please add the plunkr that reproduces the issue. thanks

**Comment by mickeychu** [comment] 2017-03-06 12:18
I have the same problem. Had to reverse back to **@angular/router 3.4.3**

**Comment by usersk12** [comment] 2017-03-16 06:22
@DzmitryShylovich  I have added a GitHub project that could reproduce the issue. Kindly refer below link:
https://github.com/KAfroz/angular2-project

**Comment by helzgate** [comment] 2017-03-16 17:25
@mickeychu same here

**Comment by DzmitryShylovich** [comment] 2017-03-23 23:38
I can't reproduce https://plnkr.co/edit/FaJ3MMlfqbOYLiswxo5c?p=preview

**Comment by usersk12** [comment] 2017-03-24 05:40
@DzmitryShylovich i was not able to reproduce the issue in plunker too. The issue occurs only when application is running on server and URL is directly typed in the browser, other than default URL. Since AppComponent is being bootstrapped, it loads Comp2 automatically. If URL other than comp2, e.g comp1 is typed in browser, e.g. localhost:8080/#comp1, then comp2 loads for the first time, rather than comp1.

**Comment by vicb** [comment] 2017-03-24 06:03
@usersk12 please add steps to reproduce. Without further details we will close this issue. Thanks.

**Comment by DzmitryShylovich** [comment] 2017-03-24 07:01
@usersk12 when you change url manually, a page is not reloaded, so AppComponent's constructor is not executed.

**Comment by usersk12** [comment] 2017-03-24 10:42
@DzmitryShylovich The steps to produce issue are with respect to project on Github: https://github.com/KAfroz/angular2-project

Following are the steps to reproduce the issue:
1. Run the application using 'npm run build' and then 'npm start' after installing node_modules
2. Type following url in browser :  http://localhost:8080/DemoApplication/#/SCREEN2
3. It will load the URL: http://localhost:8080/DemoApplication/#/SCREEN1

**Comment by DzmitryShylovich** [comment] 2017-03-24 10:43
because of this line https://github.com/KAfroz/angular2-project/blob/master/common/archive/common/module/app.component.ts#L15

**Comment by usersk12** [comment] 2017-03-24 14:46
But at version @angular/router version 3.4.3, it works as expected

**Comment by DzmitryShylovich** [comment] 2017-03-24 15:02
@usersk12 it was a bug https://github.com/angular/angular/pull/13932

**Comment by usersk12** [comment] 2017-03-30 01:42
Thank you for the information @DzmitryShylovich . But the behaviour (switching to a URL directly) I require is achieved using redirectTo. Could you please confirm if using redirectTo as follows is the correct way or recommended way:
{
       path: "",        
       redirectTo: "/SCREEN1",
       pathMatch: "full" 
  },

Why i'm able to switch to URL directly while using redirectTo otherwise not?

**Comment by jasonaden** [comment] 2017-12-19 19:07
Fixed with #13932

**Closed by jasonaden** 2017-12-19 19:07 UTC
Labels: comp: router, type: bug
