### ISSUE TITLE
Multiple select issue when binding ngModel or formControl

### ISSUE THREAD

**Issue by ersandeepranjit** [angular/angular#12040] opened 2016-10-03 11:32 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`TypeError: values.map is not a function
    at SelectMultipleControlValueAccessor.writeValue (forms.umd.min.js:13)
    at setUpControl (forms.umd.min.js:13)
    at FormControlDirective.ngOnChanges (forms.umd.min.js:15)
    at DebugAppView._View_ApiAccessEditorComponent0.detectChangesInternal (ApiAccessEditorComponent.ngfactory.js:472)
    at DebugAppView.AppView.detectChanges (core.umd.min.js:38)
    at DebugAppView.detectChanges (core.umd.min.js:38)
    at DebugAppView.AppView.detectViewChildrenChanges (core.umd.min.js:38)
    at DebugAppView._View_ApiAccessComponent6.detectChangesInternal (ApiAccessComponent.ngfactory.js:754)
    at DebugAppView.AppView.detectChanges (core.umd.min.js:38)
    at DebugAppView.detectChanges (core.umd.min.js:38)`

**Expected behavior**
Select the Multiple option as a array is provided in the model

**Reproduction**
```<select multiple role="listbox" [formControl]="apiAccessForm.controls['roleName']" [(ngModel)]="objSelectedRole">
                    <title="select question" class="form-control">
                    <option *ngFor="let obj of objRoleList" [value]="obj.roleName">{{obj.roleName}}</option>
                    <select>```

**Its works, if I remove both ngModel and formControl directives, here objSelectedRole  is data from db**

* **Angular version:** 2.0.1
<!-- Check whether this is still an issue in the most recent Angular version -->



* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
<!-- All browsers where this could be reproduced -->
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment] 2016-10-03 11:43
Pls provide minimal reproduction.

**Comment by nertzy** [comment] 2016-10-05 16:01
Looks like a duplicate of #11926

**Comment by pkozlowski-opensource** [comment] 2016-10-05 21:16
It is a duplicate of  #11926 indeed, thnx @nertzy . I will look into those scenarios tomorrow.

Closing as a duplicate of #11926.

**Closed by pkozlowski-opensource** 2016-10-05 21:16 UTC
Labels: comp: forms, flag: can be closed?, state: Need repro
