### ISSUE TITLE
fix(common): don't capitalize local language special letters in TitleCasePipe

### ISSUE THREAD

**Issue by krzSobin** [angular/angular#20561] opened 2017-11-21 14:08 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The TitleCasePipe capitalizes special letters inside word and one normal letter after it.

For example
`<h3 class="panel-title">{{dailyMeals.date | date: 'EEEE, dd/MM/yyyy':'':'pl' | titlecase }}</h3>`
produces `PoniedziaŁEk, 25/12/2017`
(Poniedziałek is Monday in Polish)

## Expected behavior
`<h3 class="panel-title">{{dailyMeals.date | date: 'EEEE, dd/MM/yyyy':'':'pl' | titlecase }}</h3>`
produces `Poniedziałek, 25/12/2017`

## What is the motivation / use case for changing the behavior?
Intend to change the title case of words properly

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 62
- [x] Firefox version Quantum
 

</code></pre>

**Comment by trotyl** [comment] 2017-11-21 14:55
Possibly duplicate of #16586

**Comment by vicb** [comment] 2017-11-21 18:38
@krzSobin could you please add your use case to the former issue and close this one ?

**Comment by krzSobin** [comment] 2017-11-21 20:12
ok I will

**Closed** 2017-11-21 20:15 UTC
Labels: comp: common, severity3: broken
