### ISSUE TITLE
When processing a data model in a template, there is no type checking

### ISSUE THREAD

**Issue by splincode** [angular/angular#21400] opened 2018-01-08 20:30 UTC
## Normal situation

app.component.ts

```typescript
import { Component } from '@angular/core';

export interface CtxField {
  id: number;
  value: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  ctxFields: CtxField[] = [];
  selectedCtxField: CtxField;

  constructor() {
    this.selectedCtxField = {
      id: 0,
      value: "8-900-0000-000"
    };
  }

  public ngOnInit() {

    // mock
    this.ctxFields = [
      {
        id: 1,
        value: "8-911-1111-111"
      },
      {
        id: 2,
        value: "8-922-2222-222"
      }
    ];

  }

}

```

app.component.html

```html
<p>current selectedCtxField:</p>

<pre>
{{selectedCtxField|json}}
</pre>

<select [(ngModel)]="selectedCtxField">
  <option *ngFor="let ctx of ctxFields" name="ctx" [ngValue]="ctx">
    {{ctx.value}}
  </option>
</select>

```

Everything works as it should and was conceived by the developer

![image](https://user-images.githubusercontent.com/12021443/34690441-34c6e9a4-f4ca-11e7-939c-c0613d05a43f.png)

By the way, incomprehensible ticks

![image](https://user-images.githubusercontent.com/12021443/34690636-efb641c4-f4ca-11e7-9846-9039c44a1588.png)

## But the model can easily be redefined from the template (here typescript does not help)

app.component.html

```html
<p>current selectedCtxField:</p>

<pre>
{{selectedCtxField|json}}
</pre>

<select [(ngModel)]="selectedCtxField">
  <option *ngFor="let ctx of ctxFields" name="ctx" [ngValue]="ctx.value">
    {{ctx.value}}
  </option>
</select>
```

If I accidentally or intentionally point to the wrong ngValue, then the model can easily change, which means that when the data is further used in runtime, the result of the application can be unpredictable.

![](https://habrastorage.org/webt/8f/tn/q3/8ftnq30vqt6o6_a0ukcar3gei1k.gif)

![image](https://user-images.githubusercontent.com/12021443/34690458-48813d1e-f4ca-11e7-9a22-6115a3222d8c.png)

## Additional questions to the compiler

*ngFor, *ngIf ... etc need import CommonModule
ngModel ... etc need import FormsModule
...

if I forget to add, the errors appear in the runtime, but there is no warning when building the application with webpack (why no clues what modules to plug in? why should I crawl on stackoverflow)

## Minimal reproduction of the problem with instructions

Repo: https://github.com/splincode/typecheck-bad

## Environment

Angular version: 5.1.3

**Comment by trotyl** [comment] 2018-01-09 02:05
Duplicate of #16952

**Comment by kara** [comment] 2018-01-09 18:49
Yeah, looks like a duplicate.

**Closed by kara** 2018-01-09 18:49 UTC
