### ISSUE TITLE
Page with list of built-in pipes is missing (eg keyvalue pipe)

### ISSUE THREAD

**Issue by koesper** [angular/angular#56150] opened 2024-05-29 09:57 UTC
### Describe the problem that you experienced

On the page https://angular.dev/guide/pipes, you expect a full list of the available pipes, but some are missing: eg the keyvalue pipe.
Because this list is incomplete, they the note at the bottom links to https://angular.dev/api/common#pipes "For a complete list of built-in pipes"
That page does not exist on the new domain.
for v16, it is still available at https://v16.angular.io/api?type=pipe

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

**Comment by JeanMeche** [comment] 2024-05-29 09:59
Duplicate of https://github.com/angular/angular/issues/52968

**Closed by JeanMeche** 2024-05-29 09:59 UTC
