### ISSUE TITLE
'regeneratorRuntime' is undefined IE 11

### ISSUE THREAD

**Issue by JohnGalt1717** [angular/angular#32393] opened 2019-08-29 11:23 UTC
# 🐞 bug report

### Affected Package
Startup

### Is this a regression?
Yes. It was working in earlier versions of Angular 8.

### Description

With the following browserslist file that npx browserslist shows IE 11 compatbility:

> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11 # For IE 9-11 support, remove 'not'.

Opening the site in IE 11 (build -prod, not serve) results in the above error which appears to be a shim missing? 

My understanding is that this was supposed to be shimed automatically or handled by the cli.  Am I missing something? I compared my tsconfig against the ng new version and they're identical so I'm at a loss.

**Angular Version:**
Angular CLI: 8.3.0
Node: 12.3.1
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@angular/http                     7.2.15
@angular/pwa                      0.803.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2

**Comment by trotyl** [comment] 2019-08-29 15:01
Duplicate of https://github.com/angular/angular-cli/issues/15436, will be solved by https://github.com/angular/angular-cli/pull/15470

**Closed** 2019-08-29 15:08 UTC
