### ISSUE TITLE
Issue with ivy removing html nodes when an object tree is updated and the nodes are defined by the object tree

### ISSUE THREAD

**Issue by neofuture** [angular/angular#38239] opened 2020-07-26 23:45 UTC
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core
### Is this a regression?
Yes, the previous version in which this bug was not present was: error in console log

### Description
strange error when change detection removes nodes when using *ngFor I have a complex set of div's being rendered

## 🔥 Exception or Error
<pre>[Error] ERROR
TypeError: Argument 1 ('child') to Node.removeChild must be an instance of Node
removeChild
removeChild — platform-browser.js:672
(anonymous function) — tooltip.directive.ts:47
onInvokeTask — core.js:27137
runTask — polyfills.js:180
invokeTask — zone-evergreen.js:480
timer — zone-evergreen.js:2552
	defaultErrorLogger (vendor.js:10098)
	handleError (vendor.js:10146)
	next (vendor.js:33717)
	(anonymous function) (vendor.js:30555)
	__tryOrUnsub (vendor.js:55226)
	next (vendor.js:55165)
	_next (vendor.js:55115)
	next (vendor.js:55092)
	next (vendor.js:54878)
	emit (vendor.js:30545)
	run (polyfills.js:136)
	onHandleError (vendor.js:33189)
	runTask (polyfills.js:183)
	invokeTask (polyfills.js:493)
	timer (polyfills.js:2565)<code>
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cli                      10.0.3
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
Issue is very sporadic only happening in 25% of occasions, im unable to share a repo because of company copyright, but please reach out on neofuture@gmail.com and I will send a personal repo

**Comment by neofuture** [comment] 2020-07-26 23:47
Might be me ill close for now and re-open if I need too

**Comment by neofuture** [comment] 2020-07-27 00:35
Ok the issue was issued by the directive, trying to removed a node through Renderer2, there is no check to see if the node exists, so when closing a node that the Dom has deleted through change detection, the renderer then reports an an error that the element no longer exists.

**Comment by pkozlowski-opensource** [comment] 2020-07-27 09:43
@neofuture I'm afraid that we will need a simplified / extracted reproduction scenario here. I understand that your application setup might be quite complex but you are in the privileged position to actually narrow down the scenario and extract the relevant pieces (it doesn't have to be your application code at all - we need the actual scenario using sample components / directives).

As the issue stands it is not reproductible for us and as such not actionable...

**Comment by neofuture** [comment] 2020-07-27 18:22
Repo

https://github.com/neofuture/DesktopV2

To illustrate the issue, open a new window, hover over the close icon on a new window, move the mouse as you click the close button, this causes the directive to trigger to hide the tool tip at the same time the window is removed via a change to the windows object, the directive triggers Renderer2 to remove the tooltip node

This causes the error in the console.

This can probably be argued that the issue is created by me because the directive has a timeout to show a fade transition, as does the window component. Please feel free to close this is you believe that Renderer2 should not be required to check the node should exist before attempting to destroy it

**Comment by AndrewKushnir** [comment] 2020-10-28 20:27
Just checked the GitHub link and it looks like a repro is removed. I will close this ticket, please create a new one if the problem still exists and there is a minimum repro that we can look at (I guess the mentioned scenario can be re-created using https://stackblitz.com/). Thank you.

**Closed by AndrewKushnir** 2020-10-28 20:27 UTC
Labels: comp: core, core: DOM rendering, needs clarification, needs reproduction
