### ISSUE TITLE
Generic type for FormBuilder functions

### ISSUE THREAD

**Issue by michaeljota** [angular/angular#22202] opened 2018-02-13 17:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

FormBuilder have functions to create forms controls, but they can't be typed with a model structure.

## Expected behavior

FormBuilder functions could have a generic type argument to type the form model.
```typescript
interface Model {
  name: string;
}

this._fb.group<Model>({
  name: '', // Verify property value
}) 

this._fb.group<Model>({
  name: 123123, // Throws error
}) 
```
## What is the motivation / use case for changing the behavior?

Typed Forms can help and improve development.

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: LTS 
- Platform:  Windows 

Others:

</code></pre>

**Comment by Toxicable** [comment] 2018-02-13 18:18
Duplicate of https://github.com/angular/angular/issues/13721

**Comment by IgorMinar** [comment] 2018-02-13 23:19
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #13721. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2018-02-13 23:19 UTC
Labels: comp: forms
