### ISSUE TITLE
Angular 5 is missing COMPILER_PROVIDERS

### ISSUE THREAD

**Issue by claygifford** [angular/angular#20253] opened 2017-11-07 20:04 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular 5 does not include COMPILER_PROVIDERS @angular/compiler

## Expected behavior

Angular 5 include COMPILER_PROVIDERS @angular/compiler

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-11-08 01:56
> One intentional omission from this list is `@angular/compiler`, which is currently considered a low level api and is subject to internal changes. These changes will not affect any applications or libraries using the higher-level apis (the command line interface or JIT compilation via `@angular/platform-browser-dynamic`). Only very specific use-cases require direct access to the compiler API (mostly tooling integration for IDEs, linters, etc). If you are working on this kind of integration, please reach out to us first.

As stated in [PUBLIC_API](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md) doc, the `@angular/compiler` is not part of the public APIs, so any use case based on it is not a defined behavior.

**Comment by claygifford** [comment] 2017-11-08 15:29
So where is the JitCompilerFactory then?

**Comment by claygifford** [comment] 2017-11-08 22:21
import { JitCompiler } from '@angular/compiler';

public static createComponent(compiler: JitCompiler, template: string, components: any[]): object {
        @Component({ template })
        class TemplateComponent { }

        @NgModule({ declarations: [TemplateComponent], imports: [RouterModule, ControlsModule] })
        class TemplateModule { }

        const mod = compiler.compileModuleAndAllComponentsSync(TemplateModule);
        const factory = mod.componentFactories.find((comp: any) =>
            comp.componentType === TemplateComponent
        );

        return factory;
 }


causes JitCompiler provider exception.

COMPILER_PROVIDERS in angular 4 allowed this code to work.

Where is the JitCompilerFactory in angular 5?

**Comment by trotyl** [comment] 2017-11-09 01:46
Duplicate of #20125, please respect `Please search GitHub for a similar issue or PR before submitting`.

**Comment by jasonaden** [comment] 2017-11-09 21:08
Closing as duplicate.

**Closed by jasonaden** 2017-11-09 21:08 UTC
Labels: comp: core & compiler, flag: can be closed?
