### ISSUE TITLE
Nested selectors in sass parent selector `&` are not encapsulate properly

### ISSUE THREAD

**Issue by koji-nakamura-classi** [angular/angular#50215] opened 2023-05-09 04:10 UTC
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

With the default value of View.encapsulation, nested selectors in sass parent selector `&` like below are not encapsulate properly.

```
:host {
  dl {
    color: blue;

    dt {
      font-weight: bold;
      text-decoration: underline;
    }
  }

  &[red] {
    dl {
      color: red;

      dt {
        font-weight: normal;
        text-decoration: line-through;
      }
    }
  }
}
```

Generated style:

```
[_nghost-ffs-c12]   dl[_ngcontent-ffs-c12]{color:blue}
[_nghost-ffs-c12]   dl[_ngcontent-ffs-c12]   dt[_ngcontent-ffs-c12]{font-weight:bold;text-decoration:underline}
[red][_nghost-ffs-c12] dl{color:red}
[red][_nghost-ffs-c12] dl dt{font-weight:normal;text-decoration:line-through}
```

Some attribute selectors are missing, so that styles are applied in the wrong order due to CSS Specificity.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/54160928/236989283-ea6d0277-1c6b-48b2-b3ed-6b1fdd3cc393.png">

Expected style is below (and angular 15.1.1 generate this properly).

```
[_nghost-ffs-c12]   dl[_ngcontent-ffs-c12]{color:blue}
[_nghost-ffs-c12]   dl[_ngcontent-ffs-c12]   dt[_ngcontent-ffs-c12]{font-weight:bold;text-decoration:underline}
[red][_nghost-ffs-c12] dl[_ngcontent-ffs-c12]{color:red}
[red][_nghost-ffs-c12] dl[_ngcontent-ffs-c12] dt[_ngcontent-ffs-c12]{font-weight:normal;text-decoration:line-through}
```

angular 15.1.2+ reproduce this behavior.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-p2auoh?file=src%2Fsome.component.scss

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 15.1.2
```

### Anything else?

Angular 15.1.1 does not reproduce this.
Angular 16.0.0 reproduce this.

**Comment by JoostK** [comment] 2023-05-09 06:22
Likely affected by #48558 given the patch release you identified (thank you, that is super helpful 💯)

/cc @JeanMeche

**Comment by JeanMeche** [comment] 2023-05-09 07:39
Hi, I have #49118 that is pending review to fix this issue !

**Comment by JeanMeche** [comment] 2023-06-10 10:45
I'm closing this as a dupe of #49100, watch for the PR to see when the fix lands !

**Closed by JeanMeche** 2023-06-10 10:45 UTC
Labels: regression, area: compiler, core: CSS encapsulation, P3
