### ISSUE TITLE
Getting this - Error during instantiation of Token(Promise<ComponentRef>)!.

### ISSUE THREAD

**Issue by mi6crazyheart** [angular/angular#4156] opened 2015-09-13 02:14 UTC
I'm new to angular. Currently playing with it's doc from "https://angular.io/docs/ts/latest/guide/displaying-data.html" . 

My files -

show-properties.html
-----------------------------
    <!DOCTYPE html>
    <html>
        <head>
            <script src="../node_modules/traceur/bin/traceur-runtime.js"></script>
            <script src="../node_modules/es6-module-loader/dist/es6-module-loader.js"></script>
            <script src="../node_modules/systemjs/dist/system.src.js"></script>
            <script src="../node_modules/angular2/bundles/angular2.dev.js"></script>
        </head>

        <body>
            <display></display>

            <script>
                System.import('show-properties');
            </script>
        </body>
    </html>

show-properties.ts
---------------------------
    // TypeScript
    import {Component, View, bootstrap, NgFor} from 'angular2/angular2';

    @Component({
	    selector: 'display',
	    appInjector: [FriendsService]
    })

    @View({
	    template: `
	      <p>My name: {{ myName }}</p>
	      <p>Friends:</p>
	      <ul>
	         <li *ng-for="#name of names">
	            {{ name }}
	         </li>
	      </ul>
	    `,
	    directives: [NgFor]
    })

    class DisplayComponent {
	    myName: string;
	    names: Array<string>;

	    // constructor() {
	    // 	this.myName = "Alice";
	    // 	this.names = ["Aarav", "Martín", "Shannon", "Ariana", "Kai"];
	    // }

	    constructor(friendsService: FriendsService) {
		    this.myName = 'Alice';
		    this.names  = friendsService.names;
	    }
    }

    class FriendsService {
	    names: Array<string>;
	    constructor() {
		    this.names = ["Alice", "Aarav", "Martín", "Shannon", "Ariana", "Kai"];
	    }
    }

    bootstrap(DisplayComponent);

When I'm executing above code it's giving me following error - 
    EXCEPTION: Error during instantiation of Token(Promise<ComponentRef>)!.
    angular2.dev.js:22367 ORIGINAL EXCEPTION: Cannot resolve all parameters for DisplayComponent(undefined). Make sure they all have valid type or annotations.
    angular2.dev.js:22367 ORIGINAL STACKTRACE:
    angular2.dev.js:22367 Error
        at NoAnnotationError.BaseException (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:7735:25)
        at new NoAnnotationError (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:9092:63)
        at _extractToken (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:25841:13)
        at http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:25804:14
        at Array.map (native)
        at Function.execute.ListWrapper.map (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:8494:26)
        at _dependenciesFor (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:25803:24)
        at execute.Binding.resolve (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:25933:28)
        at Function.execute.metadata.createFromBinding (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:28203:30)
        at Function.execute.metadata.createFromType (http://localhost/ngular/node_modules/angular2/bundles/angular2.dev.js:28237:37)

But, when I'm not injecting that CLASS ARRAY property(FriendsService) & using it normally by making following changes it's working fine.

    class DisplayComponent {
	    myName: string;
	    names: Array<string>;

	    constructor() {
		    this.myName = "Alice";
		    this.names = ["Aarav", "Martín", "Shannon", "Ariana", "Kai"];
	    }

	    // constructor(friendsService: FriendsService) {
	    // 	this.myName = 'Alice';
	    // 	this.names  = friendsService.names;
	    // }
    }

Any one, suggest me where i'm doing wrong ?

**Comment by jessegood** [comment] 2015-09-13 03:32
`appInjector` was removed in `alpha-29`. We are at alpha-37 now and you can use `bindings` there instead. 
Your `class FriendsService` is declared after `DisplayComponent`. Classes are not hoisted, see http://blog.thoughtram.io/angular/2015/09/03/forward-references-in-angular-2.html for some in depth information.

**Comment by mi6crazyheart** [comment] 2015-09-13 04:17
Event after replacing "appInjector" with "bindings" & declaring class 'FriendsService' before 'DisplayComponent' it's not working.

**Comment by jessegood** [comment] 2015-09-13 04:48
Try using @Inject(FriendsService) friendsService: FriendsService

**Comment by mi6crazyheart** [comment] 2015-09-13 04:55
I've updated my 'DisplayComponent' constructor to -
```constructor(@Inject(FriendsService) friendsService: FriendsService)```

& added 'inject' to import also -
```import {Component, View, bootstrap, NgFor, Inject} from 'angular2/angular2';```

Still, no luck

**Comment by ericmartinezr** [comment] 2015-09-13 11:06
Hey @mi6crazyheart 

First of all you can remove es6-module-loader since [it isn't used anymore](https://github.com/angular/angular/pull/3867).

Second, add System.config (this is mine, could be different in your case)
```javascript
System.config({
	traceurOptions: {
	   annotations: true,
	   types: true,
	   memberVariables: true
	},
	paths: {
		'angular2/*' : 'node_modules/angular2/*',
		 'rx': 'node_modules/rx/dist/rx.all.min.js'
	},
	defaultJSExtensions: true
});
```
*Note: Keep in mind that [traceur will be replaced with es6-shim](https://github.com/angular/angular/pull/4148)*

And third, I would recommend you to upgrade your typescript version (I'm guessing it's 1.5.3) to 1.6.0-beta

`npm install -g typescript@^1.6.0-beta`

PS : It is weird, I've had being using typescript  1.5.3 and viewBindings/bindings and I've never had to use `@Inject` with my services. I don't know why so many differences.

**Comment by webteckie** [comment] 2015-09-14 02:32
I'm seeing the same issue described by @mi6crazyheart using v37.  Has someone else really confirmed this still works fine in v37?  I've tried both with and without forwardRef as in the linked blog and can't get it to work.

**Comment by jessegood** [comment] 2015-09-14 03:10
@webteckie :
Here's a plunk in alpha-37 if you want to compare with your code:
http://plnkr.co/edit/G2WdDzdr36UF3mALzqi5?p=preview

**Comment by mi6crazyheart** [comment] 2015-09-14 03:58
@webteckie : Your plunk code is working for me.

**Comment by zheffie** [comment] 2015-09-26 15:33
I'm experiencing the same as @mi6crazyheart

**Comment by mhevery** [comment] 2015-09-29 16:51
This is a configuration issue of missing annotations. The error message is telling you that. Closing as working as intended. If you have trouble getting the project running please check with gitter.

**Closed by mhevery** 2015-09-29 16:51 UTC
