### ISSUE TITLE
Attribute and class bindings throw an error when declared inside ngForm elements in Beta.1

### ISSUE THREAD

**Issue by deeleman** [angular/angular#6374] opened 2016-01-09 14:24 UTC
I've come across a really weird error right after upgrading to Beta 1: Every time I drop a `[class.whatever]` or any other attribute binding within a nested DOM element wrapped by a `ngForm` element I get the infamous `No provider for ControlContainer! (NgControlName -> ControlContainer)` exception.

I've put together a tiny sample component to replicate the error:

```javascript
import { bootstrap } from 'angular2/platform/browser';
import { Component } from 'angular2/core';
import { FormBuilder, ControlGroup, Control, Validators, FORM_PROVIDERS, FORM_DIRECTIVES } from 'angular2/common';

@Component({
    selector: 'test-form',
    directives: [FORM_DIRECTIVES],
    template: `
        <form [ngFormModel]="testForm">
            <p *ngIf="!testControl.valid">Form is empty and hence not valid</p>

            <!-- This little guy below will make Angular 2 complain -->
            <div [class.error]="!testControl.valid">
                <input type="text" ngControl="testControl">
            </div>

        </form>
    `
})
class TestForm {
    testForm: ControlGroup;
    testControl: Control;

    constructor(private formBuilder: FormBuilder) {
        this.testControl = new Control('', Validators.required);
        this.testForm = this.formBuilder.group({
            testControl: this.testControl
        });
    }
}

bootstrap(TestForm, [FORM_PROVIDERS]);
```

Apparently this only occurs when attaching class or attribute bindings to nested elements. Whenever I bind class names by means of `ngClass` instead, the issue simply does not occur.

**Comment by deeleman** [comment] 2016-01-09 19:15
The following plunker showcases the issue: http://plnkr.co/edit/PLViDZQ4SWbpLwNqbWWE

The exception thrown there is different though: 
> `EXCEPTION: No provider for t! (t -> t)`

**Comment by qdouble** [comment] 2016-01-10 02:52
I'm having the exact same issue as well, had to almost delete the whole form until I got to what the issue was.

**Comment by user414** [comment] 2016-01-10 15:45
I'm getting also the same issue, but strangely in my environment I get the error in the OP first post
``` No provider for ControlContainer...```
and when I downgrade to beta0 I still get the same error. However, I see in the plunk it works when downgrading to beta0...

**Comment by danicomas** [comment] 2016-01-11 09:23
The same error. Is it a ngControl error?

**Comment by deeleman** [comment] 2016-01-11 09:46
@danicomas: It's actually hard to point fingers in one way or another. I managed to replicate the error just by dropping an attribute binding with a dynamic ARIA role in a random node in the code example prior to post the Plunker but now I do not recall if there was an `NgControl` around. Perhaps that is a good starting point to start debugging, although the exception thrown in the plunker seems pretty esoteric and kind of unrelated to me.

**Comment by user414** [comment] 2016-01-11 14:04
@danicomas Yes I'm getting the exactly error
```
No provider for ControlContainer! (NgControlName -> ControlContainer)
```

@deeleman 
If we change the dependency in the plunker to the dev one
```
<script src="https://code.angularjs.org/2.0.0-beta.1/angular2.dev.js"></script>
<script src="https://code.angularjs.org/2.0.0-beta.1/http.dev.js"></script>
```
we get the error above and not the more cryptic one
```
EXCEPTION: No provider for t! (t -> t)
```

**Comment by zgosalvez** [comment] 2016-01-18 11:21
This appears to be a simple workaround for now:

Switch to `https://code.angularjs.org/2.0.0-beta.1/angular2.dev.js` then change all instance of `ngControl` in your views to `(ngControl)`.

**Comment by spock123** [comment] 2016-01-18 15:16
@zgosalvez  I have to use the npm source, as I'm using Webpack. I'll just downgrade to beta0 again until this is resolved.. but thanks

**Comment by spock123** [comment] 2016-01-18 15:28
I have to admit I just removed the [ngClass] in the parent divs for now.

I'm using Webpack, and it was too much of a hazzle to change too much of the code for the workaround. When ( fingers crossed) this gets resolved, I'll reintroduce my [ngClass] thingies..

**Comment by jvanharn** [comment] 2016-01-22 13:29
I have this same problem after upgrading to beta.1, and the weird thing is that in one controller it works without  the braces () around ngControl,, on the other (where I get this error) I had to add the braces and it suddenly worked again.
I should also mention that I am not using [ngClass] or [class.something] on any of the *parent* elements, but *am* using them in children and siblings. I also have a `*ngIf` on the same element as the `[ngFormModel]`. I have tried separating them etc., but nothing seemed to help.

**Comment by vcorr** [comment] 2016-02-01 11:18
Still having this issue with beta.2

**Comment by yfain** [comment] 2016-02-01 12:01
Getting the same error in beta.2.

angular2.dev.js:22833 EXCEPTION: No provider for ControlContainer! (NgControlName -> ControlContainer)
angular2.dev.js:22823 EXCEPTION: No provider for ControlContainer! (NgControlName -> ControlContainer)BrowserDomAdapter.logError @ angular2.dev.js:22823

 Downgrade to beta.0 helped.

**Comment by jvanharn** [comment] 2016-02-03 17:26
Comming back unto my earlier comment. After upgrading to beta.2 the adding of braces around ``ngControl`` no longer works, as it still does not throw an error, but now it no longer changes the value of the field (e.g. in the browser the field appears to have no value). All the events do still seem to trigger though (like the validation etc.) which makes it even weirder.

**Comment by jvanharn** [comment] 2016-02-05 13:56
This error persists in beta.3

**Comment by jvanharn** [comment] 2016-02-05 14:53
I have been debugging a bit, and something is causing the dependency injection to look for the dependencies only in it's own contexts. This namely the only form to even get to the ``getPrivateDependency`` function. The ``NgControlName`` instance injection thing has a ``SkipSelfMetadata`` in it's ``lowerBoundVisibility``, causing it to not look in it's parent in the ``Injector.prototype._getByKeyHost`` function. Basically, if I runtime edit the code to not include this check, (and let it roll through to it's parent), it works.

I haven't checked if there are any changes to this code (The injector and the NgControlName metadata) since beta.0, but I will after the weekend.

Does any actual core developer know what might be causing this?

`
Injector._getPrivateDependency (injector.js:620)
Injector._getByKeyHost (injector.js:601)
Injector._getByKey (injector.js:581)
Injector._getByDependency (injector.js:571)
Injector._instantiate (injector.js:468)
Injector._instantiateProvider (injector.js:440)
Injector._new (injector.js:430)
InjectorInlineStrategy.instantiateProvider (injector.js:194)
ElementDirectiveInlineStrategy.init (element.js:547)
AppElement (element.js:237)
viewFactory_RoleFormComponent6 (viewFactory_Rol…omponent:13921)
AppViewManager_.createEmbeddedViewInContainer (view_manager.js:110)
ViewContainerRef_.createEmbeddedView (view_container_ref.js:71)
Object.defineProperty.set (ng_if.js:31)
ChangeDetector_RoleFormComponent_1.detectChangesInRecordsInternal (viewFactory_Rol…mComponent:270)
AbstractChangeDetector.detectChangesInRecords (abstract_change…etector.js:105)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:88)
AbstractChangeDetector._detectChangesContentChildren (abstract_change…etector.js:167)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:89)
AbstractChangeDetector._detectChangesInViewChildren (abstract_change…etector.js:173)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:92)
AbstractChangeDetector._detectChangesContentChildren (abstract_change…etector.js:167)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:89)
AbstractChangeDetector._detectChangesContentChildren (abstract_change…etector.js:167)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:89)
AbstractChangeDetector._detectChangesInViewChildren (abstract_change…etector.js:173)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:92)
AbstractChangeDetector._detectChangesInViewChildren (abstract_change…etector.js:173)
AbstractChangeDetector.runDetectChanges (abstract_change_detector.js:92)
AbstractChangeDetector.detectChanges (abstract_change_detector.js:77)
ChangeDetectorRef_.detectChanges (change_detector_ref.js:31)
(anonymous function) (application_ref.js:358)
ApplicationRef_.tick (application_ref.js:357)
(anonymous function) (application_ref.js:266)
Zone.run (zone.js:115)
(anonymous function) (ng_zone.js:175)
NgZone.run (ng_zone.js:137)
(anonymous function) (application_ref.js:265)
schedulerFn (async.js:113)
tryCatcher (tryOrOnError.ts:5)
Subscriber.next (Subscriber.js:106)
Subject._next (Subject.js:112)
Subject.next (Subject.js:76)
EventEmitter.emit (async.js:94)
(anonymous function) (ng_zone.js:68)
Zone.run (zone.js:115)
NgZone._notifyOnTurnDone (ng_zone.js:67)
(anonymous function) (ng_zone.js:182)
zoneBoundFn (zone.js:94)
`

**Comment by eliezerreis** [comment] 2016-02-11 00:58
+1 same bug

**Comment by gingters** [comment] 2016-02-12 09:27
I also encounter the same issue. Also, the Temporary fix with the additional *ngIf between the form and the enclosing element does work around the issue.

Thanks a lot @jvanharn for this investigation.

**Comment by Binvention** [comment] 2016-02-15 19:42
I have this problem in beta.6 except im not using ngControl instead my error is for ngIf that is contained within a component if i remove the ngIf the problem goes away but no matter what i put the value of the ngIf to it bring up the error (which since im using the compiled non dev version is EXCEPTION: No provider for e! (e -> e) )

**Comment by sraparlatmw** [comment] 2016-02-16 15:47
Updated to beta.6 and I am getting this error. Sample form I have 
` <form  role="form" name="accountAddFrm" id="accountAddFrm"  #accountForm = "ngForm" (ngSubmit)="saveData(accountForm)" novalidate>
            <div class="form-group row" [class.has-danger]="!name.valid && name.dirty">
                <label class="form-control-label col-sm-2 text-sm-right font-weight-bold" for="name">Name:</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name"
                           [(ngModel)]= "account.name"  ngControl="name"  #name="ngForm" required>
                </div>
            </div>
</form>
`
<img width="1229" alt="screen shot 2016-02-16 at 10 44 45 am" src="https://cloud.githubusercontent.com/assets/10406415/13081319/6e98f2dc-d49a-11e5-86b9-113135d678a6.png">

**Comment by afirdousi** [comment] 2016-02-19 00:28
This error persist in beta.3 through beta.6.

**Comment by joehmchan** [comment] 2016-02-19 16:32
I encountered the same issues and found a workaround in docs (https://angular.io/docs/ts/latest/api/common/NgFormControl-directive.html)

Finally, I wrapped the input form control like this
<input type='text' [(ngFormControl)]='someInputControl' [(ngModel)]='inputModel'>

[(ngFormControl)] will allow getter and setter.

**Comment by Binvention** [comment] 2016-02-20 20:02
Okay i found a really weird bug with this. i correct my previous comment it isn't ngIf contained within a component that doesn't work it is an ngIf that is in the same component as a ngStyle even though they are not on the same element  if either one is removed then the other works but for some odd reason they don't work in the same component at the same time. and the error recieved is the same error as many people have displayed above

**Comment by portah** [comment] 2016-02-26 03:16
The other temporary fix is to use [ngClass] instead of [class.something]

**Comment by nosachamos** [comment] 2016-02-26 23:57
Also hitting this issue. I guess I'm downgrading to beta.0, then.

**Comment by mohamedb** [comment] 2016-03-02 16:02
In beta 7 i get this error when I use ngControl on input  outiside of a <form> element.

**Comment by danielcreid** [comment] 2016-03-03 22:15
I am seeing the same behavior as @mohamedb in Beta 7. ngControl errors if it is on an input that's not nested inside a form element.

**Comment by vkrylov-iqcard** [comment] 2016-03-04 13:40
Beta7, still have error.

**Comment by bromzh** [comment] 2016-03-04 13:41
Beta7, still have error.

**Comment by ericmartinezr** [comment] 2016-03-04 13:43
@mohamedb @danielcreid that's the normal behavior. The control must be inside of a form. On the other hand this issue is a bug since it's completely ignoring that the control is inside a form.

**Comment by mofirouz** [comment] 2016-03-04 13:45
On beta8 and this is still an issue :/

**Comment by chad-autry** [comment] 2016-03-05 15:26
Attempted to update to beta8 as well (from beta0) having the same problem.

**Comment by chrkorn** [comment] 2016-03-06 12:41
+1.

In beta 8, using [class.xyz] on a fieldset inside a form triggers this problem:

```
<form [ngFormModel]="loginForm" (submit)="login()">
                    <fieldset class="form-group" [class.has-danger]="!valid">
                        <input ngControl="name" id="name" class="form-control form-control-lg" type="text"
                               placeholder="Nutzername" autofocus="autofocus" />
```

**Comment by cghislai** [comment] 2016-03-22 10:20
Just for information, I ran into this issue as well after upgrading to beta11.
This was caused by having form controls wrapped inside div elements with [hidden] directive set.
Replacing [hidden] with *ngIf solved the issue.

**Comment by chbrules** [comment] 2016-03-22 12:42
I'm currently having this issue after upgrading to 2.0.0 Beta 11. I've quickly tried to use that *ngIf="true" fix, but that didn't work. I have a div element wrapped around a form in a template, but it wasn't hidden. I tried removing it anyway, but that didn't work.

**Comment by vtajzich** [comment] 2016-03-26 15:26
+1 to fix it.

**Comment by rakeen** [comment] 2016-03-28 08:58
tried beta 12 didn't worked.

**Comment by DrewynV** [comment] 2016-04-05 00:28
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166462.
------------------------------------------------------------------------------------------------------------


[[dec1b3499971ae3cb89b2d15b0d293551459f0ce-673073421]]

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166563.
------------------------------------------------------------------------------------------------------------


[[aa382961e91dbdcfc92852ee9adda5e0f207cdb9-673074322]]

**Comment by mohamedb** [comment] 2016-04-05 09:28
@chrkorn did you mean  *ngFor="true" or *ngIF= true ?

**Comment by chrkorn** [comment] 2016-04-05 09:36
I meant *ngIf - sorry for the confusion.

**Comment by andrewkon** [comment] 2016-04-06 21:02
+1 on beta.13

**Comment by abductedMind** [comment] 2016-04-11 03:00
I received the `No provider for ControlContainer! (NgControlName -> ControlContainer)` error for not having the ngControl surrounded by a form tag.

**Comment by graundas** [comment] 2016-04-11 14:01
To make this work, you can replace `ngControl="name" `with `[ngFormControl]="form.find('name')"` .
For me it is much more readable workaround.

```
<form [ngFormModel]="loginForm" (submit)="login()">
     <fieldset class="form-group" [class.has-danger]="!valid">
          <input [ngFormControl]="loginForm.find('name')" id="name" class="form-control form-control-lg" type="text"
                               placeholder="Nutzername" autofocus="autofocus"/>
```

**Comment by joehmchan** [comment] 2016-04-12 07:18
portah, your temp fix work for me. It will not work only when css class name contains dash. I tried to do it like `[ngClass]={ 'state-disabled': !valid }`. It works properly.

I am using beta 14 + webpack

**Comment by doxiaodong** [comment] 2016-04-15 10:32
It works fine use [ngClass];
[class.haserror] is still not good.

**Comment by zhenyanghua** [comment] 2016-04-22 20:56
beta.15, same issue.

**Comment by sicaner** [comment] 2016-04-28 18:01
bea 16. OK

**Comment by sundriver** [comment] 2016-04-29 01:01
Actually I have it on beta 16

**Comment by zoechi** [comment] 2016-04-29 06:26
The issue would be closed and listed in the changelog if it had been fixed.

**Comment by bromzh** [comment] 2016-04-29 11:14
I haven't this issue anymore.
Angular@beta.16, rxjs@5.0.0-beta.5, zone.js@0.6.12. 
Checked in Chrome 50 and FF 45

**Comment by Lanayx** [comment] 2016-05-13 12:38
Still having this issue in rc1. This code structure throws No provider for ControlContainer
```
//parent component
<form>
  <myComponent></myComponent>
</form>

//myComponent
<input type="text"  ngControl="test" >
```

**Comment by cghislai** [comment] 2016-05-13 20:46
Put an ngForm directive in your myComponent template:

<div class="myComponent" ngForm>
<input type="text" ngControl="test">
</div>

**Comment by Lanayx** [comment] 2016-05-16 07:28
Thank you, @cghislai ! Now the error has gone, but I can't still can't use the control
```
//parent component
 <form #myForm="ngForm">
    <myComponent></myComponent>
 </form>

//myComponent
<div ngForm>
    <input type="text" ngControl="test" >
</div>
```
Meaning _myForm.Controls_ collection is empty, when I'm checking it on form submit.

**Comment by cghislai** [comment] 2016-05-16 13:32
This is a support question, please use StackOverflow.
That said, the following should work, provided your myComponent implements
NgValueAccessor

// parent
<form ngForm #myForm="ngForm">
  <myComponent ngControl="myComponentControl"
[(ngModel)]="myModelValue"></myComponent>
</form>
// child
<div ngForm>
  <input type="text" ngControl="myInputControl" [(ngModel)]="myModelValue">
</div>

**Comment by lathonez** [comment] 2016-08-09 12:55
The above issue:

```
    ✖ initialises
      PhantomJS 2.1.1 (Linux 0.0.0)
    Failed: Template parse errors:
    Can't bind to 'formGroup' since it isn't a known native property ("<form [ERROR ->][formGroup]="form" (submit)="newClicker(form.value)">
      <ion-row>
        <ion-col width-80>
    "): ClickerForm@0:6
    Expected null not to be null.
```

is solved by adding `REACTIVE_FORM_DIRECTIVES` to the component in question

**Comment by lathonez** [comment] 2016-08-09 12:56
EDIT (removed previous post) - too many issues open, sorry.

**Comment by kara** [comment] 2016-08-09 16:04
This issue looks stale. The new forms API should resolve this. Please feel free to open a new issue if anyone is still getting a ControlContainer issue with the new API.

**Closed by kara** 2016-08-09 16:04 UTC
Labels: comp: forms
