### ISSUE TITLE
Renderer does not unsubscribe on element removal

### ISSUE THREAD

**Issue by waterplea** [angular/angular#28541] opened 2019-02-05 13:38 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Is this a regression?

 No

### Description

 Not sure if it's really a bug or not, but if you remove element using Renderer2's `removeChild` method it does not trigger unsubscribe on event listeners added in a template. If element is removed/added with `*NgIf` event listeners are removed and reattached.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-destroy-event

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.0.0</code></pre>

**Anything else relevant?**

I've been experimenting with EventManager. I know it's a semi-public API but this is not really about it. I just noticed that events are unsubscribed only after the host view is destroyed, even if I do not keep any references to the removed child.

**Comment by pkozlowski-opensource** [comment] 2019-02-05 14:15
It is _not_ responsibility of `Renderer2` to remove event listeners so this is not a bug. Angular mostly operates on a view concept (capturing the fact that nodes in a given view are always created / deleted together and can't change position). Thus view creation / destruction is the place where event handlers are added / removed. `Renderer2` is a very low-level API that just abstracts DOM manipulation - a higher level APIs need to send take care of invoking proper DOM operations.

Closing as the `Renderer2` works as intended.

**Closed by pkozlowski-opensource** 2019-02-05 14:15 UTC
