### ISSUE TITLE
RequestOptions merge method not deep copying headers

### ISSUE THREAD

**Issue by dbettini** [angular/angular#11980] opened 2016-09-29 11:35 UTC
Not sure if this is a bug report or a feature request, since I'm not sure what you guys had in mind for this method in the first place. However, the [documentation](https://angular.io/docs/ts/latest/api/http/index/RequestOptions-class.html#!#merge-anchor) states that it creates a copy of RequestOptions instance, and does not change the values of the instance on which it is called.

**Current behavior** 
As per [source](https://github.com/angular/angular/blob/2.1.0-beta.0/modules/%40angular/http/src/base_request_options.ts#L91-L133), the method returns `headers` from one or the other object (`this` or `options`). That means that `copy` will have access to the same list as `this` or `options`. So, if the `append` method is called on `copy.headers`, the original instance it was copied from will also have the new version of headers, since they are using the same list.

**Expected behavior**
`copy.headers` is returned as a deep copy, so appending to `copy.headers` doesn't affect `this.headers` or `options.headers`. So, instead of returning `this.headers`, merge should return `new Headers(this.headers)` (same goes for `options`, if present).

**Reproduction of the problem**
EDIT: [plunker here](http://plnkr.co/edit/amSzQ5B8nACveEA1Q9Rm?p=preview)
Let's say we have custom BaseRequestOptions object globally available, that appends a custom `base-custom`header, and are provided through DI as Request options. Let's say we also have a CustomHttp service, that needs to append another custom header when its methods are called.

```
export class CustomHttp extends Http {

    constructor(protected _backend: XHRBackend,
        protected _defaultOptions: RequestOptions,
        private _customService: CustomService) {

        super(_backend, _defaultOptions);
    }
    get(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return customLogicBeforeReq.call(this, super.get, url, options);
    }
    // code...
}

function customLogicBeforeReq(func, url, options?){
    let reqOpts = this._defaultOptions.merge(options);
    reqOpts.headers.append("x-custom", "from custom service");
    // code...
    return func.call(this, url, reqOpts);
}
```

After appending to `reqOpts`, `this._defaultOptions` will also have that header appended (or `options`, if available). That means that for each request made with this service (without providing the `options` object), a new `x-custom` header will be appended. So, after 5 requests, `this._defaultOptions` will have an `x-custom` entry which is an array of 5 "from custom service" values. The expected behaviour would be that it only has one `base-custom` header, and none of `x-custom`.
- **Angular version:** 2.0.0

**Comment by vicb** [comment] 2016-09-29 15:38
1) your issue need a reproduction,
2) have you search the issue tracker for similar issue ?

**Comment by vicb** [comment] 2016-09-29 23:31
duplicate of #6060

**Comment by dbettini** [comment] 2016-09-29 23:40
1) I wrote the sample code, if there's something that's not understandable there, just tell and I'll try to explain.
2) Yes, I have searched. It would be nice if you read this issue before closing it. #6060 has nothing to do with this. Firstly, this one happens only with headers, not with query. Secondly, this has nothing to do with options rewriting the entire headers/query of the original, since that is written in the docs, so there would be no reason to think of it as a bug in the first place. I clearly stated that I'm not sure if this is a bug or not, since the docs say that the original should not be affected. 

All in all, I suggest you read this.

**Comment by vicb** [comment] 2016-09-30 00:28
@dbettini thanks for clarifying. We try to do our best to triage the issues but sometimes we fail !

Please add a plunker and I'll re-open. Thanks.

**Comment by dbettini** [comment] 2016-09-30 19:03
http://plnkr.co/edit/amSzQ5B8nACveEA1Q9Rm?p=preview fire away. Then, in the console, you can clearly see that the original, DI injected service instance (`this._defaultOptions`) is having its headers changed when you append to its copy (`reqOpts`) that was created by `merge` method. The way it should work is: changing the copy shouldn't affect the original, just like it works for other fields that are not reference types.

**Closed** 2016-12-12 19:16 UTC
Labels: comp: http
