### ISSUE TITLE
Parent form should become invalid if child component having formcontrol is invalid

### ISSUE THREAD

**Issue by salmansgit** [angular/angular#12812] opened 2016-11-11 16:32 UTC
I was expecting when a child component becomes invalid, parent component should become invalid too

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Parent form is valid even if child component is invalid, parent form should become invalid as well

http://plnkr.co/edit/6IEwagKr6fZaKY06QUWE?p=preview

There is no way to react on the parent form unless there is a separate output emitter to do the same.

Windows 10, lite-server

Angular 2.0.0

Browser: Chrome
 
Language: TypeScript 2.0.3 ES5

**Comment by DzmitryShylovich** [comment] 2016-11-11 16:40
Duplicate of https://github.com/angular/angular/issues/10530

**Comment by salmansgit** [comment] 2016-11-11 16:44
Isn't that issue is related to form group errors Vs status

**Comment by DzmitryShylovich** [comment] 2016-11-11 16:48
Status is calculated based on errors https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L536

**Comment by salmansgit** [comment] 2016-11-11 16:54
Even the child formcontrol status is not updated in the parent. 

`<small [hidden]="form.get('username').valid" class="text-danger">
         Child control Invalid
  </small>`

I can still make it work even if errors from child controls are not merged with the parent

`<small [hidden]="form.valid" class="text-danger">
         Form Invalid
  </small>`

But how to know that child control is invalid.

**Comment by kara** [comment] 2017-02-21 23:23
The internal state of a custom value accessor is encapsulated and doesn't bleed up to its parent form by design. Instead it has an explicit contract with its parent for common tasks like writing the value or adding custom validators. Just like you teach forms to write the value, you also teach forms how to validate it by default.

In practice, this means implementing a `validate()` method and providing it to NG_VALIDATORS as a default validator for your custom control.

```ts
{provide: NG_VALIDATORS, useExisting: Child, multi: true}

...

class Child implements ControlValueAccessor, Validator {
   writeValue() {...}   
   ...
   validate(ctrl: AbstractControl) {
     // or build the error list however you want
      return this.name.get('firstName').errors;
   }
}
```

Here is an [updated version of your plunker](http://plnkr.co/edit/ETmHHwoFw0tu40VkFb5g?p=preview).

This works as intended, but I can see how this can be confusing. We are looking into how we can make this more obvious and easier to write, so I'm adding this issue to our tracker as a potential pain point. Thanks for the report.

**Closed by kara** 2017-02-21 23:23 UTC
Labels: comp: forms

**Comment by squadwuschel** [comment] 2017-06-27 19:40
@kara this is a really great solution I've found so far https://gist.github.com/jehugaleahsa/c40fb64d8613cfad8f1e1faa4c2a7e33 the only working one
