### ISSUE TITLE
DomSanitizer: Apply angular2 directives to sanitized html

### ISSUE THREAD

**Issue by eliasre** [angular/angular#19197] opened 2017-09-14 11:16 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I would like to apply components/directives to the sanitized html produced by the domsanitizer.
I am currently sanitizing trusted html containing tags that offer spesific information.
These spesific tags should be compiled as directives, replacing their content with internal links (routerLink) to other components.

## Expected behavior

I am no angular wizard, but I suppose compiling html willy-nilly with all available components/directives would be bad both regarding security and AoT.
Ideally I would like to extend the DomSanitizer and provide the components/directives that are considered 'safe' and should be applied when the safeHtml is applied to a dom-element. Would be great if this also worked with AoT compilation.
If this is impossible (nothing is impossible), it would be nice with a workaround (parsing the html while in string-form seems tedious and applying routerLink is still impossible since that is also a directive)..

## What is the motivation / use case for changing the behavior?

Display certain attribute tags as internal links in sanitized html

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment] 2017-09-14 15:29
Sounds like duplicate of https://github.com/angular/angular/issues/15275 regardless what the API is.

**Comment by alxhub** [comment] 2021-07-17 00:54
Closing as not feasible - one of the points of sanitization is to explicitly prevent hooks into existing JS code.

**Closed by alxhub** 2021-07-17 00:54 UTC
Labels: comp: core, feature, insufficient votes, votes required
