### ISSUE TITLE
Validators should not called during view init

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#16346] opened 2017-04-26 12:54 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`validate` method is called multiple times during initialization. The AbstractControl value is first null then undefined.

For Validators registered on ModelGroups the method get be called for every input field two times.

Current calls:
```
FormGroup {} Object {}
FormControl {name: input1} null
FormGroup {} Object {input1: null}
FormControl {name: input1} ""
FormGroup {} Object {input1: ""}
FormControl {name: input2} null
FormGroup {} Object {input1: "", input2: null}
FormControl {name: input2} ""
FormGroup {} Object {input1: "", input2: ""}
```

**Expected behavior**
`validate` method should called at end of initilization with undefined.

Validator registered on ModelGroups should be called one time after all input fields are ready.

Expected calls:
```
FormControl {name: input1} ""
FormControl {name: input2} ""
FormGroup {} Object {input1: "", input2: ""}
```

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/AdYiqCTX3sjKiJDzQf8O?p=preview

**What is the motivation / use case for changing the behavior?**
I don't want to check in the validate method every time if the control is really initialized see the commented code in the `validate` method.

**Please tell us about your environment:**
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

* **Browser:**
Chrome 53
 
* **Language:**
TypeScript 2.2

**Comment by kara** [comment] 2019-01-08 23:52
Looks like a dupe of https://github.com/angular/angular/issues/21500. Keeping the later ticket because it has a bit more info. This is on our radar, but let's track it there.

**Closed by kara** 2019-01-08 23:52 UTC
Labels: comp: forms, freq1: low, severity2: inconvenient, type: bug/fix
