### ISSUE TITLE
setAttribute from Renderer2 is rendering all attributes in lower case

### ISSUE THREAD

**Issue by atmike** [angular/angular#22230] opened 2018-02-14 20:42 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When using Renderer2 to set Attributes on a DIV (in my case Felx Layout Attributes). The Renderer renders all Attributes in lower case. So fxFlex will get fxflex and the the FlexLayout is no longer working
Here is the Code I'm using =>
```
          var rowcol = renderer.createElement('div');
          renderer.setAttribute(rowcol , "fxFlex", "");
          renderer.setAttribute(rowcol , 'fxLayout', "row");
          renderer.setAttribute(rowcol , "fxLayout.xs", "column");
          renderer.setAttribute(rowcol , "fxLayoutGap", "10px");
```

## Expected behavior
The Attributes must be rendered as described in the function call. The outcome for "fxFlex" should be "fxFlex"

## Minimal reproduction of the problem with instructions
see my code above!

## What is the motivation / use case for changing the behavior?
At the moment it is not possible to render a FlexLayout from Code. 

## Environment

<pre><code>
I'm using Angular CLI 1.6.8 / Angular 5.1.3 / Node 9.5.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by trotyl** [comment] 2018-02-15 04:50
Duplicate of https://github.com/angular/angular/issues/17610, support question.

**Comment by atmike** [comment] 2018-02-15 08:22
Hi Trotyl,
I see that they are all related but there is no solution is any of them - since 6 Month. 
I thought both products are from google so why is there a finger pointing?
Regards

**Comment by sarunint** [comment] 2018-02-15 08:29
What @trotyl is trying to say is, [HTML attributes are case-insensitive](http://w3c.github.io/html-reference/documents.html#case-insensitivity) so it doesn't matter.

**Comment by atmike** [comment] 2018-02-15 08:34
I understood that! But that does not apply to fxLayout here it is a difference and the colleagues from FlexLayout say it it an angular problem and angular says it is a FlexLayout Problem.

**Comment by trotyl** [comment] 2018-02-15 08:38
@atmike For triggering directive from attribute binding, that's a feature request tracked at #11716. And `Renderer` has nothing to do with that.

**Closed** 2018-02-15 08:43 UTC
