### ISSUE TITLE
ng build fails when using @angular/bazel

### ISSUE THREAD

**Issue by rerion** [angular/angular#30256] opened 2019-05-03 13:15 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/bazel

### Is this a regression?

 Probably not

### Description

 <code>ng build</code> fails when using @angular/bazel
on vanilla project generated with `ng new`

## 🔥 Exception or Error
<pre><code>
ng build
INFO: Analysed target //src:prodapp (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/rerion/ideaprojects/house-of-r/ng-mui/src/BUILD.bazel:39:1: Downleveling JavaScript to ES5 src/bundle.js [typescript] failed (Exit 2)
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/http.d.ts(24,14): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/http.d.ts(48,14): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
../../../../ideaprojects/house-of-r/ng-mui/node_modules/@types/selenium-webdriver/remote.d.ts(139,29): error TS2583: Cannot find name 'Map'. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
Target //src:prodapp failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.090s, Critical Path: 5.19s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
C:\Users\rerion\IdeaProjects\house-of-r\ng-mui\node_modules\@bazel\bazel failed with code 1.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.0-rc.2
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0-rc.2
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.2
@angular-devkit/build-angular     0.800.0-rc.2
@angular-devkit/build-optimizer   0.800.0-rc.2
@angular-devkit/build-webpack     0.800.0-rc.2
@angular-devkit/core              8.0.0-rc.2
@angular-devkit/schematics        8.0.0-rc.2
@ngtools/webpack                  8.0.0-rc.2
@schematics/angular               8.0.0-rc.2
@schematics/update                0.800.0-rc.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

@angular/bazel:                   8.0.0-rc.2
@bazel/bazel:                     0.24.1
@bazel/ibazel:                    0.10.2
</code></pre>

**Anything else relevant?**

Error comes from here:
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/rollup/rollup_bundle.bzl#L501  
https://github.com/bazelbuild/rules_nodejs/blob/master/internal/rollup/rollup_bundle.bzl#L225-L238

**Comment by rerion** [comment] 2019-05-07 06:57
Work required:
- wait for this https://github.com/bazelbuild/rules_nodejs/pull/736
- wait for rules_nodejs release
- bump rules_nodejs

**Comment by kyliau** [comment] 2019-05-16 22:03
https://github.com/bazelbuild/rules_nodejs/pull/736 is merged and released as 0.29.0
Could you please confirm that the issue is fixed?

**Comment by kyliau** [comment] 2019-05-16 22:04
Please also remember to update @bazel/* packages to 0.29.0

**Comment by rerion** [comment] 2019-05-17 14:21
Yes, with rules_nodejs @ 0.29.0 prodapp target works fine

**Comment by kyliau** [comment] 2019-05-17 17:06
Thanks for confirming!

**Closed by kyliau** 2019-05-17 17:06 UTC
Labels: comp: bazel
