### ISSUE TITLE
Compiling @Injectable abstract class fails when constructor params cannot be resolved

### ISSUE THREAD

**Issue by johncrim** [angular/angular#37914] opened 2020-07-03 18:32 UTC
# 🐞 bug report

### Affected Package
This is caused by package @angular/compiler

### Is this a regression?
Kind-of - abstract classes didn't require `@Injectable` or `@Directive` annotations until v10

### Description

Adding `@Injectable` annotation to an abstract class, with `"strictInjectionParameters": true`, fails compilation if
the compiler can't resolve constructor parameter injection tokens for the abstract class constructor. This should not fail,
because the abstract class constructor isn't called by the angular injector at runtime.

## 🔬 Minimal Reproduction
I've attempted to reproduce it in stackblitz, but it seems that stackblitz doesn't respect the tsconfig  `"strictInjectionParameters": true`. The code is here:
https://stackblitz.com/edit/angular-ivy-vwamit

Here's a minimal repro on an `ng new --strict --minimal`:
https://github.com/johncrim/ng10-abstract-injectable/commit/a10be0eca1f4225a91946f65acdc46130a2da2b5

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/abstract.service.ts:6:24 - error NG2003: No suitable injection token for parameter 'name' of class 'AbstractService'.
Found string

6   constructor(readonly name: string) { }
                         ~~~~
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.1
Node: 14.4.0
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
See: https://github.com/angular/angular/pull/32987

It appears that a fix for this issue was added for the `@Directive` decorator (allowing abstract constructors to not be injectable), but not for `@Injectable`.

**Comment by JoostK** [comment] 2020-07-03 18:36
Thank you for the excellent bug report, this is indeed an issue.

**Comment by Zuckjet** [comment] 2020-07-11 15:33
Right now, Angular compiler will lose class information about whether is a abstract class or a normal class. It will compile `abstract class A` to `class A`, when I use ngc compiler to compile my code. 
If we know the class is a abstract class , we can let Angular DI not to handle the constructor params.
explicit use* definition can tell DI that constructor can be irrelevant , but abstract class cannot do in that way. So should we add more information to ClassDeclaration such as type property to tell whether the class is a abstract class or normal class ?

**Comment by Zuckjet** [comment] 2020-07-11 15:53
One more question , I don't whether it is a proper place to discuss here. Abstract class service can be a DI params, such as :
```
@Injectable({ providedIn: 'root' })
export abstract class AbstractService {
}

export class AppComponent {
  constructor(private service: AbstractService) {
  }
}
```
As you can see , I inject a abstract service into a component. At now, Angular won't throw error with this usage.
In my opinion, we cannot inject a abstract class service, because we cannot create a instance of abstract class. 
I am not sure this is working as intended or a bug.

**Comment by pheinicke** [comment] 2020-07-13 06:10
You could always write a provider for your abstract class, providing an actual implementation of that class. For me, that's a feature.

**Comment by sergidt** [comment] 2020-08-03 08:15
@pheinicke Prividing a provider for any abstract class could be a solution, but is not the best solution. Any developer should be able to extends any abstract class passing parameters, is a OOP rule, without resolving via Dependency Injector. 

In my product with thausands of files, I cannot resolve this kind of error declaring providers. In my opinion is a bug with high priority!!

**Comment by sergidt** [comment] 2020-11-26 08:25
Any update?

**Comment by JoostK** [comment] 2022-05-03 17:44
Hi folks, an update on this issue: the upcoming v14 will suppress the error for classes with the `abstract` keyword. Instead, it reports an error on a concrete subclass _iff_ the invalid constructor is inherited.

**Closed** 2022-10-10 21:46 UTC
Labels: type: bug/fix, freq2: medium, state: has PR, comp: compiler, P4

**Comment by JoostK** [comment] 2022-10-12 21:06
Sharing an update here: `15.0.0-next.6` has just been released which contains a change regarding this issue, such that `abstract` classes are now exempt from `strictInjectionParameters`. In contrast, the compiler is now strictly checking inheritance chains, such that subclasses are required to provide a compatible constructor. Please try out the prereleases and share any feedback on this new behavior in this issue or in a new issue.
