### ISSUE TITLE
AOT - function calls are not supported with Module.forRoot 

### ISSUE THREAD

**Issue by alvaro9210** [angular/angular#14707] opened 2017-02-24 17:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When AOT compiling my project, it throws the following error:
`Calling function 'PanelModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function.`
Event though I have no function/lambda functions on my PanelModule file.

**Expected behavior**
It should continue compilation instead of breaking with a normal Module file.

**Minimal reproduction of the problem with instructions**
- Have 2 Angular 2 projects
  - One only exporting a Module with its components (PanelModule)
  - The other one as your main project which imports it:
    - Uses webpack 2.0
    - Use [@ultimate/aot-loader](https://github.com/UltimateAngular/aot-loader/wiki/Usage)
    - @angular/compiler-cli

**app.module.ts**
```typescript
import { NgModule } from "@angular/core";
import { APP_BASE_HREF } from "@angular/common";
import { BrowserModule, Title } from "@angular/platform-browser";

// Providers
import { URL_BASE } from "./config";
import { CARBON_PROVIDERS } from "angular2-carbonldp/boot";
import { CARBON_SERVICES_PROVIDERS } from "angular2-carbonldp/services";
import { routing, appRoutingProviders } from "./app.routing";
// Components
import { AppComponent } from "./app.component";
import { LoginView } from "./login/login.view";
// Modules
import { PanelModule } from "carbonldp-panel/panel.module";

@NgModule( {
    imports: [
        BrowserModule,
        routing,
        PanelModule.forRoot(),     <---- This line causes the issue
    ],
    declarations: [
        AppComponent,
        LoginView
    ],
    providers: [
        {
            provide: APP_BASE_HREF,
            useValue: URL_BASE
        },
        CARBON_PROVIDERS,
        CARBON_SERVICES_PROVIDERS,
        appRoutingProviders,
        Title,
    ],
    bootstrap: [ AppComponent ],
} )
export class AppModule {}
```

**PanelModule**
```typescript
// Imports 
@NgModule( {
    imports: [
        CommonModule,
        RouterModule,
        SemanticModule,
        DirectivesModule,
        FormsModule
    ],
    declarations: [
        HeaderComponent,
	...
        PaginatorComponent,
    ],
    exports: [
        HeaderComponent,
	...
        PaginatorComponent,
    ],
    providers: []
} )

export class PanelModule {
    static forRoot():ModuleWithProviders {
        return {
            ngModule: PanelModule,
                providers: [ HeaderService, SidebarService, RouterService, MyAppsSidebarService, ErrorsAreaService ]
        };
    }
}
```

With that configuration, every time I try to AOT compile the project it returns the error mentioned above, but, as you can see, I have no lambda function in my PanelModule forRoot file.
If I comment that line (`PanelModule.forRoot(),`) it continues compilation but I need that line to work. 

**What is the motivation / use case for changing the behavior?**
The AOT compilation should work because the files are AOT compliant.

**Please tell us about your environment:**
OS X Sierra.

* **Angular version:** 2.0.X
@angular@2.4.7
@angular/compiler-cli@2.4.8
Webpack@2.2.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript@2.1.6

* **Node (for AoT issues):** `node --version` =   
v6.2.0

**Comment by DzmitryShylovich** [comment] 2017-02-24 17:08
angular `2.x` doesn't support ts `2.1.x`. did you try with ts `2.0.10`?

**Comment by alvaro9210** [comment] 2017-02-24 17:32
I just tried it with v.2.0.10 and it throws the same error.

**Comment by DzmitryShylovich** [comment] 2017-02-24 17:34
pls add a repro

**Comment by metamaker** [comment] 2017-02-27 07:57
@DzmitryShylovich This error is floating here for quite a while, see https://github.com/angular/angular-cli/issues/3706.

**Comment by DzmitryShylovich** [comment] 2017-02-27 08:18
@metamaker I tested it using https://github.com/AngularClass/angular2-webpack-starter and didn't get any errors so it's most likely a cli issue.

**Comment by vdzundza** [comment] 2017-04-10 16:18
I tried with angular version 4.0.1 and have the same issue

**Comment by ericmackrodt** [comment] 2017-04-11 01:13
I have the same issue with Angular 4.0.1 and webpack, AoT is a nightmare to configure. I can't build my app with ngx-bootstrap and ngx-translate.

Angular is really starting to get in my nerves.

**Comment by ericmackrodt** [comment] 2017-04-11 08:02
I managed to fix it. My problem was the "rootDir" in the tsconfig.json. I removed it completely and it started working.

**Comment by code0wl** [comment] 2017-04-25 13:45
@ericmackrodt For me it only breaks if I pass in an empty forRoot. I get this from using the ng-bootstrap package

**Comment by almgwary** [comment] 2017-05-07 10:41
please enable function and object

**Comment by MohammedSiddiqui** [comment] 2017-06-05 19:34
I'm currently the same issue as @ericmackrodt ...
Needed to work with Angular Universal and added ngx-bootstrap into my project, after which webpack throws up:
ERROR in Error encountered resolving symbol values statically. Calling function 'Ng2BootstrapModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in ....

**Comment by Yugloocamai** [comment] 2017-06-08 22:44
Same issue here trying to enable angular-router-loader

**Comment by ianqueue** [comment] 2017-06-14 18:28
same here... seems like it's just a blanket error that is thrown when 1 of the 20 AOT don'ts are present in your application.  The other one i see is `[your]Module is not an ngModule` if you don't have a forRoot().

I'm really hoping for better linting or build errors as this is a pain to triage.

**Comment by giovannicandido** [comment] 2017-07-05 01:38
This library: https://github.com/atende/angular-http-interceptor/blob/master/src/interceptor.module.ts

Contains a `withInterceptors` static function that behaves like forRoot. This code has working on previous versions, but now cannot compile with angular for the same problem reported in this issue.

**Comment by Ks89** [comment] 2017-08-06 17:10
This bug is really annoying. I'm using forRoot in a library published on npm and I discovered this error using it with the qdouble's starter.

Question for the Angular team:
- **Which is the recommended workaround until the official fix?**
- Also, will this problem be resolved in the next major release?

Thank you.

**Comment by tytskyi** [comment] 2017-08-07 08:14
@giovannicandido are you sure it was working in AOT mode or that method itself is not changed?

The fact that it does not is that acts methods like `forRoot` should be simple return statement with no logic inside.

@Ks89 what exactly does not work for you?

If you want `forRoot` method that can configure other services - use example of Angular Router package: 
https://github.com/angular/angular/blob/4.3.3/packages/router/src/router_module.ts#L150

See how `config` is registered as `ROUTER_CONFIGURATION` and then `ROUTER_CONFIGURATION` is used as a dependency for `LocationStrategy` below

**Comment by Ks89** [comment] 2017-08-08 16:38
@tytskyi I used InjectionToken and now I'm receiving this error (always with qdouble's starter) :

"ERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol KEYBOARD_CONFIGURATION in /Users/ks89/git/angular-webpack2-starter-demo-with-angular-modal-gallery/node_modules/angular-modal-gallery/src/modal-gallery.module.ts, resolving symbol ModalGalleryModule.forRoot in /Users/ks89/git/angular-webpack2-starter-demo-with-angular-modal-gallery/node_modules/angular-modal-gallery/src/modal-gallery.module.ts, resolving symbol AppModule in /Users/ks89/git/angular-webpack2-starter-demo-with-angular-modal-gallery/src/app/app.module.ts, resolving symbol AppModule in /Users/ks89/git/angular-webpack2-starter-demo-with-angular-modal-gallery/src/app/app.module.ts"

This is my code:

```
export const KEYBOARD_CONFIGURATION = new InjectionToken<KeyboardServiceConfig>('KEYBOARD_CONFIGURATION');

@NgModule({
  imports: [ CommonModule ],
  declarations: [ AngularModalGalleryComponent, UpperButtonsComponent, GalleryComponent, DIRECTIVES ],
  exports: [ AngularModalGalleryComponent ]
})
export class ModalGalleryModule {
  static forRoot(config?: KeyboardServiceConfig): ModuleWithProviders {
    return {
      ngModule: ModalGalleryModule,
      providers: [
        {
          provide: KeyboardService,
          useFactory: setupKeyboardService,
          deps: [ KEYBOARD_CONFIGURATION ]
        },
        {
          provide: KEYBOARD_CONFIGURATION,
          useValue: config ? config : {}
        }
      ]
    };
  }
}

export function setupKeyboardService(injector: KeyboardServiceConfig) {
  return new KeyboardService(injector);
}
```

**Comment by tytskyi** [comment] 2017-08-08 17:24
@Ks89 could you try to reorder provider so that `KEYBOARD_CONFIGURATION` is first provided, then used as a dependency?

Note: if your `ModalGalleryModule` is served like linked package (using `npm link`) you might want to try this solution: https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771 (add this in main project, not the library)

**Comment by Ks89** [comment] 2017-08-09 14:10
@tytskyi I tried and now It seems ok.
I changed the order, downgraded npm from 5.x.x to 3.x.x to use yarn with qdouble's starter and now It seems ok.

With npm I having the same issue again.

I should open an issue on that repository. Probably it's not a problem caused by Angular itself.

Thank u for your support.

**Comment by gciluffo** [comment] 2017-09-26 18:33
@tytskyi Having a similar issue with a similar setup to what @Ks89 has for his module. Is there any simple examples on how to make a custom module AOT while still providing config values in its `forRoot` method? Thanks in advance.

**Comment by vytautas-pranskunas-** [comment] 2017-11-02 22:05
Bug Report

- [x] bug report
I cannot understand why all issues are closed but it got me annoyed to the death... Wasted whole day on this and still cannot understand why this code is not working

```ts
@NgModule({
    imports: [CommonModule]
})
export class StoreModule {
    static provideStore(): ModuleWithProviders {
        return {
            ngModule: StoreModule,
            providers: [ added some providers]
        };
    }     
}
```
throwing an error:
```
"Calling function 'SotreModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule"
```

I compared it with RouterModule in .ts and .js all the same. Tried to many of work arounds and nothing.
In dev mode all works fine, when this code is added stright to project it works fine too, but when exported as a separate package - BAM - nothing!

Anybody?

For example RouterModule:
```
@NgModule({declarations: ROUTER_DIRECTIVES, exports: ROUTER_DIRECTIVES})
export class RouterModule {
  constructor(@Optional() @Inject(ROUTER_FORROOT_GUARD) guard: any, @Optional() router: Router) {}
  static forChild(routes: Routes): ModuleWithProviders {
    return {ngModule: RouterModule, providers: [provideRoutes(routes)]};
  }
}
```ts
If this thing will not be resolved I will not have any other way just to drop Angular support and stay only in react since this issue with ngc aot is very old.

More than that - when compiling AOT with webpack all works fine, just after upgrading to Angular 5.0.0 ngc-weback plugin is not working any more.

here is complete code of ng-state.module.ts:
```ts
import { Inject, Injector, ModuleWithProviders, NgModule, InjectionToken } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Dispatcher } from './services/dispatcher';
import { Router } from '@angular/router';
import { RouterState } from './state/router-state';
import { ServiceLocator } from './helpers/service-locator';
import { State } from './state/state';
import { StateHistory } from './state/history';
import { StateHistoryComponent } from './state/state-history';
import { Store } from './store/store';

export const INITIAL_STATE = new InjectionToken('INITIAL_STATE');
export const COLLECT_HISTORY = new InjectionToken('COLLECT_HISTORY');
export const STORE_HISTORY_ITEMS = new InjectionToken('STORE_HISTORY_ITEMS');
export const IS_PROD = new InjectionToken('IS_PROD');

export function stateFactory(initialState) {
    return new State(initialState);
}

export function storeFactory(state: State<any>) {
    return new Store(state);
}

export function historyFactory(store: Store<any>) {
    return new StateHistory(store);
}

export function routerStateFactory(store: Store<any>, router: Router) {
    return new RouterState(store, router);
}

@NgModule({
    imports: [CommonModule],
    declarations: [StateHistoryComponent],
    exports: [StateHistoryComponent]
})
export class StoreModule {
    static provideStore(initialState: any, isProd?: boolean, collectHistory?: boolean, storeHistoryItems?: number): ModuleWithProviders {
        return {
            ngModule: StoreModule,
            providers: [
                { provide: STORE_HISTORY_ITEMS, useValue: storeHistoryItems },
                { provide: COLLECT_HISTORY, useValue: collectHistory },
                { provide: INITIAL_STATE, useValue: initialState },
                { provide: IS_PROD, useValue: isProd },
                { provide: State, useFactory: stateFactory, deps: [INITIAL_STATE] },
                { provide: Store, useFactory: storeFactory, deps: [State] },
                { provide: StateHistory, useFactory: historyFactory, deps: [Store, INITIAL_STATE] },
                { provide: RouterState, useFactory: routerStateFactory, deps: [Store, Router] },
                Dispatcher
            ]
        };
    }

    constructor(
        injector: Injector,
        stateHistory: StateHistory,
        routerState: RouterState,
        @Inject(INITIAL_STATE) initialState: any,
        @Inject(STORE_HISTORY_ITEMS) storeHistoryItems: any,
        @Inject(COLLECT_HISTORY) collectHistory: any,
        @Inject(IS_PROD) isProd: any
    ) {
        if (storeHistoryItems !== undefined) {
            StateHistory.collectHistory = collectHistory;
        }

        if (collectHistory !== undefined) {
            StateHistory.storeHistoryItems = storeHistoryItems;
        }

        ServiceLocator.injector = injector;
        stateHistory.init(initialState);
        routerState.init();

        if (!isProd) {
            (<any>window).state = StateHistory;
        }
    }
}
```

**Comment by Ismaestro** [comment] 2018-01-12 12:47
Check [this](https://stackoverflow.com/questions/48225993/angular-call-function-in-forroot-method). Maybe it can help!

**Comment by andreimcristof** [comment] 2018-02-13 12:50
Hi, I have the same error. Working fine without aot, throwing the following error with `ng build --aot`
Error during template compile of 'AppModule'

> Function calls are not supported in decorators but '[provider_here]' was called.

This is after I made a class that implements FactoryProvider from angularcore, But production needs aot. This provider is intended to just run a function on APP_INITIALIZER to fetch the user config - basic stuff which, again, works when building without aot. 

As I see, this issue has been reported initially on Feb 24, 2017 . Today is the 13th of February, 2018. With all due respect, are we waiting for Elon Musk to reach Mars before we actually do prioritize investigating this?

**Comment by mlc-mlapis** [comment] 2018-02-13 13:44
@andreimcristof ... do you have any extra reason to use the following syntax even in the main app module?
```
export class AppModule {
	static forRoot(): ModuleWithProviders {
		return {
			ngModule: AppModule,
			providers: [
				...
			]
		};
	}
}
```

**Comment by trotyl** [comment] 2018-02-13 13:54
> As I see, this issue has been reported initially on Feb 24, 2017 . Today is the 13th of February, 2018. 

@andreimcristof Please note that there has never been a valid repro provided in the entire thread, and most of them are just obvious symlink issue there has nothing to do within this repo.

**Comment by andreimcristof** [comment] 2018-02-13 18:04
@mlc-mlapis I am actually _not_ using that pattern, however I got an almost identical error:

> function calls are not supported ...

and all google searches pointed to this thread.

@trotyl Thanks for the input. It's quite simple to reproduce actually: basically I made a class that implements FactoryProvider e.g. 
`export class MyProvider implements FactoryProvider` , provided that in the APP_INITIALIZER, 
, and in the providers of app.module I said
providers: [ new MyProvider() ]
and that gives the error. 
I will provide a repro repository this weekend, to prove it. 
now, I do know that I know only 1% of the Angular that you know since you work on the Angular team, but correct me if I'm wrong, but I expect some consistency - if it was a bad implementation, why did it build successful on non-aot build and fails only on `ng build --aot` ? That's what frustrates me, because if it didn't work at all, then I would say "ok, it's my fault I need to read the docs better".

**Comment by mlc-mlapis** [comment] 2018-02-13 18:33
@andreimcristof ... ah OK, but you should use exported function ... like the following pattern:
```
export function appConfigServiceFactory(config: AppConfig): () => void {
	return () => config.load();
}
```
```
@NgModule({
	...
	providers: [
		AppConfig,
		{
			provide: APP_INITIALIZER,
			useFactory: appConfigServiceFactory,
			deps: [AppConfig],
			multi: true
		},
		...
	],
	bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by trotyl** [comment] 2018-02-14 01:50
@andreimcristof No, I'm a normal user as well.

This thread has been filled with all different kinds of questions, like all people reporting an `undefined is not a function` error, but they're never refer to the same thing.

For your case, there're known design limits for static metadata collecting, your case is not yet supported, please try solution provided by @mlc-mlapis .

**Comment by mflorence99** [comment] 2018-03-05 16:56
FWIW I had this issue and did not understand it because my feature libraries appeared to be identical to others (eg: ngrx) that the AoT compiler did not complain about. As in:

```ts
  imports: [
    MyFeatureModule.forRoot(), // <----- FAILED
    EffectsModule.forRoot([
      ControlEffects,
      HeadsUpEffects,
      PartnerEffects
    ]),
    RouterModule.forRoot(ROUTES, { useHash: true }), // <----- WORKS
    StoreRouterConnectingModule,
    StoreModule.forRoot(reducers) // <----- WORKS
  ],
```

I discovered I had not been building my libraries correctly. I had not been emitting `*.metadata.json` files. Once I changed my `tsconfig.json` appropriately, my AoT issues went away.

```
{
  "angularCompilerOptions": {
    "genDir": "./dist",
    "skipMetadataEmit": false, // <------- WAS PREVIOUSLY true
    "skipTemplateCodegen": true
  },
  ...
}
```

**Comment by RadouaneRoufid** [comment] 2018-03-27 09:51
My feature module didn't satisfied this rule :` Your static function in the module class can only have 1 statement, and that statement has to be a return.`

**Comment by sojimon** [comment] 2018-03-29 06:34
@almgwary How can be enable function and object?

**Comment by anarckk** [comment] 2018-04-03 05:03
我的终于可用了。
参考  https://www.angular.cn/guide/singleton-services
forRoot直接是return语句的话就可用。forRoot如果中间有别的语句就会报错。

**Comment by Johanneke** [comment] 2018-09-05 14:32
@mlc-mlapis your suggestion of using an exported named function works, but shouldn't this be part of the documentation somewhere? The documentation for the FactoryProvider simply states "A function to invoke to create a value for this `token`.", but there is no mention of it having to be a named and exported function... And the error message isn't exactly clear either.

**Comment by mlc-mlapis** [comment] 2018-09-05 17:26
@Johanneke ... the docs could be improved in any time and still there will be some gaps ... 
 😄  but generally, the conditions for AOT compilation are concentrated mainly here https://angular.io/guide/aot-compiler and if we talk about arrow functions then https://angular.io/guide/aot-compiler#no-arrow-functions.

**Comment by Johanneke** [comment] 2018-09-06 08:36
But if arrow functions are never allowed there, can you explain why this works:
```
@NgModule({
  providers: [
    {
      provide: LOCALE_ID,
      deps: [LocaleService],
      useFactory: (localeService: LocaleService):
        string => localeService.locale
    }
  ]
})
```
and this does not:
```
@NgModule({})
export class ServiceModule {
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: ServiceModule,
      providers: [
        {
          provide: EmailValidator,
          useFactory: ():
            EmailValidator => new EmailValidator()
        }
      ]
    };
  }
```
To me, it seems like the exact same syntax, but in `forRoot` I am required to use the non-arrow function syntax for AOT, and in `NgModule` it doesn't matter.

**Comment by benwinding** [comment] 2019-02-20 00:35
For anyone trying to get `SomeModule.forRoot(config)` to work, check that you're not using `console.log(config)` in the constructor. That was my issue....

**Comment by shprink** [comment] 2019-03-13 10:31
Same as @benwinding 😱

```
export class ForgerockMainLayoutModule {
  static forRoot(config: ForgerockMainLayoutConfig) {
    // console.log({ config }); <- Prod build fails if uncommented 

    return {
      ngModule: ForgerockMainLayoutModule,
      providers: [
        { provide: ForgerockMainLayoutConfigToken, useValue: config.layout },
        { provide: ForgerockMainLayoutNavigationToken, useValue: config.navigation }
      ]
    };
  }
}
```

**Comment by BhavinPatel04** [comment] 2019-03-26 17:41
If it helps anyone, the below worked for me and I was successfully able to build for AOT

````
@Injectable({
  providedIn: "root"
})
export class SomeService { }
````

As mentioned in [docs](https://angular.io/guide/singleton-services#providing-a-singleton-service)

**Comment by HighSoftWare96** [comment] 2019-10-11 13:56
In my `forRoot` I was declaring a variable. Removing that solved the issue.

**Comment by JoostK** [comment] 2020-03-14 23:42
This issue is a thing of the past with Ivy. Because the `ModuleWithProviders` type has gained a generic type parameter, the compiler doesn't have to introspect the actual code to figure out what module to use.

**Closed by JoostK** 2020-03-14 23:42 UTC
Labels: comp: compiler, comp: core, core: NgModule, fixed by Ivy, freq2: medium, severity3: broken, type: bug/fix
