### ISSUE TITLE
Upgrade v9 → v10 : Pre-rendering → TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by mazlano27** [angular/angular#37725] opened 2020-06-25 05:17 UTC
# 🐞 bug report

### Is this a regression?

Before upgrading to Angular 10 from Angular 9, pre-rendering was working normally.

### Description

After updating to Angular 10 using ng update, the pre-rendering script throws an error.

## 🔬 Minimal Reproduction

Please find the repro here → https://github.com/mazlano27/repro-app-v10

package.json script to pre-render →
<pre><code>

"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "webpack:prerender": "webpack --config webpack.prerender.config.js",
    "build:prerender": "node dist/myDayPwaApp/prerender.js",
    "serve:prerender": "http-server dist/myDayPwaApp -o",
    "build:all": "ng build --prod --stats-json && ng run myDayPwaApp:server && npm run webpack:prerender && npm run build:prerender",
    "bundle-report": "webpack-bundle-analyzer dist/myDayPwaApp/stats.json"
  }
</code></pre>

prerender.ts →
<pre><code>

// Load zone.js for the server.
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import {join, resolve} from 'path';

(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xhr2');

import {enableProdMode} from '@angular/core';

import * as fs from 'fs-extra';

// Add routes manually that you need rendered
const ROUTES = [
  '/',
  '/privacy-policy',
  '/demo-request',
  '/auth/login',
  '/auth/register',
  '/auth/forgotten-password'
];

const APP_NAME = 'myDayPwaApp';

// leave this as require(), imported via webpack
const {
  AppServerModule,
  renderModule
} = require(`./dist/${APP_NAME}-server/main`);

enableProdMode();

async function prerender() {
  // Get the app index
  const browserBuild = `dist/${APP_NAME}`;
  const index = await fs.readFile(join(browserBuild, 'index.html'), 'utf8');

  // Loop over each route
  for (const route of ROUTES) {
    try {
      console.log(route);
      const pageDir = join(browserBuild, route);
      await fs.ensureDir(pageDir);

      // Render with Universal
      const html = await renderModule(AppServerModule, {
        document: index,
        url: route,
      });

      await fs.writeFile(join(pageDir, 'index.html'), html);
    } catch (e) {
      console.log('MAJOR ERROR IN PRERENDER=> ', e);
    }
  }

  await fs.copySync(resolve(`dist/${APP_NAME}/index.html`), `dist/${APP_NAME}/404.html`);

  console.log('done');
  process.exit();
}

prerender();

</code></pre>

webpack.prerender.config.ts →

<pre><code>

const path = require('path');
const webpack = require('webpack');

const APP_NAME = 'myDayPwaApp';

module.exports = {
  entry: {prerender: './prerender.ts'},
  resolve: {extensions: ['.js', '.ts']},
  mode: 'development',
  target: 'node',
  externals: [/(node_modules|main\..*\.js)/],
  output: {
    path: path.join(__dirname, `dist/${APP_NAME}`),
    filename: '[name].js'
  },
  module: {
    rules: [
      {test: /\.ts$/, loader: 'ts-loader'}
    ]
  },
  plugins: [
    new webpack.ContextReplacementPlugin(
      /(.+)?angular(\\|\/)core(.+)?/,
      path.join(__dirname, 'src'), // location of your src
      {} // a map of your routes
    ),
    new webpack.ContextReplacementPlugin(
      /(.+)?express(\\|\/)(.+)?/,
      path.join(__dirname, 'src'),
      {}
    )
  ]
}

</code></pre>
## 🔥 Exception or Error
<pre><code>

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (webpack:///./dist/myDayPwaApp-server/main.js?:26:30)
    at Function.requireEnsure [as e] (webpack:///./dist/myDayPwaApp-server/main.js?:45:25)
    at loadChildren (webpack:///./dist/myDayPwaApp-server/main.js?:157033:96)
    at RouterConfigLoader.loadModuleFactory (webpack:///./dist/myDayPwaApp-server/main.js?:109777:39)
    at RouterConfigLoader.load (webpack:///./dist/myDayPwaApp-server/main.js?:109763:37)
    at MergeMapSubscriber.eval [as project] (webpack:///./dist/myDayPwaApp-server/main.js?:108843:46)
    at MergeMapSubscriber._tryNext (webpack:///./dist/myDayPwaApp-server/main.js?:149286:27)
    at MergeMapSubscriber._next (webpack:///./dist/myDayPwaApp-server/main.js?:149276:18)
    at MergeMapSubscriber.next (webpack:///./dist/myDayPwaApp-server/main.js?:144572:18)
    at Observable.eval [as _subscribe] (webpack:///./dist/myDayPwaApp-server/main.js?:153991:20)
    at resolvePromise (webpack:///./node_modules/zone.js/dist/zone-node.js?:836:39)
    at resolvePromise (webpack:///./node_modules/zone.js/dist/zone-node.js?:788:21)
    at eval (webpack:///./node_modules/zone.js/dist/zone-node.js?:898:21)
    at ZoneDelegate.invokeTask (webpack:///./node_modules/zone.js/dist/zone-node.js?:425:35)
    at Object.onInvokeTask (webpack:///./dist/myDayPwaApp-server/main.js?:79808:33)
    at ZoneDelegate.invokeTask (webpack:///./node_modules/zone.js/dist/zone-node.js?:424:40)
    at Zone.runTask (webpack:///./node_modules/zone.js/dist/zone-node.js?:192:51)
    at drainMicroTaskQueue (webpack:///./node_modules/zone.js/dist/zone-node.js?:605:39) {
  rejection: TypeError: Cannot read property 'call' of undefined
      at __webpack_require__ (webpack:///./dist/myDayPwaApp-server/main.js?:26:30)
      at Function.requireEnsure [as e] (webpack:///./dist/myDayPwaApp-server/main.js?:45:25)
      at loadChildren (webpack:///./dist/myDayPwaApp-server/main.js?:157033:96)
      at RouterConfigLoader.loadModuleFactory (webpack:///./dist/myDayPwaApp-server/main.js?:109777:39)
      at RouterConfigLoader.load (webpack:///./dist/myDayPwaApp-server/main.js?:109763:37)
      at MergeMapSubscriber.eval [as project] (webpack:///./dist/myDayPwaApp-server/main.js?:108843:46)
      at MergeMapSubscriber._tryNext (webpack:///./dist/myDayPwaApp-server/main.js?:149286:27)
      at MergeMapSubscriber._next (webpack:///./dist/myDayPwaApp-server/main.js?:149276:18)
      at MergeMapSubscriber.next (webpack:///./dist/myDayPwaApp-server/main.js?:144572:18)
      at Observable.eval [as _subscribe] (webpack:///./dist/myDayPwaApp-server/main.js?:153991:20),
  promise: ZoneAwarePromise [Promise] {
    __zone_symbol__state: 0,
    __zone_symbol__value: TypeError: Cannot read property 'call' of undefined
        at __webpack_require__ (webpack:///./dist/myDayPwaApp-server/main.js?:26:30)
        at Function.requireEnsure [as e] (webpack:///./dist/myDayPwaApp-server/main.js?:45:25)
        at loadChildren (webpack:///./dist/myDayPwaApp-server/main.js?:157033:96)
        at RouterConfigLoader.loadModuleFactory (webpack:///./dist/myDayPwaApp-server/main.js?:109777:39)
        at RouterConfigLoader.load (webpack:///./dist/myDayPwaApp-server/main.js?:109763:37)
        at MergeMapSubscriber.eval [as project] (webpack:///./dist/myDayPwaApp-server/main.js?:108843:46)
        at MergeMapSubscriber._tryNext (webpack:///./dist/myDayPwaApp-server/main.js?:149286:27)
        at MergeMapSubscriber._next (webpack:///./dist/myDayPwaApp-server/main.js?:149276:18)
        at MergeMapSubscriber.next (webpack:///./dist/myDayPwaApp-server/main.js?:144572:18)
        at Observable.eval [as _subscribe] (webpack:///./dist/myDayPwaApp-server/main.js?:153991:20)
  },
  zone: Zone {
    _parent: Zone {
      _parent: null,
      _name: '<root>',
      _properties: {},
      _zoneDelegate: [ZoneDelegate]
    },
    _name: 'angular',
    _properties: { isAngularZone: true, maybeDelayChangeDetection: false },
    _zoneDelegate: ZoneDelegate {
      _taskCounts: [Object],
      zone: [Circular],
      _parentDelegate: [ZoneDelegate],
      _forkZS: null,
      _forkDlgt: null,
      _forkCurrZone: null,
      _interceptZS: null,
      _interceptDlgt: null,
      _interceptCurrZone: null,
      _invokeZS: [Object],
      _invokeDlgt: [ZoneDelegate],
      _invokeCurrZone: [Circular],
      _handleErrorZS: [Object],
      _handleErrorDlgt: [ZoneDelegate],
      _handleErrorCurrZone: [Circular],
      _scheduleTaskZS: [Object],
      _scheduleTaskDlgt: [ZoneDelegate],
      _scheduleTaskCurrZone: [Circular],
      _invokeTaskZS: [Object],
      _invokeTaskDlgt: [ZoneDelegate],
      _invokeTaskCurrZone: [Circular],
      _cancelTaskZS: [Object],
      _cancelTaskDlgt: [ZoneDelegate],
      _cancelTaskCurrZone: [Circular],
      _hasTaskZS: [Object],
      _hasTaskDlgt: [ZoneDelegate],
      _hasTaskDlgtOwner: [Circular],
      _hasTaskCurrZone: [Circular]
    }
  },
  task: ZoneTask {
    _zone: Zone {
      _parent: [Zone],
      _name: 'angular',
      _properties: [Object],
      _zoneDelegate: [ZoneDelegate]
    },
    runCount: 0,
    _zoneDelegates: null,
    _state: 'notScheduled',
    type: 'microTask',
    source: 'Promise.then',
    data: ZoneAwarePromise [Promise] {
      __zone_symbol__state: 0,
      __zone_symbol__value: TypeError: Cannot read property 'call' of undefined
          at __webpack_require__ (webpack:///./dist/myDayPwaApp-server/main.js?:26:30)
          at Function.requireEnsure [as e] (webpack:///./dist/myDayPwaApp-server/main.js?:45:25)
          at loadChildren (webpack:///./dist/myDayPwaApp-server/main.js?:157033:96)
          at RouterConfigLoader.loadModuleFactory (webpack:///./dist/myDayPwaApp-server/main.js?:109777:39)
          at RouterConfigLoader.load (webpack:///./dist/myDayPwaApp-server/main.js?:109763:37)
          at MergeMapSubscriber.eval [as project] (webpack:///./dist/myDayPwaApp-server/main.js?:108843:46)
          at MergeMapSubscriber._tryNext (webpack:///./dist/myDayPwaApp-server/main.js?:149286:27)
          at MergeMapSubscriber._next (webpack:///./dist/myDayPwaApp-server/main.js?:149276:18)
          at MergeMapSubscriber.next (webpack:///./dist/myDayPwaApp-server/main.js?:144572:18)
          at Observable.eval [as _subscribe] (webpack:///./dist/myDayPwaApp-server/main.js?:153991:20)
    },
    scheduleFn: undefined,
    cancelFn: undefined,
    callback: [Function],
    invoke: [Function]
  }
}

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.0.0
Node: 12.16.1
OS: darwin x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1000.0
@angular-devkit/build-angular              0.1000.0
@angular-devkit/build-optimizer            0.1000.0
@angular-devkit/build-webpack              0.1000.0
@angular-devkit/core                       10.0.0
@angular-devkit/schematics                 10.0.0
@angular/fire                              6.0.2
@ngtools/webpack                           10.0.0
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        10.0.0
@schematics/update                         0.1000.0
rxjs                                       6.5.5
typescript                                 3.9.5
webpack                                    4.43.0

</code></pre>

**Comment by JoostK** [comment] 2020-06-25 06:26
Hi @mazlano27, unfortunately the issue description does not provide sufficient information for us to determine the cause of your issue. Can you share a minimal reproduction, e.g. a public Github repo and the commands that we need to run to reproduce the issue?

**Comment by mazlano27** [comment] 2020-06-25 07:26
> Hi @mazlano27, unfortunately the issue description does not provide sufficient information for us to determine the cause of your issue. Can you share a minimal reproduction, e.g. a public Github repo and the commands that we need to run to reproduce the issue?

@JoostK Please find the repro here for your review → https://github.com/mazlano27/repro-app-v10

Please run npm run build:all to init the build & pre-rendering script

**Comment by alan-agius4** [comment] 2020-06-25 12:08
Hi @mazlano27, 

This is happening because now the root level `tsconfig.json` is used as a solution style TypeScript configuration, the previous `tsconfig.json` was renamed to `tsconfig.base.json`. This is configuration is being picked up by `ts-loader` which is unable to transpile the application correctly using that.

You'll need to provide a `tsconfig.base.json` to ts-loader. See more https://github.com/TypeStrong/ts-loader. And also, since you are not using the prerendering solutions from https://github.com/angular/universal you'll also need to change the module target of the server application in `tsconfig.server.json` to CommonJS.

Closing this issue since custom Webpack configurations are not supported by the Angular tooling team.

**Closed by alan-agius4** 2020-06-25 12:08 UTC
Labels: state: Needs repro

**Comment by mazlano27** [comment] 2020-06-25 13:51
> Hi @mazlano27,
> 
> This is happening because now the root level `tsconfig.json` is used as a solution style TypeScript configuration, the previous `tsconfig.json` was renamed to `tsconfig.base.json`. This is configuration is being picked up by `ts-loader` which is unable to transpile the application correctly using that.
> 
> You'll need to provide a `tsconfig.base.json` to ts-loader. See more https://github.com/TypeStrong/ts-loader. And also, since you are not using the prerendering solutions from https://github.com/angular/universal you'll also need to change the module target of the server application in `tsconfig.server.json` to CommonJS.
> 
> Closing this issue since custom Webpack configurations are not supported by the Angular tooling team.

Hey @alan-agius4 ,

Thanks for your response. I did the two things you've suggested - namely:

1) Provide tsconfig.base.json to ts-loader by updating the entry in the webpack.prerender.config.js 

`module: {
    rules: [
      {
        test: /\.ts$/,
        loader: 'ts-loader',
        options: {
          configFile: './tsconfig.base.json'
        }
      }
    ]
  },`

2) Changed the module target of the server application in the tsconfig.server.json to CommonJS

The error persists. Please could you point me in the right direction? I understand custom Webpack configurations are not supported by the Angular tooling team and would appreciate any assistance you can spare. Thank you
