### ISSUE TITLE
FormControl classes are not fully reactive

### ISSUE THREAD

**Issue by SebastianStehle** [angular/angular#26522] opened 2018-10-17 17:19 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

The form control classes are nice and very often you can use them in OnPush components, thanks to the observables like `valueChanges` and `statusChanges`. But it has not been fully implemented.

I am missing:

1. AbstractControl

* `touchChanges: Obserable<boolean>`
* `pristineChanges: Obserbable<boolean>`

2. FormGroup / FormArray

* `collectionChanges: Observable<?>`

For me it prevents some OnPush scenarios and I had to add some ugly hacks.

**Comment by kara** [comment] 2018-10-25 22:20
Duplicate of https://github.com/angular/angular/issues/10887

**Closed by kara** 2018-10-25 22:20 UTC
Labels: comp: forms

**Comment by javix** [comment] 2018-12-12 09:48
This issue was closed with a reference to #10887, but also #10887 was closed with a reference to this issue. 
Is not it strange?
