### ISSUE TITLE
Overridden component classes and @Input() properties

### ISSUE THREAD

**Issue by baio** [angular/angular#5794] opened 2015-12-10 13:27 UTC
Some subtle bug
```
export class BaseComp { 
    @Input() val: any;
    ...
}

@Component(...)
export class Comp extends BaseComp { 
    //@Input() val: any; 

   //@Output() evt = new EventEmitter(); <----
  //If uncomment this one, you have to uncomment also  @Input ... line, overwise 
  // component wouldn't see `val` variable
    ...
   ngOnInit() {
     console.log("I see ya, all fine, but try uncomment @Output ",  this.val);
   }
}

```

**Comment by vicb** [comment] 2015-12-10 17:09
What exactly is your pb ?

**Comment by vicb** [comment] 2015-12-10 17:10
`@input()`s are not inherited by design.

**Comment by zoechi** [comment] 2016-02-25 15:06
dup of #5415

**Comment by pkozlowski-opensource** [comment] 2016-10-04 12:16
Duplicate of #11606

**Closed by pkozlowski-opensource** 2016-10-04 12:16 UTC
