### ISSUE TITLE
<inputs> with a formControlName lose their `value` when `type` is set from interpolation or binding

### ISSUE THREAD

**Issue by seeplusplus** [angular/angular#46742] opened 2022-07-07 17:23 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I haven't figured out _all_ of the scenarios in which this breaks, but the title sums it up pretty accurately. If `type` is specified on an input from an interpolation then `value` seems to get nulled out. This isn't specific to interpolations either, I've tried changing it to a `[type]` binding, as well as changing `formControlName` and `value` to binding syntax as well, all to the same result.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zqch6y?file=src/app/app.component.css

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.x
```

**Comment by pkozlowski-opensource** [comment] 2022-07-07 17:46
I believe that this is a duplicate or at least related to #13243

**Comment by AndrewKushnir** [comment] 2022-07-07 18:13
Closing as a duplicate of https://github.com/angular/angular/issues/13243.

**Closed by AndrewKushnir** 2022-07-07 18:13 UTC
Labels: comp: forms
