### ISSUE TITLE
Entire website is broken

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular#21897] opened 2018-01-30 15:21 UTC
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/4531036/35574210-18a695fe-05d1-11e8-9014-b5007e91d060.png)

## Expected behavior

What is looked like before...

## Minimal reproduction of the problem with instructions

Go to https://angular.io/

## What is the motivation / use case for changing the behavior?

Readability 

## Referances

#21889

**Comment by mansoorsiddiqui** [comment] 2018-01-30 16:00
Website shows up fine for me

**Comment by gkalpak** [comment] 2018-01-30 16:14
Closing as duplicate of #21889. Some users are affected and others not. Working on figuring out the root cause.

**Closed by gkalpak** 2018-01-30 16:14 UTC
