### ISSUE TITLE
[feat] Export `formatDate` and other format methods

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#21199] opened 2017-12-28 14:37 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
At the moment in order to format a date, I need to include a library like moment, and will have to include it's locals as well. 

Angular are already using CLDR locals, so in theory it's double the data for nothing, however non of the format methods are being exported like this;
https://github.com/angular/angular/blob/2e7e935b028784efdced34104964dad74b455fbf/packages/common/src/i18n/format_date.ts#L45

Is there any reason why they are internal and not exported?

## What is the motivation / use case for changing the behavior?
Don't want to include an addition library to format my dates when Angular can do it.

## Environment

<pre><code>
Angular version: 5.1.2

**Comment by Toxicable** [comment] 2017-12-28 20:44
duplicate of https://github.com/angular/angular/issues/20536

**Closed** 2017-12-28 20:55 UTC
