### ISSUE TITLE
Change detection stops working on Cordova

### ISSUE THREAD

**Issue by artuska** [angular/angular#22476] opened 2018-02-27 15:58 UTC
Change detection stops working if the Cordova application:

- goes to the background;
- opens via the Push Notification click on mobile phone.

For example, I have a social authorization via the native mobile Facebook application on iPhone. When I click on authorization button Facebook application opens and my application goes to the background, when authorization is finished my application goes back to the foreground, but change detection stops working — if there are some `(click)` events on some buttons they will run fine, but HTML code will not update — for example, `[ngClass]` will not change classes, etc. 

## Environment
<pre><code>Angular version: 5.2.1

Browser:
- [x] iOS webView browser

For Tooling issues:
- Platform: iOS, Cordova
</code></pre>

**Comment by JiaLiPassion** [comment] 2018-02-27 16:02
@artuska , this should be a `zone.js` issue, could you post a reproduce repo?

**Comment by artuska** [comment] 2018-02-27 16:06
@JiaLiPassion ugh, unfortunatelt, that is just not possible for me to make a repro repo.

**Comment by artuska** [comment] 2018-02-27 19:15
Duplicated this issue in `zone.js` also.

**Comment by Itrulia** [comment] 2018-02-27 22:00
Can't reproduce this in our app.

**Comment by alexeagle** [comment] 2018-02-28 02:24
@JiaLiPassion I think the zone.js dupe of the bug is more actionable, since you're pretty sure the bug is there. 
Closing this, please re-open if I'm wrong

**Closed by alexeagle** 2018-02-28 02:24 UTC
