### ISSUE TITLE
Single page routing not working after BrowserAnimationModule or NoopAnimationModule are added to the app

### ISSUE THREAD

**Issue by dubdub37** [angular/angular#19158] opened 2017-09-12 15:13 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Whenever I add BrowserAnimationsModule or NoopAnimationsModule my application will stop loading the routes as a single page. The routes will load but they will just load on top of each other. For instance If I keep clicking on a button that is supposed to open a new single page component it just loads that component ontop of the other. If I keep clicking the page will get longer and longer.

## Expected behavior

Desired behavior would be that the selected component opens as a single page as normal. This issue only manifests itself when the BrowserAnimationModule are added in my app.module.ts

## What is the motivation / use case for changing the behavior?

needs to load as a single page application for it to work. 

## Environment

<pre><code>
Angular version: 4.3.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:   Windows

Others:

</code></pre>
running locally on my computer

**Comment by dubdub37** [comment] 2017-09-12 15:56
It was caused by data I was displaying  through my service.

**Comment by dubdub37** [comment] 2017-09-12 16:11
Nevermind it is still happening. No matter how I display my data in a specific component my routes don't change they just stack on top of each other. Almost as if some route is not being killed.

**Comment by jotatoledo** [comment] 2017-09-12 18:52
Plnkr?

**Comment by sean1504** [comment] 2017-09-13 07:45
I'm also getting this issue.

**Comment by ramadurgarao** [comment] 2017-09-18 13:44
This issue occurring when our application imported BrowserAnimationModule or NoopAnimationModule and if we get any exception while routing (that might be data issue or any other exception in ngOnInit).  This issue is not happening when we don't import the BrowserAnimationModule and NoopAnimationModule

**Comment by Agrumas** [comment] 2017-09-21 09:37
Duplicate of #19093

**Comment by jasonaden** [comment] 2017-11-30 21:19
Closing as a duplicate.

**Closed by jasonaden** 2017-11-30 21:19 UTC
Labels: comp: animations, comp: router, freq3: high, severity3: broken
