### ISSUE TITLE
angular packages are installed wrongly

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular#45208] opened 2022-02-26 17:25 UTC
### Which @angular/* package(s) are the source of the bug?

compiler-cli, core, router

### Is this a regression?

Yes

### Description

I created a node project that includes an Angular workspace, the project structure looks like:

/package.json
```
{
 "name": "root",
  "workspaces": ["./child"]
}
```

/child/package.json
```
{
  "name": "child",
  "dependencies": {
    "@angular/compiler": "^13.1.2",
    "@angular/router": "^13.1.2"
  }
}
```
 
when running `npm install` it installs `@angular/compiler` in the root node_modules dir which is the expected behavior.
but it installs `@angular/router` in child/node_modules, it should be installed in the root node_modules

also, the dependencies of it such as `rxjs` are installed in the child dir even no other versions of the same packages 

the project is created in a clean and empty folder, and I cleared the npm cache

[minimal reproduction](https://github.com/eng-dibo/issue-npm-install)
run `npm install`

### Please provide a link to a minimal reproduction of the bug

https://github.com/eng-dibo/issue-npm-install

### Please provide the exception or error you saw

```true
@angular packages are installed in the child directory instead of the root dir.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 16.14.0
Package Manager: npm 8.3.1
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.3
@angular-devkit/core         13.1.3
@angular-devkit/schematics   13.1.3
@schematics/angular          13.1.3
typescript                   4.5.4
webpack                      5.66.0
```

**Comment by JoostK** [comment] 2022-02-26 19:36
Package hoisting is implemented by package managers, not Angular itself. Yarn does not inhibit this same behaviour, and the node_modules structure as chosen by NPM is a valid configuration that satisfies the package requests, so I don't think this is even necessarily a bug in NPM.

**Comment by alan-agius4** [comment] 2022-02-26 19:53
As @JoostK correctly pointed out, this is not caused by Angular.

As such, I am closing this issue.

**Closed by alan-agius4** 2022-02-26 19:53 UTC
