### ISSUE TITLE
API reference docs should contain links to other API items they refer to

### ISSUE THREAD

**Issue by daiscog** [angular/angular#57184] opened 2024-07-29 14:54 UTC
### Describe the problem that you experienced

The new API reference documentation on angular.dev is difficult to navigate around because other items referred to in the documented API of something are not links.

As a simple example, the documentation for [`AsyncValidatorFn`](https://angular.dev/api/forms/AsyncValidatorFn) references the other API items `AbstractControl` and `ValidationErrors`, but to see the documentation for those, I have to manually search for them.

It would be much easier to navigate through the docset if all occurrences of a name of an item that is also part of Angular's public API in the documentation are links to the documentation for that item.  This should be the case everywhere in the docset - including, but not limited to, the API tab, the description tab, and the details sidebar.

### Enter the URL of the topic with the problem

E.g., https://angular.dev/api/forms/AsyncValidatorFn

**Comment by JeanMeche** [comment] 2024-07-29 15:08
Duplicate of #57128

**Closed by JeanMeche** 2024-07-29 15:08 UTC
