### ISSUE TITLE
Parameters (and data) only available in the component target

### ISSUE THREAD

**Issue by felipedrumond** [angular/angular#11023] opened 2016-08-23 22:22 UTC
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a parametrized route which targets a component, only this component can access those parameters.

**Expected/desired behavior**
It might be necessary to read the parameters in other components.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Consider the following route configuration

```
export const routes: RouterConfig = [
 { path: 'confirmation/:hashID', component: ConfirmationComponent, canActivate: [AuthGuard] },
];

```

Consider the following code as part of the ConfirmationComponent

```
this.activatedRoute.params.subscribe(params => {
            var hashID = params['hashID'];
        },
```

If I use the above code in any other component, hashID won't be available. It is necessary to read location.path() and extract the hashID value.

**What is the expected behavior?**
Although I understand that the targeted component it the ConfirmationComponent, sometimes other components might need to have access to the parameters explicitly written in the URL.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [all | **TypeScript 1.8** | ES6/7 | **ES5**]

**Comment by brandonroberts** [comment] 2016-08-23 22:55
Are you talking about components inside the ConfirmationComponent template?

**Comment by felipedrumond** [comment] 2016-08-23 23:15
Hi @brandonroberts, not exactly.
My app.component.html has the following structure:

```
<header></header>
<router-outlet></router-outlet>
<footer></footer>
```

My header.component would like to know the parameters "hashID" sent to the ConfirmationComponent. The only way I found to read it was reading location.path().

**Comment by brandonroberts** [comment] 2016-08-23 23:40
Ok. You should use a shared service that stores the `hashID` and you set that hashID from within your ConfirmationComponent. You share the same service with your header/footer/whatever and they have access to the hashID.

**Comment by vicb** [comment] 2016-08-25 04:52
@brandonroberts is this a bug ?

**Comment by felipedrumond** [comment] 2016-08-25 11:33
@vicb I don't think so. When your app discover which route you are accessing, your app instantiates that component's route and send your params to that component. As @brandonroberts said, a good strategy for having access to that parameters is to share them via a shared service.

**Comment by tinchou** [comment] 2016-09-01 22:44
I think this is a bug. I have a `ShopComponent`, which receives a shared `SongsStore` service in its constructor.

If I receive an `ActivatedRoute` in the service the params are empty:

```ts
class SongsStore {
    constructor(
        private route: ActivatedRoute) {
        console.log("store", route.snapshot.params); // empty
    }
```

But if I do it in the component they aren't:

```ts
class ShopComponent {
    constructor(
        private store: SongsStore,
        private route: ActivatedRoute) {
        console.log("shop", route.snapshot.params); // not empty
    }
```

I believe this was working on RC4 or RC5.

Is there another recommended strategy? Maybe sending the params to the service from the instantiated component?

**Comment by u12206050** [comment] 2016-09-05 06:20
It depends where your service is initiated. But since a service is usually a singleton, thus being constructed once, there won't be any route for it to make use of.

Better way will to have a private property 'route' with setter and getter, whereby you can set the route from within any component using the service.

Better yet, in your main app.component.ts you could set the route of your service every time on route change.

Even better, subscribe to the params attribute of the route within your service like so:

class SongsStore {
    constructor(
        private route: ActivatedRoute) {
        this.route.params.subscribe(params => {
                console.log("store", params); // should not be empty if there really are params.
        });
    }

**Comment by tinchou** [comment] 2016-09-05 15:22
Last option was what I was using, but it's not working anymore. I
simplified it with the snapshot for the example, but didn't realize it
wouldn't be a good example.

**Comment by felipedrumond** [comment] 2016-09-05 16:26
It seems your code is right, but I'm not sure the params will be available when instantiating you component class (SongsStore). Try reading your params in  ngOnInit.

import { OnInit }  from '@angular/core';

export class SongsStore implements OnInit {  
   this.activatedRoute.params.subscribe(params => {
                console.info('params', params);
            }
}

**Comment by tinchou** [comment] 2016-09-05 16:37
But the store is not a component, and so it doesn't get the onInit
lifecycle event. Right?

**Comment by felipedrumond** [comment] 2016-09-05 16:44
Oh, right! I didn't see that SongsStore is not a Component. In this case, I believe that you will need to make your component send your params to your SongsStore class because the angular router sends the parameters to your activated component, and only it will be able to read those parameters. I had a similar problem here, and it seems that the router shares the params only with the target component.

**Comment by tinchou** [comment] 2016-09-05 16:48
Sounds good, thanks!

**Comment by felipedrumond** [comment] 2016-09-05 17:18
Keep us informed whether you succeeded or not to implement what you want :-)

**Comment by tinchou** [comment] 2016-09-05 17:30
Yes, it's working. I originally subscribed to params changes to update my
UI.

Click Search -> do store.search -> Update URL -> Receive new URL params and
update UI accordingly

Now I'm not depending on the URL so much:

Click Search -> do store.search -> Update URL *and an internal parameters
Observable* -> Receive new params (through the new observable) and update
UI accordingly

I fear I could get out of sync with my URL if things get more complicated,
since I'm not deriving my UI from it now, and only updating it as a side
effect. But for now this will be enough!

**Comment by dancancro** [comment] 2016-09-19 20:17
I'm having this problem too. I'm using Redux and want to access route.params in a side-effect, epic, function that runs in response to dispatched actions. It's a couple degrees separated from any components.
https://github.com/dancancro/rangle-started/blob/scrolltoobjection/src/epics/list.epics.ts#L56

**Comment by alexbyk** [comment] 2016-10-06 23:45
I faced this problem too. And surprisingly I realized that each component gets a different instance of ActivatedRoute. Which is unexpected (because I was sure that DI creates an instance only once and injects  it each time).
I was trying to change a title in the root component:
```
    this.route.data.subscribe((d: Data) => {
      this.title = (d as any).title;
    });
``

But this doesn't work.
I can subscribe to `router.events` but what's then? Should I parse url by myself?

**Comment by brandonroberts** [comment] 2016-10-07 00:08
@alexbyk See https://github.com/angular/angular/issues/9662. You can inject the ActivatedRoute into the root component and access the entire tree of activated routes.

**Comment by alexbyk** [comment] 2016-10-07 00:41
@brandonroberts thanks for pointing me. Examples from that issue are outdated, but at least I got an idea.

**Comment by francosioquim** [comment] 2016-10-07 00:48
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request => Please do not submit support request here, instead  
see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using a parametrized route which targets a component, only this  
component can access those parameters.

**Expected/desired behavior**
It might be necessary to read the parameters in other components.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request  
better with an example, please provide the steps to reproduce and if  
possible a minimal demo of the problem via https://plnkr.co or similar (you  
can use this template as a starting point:  
http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Consider the following route configuration

```
export const routes: RouterConfig = [
  { path: 'confirmation/:hashID', component: ConfirmationComponent,  
canActivate: [AuthGuard] },
];

```
Consider the following code as part of the ConfirmationComponent
```
this.activatedRoute.params.subscribe(params => {
             var hashID = params['hashID'];
         },
```

If I use the above code in any other component, hashID won't be available.  
It is necessary to read location.path() and extract the hashID value.

**What is the expected behavior?**
Although I understand that the targeted component it the  
ConfirmationComponent, sometimes other components might need to have access  
to the parameters explicitly written in the URL.


**What is the motivation / use case for changing the behavior?**


**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

* **Browser:** [**all** | Chrome XX | Firefox XX | IE XX | Safari XX |  
Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX  
UIWebView | iOS XX WKWebView ]

* **Language:** [all | **TypeScript 1.8** | ES6/7 | **ES5**]


-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/11023

**Comment by alexbyk** [comment] 2016-10-07 01:20
I ended up with this solution: https://gist.github.com/alexbyk/0801373112b64bd171721c4b6b23e9e2

In my opinion it's too complex to do such a simple thing.

**Comment by brandonroberts** [comment] 2016-10-07 01:34
@alexbyk there are plans to make setting page titles easier with the router if that's what your goal is but for now that's how you access activated route data outside the component.

**Comment by maxime1992** [comment] 2016-11-03 11:06
Let say we have a sidenav that is never changed by the router.
But our content is dynamically loaded using the router.

From this sidenav, we need to react to router changes so we can update a view within the sidenav.

To make it simple, in that sidenav I'd like to be able to display every route params (even from child routes).

Is that possible ?

**Comment by wendro** [comment] 2016-11-03 15:16
I myself use redux store - and this is my point of coupling for such components. You could couple the components via events there must be common parent to them which can relay the event. If you are asking about how to best perform such component coupling - you are asking about architecture. You would need to notify probably via common parent component or via some external state - knowledge store. 

If you wanna know how to get more information from AdvancedRoute I found myself hacking routers to rebuild properly store (state). You can always traverse up/down routers tree (because it resembles component tree).

For example some SAMPLE code which could show how to traverse and collect params from parents/first children:
prepare(route: ActivatedRoute) {
        // current
        let result: Params = Object.assign({}, route.snapshot.params);;
        // bottom
        let tmp: ActivatedRoute = route.firstChild;
        while(tmp) {
            if(tmp.snapshot && tmp.snapshot.params) {
                result = Object.assign(result, tmp.snapshot.params);
            }
            tmp = tmp.firstChild;
        }
        // up
        tmp = route.parent;
        while(tmp) {
            if(tmp.snapshot && tmp.snapshot.params) {
                result = Object.assign(result, tmp.snapshot.params);
            }
            tmp = tmp.parent;
        }
        return Observable.from([ result ]);
    }

You need to thing if you wanna use the snapshot or play on streams and what you need. Happy route hacking ;)

**Comment by klinki** [comment] 2016-11-30 12:53
I have basically the same problem as @maxime1992 . I want to create breadcrumbs component. But it is currently <s>not possible</s> complicated, because data it gets in ActivatedRouteSnapshot depends on its location in component tree.

I guess I will have to use some workaround similar to one suggested by @wendro .

**Comment by darrenchiu** [comment] 2016-12-10 07:47
absolutely, it would be nice if we can access those route params in service so that we can create a service based on route changes. Then component will be free of route params subscription

**Comment by Sneez** [comment] 2017-01-18 11:52
if you want to wait to render a view before you have your data you can just wrap everything in an ngIf and have it trigger once your data arrives.  It's at least a temporary workaround

**Comment by nischi** [comment] 2017-05-24 09:31
A workaround for me

other.service.ts
```
this.utilService.getAllRouteParams(this.activatedRoute.root.params, this.activatedRoute.root)
      .filter((params: Params) => {
        return [PARAM YOU NEED]
      });
```

util.service.ts
```
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { ActivatedRoute, Params } from '@angular/router';

@Injectable()
export class UtilService {

  constructor() { }

  getAllRouteParams(params: Observable<Params>, route: ActivatedRoute, outlet: string = 'primary'): Observable<Params> {
    let children: ActivatedRoute[] = route.children.filter((c: ActivatedRoute) => {
      return c.outlet === outlet;
    });

    if (children.length) {
      return this.getAllRouteParams(params.merge(children[0].params), children[0], outlet);
    } else {
      return params;
    }
  }
}
```

**Comment by jeneser** [comment] 2017-06-11 14:11
The same problem as @maxime1992 @felipedrumond  .
I found the code [@Sid](https://stackoverflow.com/users/1211329/sid)

```
import { Component } from '@angular/core';
import { Router, ActivatedRoute, Params, RoutesRecognized } from '@angular/router';

export class AppComponent {

    constructor(private route: ActivatedRoute, private router: Router) {

    }

    ngOnInit(): void {
        this.router.events.subscribe(val => {

            if (val instanceof RoutesRecognized) {

                console.log(val.state.root.firstChild.params);

            }
        });

    }
}
```
https://stackoverflow.com/questions/42947133/parent-components-gets-empty-params-from-activatedroute

Good job! 
But, what shall we do? The component and route can free of route params subscription.

>I just want to use ActivatedRoute.

**Comment by hg-egrossman** [comment] 2017-07-03 19:25
+1.

**Comment by dgroh** [comment] 2017-07-13 06:56
In my case I have a wrapper of `Http` service.

This wrapper, wrapps all common headers for our WebApi call.

One header for example should come from the routing URL

That is my code:

```ts
export class HttpClientService {

  private vertragsId;

  constructor(
    private http: Http,
    @Inject(DNN_CONTEXT) private _dnnContext: DnnContext,
    private activatedRoute: ActivatedRoute) {

      this.activatedRoute.paramMap.subscribe((params) => {
        console.log(params); // null
      });
    }

}
```

This `HttpClientService` is in `SharedModule`

**Comment by joostblok** [comment] 2017-08-25 08:18
My workaround:
   The `this.router.events` subscription is so that you get the params every time the router updates, this solves the issue of lazy loaded modules having to first reload the page before the function works.
   
       this.router.events.subscribe((event: any) => {
           let r = this.route
           while (r.firstChild) {
               r = r.firstChild
           }
           r.params.subscribe(params => {
               //do stuff with params['yourParam']
           })
       })

**Comment by robinkedia** [comment] 2017-08-30 06:47
Any update on this feature request?

**Comment by robinkedia** [comment] 2017-08-30 06:58
Somehow this wierd work around works without any code -
http://localhost:4200/protected;dataset=1/app/dashboard;dataset=1

Both my protected and dashboard component now can receive param values.

**Comment by brandonroberts** [comment] 2017-08-30 12:23
@robinkedia that works because you're passing the `dataset` to both routes as parameters.

See [here](https://github.com/angular/angular/issues/11812#issuecomment-325228258) for a solution for using shared components/services and the `ActivatedRoute` to get the parameters.

**Comment by RoyiNamir** [comment] 2018-03-29 18:38
For those who want Angular service which does that : 

```
import {Injectable}                                                        from '@angular/core';
import {ActivatedRoute, NavigationEnd, NavigationExtras, ParamMap, Router} from "@angular/router";
import {RouterExtensions}                                                  from "nativescript-angular/router";
import {NavigationOptions}                                                 from "nativescript-angular/router/ns-location-strategy";
import {Observable}                                                        from "rxjs/Observable";
import {first}                                                             from "rxjs/operators/first";
import {filter}                                                            from "rxjs/operators/filter";
import {map}                                                               from "rxjs/operators/map";
import {switchMap}                                                         from "rxjs/operators/switchMap";
import {unRegisterAndroidOnBack}                                           from "../../utils/view.utils";

@Injectable()
export class RoutingService
    {
        constructor(private routerExtensions: RouterExtensions, private route: ActivatedRoute, private router: Router)
        {
        }
        public getActivatedRouteParameter(paramName: string): Observable<ParamMap>
        {
            return this.router.events.pipe(filter(e => e instanceof NavigationEnd),
                                           map((): ActivatedRoute =>
                                               {
                                                   let route = this.route;
                                                   while (route.firstChild)
                                                       {
                                                           route = route.firstChild;
                                                       }
                                                   return route;
                                               }),
                                           filter((route: ActivatedRoute) => route.outlet === 'primary'),
                                           switchMap((route: ActivatedRoute) => route.paramMap) , first());

        }
```

**Comment by chriszrc** [comment] 2018-04-03 19:34
This is not a real solution, I want to see a better way to see the params from child components from the root component, but this does technically work and allows you to use the router outlet name to get the right outlet (in this case "detail"):

```javascript
let [{path:id},{path:state}] = this.router.parseUrl(this.router.routerState.snapshot.url).root.children.primary.children.detail.segments;
```

So given a url like:

http://localhost:4200/#/map/(detail:123/NY)

You'd get id=123 and path=NY

**Comment by RoyiNamir** [comment] 2018-04-03 20:16
@chriszrc It was just a suggestion for a service to know which  params I have currently - which I use in my current app(mobile)  via a service. and I use this ^

**Comment by chriszrc** [comment] 2018-04-03 20:39
Yup, my response was just another approach you could use, rather than listening to all NavigationEnd events, you can get the same info from the router snapshot with some lame trickery-

**Comment by diddimar** [comment] 2018-06-23 11:15
I was looking for a way to extract a specific value from the params  inside of a service so I could share it accross multiple components. The below code works perfectly for me.

```typescript
import { Injectable } from '@angular/core';
import { ActivatedRoute, Router, NavigationEnd, Params } from '@angular/router';
import { filter } from 'rxjs/operators';

@Injectable()
export class MiscService {

  public IdParameter: string;
  constructor(
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.subscribeToRouterParams();
  }

  subscribeToRouterParams(){
    this.router.events.pipe(filter(event => event instanceof NavigationEnd))
    .subscribe( () => {
      let active = this.route;
      while (active.firstChild) { active = active.firstChild };
      active.params.subscribe( (params: Params) => {
          this.IdParameter = params['id'];
      });
    });
  }

}
```

- Angular version : 5.2.0
- Typescript : 2.5.3
- rxjs : 5.5.6

**Comment by Ahsanmughal** [comment] 2018-09-07 12:47
user **paramsInheritanceStrategy** inside root module. it will return object of all params.
`RouterModule.forRoot(routes, {
   paramsInheritanceStrategy: 'always'
})`

**Comment by kamechb** [comment] 2018-10-12 05:05
@Ahsanmughal that's for child component consume parent params, it's inverse.

**Comment by leviatorkilsheyggi** [comment] 2019-01-02 20:02
Any news on this? Can we agree on a _right_ way to subscribe to parameters in other/parent components?

**Comment by rzzo** [comment] 2019-01-23 02:06
subscribing

**Comment by klinki** [comment] 2019-01-31 15:13
After 2 years, this issue caught me again. This is 2nd Angular project out of 3 I worked on where I need this feature.

`paramsInheritanceStrategy` was a huge step forward and I'm very glad for it, but having available ALL params inside parent component would be very beneficial too.

**Comment by T04435** [comment] 2019-02-05 03:50
You can pass the `ActivatedRoute` as a param of the service function from your component/s.

https://stackoverflow.com/a/54527469/4374291

**Comment by Humberd** [comment] 2019-02-25 13:27
I've created a simple service that gets a param by traversing a current route tree.

```typescript
@Injectable({
  providedIn: 'root'
})
export class RouterUtilsService {

  constructor(private router: Router) {
  }

  /**
   * Traverses a router tree from root to a leaf looking for {@param}.
   */
  getParam(param: string): string | null {
    for (const route of this.getCurrentRoutesChain()) {
      if (route.snapshot.paramMap.has(param)) {
        return route.snapshot.paramMap.get(param);
      }
    }
    return null;
  }

  /**
   * Retrieves a chain of {ActivatedRoutes} from root to a leaf.
   */
  getCurrentRoutesChain(): ActivatedRoute[] {
    let currentRoute = this.router.routerState.root;
    const results: ActivatedRoute[] = [currentRoute];

    while (currentRoute.firstChild) {
      currentRoute = currentRoute.firstChild;
      results.push(currentRoute);
    }

    return results;
  }
}
```

**Comment by nagyzsolthun** [comment] 2019-08-04 22:44
My implementation to access URL params outside the view (I believe this is the most simple solution ATM) :

`@Injectable({
  providedIn: 'root'
})
export class RouteParamsService {
  private params$: Observable<ParamMap>;

  constructor(router: Router, route: ActivatedRoute) {
    this.params$ = router.events.pipe(
      filter(event => event instanceof NavigationEnd),
      switchMap(() => route.firstChild.paramMap),
      shareReplay(1)
    );
  }

  getQuery(): Observable<string> {
    return this.params$.pipe(
      map(params => params.get("query")),
      distinctUntilChanged()
    );
  }
}`

**Comment by michael-letcher** [comment] 2019-12-11 00:58
@angular is there any plans to make getting this data easier? If not, then this ticket should be closed stating that by design it's meant to left to us to get the data.

Is there a recommended approach?

**Comment by BenRacicot** [comment] 2019-12-11 22:06
It would be very useful to have one true source for router information available anywhere at any time.

**Comment by bnohad** [comment] 2020-01-09 12:58
Guys thank me later:

`
@Injectable({
  providedIn: 'root'
})
export class MyParamsAwareService {
  constructor(private router: Router) { 
    this.router.events
      .pipe(
        filter(e => (e instanceof ActivationEnd) && (Object.keys(e.snapshot.params).length > 0)),
        map(e => e instanceof ActivationEnd ? e.snapshot.params : {})
      )
      .subscribe(params => {
      console.log(params);
      // Do whatever you want here!!!!
      });
  }
}
`

**Comment by BenRacicot** [comment] 2020-01-09 15:57
@bnohad nice one. I ended up with something similar and doesn't look as clean as yours.

Within a service's ctor:

```
this.router.events.pipe(
    filter(event => event instanceof NavigationEnd),
    map(() => this.route),
    map(route => {
        while (route.firstChild) route = route.firstChild
        return route
    }),
    // filter(route => route.outlet === 'primary'), // not required?
    mergeMap(route => route.data)
).subscribe(data => {
    let path = this.router.url.split('/')[1];
    console.log(path);
});
```

**Comment by JonathanIlk** [comment] 2020-01-12 15:14
I turned the solution from @bnohad into a service that other services can inject, to listen changes in the paramMap.

```
class EmptyParamMap implements ParamMap {
  readonly keys: string[] = [];
  get(name: string): string | null {
    return null;
  }

  getAll(name: string): string[] {
    return [];
  }

  has(name: string): boolean {
    return false;
  }
}

@Injectable({
  providedIn: 'root'
})
export class RouteChangeService {
  public paramsChange$: Observable<ParamMap>;

  private emptyParamMap = new EmptyParamMap();

  constructor(router: Router) {
    this.paramsChange$ = router.events
      .pipe(
        filter(event => (event instanceof ActivationEnd) && (event.snapshot.paramMap.keys.length > 0)),
        map(e => e instanceof ActivationEnd ? e.snapshot.paramMap : this.emptyParamMap),
        distinctUntilChanged(RouteChangeService.isSameParamMap)
      );
  }

  private static isSameParamMap(prev: ParamMap, curr: ParamMap) {
    if (prev.keys.length !== curr.keys.length) {
      return false;
    }
    for (const key of prev.keys) {
      if (prev.get(key) !== curr.get(key)) {
        return false;
      }
    }
    return true;
  }
}
```

**Comment by amitport** [comment] 2020-02-10 07:50
I haven't seen the following mentioned, I think it is one of the nicer ways of accessing a child's activated route:
```html
<ng-container *ngIf="routerOutlet.activatedRouteData['example'] as example">
   example is available {{example}} at parent
</ng-container>
<router-outlet #routerOutlet="outlet"></router-outlet>
```

(in the example I'm `outerOutlet.activatedRouteData` assuming there is a `{resolve: {example: 'exampleResolver'}}` in the route, but note that `outerOutlet.activatedRoute.paramMap` is also available if needed)

**Comment by Lucas00012** [comment] 2020-11-27 05:16
2020 and this issue still exists. Google, you can fix this or not?

**Comment by peternixey** [comment] 2020-12-17 11:40
It's really surprising how difficult this seemingly simple task is to do. However given that a) the angular team is smart and b) it's by design, my lack of understanding of the required complexity points towards a lack of understanding of how the router treats the params across nested routes. 

I have to assume that there's a reason this is so very hard and I'd like to understand what it is as my mental model of how the router works obviously doesn't map to what's really happening. What would be the best places in the docs to get a deeper understanding of the reasoning behind all of the trickery required?

**Comment by peternixey** [comment] 2020-12-17 12:15
Also I wanted to just add to @diddimar's excellent solution. It got me to the answer but it also has a side effect of creating a new subscription every time the route chagnes. 


````
import { Injectable } from '@angular/core';
import { ActivatedRoute, Router, NavigationEnd, Params } from '@angular/router';
import { filter, switchMap } from 'rxjs/operators'
import { of, Observable } from 'rxjs'

@Injectable()
export class MiscService {

  params$: Observable<Params>

  constructor( private router: Router,
              private route: ActivatedRoute) {

    // Create an observable representing the params
    this.params$ = this.router.events.pipe(
      filter(event => event instanceof NavigationEnd),
      switchMap(() => {
        const params = this.route.firstChild?.params
        // return params or an empty observable 
        return params || of()
      })
    )
    
    // subscribe to the params$ observable - can be done for 
    // multiple observers
    this.params$.subscribe((params) => {
      console.log('params', params)
    })
  }

}
````
This version of the service uses `switchMap` to ensure that you don't accidentally create a set of nested subscriptions every time the route changes

**Comment by atscott** [comment] 2020-12-29 20:21
In general, this is working as intended but I understand that it's difficult to work with. There's really a question as to whether the `router` package should provide utility functions like this or if it should be left to the community to develop libraries that accomplish common goals.

One of the difficult problems to solve with something like this would be agreeing on a strategy for constructing the object containing "all parameters". Once it's written and made available as public API, it can't change without breaking people who are already depending on the way its written, so there's a risk of creating `getAllParameters` and then needing `getAllParametersBFS` to accommodate those who want different prioritization for duplicate parameter keys across named outlets. As a general rule, we try to ensure that the building blocks are there and then tend to allow devs to develop their own approaches to these types of issues, tailored to their specific needs.

That said, it does seem reasonable that the `ActivatedRouteSnapshot` could provide a base utility function to merge all parameters and/or data starting from the root, as it already has a few similar "helper" functions (`paramMap`, `toString`, `pathFromRoot`). Then in order to get "all parameters" at a given time, you could use `snapshot.mergedParams`. If there are more specific needs, the built-in helper could be used as a reference.

Getting all params and data can currently be done like this (could be simpler if you don't care about `data` or named outlets):
```
  mergeRouteParams() {
    let params = {};
    let data = {};
    const stack: ActivatedRouteSnapshot[] = [this.router.routerState.snapshot.root];
    while (stack.length > 0) {
      const route = stack.pop();
      params = { ...params, ...route.params };
      data = { ...data, ...route.data };
      stack.push(...route.children);
    }

    return { params, data };
  }
```
Subscribing to the `NavigationEnd` event and calling this function seems like it would get what's needed here.
Here's an example: https://stackblitz.com/edit/angular-merge-route-params-example

Is this the param merging behavior that is desired here or have I misinterpreted the request?

**Closed** 2021-01-08 19:48 UTC
Labels: comp: router, feature, freq2: medium
