### ISSUE TITLE
AOT Compiler does not handle default exports

### ISSUE THREAD

**Issue by schungx** [angular/angular#11975] opened 2016-09-29 08:43 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When running `ngc` while some modules have default exports:

`some-module.ts`
~~~~~~ {.ts}
export default { foo, bar };
~~~~~~

`another-module.ts`
~~~~~~ {.ts}
import someModule from "./some-module";
~~~~~~

The compiler fails to find `someModule` inside `some-module.ts` with the following error:

`can't resolve module .some-module from D:/path/to/another-module.ts`
`Error: can't find symbol undefined exported from module D:/path/to/some-module.ts`

If changed to explicitly-named exports:

`some-module.ts`
~~~~~~ {.ts}
export var someModule = { foo, bar };
~~~~~~

`another-module.ts`
~~~~~~ {.ts}
import { someModule } from "./some-module";
~~~~~~

It now works fine.  Obviously, the code does not handle the case of an unnamed default export.

**Expected behavior**
The default export should also work.

**Reproduction of the problem**
See above example.

**Please tell us about your environment:**
Windows 10.

* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** all
 
* **Node (for AoT issues):** `node --version` =  v4.3.1

**Comment by robwormald** [comment] 2016-09-29 10:19
Duplicate of #11402 - we do plan to support this.

**Closed by robwormald** 2016-09-29 10:19 UTC
