### ISSUE TITLE
Need a way for a component to add CSS classes to host non-destructively

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#7289] opened 2016-02-25 21:21 UTC
Say a user wants to add margin around a component:

``` html
<cool-thing class="extra-margin"> ... 
```

But the component itself has need to set a dynamic CSS class to the host element:

``` ts
@Component({
  ...
  host: { '[class]': 'myCustomStyle' }
})
class CoolThing {
  myCustomStyle: string = figureOutWhichClassToUse();
}
```

Doing this in the component will completely overwrite the `class` property, wiping away the user's classes.

In other situations, `NgClass` serves this purpose, but a component cannot apply a directive to its host element. Using the `[class.whatever]` syntax also doesn't solve this, as the `whatever` is the variable part. 
### Proposal

Each component can, conceptually, have two distinct `class` lists: one that is from the user and one that comes from the component itself. These could be resolved independently with Angular rendering the union. Any time the user uses `ngClass` or the `[class.whatever]` syntax, it should override whatever is set to "class". 

cc @mhevery

**Comment by wembernard** [comment] 2016-03-09 11:04
:+1:

**Comment by justas-kuizinas** [comment] 2017-02-27 17:55
Any updates on this?

**Comment by DzmitryShylovich** [comment] 2017-02-27 18:27
@justas-kuizinas as a workaround you can use `@HostBinding` instead of `@Component.host` http://plnkr.co/edit/CmCBBn4yx1Z0E0kFvXmf?p=preview

**Comment by Swiftwork** [comment] 2017-03-30 14:10
Isn't this quite easily solved by:
```typescript
@HostBinding('class') @Input('class') classList: string = '';
```
This will capture any previous classes that have been manually assigned to the components dom. However does not facilitate for ones set dynamically by e.g. directives.

**Comment by tsu1980** [comment] 2017-09-20 03:20
My workaround.

```
constructor(private el: ElementRef, private renderer: Renderer) { }

ngOnInit() {
  this.renderer.setElementClass(this.el.nativeElement, 'my-item-' + this.itemType, true);
}
```

**Comment by xmeng1** [comment] 2017-10-18 10:54
Currently, I use two methods to add the class name for a component. I don't know whether they are good way to do it, but it works according to my test.
1. use host:

@Component({
  host: {
    ['class']: 'm-grid__item' +
    ' m-grid__item--fluid''},
})

2. use HostBinding

@HostBinding('class.m-grid__item')  public bindStyle: boolean = true;
@HostBinding('class.m-grid__item--fluid')  public bindStyle2: boolean = true;

**Comment by MartinMa** [comment] 2017-11-08 14:55
@xmeng1 Thanks for your summary. Just a small correction for approach 1 to avoid confusion (for anyone who might read this).

It has to be `'[class]':` (instead of `['class']:`)! The quotes have to be on the outside.

**Comment by xmeng1** [comment] 2017-11-08 16:44
@MartinMa you are right, thanks!

**Comment by trotyl** [comment] 2017-12-16 11:53
I used a manually provided `NgClass` to achieve this like:

```typescript
const prefix = 'ant-btn'

@Directive({
  selector: 'button[antBtn]',
  providers: [ NgClass ],
})
export class HelloComponent implements OnChanges  {
  @Input() color: string = 'default'

  private hostClasses: { [name: string]: boolean }

  constructor(@Self() private ngClass: NgClass) { }

  ngOnChanges(changes: SimpleChanges): void {
    this.hostClasses = {
      [`${prefix}`]: true,
      [`${prefix}-${this.color}`]: true,
    }

    this.updateHostClasses()
  }

  private updateHostClasses(): void {
    this.ngClass.ngClass = this.hostClasses
    this.ngClass.ngDoCheck()
  }
}
```

More details can be found in the [StackOverflow answer](https://stackoverflow.com/a/47845343/6714112).

**Comment by arniebradfo** [comment] 2018-05-19 16:18
Overriding the native `class=""` attribute with an `@Input() class: string;` works pretty well:

```ts
import { Component, Input, HostBinding } from '@angular/core';

@Component({
	selector: 'gist-keeps-class',
	template: 'this component keepes class="class" attributes'
})
export class KeepsClass {

	@Input() booleanInput: boolean = false;
	@Input() stringInput: 'some-thing' | 'another-thing' | 'a-third-thing' = 'another-thing';

	@Input() class: string = ''; // override the standard class attr with a new one.
	@HostBinding('class')
	get hostClasses(): string {
		return [
			this.class, // include our new one 
			this.booleanInput ? 'has-boolean' : '',
			this.stringInput
		].join(' ');
	}
       
}
```
```html
<gist-keeps-class 
  class="some classes" 
  [booleanInput]="true" 
  [stringInput]="some-thing"
></gist-keeps-class>
```
will output this:
```html
  <gist-keeps-class class="some classes has-boolean some-thing" >
    this component keepes class="class" attributes
  </gist-keeps-class>
```
It's not throughly tested, but should work?

**Comment by kylecordes** [comment] 2018-05-19 16:31
We sometimes get this issue's question (teaching Angular Boot Camp) from people first learning Angular, before they are really committed to it.  We manage to get them up and running with variants of the solutions written above, but is definitely an area where we are to some extent "apologizing" that this is currently quite a rough edge.

My request for whoever designs a full solution to this: aim for best in class, very easy and smooth.

**Comment by MattewEon** [comment] 2018-07-14 22:39
@arniebradfo do you think that it is possible to wrap your solution in an abstract component or in a directive ?

**Comment by faizalmy** [comment] 2018-12-21 10:30
My solution:


	@HostBinding('class') classList = 'fixed-class';
	@Input() class: string;

	constructor() {
	}

	ngOnInit() {
	   if (this.class) {
	      this.classList += ' ' + this.class;
	   }
	}


usage:

	<my-component [class]="'custom-class'">
        my content
	</my-component>


output:

	<my-component class="fixed-class custom-class">
        my content
	</my-component>

**Comment by kyubisation** [comment] 2019-02-21 15:59
Based on the answer by @trotyl I implemented a simple solution: https://stackblitz.com/edit/angular-cvkrpe?file=src%2Fapp%2Fapp.component.html

This solution will not overwrite class attribute on host, [class.binding] or [ngClass] (as other solutions might do).

```typescript
import { Directive } from '@angular/core';
import { NgClass } from '@angular/common';

@Directive({})
export class HostClass extends NgClass {
  apply(value: string | string[] | Set<string> | { [klass: string]: any }) {
    this.ngClass = value;
    this.ngDoCheck();
  }
}
```

Usage:
```typescript
@Component({
  selector: 'hello',
  template: `<h1>Hello {{name}}!</h1>`,
  providers: [HostClass]
})
export class HelloComponent implement OnInit  {
  @Input() name: string;

  constructor(@Self() private hostClass: HostClass) { }

  ngOnInit() {
    if (this.name === 'special name') {
      this.hostClass.apply('special);
    } else {
      this.hostClass.apply({
        [this.name]: true,
        normal: true,
      });
    }
  }
```

**Comment by mslooten** [comment] 2019-02-28 08:45
How about using an ElementRef to do this? We ran into the same issue and saw that Material uses this method to add classes.

This works for both class and ngClass classnames set on the host element.

```javascript
  constructor(elementRef: ElementRef) {
    elementRef.nativeElement.classList.add('my-classname');
  }
```

**Comment by MaKCbIMKo** [comment] 2019-02-28 10:10
@mslooten - this is what I had to use as well. But it looks bulkier than `@HostBinding`

**Comment by greggbjensen** [comment] 2019-07-09 18:03
This worked well for me and was a simple solution:

```TypeScript
@HostBinding('class.header-logo') public additionalClass: boolean = true;
```

**Comment by jpcmf** [comment] 2019-08-21 23:13
All examples

> constructor() {
> }

I've just add ```@HostBinding('class') classList = 'd-flex flex-column h-100';``` to my ```app.component``` and it works. Thank you :)

**Comment by jpcmf** [comment] 2019-08-21 23:14
> My solution:
> 
> ```
> @HostBinding('class') classList = 'fixed-class';
> @Input() class: string;
> 
> constructor() {
> }
> 
> ngOnInit() {
>    if (this.class) {
>       this.classList += ' ' + this.class;
>    }
> }
> ```
> 
> usage:
> 
> ```
> <my-component [class]="'custom-class'">
>     my content
> </my-component>
> ```
> 
> output:
> 
> ```
> <my-component class="fixed-class custom-class">
>     my content
> </my-component>
> ```

All examples

> constructor() {
> }

I've just add ```@HostBinding('class') classList = 'd-flex flex-column h-100';``` to my ```app.component``` and it works. Thank you :)

**Comment by jpcmf** [comment] 2019-08-21 23:15
> My solution:
> 
> ```
> @HostBinding('class') classList = 'fixed-class';
> @Input() class: string;
> 
> constructor() {
> }
> 
> ngOnInit() {
>    if (this.class) {
>       this.classList += ' ' + this.class;
>    }
> }
> ```
> 
> usage:
> 
> ```
> <my-component [class]="'custom-class'">
>     my content
> </my-component>
> ```
> 
> output:
> 
> ```
> <my-component class="fixed-class custom-class">
>     my content
> </my-component>
> ```

All examples

> constructor() {
> }

I've just add ```@HostBinding('class') classList = 'd-flex flex-column h-100';``` to my ```app.component``` and it works. Thank you @faizalmy  😃

**Comment by etay2000** [comment] 2019-10-08 14:43
Wow another common use case issue lingering since 2016. Perhaps my open source software expectations are too high?

**Comment by trotyl** [comment] 2019-10-09 01:59
@etay2000 It has already been fixed in Ivy for some time, just wan't brought back to view engine.

**Comment by etay2000** [comment] 2019-10-09 05:26
Ok thanks, I appreciate the info.

**Comment by yankee42** [comment] 2019-12-11 10:00
Interestingly there is another bug, which can be used as a workaround in the meantime (until you upgrade to Ivy): #26251
# Broken (overrides class)
```typescript
@Component({
  ...
  host: { '[class]': 'myCustomStyle' }
})
class CoolThing {
  myCustomStyle: string = figureOutWhichClassToUse();
}
```
# Works (merges class)
```typescript
@Component({
  ...
  host: { 'class': 'myCustomStyle' }
})
class CoolThing {
  myCustomStyle: string = figureOutWhichClassToUse();
}
```
The only difference is `[class]` vs `class`.

**Comment by exequiel09** [comment] 2019-12-20 09:21
I'm having an issue with `HostBinding` which outputs the string `[MAP]`.

![Screen Shot 2019-12-20 at 5 05 52 PM](https://user-images.githubusercontent.com/1289472/71244158-dc603280-234c-11ea-9549-c2de026439d6.png)

I am currently using @faizalmy reply here in this issue

> My solution:
> 
> ```
> @HostBinding('class') classList = 'fixed-class';
> @Input() class: string;
> 
> constructor() {
> }
> 
> ngOnInit() {
>    if (this.class) {
>       this.classList += ' ' + this.class;
>    }
> }
> ```
> 
> usage:
> 
> ```
> <my-component [class]="'custom-class'">
>     my content
> </my-component>
> ```
> 
> output:
> 
> ```
> <my-component class="fixed-class custom-class">
>     my content
> </my-component>
> ```

**Comment by vthinkxie** [comment] 2020-01-08 08:16
this issue has been fixed in angular 9.0.0

**Comment by PeterHewat** [comment] 2020-01-27 11:47
I confirm this works in Angular 9.0.0
Here is a simple example:
```ts
import { Component, OnInit, HostBinding } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  @HostBinding('class') private hostClass: object = {};

  public ngOnInit(): void {
    this.addClass('myYellowBackground');
  }

  private addClass(className: string): void {
    this.hostClass[className] = true;
  }

  private removeClass(className: string): void {
    delete this.hostClass[className];
  }

}
```
Then, if you add a class to that component as follows...
```html
<app-root class="myRedBorder"></app-root>
```
... both myRedBorder and myYellowBackground classes will be applied to the instance of <app-root/>

**Comment by wnvko** [comment] 2020-02-05 11:38
I think this is some easy way for adding class to component:
```
@Component({
  ...
})
export class CoolThingComponent {
  @HostBinding('class.myCustomStyle') private hostClass = true;
}
```
And then use component like this:
```
<cool-thing class="extra-margin">
```

**Comment by vladimiry** [comment] 2020-02-05 11:47
@wnvko adding one class is easy, the issue is about host-bind a multiple classes.

**Comment by mhevery** [comment] 2020-02-06 02:11
This has been resolved as of https://github.com/angular/angular/pull/34938 Closing the issue.

**Closed by mhevery** 2020-02-06 02:11 UTC
Labels: comp: core, fixed by Ivy, hotlist: angular-core-team, hotlist: components team, state: Needs Design, type: feature
