### ISSUE TITLE
PWA application unfortunately stopped/Crashed.

### ISSUE THREAD

**Issue by akilmakda** [angular/angular#26411] opened 2018-10-12 09:49 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

![imkmndakhcmkloge](https://user-images.githubusercontent.com/24309502/46862147-e544a280-ce31-11e8-8524-390caff18d5a.png)

Case 1) When I use application that time application crashed.
Case 2) When I open other native Android application that time crashed.

Note: **Mobile memory is low**

This is my website URL: https://www.greatbuyz.com/
Service worker URL: https://www.greatbuyz.com/ngsw-worker.js

## Expected behavior

Application work normally

## Environment

<pre><code>
Angular-cli : 6.2.1

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.10.1
- Platform:  Linux

Others:

</code></pre>

**Comment by gkalpak** [comment] 2018-10-12 13:43
Is there any indication this is related to SW?

**Comment by akilmakda** [comment] 2018-10-12 14:02
We have implemented a PWA SW around 1 week after implemented. A2HS is working after implementation of ngsw. We assume this is the issue is related to SW.
Also, we have tested on other devices it is not crashing on it.

**Comment by gkalpak** [comment] 2018-10-12 14:20
I'm afraid there is not much we can do without more info. The SW itself shoudn't cause any issues wrt memory.
If you are caching many or large assets or data, that might cause problems on devices with low memory, but this does not seem to be the case with your app.

So, I really don't know what might be the root cause 😞

**Comment by gkalpak** [comment] 2018-10-12 14:20
I am going to close this, since it is not actionable in it current state.
Happy to reopen and investigate if you can provide more info.

**Closed by gkalpak** 2018-10-12 14:20 UTC
Labels: comp: service-worker, type: bug/fix

**Comment by gkalpak** [comment] 2018-10-13 10:08
This is browser/devide specific, so I have no idea 😅
