### ISSUE TITLE
percent pipe digitInfo not working as expected

### ISSUE THREAD

**Issue by wdanda** [angular/angular#20866] opened 2017-12-07 14:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If I do this in an Angular 5 template:

`{{0.7 | percent:'1.2-5'}}`

I get this as expected: `70.00%`

However, when I do this:
`{{0.07 | percent:'1.2-5'}}`

I get `7.00000%` instead of what the expected `7.00%`

-- | --

## Expected behavior

`{{0.07 | percent:'1.2-5'}}`

Should parse to `7.00%` instead of `7.00000%`.

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/0QETNJgjqLDgrK4o7uB1

## What is the motivation / use case for changing the behavior?
I'm working on a project that has a requirement to format some values into a percent format with a minimum of 2 fraction digits and a maximum of 5.

## Environment
<pre><code>
Angular version: 5.0.1

Browser:
- [X] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by vicb** [comment] 2017-12-07 23:14
duplicate of https://github.com/angular/angular/issues/20136

**Closed by vicb** 2017-12-07 23:14 UTC
Labels: comp: common, comp: i18n, type: bug
