### ISSUE TITLE
Cannot redirects to child aux routes

### ISSUE THREAD

**Issue by mhartington** [angular/angular#27215] opened 2018-11-21 17:31 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
`@angular/router`

### Is this a regression?
No

 Yes, the previous version in which this bug was not present was: ....

### Description

With a lazy loaded component, trying to redirect to a child/aux-router throws a " Cannot match any routes. URL Segment: 'home' ".  Seems that when you have a root app-router setup like:

```ts

const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsModule' }
];
```

And a second router setup for TabsModule like:

```ts
const routes: Routes = [
  {
    path: '',
    component: TabsComponent,
    children: [
      {
        path: 'home',
        component: HomeComponent,
        outlet: 'home'
      },
      {
        path: '',
        redirectTo: '/(home:home)',
        pathMatch: 'full'
      }
    ]
  }
];
```

The router isn't able to load `localhost:4200/(home:home)`

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

https://github.com/mhartington/ng-aux-redirects

## 🔥 Exception or Error
<pre><code>
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'home'
noMatchError
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.6
Node: 10.0.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Comment by BaggersIO** [comment] 2018-12-04 13:57
I had a similar issue: Maybe a duplicate of https://github.com/angular/angular/issues/19069

**Comment by jasonaden** [comment] 2019-01-03 22:59
From what I remember of this code, the parser can't identify aux routes on the root. I could be wrong, but that's what I remember.

I can take a look at this some time in the next few weeks at best. If anyone else comes across this issue and has a few minutes to confirm, that would be helpful.

**Comment by atscott** [comment] 2020-11-16 21:49
Closing as a duplicate of #10726. Redirects otherwise do work: https://stackblitz.com/edit/angular-ivy-fhtbxw?file=src%2Fapp%2Fmain.module.ts

**Closed by atscott** 2020-11-16 21:49 UTC
Labels: P3, comp: router, freq2: medium, router: aux routes, router: config matching/activation/validation, state: confirmed, triage #1, type: bug/fix
