### ISSUE TITLE
`ComponentRef#setInput` should return result indicating whether input was set successfully

### ISSUE THREAD

**Issue by MaximSagan** [angular/angular#56448] opened 2024-06-14 01:59 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

(Tangentially related to #51878)

Currently, we call `setInput(name, value)` with an incorrect input name, all that will occur is a console error. This makes it impossible for the consumer to capture this error and deal with it as they wish.

### Proposed solution

Simply have `setInput()` return a boolean indicating whether the value was set properly. This should not represent a meaningful breaking change (should only affect consumers who were for some reason depending on the return type of setInput being `void`).

### Alternatives considered

N/A

**Comment by Harpush** [comment] 2024-06-14 08:09
I don't think this is correct. Returning a boolean just goes around the problem of not having types.
I believe something like https://github.com/angular/angular/issues/51878#issuecomment-1973757043 should be the solution.

**Comment by MaximSagan** [comment] 2024-06-14 10:09
> I don't think this is correct. Returning a boolean just goes around the problem of not having types. I believe something like [#51878 (comment)](https://github.com/angular/angular/issues/51878#issuecomment-1973757043) should be the solution.

This is not supposed to replace any solution described in #51878. That issue describes a compile-time check, this issue describes a runtime check. Ideally we'd have both, but the compile-time check is non-trivial for reasons described there and does not seem likely to be implemented soon (hope I'm wrong), whereas this runtime check is trivial as you can see from my PR.

**Comment by Harpush** [comment] 2024-06-14 12:03
What I meant is 99% of the cases where you are wrong about the input name or value is in development time. So a runtime validation seems too late. Unless there is a use case for it (guess some dynamic input name from server? But seems far fetched)

**Comment by pkozlowski-opensource** [comment] 2024-06-20 10:01
Thnx for the suggestion @MaximSagan - we did discuss this at length in the team and decided that we would rather focus on addressing the root cause - in this sense I can see it as duplicate of #51878.

As the API returning a boolean to indicate status - we would rather consider a breaking change (or a feature behind a flag) that throws an error instead of logging to the console.

**Closed by pkozlowski-opensource** 2024-06-20 10:01 UTC
Labels: area: core, core: inputs / outputs, core: dynamic view creation
