### ISSUE TITLE
Validator email - Not allowing international email (RFC 6531)

### ISSUE THREAD

**Issue by Swissbite** [angular/angular#26395] opened 2018-10-11 11:30 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Using Validator.email with an international email (UTF-8 in the local part) is claiming that the email is invalid.

## Expected behavior
Validator.email should accept valid emails as RFC 6531 suposes.

## Minimal reproduction of the problem with instructions
1. Create a basic form with a field including Validator.email
2. Put an international email address like `müller@example.com` into the email field
3. Check validation

Example: https://stackblitz.com/edit/angular-gitter-cn98xo

## What is the motivation / use case for changing the behavior?
The world is not just ASCII or english speaking, so emails with valid UTF-8 parts should work as well. Even hotmail is allowing international local parts like umlauts.

## Environment

<pre><code>
Angular version: 6.0.7, 6.1.0
Browsers: Irelevant, it is a regex issue
For Tooling issues:
- Node version: 8.9.4+
- Platform:  Any
</code></pre>

**Comment by trotyl** [comment] 2018-10-11 11:35
Duplicate of https://github.com/angular/angular/issues/25186

**Comment by gkalpak** [comment] 2018-10-11 12:42
Not even browsers support such characters (e.g. `äöü`) in email addresses (at least Chrome doesn't), so I'm not sure it makes sense to allow them in Angular at this point.

**Comment by Swissbite** [comment] 2018-10-11 12:47
We have the use case and customers with such emails, so yes: Even if it may not yet be in the WHATWG, it makes sense.
I know I could just use another regex validator, but in my opinion it would make sense to adjust the validator that it matches the real world.

**Comment by fetis** [comment] 2018-11-12 16:38
> Not even browsers support such characters (e.g. äöü) in email addresses

@gkalpak what do you mean?


What about to provide something like `.internationalEmail` validator for such cases?

**Comment by gkalpak** [comment] 2018-11-12 19:37
>> Not even browsers support such characters (e.g. äöü) in email addresses
>
> @gkalpak what do you mean?

I mean native browser email validation does not consider these character valid.

**Comment by dylhunn** [comment] 2021-07-29 17:59
Changing email validation would be a huge breaking change, and without sufficient community interest we cannot do that.

Also: we'd strongly encourage you to provide your own validator for this use case.

**Closed by dylhunn** 2021-07-29 17:59 UTC
Labels: comp: forms, feature, freq2: medium, insufficient votes, votes required
