### ISSUE TITLE
Auxillary routes / named outlets don't seem to work like one would expect

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#37692] opened 2020-06-23 18:55 UTC
# 🐞 bug report

### Affected Package
@angular/router

### Is this a regression?
This doesn't seem to work in legacy versions either, so no?

### Description
Named router outlets don't work or don't work as expected.

We should fix the bug, fix error messages and improve clarity if I'm holding it wrong, remove the non-functional behavior, or document around it.

(I've had 3 other folks look at this and we think we're doing it right)

## 🔬 Minimal Reproduction
https://stackblitz.com/github/stephenfluin/named-outlets-repro
(also here: https://github.com/stephenfluin/named-outlets-repro)

## 🔥 Exception or Error
1. Click on Next Tutorial Step, the named outlet receives the new component.
2. Click on Previous Tutorial Step, the router errors.

<pre><code>
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'b'
Error: Cannot match any routes. URL Segment: 'b'
at ApplyRedirects.noMatchError (https://xoriwymkg.github.stackblitz.io/turbo_modules/@angular/router@10.0.0-rc.6/bundles/router.umd.js:2762:20)
at CatchSubscriber.eval [as selector] (https://xoriwymkg.github.stackblitz.io/turbo_modules/@angular/router@10.0.0-rc.6/bundles/router.umd.js:2743:33)
at CatchSubscriber.error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/operators/catchError.js:48:31)
at MapSubscriber.Subscriber._error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:72:18)
at ThrowIfEmptySubscriber.Subscriber._error (https://xoriwymkg.github.stackblitz.io/turbo_modules/rxjs@6.5.5/internal/Subscriber.js:92:26)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 10.0.0-rc.5
Node: 12.18.0
OS: linux x64

Angular: 10.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.5
@angular-devkit/build-angular     0.1000.0-rc.5
@angular-devkit/build-optimizer   0.1000.0-rc.5
@angular-devkit/build-webpack     0.1000.0-rc.5
@angular-devkit/core              10.0.0-rc.5
@angular-devkit/schematics        10.0.0-rc.5
@angular/cli                      10.0.0-rc.5
@ngtools/webpack                  10.0.0-rc.5
@schematics/angular               10.0.0-rc.5
@schematics/update                0.1000.0-rc.5
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by richarddavenport** [comment] 2020-06-26 21:29
@AndrewKushnir  I think you just need to null out the outlet. I don't think the outlet works with an empty string. Not sure if that's what you want, but that doesn't seem to be how it works: https://stackblitz.com/edit/github-ndpte2

**Comment by atscott** [comment] 2020-06-30 21:35
Thanks @richarddavenport - your workaround does appear to achieve the intended action. I think this could still be considered an issue in the documentation (why doesn't '/' work and why do you need to provide a path command for the primary outlet?), a bug in the router (we should still handle '/' as being equivalent to setting the outlet to null), or both.

Not being able to clear the aux route by setting it to null is related to #15718. It works from outside the child components (i.e. `<a [routerLink]="[{outlets: {tutorial: null}}]">clear</a>` works in `home1.component.ts` but not `child2.component.ts`, which needs to be `<a [routerLink]="['', {outlets: {tutorial: null}}]">`)

**Comment by atscott** [comment] 2020-11-16 21:57
Closing as duplicate of #13523. This is a very common issue report with how named outlets get applied and should likely be one of the top priorities for improved documentation. See related comment here: https://github.com/angular/angular/issues/15718#issuecomment-717434043

**Closed by atscott** 2020-11-16 21:57 UTC
Labels: P3, comp: docs, comp: router, freq2: medium, router: aux routes, router: config matching/activation/validation, state: confirmed, type: bug/fix

**Comment by qqaimh** [comment] 2020-11-30 10:17
Angular 11 support Lazy Loading with Named Outlets, it is a good work. But if the lazy loading module has a RoutingModule which contains some routes, is it support navigate between these routes now?: #39886
