### ISSUE TITLE
FormControlDirective never unsubscribes.

### ISSUE THREAD

**Issue by SebastianStehle** [angular/angular#22294] opened 2018-02-18 23:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When you update the binding for a formControlDirective the directive is still bounded to the old form control.

## Expected behavior
FormControlDirective should cleanup correctly in ngOnChanges

## Minimal reproduction of the problem with instructions
I have no mínimal repro yet, but it is obvious that some calls to cleanUpControl are missing here: https://github.com/angular/angular/blob/master/packages/forms/src/directives/shared.ts

## Environment
Angular version: 5.2.1

**Comment by mlc-mlapis** [comment] 2018-02-19 00:31
... without a simple demo reproduction as on http://stackblitz.com it is so vague.

**Comment by mlc-mlapis** [comment] 2018-02-19 08:44
@SebastianStehle ... hmm, it only happens after switching through all forms first. Doesn't happen when firstly switching from index 0 to 1 or 2. Something is really wrong ... you are right.

**Comment by SebastianStehle** [comment] 2018-02-19 10:15
As I said: The directive never unsubscribes from the formcontrol. 

Therefore, when you go from form 0 to 1 to 2 to 0, the directive is binded:

* To FormControl 0: 2 times
* To FormControl 1: 1 time
* To FormControl 2: 1 time 

And because the loop is setting FormControl 2 last, it shows the value of FormControl 2, not from FormControl 0:

**Comment by SebastianStehle** [comment] 2018-02-19 10:20
A potential fix: https://github.com/angular/angular/compare/master...SebastianStehle:patch-1

**Comment by AndrewKushnir** [comment] 2020-06-23 23:43
Hi @SebastianStehle, thanks for reporting the issue. It looks like it should be resolved by #37566 (note: the PR is still in Draft mode and there is no ETA at this moment). Thank you.

**Comment by SebastianStehle** [comment] 2021-01-12 07:23
This is going to be fixed here: https://github.com/angular/angular/pull/39235 and this issue can be closed in my opinion

**Comment by AndrewKushnir** [comment] 2021-01-12 17:27
Thanks for the message @SebastianStehle, I'm closing this ticket since the problem should be resolved by #39235 as you mentioned and the fix would be available in 11.1.0 release later this month. Thank you.

**Closed by AndrewKushnir** 2021-01-12 17:27 UTC
Labels: P3, comp: forms, forms: directives, freq2: medium, state: confirmed, triage #1, type: bug/fix
