### ISSUE TITLE
Error with compile `:host-context` and `:host` in component styles

### ISSUE THREAD

**Issue by Dok11** [angular/angular#19572] opened 2017-10-05 12:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Style of component:
```scss
:host-context(.browser-safari) {
  :host:not(.disabled) .button:hover {
    .blob {
       transform: translateZ(0) scale(1.8);
    }
  }
}
```

Generated to:
```css
.browser-safari[_nghost-c15] [_nghost-c15]:not(.disabled) .button[_ngcontent-c15]:hover .blob[_ngcontent-c15],
.browser-safari [_nghost-c15] [_nghost-c15]:not(.disabled) .button[_ngcontent-c15]:hover .blob[_ngcontent-c15] { //...
```

## Expected behavior
Exptected css like this:
```css
.browser-safari[_nghost-c15]:not(.disabled) .button[_ngcontent-c15]:hover .blob[_ngcontent-c15],
.browser-safari [_nghost-c15]:not(.disabled) .button[_ngcontent-c15]:hover .blob[_ngcontent-c15] { //...
```

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/LSmrYc2GGGrupNYllSv7?p=preview

## What is the motivation / use case for changing the behavior?
Usual usage combination `:host-context` and `:host`.

## Environment
<pre><code>Angular version: 4.3.6 and 4.4.4</code></pre>

**Comment by petebacondarwin** [comment] 2021-01-23 21:09
So just to be clear the style you posted is SASS, right? This equates to the following CSS:

```css
:host-context(.some-host-content) :host.red .deep {
  color: red;
}
```

**Comment by petebacondarwin** [comment] 2021-01-23 21:16
I reproduced this in StackBlitz: https://stackblitz.com/edit/angular-ivy-qamnuw?file=src%2Fapp%2Fhello.component.ts

This produces the following selectors:

```css
.some-host-content[_nghost-pof-c40]   .red[_nghost-pof-c40]   .deep[_ngcontent-pof-c40],
.some-host-content   [_nghost-pof-c40]   .red[_nghost-pof-c40]   .deep[_ngcontent-pof-c40]
```

I believe this is a duplicate of #14349.

**Closed by petebacondarwin** 2021-01-23 21:16 UTC
Labels: P3, comp: core, core: CSS encapsulation, freq1: low, type: bug/fix
