### ISSUE TITLE
Redirect doesn't work: pipes API documentation 

### ISSUE THREAD

**Issue by LeraKill** [angular/angular#56276] opened 2024-06-05 13:53 UTC
### Describe the problem that you experienced

On page https://angular.dev/guide/pipes in the Note, the link [pipes API documentation](https://angular.dev/api/common#pipes) goes to 'Page not found' page

### Enter the URL of the topic with the problem

https://angular.dev/guide/pipes

### Describe what you were looking for in the documentation

i was looking for the list of the Pipes

**Comment by JoostK** [comment] 2024-06-05 14:03
Thanks for the report, this is a duplicate of #52968

**Closed by JoostK** 2024-06-05 14:03 UTC
