### ISSUE TITLE
ngSwitch: Type safety with AOT and a `ngSwitchThrow` directive?

### ISSUE THREAD

**Issue by maxime1992** [angular/angular#24978] opened 2018-07-19 09:33 UTC
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
With Typescript it's possible to have some type safety within a switch statement and make sure that all cases are handled. For that, at the end of the switch case we have to throw an error from the default statement.

The error should be something like that:

```
class ImpossibleSwitchStatement extends Error {
  constructor (x: never) {}
}
```

And if a case is missing in the switch statement then an error is emitted by Typescript.

Article about: http://ideasintosoftware.com/exhaustive-switch-in-typescript/

Stackblitz demo: https://stackblitz.com/edit/typescript-mlgrks

## Expected behavior
It'd be really nice to get that type safety with AOT from templates.
I do have an `ngSwitch`, relying on an enum, coming from an external project that can get updates.
Every time I upgrade the external project, I'd like to make sure that on my side, everything is well handled from my templates and that I haven't forgot a case.

Eventually, we could have something like the following:

```
<container-element [ngSwitchStrict]="switch_expression">
  <some-element *ngSwitchCase="match_expression_1">...</some-element>
  <some-element *ngSwitchCase="match_expression_2">...</some-element>
</container-element>
```

This way it wouldn't be a breaking change for existing app, just a new feature.
Also, using `ngSwitchStrict` you wouldn't be allow to have a `ngSwitchDefault` because the `default` will be handled directly by Angular.

Or maybe we could also have `<container-element [ngSwitch]="switch_expression" ngSwitchStrict>` but I'd rather prefer the first one :smile:.

## What is the motivation / use case for changing the behavior?
:tada: Type safety :tada: 

## Environment

Angular version: 6.0.6

**Comment by alxhub** [comment] 2021-07-16 23:36
Closing as a duplicate of #20780.

**Closed by alxhub** 2021-07-16 23:36 UTC
Labels: comp: common, comp: compiler, compiler: template type-checking, feature, insufficient votes, votes required
