### ISSUE TITLE
'last' variable in ngFor is always true

### ISSUE THREAD

**Issue by Routhinator** [angular/angular#35699] opened 2020-02-26 21:56 UTC
# 🐞 bug report

### Is this a regression?

Uncertain, as I have not implemeneted this method before.

### Description

In the below example code, with Angular 9.0.1 I am seeing that `last` is somehow always `true`

```typescript
        <ng-container *ngFor="let quote of (currentPage | async)?.results; let isLast = last;">
          <div class='quote-item'>
            "{{ quote.body }}"<br />
            -- <em><a [routerLink]="['/quotees', quote.quotee.slug]">{{ quote.quotee.name }}</a></em>
          </div>
          <hr *ngif="!isLast" />
        </ng-container>
```

The hr never renders in the DOM. as seen here in the results list.. https://v5.staging.amateurwriting.net/quotes

## 🔬 Minimal Reproduction
I have created a repro of the code (minus ng-bootstrap) in StackBlitz, however it seems that Angular 9 doesn't work in StackBlitz.. it just keeps going in circles asking for core-js even though it's installed. No idea how to fix the StackBlitz, the error it's throwing doesn't make sense..

https://stackblitz.com/edit/angular-issue-repro2-od4qyw?file=src%2Fapp%2Fapp.component.html 

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 13.9.0
OS: linux x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.0.1
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-02-26 22:06
@Routhinator there is a lot going on in your stackblitz so I can't be sure for 100% _but_ I think that the problem is a typo in ` <hr *ngif="!isLast" />`. Notice that it is `*ngif` while it should be `*ngIf`! When you correct this typo a basic scenario works: https://ng-run.com/edit/kdaSNKxEoXecq82Hqvhm

**Comment by Routhinator** [comment] 2020-02-26 22:10
Oh jeese.. a capital letter. 

Sometimes you just need a second pair of eyes. Thats the issue with working on a personal project sometimes. Cheers.

**Comment by pkozlowski-opensource** [comment] 2020-02-26 22:11
So the real problem here is that we _do_ report a warning (`console.warn`) but it is "too subtle". In VE this was a hard error: https://ng-run.com/edit/CGPY00WxXO8P9pelsgXH

I think that we should, as the very minimum, change the warning to error as currently it is very easy to miss those types of typos.

@Routhinator I'm going to re-open this issue so we can improve the error reporting here.

**Comment by Routhinator** [comment] 2020-02-26 22:13
Cheers, that sounds great. Thanks.

**Comment by FDIM** [comment] 2020-04-02 14:40
@atscott Can we reopen this bug? PR was reverted due to weak reason in my opinion. For us unit tests results in false positives when not everything is mocked

**Comment by atscott** [comment] 2020-04-02 15:48
@FDIM it was closed because the PR was merged, but yes, it should be reopened because the PR was reverted.

**Closed** 2020-05-04 19:37 UTC
Labels: comp: core, comp: ivy, core: host and host bindings, core: inputs / outputs, core: property / attr bindings and interpolations, freq3: high, hotlist: error messages, severity1: confusing, type: bug/fix
