### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by cesperian** [angular/angular#54151] opened 2024-01-30 04:45 UTC
### Describe the problem that you experienced

"See the [NgComponentOutlet API reference](https://angular.dev/api/core/NgComponentOutlet) for more information on the directive's capabilities." link leads to page not found

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/programmatic-rendering#using-ngcomponentoutlet

### Describe what you were looking for in the documentation

ngComponentOutlet

**Comment by maequise** [comment] 2024-01-30 06:21
Hi @cesperian, thank you for the report. It seems that the PR [#52829](https://github.com/angular/angular/pull/49915) has already fixed the problem of the deadlink.

@JeanMeche  do you know when it will be release?

**Comment by JoostK** [comment] 2024-01-30 06:59
Thanks for the report, closing as a duplicate of https://github.com/angular/angular/issues/52828 for which the fix is pending deployment.

@maequise It's being worked on, but the deployment is not set up yet. I don't have an ETA.

**Closed by JoostK** 2024-01-30 06:59 UTC
