### ISSUE TITLE
Upgrade adapter causing component to run outside zone

### ISSUE THREAD

**Issue by arins** [angular/angular#13770] opened 2017-01-04 09:27 UTC
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 

**Current behavior**
I am using upgrade adapter. When using *ngIf on components angular runs the components outside of zone which causes the GUI not to update.

**Expected behavior**
I expect the angular component to run in a zone regardless of upgrade adapter (because without it works just fine)

**Minimal reproduction of the problem with instructions**
[zone lost example](https://plnkr.co/edit/xgyiXw?p=preview) open the console click on ng2 and you will see that I am logging if in zone ore not. As you can see when using *ngIf we suddenly are outside of zone!

here is example without upgrade adapter which is working and logging in the console that we still are in zone.
 [zone working](https://plnkr.co/edit/DGuyBsT95vv7vRerfe8y?p=preview)

**What is the motivation / use case for changing the behavior?**
It is working without upgrade adapter so it should work in the same way with upgrade adapter.

**Please tell us about your environment:**
chrome

* **Angular version:** 2.4.1

* **Browser:** [all ]

 
* **Language:** [ TypeScript]

**Comment by mhevery** [comment] 2017-01-05 20:50
Duplicate of #13540

**Closed by mhevery** 2017-01-05 20:50 UTC
