### ISSUE TITLE
usage of HostListener leads to excessive change detection

### ISSUE THREAD

**Issue by shaharvaldman** [angular/angular#16986] opened 2017-05-24 08:50 UTC
I'm submitting a feature request

**Current behavior**
The HostListener decorator is a very useful feature. We use it a lot. Very often the events we subscribe to come from the document.  
Very often, when the HostListener fires for document level events, we need to perform additional checks before performing any change to the application. Most times the handler is invoked, nothing happens to the app. Since HostListener marks the component tree as dirty, it leads to heavy re-evaluation of many components, and hurts performance (the tree is on Push but some paths are very long with HostListener near the leafs).

**Expected behavior**
I would appreciate a way to use the HostListener without triggering a change detection for the sub tree.

**What is the motivation / use case for changing the behavior?**
An example use-case is in directives checking for clicks outside a component. They are very common and have few implementations such as  [https://github.com/chliebel/angular2-click-outside/blob/master/clickOutside.directive.ts](url) and [https://christianliebel.com/2016/05/angular-2-a-simple-click-outside-directive/](url).
Using these directives leads to heavy evaluation of many components.

 **Angular version:** 4.0.2

**Comment by pkozlowski-opensource** [comment] 2017-05-24 08:57
This is the same use-case as in #15905 - please add your input in there.

Closing as a duplicate of #15905

**Closed by pkozlowski-opensource** 2017-05-24 08:57 UTC

**Comment by johannesjo** [comment] 2018-03-21 11:14
@pkozlowski-opensource this is not a duplicate of #15905 though it might be related.

**Comment by SaltyDH** [comment] 2018-04-05 04:08
Please reopen this, whilst additional features as described in #15905 would be extremely useful, the current implementation has some serious performance problems as described above.

**Comment by michaelarnauts** [comment] 2019-01-11 10:45
Is there a way to tell the Angular that no ChangeDetection cycle is needed, like with             `this._changeDetection.checkNoChanges()`?
