### ISSUE TITLE
router-outlet on child route inside of conditional can't be found

### ISSUE THREAD

**Issue by frederikaalund** [angular/angular#11100] opened 2016-08-26 12:29 UTC
Identical to #9500 which was closed even though the issue persists in RC5. See my comment in said issue (which links to [this plunk](http://plnkr.co/edit/2NBjX45NRUbKKwA8INxy)).

I'm only creating a new issue since there has been no response from the dev team in the closed issue in the past 2 weeks. I thought that you might not get notifications from closed issues. I understand if you're busy with something else.

**Comment by brandonroberts** [comment] 2016-08-26 19:19
This is by design. The rendering process for the router is synchronous, so the `router-outlet` has to be present at the time the component(s) are to be rendered. This is because the router state is the source of truth as to what the current URL is and what is rendered on the screen.

**Comment by Apee** [comment] 2016-08-26 19:24
Thanks @brandonroberts ,

Ok but how can we manage to do something like this :
http://stackoverflow.com/questions/38983575/how-can-i-dynamically-position-the-router-outlet-depending-on-the-url-called/

Thanks ?

**Comment by mattem** [comment] 2016-08-26 19:45
@brandonroberts Maybe I have misunderstood, but in my original plnkr (and it's subsequent update to rc4), the router found the correct outlet on the parent route. 

In ```app/app.component.ts```, changing the value of ```showLinks``` still allows the router to find the router-outlet. However, the ```*ngIf``` in the child route in ```app/crisis-center/crisis-center.component.ts``` causes the router to error. 

By the synchronous reasoning, then I'd expect neither of these router-outlets to be found.

[Original plnkr](http://plnkr.co/edit/kuniIBjKpdD6mCb2Aq26?p=preview)

**Comment by jculverwell** [comment] 2016-08-28 05:02
Just to add my 2 cents...I think the scenario of placing router outlets inside conditionals will be common place.  A number of us seem to be falling into this pit of failure.  If it is not possible to place router outlets inside conditionals is there any guidance on workarounds?

**Comment by brandonroberts** [comment] 2016-08-29 00:33
@jculverwell I agree it is a common thing to do. If you need to handle something async that involves the router outlet, then you should handle it in your component without restricting the display of the router-outlet. Your other option is to use a resolver to complete your async operations before the route is activated.

**Comment by firov** [comment] 2016-08-29 07:00
@brandonroberts  yes it is common task to delay router's component initialization until some event from like user login. Also this functionality (router-outlet with ngIf) perfectly worked in RC4.

**Comment by brandonroberts** [comment] 2016-08-29 13:30
@firov yes, but we have [guards](https://angular.io/docs/ts/latest/guide/router.html#!#guards) that accomplish that now instead of hiding the router-outlet.

**Comment by firov** [comment] 2016-08-29 14:25
@brandonroberts thanks i missed that. But it forces you to use separate urls for login and logout.

**Comment by Apee** [comment] 2016-08-29 15:05
If I may add to this, restricting the display of the router-outlet is sometime mandatory in some cases (i.e. like placing dynamically a router-outlet in a list of dynamic elements).

It's not only placing a router-outlet in a ngIf but may be in ngFor too and basically any async directives.

**Comment by iBasit** [comment] 2016-08-31 01:23
I'm integrating angular2 on existing angular1 + php project and there are too many restriction like `router-outlet` needs to be in html and if its there, then route needs to be defined, if not defined for one page. 

I still can't find any one with the answer telling me, how to dynamically load component based on per url (so that's why I started using route), but now I have to put route on all pages, because I get `Error: Cannot match any routes: 'dashboard'`

Just read whole thread and past thread, and 👎

**Comment by brandonroberts** [comment] 2016-08-31 02:34
@iBasit you're going to have to provide some more context if you need some help. A reproduction of your issue in a plunker would be a good start. 👍

**Comment by frederikaalund** [comment] 2016-08-31 07:52
> This is by design. The rendering process for the router is synchronous, so the router-outlet has to be present at the time the component(s) are to be rendered. This is because the router state is the source of truth as to what the current URL is and what is rendered on the screen.

@brandonroberts Thanks for the clarification. Feel free to close this issue.

I'm now using [guards](https://angular.io/docs/ts/latest/guide/router.html#!#guards) to ensure that my asynchronous content has loaded before being displayed. If the asynchronous data is not ready, a loading component is displayed. This is a better design anyways. Before, I had no loading component and simply removed the `router-outlet` with an `ngIf` directive until the asynchronous data was ready.

**Comment by brandonroberts** [comment] 2016-08-31 12:55
@frederikaalund great. I can't close this so you or one of the team members will have to close it.

**Comment by pkozlowski-opensource** [comment] 2016-08-31 12:56
Thnx @brandonroberts !

**Closed** 2016-08-31 12:55 UTC

**Comment by chenyingyin** [comment] 2016-12-01 04:00
![default](https://cloud.githubusercontent.com/assets/24284270/20781448/b69ec64a-b7bd-11e6-9ecc-0f984358c2bc.png)
