### ISSUE TITLE
Docs: Higlighted selection in mini-scroll-tracks does not always match the highlighted blocks in the reference pages

### ISSUE THREAD

**Issue by ArneCaluwe** [angular/angular#52836] opened 2023-11-12 13:08 UTC
### Describe the problem that you experienced

When highlighting reference members on the reference pages with a code fragment, from time to time the highlighted code-fragment does not match the clicked reference member. 
![image](https://github.com/angular/angular/assets/47561535/548b3516-a6bc-4dbb-8160-4c76c1717aba)

Reloading the page does not solve this issue. 

This issue occures on the reference page for AnimateChildOptions, but it can also be found in other reference pages.

### Enter the URL of the topic with the problem

https://angular.dev/api/animations/AnimateChildOptions

### Describe the actions that led you to experience the problem

- Open the reference page for AnimateChildOptions
- Highlight the reference member for params
- Expected behavior: In the code fragment, the line for params is highlighted
- Actual behavior: The line for delay is highlighted or no line is highlighted

- Click the line in the code fragment for params
- Expected behavior: The line is highlighted
- Actual behavior: The line above is highlighted

### Describe what you want to experience that would fix the problem

The correct line is highlighted

### Add a screenshot if that helps illustrate the problem

https://github.com/angular/angular/assets/47561535/23940119-8b3e-4c82-a2df-ebf801197c91

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
Observed on both Chrome and Firefox
```

**Comment by sasidharansd** [comment] 2023-11-12 16:07
I guess the issue is not browser specific, it is due to resolution. On smaller resolution when the scroll bar is present, it works fine, but on a large resolution where scroll bar isn't available its not highlighting the correct api reference member.

**Comment by ArneCaluwe** [comment] 2023-11-12 18:32
I checked the code and noticed that the highlighting is done based of the scroll-offset which indeed explains why resolution would play a role here. 
I would love to have a crack at solving it, but that would be my first code-contribution to angular. I'm currently looking at [reference-scroll-handler service](https://github.com/angular/angular/blob/main/adev/src/app/features/references/services/reference-scroll-handler.service.ts)

**Comment by twerske** [comment] 2023-11-29 18:05
This is because we use the Angular router's scrolling and the highlight is beyond the scroll length of the page. We'd like to defer to the browsers scroll so I'm closing this as un-implimented!

**Closed by twerske** 2023-11-29 18:05 UTC
Labels: help wanted, good first issue, area: adev, area: adev-infra
