### ISSUE TITLE
Parent form only updates with patchValue and setValue if I am in debugging mode. (or sometimes it does, sometimes not)

### ISSUE THREAD

**Issue by ssaso** [angular/angular#51995] opened 2023-10-03 07:37 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

So I have this autocomplete:
(This is in children component) 
```
<mat-autocomplete #auto="matAutocomplete">
	<mat-option
		**(onSelectionChange)="addChosenOptionToResult(resultInput, $event, i)"**
		*ngFor="let option of autocompleteOptions$[i] | async"
		[value]="option"> {{ option }}
	</mat-option>
</mat-autocomplete>
```
And onSelectionChange I call this function:

```
	addChosenOptionToResult(inputElement: HTMLInputElement, event: MatOptionSelectionChange, index: number): void {
               const selectedOption = event.source.value; //let's say selectedOption is 'X'
               // >> Here goes some code where I apply my logic to inputValue which is not important for our scenario, so let's just set it as a normal string for our need <<

               const inputValue = 'test' + selectedOption;
		const control = this.transactionForm[index].get('result') as FormControl;
		control.setValue(inputValue); 
		console.log(control.value); //testX is printed
		console.log(this.parentFormGroup.value.transactions[0].result);  //testX is printed

		//Added this also to 'try' but still doesn't work
		control.updateValueAndValidity();
		// Also tried different approach like this one for example
		// const control = this.transactionForm[index];
		// control.setValue({ result: inputValue });

}
```

And then when I click save and access the form from my parent component:
`			console.log(this.formGroup.controls.transactions.value[0]['result']); //**X** is printed  (THE BUG)
`
And the strange thing is when I debug this then it works fine (testX is printed). And also sometimes it is OK, sometimes not.  
It is very strange and I have no idea what can be the problem.
Please help! :D

### Please provide the exception or error you saw

```true
If the  value accessing from the parent this.formGroup.controls.transactions.value[0]['result']) == testX
then is OK,

if it is only X then it is not OK, which event.source.value; //let's say selectedOption is 'X'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.4
Node: 18.16.1
Package Manager: npm 9.6.0
OS: win32 x64

Angular: 16.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by ssaso** [comment] 2023-10-03 09:32
I found a solution to this, but still have no idea why this happens. 

The solution is that now I save the inputValue at component lvl and then I patch it in another function that executes after onSelectionChange: 

`<mat-autocomplete #auto="matAutocomplete" (optionSelected)="patchValueToResultControl(i)">`

It is interesting that here in the patchValueToResultControl function the value is the one is chosen, not the one that I added in patchValue after onSelectionChange.

**Comment by JeanMeche** [comment] 2024-04-08 22:30
Since you found a solution and didn't provide a complete repro for investigation, I'll close this for now. 
If someone has a similar issue with a reproduction, feel free to file a new issue, thank you for your understanding.

**Closed by JeanMeche** 2024-04-08 22:30 UTC
Labels: area: forms
