### ISSUE TITLE
Remove references to deprecated QuickStart repo

### ISSUE THREAD

**Issue by JoeCool1986** [angular/angular#23868] opened 2018-05-12 02:29 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Setup guide (and also Upgrade from AngularJS guide) references QuickStart repo, even though it's deprecated

## Expected behavior

The guides references using Angular CLI, which is a replacement for QuickStart project

## What is the motivation / use case for changing the behavior?

Confusion for beginners

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jenniferfell** [comment] 2018-05-22 22:39
Deprecation note: https://github.com/angular/quickstart/blob/master/README.md

Definitely need to change: 
filename=https://angular.io/guide/setup
filename=https://angular.io/guide/upgrade

Needs review:
filename=https://angular.io/guide/setup-systemjs-anatomy

docsarea=setup

**Comment by jenniferfell** [comment] 2018-10-25 19:15
Quick update:
* Partial work done in v7. Removed from nav. Most xref links changed to quickstart.md 
* Next level of work is in https://github.com/angular/angular/pull/26758
* Final removal dependent on rewriting the upgrade information and other minor changes.

**Comment by jenniferfell** [comment] 2018-10-25 19:57
Closing as duplicate of https://github.com/angular/angular/issues/26461. That PR has more details.

**Closed by jenniferfell** 2018-10-25 19:57 UTC
Labels: comp: docs, freq2: medium, severity3: broken, state: has PR, subtype: docs-deprecated, type: bug/fix
