### ISSUE TITLE
Routing Authentication in Angular2

### ISSUE THREAD

**Issue by prashobh-k** [angular/angular#9059] opened 2016-06-07 10:40 UTC
i want to override the RouterOutlet class so that each time of routing it can check the localStorage for the user credentials for routing to that page.problem is that in angular RC1 method and class has been changed, so finding difficult to access the class for overriding.

**Comment by zoechi** [comment] 2016-06-07 11:05
dup of #8562

**Comment by prashobh-k** [comment] 2016-06-07 11:14
i don't find any connection between dup of #8562 and my question

**Comment by zoechi** [comment] 2016-06-07 11:17
>  so finding difficult to access the class for overriding.

They are not exported, therefore you can't import them and therefore can't override them. 

If this is not your issue, please make it more clear what the issue actually is.

**Comment by prashobh-k** [comment] 2016-06-07 11:20
i want to override the RouterOutlet class so that each time of routing it can check the localStorage for the user credentials for routing to that page( actually for Authentication).

code 


import { Directive,ElementRef,DynamicComponentLoader } from '@angular/core';
import{Routes} from '@angular/router';
import{ComponentInstruction,RouterOutlet,Router} from'@angular/router-deprecated'
@Directive({
  selector: '[authcheck]'
})
export class Authcheck extends RouterOutlet {
publicRoutes:any;
private parentRouter:Router;
  constructor(_elementRef:ElementRef,_loader:DynamicComponentLoader,_parentRourter:Router,@Attribute('name')nameAttr:string) {
    super(_elementRef,_loader,_parentRourter,nameAttr);
    this.parentRouter=_parentRourter;
    this.publicRoutes={
      'login':true
    };
    activate(instruction:ComponentInstruction){
      let url=ComponentInstruction.urlPath;
      if(!this.publicRoutes[url]&&!localStorage.getItem('user')){
        this.parentRouter.navigateByUrl('/login');
      }
      return super.activate(instruction);
    }
    
  }

}

**Comment by meeroslav** [comment] 2016-06-07 11:21
Hi, the issue is that previously the RouterOutlet had activate method which returned promise. This was easy to override by returning your custom promise (check localStorage, get config via http etc.). 
In new RouterOutlet this method is gone and replacement is load which returns ComponentRef so having a promise there is not possible.

**Comment by zoechi** [comment] 2016-06-07 11:22
The RC.1 router is deprecated AFAIK therefore migrating to it at this point probably isn't a good idea anyway. This probably won't be fixed.

**Comment by meeroslav** [comment] 2016-06-07 11:22
+ In the latest commits, RouterOutlet and RouterLink are exported, however this still doesn't solve the given issue.

**Comment by meeroslav** [comment] 2016-06-07 11:23
@zoechi: Do you have then another idea how to do this?

**Comment by zoechi** [comment] 2016-06-07 12:45
@meeroslav waiting for RC.2 and see if it contains a new router. Otherwise waiting for RC.3 or staying with router-deprecated until the new router arrives and is stable enough.

**Comment by ericmartinezr** [comment] 2016-06-07 12:52
@meeroslav stay away from the official router until it is released. Start looking at ngrx/router or ui-router.

**Comment by meeroslav** [comment] 2016-06-07 13:38
@ericmartinezr: I'll have a look at ngrx/router. UI-router is for 1.x only.
I've solved my problem (pre-loading data before first route kicks in) with help of APP_INITIALIZER.
@prashobh-k: I believe you can use **load** from new RouterOutlet to redirect user to login page. However, you'd still have to fake **ComponentRef** somehow.

**Comment by ericmartinezr** [comment] 2016-06-07 13:41
@meeroslav https://github.com/ui-router/quickstart-ng2

**Comment by a5hik** [comment] 2016-06-30 15:37
What would be the best way to do Router Authentication with the new Router version '3.0.0-alpha.X' ?
Any sample or a hint would be much helpful.

**Comment by zoechi** [comment] 2016-06-30 17:41
@a5hik Everything already in place https://angular.io/docs/ts/latest/guide/router.html#!#guards

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by a5hik** [comment] 2016-07-01 12:49
@zoechi Got it thanks!

**Closed** 2016-07-01 15:30 UTC
