### ISSUE TITLE
[router] CanActivate and DI

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4112] opened 2015-09-10 08:29 UTC
The `CanActivate` hook is available as a decorator. 
That's a bit surprising compared to all the other lifecycle hooks which are simple functions of the component. I understand the reason behind that (the hook is called before the component is instanciated), even if I think the API would be simpler if everything was a function...

If things stay like this, I have a question: will it be possible to use DI in the `CanActivate` hook?

Do you plan to support something like : 

    @CanActivate((userService: UserService) => userService.isAdmin())

**Comment by brandonroberts** [comment] 2015-09-10 21:17
I'm not sure if you will be able to do it that way, but you can use the injector in the CanActivate function. Here is a simple example: 

http://plnkr.co/edit/zoSAcCkAwQ1TfzxJaiSI?p=preview

**Comment by tamascsaba** [comment] 2015-09-14 14:24
You are created new Object from Auth, it is a not the original instance, as I know.

**Comment by btford** [comment] 2015-09-14 19:52
Yes, I plan to handle this case.

I think the hooks should be able to augment instructions with bindings to be passed to the component.

**Comment by cexbrayat** [comment] 2015-09-14 20:00
@btford Thanks for your answer

**Comment by frederikschubert** [comment] 2015-11-04 16:52
Has there been any activity regarding this issue? I would like to inject a router instance into the CanActivate hook of my component which is the root of my login-protected app. So if the user is not authenticated he will be redirected to the login page. I think this is essential for protecting an application.

Or is there any other way to accomplish this behavior?

**Comment by brandonroberts** [comment] 2015-11-04 18:06
@frederikschubert I have a simple workaround here. I store the application injector and use it to inject dependencies inside the CanActivate function.

http://plnkr.co/edit/SF8gsYN1SvmUbkosHjqQ?p=preview

**Comment by frederikschubert** [comment] 2015-11-04 19:41
Ok I see. Thanks! Still getting used to the new DI system. :)

**Comment by ribizli** [comment] 2015-11-04 19:45
It is still a workaround, but it works 😀

**Comment by janneromell** [comment] 2015-11-05 09:44
See this too:
https://github.com/angular/angular/issues/2965#issuecomment-152262966

**Comment by frederikschubert** [comment] 2015-11-05 15:58
@brandonroberts I implemented your workaround and it worked but I discovered some problems. When your evaluation of whether the user is logged in or not depends on Promises or Observables, then the content of the component that is protected in the `CanActivate` hook is visible for a fraction of a second before the user is redirected to the login component. I do not know if this can be prevented.

@janneromell I also tried implementing your use case where the user gets redirected to the initial requested url after he successfully logged in. This is not possible because the `CanActivate` hook only receives the `ComponentInstruction` for the annotated component. To implement this behavior it would be necessary to pass the full `Instruction` to the hook. @btford Is it planned to implement this?

**Comment by brandonroberts** [comment] 2015-11-05 16:18
@frederikschubert can you reproduce the component showing in a plunk? As I understand it, the component behind the CanActivate shouldn't be loaded until after the promise/value is returned as true.

**Comment by frederikschubert** [comment] 2015-11-06 11:10
@brandonroberts http://plnkr.co/edit/TdGv0XiExiOvaAFzRWKD
I found a problem with the `CanActivate` hook. I returned the subscription in my `isLoggedIn()` that in turn returned whether the user is authenticated or not via an Rx.Observable. Because the subscription is not undefined it is evaluated as true and the content is shown. After the Observable returned false however the user is redirected to the login page.
I think that this can happen quiet often and could be easily prevented by checking the outcome of the `CanActivate` hook to be exactly true (type safe). Snippet from my plunk:
```
@CanActivate((to, from) => {
  // This causes the intended behavior.
  // return isLoggedIn() === true;
  
  // This causes problems
  return isLoggedIn();
})
```

**Comment by panKt** [comment] 2015-12-29 04:09
Is there any workaround for now? I'm trying to inject **RouteParams** the way @brandonroberts proposed and it does not work this way. Here is updated plunker http://plnkr.co/edit/siMNH53PCuvUBRLk6suc?p=preview
it will say ```No provider for RouteParams!``` once you try on inject it (you need to click on *Protected Page* link)

**Comment by brandonroberts** [comment] 2015-12-29 04:19
@panKt you don't access route params that way. They are already provided as` to.params` and `from.params` in my plunker example.

**Comment by panKt** [comment] 2015-12-29 04:46
OMG, true :) Thanks, @brandonroberts

**Comment by ribizli** [comment] 2015-12-29 07:11
@frederikschubert you have to return a promise from the `isLoggedIn()` method as the documentation says. Observable has a `toPromise()` method what you can use for this purpose...

**Comment by danikenan** [comment] 2016-01-09 06:33
It's nice that we can use workarounds like the ones above(@brandonroberts  thanks), but this needs to be addressed by the core and simplified. Decorators such as CanActivate must be able to interact with the DI, namely be injected with there dependencies.
They are almost useless otherwise, or requires tons of complicating workarounds...

**Comment by Schnueggel** [comment] 2016-01-11 22:17
@brandonroberts thanks. Best solution so far.

**Comment by brandonroberts** [comment] 2016-01-12 03:38
The plunker example has been updated to beta.1

**Comment by nielslbeck** [comment] 2016-01-12 07:16
Great workaround, @brandonroberts. 

But in the real world I guess you would have an `ngOnInit` in `Auth.ts` where you would check in local storage or a remote server if you are already logged in, right? But `ngOnInit` isn't executed by the injector and thus `loggedIn` isn't updated to reflect the correct state. 

So we have to have another workaround where we manually call `ngOnInit`. But `ngOnInit` should only be called once so it has to remember whether it's been called before. 

Workaround on workaround... not pretty! 

I hope we get DI for decorators.

**Comment by brandonroberts** [comment] 2016-01-12 13:42
@nielslbeck Sure. There are plenty of ways to achieve the same outcome. The CanActivate function keeps your component from being loaded at all until it returns true. ngOnInit will never be called if the CanActivate function returns false because the component was never loaded.

**Comment by nolazybits** [comment] 2016-01-14 02:21
@brandonroberts thanks for the workaround in the meantime

**Comment by crowebird** [comment] 2016-01-14 19:55
@brandonroberts +1 +1 +1

By the doc comments for ComponentInstruction, the instance of ComponentInstruction is meant to be immutable, but I am performing a query in CanActivate to see if data exists for the route.  In performing that query I get data that I want to show on the page.  Rather than re-query once I get inside the class I need a way to pass that data inside.  To do this I am adding a key to the instance of componentinstruction with my data and retrieving it inside the routerOnActivate function.

Is there a better way?

**Comment by brandonroberts** [comment] 2016-01-14 20:45
@crowebird Another terrible workaround(disclaimer) is overriding the route data in the CanActivate. Then you can inject RouteData into your component and use it in the constructor instead of the routerOnActivate.

http://plnkr.co/edit/wWG8XB6SX2OPX5OklLfj?p=preview

**Comment by crowebird** [comment] 2016-01-14 20:51
@brandonroberts - Interesting!  I like that better than having to get the data through routerOnActivate.

Will have to work for now and I can just add a unique key to RouteData data instead of overwriting the whole thing.

**Comment by ThiagoT1** [comment] 2016-01-16 02:04
I need to recover a singleton instance while ate the CanActivate handler.

How ugly is this?

    ng.router.CanActivate(
        function () {
            return singletonService.Service.getInstance().getPromise();
        }
    )(AppComponent);

singletonService.Service.getInstance could be set inside its constructor.

**Comment by PascalPrecht** [comment] 2016-01-17 23:14
@ThiagoT1 actually, dependencies are already singletons by default as long as they are a) created by Angular's DI and b) injected in the same injector container.

**Comment by clemcke** [comment] 2016-01-26 19:56
I wrote a spec test that uses the appInjector() solution. (Based off of @brandonroberts  implementation) https://gist.github.com/clemcke/c5902028a1b0934b03d9

**Comment by astopo** [comment] 2016-02-15 19:40
+1 @brandonroberts thanks for the plunker! Would prefer not to inject services in bootstrap, but is a good work around for now.

**Comment by swunderlich** [comment] 2016-02-20 00:05
@brandonroberts Hi, I try to use your plunker http://plnkr.co/edit/SF8gsYN1SvmUbkosHjqQ?p=preview but I always end up with: 

> Cannot resolve all parameters for 'function (injector) {'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'function (injector) {' is decorated with Injectable.
angular2-polyfills.js:1243 Error: Cannot read property 'getOptional' of undefined(…)Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:401(anonymous function) @ angular2-polyfills.js:123Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262

Any ideas or somebody facing the same issue?

**Comment by brandonroberts** [comment] 2016-02-20 01:37
@swunderlich I just tried the plunker and it worked fine for me. That error means you have requested something that haven't been provided to dependency injection. The injector workaround uses the providers that are in your bootstrap, so if you haven't placed it there, you won't be able to get it using the injector. If you make a plunker of the error we'll be able to diagnose it better.

**Comment by swunderlich** [comment] 2016-02-20 07:57
@brandonroberts http://plnkr.co/edit/zVGnd8noWfbxwfuEVr9x?p=preview

**Comment by brandonroberts** [comment] 2016-02-20 17:14
@swunderlich you don't need the AppInjector in your bootstrap array and you need to add a base href to your index.html in the <head> section.

 `<base href=".">`

**Comment by swunderlich** [comment] 2016-02-21 15:51
Got it! Thanks so much!

**Comment by brandonroberts** [comment] 2016-02-23 03:30
@btford is there a way to provide a class to the CanActivate instead of a pure function and pass that class through the injector? This could be used for resolving providers also.

Proposal

```js
@Injectable()
class Authenticated implements BeforeActivate {
    constructor(public router: Router) {}

    routerBeforeActivate(next: ComponentInstruction, prev: ComponentInstruction) {
        if (notLoggedIn) {
            this.router.navigate(['/Login']);
            return false;
        }

        return true; // or return promise that resolves to true
    }
}


@CanActivate(() => Authenticated) or @CanActivate(Authenticated)
class ProtectedRoute{}
```

**Comment by tamascsaba** [comment] 2016-02-23 07:50
@brandonroberts nice idea :) must have feature :+1:

**Comment by fxck** [comment] 2016-02-23 20:23
Out of 10, I'd rate this 11 on scale of how important is this. Can't believe it's been like 6 months without this being resolved, or at least discussed about..

**Comment by keithotto** [comment] 2016-02-24 21:18
@brandonroberts Going off your example I was able to inject my user service to check if they're logged in. But I can't seem to redirect to another page properly from within the @CanActivate. I'm currently just trying to redirect back to the homepage, and the URL changes correctly, but it seems the content never gets loaded for that page. This is using beta.6.

```
@CanActivate((next, prev) => {
    let injector: Injector = appInjector(); // get the stored reference to the injector
	let userService: UserService = injector.get(UserService); 
    let router: Router = injector.get(Router);
    return new Promise((resolve, reject) => {
        if(!userService.loggedIn) {
            router.navigate(['/Home']);
            resolve(false);
        } else {
            resolve(true);
        }
    });
})
```

Have you encountered this problem at all?

**Comment by brandonroberts** [comment] 2016-02-25 00:36
@keithotto I haven't seen that before. Do you only have your ROUTER_PROVIDERS in the bootstrap array? Are you getting any errors?

**Comment by simonbrandl** [comment] 2016-02-25 10:15
+1
We really need a proper way to detect and handle unauthorized access.  I like @brandonroberts proposal!

**Comment by swunderlich** [comment] 2016-02-25 11:00
+1

**Comment by keithotto** [comment] 2016-02-25 17:07
@brandonroberts Looks like it's working now. I don't believe I had any other ROUTER_PROVIDERS being injected anywhere else, but I must have changed something that fixed it after the fact. Either way +1 for being able to have DI on @CanActivate!

**Comment by brandonroberts** [comment] 2016-02-25 17:11
@keithotto cool :+1:

**Comment by msak** [comment] 2016-02-26 12:55
I like @brandonroberts proposal, too!

**Comment by nikkwong** [comment] 2016-02-28 00:48
Call me a dummy but what is the purpose of 
````
bootstrap([ ... ])
]).then((appRef) => {
  appInjector(appRef.injector);
});
````

Why is it necessary that we need to use this instance of the injector?

**Comment by brandonroberts** [comment] 2016-02-28 01:26
@nikkwong Its the topmost injector in the tree that contains everything that was provided when the application was bootstrapped. It provides access to the root Router and whatever global services you provided that you want to share throughout the application.

**Comment by nikkwong** [comment] 2016-02-28 03:22
@brandonroberts awesome. thanks fro getting back to me. I guess at the stage: 

````
...
let userService: UserService = injector.get(UserService);
let router: Router = injector.get(Router);
let routeParams: RouteParams = injector.get(RouteParams);
````

doing something slightly more advanced like getting route paramters wouldn't be available correct? Seems unavailable: ```No provider for RouteParams!```
http://plnkr.co/edit/zesEp576GQ86Y6ZZaSTx?p=preview

**Comment by brandonroberts** [comment] 2016-02-28 03:27
@nikkwong you can get the RouteParams from the `next.params`. RouteParams are provided per component and since the injector used is essentially the main App component injector which is not a route component, it doesn't have RouteParams.

**Comment by fctucker09** [comment] 2016-03-02 01:54
+1

**Comment by mdekrey** [comment] 2016-03-03 01:42
:+1:

Thanks @brandonroberts for the proposal as an Injectable class. This also is a must-have feature for me, too. 

I also can't use the workaround provided, as I can't use a global Injector for my case (nor would I really want to anyway.)

**Comment by brandonroberts** [comment] 2016-03-03 03:12
@mdekrey you don't technically have to use the global injector. You can provide whichever injector that will give you the dependencies you need inside the CanActivate.

**Comment by whelanp** [comment] 2016-03-03 11:32
@brandonroberts your proposal. +1

**Comment by eXXeption** [comment] 2016-03-04 12:41
+1, really need this

Running in alot of Problems without having it.

But i got a case where it stops working.
In the "isLoggedIn" i use a service that provides the current user stuff.
if that service requires another service my app crashes. (Dependency unkown)
If i add that dependency to the bootstrap array too, it crashed with core_1.provide is a unkown function.

**Comment by brandonroberts** [comment] 2016-03-04 12:45
@eXXeption sounds like a different issue. Are you importing the provide function in your main app module and adding `@Injectable()` to your user service?

**Comment by tonimora74** [comment] 2016-03-08 12:08
@brandonroberts +1 +1 +1

it running very welll
thankssssss

**Comment by calbrecht** [comment] 2016-03-08 12:43
And then extending the @CanActivate decorator is as easy as:
```javascript
import {appInjector, UserService} from './shared/services/';
import {Router} from 'angular2/router';
import {makeDecorator} from 'angular2/src/core/util/decorators';
import {CanActivate as CanActivateAnnotation} from 'angular2/src/router/lifecycle_annotations_impl';

class CanActivateIfAuthenticatedAnnotation extends CanActivateAnnotation {
    constructor() {
        super((next, prev) => {
            let injector = appInjector();
            if (!injector.get(UserService).isAuthenticated()) {
                injector.get(Router).navigate(['Login']);
                return false;
            }
            return true;
        });
    }
}
export const CanActivateIfAuthenticated: () => ClassDecorator = makeDecorator(CanActivateIfAuthenticatedAnnotation);
```
Thanks @brandonroberts and angular

**Comment by SamVerschueren** [comment] 2016-03-10 20:26
Adding support for services isn't breaking as the current implementation still keeps working. It just adds support for a service (class).

Think I'd rather see this handled by a service to be honest and keep it more angular2 like. Providing an array of classes makes me feel like going back to angular1 with the `$inject`.

**Comment by brandonroberts** [comment] 2016-03-10 20:38
That's why I went with using a service like implementation. Seems more flexible if the CanActivate is going to be used for restricting routes and eventually resolving data.

**Comment by wardbell** [comment] 2016-03-12 01:09
I started exploring this again. I came up with my own preferred approach. But frankly, we're really stuck here. We can handle some scenarios with these tricks but not some of the most important ones.

The crux is that we have no opportunity to use the router or the injector that operates at the level of the target component. You're ok if you can reach what you need with the root injector and the root router.  But if you need something ... let's say a data service ... that isn't known to the root injector, you are toast.

In all of the scenarios above, you've made a critical assumptions: 
* you can use the root router to go where you want to go (namely the login page).
* the service you need that tells you if you're logged in is accessible from the root injector

Good for you. But if I've got services that are only available in feature areas that I reach via a child router, I'm hosed. Why? Because the services I need aren't defined at the root injector level. If I try to resolve them at the root level, it will create a service instance at the root level ... which is not the same service instance that a child component will inject later. That's ok if the service is stateless; it's not ok if the service is stateful (e.g., if it caches).

This is just a mess.  AFAIK, it won't be addressed before v.1.

At least you have a way to handle the auth requirements.

**Comment by brandonroberts** [comment] 2016-03-12 02:15
Care to share what your preferred approach is @wardbell?

**Comment by cexbrayat** [comment] 2016-03-12 07:15
I opened this issue 6 months ago, and it has come up  again and again in the projects I've seen, exactly with the problem explained by @wardbell. 

I really hope the team will consider it for v1

**Comment by robwormald** [comment] 2016-03-12 08:33
note this is included in the RC candidate milestone: https://github.com/angular/angular/milestones/Angular%202%20Release%20Candidate

**Comment by brandonroberts** [comment] 2016-03-12 15:37
@cexbrayat @wardbell can one of you explain how you expect this to work? Do you want the providers and/or dependencies from the component that hasn't been created yet to be available to the CanActivate and then that same instances to be provided to the component once the CanActivate passes?

**Comment by wardbell** [comment] 2016-03-12 17:51
@brandonroberts I think my answer is "yes".  I think that's reasonable as those are resources that will have to become available to instantiate that component.

I think that implies creating the injector instance (or proto) and scoped service instances that _will be injected_ into the target component _if it passes the `CanActivate` test_.

Of course, we have to account for that in a (future) world of just-in-time, dynamically loaded "feature modules". It's not just about lazy loading components; it's about lazy loading _anything_.

Frankly, I keep coming back to my suspicion that `CanActivate` is a well-intentioned mistake. It seemed like a good (and clever) idea to check a class method. No worries about what the freshly created instance might run off and do on its own. But we've since learned how that path is fraught with complications.

These complications would disappear and clarity would flow if it were an instance method, executed _after_ the component is constructed and _before_ any  other lifecycle hook!  Ideally before any attempt by A2 to evaluate bindings to the component or do anything with the component.

As developers of the component, we would be responsible for ensuring that the component constructor did no work. No running off to the database. It should simply wire up component values. And that's what I recommend to everyone _anyway_.

There is such a candidate router method, `OnActivate`.  I'd say "forget about that `CanActivate` and just use `OnActivate`." Unfortunately, as yet I am unable to get that method to work as advertised.  That's an issue I'm exploring separately.

p.s.: @brandonroberts  - I'd like to talk to you by email but don't know how to reach you. You can email me at my github contributor address. Thanks!

**Comment by wardbell** [comment] 2016-03-12 21:59
FYI, I just filed issue #7576 regarding my troubles with `OnActivate`.

**Comment by brandonroberts** [comment] 2016-03-14 13:52
Thanks @wardbell for the explanation. I agree that the constructor should be thin and be used for simply wiring things up. Its an easy trap for developers to fall into making the constructor very heavy and putting logic there. The `OnActivate` method could work if you push the routes down a level to another outlet also.

**Comment by IsaacBorrero** [comment] 2016-03-19 23:05
Just adding my request for this feature.  I am happy to see it will be addressed in RC1.  I need to verify a user is authorized before navigating to various routes.

**Comment by borispk** [comment] 2016-03-26 11:42
I just wonder inside CanActivate calling a call back function,  say calling an API through http request.  As the http returns is a call back function to determine the page is show or not depends on the return value.  However,  after calling the http request API, the async frature would go to the final step of CanActivate function. As a result,  the activate behavior does not depend on the API return value.  Is there any work around?

**Comment by zoechi** [comment] 2016-03-26 12:02
@borispk can you provide a Plunker that shows what you try to accomplish? Just completing the `Promise` when the response is processed shouldn't be difficult.

**Comment by PascalPrecht** [comment] 2016-03-26 12:12
@wardbell can you please share your solution for this? The one you've
mentioned? I think it's good to see and evaluate different approaches as we
don't have a go-to solution yet.

Thanks!

**Comment by wardbell** [comment] 2016-03-27 03:21
@PascalPrecht @brandonroberts @cexbrayat and others: you may find interesting the design "issue" I just created as #7784 which explores my (limited) understanding of what might be.

**Comment by borispk** [comment] 2016-03-29 07:00
Thank @zoechi  and others, Here is my code for the captioned problem. See if you have any advice.

`@CanActivate(next: ComponentInstruction, prev: ComponentInstruction) => {
let rtn = funHttpAPI(username, (allowAccess) => {
             return allowAccess;                           // callBack function of funHttpAPI, Suppose allowAccess = true, then CanActivate return true, or otherwise.
      }

 return false;                                                // the page hold up here if return false, otherwise, the page is opened and not wait for funHttpAPI return value.
})`

**Comment by zoechi** [comment] 2016-03-29 07:25
@borispk I think you should one of the channels listed in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question with a Plunker that allows to reproduce if possible.

**Comment by kemsky** [comment] 2016-04-02 22:23
In fact, we need injection in every decorator or API should be reworked. Imagine you have `loader` property set in your route definition, obviously you may want to access model, service or whatever else to decide which component to load. Otherwise developers would have to implement there own routing using Dynamic Component Loader or various static hacks as shown above.

**Comment by DrewynV** [comment] 2016-04-05 00:29
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166504.
------------------------------------------------------------------------------------------------------------


[[f52d9405d42b4e280285d4ee59bacd804ec32b68-673073910]]

**Comment by DrewynV** [comment] 2016-04-05 00:29
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166511.
------------------------------------------------------------------------------------------------------------


[[e55b2d243c912df36cc390d34acb0cc3bf9ef2b2-673073919]]

**Comment by DrewynV** [comment] 2016-04-05 00:31
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166553.
------------------------------------------------------------------------------------------------------------


[[9406a1d9dc4a85e54ed3162db444d394fce7591d-673074178]]

**Comment by ribizli** [comment] 2016-04-05 04:01
Hi, 

I've read an article in the last days, where a custom router-outlet was used to control access to the routes. This component has an activate method where things can happen. DI works as usual in components. 

What do you think about that solution? Can it replace the @CanActivate logic?

**Comment by jamalsoueidan** [comment] 2016-04-06 21:53
Is there any good example how to wait for Angular 2 to load/resolve model before rendering view/template?

I have this problem on all "nested components", because the main application load the json component, this also make my development slow, since I need to navigate every time to nested component to check everything is working! 

Thank you

**Comment by divined** [comment] 2016-04-11 21:22
and what about role based routes?

@CanActivate(roleCheck($roleName))

**Comment by syndicatedshannon** [comment] 2016-05-02 17:08
I'd like to mention that I'm using this feature, CanActivate + DI, as a workaround for another issue; Route Dependency Resolution. I just ran into an issue where this feature (CanActivate + DI) no longer meets my needs for that workaround because the CanActivate hook is not run for AuxRoute Components.

https://github.com/angular/angular/issues/4015

This may not be a problem for more legitimate uses of CanActivate, but I thought I'd mention it.

**Comment by DrClick** [comment] 2016-05-09 15:47
So I found an interesting solution the problem of alllowing routes based on an auth service. Using a directive with transclusion. 

```
import {Component, OnDestroy, OnInit } from '@angular/core';
import {AuthService} from './auth.service';
import {ROUTER_DIRECTIVES, Router, OnActivate} from "@angular/router-deprecated";
import {Location} from "@angular/common";

@Component({
    selector: 'protected',
    template: `
        <div class="jumbotron" *ngIf='!isAuthenticated()'>
        <div class="container">
            <h1 class="display-3">Welcome to the dark side</h1>
            <p class="lead">You must first <a (click)="login()">login</a>
            to access this resource</p>
        </div>
        </div>
        <div *ngIf='isAuthenticated()'>
            <ng-content></ng-content>
        </div>
    `
})

export class ProtectedComponent implements OnInit, OnDestroy {
    private logoutSubscription: any = null;

    constructor(
        private authService: AuthService,
        private router: Router,
        private location: Location) {
    }

    isAuthenticated() {
        return this.authService.isAuthenticated();
    }

    ngOnInit() {
        debugger
        this.logoutSubscription = this.authService.subscribe((val) => {
            if (!val.authenticated) {
                this.location.replaceState('/');
                this.router.navigate(['Home']);
            }
        });
    }

    ngOnDestroy() {
        if (this.logoutSubscription != null) {
            this.logoutSubscription.unsubscribe();
        }
    }

    login() {
        this.authService.doLogin();
    }
}
```

then in my component I want to protect
```
...
import {ProtectedComponent} from "../shared/protected.component";


@Component({
   ...
    template: `
        <protected><router-outlet></router-outlet></protected>
      `,
   ...
    directives: [RouterOutlet, ProtectedComponent],
    ...
})


export class ModelMetricsComponent {

}


```

**Comment by jkyoutsey** [comment] 2016-05-19 18:02
Does anyone have an example of how to unit test a class that depends on the app injector?  Since jasmine/karma abstracts the `bootstrap` process, how do I create/reference the injector in my unit test?

In main.ts
```javascript
bootstrap(AppComponent, [
    ...
]).then((appRef: ComponentRef<AppComponent>) => {
        AppInjector.getInstance().setInjector(appRef.injector);
    },
    error => console.log(error)
    );
```
In class constructor:
```javascript
        let injector: AppInjector = AppInjector.getInstance();
        this.uiStateService = injector.getInjector().get(UiStateService);
```

All works.  But unit tests can't find the injector.

**Comment by brandonroberts** [comment] 2016-05-19 19:36
@jkyoutsey see higher up in the thread: https://github.com/angular/angular/issues/4112#issuecomment-175200243

**Comment by nolazybits** [comment] 2016-06-16 21:51
Seems that this is now working as @brandonroberts said on gitter.
Link of working example is http://plnkr.co/edit/gQcyGu?p=preview

**Comment by nolazybits** [comment] 2016-06-16 23:10
Ooops, that is for the new Router v3 not the deprecated v2. Yet people will be glad to see it works in v3 :)

**Comment by zoechi** [comment] 2016-06-22 05:40
I guess this can be closed now the new router is available and supports this use case.

**Comment by vicb** [comment] 2016-06-22 05:59
Please reopen if still a problem (thanks @zoechi)

**Closed by vicb** 2016-06-22 05:59 UTC
Labels: comp: router-deprecated, effort2: medium (day), P2: required, type: feature

**Comment by Chabane** [comment] 2016-09-09 23:09
I got this error with rc6 : 

Uncaught TypeError: core_1.provide is not a function

**Comment by Delagen** [comment] 2016-09-10 07:52
provide is obsolete, use plain object notation

**Comment by Chabane** [comment] 2016-09-10 11:33
@Delagen Yes, but my only provider declaration is dedicated for ng2Translate
 
```
 TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),
            deps: [Http]
        })
```
