### ISSUE TITLE
lifecycle onChange doesn't work on top level component

### ISSUE THREAD

**Issue by gdi2290** [angular/angular#2192] opened 2015-05-27 20:21 UTC
```coffeescript 
lifecycle: [onChange]
``` 
doesn't work on the top level component

**Comment by vicb** [comment] 2015-05-27 20:24
probably the same root cause as https://github.com/angular/angular/issues/1858

**Comment by mhevery** [comment] 2015-08-21 03:47
dup of #1858 closing

**Closed by mhevery** 2015-08-21 03:47 UTC
Labels: comp: core/change_detection, effort2: medium (day), P2: required, state: Periodic Review, type: bug
