### ISSUE TITLE
Simplify the navigation for in-depth guides

### ISSUE THREAD

**Issue by mgechev** [angular/angular#54203] opened 2024-02-01 17:39 UTC
### Describe the problem that you experienced

Currently the list contains an overwhelming amount of topics and we should consider simplifying it.

**Comment by danieljancar** [comment] 2024-02-02 06:08
Hey @mgechev, 
You're absolutely right, feel like a more nested navigation based on the categories would be helpful.

**Comment by surajy93** [comment] 2024-02-24 21:19
Assign to me I can surely resolve this,🫣

**Comment by danieljancar** [comment] 2024-02-25 11:46
Hey @surajy93,
I think @bencodezen already works on it, otherwise you can just create your own fork/pull request with suggestions on how to improve the in-depth navigation. 😉

**Comment by bencodezen** [comment] 2024-02-29 17:24
Appreciate the enthusiasm @surajy93! The issue is already in PR, but we'd welcome your contributions on other issues you see in the queue!

**Closed** 2024-03-14 16:07 UTC
Labels: P1, area: adev
