### ISSUE TITLE
Design: named outlet API is sort of weird

### ISSUE THREAD

**Issue by robwormald** [angular/angular#9470] opened 2016-06-22 19:04 UTC
_From @robwormald on June 5, 2016 3:17_

The current mechanism for multiple components rendered into multiple views is sort of strange, as compared to ngrx's relatively straightforward syntax.

```js
//ngrx
const routes: Routes = [
  {
    path: '/blog',
    components: {
      main: Blog,
      sideMenu: RecentPosts
    }
  }
]
```

UI-router implements a similar pattern:
```js
//ui-router
{
  url: '/blog',
  views: {
    main: {
      templateUrl: 'blog.html',
      controller: 'BlogController'
    },
    sideMenu: {
      templateUrl: 'recent.html',
      controller: 'RecentController'
    }
  }
}
```

For vladivostok I reckon a similar pattern is better, though perhaps "outlets" is a better key name:

```js
{
    path: '/blog',
    outlets: {
      main: Blog,
      sideMenu: RecentPosts
    }
  }
```

cc @vsavkin @MikeRyan52 @brandonroberts 

_Copied from original issue: angular/vladivostok#18_

**Comment by choeller** [comment] 2016-06-23 05:32
Maybe I don't fully get the idea, but isn't the current mechanism much more flexbile then the one suggested? 
So the use-case I just solved with a secondary outlet, is that, when I mark an entry in a list, I show a summary of that entry in the sidebar. For that I need to dynamically decide which component with what data I want to load into the secondary outlet (If no entry is marked I don't want to load anything into it). This is perfectly possible with the current approach:

```ts
export const APP_ROUTES: RouterConfig = [
  {path: '', component: DashboardComponent}, //Dashboard direkt unter dem Root-Pfad
 ...
  /** Aux-route **/
  {path: 'overview', component: TaskOverviewComponent, outlet: "right"},
];
```

```ts
    this.router.navigate(["/right:taskoverview", {id: taskId}]);
```

Would that also be possible with the suggested mechanism?

**Comment by choeller** [comment] 2016-06-23 05:55
Ah I guess I got it: the suggested syntax would make it possible to easily load a component into a named outlet *initially*. Loading another component into that outlet via a link would still work, right?

**Comment by vsavkin** [comment] 2016-06-25 18:44
After talking about it with a few people, this is a nee, more concrete, description of the problem.

We often have a few siblings that form some notion of a "screen". They are not independent. They always come together. Say you want to show TeamList and TeamDetails next to each other. Both of them need some teamId.

One way to solve it would be to model the two components separately in the url, as follows:

/team/11(details:team/11)

The issue is that we repeat the id in two places. 

Another way to solve it would be to have a bogus parent component

```
{
  path: 'team/:id',
  component: Team,
  children: [
    {path: '', component: List}
    {path: '', component: Details, outlet: 'details'}
  ]
}
```

so you can navigate to:

/team/11

and you will see the two components side by side. 

The issue here is that need to have the bogus component, and both the details and the list components have to access the id via parent.

That is why we introduced the notion of componentless routes.

```
{
  path: 'team/:id',
  children: [
    {path: '', component: List}
    {path: '', component: Details, outlet: 'details'}
  ]
}
```

so you can navigate to:

/team/11

And the two components will be instantiated. In addition, we automatically merge the parameters of componentless routes into their children. So both the list and details components can access `id` directly.

**Closed by vsavkin** 2016-06-25 18:44 UTC
Labels: comp: router

**Comment by yvoronen** [comment] 2016-07-27 21:57
Does the above example work in latest router?

**Comment by chenyingyin** [comment] 2016-12-01 04:05
![default](https://cloud.githubusercontent.com/assets/24284270/20781516/651ae690-b7be-11e6-9747-a9eef2ce43b7.png)
![Uploading 图片.png…]()
