### ISSUE TITLE
Arrow function in angular1_router code

### ISSUE THREAD

**Issue by calebegg** [angular/angular#8074] opened 2016-04-14 22:01 UTC
There's an arrow function in the angular1_router code that prevents the JS from being run in IE unless it's transpiled.

https://github.com/angular/angular/blob/master/modules/angular1_router/src/module_template.js#L99

**Comment by brandonroberts** [comment] 2016-04-14 22:20
Dupe of #7913

**Comment by jelbourn** [comment] 2016-04-14 23:44
Closing as dupe of #7913

**Closed by jelbourn** 2016-04-14 23:44 UTC
