### ISSUE TITLE
Yes?mb no.

### ISSUE THREAD

**Issue by ViktorBKod** [angular/angular#53224] opened 2023-11-28 12:41 UTC
### Describe the problem that you experienced

Card to : command references
Page Not Found 🙃
If you think this is a mistake, please [open an issue](https://github.com/angular/angular/issues/new?template=3-docs-bug.yaml) so we can fix it.

### Enter the URL of the topic with the problem

https://angular.dev/cli/commands

### Describe what you were looking for in the documentation

Short commands

### Describe the actions that led you to experience the problem

pressing the card to command Reference

### Describe what you want to experience that would fix the problem

fix the link and add content with a table of short command for me to see and learn

### If this problem caused an exception or error, please paste it here

```true
<docs-viewer _ngcontent-ng-c2279891254="" class="docs-viewer ng-star-inserted">
  <!-- Document Header -->
  <header class="docs-header">
    <docs-breadcrumb></docs-breadcrumb>

    
  <!-- Page title -->
  <div class="docs-page-title">
    <h1 tabindex="-1"><span class="docs-emoji">Page Not Found 🙃</span></h1>
    <a class="docs-github-links" target="_blank" href="https://github.com/angular/angular/edit/main/adev/src/content/error.md" title="Edit this page" aria-label="Edit this page">
      <!-- Pencil -->
      <!-- <docs-icon role="presentation">edit</docs-icon> -->
    </a>
  </div>
  </header>
  <p>If you think this is a mistake, please <a href="https://github.com/angular/angular/issues/new?template=3-docs-bug.yaml" target="_blank">open an issue</a> so we can fix it.</p>
</docs-viewer>
```

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
chrome
```

**Comment by JoostK** [comment] 2023-11-28 12:42
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52549.

**Closed by JoostK** 2023-11-28 12:42 UTC
