### ISSUE TITLE
Code coverage measurement prevents DI to function properly in abstract services

### ISSUE THREAD

**Issue by hodossy** [angular/angular#43054] opened 2021-08-05 08:58 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have an abstract base service with an optionally injected configuration, and a concrete child class that do not override the constructor. During testing `ng test` passes, but in the CI, which has code coverage measurement, fails. I have created a minimal reproduction repository.

There are two conditions in which the test runs fine with code coverage measurement:
- If there is no implementation in the child class, i.e. the body is empty (`{}`)
- The constructor is overridden and Injection happens there

Current behavior: `ng test` passes while `ng test --code-coverage` fails
Expected behavior: `ng test` and `ng test --code-coverage` passes 

### Please provide a link to a minimal reproduction of the bug

https://github.com/hodossy/angular-inject-error-in-tests

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.0
Node: 14.16.0
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by JoostK** [comment] 2021-08-05 10:07
Duplicate of #31337.

**Closed by JoostK** 2021-08-05 10:07 UTC
