### ISSUE TITLE
(Reactive Forms)Radio name and formControlName must match in child formGroup

### ISSUE THREAD

**Issue by zamzowd** [angular/angular#23319] opened 2018-04-11 16:40 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using a Reactive Form that contains a radio control inside of a form group, an error is thrown when setting both the `name` and `formControlName` attributes:

`If you define both a name and a formControlName attribute on your radio button, their values must match.  Ex: <input type="radio" formControlName="food" name="food">`

This occurs when following the same naming convention that works for other controls: the input is under an element with `formGroupName=groupName` and `name` is `groupName.controlName` and `formControlName` is `controlName`.

When the radio control is in a FormArray, the value does not get included in the FormData created from the HTMLFormElement.

## Expected behavior

Radio form controls with both attributes `name` and `formControlName` should work inside of FormGroup and FormArray of a Reactive Form without throwing an error.

More significantly, the value of radio form controls that (a) are inside a FormArray and (b) have the `name` attribute set on the `input` element should be included in the FormData when submitting the form.

## Minimal reproduction of the problem with instructions

**Minimal Demo:** https://plnkr.co/edit/3FIQgYsx0b7hrpNDLDdR?p=preview

**Steps to Reproduce:**

1. Create a Reactive Form with a FormGroup and/or a FormArray
2. Add `<input type="radio">` elements for a form control within a FormGroup and/or a FormArray.
3. Set both the `name` and `formControlName` attributes of the radio inputs.
4. **Bug:** An error is logged in the console for each radio input:
`If you define both a name and a formControlName attribute on your radio button, their values must match.  Ex: <input type="radio" formControlName="food" name="food">`
5. Submit the form using the FormData created from the HTMLFormElement.
6. **Bug:** the values of the radio inputs inside of a FormArray are not included in the FormData.

## What is the motivation / use case for changing the behavior?

Radio form controls with both attributes `name` and `formControlName` should work inside of FormGroup and FormArray of a Reactive Form without throwing an error.

More significantly, the value of radio form controls inside a FormArray should be included in the FormData when submitting the form.  FormData is used for forms that also include file inputs.

## Workaround
Don't set the `name` attribute of radio form controls.  On submit, get the values of the radio form controls in a FormArray using [AbstractControl.value](https://angular.io/api/forms/AbstractControl) and add them to the FormData using [FormData.append()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append)

## Environment

<pre><code>
Angular version: 5.2.9

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by LinBoLen** [comment] 2018-04-16 06:29
maybe should remove `@host` annotaion on `formControlName`

**Comment by kara** [comment] 2018-05-03 22:57
Radio buttons must have matching `name` and `formControlName` attributes in order for the grouping to work properly, which is why we throw the error. Closing as it works as intended.

**Closed by kara** 2018-05-03 22:57 UTC
Labels: comp: forms

**Comment by zamzowd** [comment] 2018-05-04 13:19
@kara I don't think it is working as intended.

1. For all other controls, the `name` has to follow the property selection path of parent FormGroups and FormArrays.  When inside a `FormGroup`, the `name` has to be `{{formGroupName}}.{{formControlName}}`.  When inside a `FormArray`, the `name` has to be `{{formArrayName[{{index}}].{{formControlName}}`.

2.  The error message seems to be inaccurate for radio controls inside of a `FormGroup`.  Even though the error is thrown when I follow the pattern described above for a radio button in a `FormGroup`, that is the only way to get it to work.  This is demonstrated with the `meta.publisher` radio buttons in the plunker above.  If the `name` and `formControlName` values match, then the resulting `FormData` does not match the desired model.  When using the pattern described above, everything seems to work correctly despite the error message.

If this really is working as intended, could you demonstrate how to use radio button controls inside of a `FormGroup` and `FormArray` such that the submitted `FormData` has the correct property names for the desired model?

If a working demonstration cannot be provided, then can this issue be re-opened?

If using radio button controls in a `FormGroup` or `FormArray` cannot be used for a reactive form used to generate `FormData`, should that be acknowledged in the documentation?

(It looks like my plunk broke because of npm package version dependencies.  I've fixed it and updated the link to use angular 5.2.10 and rxjs 5.5.10.)

**Comment by mlc-mlapis** [comment] 2018-05-04 13:33
@zamzowd ... but isn't the `name` property just a string? And for radio-buttons and check-boxes the name has to be the same for all items.

**Comment by zamzowd** [comment] 2018-05-04 13:37
I've created a new plunk to demonstrate the behavior when making the `name` and `formControlName` match.  The submitted FormData is always _null_ for radio controls inside of a FormGroup or FormArray.

https://plnkr.co/edit/XGWR616adDzK2lreusN6?p=preview

@mlc-mlapis Yes, the `name` property is a string.  I was describing the naming pattern used.  I am correctly using the same `name` value for all radio inputs in the same group.  Please see the linked plunks.

**Comment by mlc-mlapis** [comment] 2018-05-04 13:58
@zamzowd ... I think that it is related to the `submit` event. I look it as the reactive forms have nothing to do with HTML tag `<form>` at all. They even don't have `submited` property, while template based forms have it.

I always use reactive based forms totally without `<form>` tag and I use something like:
```
<ng-container [formGroup]="myReactiveForm"> .... </ng-container>
```
and I also use only subscriptions to changes in the model like:
`this.myReactiveForm.valueChanges.subscribe((values) => {...});`

So I detect every change in the model ... and submit is just an usual event under some user action in UI ... as many others actions ... so I have events like `init`, `reset`, `undo`, `redo`, ...

If I add the subscription to your demo, then the modal data looks as:

![image](https://user-images.githubusercontent.com/5693835/39631595-e737ef32-4fb2-11e8-818a-0bf90e717d67.png)

**Comment by zamzowd** [comment] 2018-05-04 14:03
@mlc-mlapis I need to use the `submit` and `FormData` because I need to include a file attachment in my form.  Just getting the reactive form `value` json object does not include that.

Is this to say that Reactive Forms should not be used in conjunction with the form `submit`?  I'm using Reactive Forms because of the additional validation functionality they provide, including validators for file attachments.

**Comment by mlc-mlapis** [comment] 2018-05-04 14:17
@zamzowd ... I am not sure. And as I said there isn't `submitted` property. So I vote for: `Don't use it.` Also, I don't use mixed FormData of course. Just sending structural data when I want and if there is a file(s) then I send it ahead of time ... to minimize complications on the server side and keep the user happier because he can see live updates continuously.

**Comment by zamzowd** [comment] 2018-05-04 14:25
Some additional information I've found:

In the final html, the `name` property for radio inputs inside of a FormArray is _absent_ regardless of the value set in the Angular template.  The `name` property remains for radio inputs inside of a FormGroup.  That is why the values for radio inputs in a FormArray are absent but the values for radio inputs in a FormGroup are not.

**Comment by mlc-mlapis** [comment] 2018-05-04 14:30
@zamzowd ... hmm, interesting ... I didn't know it because I never used `submit` on reactive forms. 😸

**Comment by mlc-mlapis** [comment] 2018-05-04 14:33
@zamzowd ... no, it is still just `status`:
![image](https://user-images.githubusercontent.com/5693835/39633645-dd0da9e2-4fb8-11e8-98c4-47db8d5f4d65.png)

**Comment by zamzowd** [comment] 2018-05-04 14:43
@mlc-mlapis I was mistaken on my original post.  `name` gets dropped when I try to set it using the array index, in the first plunk.  I edited my post to reflect that.  Similarly, if it's set `name="{{'status'}}"` then the name property gets dropped.

I think it's less to do with being inside a FormArray and more to do with accepting an interpolated value.

**Comment by mlc-mlapis** [comment] 2018-05-04 14:47
@zamzowd ... ah, a positive step ... forward. 😄

**Comment by mlc-mlapis** [comment] 2018-05-04 14:49
@zamzowd ... because it should `name="{{status}}"`. As interpolation works ... OK.

**Comment by zamzowd** [comment] 2018-05-04 14:55
@mlc-mlapis `name="{{'status'}}"` interpolates in the string `'status'` as the value.  We can also set `statusName: string = 'status';` in the component and then use `name="{{statusName}}"` like you describe for the same effect.  That also results in the `name` property getting dropped from the final html.

**Comment by zamzowd** [comment] 2018-05-06 12:16
Added PR #23727 as my proposal to fix the enforced naming of radio controls inside of FormGroups or FormArrays.
