### ISSUE TITLE
[Ivy - 9.0.0-rc1] Random R3InjectorError error while testing projects

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular#33757] opened 2019-11-12 12:35 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

With Angular 8 and ViewEngine tests run fine.

### Description

Every now and then when I run `ng test` for all the projects in the workspace I randomly get the following error: 
```
NullInjectorError: R3InjectorError(DynamicTestModule)[ApplicationInitStatus -> ApplicationInitStatus]:
```

Error appears in 5/10 cases, which makes it very hard to reproduce.

## 🔬 Minimal Reproduction

I am still struggling with pinning down what exactly causes this issue. I do not have the exact reproduction yet, but will update this question as soon as I find out, but maybe someone in the community has the same issue.

## 🔥 Exception or Error
```
11% building 16/16 modules 0 active12 11 2019 13:19:39.819:WARN [karma]: No captured browser, open http://localhost:9876/
12 11 2019 13:19:39.904:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
12 11 2019 13:19:39.904:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
12 11 2019 13:19:39.930:INFO [launcher]: Starting browser ChromeHeadless
12 11 2019 13:19:44.886:WARN [karma]: No captured browser, open http://localhost:9876/
12 11 2019 13:19:44.927:INFO [HeadlessChrome 78.0.3904 (Mac OS X 10.14.6)]: Connected on socket eY5cp4fpj7oZSNYnAAAA with id 81970510
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6) SearchService should be created FAILED
        NullInjectorError: R3InjectorError(DynamicTestModule)[ApplicationInitStatus -> ApplicationInitStatus]: 
          NullInjectorError: No provider for ApplicationInitStatus!
        error properties: Object({ ngTempTokenPath: null, ngTokenPath: [ 'ApplicationInitStatus', 'ApplicationInitStatus' ] })
            at <Jasmine>
            at NullInjector.get (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:895:1)
            at R3Injector.get (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:18046:1)
            at R3Injector.get (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:18046:1)
            at NgModuleRef$1.get (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:35741:1)
            at R3TestBedCompiler.finalize (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:1979:24)
            at TestBedRender3.get testModuleRef [as testModuleRef] (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3299:1)
            at TestBedRender3.inject (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3160:1)
            at Function.inject (http://localhost:9876/path-to-project/node_modules/@angular/core/__ivy_ngcc__/fesm2015/testing.js:3045:1)
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/src/lib/example.service.spec.ts:9:44)
            at ZoneDelegate.invoke (http://localhost:9876/path-to-project/node_modules/zone.js/dist/zone-evergreen.js:365:1)
HeadlessChrome 78.0.3904 (Mac OS X 10.14.6): Executed 1 of 26 (1 FAILED) (0 secs / 0.011 secs)
```

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 9.0.0-rc.1
Node: 10.17.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.1
@angular-devkit/build-angular      0.900.0-rc.1
@angular-devkit/build-ng-packagr   0.900.0-rc.1
@angular-devkit/build-optimizer    0.900.0-rc.1
@angular-devkit/build-webpack      0.900.0-rc.1
@angular-devkit/core               9.0.0-rc.1
@angular-devkit/schematics         9.0.0-rc.1
@angular/cdk                       9.0.0-rc.0
@angular/flex-layout               8.0.0-beta.27
@angular/localize                  9.0.0-rc.0
@angular/material                  9.0.0-rc.0
@angular/pwa                       0.900.0-rc.1
@ngtools/webpack                   9.0.0-rc.1
@schematics/angular                9.0.0-rc.1
@schematics/update                 0.900.0-rc.1
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2

**Anything else relevant?**

**Comment by kara** [comment] 2019-11-12 20:02
@klemenoslaj Thanks for the report! Let us know when you have a repro so we can look into this

**Comment by IgorMinar** [comment] 2019-11-13 08:22
this might have been fixed already, please test with rc.2 (due tomorrow) and if the issue still exists please provide steps to reproduce this.

**Comment by klemenoslaj** [comment] 2019-11-13 12:32
> this might have been fixed already, please test with rc.2 (due tomorrow) and if the issue still exists please provide steps to reproduce this.

I will do that, thanks!

---

I still couldn't reproduce this in 100% of cases, however I think `ngcc` with `--async=false` made a difference (_still testing, takes ages_).

**Comment by klemenoslaj** [comment] 2019-11-14 10:07
We can still reproduce this after updating to rc.2 and it is still fixed with `--async=false`.  
Does the order of `ngcc` compilation matter? Is it possible for the sequence to somehow be incorrect when running in asynchronous mode?

---

I will try to extract our dependencies and reproduce it in a clean project, hopefully it will be sufficient reproduction already.

**Comment by IgorMinar** [comment] 2019-11-19 06:40
Thanks @klemenoslaj, a repro of the issue would really help us figure out what's going on here.

**Comment by klemenoslaj** [comment] 2019-11-19 07:36
I am trying but cannot nail it down really.

Instead, I will share later today the project I am playing on and rough reproduction steps.

---

Observations so far:
- Only reproducible with `--async=true`
- It is reproducible in roughly 5/10 cases
- Triggering the exact same sequence of ngcc as when the tests are failing is not reproducing the problem
- If I reduce the libraries too much in an attempt to minimize the noise it starts working 10/10
- Libraries/dependencies are mostly unused

**Comment by klemenoslaj** [comment] 2019-11-19 14:32
@IgorMinar I created a repo where I hope you will be able to reproduce the problem: https://github.com/klemenoslaj/angular-ivy-test-errors

---

From [README.md](https://github.com/klemenoslaj/angular-ivy-test-errors/blob/master/README.md):
> Steps to reprocude:
> - `yarn`
> - `ng test example --browsers="ChromeHeadless"
>
> In case this does not work try instead `with-node-modules` branch.  
> _Please not that here all node_modules are pushed, therefore it might take a while_

**Comment by alxhub** [comment] 2019-11-19 23:49
Hi @klemenoslaj,

I'm able to see the error using the `with-node-modules-npm` branch in your repo. A fresh install does not show the issue, the test passes for me.

The reason, I believe, is an ngcc failure sometime during the post-install hook which "broke" the `node_modules` in the branch. With this failure, `BrowserModule` is not AOT compiled and is only partially able to be compiled at runtime by the `TestBed`. Specifically, its imports are missing (including `ApplicationModule` which defines `ApplicationInitStatus`).

I'm going to close this issue as WAI for now, since I can't reproduce starting from a fresh `node_modules`. If you keep encountering the problem and can pin down some reproduction steps that don't depend on a checked-in copy of `node_modules`, please feel free to open a new issue (and ping me on it, please).

**Closed by alxhub** 2019-11-19 23:49 UTC
Labels: comp: core, comp: ivy, comp: ngcc, state: Needs repro

**Comment by klemenoslaj** [comment] 2019-11-20 07:55
@alxhub well that is the thing.

> If you keep encountering the problem

I am still encountering it really often and pipelines are failing consistently without `async=false`.

I was mostly testing this using `yarn`(_failing 5/10_), however yesterday for the sake of completeness I tried `npm` and that is failing for me 10/10, dunno why it doesn't on your machine though.

Any ideas on how to move this forward?

**Comment by klemenoslaj** [comment] 2019-11-21 15:50
@alxhub as my last try I updated the repository again.

Can you please try to pull and execute `npm run reproduce`?
This will build the docker image, execute the `ngcc` builds and karma test (_to mimic the CI_).

We tried that on 4 different machines (3x MacBook, 1x Ubuntu) and it was constantly reproducible.
