### ISSUE TITLE
custom element built-in not work

### ISSUE THREAD

**Issue by aron-taiwan** [angular/angular#36685] opened 2020-04-17 08:47 UTC
# 🐞 bug report

### Description

```ts
class FancyButton extends HTMLButtonElement {
  connectedCallback() {
    console.log('connectedCallback');
  }
}

customElements.define('fancy-button', FancyButton, {extends: 'button'});
```

```html
<button is="fancy-button" disabled>Fancy button!</button>
```

## 🔬 Minimal Reproduction
https://developers.google.com/web/fundamentals/web-components/customelements?hl=zh-tw#extendhtml

## 🔥 Exception or Error

I'm pretty sure that I can run custom element built-in provided by the browser on normal web pages, but Angular does not.

I found that Angular seems to have rewritten the properties or methods of the native window.customElements, which is very weird and will cause invalid UI elements that I have not customized through Angular Element.

The custom element built-in I customized through the browser will not be initialized at the beginning of the page, but if the element is inserted dynamically, it will be initialized. It stands to reason that any elements that appear on the page after customElements are defined All will be initialized, which is the action handled by the browser itself, so the reasonable reason is that Angular has rewritten the native browser method?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 13.13.0
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@angular/fire                     6.0.0
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by pkozlowski-opensource** [comment] 2020-04-17 08:59
As of today Angular doesn't understand / interpret the `is="..."` attribute. This is already tracked in #6827. Closing as a duplicate of #6827

**Closed by pkozlowski-opensource** 2020-04-17 08:59 UTC
