### ISSUE TITLE
Usage Notes page rendering broken on all reference pages

### ISSUE THREAD

**Issue by Michael-Ziluck** [angular/angular#57324] opened 2024-08-09 19:21 UTC
### Describe the problem that you experienced

On the docs, there is a section on named "Usage Notes" that appears to broken on almost every reference page in the new angular.dev docs. Even ones that are "working" have issues.

For pages that use either `<code-example>` or `{@example}` references are broken entirely and render nothing:
- [AsyncPipe docs](https://angular.dev/api/common/AsyncPipe?tab=usage-notes) ([Source](https://github.com/angular/angular/blob/main/packages/common/src/pipes/async_pipe.ts#L81-L93))
- [TitleCasePipe docs](https://angular.dev/api/common/TitleCasePipe?tab=usage-notes) ([Source](https://github.com/angular/angular/blob/main/packages/common/src/pipes/case_conversion_pipes.ts#L69-L72))

For other pages that use the triple backtick for code blocks, it doesn't remove the backticks in the rendered code blocks:
- [NgIf docs](https://angular.dev/api/common/NgIf?tab=usage-notes) ([Source](https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_if.ts#L67-L152))
- [NgPlural docs](https://angular.dev/api/common/NgPlural?tab=usage-notes) ([Source](https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_plural.ts#L18-L25))

It is especially noticeable on pages that include the language immediately following the backticks:
- [NgOptimizedImage docs](https://angular.dev/api/common/NgOptimizedImage?tab=usage-notes) ([Source](https://github.com/angular/angular/blob/main/packages/common/src/directives/ng_optimized_image/ng_optimized_image.ts#L193-L271))

### Enter the URL of the topic with the problem

All reference pages that contain Usage Notes, see full description

### Describe what you were looking for in the documentation

Was looking for the docs on the TitleCasePipe to determined whether it capitalizes words like "of" and "and" (which is also lacking but deserving of a different story).

### Describe what you want to experience that would fix the problem

Fix the code renderer on the angular.dev site as it works fine on the old site.

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/user-attachments/assets/25e7ebb5-7e26-445b-82d7-d7ac6f3f18eb)

### If this problem caused an exception or error, please paste it here

No errors in the console.

**Comment by Michael-Ziluck** [comment] 2024-08-09 19:25
This is _not_ a duplicate of https://github.com/angular/angular/issues/56321, please do not close this one @JoostK. That issue is only dealing with `@example` references. This also highlights the issues with `\`\`\`` as well as `<code-example>` blocks.

**Comment by JeanMeche** [comment] 2024-08-10 14:22
It's a dupe of #56068, the same root issue.

**Closed** 2024-08-10 14:23 UTC
Labels: P2, area: adev, area: docs-infra
