### ISSUE TITLE
QueryParamsHandling type should be exported

### ISSUE THREAD

**Issue by willyboy** [angular/angular#30925] opened 2019-06-08 00:01 UTC
#30816 - The reporter closed it but it shouldn't have been closed.

# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 7

### Description

The QueryParamsHandling type is no longer exposed. All types that are used in public APIs should be exposed to avoid people having to duplicate the type. Previously, it was accessible via @angular/router/src/config.

## 🔬 Minimal Reproduction

N/A

## 🔥 Exception or Error
<pre><code>

 
libs/shared/layout/src/lib/ctas/link.model.ts(1,37): error TS2307: Cannot find module '@angular/router/src/config'.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.1
Node: 10.15.2
OS: darwin x64
Angular: 8.1.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.1
@angular-devkit/build-angular      0.800.2
@angular-devkit/build-ng-packagr   0.800.2
@angular-devkit/build-optimizer    0.800.2
@angular-devkit/build-webpack      0.800.2
@angular-devkit/core               8.0.2
@angular-devkit/schematics         8.0.2
@angular/cdk                       8.0.0
@angular/cli                       8.0.1
@angular/flex-layout               8.0.0-beta.26
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.2
@schematics/angular                8.0.2
@schematics/update                 0.800.1
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**

**Comment by jotatoledo** [comment] 2019-06-08 09:08
> The QueryParamsHandling type is no longer exposed. ....Previously, it was accessible via @angular/router/src/config.

Then it wasnt trully exposed in the public API. I wonder why though.

**Comment by willyboy** [comment] 2019-06-10 14:45
@jotatoledo Yeah, I struggle with whether or not it was "exposed" because there are things like @angular/core/testing where it's allowed but not in the root export.

Even if it was unintentionally exposed earlier, I still consider it to be a bug because query params handling is part of the public API and types shouldn't have to be duplicated.

**Comment by willyboy** [comment] 2019-06-10 15:17
@trotyl Did you downvote because of #19950?
That's over a year old and I think inability to update a docs site shouldn't force everyone to create an external type for QueryParamsHandling when it already exists.

**Comment by trotyl** [comment] 2019-06-11 03:05
> Yeah, I struggle with whether or not it was "exposed" because there are things like @angular/core/testing where it's allowed but not in the root export.

Every package could have multiple entries, that's what designed in [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx). You can check the docs for what they are, e.g. `common/http`, `upgrade/static`.

> Even if it was unintentionally exposed earlier

It's not exposed at all, there is no declaration merging for `.d.ts`, the only different between public and private types are whether re-exported by entry or not. Private APIs means not allowed to use, not inaccessible in file system.

> I still consider it to be a bug because query params handling is part of the public API and types shouldn't have to be duplicated.

It's a possible solution, but there are also other solutions like inline the type signatures without reference to a private type. The latter historically preferred, see https://github.com/angular/angular/pull/29338#issuecomment-474616263 for more information.

(May still worth case-by-case discussion though).

> Did you downvote because of #19950?

No, because you're provide invalid description and claiming it a regression while clearly it isn't.

**Comment by willyboy** [comment] 2019-06-11 11:26
@trotyl Thanks for the APF link.

> It's a possible solution, but there are also other solutions like inline the type signatures without reference to a private type. 

I would hope that the Angular team wouldn't recommend inlining types to external teams. That's a dangerous recommendation. We have a lot of junior developers who don't understand that a type should be created for this and would use that recommendation as an excuse for why they duplicated type information.

> The latter historically preferred, see #29338 (comment) for more information.

I looked at that comment and I don't think it applies here. 
> @trotyl Just chatted about this a bit further with @IgorMinar, and it seems like we should wait to export the FormHooks type until later. Currently, there isn't good IDE support or API doc support for those kind of union types, and we need to have a longer conversation about the name before we make it public (and can no longer change it).

The API name is already public as queryParamsHandling in NavigationExtras. Even if it were still undergoing name changes, it's super easy to rename a type in a backwards compatible manner.

```
export type Bob = {a: number};
export type Joe = Bob;
```

Anyway, I don't really care about the semantics of regression/bug. The change is minor and there are at least 3 separate PRs/issues related to it. There were people using the type who now have to duplicate the type in their code. If queryParamsHandling were updated, it would be a full scale refactor to fix the duplicated types (which in our "Agile" world, would mean a story which means grooming... don't ask, it's frustrating).

Given that the API name is already public and the type is used internally and a name change could easily be done in a backwards compatible manner and that the type was accessible before (whether or not it was a part of the "public" API) and that best practices should be to reuse types instead of copying and that there is a PR already open, I can't think of a reason why this shouldn't be merged with haste.

Semantics aside, can you think of any reason to block this?

**Comment by jasonaden** [comment] 2019-06-25 23:00
We should export it. The original reason for not doing it isn't fixed and we don't know when it will be, so to avoid further problems here we can get it exported.

I would love a PR for this is someone wants to put it together quickly.

**Comment by willyboy** [comment] 2019-06-25 23:52
@jasonaden https://github.com/angular/angular/pull/30926 let me know if you need any changes. Tests seem to be failing because of a wrong selenium version?

**Comment by squirrelsRduck** [comment] 2019-08-04 00:36
@willyboy @jasonaden correct me if i'm wrong, but it seems this was already fixed in https://github.com/angular/angular/pull/31476 if you check out the index.ts file.

**Comment by nishi90297** [comment] 2020-04-19 18:48
try to change the primeNg version in package.json file, it is compatible with "^8.0.0" version. It worked for me, hope it helps.

**Comment by atscott** [comment] 2020-05-29 17:33
> @willyboy @jasonaden correct me if i'm wrong, but it seems this was already fixed in #31476 if you check out the index.ts file.

Yea, that does seem to be the case. Closing.

**Closed by atscott** 2020-05-29 17:33 UTC
Labels: comp: router, freq3: high, hotlist: community-help, severity3: broken, triage #1, type: bug/fix
