### ISSUE TITLE
question: why doesn't Javascript have optional static typing ?

### ISSUE THREAD

**Issue by catastrop** [angular/angular#31219] opened 2019-06-23 14:52 UTC
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by mlc-mlapis** [comment] 2019-06-23 14:55
@catastrop You have to ask somebody else probably.

**Comment by santoshyadav198613** [comment] 2019-06-23 14:58
Hi @catastrop,

Angular team does not maintain JS, maybe you need to raise this somewhere else.

**Comment by catastrop** [comment] 2019-06-23 15:02
@santoshyadav198613, let us do this

**Comment by santoshyadav198613** [comment] 2019-06-23 15:06
Hi @catastrop ,
https://github.com/tc39/proposals you can provide your proposal here. And you can close this issue.

**Comment by JoostK** [comment] 2019-06-24 06:58
I'm sorry but this issue is not caused by Angular. Please redirect this proposal to the tc39 committee as @santoshyadav198613 mentioned.

**Closed by JoostK** 2019-06-24 06:58 UTC
