### ISSUE TITLE
flex-layout wrong on host component container

### ISSUE THREAD

**Issue by furyscript** [angular/angular#20792] opened 2017-12-05 08:31 UTC
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Current behavior

I Have problem with package https://github.com/angular/flex-layout that have problem with host component.
This is related issue in other repo. https://github.com/angular/flex-layout/issues/517
It is a bug when using dynamic content creation and want to styling the host component.

## Expected behavior

API/Improvements to set host component fxFlex columns and layout. More generically, a way to bind "directive" to host component, in this case fxFlex.

## Minimal reproduction of the problem with instructions

I'm using `resolveComponentFactory` to create my component dynamic that is a child of parent and have `fxFlex`directive. The problem is that the fxFlex not apply the correct `width` to my host component.

I have attached the result of my page.

I have this main component html
```html
<div fxLayout="row" fxLayoutWrap fxLayoutAlign="start start">
    <template #widgetContainer></template>
</div>
```
And in the js I fire the `createComponent` for its children.

This is the content of children HTML:
```html
<div [fxFlex]="this.widget.options.columns">
    <mat-card>
        <mat-card-title>{{this.widget.options.title}}</mat-card-title>
        <mat-card-content>
            Grid {{this.widget.options.columns}}
        </mat-card-content>
    </mat-card>
</div>
```
And JS:
```javascript
@Component({
    selector: 'grid',
    templateUrl: './grid.component.html'
})
export class GridComponent implements OnInit {
    public widget: WidgetService;

    public constructor(
        public viewContainerRef: ViewContainerRef
    ) {

        this.widget = new WidgetService({
            title: "Tabella " + this.getIntNum(),
            originalX: 1,
            originalY: 1,
            x: 1,
            y: 1,
            base_columns: 50,
            base_rows: 2,
            columns: this.getIntNum() % 2 == 0 ? 50 : 25,
            rows: 2,
            type: "grid",
            resizable: true
        });
    }

    private getIntNum() {
        let n = Math.floor(+(Math.random()*100));
        return n;
    }

    public ngOnInit(): void {
    }
}
```

Page result
![schermata del 2017-11-27 14-19-39](https://user-images.githubusercontent.com/10270403/33268742-92eb9358-d37e-11e7-92f6-657ecf3ea7c8.png)

As you can see the card item not fit the correctly width of my container (container is a full browser page), because have another construnction of host component (`<grid>`)

## What is the motivation / use case for changing the behavior?

In dynamic content creation this is required to set Host container style/customizations. Like flex layout this is required if any host component have an fxFlex directive.
I think this is caused by angular compiler that not bind the directive, as described in other issue repo.

## Environment

<pre><code>
Angular version: 5.0.3

Browser:
- [x] Chrome (desktop) version  62.0.3202.94
- [x] Firefox version 57.0.1 
 
For Tooling issues:
- Node version: 6.11.1  
- Platform:  Mac, Linux, Windows

</code></pre>

**Comment by alxhub** [comment] 2021-07-17 00:24
Closing as a couple of things:
1. we don't support `flex-layout` anymore, and
2. this is a duplicate of wanting host bindings to add directives, which is already a planned feature

**Closed by alxhub** 2021-07-17 00:24 UTC
Labels: comp: core, core: host and host bindings, feature, insufficient votes, votes required
