### ISSUE TITLE
View encapsulation result is inconsistent with the official website

### ISSUE THREAD

**Issue by JohnieCheng** [angular/angular#49803] opened 2023-04-12 08:02 UTC
### Describe the problem that you experienced

Native angular version 15.2.0
chrome  version 112.0.5596.2 dev
When I performed View encapsulation locally, I found that the result of the web page was inconsistent with that of the official website

### Enter the URL of the topic with the problem

https://angular.io/guide/view-encapsulation

### Describe what you were looking for in the documentation

View encapsulation

### Describe the actions that led you to experience the problem

study angular

### Add a screenshot if that helps illustrate the problem

My browser show like this :

![ViewEncapsulationResult](https://user-images.githubusercontent.com/70625981/231391644-66b11b45-d7aa-469a-aff1-c9bdcb3e1539.png)

**Comment by JeanMeche** [comment] 2023-04-12 08:08
Hi, could you share on stackblitz the exemple you wrote  so we can investigate ? Thx !

**Comment by JeanMeche** [comment] 2023-04-12 08:11
Hi, could you share on stackblitz the example you wrote so we can investigate ? 

Also, you can compare what you wrote with this example : https://angular.io/generated/live-examples/view-encapsulation/stackblitz.html

**Comment by JohnieCheng** [comment] 2023-04-12 08:45
I wrote it this way：
https://stackblitz.com/edit/angular-tzjwow?file=src/app/mine/shadow-dom-encapsulation/shadow-dom-encapsulation.component.html

**Comment by JeanMeche** [comment] 2023-04-12 09:27
If you take a look at the devtools, you'll see that the `h2` have 2 matching selectors for styles within your shadow-root : 

* `blue` from the shadownDom component
* `red` from the no-encapsulation component.

The difference you observe is because the selectors have the same specificity so the browser selects the last one defined in the DOM.

**Comment by JohnieCheng** [comment] 2023-04-12 09:55
I see, but why does the import of external files cause the location and order of style tags in shadow-root to be inconsistent.

![image](https://user-images.githubusercontent.com/70625981/231422575-142b5d71-951f-44e1-a5c0-59403a417cfc.png)
![image](https://user-images.githubusercontent.com/70625981/231422733-7d777367-5f3e-4286-a4ee-94a8508432db.png)

**Comment by JeanMeche** [comment] 2023-04-12 14:47
Yeah, it seems that the insertion of styles tags in the DOM is inconsistent. 

I have a narrowed down example here : https://stackblitz.com/edit/angular-tzjwow-qxxlvv?file=src%2Fapp%2Fapp.component.ts

Removing the first component change the insertions of the style tags in the DOM.

**Comment by JohnieCheng** [comment] 2023-04-14 07:17
I saw a blog post today about how the priority is different without having to introduce css, template inline styles > styleUrls > styles. That means the initialization order is reversed, so it makes a lot of sense.

**Comment by JohnieCheng** [comment] 2023-04-14 07:19
I saw a blog post today about how different ways to introduce css have different priorities, template inline styles > styleUrls > styles. That means the initialization order is reversed, so it makes a lot of sense

**Comment by JohnieCheng** [comment] 2023-04-14 07:23
I saw a blog post today that said: Different ways to introduce css have different priorities, template inline styles > styleUrls > styles. Could this have something to do with it?

**Comment by Detzito** [comment] 2023-11-27 08:42
Did anyone find a solution? I tried, and the behavior is the same in angular 17...
In my case, it makes the use of ShadowDom impossible because I use the NoEncapsulation material components.
Is the ShadowDom functionality usually used or is it planned to be deprecated ? I'm a bit confused since I have this kind of problem at the beginning of my tests.

**Comment by JeanMeche** [comment] 2024-03-30 07:50
Closing as a dupe of #45462

**Closed by JeanMeche** 2024-03-30 07:50 UTC
Labels: area: core, core: CSS encapsulation
