### ISSUE TITLE
Strict templates validation doesn't check target event names

### ISSUE THREAD

**Issue by fansanelli** [angular/angular#49825] opened 2023-04-13 06:27 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Enable strictTemplates as per:

https://angular.io/guide/template-typecheck

On your template put:

<button (xclick)="'unreachable'">Save</button>

build your angular project successfully.
This may lead to bugs mostly and in case of refactoring of components you may leave behind your templates.

### Please provide the exception or error you saw

```true
In this case I would expect an error like:
Target event name "xclick" is not available on button component.
```

**Comment by crisbeto** [comment] 2023-04-13 06:56
`xclick` is a valid event name, because DOM nodes allow for custom events to be triggered.

**Comment by JoostK** [comment] 2023-04-13 07:36
This is essentially a duplicate of #43603, so I'll close this as a dup.

**Closed by JoostK** 2023-04-13 07:36 UTC
Labels: area: compiler, compiler: template type-checking
