### ISSUE TITLE
Detached DOM nodes

### ISSUE THREAD

**Issue by bellostom** [angular/angular#56477] opened 2024-06-17 15:17 UTC
### Which @angular package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Hi

We have run into an issue where a phenomenally simple use of signals, leads to memory leak with detached DOM nodes.
The culprit however seems to be `<select>` element, from our investigation
However, the behavior is not consistent, meaning that the leak does not manifest every time. For example when closing the browser and reopening it, it may not manifest, One needs to make several interactions with the UI, in order for it to manifest.
Below is a simplified version of the issue

https://stackblitz.com/edit/stackblitz-starters-fwdvbu

Note that the project is running zoneless

https://github.com/angular/angular/assets/1138182/e0e9de96-99fd-416b-89aa-85f8c883d00a

Attached is also a video displaying the leak

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-fwdvbu

### Please provide the environment you discovered this bug in (run `ng version`)

```

true
Angular CLI: 18.0.4
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cdk                    18.0.1
@angular/cli                    18.0.4
@angular/material               18.0.1
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5


```

**Comment by JeanMeche** [comment] 2024-06-17 15:25
Since this is not consistant, can you check that you can still reproduce it after forcing Garbage collection ? 

Use the dedicated button to trigger GC: 
<img width="295" alt="image" src="https://github.com/angular/angular/assets/1300985/a6a2dc67-e1a2-4359-9499-fdcc85918255">

**Comment by bellostom** [comment] 2024-06-18 10:31
Hi @JeanMeche 
I have tried GC but it has not collected the detached nodes.
I have tried with Edge which has a cool Detached Elements feature is its developer tools
I attach a video displaying the issue.

In the video, the first few actions, where I do not interact with the select list, are garbage collected.
As soon as I select something in the list, the whole <app-list> component is detached and not garbage collected


https://github.com/angular/angular/assets/1138182/b28179fe-e777-46e2-bf0f-41d4d90a0f63

Let me know if you need any more information
Thanks

**Comment by bellostom** [comment] 2024-06-18 11:40
Continuing from the previous video, I attach a new one, where following the details described in Microsoft's article on detached nodes,
 https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/memory-problems/dom-leaks#identify-the-dom-node-causing-others-to-be-retained, 
the Detached Elements functionality of their Dev Tools, has the ability to pinpoint the exact culprit, by breaking the parent child DOM graph

So, stripping the DOM, the culprit seems to be the select DOM element


https://github.com/angular/angular/assets/1138182/9f14e645-706b-4e85-9421-786fb3cbec21

Hope this helps

**Comment by bellostom** [comment] 2024-06-19 12:14
Back again with another observation.
I would expect the detached elements to keep increasing, once you enter the view, interact with the select element and return to the home page.
However this is not true and also puzzling.
Instead, as shown in the below video, the ,app-list> that remains detached, seems to be collected and replaced by a new one, each time you execute the beforementioned actions.
I have tried both with zone and zoneless and the behavior is the same.
Hope the above help


https://github.com/angular/angular/assets/1138182/42514992-cfa7-481a-83da-c30613f2de44

**Comment by JeanMeche** [comment] 2024-10-08 18:37
This is actually an interesting leak. The select element isn't retained on angular's side. 
It looks like to be a Chromium bug : 

* https://issues.chromium.org/issues/40056157
* https://issues.chromium.org/issues/41466808

I'll close this as an upstream issue.

**Closed by JeanMeche** 2024-10-08 18:37 UTC
Labels: memory leak, area: core, state: needs more investigation
