### ISSUE TITLE
HMR support? 😢 

### ISSUE THREAD

**Issue by omerman** [angular/angular#51641] opened 2023-09-04 05:23 UTC
### Description

Hot module replacement support in components would be greatly appreciated by everyone 

### Proposed solution

-

### Alternatives considered

-

**Comment by json-derulo** [comment] 2023-09-04 07:07
You can enable hot module replacement by running `ng serve --hmr=true`, see the [docs](https://angular.io/cli/serve). What exactly are you missing?

**Comment by alan-agius4** [comment] 2023-09-04 07:10
Duplicate of https://github.com/angular/angular/issues/39367

**Closed by alan-agius4** 2023-09-04 07:10 UTC

**Comment by shunia** [comment] 2023-09-14 07:07
> You can enable hot module replacement by running `ng serve --hmr=true`, see the [docs](https://angular.io/cli/serve). What exactly are you missing?

But now it will always trigger a page reload, right?
Or if I'm missing anything here? How can we config Angular to make the code modification only update the affected component/module in-place without a full page reload? 
Or we could just step down, for in-place style update without refreshing the whole page, and how can we do that?
