### ISSUE TITLE
ng xi18n does not extract message in $localize

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular#36812] opened 2020-04-27 03:42 UTC
# 🐞 bug report

### Affected Package

`@angular/cli`

### Is this a regression?

no

### Description
1. create a component
```ts
@Component({
  template: '{{ title }}'
})
export class HomeComponent {
  title = $localize`You have 10 users`;
}
```
2. ng xi18n
3. no trans-unit in messages.xlf

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.3
Node: 12.13.1
OS: darwin x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by petebacondarwin** [comment] 2020-04-27 09:06
Duplicate of #36714

**Closed by petebacondarwin** 2020-04-27 09:06 UTC

**Comment by vthinkxie** [comment] 2020-04-27 09:21
Hi @petebacondarwin 
is there any plan to support json format? the current xi18n only support xlf like format

**Comment by petebacondarwin** [comment] 2020-04-27 09:26
See #36644
