### ISSUE TITLE
docs: no API docs for HostListener 

### ISSUE THREAD

**Issue by turnerguo** [angular/angular#15602] opened 2017-03-30 02:46 UTC
**I'm submitting a Improvement for documents**
```
[ ] bug report
[x] feature request
[x] improvement request
[ ] support request
```

**Current behavior**
For example, in [HostListener](https://angular.io/docs/ts/latest/api/core/index/HostListener-interface.html) doc, there is no detailed descriptions for `eventName`.
In common that should be dom event names, but actually we could use it some way like `document:click`/`keyup.esc` etc.

**Expected behavior**
I think it should be a more clear doc for any details even that advanced usage,
e.g. how can we use that `eventName` in `HostListener` decorator.
Angular is moving fast, any details should be checkable for developers.

Thx.

**Comment by trotyl** [comment] 2018-06-22 08:55
Related to https://github.com/angular/angular/issues/18870, https://github.com/angular/angular/issues/20969

**Comment by mo7amd** [comment] 2018-06-22 09:44
thanks @trotyl  i got your answers on those post.

**Comment by pkozlowski-opensource** [comment] 2019-04-10 08:18
I'm going to close this one as a duplicate of  #18870 / #20969

**Closed by pkozlowski-opensource** 2019-04-10 08:18 UTC
Labels: comp: core & compiler, comp: docs, comp: docs/api, freq3: high, type: feature
