### ISSUE TITLE
Live example links on the angular.io do not work

### ISSUE THREAD

**Issue by yr2193** [angular/angular#21619] opened 2018-01-18 04:56 UTC
## I'm submitting:

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Click on the live example link, got
 {"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}

## Expected behavior

To see a live example...

## Minimal reproduction of the problem with instructions

For example: 
Go to page: https://angular.io/guide/animations#animatable-properties-and-units
Click on the live example link. 
Got internal error.

## What is the motivation / use case for changing the behavior?

I am learning angular animation and want to try it out. 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 63.0.3239.132
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Siyeza** [comment] 2018-01-18 07:51
experiencing the same issue, when is this getting the attention?

**Comment by gkalpak** [comment] 2018-01-18 10:51
Closing as a duplicate of #21616.

**Closed by gkalpak** 2018-01-18 10:51 UTC
