### ISSUE TITLE
Unable to access child structural directive from parent structural directive

### ISSUE THREAD

**Issue by thekalinga** [angular/angular#16840] opened 2017-05-17 09:35 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Neither viewChild nor contentChild are being set

**Expected behavior**
Either viewChild or contentChild should be set

**Minimal reproduction of the problem with instructions**

I am trying to access child structural directive from parent directive.

This is how I'm trying to access the child

```ts
@Directive({
  selector: '[appChildStruralDirective]'
})
export class ChildStruralDirective {
  constructor(private templateRef: TemplateRef<any>, private viewContainer: ViewContainerRef, private renderer: Renderer) {
    this.viewContainer.createEmbeddedView(this.templateRef);
  }

  ngAfterViewInit(): void {
  }
}

@Directive({
  selector: '[appParentStruralDirective]'
})
export class ParentStruralDirective {
  @ViewChild(ChildStruralDirective) viewChild: ChildStruralDirective;
  @ContentChild(ChildStruralDirective) contentChild: ChildStruralDirective;

  constructor(private templateRef: TemplateRef<any>, private viewContainer: ViewContainerRef, private renderer: Renderer) {
    this.viewContainer.createEmbeddedView(this.templateRef);
  }

  ngAfterViewInit(): void {
    console.log('ngAfterViewInit:viewChild', this.viewChild);
    console.log('ngAfterViewInit:contentChild', this.contentChild);
  }

  ngAfterContentChecked(): void {
    console.log('ngAfterContentChecked:viewChild', this.viewChild);
    console.log('ngAfterContentChecked:contentChild', this.contentChild);
  }
}
@Component({
  selector: 'my-app',
  template: `
   <h1 *appParentStruralDirective>
     <span *appChildStruralDirective>Hello world</span>
   </h1>
  `,
})
export class App {
  constructor() {
  }
}
```

Plunkr that reproduces the issue

https://plnkr.co/edit/deQC6cY4oHuNdKbzsfhE?p=preview

**What is the motivation / use case for changing the behavior?**
Have a channel between parent and child directives so that each can talk to the other do perform a specific set of operations of the child elements

**Please tell us about your environment:**
Ubuntu 14.04

* **Angular version:** 2.0.X
Angular 2.4

* **Browser:**
All

* **Language:**
TypeScript 2.2

**Comment by thekalinga** [comment] 2017-05-17 09:38
I tried accessing the other way around. i.e from child directive, I'm able to access parent

```ts
export class ChildStruralDirective {
  constructor(private templateRef: TemplateRef<any>, private viewContainer: ViewContainerRef, private renderer: Renderer, @Inject(forwardRef(() => ParentStruralDirective)) private parent: ParentStruralDirective) {
    // more
  }
  // more
}
```

**Comment by thekalinga** [comment] 2017-05-17 13:08
Ability to access from child to parent seems to be working only in 2.4.0 (as far as I could test), but not in 4.1.2. Not sure what has changed in between

**Comment by thekalinga** [comment] 2017-05-17 13:26
Here is the link to the angular cli project where the DI in child was working https://github.com/thekalinga/angular-structural-directive-test

**Comment by tbosch** [comment] 2017-05-19 23:23
Creating a directive via `TemplateRef` and inserting it via `ViewContainerRef` creates the template as a sibling in the dom, not as a child. Therefore, Angular's injection also respects this in that the child and the place of creation cannot see each other.

This happened to work in 2.4 by accident, but not by design.

Closing in favor of https://github.com/angular/angular/issues/15998 which captures the same use case.

**Closed by tbosch** 2017-05-19 23:23 UTC
Labels: comp: core & compiler

**Comment by thekalinga** [comment] 2017-05-22 03:03
@tbosch

> Creating a directive via TemplateRef and inserting it via ViewContainerRef creates the template as a sibling in the dom, not as a child.

This is not true.

Here is the DOM created by the example

```html
<h1>
  From parent<br>
  <!--template bindings={}--><span>From child</span>
 </h1>
```

The template responsible for template generation

```html
<h1 *appInlineEdit>
  From parent<br>
  <span *appShowOnEdit>From child</span>
</h1>
```

The child should be made accessible so that the communication between parent & child can accomplished without external co-ordination (such as managing mapping between parent & child via external service)
