### ISSUE TITLE
aio: impossible to view/click on team profile twitter/GitHub links on mobile

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#16690] opened 2017-05-10 11:28 UTC
Currently, the Twitter/GitHub links are shown on hover. Upon click the card is flipped and the bio is displayed. On mobile (where there is no hover and click acts like both hover and click) it is not possible to view or click on theses links.

Note, in the previous version the Twitter/GitHub links were also shown in the bio, so it was possible to view/click them.

**Comment by petebacondarwin** [comment] 2017-09-13 14:00
Still a problem @gkalpak ?

**Comment by gkalpak** [comment] 2017-09-13 14:39
Yes.

**Comment by sergeome** [comment] 2018-01-04 04:23
Hello, guys.
I wanted to fix this issue.
@gkalpak, when you said: 
> On mobile (where there is no hover and click acts like both hover and click) it is not possible to view or click on theses links.

Could you please give an idea, how it should be fixed? 

The reason I wanted to fix this issue is I also noticed that there're redundant scrolling bars around the card description. Please take a look at the attachment. 

<img width="826" alt="reduntant-scrolling-bars" src="https://user-images.githubusercontent.com/10011693/34550127-eda808ae-f0d3-11e7-80f4-007c54e949fa.png">

I also wanted (and know) how to remove this bars if the description is less than card height. If the description would be bigger then card it would be scrollable. 

Thank you.

**Comment by gkalpak** [comment] 2018-01-26 14:12
Sorry, for the late response, @sergeome. Assuming you are still interested to hlp address this issue (which would be awesome ❤️):

- 👍 for removing the unnecessary scrollbars.
- I am not sure how the hover/click issue should be fixed. Off the top of my head, we could have the bio/Twitter/GitHub links be always visible on mobile (instead of only on hover).
  This is more of a design question. Maybe @sjtrimble has some ideas.

<sub>
That being said, I am not a big fan of the current "flipping cards". I prefered the [expanding cards][1] we had before 😇 
</sub>

[1]: https://v2.angular.io/about/

**Comment by sergeome** [comment] 2018-01-27 19:34
Hello @gkalpak. 
I'm happy to address this issue. However, I've noticed that change to cards was made about 10 months ago [link](https://github.com/angular/angular/commit/6e89f0bf8da31537e7eee438d7e0653300f3663e).

I also tried to reproduce this issue and I was able to navigate to a contributor's twitter and personal page on mobile. However, as you pointed, it's not very obvious unless you actually click once. 
I'm attaching video recording of my observation [here](https://photos.app.goo.gl/A25qLEpzi6umYv4x2).
Could you please suggest how should I fix that? Thank you!

**Comment by petebacondarwin** [comment] 2018-10-12 09:29
Or even better, put it in a `@media (hover)` query.

**Closed** 2018-10-17 18:06 UTC
Labels: comp: docs-infra, freq1: low, severity3: broken, subtype: docs-design, type: bug/fix
