### ISSUE TITLE
Angular 7 upgrade to 10. Appears in the NgModule.imports could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by ruchiagrawal2** [angular/angular#38950] opened 2020-09-23 13:39 UTC
Stuck with this for days ! Have tried all suggestions from previous forums.......importHelpers, clean up node. Without Ivy there are no issues. I get the below error on using Ivy Angular 10. I can not use postinstall :ngcc  to fix this since npm install is not run . Build files for the library are simply copied under node_modules ('@abc/uiplatform') after ng build is run for the library.

UIPlatformModule is a module within an internal package '@abc/uiplatform' which is built using ng build and then copied under node_modules under a folder structure "@abc/uiplatform".  

```
BUILD ERROR ../node_modules/@infogix/uiplatform/uiplatform.module.d.ts:2:22 - error NG6002: Appears in the NgModule.imports of ControlModule, but could not be resolved to an NgModule class.

This likely means that the library (@infogix/uiplatform) which declares UIPlatformModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

2 export declare class UIPlatformModule {
```

Below is From my angular.json : 

```
"uiplatform": {
      "root": "platform/UIPlatform",
      "sourceRoot": "platform/UIPlatform/ngsrc",
      "projectType": "library",
      "prefix": "ng",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "platform/UIPlatform/tsconfig.ui.json",
            "project": "platform/UIPlatform/ng-package.json"
          },
      
        }
      }
    },
```
Please help !!!

**Comment by petebacondarwin** [comment] 2020-09-25 08:18
It is very hard to help without some more information. From the error it looks like ngcc has not processed this library that you have copied into node_modules. Generally it would be better to run `npm pack` on the generated library dist folder, then reference the `.tgz` file that is produced in the `package.json` of the consuming app. This will then install the library as needed. The CLI (I assume you are using this to build?) will ensure that the library has been processed by ngcc.

**Comment by petebacondarwin** [comment] 2020-11-02 20:02
Closing due to a lack of reproduction. If this is still a problem, please open a new issue with a reproduction that we can debug.

**Closed by petebacondarwin** 2020-11-02 20:02 UTC
Labels: P3, comp: ngcc, freq1: low, needs clarification, needs reproduction, type: bug/fix
