### ISSUE TITLE
Object as a component property in For directive

### ISSUE THREAD

**Issue by baio** [angular/angular#1846] opened 2015-05-12 20:34 UTC
Hi!

Inside `for` directive, I had repeated component which have property `item`, when this component is generated I had exception. If I bind not object but some property all work fine.

```
import {Component, View, For} from 'angular2/angular2';
import {ResortsListItem} from './resorts-list-item'

@Component({
  selector: 'resorts-list'
})
@View({
  template: `
    <h2>List</h2>
    <ul>
      <li *for="var item of items">
        <resorts-list-item [item]='item'><resorts-list-item>
      </li>
    </ul>
    `,
  directives: [ResortsListItem, For]
})
export class ResortsList {
  items: Array<{name : string}>; 
  
  constructor() {
    this.items = [{name: "Sidr"}, {name: "Cral"}];
  }
}


////////////////////

import {Component, View} from 'angular2/angular2';

@Component({
  selector: 'resorts-list-item',
  properties: {item: 'item'},  
})
@View({
  template: '<p>{{item.name}}</p>'
})
export class ResortsListItem {
  item : {name: string};
    
  constructor() {
  }
}

```

Throw exception 

TypeError: Cannot read property 'name' of undefined in [{{item.name}} in ResortsListItem: <p>]
STACKTRACE:

Error
    at Function.getStacktraceWithUncaughtError (http://127.0.0.1:8080/bundle/angular2.dev.js:698:32)
    at Zone.longStackTraceZone.fork (http://127.0.0.1:8080/bundle/angular2.dev.js:757:43)
    at Zone.bind (http://127.0.0.1:8080/bundle/angular2.dev.js:62:21)
    at Function.Zone.bindArguments (http://127.0.0.1:8080/bundle/angular2.dev.js:194:22)
    at t.fnNames.forEach.obj.(anonymous function) [as then] (http://127.0.0.1:8080/bundle/angular2.dev.js:185:42)
    at Function.execute.PromiseWrapper.then (http://127.0.0.1:8080/bundle/angular2.dev.js:20301:47)
    at http://127.0.0.1:8080/bundle/angular2.dev.js:30378:22
    at Zone.run (http://127.0.0.1:8080/bundle/angular2.dev.js:87:19)
    at VmTurnZone.execute.VmTurnZone.run (http://127.0.0.1:8080/bundle/angular2.dev.js:15337:36)
    at Object.bootstrap (http://127.0.0.1:8080/bundle/angular2.dev.js:30376:10)

**Comment by matanlurey** [comment] 2015-05-13 03:29
I think the required syntax is `*for="var #item in items"`. The `#` is important.

**Comment by vicb** [comment] 2015-05-13 05:10
I think it's either `#item` or `var item` both being synonym

**Comment by vicb** [comment] 2015-05-14 17:47
@vsavkin do you have time to take a look at this issue ?

What seems to happens here is that we try to evaluate `item.name` before the `item` is set.

It works with the following update:
```ts
export class ResortsListItem {
  item : {name: string};

  constructor() {
    this.item = {name: null};
  }
}
```

**Comment by vicb** [comment] 2015-05-19 13:04
Hum... took me a while to figure out... and the issue is:
`<resorts-list-item [item]='item'><resorts-list-item>`

Take a look at the "closing" tag ! (should be `</resorts-list-item>`)

**Closed by vicb** 2015-05-19 13:04 UTC
