### ISSUE TITLE
Angular 4 test using whenStable hangs (worked in Angular 2)

### ISSUE THREAD

**Issue by mmc41** [angular/angular#15486] opened 2017-03-25 13:25 UTC
[x ] bug report => search github for a similar issue or PR before submitting

**Current behavior**
I have a test that worked with angular 2 but fails with a jasmine timeout error under angular 4 because the whenStable promise never completes. The test is using  (done) to handle asynchronicity rather than async/fakeAsync which I have found to be not working correctly when using rxjs observables and advanced features like debounce, delay etc. An incomplete extract of my approach is shown below:

Nb. According to the docs whenStable should resolves when the fixture is stable and work universally, but some issues (#12721) suggest that it may not work outside async/fakeAsync. In any case, the code worked in Angular 2 but does not work in Angular 4.

```
// Works in Angular 2 but not in Angular 4 due to whenStable:
it('should submit correctly', (done) => {
   ....
   let stableSubmissions = submitSubject // called when user presses a submit button.
           .do(() => {  fixture.detectChanges(); })
           .switchMap(fromValues => {
             return Observable.fromPromise(fixture.whenStable()) // hangs in 4.0.0 ?
                    .map(na => fromValues)
                    .do(() => { fixture.detectChanges(); });
           });

    stableSubmissions.subscribe(() => {
      // never called because fromPromise above hangs.
      // ...
     done();
    };
  }

```

**Expected behaviour**
The test should run in angular 4 just like it does in angular 2.

**Please tell us about your environment:**
Mc OS X 4.

* **Angular version:** 4.0.0

* **Browser:**  chrome

 
* **Language:** TS 2.2.1 

* **Node (for AoT issues):** `node --version` =   v7.6.0

**Comment by DzmitryShylovich** [comment] 2017-03-25 13:30
Please reproduce here http://plnkr.co/edit/Oqc2xFpd168zTSqx9dVf?p=preview

**Comment by mmc41** [comment] 2017-03-25 13:33
It is rather difficult to reproduce so first I would like to know if fixture.whenStable is supposed to be supported in the outlined case (i.e. when using done instead of async/fakeAsync).

**Comment by vikerman** [comment] 2017-03-26 05:44
There should be no difference in behavior of ComponentFixture from 2 to 4

**Comment by mmc41** [comment] 2017-03-26 07:55
Yes, there should be no difference but some of my tests behave different concerning whenStable.

For some tests whenStable works fine under Angular 4 and in some other tests they don't. They tests that fail depend on lots of complex UI, so it is very difficult to create an independent test case.

Also, I do miss an explanation if my use case is officially supported or not ? I.e. was it luck that it worked in Angular 2 or not ?

**Comment by renehamburger** [comment] 2017-06-02 23:08
I'm experiencing a related issue on angular@4.1.3, which may well have the same cause. In a [very simple component test](https://github.com/valor-software/ng2-handsontable/blob/test-async-issue/demo/src/hanging-async.spec.ts), the async function in a beforeEach block never resolves.

The component being tested contains a large, external JavaScript library with an Excel-like table, which is created outside of Angular's zone. But it seems that the setTimeout calls within that library still increase the pending task counts of AsyncTestZoneSpec, but never reset them. At least that's what it looks like on first glance.

Would it be better to file this issue at zone.js?

**Comment by giniedp** [comment] 2017-07-10 09:14
Any progress on this issue? Testing form components with async validators is a big pain right now. At the moment positive results of tests that use `whenStable` inside can not be trusted.

**Comment by elliot-xu** [comment] 2017-11-30 09:57
In my case, `whenStable` resloves too fast but my `Promise` hasn't resolved yet.

https://plnkr.co/edit/td8zKmBBqtAEL768kx4v?p=preview

**Comment by giniedp** [comment] 2018-05-31 13:30
i did again run into a test, that was passing locally but failed sometimes in CI pipeline. It used `async` together with `whenStable`. The whenStable block did not run most of the time so the expectation was simply skipped. My only solution is to use async/await instead of async

```ts
it("is a test", async (done) => {
  ...
  await fixture.whenStable()
  ...
  done()
})
```

**Comment by alxhub** [comment] 2019-02-26 23:34
We need a working reproduction to look into this issue.

**Comment by alxhub** [comment] 2019-03-05 23:05
Closing as no reproduction is available. Please feel free to re-open the issue with a working reproduction.

**Closed by alxhub** 2019-03-05 23:05 UTC
Labels: comp: testing, freq1: low, severity5: regression, state: Needs repro, type: bug/fix
