### ISSUE TITLE
http: PUT and POST body param should accept an object

### ISSUE THREAD

**Issue by wardbell** [angular/angular#6538] opened 2016-01-17 17:06 UTC
As of beta.1, `.put` and `.post` require a string body property (see also #6533). 

It is a PITA to `JSON.stringify` the body object everywhere in our calling code. Other http clients (such as [jQuery ajax](http://api.jquery.com/jquery.post/)) accept either string or object; they `JSON.stringify` the object for us.

**Comment by robwormald** [comment] 2016-01-17 17:10
duplicate of https://github.com/angular/angular/issues/5211

**Comment by wardbell** [comment] 2016-01-17 17:12
Oh your fast a responder @robwormald! It is a duplicate in the sense that it is under the umbrella of your issue. That's a big umbrella though and this specific point might be overlooked.

**Comment by PascalPrecht** [comment] 2016-01-17 22:27
It's also duplicate of https://github.com/angular/angular/issues/5517

However, as more ppl are requesting this, we should do sth. about it. Is there something stopping us from implementing that?

**Comment by robwormald** [comment] 2016-01-17 22:55
nothing but the finite amount of hours in the day!

**Comment by PascalPrecht** [comment] 2016-01-17 22:57
I think I saw a pending PR from you @robwormald that addresses this no? Otherwise I could try to take a look at this.

**Comment by wardbell** [comment] 2016-01-17 23:00
Looks like we all want it!  Not sure why I couldn't find my predecessor's issues. Perhaps because this has been an untapped issue for so long.

**Comment by robwormald** [comment] 2016-01-17 23:22
@PascalPrecht i've got a bigger refactor which is probably gonna have to get punted in favor of some other stuff. go for it.

**Comment by spock123** [comment] 2016-02-01 21:17
I can see that it would be a nice addition, however I*m not sure it's a great problem that _should_ be part of the core code.. I mean, most of us will use some kind of wrapper class around the http service anyway.. 
So: convenient yes, super necessary no..

**Comment by aoakeson** [comment] 2016-02-02 17:02
@spock123 I agree that this will be a very nice addition, but I also think its critical to the core code.  The http service is almost useless if the only thing you can pass is a string.  People may write workarounds to do this like you suggested, (I have done this myself), and there are obvious downsides to this.  This is something that is used so frequent that its imperative that this is included.

**Comment by spock123** [comment] 2016-02-03 22:21
@aoakeson, you've convinced me.. I agree

**Comment by israelshirk** [comment] 2016-02-04 23:24
(random guy here) I'd be glad to hop on this with a little direction - the big question in my mind is what serialization method[s] should be used, and how should they be specified for a specific request?

**Comment by robwormald** [comment] 2016-02-08 19:01
This issue was moved to angular/http#50

**Closed by robwormald** 2016-02-08 19:01 UTC
Labels: comp: http, effort1: easy (hour), hotlist: community-help, P3: important, type: feature
