### ISSUE TITLE
[Service Worker] Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.

### ISSUE THREAD

**Issue by zh99998** [angular/angular#24554] opened 2018-06-17 16:01 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I got a 
```
Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
```
and site can't open in some browsers.

seems it's related to 
https://github.com/GoogleChrome/workbox/issues/1386

<img width="1119" alt="2018-06-18 12 05 33" src="https://user-images.githubusercontent.com/359622/41509751-63d1482c-728b-11e8-856e-541662837a23.png">

## Minimal reproduction of the problem with instructions

my `ngsw-config.json`
```json
{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": ["/favicon.ico", "/index.html", "/*.css", "/*.js"]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": ["/assets/**", "/fontawesome-webfont.*", "/MaterialIcons-Regular.*"]
      }
    }
  ],
  "dataGroups": [
    {
      "name": "api-freshness",
      "urls": [
        "https://ygobbs.com/top/quarterly.json",
        "https://mycard.moe/ygopro/api/history",
        "https://api.mycard.moe/ygopro/arena/user"
      ],
      "cacheConfig": {
        "maxSize": 100,
        "maxAge": "3d",
        "timeout": "1m",
        "strategy": "freshness"
      }
    },
    {
      "name": "api-performance",
      "urls": [
        "https://api.mycard.moe/apps.json",
        "https://cdn01.moecube.com/avatars/*",
        "https://ygobbs.com/user_avatar/*",
        "https://ygobbs.com/uploads/**"
      ],
      "cacheConfig": {
        "maxSize": 100,
        "maxAge": "3d",
        "timeout": "1m",
        "strategy": "performance"
      }
    }
  ]
}

```

## Environment

<pre><code>
Angular version: 6.0.5

Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version 57
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>
Tencent QQ browser

**Comment by gkalpak** [comment] 2018-06-17 18:27
Duplicate of #20756. See https://github.com/angular/angular/issues/20756#issuecomment-386236004 for an explanation of the problem (tldr; it is a browser bug) and for possible workarounds.

**Closed by gkalpak** 2018-06-17 18:27 UTC
