### ISSUE TITLE
Dependency Injection not working for Components/Directives inherited from Angular2 Components/Directives.

### ISSUE THREAD

**Issue by sergeykhomyuk** [angular/angular#8700] opened 2016-05-17 18:09 UTC
Dependency Injection not working for Components/Directives inherited from Angular2 Components/Directives if using TypeScript Compiler instead of Angular Template Compiler.

**Steps to reproduce and a minimal demo of the problem**
1. Define DatePicker directive inherited from DefaultValueAccessor.
2. Add any additional parameter to DatePicker constructor (e.g. `logger: Logger`).
3. Compile source code with TypeScript Compiler.
4. Run application.
```
@Injectable()
class Logger {}

@Directive({
  selector: '[datePicker]'
})
class DatePicker extends DefaultValueAccessor {
   constructor(renderer: Renderer, element: ElementRef, logger: Logger) {
     super(renderer, element);
     if (!logger) {
      console.error('Logger is undefined');
     } else {
       console.info('Logger is defined');
     }
   }
}
```

Minimal demo: http://plnkr.co/edit/UIybCDlayhXRO7x0Y7Lk?p=preview

**Current behavior**
DatePicker resolved using ctorParameters from DefaultValueAccessor (renderer, element) instead of metadata from DatePicker constructor (renderer, element, logger).
(see `ReflectionCapabilities.parameters(typeOrFunc: Type): any[][]` implementation for details)

**Expected/desired behavior**
DatePicker resolved using parameters from its constructor metadata (renderer, element, logger).

**Other information**
Current implementation of `ReflectionCapabilities.parameters(typeOrFunc: Type): any[][]` work properly only if code was compiled using Angular Template Compiler, otherwise it will never check metadata, because ctorParameters decorator data inherited from parent hides it.

**Comment by pe8ter** [comment] 2016-05-17 19:35
You didn't add Logger as a provider to your bootstrap. Since you don't have access to Logger in main.ts you can add it as a provider to your directive instead. In your Plunker, make your directive like this:

```typescript
@Directive({
    selector: '[datePicker]',
    providers: [Logger]
})
```

**Comment by cristi-badila** [comment] 2016-05-17 21:14
The same thing seems to happen to other classes/services which inherit from angular classes. 
In a case I observed, a custom Http service which inherits from angular `Http` always gets injected with only the dependencies of the base class even though it has other constructor parameters marked as injectable and which can be resolved by the injector. I created a small plunker to reproduce the issue [here]( http://plnkr.co/edit/ev1H0QNaqNZHhSUiya8q?p=preview).

**Comment by rhaynie8028** [comment] 2016-05-17 21:19
Same with XHRBackend in my case

**Comment by pe8ter** [comment] 2016-05-17 23:56
Anecdotally, our RouterOutlet subclass has no issues with DI in rc.1. Not sure what could be making the difference.

**Comment by hannahhoward** [comment] 2016-06-03 06:34
PR Submitted for a fix, #8991

**Comment by vicb** [comment] 2016-10-06 22:32
see #11606

**Closed by vicb** 2016-10-06 22:32 UTC
Labels: comp: core & compiler, effort2: medium (days), freq1: low, severity4: broken, type: bug, workaround3: complex

**Comment by tehkyle** [comment] 2016-10-06 23:11
This is inappropriately closed. The child component is using it's parent's decorators in all cases. This makes it impossible to extend a component and provide it new decorators.
