### ISSUE TITLE
Make service worker push listeners configurable at will.

### ISSUE THREAD

**Issue by N-Andronopoulos** [angular/angular#33432] opened 2019-10-27 16:14 UTC
# 🚀 feature request

### Relevant Package
@angular/packages/service-worker/*

### Description
The issue is that I can't use angular's service worker and firebase messaging together. If I do I get weird double callbacks and click actions when clicking the notification outside the app (by having a new custom service worker that imports this one and firebase's).

### Describe the solution you'd like
Have a boolean, like { ..., disablePush: true } in ngsw-config.json for hook listeners for push messages. I think these lines below could be activated based on the aforementioned boolean.

@angular/packages/service-worker/worker/src/driver.ts  line: 158
```
    // Handle the fetch, message, and push events.
    this.scope.addEventListener('fetch', (event) => this.onFetch(event !));
    this.scope.addEventListener('message', (event) => this.onMessage(event !));
    this.scope.addEventListener('push', (event) => this.onPush(event !));
    this.scope.addEventListener('notificationclick', (event) => this.onClick(event !));
```
Or maybe there should be two service workers, one with and without these listeners. But I believe it would be a more complicated solution.

### Describe alternatives you've considered
Right now you have to make a new service worker then import ngsw and then overwrite the listeners so they do what you want. But still can't use firebase's messaging service worker nor its functionality (at least I couldn't). I read that you can make yourself a custom solution with workbox, without angular's service worker, but I think it shouldn't be necessary.

Maybe we could do something else?

**Comment by gkalpak** [comment] 2019-10-29 09:59
That's a reasonable feature request. It is on our long-term plans to make the Angular ServiceWorker more flexible (in a way that you could do things like that), but right now it is indeed not possible (without tampering with the ServiceWorker script (`ngsw-worker.js`)).

**Comment by gkalpak** [comment] 2019-12-22 20:56
Actually, I just realized this is a duplicate of #26413. Closing in favor of #26413 (which has more context/resources).

**Closed by gkalpak** 2019-12-22 20:56 UTC
Labels: comp: service-worker, type: feature
