### ISSUE TITLE
Array push not firing to child @Input

### ISSUE THREAD

**Issue by kokhooi** [angular/angular#21121] opened 2017-12-21 03:15 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I've this child componentA inside a parent component
`<componentA [setTask]="tasks"></componentA>`

in the componentA setTask is an Input 
 `@Input() set setTask(value: Array<any>) {
    // Do stuff
  }`

now whenever I push new item in the parent component either using
this.tasks.push(item) or Array.prototype.push.apply(this.tasks, items)

the Input in the child component is not being triggered

## Expected behavior

On every update on the Array the Input should be triggered. This is working just fine in 4.4.6, but not after I've updated to Angular 5

## Environment
<pre><code>
Angular version: 5.1.2

**Comment by mlc-mlapis** [comment] 2017-12-21 08:50
@kokhooi ... are you talking about JIT or AOT mode of the application.

**Comment by pkozlowski-opensource** [comment] 2017-12-21 09:15
@kokhooi could you please provide a minimal reproduce scenario (plunker) for both Angular 4.4.6 _and_ 5.1.2? 

I don't believe that what you are describing ever worked, but only minimal plunkers will let us confirm.

**Comment by kokhooi** [comment] 2017-12-22 03:58
hi,
here's the plunker link
https://plnkr.co/edit/lU1ar8urMIn2nHiXwnib

if click on the Append, the total is increasing, but child is not getting the update

go to systemjs.config.js, change the angularVersion to 4.4.6, and do the same action again

you will see the child is getting the update. maybe I should file this bug to Kendo instead of here.

if this is not Angular bug, please kindly close it. thanks a lot

**Comment by mlc-mlapis** [comment] 2017-12-22 10:19
@kokhooi ... hmm, some change had to be done in some point between version 4.4.6 and 5.1.2 for sure. You are right ... with 4.4.6 it works as you described. That change was probably related with solutions of some issues because the behavior from 4.4.6 is wrong  - Angular shouldn't detect changes in an array content but just when its reference has been changed.

Generally `setter` is invoked when `ngOnChanges` hook detects changes on any `@Input` ... but it is not supposed that Angular would check and compare contents of array or objects ... just their references.

Another situation is when a direct (without setter) `@Input` is used ... where a parent and its child are sharing the same reference of an array or an object. This is possible to see when we add the following parts ... then the change in an array or an object is showed immediately ... because of the shared reference. 

`<app-child-component [setItems]="parentItems" [myitems]="parentItems"></app-child-component>`
...
```
@Component({
  selector: 'app-child-component',
  template: `
    <div>
      <h3>I'm the Child component</h3>
      <label>{{items}}</label>
      <hr />
      <label>{{myitems}}</label>
    </div>
  `
})
export class ChildComponent {
  
  items = new Array<number>();
  @Input() set setItems(value: Array<number>) { this.items = value; }
  @Input() myitems: Array<number>;
}
```

**Comment by pkozlowski-opensource** [comment] 2017-12-22 11:17
@mlc-mlapis is right - by default Angular should _not_ deep-check arrays. As I've said before, I don't believe it ever did as a minimal plunker using 4.4.6 doesn't trigger `ngOnChanges`: https://plnkr.co/edit/1FbdrojI7qqtmtNwQXqA?p=preview 

I'm going to close this issue as I don't see evidence of behaviour change in Angular itself. You might want to follow up with Kendo folks to see if things evolved on their end.

**Closed by pkozlowski-opensource** 2017-12-22 11:17 UTC
Labels: comp: core & compiler, state: Need repro

**Comment by dlarr** [comment] 2018-10-04 10:09
I don't know why but no Angular Plunkers works for me.... Pain in the ass...
