### ISSUE TITLE
Observable.map() referenced in the Http API documentation, but doesn't work by default.

### ISSUE THREAD

**Issue by dupski** [angular/angular#6230] opened 2016-01-03 14:44 UTC
There is a reference to the RxJS .map() function in the API documentation at https://angular.io/docs/ts/latest/api/http/Http-class.html however the .map() function isn't imported by default so the example doesn't work in a default angular project (using beta 0).

Personally I think either the reference to .map() should be removed from the example, or there should be a mention of the required workaround of adding `import 'rxjs/add/operator/map';` somewhere (anywhere!) in your code.

**Comment by PascalPrecht** [comment] 2016-01-03 15:43
I vote for updating the docs here.

**Comment by thelgevold** [comment] 2016-01-03 17:47
I agree. The process for including rxjs dependencies piecemeal is clear once you know about it, but it needs to be included in the docs as well. map() is pretty much fundamental to the http implementation, so it makes sense to leave it in the example provided more documentation is added.   

In the context of http, perhaps it would make sense to create some sort or wrapper for the most common rx operators like map, forkJoin and mergeMap etc?  These are all needed to mimic common operations that people are used to from Angular 1.x (parallel requests, chaining and even just plain json calls)

**Comment by robwormald** [comment] 2016-01-03 23:46
There's already a PR in to update the docs https://github.com/angular/angular/pull/5947, so I'll close this as a dupe of #5944 - thanks for the report though.

I'm in the process of refactoring the guts of Http (see https://github.com/angular/angular/pull/6198) to make some of this stuff a little less irritating. As far as including a bunch of standard operators, I'm still on the fence about it. Properly documented, I don't think there's much of an issue with importing the ones you want (and not forcing the bytes on those that don't...)

Note that Http is actually documented in the DevGuide, so this kind of thing will certainly be covered in the near future.

**Closed by robwormald** 2016-01-03 23:46 UTC

**Comment by thelgevold** [comment] 2016-01-04 00:12
Cool. It's definitely good to see that "post" will do an internal toJson() after this PR. 
The signature of the other http verb methods stay pretty much the same, right?

Yeah after thinking about it, I think it will be ok to explicitly include specific operators once people can read about them in the documentation. We will probably have useful samples for how to specify the imports and the belonging System.js configurations. Devs are likely to depend on the docs for samples anyway since Observables are a bit of a mental shift to most :-)

**Comment by robwormald** [comment] 2016-01-04 00:25
PUT should as well, as its the only other one that sends data. the inverse will likely be true, where requests that return JSON will have it automatically converted to JS.
