### ISSUE TITLE
Unable to sync two inputs with a value of -0.x

### ISSUE THREAD

**Issue by FrancescSM** [angular/angular#39926] opened 2020-12-02 08:18 UTC
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

I don´t think so

### Description

When use is typing a -0.x number in an input control (for instance -0.3) I am not able to sync it with another input using patchValue unless I filter it and losing synchronization for -0 values

## 🔬 Minimal Reproduction

     <div>
        <input"
          [id]="highRangeId"
          [max]="1"
          [min]="-1"
          [step]="0.1"
          type="range"
          [formControl]="chromaBoostFormGroup.controls['High']"
          />
        <output class="range-output">15</output>
        <input"
          [id]="highNumberId"
          [max]="1"
          [min]="-1"
          [step]="0.1"
          type="number"
          [formControl]="chromaBoostFormGroup.controls['High']"
          />
     </div>

  this.chromaBoostSubscription = 
    this.chromaBoostFormGroup.controls['High'].valueChanges.subscribe((value: string) => {
     if (this.chromaBoostFormGroup.controls['High'].valid){
       if (value != '-0' && value != '-0.' && value != '-.'){
         this.chromaBoostFormGroup.controls['High'].patchValue(value, { emitEvent: false });
       }
     this.changePoints();
     this.toggleRanges();
    }
  });

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
Angular10

**Anything else relevant?**

**Comment by petebacondarwin** [comment] 2020-12-02 10:46
@FrancescSM - please could you create a Stackblitz to demonstrate the problem you are having? This will help to speed up the process of us investigating the issue to diagnose if it is a bug that needs to be fixed in Angular.

**Comment by FrancescSM** [comment] 2020-12-02 17:09
Hi @petebacondarwin 

Find Stackblitz link below

https://stackblitz.com/edit/angular-ivy-gfrxyn?file=src/app/app.component.ts

**Comment by petebacondarwin** [comment] 2020-12-03 21:32
It's not a solution, as such, but if you make the `input[number]` a simple `input` then you don't have the problem.
But of course then you don't get the benefits of the number input parsing/validation etc.

**Comment by petebacondarwin** [comment] 2020-12-03 21:35
Actually the solution (keeping the number input) is to use a `pattern` validator: https://stackblitz.com/edit/angular-ivy-oobpil?file=src%2Fapp%2Fapp.component.html

Closing as this is working as expected and not a bug in Angular.

**Closed by petebacondarwin** 2020-12-03 21:35 UTC
Labels: comp: forms, needs reproduction
