### ISSUE TITLE
service-worker should allow bypassing it for some configurable url's (e.g. swagger-ui)

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular#20933] opened 2017-12-11 10:38 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
In Express, I configured the /docs route te serve swagger-ui.
With service-worker in place, it 'eats' the /docs route and navigates to the normal webapp. 

## Expected behavior
Please make it possible to configure URL's to bypass the service-worker behavior and just pass them to the webserver.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [ x] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
Mac

Others:

</code></pre>

**Comment by alxhub** [comment] 2017-12-12 23:08
Closing as a duplicate of #20404.

**Closed by alxhub** 2017-12-12 23:08 UTC
Labels: comp: service-worker
