### ISSUE TITLE
Pipes doc not loading when opening it in angular.dev https://angular.dev/api/common#pipes

### ISSUE THREAD

**Issue by GoraSharma** [angular/angular#55125] opened 2024-03-29 19:23 UTC
### Describe the problem that you experienced

Not able to open https://angular.dev/api/common#pipes as it shows the error page not found.

### Enter the URL of the topic with the problem

https://angular.dev/api/common#pipes

### Describe what you were looking for in the documentation

Pipes in angular

### Describe what you want to experience that would fix the problem

Show the documentation of pipes , not page not found

**Comment by JoostK** [comment] 2024-03-29 19:41
Thanks for the report, closing as duplicate of https://github.com/angular/angular/issues/52968.

**Closed by JoostK** 2024-03-29 19:41 UTC
