### ISSUE TITLE
Angular v5.0.0 is not part of the compilation output. Please check the other error messages for details.

### ISSUE THREAD

**Issue by xiongyayun428** [angular/angular#20091] opened 2017-11-02 08:11 UTC
![image](https://user-images.githubusercontent.com/11458959/32315694-202ee1de-bfe8-11e7-87cf-42394526d447.png)

Angular v4.4.6 upgrade v5.0.0

**Comment by xiongyayun428** [comment] 2017-11-02 08:14
"@angular/cli": "^1.5.0",
"typescript": "~2.6.1",

**Comment by BartBurger** [comment] 2017-11-02 10:17
Add that `index.ts` file to `tsconfig.json`'s "include" block. See below example:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],

    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*",
    "node_modules/angular-xyy/index.ts"
  ]
}
```

**Comment by mrcrixx** [comment] 2017-11-02 13:02
Same problem here. adding include doesn't help

Error: tsconfig.json(24,5): error TS5023: Unknown compiler option 'include'.

**Comment by 7185** [comment] 2017-11-02 13:16
> Error: tsconfig.json(24,5): error TS5023: Unknown compiler option 'include'.

You added it to "compilerOptions". You have to add it in the parent level.

**Comment by mrcrixx** [comment] 2017-11-02 13:18
yes I come back right now to give the update, yes that fixed the problem!

**Comment by Destreyf** [comment] 2017-11-02 18:08
From my research, the module included has a index.ts file and when those external modules are packaged that way typescript loads the index.ts file, instead of an index.js file, the above should work though.

**Comment by DDurga** [comment] 2017-11-02 18:34
Hi ,
still am facing same issue.
ERROR in ./node_modules/api-ai-javascript/index.ts
Module build failed: Error:

**Comment by xiongyayun428** [comment] 2017-11-03 03:08
using npm link, no node_modules?

```ts
npm link fis-ui
```

![image](https://user-images.githubusercontent.com/11458959/32358839-2038af4c-c084-11e7-86d9-f1150fc7f092.png)


![image](https://user-images.githubusercontent.com/11458959/32358876-68d58b58-c084-11e7-944b-0b973c2fe089.png)

**Comment by supertorpe** [comment] 2017-11-03 10:22
Same error here. I have a project ( https://github.com/supertorpe/angular-app-01 ) that lazy loads two modules:
- one whose code belongs to the project itself that runs ok (see branch 'runsok')
- and the other module: it's an external module (node_modules/@supertorpe/lib01) which fails with the issue title. If I add the "include" clause in tsconfig.json, the build is ok (but AOT fails with the same error), but when running the app, it shows an empty blank page with no error message in the developer console.

**Comment by vicb** [comment] 2017-11-03 18:41
I'm sorry but we don't understand the problem you are reporting.

If the problem still exists please open a new issue and provide a plunker reproducing the problem and describing the difference between the expected and current behavior. You can use this plunker template: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue

**Comment by matthewhegarty** [comment] 2017-11-05 12:21
I get a similar issue when running `ng serve --aot` (`ng serve` works ok).
Not sure if this is a compilation error or bug.

Error is: `table.component.ngfactory.js is not part of the compilation output`

Steps to reproduce are as follows:

```
cd /tmp
mkdir npm_issue && cd npm_issue

# download and install the library
git clone -b master https://github.com/matthewhegarty/ng2-datatable-bootstrap4
cd ng2-datatable-bootstrap4
npm install
npm run build
cd ..

wget https://github.com/angular/angular/files/1443989/npm-link-issue-test.tar.gz
tar xvzf npm-link-issue-test.tar.gz
cd ../npm-link-issue-test

# edit package.json to point to correct path for `ng2-datatable-bootstrap4/dist`
# in my case: "ng2-datatable-bootstrap4": "file:////tmp/npm_issue/ng2-datatable-bootstrap4/dist/"

npm install
ng serve --aot
```

[npm-link-issue-test.tar.gz](https://github.com/angular/angular/files/1443989/npm-link-issue-test.tar.gz)

```
Angular CLI: 1.5.0
Node: 6.9.5
OS: linux x64
Angular: 5.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.4
```

**Comment by micheleissa** [comment] 2017-11-06 23:30
This should be re-opened 
I'm having difficulty with adding a very simple npm pck that consists of a single Component to an angular app created via 'ng new' 
Once I downgrade the version something else ( e.g. ~4.3.4 ) it works with no issue and no need to add include in the tsconfig.json.

**Comment by trotyl** [comment] 2017-11-07 02:06
@micheleissa If you're reporting an Angular (AOT) compiler bug, please make a reproduction on pure `ngc` commands (without using `@angular/cli` or `@ngtools/webpack` in build process). 

Otherwise, you'd report it in Angular CLI as an integration problem.

**Comment by micheleissa** [comment] 2017-11-07 14:25
@trotyl Thank you.

**Comment by thatisuday** [comment] 2017-11-08 16:47
I am facing same problem. Looks like Angular 5 or Angular CLI 1.5.0 is not backward compatible.

**Comment by jjoao07** [comment] 2017-11-09 14:14
I'm having the same problem with my project!
everything was working fine, till when I decided to upgrade to angular 5, then everything started.

This the screenshot of the bugs which I'm not sure how to fix right now.

![image](https://user-images.githubusercontent.com/19816874/32609570-c5d4f4e0-c568-11e7-8e78-2d7b1048d5e7.png)


And on top of this bug, i got lot of warnings like so!

![image](https://user-images.githubusercontent.com/19816874/32609659-0de0ed98-c569-11e7-97db-acc7fbd9e70c.png)

so this is scaring us to follow, the upgrades.

**Comment by stephanecot** [comment] 2017-11-13 22:02
Same problem with the lib: https://mdbootstrap.com/angular
It's working if I used "--aot --preserve-symlinks".
But is it a bug or not? If I doesn't want to use aot, it crash.

**Comment by fredericojesus** [comment] 2017-11-26 22:58
Still having this issue with angular2-masonry library. 
--aot --preserve-symlinks solves the issue but for development is really not good because the build takes so much longer that just ng serve.
Anyone knows a better solution?
Adding the index.ts to tsconfig file didn't worked for me.

**Comment by Mds92** [comment] 2017-11-27 06:10
I have the same problem with https://www.npmjs.com/package/mds.angular.datetimepicker package,
I added `index.ts` to tsconfig file, no changes and I have the error!

**Comment by fredericojesus** [comment] 2017-11-27 14:18
@Mds92 Figured out the problem. You have to add to tsconfig.app.json instead of tsconfig.json.

**Comment by Mds92** [comment] 2017-11-27 14:23
Thanks, I added to `tsconfig.app.json`
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "../node_modules/mds.angular.datetimepicker/index.ts"
  ]
}
```
Now the following error occurre on `ng build`
```
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler\bundles\compiler.umd.js:20111:23)
    at CompileMetadataResolver.getNgModuleMetadata (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler\bundles\compiler.umd.js:15101:60)
    at visitLazyRoute (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler\bundles\compiler.umd.js:29995:104)
    at AotCompiler.listLazyRoutes (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler\bundles\compiler.umd.js:29963:20)
    at AngularCompilerProgram.listLazyRoutes (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler-cli\src\transformers\program.js:157:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:247:66)
    at Promise.resolve.then.then (D:\Sources\Mds92.github.io\MdsDateTimePickerSample\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:538:50)
```

**Comment by fredericojesus** [comment] 2017-11-27 14:29
When you put "include" in that file you have to specify all the times you want to be compiled. So you also have to add all your src files, ../src/**/*

**Comment by fredericojesus** [comment] 2017-11-27 14:31
Anyone with the same problem also check this comment https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325 . Everything is very well explain there by Filipe.

**Comment by Mds92** [comment] 2017-11-27 15:25
Thanks, I read it, I found my package library is not created in correct way, could you please post a reference to produce angular 5 library in standard and correct way?

**Comment by jjoao07** [comment] 2017-12-02 09:38
Hi Guys!

Not sure if i have fixed the problem or just got more trouble.

I have tried to fix the bug above, which was related 
ngx-sweetalert2 and ngx-select2 trowing error but ts inside node_modules.

So what i have done, i have moved those package inside my src folder,
I have created a module where do I import all my ngx  packages with problem

`import { NgModule } from '@angular/core';
import {LSelect2Module} from './ngx-select2/index';
import { SweetAlertService } from './sweet-alert.service';


@NgModule({
  imports: [
    LSelect2Module],
  exports: [
    LSelect2Module
  ],
  declarations: [],
  providers: [SweetAlertService],
})
export class NgxModule { }`

Then I import this NgxModule into my SharedModule, and all those bugs above disappear, 
and everything is compiled correct after ng serve.

But when I try to navigate into my app I got another bug which I have no idea where this come from, like below the screenshot.

![image](https://user-images.githubusercontent.com/19816874/33513981-6f5157c8-d754-11e7-94c0-d99135f84e24.png)

I tried googling it before, I find similar issue, where they saying that the error is related to guards, and my guard looks like this.

`import {Injectable} from '@angular/core';
import {Router, CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot} from '@angular/router';

@Injectable()

export class AuthGuard implements CanActivate{


	constructor(private router:Router){

	}

	canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot){
		 if (localStorage.getItem('token')) {
            return true;
        }
        this.router.navigate(['/auth/login'], { queryParams: { returnUrl: state.url }});
        return false;
	}
}
`
I tried Switching Observable to Promise like in the link below is described

https://stackoverflow.com/questions/41131476/emptyerror-no-elements-in-sequence

But nothing changed.

I have removed all Protected routes in my route file, but nothing helped.

Can you guys please Help me.
This my version I got so far

![image](https://user-images.githubusercontent.com/19816874/33514030-3d86c2e0-d755-11e7-9c8a-4c35fa7dc129.png)

**Comment by thisisgit** [comment] 2017-12-02 11:37
@jjoao07 Can you check your rxjs version? It may be related to this issue: https://github.com/ReactiveX/rxjs/issues/3151

**Comment by jjoao07** [comment] 2017-12-02 12:00
Hi @thisisgit 

below was my rxjs version

![image](https://user-images.githubusercontent.com/19816874/33515117-87e117ac-d767-11e7-826c-a2f8421e9e80.png)

And I have fixed this issue by following the link you mentioned, by downgrading the rxjs to 5.5.2

Now the question, is should I leave "rxjs": "5.5.2", like this forever or not?

**Comment by thisisgit** [comment] 2017-12-02 12:15
@jjoao07 Just subscribe to the issue that I shared and wait until rxjs team gives right fix to the problem. After the fix, then you can update the version

**Comment by jjoao07** [comment] 2017-12-02 12:31
okay I did!

Thanks

**Comment by IgorMinar** [comment] 2017-12-05 00:06
I'm reopening this because it seems to be the same issue as #20741 

Also see https://github.com/angular/angular/issues/20091#issuecomment-341969105 for suggested workaround.

**Comment by monterinio** [comment] 2017-12-14 22:00
./src/app/model/UsrToProject.ts
Module build failed: Error: C:\Users\MAMIKOLA\form-app\front-end\src\app\model\UsrToProject.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\MAMIKOLA\form-app\front-end\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:643:23)
    at plugin.done.then (C:\Users\MAMIKOLA\form-app\front-end\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/assign-user/assign-user.component.ts 11:0-53
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

When i comment constructor it compiles. 
Then I created second class with different name being a copy of the original class, guess what.. it compiled. Then I made some irrelevant changes in service somewhere else and still the problem occurs.

**Comment by avatsaev** [comment] 2017-12-15 15:38
Having the same problem, nothing helped:

**Comment by maqeelqureshi** [comment] 2017-12-16 22:30
I have added BartBurger suggestion to tsconfig.app.json and it worked for me.

My tsconfig.app.json file is 

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "include": [
    "src/**/*",
    "node_modules/angular-xyy/index.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}

**Comment by maqeelqureshi** [comment] 2017-12-18 19:10
Include worked for me previously but now it builds but browser shows following error when I try to open the page

`ERROR Error: Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_2__Models_Users_Signup2_model__.Signup2 is not a constructor

TypeError: __WEBPACK_IMPORTED_MODULE_2__Models_Users_Signup2_model__.Signup2 is not a constructor
    at new SignupComponent (signup.component.ts:19)
    at createClass (core.js:12166)
    at createDirectiveInstance (core.js:12011)
    at createViewNodes (core.js:13449)
    at createRootView (core.js:13339)
    at callWithDebugContext (core.js:14740)
    at Object.debugCreateRootView [as createRootView] (core.js:14041)
    at ComponentFactory_.create (core.js:10960)
    at ComponentFactoryBoundToModule.create (core.js:3922)
    at ViewContainerRef_.createComponent (core.js:11157)
    at new SignupComponent (signup.component.ts:19)
    at createClass (core.js:12166)
    at createDirectiveInstance (core.js:12011)
    at createViewNodes (core.js:13449)
    at createRootView (core.js:13339)
    at callWithDebugContext (core.js:14740)
    at Object.debugCreateRootView [as createRootView] (core.js:14041)
    at ComponentFactory_.create (core.js:10960)
    at ComponentFactoryBoundToModule.create (core.js:3922)
    at ViewContainerRef_.createComponent (core.js:11157)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)
defaultErrorLogger @ core.js:1350
ErrorHandler.handleError @ core.js:1411
next @ core.js:5376
schedulerFn @ core.js:4223
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4203
(anonymous) @ core.js:4651
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
NgZone.runOutsideAngular @ core.js:4577
onHandleError @ core.js:4651
ZoneDelegate.handleError @ zone.js:396
Zone.runGuarded @ zone.js:158
_loop_1 @ zone.js:702
api.microtaskDrainDone @ zone.js:711
drainMicroTaskQueue @ zone.js:610
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566`

**Comment by maqeelqureshi** [comment] 2017-12-18 19:38
Now this worked for me after changing the folder and class name.

**Comment by chuckjaz** [comment] 2017-12-19 20:04
I am having difficulty reproducing this problem.

Could someone interested in getting this fixed provide me with an example works in Angular 4.0 but doesn't work with Angular 5.0. I have tried several of the examples above and either they are broken in a similar way in Angular 4.0 or work in both. I am missing something obvious but so far have not been able to determine what this is.

It has been suggested above that this is very easy to reproduce but so far I haven't been able to. Could someone produce a repository that works in Angular 4.0 and then is broken when upgrading to Angular 5.0, preferably built from scratch using `ng` and no other changes than updating the package versions.

So far what I have determined is:

1. @xiongyayun428 provides a screen shot of a error message with no steps to reproduce so contains too little information to be actionable.
2. @xiongyayun428 follow-up I could not parse nor could I figure out what the highlighted areas are supposed to indicate.
3. @BartBurger suggestion to add files from `node_modules` in to the `"files"` section of the tsconfig.json should not be necessary. Instead the tsconfig.json should supply a `"rootDir"` value that include `node_modules` as a subdirectory.
4. This issue was reopened because of #20741 but #20741 the issue reported cannot be reproduce following the steps in the issue.

I suspect the issue is because `ngc` changed in where an how the factory modules are generated.

**Comment by stephanecot** [comment] 2017-12-19 20:45
If you create a angular-cli project with this lib:
https://mdbootstrap.com/angular/changelog/
you should normally have this error

**Comment by chuckjaz** [comment] 2017-12-19 21:24
I looked into this and `mdbootstrap` is huge and it is unclear to me exactly what you are asking me to do when you say "create an angular-cli project with...". Please give me steps like "git clone ..." or "ng new", "yarn add ..." or something similar.

Please treat me like the idiot I am and spell out exactly what you want me to do.

**Comment by IgorMinar** [comment] 2017-12-20 03:51
Just for the record: Chuck is not an idiot.

But we do need small reproductions of the problem with concrete steps that
lead to the problem and expected vs actual behavior. Otherwise we might not
understand what your problem is. Small repros help us avoid ambiguity and
fix problems faster.

**Comment by LastDragon-ru** [comment] 2017-12-20 06:22
Run
```
$ ng new test --skip-git
$ cd test
$ npm install angular-bootstrap-md
```

Update app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { MDBBootstrapModule } from 'angular-bootstrap-md';
import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    MDBBootstrapModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Run
```
$ ng build
```

Result:
```
Date: 2017-12-20T06:19:42.274Z
Hash: 1d341f6fb02942f487f1
Time: 6978ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 8.2 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 199 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 11.4 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 2.33 MB [initial] [rendered]

ERROR in ./node_modules/angular-bootstrap-md/index.ts
Module build failed: Error: test\node_modules\angular-bootstrap-md\index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (test\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:649:23)
    at plugin.done.then (test\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 9:0-58
 @ ./src/main.ts
 @ multi ./src/main.ts
```

My env
```
Angular CLI: 1.6.1
Node: 8.9.1
OS: win32 x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

**Comment by matthewhegarty** [comment] 2017-12-20 07:18
I added steps to reproduce for my issue earlier in the thread https://github.com/angular/angular/issues/20091#issuecomment-341969105

**Comment by stephanecot** [comment] 2017-12-20 09:10
No, your are not idiots :)
Sorry, yesterday I hadn't enougth time to make a full response.

@LastDragon-ru has made it after.

**Comment by syxhub** [comment] 2017-12-20 11:34
I have the same issue, upgrading from Angular 4.4.0 to 5.1.1
I had to both add some 3rd-party libs to the `include` section of `tsconfig.json`,
and set `"preserveSymlinks": true` in angular-cli.json

**Comment by rhino5oh** [comment] 2017-12-21 05:38
Still getting a bunch of "...*.ts  is not part of the compilation output. Please check the other error messages for details" when doing _ng build_ **OR** _ng build --preserve-symlinks_  (neither work)

_ng build --prod_, however, builds perfectly fine

src/tsconfig.app.json:
```
{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
  "includes": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```

some versions I'm using:
```
    "@angular/compiler-cli": "5.1.2"
    "@angular/animations": "5.1.2",
    "@angular/cdk": "5.0.2",
    "@angular/cli": "1.6.2",
    "@angular/common": "5.1.2",
    "@angular/compiler": "5.1.2",
    "@angular/core": "5.1.2",
    "@angular/forms": "5.1.2",
    "@angular/http": "5.1.2",
    "@angular/material": "5.0.2",
    "@angular/platform-browser": "5.1.2",
    "@angular/platform-browser-dynamic": "5.1.2",
    "@angular/platform-server": "5.1.2",
    "@angular/router": "5.1.2",
```

So I'm lost. I thought the "includes" section in tsconfig.app.json would fix the issues but it did not.  At the very least I though "ng build --preserve-symlinks" would allow me to build successfully but that too does not work. Any more info on this?

**Comment by doronsever** [comment] 2017-12-21 13:55
This happens to us after moving from 5.1.1 to 5.1.2

We get this error on this: 

> ERROR in ./node_modules/ngx-clipboard/src/clipboard.directive.ts
Module build failed: Error: /Users/MYUSER/dev/management/our-repo/node_modules/ngx-clipboard/src/clipboard.directive.ts is not part of the compilation output. Please check the other error messages for details.

Moving back to 5.1.1 solves this.
I tried adding stuff to the tsconfig.ts and tsconfig.app.ts but without any real success.

**Comment by avatsaev** [comment] 2017-12-21 14:29
I think this error is very misleading and doesn't actually means what it means. Itś waaay too obscure, is this   a webpack error message? they always use these unhelpful error messages.

**Comment by chuckjaz** [comment] 2017-12-21 17:36
@LastDragon-ru: Thank you for the repro steps! That is exactly what I was looking for!

This appears to me to be an issue with the Angular webpack plugin that comes from the Angular CLI. I will work with the cli team to determine the right way to address this.

**Comment by chuckjaz** [comment] 2017-12-21 19:42
This is due to a change made in the cli. See the comment https://github.com/angular/angular-cli/issues/8963#issuecomment-353436242 and https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325.

Specifically for for material bootstrap steps to compensate for the change are included in the change log here: https://mdbootstrap.com/angular/changelog/

Other libraries that use source (e.g. the `angular-xyy` seen in the original reporter's image) need a similar change in the client `tsconfig.json` file to work though might run into #20115.

I am closing this issue as a duplicate the originally reported as https://github.com/angular/angular-cli/issues/8284.

The AOT related issues will be addressed in #20115.

**Closed by chuckjaz** 2017-12-21 19:42 UTC
Labels: comp: core & compiler, freq3: high, severity5: regression, type: bug

**Comment by crh225** [comment] 2018-01-10 14:23
I was using the cli and getting this error message. It was because my version of typescript was not correct. I needed to update to typescript 2.4.2

**Comment by sparvov** [comment] 2018-02-13 15:41
My case is **mdbootstrap + jhipster**. I've fixed this issue adding 
```
"node_modules/angular-bootstrap-md/**/*.ts",
"src/**/*.ts"
```
to `tsconfig-aot.json` instead of `tsconfig.json`
