### ISSUE TITLE
RouterEvent url property ultimately undefined when subscribed to NavigationEnd event

### ISSUE THREAD

**Issue by mattrobins** [angular/angular#25322] opened 2018-08-06 11:31 UTC
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When retrieving the router url by subscribing to the NavigationEnd RouterEvent, the event is called multiple times ultimately leaving the url parameter undefined.

<pre><code>
  constructor(private router: Router) { 
    router.events.subscribe((_: NavigationEnd) => {
      this.currentUrl = _.url;
      console.log(_.url);
    });
  }
</pre></code>

Console screenshot here: https://i.imgur.com/FEmunY6.png

## Expected behavior

url parameter should reflect the current route url instead of being undefined.

## Minimal reproduction of the problem with instructions

Create a new angular app from the cli with routing and two components (eg. Sidebar & Posts).
```
ng new debugme --style=scss --routing
ng generate component sidebar
ng generate component posts
```

Main app component html will contain a reference to the sidebar and a router-outlet tag. And have routes setup so the default path goes to the Posts component.

```
#app.component.html

<app-sidebar></app-sidebar>
<router-outlet></router-outlet>
```

```
#app-routing.module.ts

const routes: Routes = [
  {
    path: '',
    component: PostsComponent
  },
];
```

In your Sidebar component import Router & NavigationEnd, and subscribe to the NavigationEnd event to retrieve the current url.

```
#sidebar.component.ts

import { Component, OnInit } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.scss']
})
export class SidebarComponent implements OnInit {

  currentUrl: string;

  constructor(private router: Router) { 
    router.events.subscribe((_: NavigationEnd) => {
      this.currentUrl = _.url;
      console.log(_.url);
    });
  }

  ngOnInit() {
  }

}
```

## Environment

<pre><code>
Angular version: 6.1.1

Browser:
- [x] Chrome (desktop) Version 67.0.3396.99 (Official Build) (64-bit)
- [x] Firefox version 61.0.1 (64-bit)
 
For Tooling issues:
- Node version: 8.11.3
- Platform:  Windows 10 x64

**Comment by trotyl** [comment] 2018-08-06 11:37
Duplicate of https://github.com/angular/angular/issues/14976

**Comment by mattrobins** [comment] 2018-08-06 12:43
Hi @trotyl, would be nice if you weren't so blunt. The issue you referenced is from version 4 and closed over a year ago. The guide material I had been following to learn Angular was using v6.0.7 where the code had worked for the author.

I did some more digging and it seems it's due to event filtering not working as expected with my code. My code fires on all these events (https://i.imgur.com/nv32zgK.png) even though I'm only asking for the NavigationEnd event. As a workaround I am checking that the event is an instance of NavigationEnd.

```
    router.events.subscribe(e => {
      if (e instanceof NavigationEnd) {
        this.currentUrl = e.url;
      }
    });
```
In this case it's not an issue with Angular. Apologies for posting an issue too early, I am new to Angular & Typescript.

**Closed** 2018-08-06 12:45 UTC

**Comment by trotyl** [comment] 2018-08-06 13:08
@maartentibau 

```
<!--
For bug reports please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/fork/angular-gitter).
-->
```

**Comment by maartentibau** [comment] 2018-08-06 13:18
@trotyl why am I being mentioned here?

**Comment by maartentibau** [comment] 2018-08-06 13:24
@trotyl aha :smile: no probs.. I was a bit confused
