### ISSUE TITLE
Angular2 Title service feature request - tie titleService.set to router navigation 1 

### ISSUE THREAD

**Issue by jeffschwartz** [angular/angular#9091] opened 2016-06-08 17:00 UTC
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
	
I'm using the following to update the document title when views change:
```html
<nav>
    <h1>Preamble BDD</h1>
    <ul>
        <li><a (click)="setTitle('Preamble BDD')" [routerLink]="['/']">Home</a></li>
        <li><a (click)="setTitle('Preamble BDD Changelog')" [routerLink]="['/changelog']">Changelog</a></li>
        <li><a (click)="setTitle('Preamble BDD API')" [routerLink]= "['/api']">API</a></li>
    </ul>
</nav>
<router-outlet></router-outlet>
```

It works but only when the user actually clicks on one of the links. However, when navigating via history (i.e. the browser's nav buttons) the document title remains unchanged and doesn't accurately reflect the current view. I am currently using the following in my views to get around this issue but it feels like something the Title service should be able to do if it was watching push and pop state events:
```typescript
import {Component} from "@angular/core";
import {Title} from "@angular/platform-browser";

@Component({
    templateUrl: "app/home.component.html"
})

export class HomeComponent {
    constructor(private titleService: Title) { }
    ngOnInit() {
        this.titleService.setTitle("Preamble BDD");
        console.log("ngOnInit called");
    }
}
```

Notice the implementation for ngOnInit in the component class. As I stated above, I think the Title service should be able to do this by listening to push and popstaate events.

Please consider adding this feature to the Title service.

**Comment by zoechi** [comment] 2016-06-08 17:07
At least related to #7630

**Comment by pkozlowski-opensource** [comment] 2016-06-08 17:12
Yeh, I think that we can safely close this as a duplicate of #7630. Thnx @zoechi - very helpful, as always!

**Closed by pkozlowski-opensource** 2016-06-08 17:12 UTC
