### ISSUE TITLE
After Update to 19.0.0-rc.1 the `ng serve` do not work with ssl anymore

### ISSUE THREAD

**Issue by salztorte** [angular/angular#58591] opened 2024-11-11 12:08 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I create a new angular project with `ng new test` and activated SSR.

If I now run `ng serve --ssl` and open the page I get this error message:
![Image](https://github.com/user-attachments/assets/eb085b0d-ee0f-4451-95f2-b180b09ab599)

If I just run `ng serve` everything works.

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.0-rc.1
Node: 20.16.0
Package Manager: npm 10.8.1
OS: darwin arm64

Angular: 19.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.0-rc.1
@angular-devkit/build-angular   19.0.0-rc.1
@angular-devkit/core            19.0.0-rc.1
@angular-devkit/schematics      19.0.0-rc.1
@schematics/angular             19.0.0-rc.1
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

**Comment by JoostK** [comment] 2024-11-11 12:14
Thanks for the report, this is a duplicate of angular/angular-cli#28807

**Closed by JoostK** 2024-11-11 12:14 UTC
