### ISSUE TITLE
Avoid boolean parameter in EventEmitter

### ISSUE THREAD

**Issue by tamascsaba** [angular/angular#6699] opened 2016-01-26 14:22 UTC
I think boolean in [EventEmitter](https://github.com/angular/angular/blob/master/modules/angular2/src/facade/async.ts#L109-L164) parameter is an antipattern, lot of articles ara in this topic:
http://silkandspinach.net/2004/07/15/avoid-boolean-parameters/

from
```
new EventEmitter(false)
```
to
```
new EventEmitter({isAsync: false})
```

One more thing node EventEmitter is sync by default:
https://github.com/Gozala/events/blob/master/events.js

**Comment by zoechi** [comment] 2016-01-26 16:25
dup of #6311

**Comment by pkozlowski-opensource** [comment] 2016-01-26 16:39
> One more thing node EventEmitter is sync by default:

This is duplicate of #6311

> I think boolean in EventEmitter parameter is an antipattern

Let's discuss this in [your pr](https://github.com/angular/angular/pull/6702)

**Closed by pkozlowski-opensource** 2016-01-26 16:39 UTC

**Comment by tamascsaba** [comment] 2016-01-27 08:59
@pkozlowski-opensource abd @zoechi thanks for quick answer.
