### ISSUE TITLE
Changing value of custom directive in template causes prod build failing. 

### ISSUE THREAD

**Issue by mohaxspb** [angular/angular#32761] opened 2019-09-18 22:37 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 No

### Description

 If there is custom directive in template and you assign new value to it in template prod build fails.

## 🔬 Minimal Reproduction

Repository with example: https://github.com/mohaxspb/ng-var-directive-issue

To get error just run `ng build --prod`

## 🔥 Exception or Error
<pre><code>
ERROR in Cannot assign to a reference or variable!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.4
Node: 10.15.3
OS: win32 x64
Angular: 9.0.0-next.6+80.sha-df1c456.with-local-changes
... animations, bazel, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, platform-server
... platform-webworker, platform-webworker-dynamic, router
... service-worker, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I'm in progress with PR with fix for it

**Comment by Splaktar** [comment] 2019-09-19 17:51
In the future, it would be best if example directives did not use the `ngXX` for directives that are not created by Angular. I.e. for your directives use something like `*myVar` instead of `*ngVar`.

**Comment by mohaxspb** [comment] 2019-09-19 19:09
@Splaktar OK, I change it in example)

**Comment by alxhub** [comment] 2019-10-08 22:42
Closing as a duplicate of #32695.

**Closed** 2019-10-08 22:43 UTC
Labels: comp: compiler

**Comment by mujahid-akbar** [comment] 2019-10-11 13:17
"angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
  }
causing this error, when fullTemplateTypeCheck is set to false, ng build --prod commad is successfully finishes.
