### ISSUE TITLE
9.1.5 @angular/compiler-cli throws `Cannot read property 'flags' of undefined`

### ISSUE THREAD

**Issue by slamjs** [angular/angular#37001] opened 2020-05-08 11:13 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli  9.1.5

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.1.4

### Description

ng build, as well as ng serve throws an error `Cannot read property 'flags' of undefined`

## 🔬 Minimal Reproduction

not able to provide

## 🔥 Exception or Error
<pre><code>
ERROR in TypeError: Cannot read property 'flags' of undefined
    at resolveAlias (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:36513:37)
    at checkAliasSymbol (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:64502:26)
    at checkImportBinding (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:64534:13)
    at checkImportDeclaration (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:64552:29)
    at checkSourceElementWorker (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:64961:28)
    at checkSourceElement (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:64800:17)
    at Object.forEach (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:317:30)
    at checkSourceFileWorker (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:65123:20)
    at checkSourceFile (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:65091:13)
    at getDiagnosticsWorker (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:65179:17)
    at Object.getDiagnostics (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:65165:24)
    at S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:98703:85
    at runWithCancellationToken (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:98665:24)
    at getBindAndCheckDiagnosticsForFileNoCache (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:98691:20)
    at getAndCacheDiagnostics (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:98956:26)
    at getBindAndCheckDiagnosticsForFile (S:\work\project-name\ui\node_modules\typescript\lib\typescript.js:98688:20)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.4
Node: 12.13.0
OS: win32 x64

Angular: 9.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cdk                      9.2.2
@angular/cli                      9.1.4
@angular/material                 9.2.2
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

When I downgrade @angular/compiler-cli to 9.1.4 error is gone

**Comment by nspeedzy** [comment] 2020-05-08 11:44
Apparently I also ran into the same issue.  I have a feeling that this problem could be caused by typescript.

**Comment by RANSoftRA** [comment] 2020-05-08 11:45
I am also running into the same problem. Also tried downgrading typescript - did not help.

**Comment by destus90** [comment] 2020-05-08 11:46
Duplicate of https://github.com/angular/angular/issues/36993

**Comment by alan-agius4** [comment] 2020-05-08 12:05
Closing as per above.

**Closed by alan-agius4** 2020-05-08 12:05 UTC
