### ISSUE TITLE
Rearranging items in an ngFor sometimes loses focus

### ISSUE THREAD

**Issue by KeatonTech** [angular/angular#43309] opened 2021-09-01 18:29 UTC
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When a focused element is rendered within an `ngFor` and the input list changes in order it will sometimes lose focus (`document.activeElement` will revert to `<body>`). This specifically only happens when the focused element moves 'up' in the DOM (eg has fewer siblings before it). It does not happen when the focused element moves down in the DOM. This is not a browser issue, as demonstrated here: https://jsfiddle.net/67edvycx/1/

### Please provide a link to a minimal reproduction of the bug

https://ng-run.com/edit/RPHg4b4yKbCv6piY0Mh1

### Please provide the exception or error you saw

```true
Focus is lost, which is a significant usability issue especially for users with vision or mobility impairments.
```

### Please provide the environment you discovered this bug in

```true
Angular 11.02
```

**Comment by pkozlowski-opensource** [comment] 2021-09-02 06:20
This is the "classical" use-case for `trackBy`, see: https://ng-run.com/edit/4raUZXEz4lLfDkg4W2A3

**Comment by KeatonTech** [comment] 2021-09-02 18:09
I don't think that's the behavior users want most of the time. The selection there has effectively changed. Plus, every component in the list has had to do significant re-rendering.

Using trackBy on the item value does not solve this problem: https://ng-run.com/edit/eNQuYlDMOfRJj3Ii0892

**Comment by mlc-mlapis** [comment] 2021-09-02 19:14
@KeatonTech  You need to use some unique permanent index, not a dynamic array index. So your array should look something like this:

```
readonly objectItems: Array<{name: string, id: number}> = [
    {name: "Item One", id: 1},
    {name: "-> Item Two <-", id: 2},
    {name: "Item Three", id: 3},
    {name: "Item Four", id: 4},
    {name: "Item Five", id: 5}
];
```
and the **trackBy** function like:

```
trackByIdFn(item): number {
    return item.id;
}
```

Then each object has its fixed permanent **id**

**Comment by KeatonTech** [comment] 2021-09-02 19:36
@mlc-mlapis Doesn't solve the problem, unfortunately: https://ng-run.com/edit/YsrHtHyW5jc0iSQNm5lB

Logically shouldn't make a difference, since the strings are also all unique.

**Comment by FrederikSchlemmer** [comment] 2021-09-27 07:28
@KeatonTech I currently have the identical problem. Are there any updates or workarounds currently available?

**Comment by KeatonTech** [comment] 2021-09-27 16:28
@FrederikSchlemmer Not that I know of. Still an open bug for my team

**Comment by windusayles** [comment] 2022-06-09 15:55
+1 to this bug

**Comment by pkozlowski-opensource** [comment] 2023-01-11 09:40
Duplicate of #45647

This is essentially the same issue as #45647 and I'm going to close this one in favour of #45647 as it has more detailed discussion.

**Closed by pkozlowski-opensource** 2023-01-11 09:40 UTC
Labels: area: common, P3
