### ISSUE TITLE
Allow @Directives to have styles attached

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular#48871] opened 2023-01-27 18:40 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Allow Angular `@Directive`s to attach styles the same way `@Component`s do.

I'm currently implement implementing a `@Directive` for rounding the corners of Angular Material Select.  This is a Demo:
https://stackblitz.com/edit/angular-ivy-cpfxig?file=src%2Fapp%2Fhello.component.css

The directive needs CSS in order to work properly.  Specifically it needs the class:
```
.el-RoundSelect
  .mat-mdc-form-field-flex
  .mdc-notched-outline
  .mdc-notched-outline__notch
  label.mdc-floating-label--float-above {
  top: 28px !important;
}
```

And it would be great if this class could be packaged with the directive.

### Proposed solution

Allow Angular `@Directive`s to attach styles the same way `@Component`s do.

### Alternatives considered

CSS can be inlined anywhere, but allowing it to be packaged with the directive keeps the design intent coherent.

### Stackoverflow

https://stackoverflow.com/questions/35915433/angular2-styles-in-a-directive

**Comment by JoostK** [comment] 2023-01-27 18:51
This is a duplicate of #17766.

**Closed by JoostK** 2023-01-27 18:51 UTC
