### ISSUE TITLE
Ivy: using local npm package does not compile

### ISSUE THREAD

**Issue by eiswind** [angular/angular#35247] opened 2020-02-08 10:56 UTC
### Affected Package
compiler.

### Is this a regression?

did work with 8.x

### Description

I have a local npm package declared like.
```
"@eiswind/proto-client-api": "../frontendclient/target/generated-sources/openapi/",
```
This used to work with 8.x but with 9 it gives me a trace like follows:
```
ERROR in .client/target/generated-sources/openapi/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /home/thomas/projects/eiswind/angular-proto-nebular/frontendclient/target/generated-sources/openapi/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/home/thomas/projects/eiswind/angular-proto-nebular/frontend/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:909:23)
    at /home/thomas/projects/eiswind/angular-proto-nebular/frontend/node_modules/@ngtools/webpack/src/loader.js:41:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
 @ ./src/app/product-management/onix-provider.service.spec.ts 4:0-60 12:25-40
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

## 🌍  Your Environment
```
**Angular Version:**
Angular CLI: 9.0.1
Node: 12.14.1
OS: linux x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      9.0.0
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4

```

**Comment by petebacondarwin** [comment] 2020-02-08 14:26
Could you provide a runnable reproduction of this error? It is difficult to track down the cause without knowing more about the build configuration.

**Comment by eiswind** [comment] 2020-02-08 16:44
please take a look at https://github.com/eiswind/ng-35247

to reproduce:
goto frontendclient/target/generated-sources/openapi (this normally gets generated)
npm install
npm run build

goto frontend
npm install
ng test

**Comment by petebacondarwin** [comment] 2020-02-08 16:48
I'll give it a try...

**Comment by eiswind** [comment] 2020-02-08 16:49
it has some other issues too with nebular, please don't get distracted by the other errors

**Comment by gkalpak** [comment] 2020-02-09 18:00
IIRC, npm will create symlinks when installing a package from a local URL. Maybe that is part of the problem.

**Comment by petebacondarwin** [comment] 2020-02-10 13:50
@gkalpak is correct. I managed to get the project to compile and tests to pass:

First of all note that the file path to the local lib in the reproduction project is actually wrong. It is pointing to the source code of the library rather than the code generated by ngPackagr. You need to add `dist` to the end of the file path.

Once that is fixed, you can either use `yarn` to do the installation, which will not create symlinks but make a copy of the local library; or if you want to continue to use npm, you can create a packed version of the library (via `npm pack`) and point to that as your dependency.

In order to actually get the build to complete you also need to run the `npm run sass` job to build the `style.css` that is required (why not get CLI to do this for you?)

I have created https://github.com/eiswind/ng-35247/pull/1 to illustrate what is needed.

---

Closing as I believe that this is all working as expected on the Angular side.

**Closed by petebacondarwin** 2020-02-10 13:50 UTC
Labels: comp: compiler, comp: ivy, severity5: regression

**Comment by eiswind** [comment] 2020-02-10 15:45
OMG I messed up the dist folder. Something changed the output path of the openapi generator, and by adapting to that I forgot to add the /dist.

@petebacondarwin Thank you very much for looking into this!
At least the tests run with symlinks on my linux box. no need to build the package.
I run the sass manually because I don't need it very often and its quite slow.

**Comment by petebacondarwin** [comment] 2020-02-10 15:47
> I run the sass manually because I don't need it very often and its quite slow.

No problem - I just added that to make it clear what I did.

**Comment by eiswind** [comment] 2020-02-10 15:55
Thanks a lot!
