### ISSUE TITLE
keyup.enter not firing on ↵

### ISSUE THREAD

**Issue by JanEggers** [angular/angular#21300] opened 2018-01-04 07:58 UTC
## I'm submitting a...
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Im using (keyup.enter) event to finalize some input. on Desktop this seems to work fine. When capturing all keyup events I either get { key: "Enter", code:"Enter" } or { key: "Enter", code: "NumpadEnter" } which work correctly.

On a Touch Panel from an onscreen keyboard I get: { key: "↵", code:"" } which  does not fire keyup.enter

## Expected behavior
keyup.enter should be fired when keyup with  { key: "↵", code:"" } is fired.

## What is the motivation / use case for changing the behavior?
It is unlikely that the behavior of the onscreen keyborad can be changed and i dont want to specialcase in all the places i accept inputs, so it would be nice if angular could handle this case.

## Environment

Angular version: 5.0.4

Browser:
- [x] Chromium on Exceed Panel

**Comment by trotyl** [comment] 2018-01-09 05:40
Duplicate of #21300 for custom key code mapping.

**Comment by TheSachin** [comment] 2018-03-27 09:10
Any status when it will be fixed?

**Comment by atscott** [comment] 2020-09-23 17:56
Closing as duplicate of #9419 / #8273 / #17128

**Closed by atscott** 2020-09-23 17:56 UTC
Labels: comp: core, core: event listeners, freq2: medium, severity3: broken, type: bug/fix
