### ISSUE TITLE
Angular animation: :enter & :leave have non-symmetric behavior

### ISSUE THREAD

**Issue by mfursov** [angular/angular#29509] opened 2019-03-25 18:14 UTC
### Affected Package
@angular/animations

### Description
:enter animation works, while :leave does not for child components of *ngFor
I believe that the behavior should be symmetric.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-qcqfdk?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment
Chrome 73

**Angular Version:**
7.2.5

**Anything else relevant?**
There is a workaround to make :leave animation to work by adding 
` trigger('animateChild', [
      transition(':enter, :leave', [query('@*', animateChild())])
    ]),`
trigger either to *ngFor or to a child component.

or by moving animation trigger from the child component to the *ngFor element.

**Comment by Sturgelose** [comment] 2019-03-29 13:29
We have exactly the same issue and we tracked the issue to `@angular/animations:7.2.8` before, it didn't happen, which means it's a regression. In chrome dev tools, we can see that the :leave animation appears to happen but too fast to see it, but I guess the problem was introduced in this PR: https://github.com/angular/angular/pull/28911

We think it's here because it's the only change related to animations in version 7.2.8. May it be something related to frames of the animation, where the animation is only doing one frame rather than all of them, thus seeming that there is no :leave animation?

We have pinned our angular animations version to 7.2.7 until a fix is released...

**Comment by dario-piotrowicz** [comment] 2021-11-26 21:23
Hi @mfursov the issue with your stackblitz is that you put the trigger in the `div` and not in the `li`, if you put `@EnterExit` in the `li` element everything works as expected as you can see in [this fork of your stackblitz](https://stackblitz.com/edit/angular-ppo6py?file=src%2Fapp%2Fapp.component.html)

The asymmetry is caused by the fact that the trigger is places in the wrong element, this causes the two different behavors, let me explain:
 - when a new `li` element enters, it creates a new `div`, so its `:enter` animation kicks in and it gets animated as expected
 - but when you remove an `li` element, it gets removed right away (it doesn't wait for anything, you haven't instructed the `li` to do anything of the sort), and the `:leave` animation is on the `div` which is "abruptly" removed from the dom without a chance to animate. Angular actually sort of tries to animate the `div` but it can't because it does not exist in the dom anymore.
 
This makes total sense, because as I just said the `li` element is added and removed by the `*ngFor` there is not logic/magic for it to know that one of it's children (the only one in this case) would want to animated a leave animation.

I hope this helps :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment] 2021-11-26 21:28
I think there is much lack of clarity on how enter and leave animations work and are supposed to work (I've got this issue open to clear this out a bit: https://github.com/angular/angular/issues/44253)

In your case I think that neither enter not leave animations should be triggered as the `div` element is not actually entering/existing by its own accord.
But that's my opinion and it's not related to this issue :slightly_smiling_face: 

I think this issue should potentially be closed as working as expected, unless you @mfursov disagree of course :slightly_smiling_face:

**Comment by jessicajaniuk** [comment] 2021-12-13 22:19
Thanks @dario-piotrowicz, for your clarifications here. @mfursov, I'm going to close this as behaving as intended, but we can definitely re-open if you feel this answer isn't clear enough / there's still a problem other than the open issue for documentation.

**Closed by jessicajaniuk** 2021-12-13 22:19 UTC
Labels: type: bug/fix, comp: animations, freq2: medium, P3
