### ISSUE TITLE
Route Guard which consumes an Observable should take more than one

### ISSUE THREAD

**Issue by envil** [angular/angular#33112] opened 2019-10-11 20:13 UTC
# 🚀 feature request

### Relevant Package
This feature request is for @angular/angular

### Description
When we want to feed the Route Guard with an `Observable`, e.g., return an `Observable` in the `canDeactivate` function, router should be able to take more than one value in the `Observable`, not just the first one like in the current implementation:
https://github.com/angular/angular/blob/362b3e4d03f1ba222e3dd2002a4b85a104453159/packages/router/src/operators/check_guards.ts?fbclid=IwAR2oQCRxXyY3EX2FyltQBXJ5I_cA8Gsnw9YpMiA0lv4VQ2fhQORjUeWcutw#L155

### Describe the solution you'd like
Remove the `first()` pipes.

### Describe alternatives you've considered
If it's problematic to do so, then at least the docs should be updated to describe what's going on, like stated in here: https://github.com/angular/angular/issues/21537

**Comment by Airblader** [comment] 2019-10-11 20:59
This is a duplicate of #10556 and there's already a lot of discussion around this there.

**Comment by Airblader** [comment] 2019-10-11 21:00
> router should be able to take more than one value in the Observable, not just the first one

And what exactly would happen if the guard returns first false and then true or vice versa?

**Comment by envil** [comment] 2019-10-12 21:44
> > router should be able to take more than one value in the Observable, not just the first one
> 
> And what exactly would happen if the guard returns first false and then true or vice versa?

Sorry, maybe I didn't pointing out the scenario clear enough. For the case with `canActivate`, it doesn't really makes sense, but for the `canDeactivate` case, it could be different. Let's say I want to create a `PreventClosingGuards`, where the output of `canDeactivate` is getting from an `Observable` (where the value is coming from some other logic and is subjected to change), then it would make much more sense for the guard to take more than one value.

**Comment by Airblader** [comment] 2019-10-12 22:02
My question still stands: what should actually happen when the observable first emits false and then true, say two minutes later?

**Comment by atscott** [comment] 2019-10-17 22:22
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Closed by atscott** 2019-10-17 22:22 UTC
Labels: comp: router
