### ISSUE TITLE
Support for multiple cases in control flow

### ISSUE THREAD

**Issue by MunMunMiao** [angular/angular#52920] opened 2023-11-15 02:58 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

```html
@switch (type) {
  @case(1) {
    <app-home />
  }
  @case(2) {
    <app-home />
  }
  @case(3) {
    <app-home />
  }
  @case(4) {
    <app-user />
  }
  @default {
    <app-error />
  }
}
```

If multiple cases are needed to support rendering the same content, it needs to be replicated several times. Supporting multiple cases can effectively solve this problem

### Proposed solution

```html
@switch (type) {
  @case(1)
  @case(2)
  @case(3) {
    <app-home />
  }
  @case(4) {
    <app-user />
  }
  @default {
    <app-error />
  }
}
```

### Alternatives considered

```html
@switch (type) {
  @case(1, 2, 3) {
    <app-home />
  }
  @case(4) {
    <app-user />
  }
  @default {
    <app-error />
  }
}
```

this code style some like golang

**Comment by JoostK** [comment] 2023-11-15 07:47
I am going to close this as a duplicate of #14659.

**Closed by JoostK** 2023-11-15 07:47 UTC
