### ISSUE TITLE
Deactivate guards with eager URL updating do not trigger navigations if they ever return false

### ISSUE THREAD

**Issue by MonocleKelso** [angular/angular#40194] opened 2020-12-18 19:15 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No

### Description

 Guarding a route with canDeactivate and the router's urlUpdateStrategy set to 'eager' doesn't allow for subsequent attempted requests to the same route. The guard fires the first time but does not if you request the same route again.

## 🔬 Minimal Reproduction

 https://github.com/MonocleKelso/EagerUrlGuardBug

Check out the above repo and serve the app. The repro steps are included in the app. Basically - trying to navigate away from a guarded route and returning false from the guard causes subsequent attempts to navigate to the same route to do nothing. It appears as if the router thinks it was able to navigate to the new route and therefore doesn't need to do anything else.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 10.1.7
Node: 12.18.4
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    10.2.7
@angular/cli                    10.1.7
@angular/material               10.2.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment] 2020-12-18 21:46
Duplicate of #28561

**Closed by atscott** 2020-12-18 21:46 UTC
