### ISSUE TITLE
Variables in animation metadata fails to interpolate using compiler AOT.

### ISSUE THREAD

**Issue by jordic** [angular/angular#12187] opened 2016-10-09 18:25 UTC
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Minimal reproduction of the problem with instructions**

Something, like:

```
export CardStates {
static in:string = "in"
static out:string = "out"
}

@Component({
...
animations: [
  trigger('frontState', [
      state(CardStates.in, style({
        transform: 'rotateY(0deg)'
      }))
   ])
]
})
```

Fails with the following error:

```
TypeError: stateMetadata.stateNameExpr.split is not a function
    at _parseAnimationDeclarationStates (/home/jordi/Documents/lupa/node_modules/@angular/compiler/bundles/compiler.umd.js:9688:48)
    at /home/jordi/Documents/lupa/node_modules/@angular/compiler/bundles/compiler.umd.js:9640:15
```

**Expected behavior**

I'm not sure if it is a expected behaviour but in this case, I think it should fail, with a more descriptive message... For debugging the error, i have had to start tracing at compiler.umd.js.
(It's still not clear for me where is the line on what can I use when I try to compile with AOT)
Also, I can't understand why I can't use functions on metadata... (Perhaps is related to this, but it's not clear for me)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

ng-cli
- **Angular version:** 2.0.X
  

angular 2.0.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:**  TypeScript 2.0.2
- **Node (for AoT issues):** `node --version` =   6.7.0

**Comment by zoechi** [comment] 2016-10-10 05:30
Bug reports need to include a Plunker that allows to reproduce as stated in the issue template.

**Comment by zoechi** [comment] 2016-10-10 05:31
Sounds like https://github.com/qdouble/angular-webpack2-starter#aot--donts, don't use functions in decorators directly.

**Comment by jordic** [comment] 2016-10-10 05:42
@zoechi 
Can you point me on a plunker example that uses the aot? And I will write one.

It's not a function, it's a variable. Also, in this case, I think the compiler should complain... All I've got is a split error.

**Comment by matsko** [comment] 2016-10-11 20:24
There are some things I'm unsure about here. CardStates is supposed to be a class yes? Is it failing because the variable isn't available due to some import issue? `state` should be able to read this fine since it is a string value that is passed in no? Unless it's null.

**Comment by jordic** [comment] 2016-10-12 04:07
A repo to reproduce the error:

https://github.com/jordic/angular_issue12187

**Comment by benelliott** [comment] 2016-10-14 15:47
@matsko More generally, is there any way to build a set of reusable animations that will still compile through AOT?

With JIT I was simply exporting a bunch of AnimationEntryMetadata objects and referencing them through my component decorator, e.g. `animations: [Animations.EXPAND_WIDTH]`.

This doesn't work in AOT, as animations' state metadata is not generated correctly. I don't want to re-declare the animation in every component decorator as they're about 6 lines each and always the same.

**Comment by DzmitryShylovich** [comment] 2017-03-10 12:01
@jordic is this still valid in angular 4?

**Comment by matsko** [comment] 2018-04-11 21:17
Closing this for now since it's been a year since any acitivty. Please open a new issue and tag me if it's still not functional.

**Closed by matsko** 2018-04-11 21:17 UTC
Labels: comp: animations, severity1: confusing, state: Need repro, type: bug/fix
