### ISSUE TITLE
Migrating to v8 changes ViewChild to VViewChild

### ISSUE THREAD

**Issue by dushkostanoeski** [angular/angular#30713] opened 2019-05-29 06:39 UTC
### Description

This might be connected to angular/angular-cli#14551 and angular/angular-cli#9712

After I ran the migration, all my `ViewChild` references turned into `VViewChild`. 

Edit: I just noticed that this only happened to the files with `UTF-8` encoding. The files encoded with `UTF-8 BOM` are good.

**Comment by devversion** [comment] 2019-05-29 09:28
@alan-agius4 Is this is actually an issue from the schematic? My impression is that this is related to the update recorder from the CLI that every migration schematic leverages. 

That's why similar issues appear for the lazy route syntax migration. I think we should have a more generic issue for this on the CLI repository as there is nothing we could do about this here.

**Comment by alan-agius4** [comment] 2019-05-29 09:57
As discussed offline, the problem is indeed in the CLI because the `updateRecorder` methods such as `insertLeft`, `remove` etc.. accepts positions which are not offset by a BOM. This is because when a file has a BOM a different recorder will be used https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics/src/tree/recorder.ts#L72 which caters for an addition offset/delta.

The main reason for this is that when a developer is writing a schematic they shouldn't need to compute the offset based if a file has a BOM or not and is handled out of the box.

Example
```ts
recorder.insertLeft(5, 'true');
```

However this is unfortunate in the case if a ts SourceFile is used and one uses `getWidth` and `getStart` method they will already be offset by 1, which at the end it results in a double offset and hence the problem.

**Comment by devversion** [comment] 2019-05-29 10:07
> The main reason for this is that when a developer is writing a schematic they shouldn't need to compute the offset based if a file has a BOM or not and is handled out of the box.

Just to add to that: I see the point of doing that, but it is simply resulting in magic behavior as schematics are not handwritten and if schematics are applying replacements to source-files, the offsets are usually determined by parsing the file.

e.g. `fs.readFileSync('./with_bom.txt', 'utf8').length` will respect the BOM characters and it's common that indices passed to the update recorder will be *truly absolute*.

Ideally the magic differentation between BOM and non-BOM files would have not happened at all, but for now the easiest way to fix this in a backwards-compatible way (where older CLI versions are used) is to strip the BOM when parsing the TypeScript source-files.

We need to find a proper solution for this in the future though. It adds unnecessary bloat and confusion to schematics as they need to know about / and handle BOM characters in a special way.

**Comment by alan-agius4** [comment] 2019-05-29 10:24
@devversion I think this discussion should be moved in a new issue in the CLI repo.

**Comment by devversion** [comment] 2019-05-29 10:39
@alan-agius4 Yeah I was asking for that one in some post above. I'm working on creating one 🙂

**Comment by devversion** [comment] 2019-05-29 10:49
Thanks @dushkostanoeski for submitting that issue! 

A temporary fix for this has been created in #30719, but the underlying issue is tracked with https://github.com/angular/angular-cli/issues/14558. We can close this issue once the temporary fix landed.

**Closed** 2019-05-31 03:50 UTC
Labels: comp: core & compiler, freq2: medium, severity3: broken, state: has PR, type: bug/fix
