### ISSUE TITLE
Content projection with nested IF does not work

### ISSUE THREAD

**Issue by JusuVh** [angular/angular#55462] opened 2024-04-22 14:03 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using multi-slot content projection, content nested behing multiple IF clauses does not get projected. A simple exemple of this with these components :

```
@Directive({
  selector: '[directive-1]',
  standalone: true,
})
export class Directive1 {}

@Component({
  selector: 'component-1',
  template: `<ng-content select="[directive-1]"></ng-content>`,
  standalone: true,
})
export class Component1 {}
```
and this scenario :
```
<component-1>
  <div directive-1>Test No If</div>
  <br />
  @if (true) {
    <div directive-1>Test If</div>
  }
  <br />
  @if (true) {
    @if (true) {
      <div directive-1>Test Nested If</div>
    }
  }
</component-1>
```

The first 2 `<div directive-1>` are projected and shown correctly, the 3rd is not.

I do not know if this is a regression but it does not work with `<ng-container *ngIf="true">` either. It is even worse because it does not work with 1 level of IF when used with a container. It does however work when used directly on the element, like this `<div *ngIf="true" directive-1>` (consistent with `@if` notation, only works 1 level down).

If you remove the `select` attribute from the `ng-content`, everything works fine, so I suppose this is combination of the select selector looking only at the root elements of the projected content and the IF creating and 'invisible' dom element that hides the content from the selector tree.

The workaround is obvisouly to use only one level of IF in the code but it sometimes duplicates code and the behavior seems inconsistent accross uses.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.2
Node: 18.19.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.3.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@angular/cli                    17.3.2
@schematics/angular             17.3.2
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

**Comment by pkozlowski-opensource** [comment] 2024-04-22 14:17
Duplicate of #54035

**Closed by pkozlowski-opensource** 2024-04-22 14:17 UTC
