### ISSUE TITLE
Wrong example for outputs option in Component decorator

### ISSUE THREAD

**Issue by saiKumarGanji** [angular/angular#30176] opened 2019-04-28 08:14 UTC
# 🐞 bug report

### Is this a regression?
Not aware

### Description
Wrong example for outputs option in Component decorator.
Please refer the link https://angular.io/api/core/Directive#outputs

**Comment by ericmartinezr** [comment] 2019-04-28 12:41
Dup of https://github.com/angular/angular/issues/29523, fixed by https://github.com/angular/angular/pull/30014

**Comment by AndrewKushnir** [comment] 2019-04-28 19:52
@saiKumarGanji thanks for noticing the problem and reporting it. As @ericmartinezr mentioned, it seems like a duplicate of #29523, so I'm closing this ticket. You can get the latest status by following [this link](https://github.com/angular/angular/issues/29523). Thank you.

**Closed by AndrewKushnir** 2019-04-28 19:52 UTC
