### ISSUE TITLE
feat: expose a method to provide functional http interceptors without having to use withInterceptors([...])

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#51303] opened 2023-08-09 10:09 UTC
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

When using class based interceptors we were able to just provide a token and it would be registered. 

```ts
providers: [
  {
    provide: HTTP_INTERCEPTORS,
    useClass: ErrorsInterceptor,
    multi: true,
  }
]
```

This gave us the possibility to just provide this token and the DI would do it's job to register the interceptor. 

With functional http interceptors, we loose this ability because we have to register them using the [withInterceptor()](https://github.com/angular/angular/blob/1eda1bdfccc09426ea8d8dd8cfbd8f521cc15f14/packages/common/http/src/provider.ts#L111) method inside [provideHttpClient()](https://github.com/angular/angular/blob/1eda1bdfccc09426ea8d8dd8cfbd8f521cc15f14/packages/common/http/src/provider.ts#L68C17-L68C34) like this: 

```ts
providers: [
  provideHttpClient(withInterceptors([errorInterceptor]))
]
```

This is great until we need to add providers or interceptors from a library. For example: 

```ts
providers: [
  provideHttpCache()
]
```

I want to be able register some http interceptors from this provider function directly (just like we were able to do it before).

### Proposed solution

Maybe expose [HTTP_INTERECPTOR_FNS](https://github.com/angular/angular/blob/1eda1bdfccc09426ea8d8dd8cfbd8f521cc15f14/packages/common/http/src/interceptor.ts#L155) so we can just provide this token with our providers just like before. 

Or expose a method that provides this token with our value. 

Sth like: 

```ts
provideInterceptors([errorInterceptor])
```

### Alternatives considered

Use class based interceptors.

**Comment by JoostK** [comment] 2023-08-09 10:14
This was a deliberate design choice of the new API; interceptors are sensitive to ordering _and_ the registration of the HTTP services to actually consider those interceptors, so the API was designed such that both ordering and the registration is determined in a single place.

**Comment by pkozlowski-opensource** [comment] 2023-08-09 13:33
> This was a deliberate design choice of the new API; interceptors are sensitive to ordering and the registration of the HTTP services to actually consider those interceptors, so the API was designed such that both ordering and the registration is determined in a single place.

Pretty much what @JoostK is saying - the ordering part is crucial: with automatic registration we can't really control it. 

Will close as "won't fix" since the current behaviour is a deliberate design choice.

**Closed by pkozlowski-opensource** 2023-08-09 13:33 UTC

**Comment by AndrewKushnir** [comment] 2023-08-09 17:26
@eneajaho thanks for creating the ticket. We've discussed this question with the team further and the proposed solution for the pattern that you've described is to expose 2 public APIs from the library:

- the `provideHttpCache` function, which would bring the necessary providers required for the feature to work
- an interceptor function that would contain the necessary logic

To install the library into an application, a developer would need to do 2 steps:

- add the `provideHttpCache()` call into the providers array
- add an interceptor function to an existing `provideHttpClient(withInterceptors(...))` or add a new `provideHttpClient` if it was not there before

In this scenario, developers are able to control the order of interceptors, which avoids the problem that Joost and Pawel mentioned above.

**Comment by pkozlowski-opensource** [comment] 2023-08-09 20:53
To add to @AndrewKushnir message: the `provideHttpCache()` pattern of adding providers is mostly useful for cases where providers need to be configured somehow and / or added optionally. For other cases providing a service in root is  the very reasonable option.
