### ISSUE TITLE
Standalone directive's input should be aliased when input named "simultaneously"

### ISSUE THREAD

**Issue by platon-rov** [angular/angular#48706] opened 2023-01-11 22:35 UTC
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

```ts
@Directive({
  selector: '[standalone]',
  standalone: true,
})
export class StandaloneDirective {
  @Input()
  set standalone(value: any) {
    // ...
  }
}

@Directive({
  selector: '[app-child]',
  hostDirectives: [
    {
      directive: StandaloneDirective,
      inputs: ['standalone: alias']
      /*
        Work:
        <div app-child alias="...

        Don't work, Error: NG0309
        <div app-child standalone="...
      */
    },
  ],
})
export class ChildDirective {}
```

This makes it impossible to have a single api when there is a single implementation. If both (standalone directive and component where it's provided) exposed, it adds misunderstanding where and which (alias or real name) should be used.

Looks like in this case when the directive is already applied in code we can skip second applying and just pass the input value.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-cumnea?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
Error: NG0309: Directive ... matches multiple times on the same element. Directives can only match an element once.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
StackBlitz Angular 15.0.2
```

**Comment by JeanMeche** [comment] 2023-01-12 01:55
Somehow a dupe of #48128 ?

**Comment by crisbeto** [comment] 2023-01-12 07:49
Exposing the input both as `standalone` and `alias` would defeat the purpose of aliasing it in the first place. We have the aliasing feature so that the consumer of the host directive is able to remap the input, not expose it under a different name. If you want to have two inputs under the same name, you can do it using getters and setters. E.g. 


```
class YourDirective {
  private inputValue: any;

  @Input()
  get standalone() { return this.inputValue; }
  set standalone(value: any) { this.inputValue = value; }

  @Input()
  get alias() { return this.inputValue; }
  set alias(value: any) { this.inputValue = value; }
}
```

**Closed by crisbeto** 2023-01-12 07:49 UTC

**Comment by platon-rov** [comment] 2023-01-12 08:55
@crisbeto I'm talking about a kinda different thing, let me try to rephrase.

For example, I have a `cdkFocusable` standalone directive to add a focusable behavior. And this directive has input named "simultaneously" with the directive selector. I expose this directive as well as use it in components.

So I have a single implementation for focusable behavior, but I cannot have a single API and it leads to confusing people who gonna use both.

```html
<div cdkFocusable>
    I'm focusable
</div>

<div [cdkFocusable]="false">
    I'm NOT focusable
</div>

<div someDirective>
    someDirective has cdkFocusable provided in hostDirectives thus i'm focusable
</div>

<!-- I cannot have this unified API, it throws error -->
<div someDirective [cdkFocusable]="false">
    someDirective has cdkFocusable provided in hostDirectives thus i'm focusable, 
    but i want to disable it
</div>

<!-- It's possible with aliasing but the API is different and going to confuse users -->
<div someDirective [someDirectiveFocusable]="false">
    someDirective has cdkFocusable provided in hostDirectives thus i'm focusable,
    but i want to disable it
</div>
```
