### ISSUE TITLE
FormGroup errors is null when invalid

### ISSUE THREAD

**Issue by michaelchiche** [angular/angular#11530] opened 2016-09-12 10:24 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I am not sure if this is the requested behavior, but this behavior does not seem logical to me.

**Current behavior** 
When using Reactive Forms, a formGroup containing FormControls which are invalid is shown as invalid which is normal, but it does not contain any errors.

**Expected behavior**
We should be able to get all the errors from FormControls | FormGroups | FormArrays inside their containing FormGroup.

**Reproduction of the problem**
http://plnkr.co/edit/OMnHZkHRIc75RRQM9XRz?p=preview

**What is the motivation / use case for changing the behavior?**
I have a form with required inputs. I fill in some input but not all of them. 
So some input are in the pristine and also invalid. (like in the example of the tutorial for template driven forms): http://plnkr.co/edit/rzQfRbufDDRmDtGFbPIy?p=preview).

I decide to click on the submit button, but I have errors, so I want to show all the inputs with errors that the user has missed.

**Please tell us about your environment:**
OS X 10.11, Visual Studio Code

* **Angular version:** 2.0.0-rc.6

* **Browser:** [all ] 

 
* **Language:** [TypeScript 2.0.0]
 
* **Node (for AoT issues):** `node --version` =   v6.5.0

**Comment by kara** [comment] 2016-09-12 17:07
This looks like a duplicate of #10530.  It was originally designed this way because there are infinite ways to reduce errors (by error type? by control? etc), but we should really offer some utility methods.  We are tracking the feature request in the other issue.

**Closed by kara** 2016-09-12 17:07 UTC
Labels: comp: forms
