### ISSUE TITLE
https://angular.io/guide/webpack Missing class view-SideNav in aio-shell

### ISSUE THREAD

**Issue by sekerin** [angular/angular#18370] opened 2017-07-27 09:51 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In page https://angular.io/guide/webpack the menu block overrides the container block
Block `<md-sidenav-container>` has style `max-width: none`, because `aio-shell` does not have class `view-SideNav`
It's make page hard to read.

## Expected behavior

Separate content block and menu block

## Minimal reproduction of the problem with instructions

Go to page https://angular.io/guide/webpack

## Environment

<pre><code>

Browser:
- [x] Chrome (desktop) version 60.0.3112.78
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by gkalpak** [comment] 2017-07-27 10:38
Duplicate of #17912.

**Closed by gkalpak** 2017-07-27 10:38 UTC
