### ISSUE TITLE
feat: add bracket access to safe navigation operator

### ISSUE THREAD

**Issue by karptonite** [angular/angular#17181] opened 2017-06-02 18:39 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

The safe navigation operator `?.` is great, but it would be even better if it also supported bracket notation, `foo?[bar]`. This was first mentioned here, but didn't get any traction
https://github.com/angular/angular/issues/791#issuecomment-77801474

**Comment by akram1905** [comment] 2017-10-05 00:50
Any updates?
Now we have Angular Language Service, it's annoying seeing this "error".
Mostly I need it in errors validations like `input.errors?['required']` instead of `input.errors?.required`.

**Comment by trotyl** [comment] 2018-01-25 15:32
This syntax is too ambiguous, and already got rejected in [optional chaining proposal](https://github.com/tc39/proposal-optional-chaining). The final syntax should be `foo?.[bar]` or `foo??[bar]` (Waiting for tc39-notes to update).

Writing different syntax in logic code and template code may not be a good idea.

**Comment by mtuzinskiy** [comment] 2018-07-05 14:56
Any updates on this? Thank you

**Comment by sheikalthaf** [comment] 2019-09-05 16:16
@chuckjaz @hansl @trotyl Any update on this?

**Comment by trotyl** [comment] 2019-09-06 05:15
@sheikalthaf In JavaScript the syntax has been settled as `a?.[x] `, I'm not sure whether Angular are currently consider this, but likely no one would like to write different syntax between TypeScript and template expression.

**Comment by AbakumovAlexandr** [comment] 2019-09-06 14:18
@trotyl I guess we mostly interested in being _able_ to navigation safely with arrays\objects.

I believe very little people her are concerned in it being implemented via either `foo?[bar]` or `foo?.[bar]`, so whatever is simpler\faster to implement.

**Comment by electrofLy** [comment] 2019-11-07 15:44
Any updates or workarounds on this?

**Comment by sheikalthaf** [comment] 2019-11-27 15:43
Any possibility of this feature to be available in ivy?

**Comment by nadeemramsing** [comment] 2020-01-31 20:17
Any news on this feature?

**Comment by pkozlowski-opensource** [comment] 2020-03-12 08:12
So, this is [supported in TS 3.7](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) but not supported in expressions used in Angular templates: https://ng-run.com/edit/sqFt4zLEyZ9oOMDtmOxp

**Comment by pkozlowski-opensource** [comment] 2020-05-08 14:11
For the record, we are tracking all issues related to `?` support in #34385

**Comment by craftmaster2190** [comment] 2020-05-08 17:25
Arrays/Indexes are safely navigated in templates but not in the way one would expect:
In TypeScript: `foo?.bar?.[0]?.quxx`
In Angular Templates: `foo?.bar[0]?.quxx`
See https://github.com/angular/angular/issues/13254
and https://github.com/angular/angular/commit/f31c9470fae06adc69b2b665773bfc0a8a10d10e

**Comment by pkozlowski-opensource** [comment] 2020-05-11 14:41
I'm going to close it as a duplicate of #34385 - I think that the good, longer-term strategy is to align Angular expression syntax with what is cooking on the ES side: https://github.com/tc39/proposal-optional-chaining - we don't want to maintain same syntax with the different semantics on the Angular side.

**Closed by pkozlowski-opensource** 2020-05-11 14:41 UTC
Labels: comp: compiler, comp: core, core: property / attr bindings and interpolations, type: feature
