### ISSUE TITLE
Reactive Forms not registering formGroup property after installing angular material package

### ISSUE THREAD

**Issue by maxgaurav** [angular/angular#33345] opened 2019-10-23 09:19 UTC
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms @angular/cdk @angular/material

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
**N/A. It's a new installation.**

### Description

The application is using angular reactive forms. After installing the angular material package the components containing the reactive forms throws error while **live reloading** when changes are done in the HTML part of the component.

Even gives the same error when refreshing the browser on first successful load.

Point to note: Builds are not showing this error only when running the application in serve mode. 

## 🔬 Minimal Reproduction

Github Repository: [https://github.com/maxgaurav/sample-form-group-error](https://github.com/maxgaurav/sample-form-group-error)

### Steps to Replicate
All steps to replicate in detail
1. Clone the repo
2. Install dependencies using **npm install**
3. Run the app using **ng serve**
4. An basic login page should open without any errors. 
5. Now change something in the **login.component.html** file you should see the error mentioned.
6. Now change something in the **login.component.ts** file. 

The error should go away. The error also goes away for the first time when the ng serve is done again but comes back when page is refreshed.

## 🔥 Exception or Error
<pre><code>

core.js:6014 ERROR Error: Template error: Can't bind to 'formGroup' since it isn't a known property of 'form'.
    at createUnknownPropertyError (core.js:12759)
    at validateAgainstUnknownProperties (core.js:12698)
    at elementPropertyInternal (core.js:12603)
    at Module.ɵɵproperty (core.js:19773)
    at LoginComponent_Template (login.component.html:2)
    at executeTemplate (core.js:12177)
    at checkView (core.js:13615)
    at componentRefresh (core.js:13359)
    at refreshChildComponents (core.js:11858)
    at refreshDescendantViews (core.js:11757)
defaultErrorLogger @ core.js:6014
handleError @ core.js:6066
(anonymous) @ core.js:41068
invoke @ zone-evergreen.js:359
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:39579
tick @ core.js:41065
(anonymous) @ core.js:40903
invoke @ zone-evergreen.js:359
onInvoke @ core.js:39706
invoke @ zone-evergreen.js:358
run @ zone-evergreen.js:124
run @ core.js:39518
next @ core.js:40900
schedulerFn @ core.js:35335
__tryOrUnsub @ Subscriber.js:185
next @ Subscriber.js:124
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35297
checkStable @ core.js:39649
onHasTask @ core.js:39726
hasTask @ zone-evergreen.js:411
_updateTaskCount @ zone-evergreen.js:431
_updateTaskCount @ zone-evergreen.js:264
runTask @ zone-evergreen.js:185
drainMicroTaskQueue @ zone-evergreen.js:559
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:542
scheduleTask @ zone-evergreen.js:381
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:372
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:845
resolvePromise @ zone-evergreen.js:791
(anonymous) @ zone-evergreen.js:707
webpackJsonpCallback @ bootstrap:25
(anonymous) @ pages-login-login-module.js:1

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.3.12
Node: 10.15.1
OS: darwin x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              8.3.12
@angular-devkit/schematics        8.3.12
@angular/cdk                      8.2.3
@angular/cli                      8.3.12
@angular/material                 8.2.3
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

* Operating System: Mac OS 10.14.3 (18D42)
* IDE: PhpStorm
```
PhpStorm 2019.2.3
Build #PS-192.6817.20, built on September 25, 2019
You have a perpetual fallback license for this version
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: biz.elfuego.idea.issues.gitea, mobi.hsz.idea.gitignore, Karma, com.intellij.plugins.webcomponents, de.espend.idea.laravel, lv.midiana.misc.phpstorm-plugins.deep-keys, org.psliwa.idea.composer, ru.adelf.idea.dotenv
```

**Comment by petrikas** [comment] 2019-10-23 09:43
I was able to reproduce the error.
[error.log](https://github.com/angular/angular/files/3761532/error.log)

**Comment by maxgaurav** [comment] 2019-11-04 04:18
Update:
The issue has escalated. Now any input binding in HTML causes a similar error.
Any component with input properties has a similar error.

**Comment by arayaryoma** [comment] 2019-11-06 16:14
I have same error too.

**Comment by skynolimits247** [comment] 2019-11-06 16:28
Experiencing same issue......any updates ??

**Comment by maxgaurav** [comment] 2019-11-07 11:58
I have updated the sample repository with error pointed above.

### Changes Done
I have created a component with a property with input decorator and I have binded with using **[]** in the main login.component.html 

Starting a new serve would not throw error but when you change anything in any of the html the following error shows up just like the **formGroup** error.

```
ERROR Error: Template error: Can't bind to 'inputValue' since it isn't a known property of 'app-sampleinput'.
    at createUnknownPropertyError (core.js:12759)
    at validateAgainstUnknownProperties (core.js:12698)
    at elementPropertyInternal (core.js:12603)
    at Module.ɵɵproperty (core.js:19773)
    at LoginComponent_Template (login.component.html:16)
    at executeTemplate (core.js:12177)
    at checkView (core.js:13615)
    at componentRefresh (core.js:13359)
    at refreshChildComponents (core.js:11858)
    at refreshDescendantViews (core.js:11757)
```

@AndrewKushnir 
Please check.

**Comment by AndrewKushnir** [comment] 2020-05-27 01:26
Hi @maxgaurav,

I've just tried to reproduce this problem using the Github repository provided. I upgraded Angular packages (Framework, CLI and Material) to the latest versions (+ updated some imports for material components to make them deep imports) and was unable to reproduce the problem.

Could you please try to update all packages to the latest versions and test the behavior once again? Please let us know if the problem still exists.

Thank you.

**Comment by AndrewKushnir** [comment] 2020-06-12 20:07
Hi, as I mentioned in my previous comment, I was unable to repro the issue after upgrading Angular packages to the latest versions. I will close this ticket for now, please create a new one if the problem still exists. Thank you.

**Closed by AndrewKushnir** 2020-06-12 20:07 UTC
Labels: comp: forms, state: Needs repro, triage #1

**Comment by maxgaurav** [comment] 2020-06-15 03:38
Ok. Thanks
Yes its working with Angular 9.
While upgrading the items I also found the root cause of the problem, Leaving this for others who are facing this
Firstly, I had the AOT on with ivy engine on which is main error point. Anyone facing issue with angular 8 turn ivy and AOT off.
