### ISSUE TITLE
forms: sync patchValue/setValue call with async validator only emits statusChanges once.

### ISSUE THREAD

**Issue by crysislinux** [angular/angular#12470] opened 2016-10-23 12:27 UTC
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see 
```

**Current behavior**

Please see this plnkr.
http://plnkr.co/edit/JipoCIKnncYPosFVMFaT?p=preview

I called 

``` js
this.form.patchValue({name: 'Lucy'})
```

after form was created.

statusChanges only emits once, the status value is PENDING, and no any more statusChanges events. 

But another VALID statusChanges event will be fired later if patchValue is wrapped with setTimeout.

The same behavior happened when use setValue or set initial value with new FormControl(value);

I also found that when wrap patchValue with setTimeout, _runAsyncValidator in forms/src/model.js will run only once for the name control. But if call patchValue synchronously, _runAsyncValidator will be called several times.

**Expected behavior**

patchValue will cause two statusChanges events to be fired, with the value of PENDING and VALID.

**Minimal reproduction of the problem with instructions**

Please check this plnkr.
http://plnkr.co/edit/JipoCIKnncYPosFVMFaT?p=preview

Open the dev console to see console logs.
You will find that only PENDING is printed. But form.valid changed in the UI.

**What is the motivation / use case for changing the behavior?**

I want to track the status of the form with statusChanges event. This is convenient when cannot access the form instance directly.

**Please tell us about your environment:**

Operating system: OS X EI Capitan
Package manager: npm
- **Angular version:** 2.0.X

2.1.1, 2.2.0-beta.0
- **Browser:** 

Chrome  56.0.2898.0 canary (64-bit) and 53.0.2785.143 (64-bit)
Mac Safari 10.0 (11602.1.50.0.10)
Firfox: 49.0.1
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 2.0.3
- **Node (for AoT issues):**

v6.4.0

**Comment by mackelito** [comment] 2017-05-25 21:12
@crysislinux  Did you ever solve this issue?

**Comment by crysislinux** [comment] 2017-06-30 02:17
@mackelito Sorry, it was a long time ago. I am not sure about it. I thought that I wrapped the code with setTimeout at last.

**Comment by moniuch** [comment] 2017-08-08 09:04
I can confirm - `setTimeout` worked for me in this case. The control with asyncValidator on it was constantly reporting itself as `pending` after calling `.setValue()` on it. Wrapping `.setValue()` in a `setTimeout` did the trick.

**Comment by kara** [comment] 2017-12-05 00:24
@crysislinux The plunker link no longer works, so I can't reproduce this issue. Do you mind posting a fresh plunker/stackblitz repro case so this is actionable?

**Comment by kara** [comment] 2017-12-13 00:09
Closing this, as it's not actionable without a repro.

**Closed by kara** 2017-12-13 00:09 UTC
Labels: comp: forms, state: Need repro
