### ISSUE TITLE
NG0500 when template is dynamic

### ISSUE THREAD

**Issue by web-dave** [angular/angular#52454] opened 2023-10-30 20:13 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When using hydration and if the template is dynamic ngFor or @for i get a ng0500 error

### Please provide a link to a minimal reproduction of the bug

https://github.com/web-dave/cli-test

### Please provide the exception or error you saw

```true
ERROR Error: NG0500: During hydration Angular expected <th> but found <tr>.

Angular expected this DOM:

<thead _ngcontent-ng-c3385063389="">
  <th>…</th>  <-- AT THIS LOCATION
  …
</thead>

Actual DOM is:

<thead _ngcontent-ng-c3385063389="">
  <tr>…</tr>  <-- AT THIS LOCATION
</thead>

Note: attributes are only displayed to better represent the DOM but have no effect on hydration mismatches.

To fix this problem:
  * check the "_AppComponent" component for hydration-related issues
  * check to see if your template has valid HTML structure
  * or skip hydration by adding the `ngSkipHydration` attribute to its host node in a template

 Find more at https://angular.io/errors/NG0500
    at validateMatchingNode (core.mjs:17491:15)
    at locateOrCreateElementNodeImpl (core.mjs:20926:18)
    at ɵɵelementStart (core.mjs:20825:20)
    at AppComponent_Template (app.component.html:1:8)
    at executeTemplate (core.mjs:12187:13)
    at renderView (core.mjs:13386:13)
    at renderComponent (core.mjs:13333:5)
    at renderChildComponents (core.mjs:13431:9)
    at renderView (core.mjs:13411:13)
    at ComponentFactory.create (core.mjs:14310:13)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.0-rc.2
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.2
@angular-devkit/build-angular   17.0.0-rc.2
@angular-devkit/core            17.0.0-rc.2
@angular-devkit/schematics      17.0.0-rc.2
@angular/cli                    17.0.0-rc.2
@angular/ssr                    17.0.0-rc.2
@schematics/angular             17.0.0-rc.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.1
```

**Comment by jnizet** [comment] 2023-10-30 21:24
The error message could be a little bit clearer, but it still tells you what the problem is: a `thead` element is supposed to contain `tr` child elements, not `th` elements. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/thead

**Comment by AndrewKushnir** [comment] 2023-10-30 23:48
Closing based on @jnizet comment. Please reopen if the problem still exists after adding `<th>` elements.

@jnizet please let us know if you have some thoughts on how we can improve the error message (please create a ticket with additional info). Thank you.

**Closed by AndrewKushnir** 2023-10-30 23:48 UTC
