### ISSUE TITLE
ngOnInit implicitly detects changes if no detectChanges has been called

### ISSUE THREAD

**Issue by JeviScript** [angular/angular#39511] opened 2020-10-30 14:03 UTC
### Description

Hello there! 
I am not sure if that's a bug or intended behaviour, but here is what I am confused about.
If your component uses ChangeDetectionStrategy.OnPush, and you don't call detectChanges inside of your lifecycle-hooks such as `ngOnInit`, all variables are being assigned. So it seems that angular itself implicitly runs detectChanges after `ngOnInit`.
However if somewhere along the lines of `ngOnInit` you call for detectChanges before some variable assignments, those variable assignments are ignored. Is it expected behaviour or a bug ?

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-playground-bbnpda?file=app%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version: 7 - 10**

**Comment by alexzuza** [comment] 2020-10-30 15:27
I think that's by design.

Once component with OnPush change detection strategy gets update through change detection Angular marks it as checked. It won't be checked anymore unless you mark it for check or call detectChanges for component's view again.

On first load Angular  triggers change detection starting from root component smth like:

```
ngOnInit() {
  ...
}

// sometimes later Angular triggers rootComponent.detectChanges() or appRef.tick()
```
Change detection goes from root view down to child components views. It won't check onPush components that were already checked once(marked as checked).

By calling `cdRef.detectChanges` within `onOnInit` you're marking component as checked. It means it won't be checked during `appRef.tick()` because you blocked this check.

**Comment by jelbourn** [comment] 2020-10-30 20:50
The `ngOnInit` hook will always be called during app initialization. This lifecycle hook happens _during_ change detection, so calling `detectChanges` again manually in `ngOnInit` would be invalid (this throws an error in later versions of Angular).

**Closed by jelbourn** 2020-10-30 20:50 UTC
Labels: comp: core
