### ISSUE TITLE
Feature: New platform to use DI in node apps

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#24130] opened 2018-05-25 14:18 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Angular dependency injection can be only used in font-end applications.

## Expected behavior
Ability to use angular DI mechanism for any app, that has nothing to do with front-end.
New platform, let's call it `platformApp`, should be added. It will create `Injector` and bootstrap any node.js app. Example usage:
```typescript
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class HelloWorldService {
  run(req, res): void {
    res.send('Hello World');
  }
}
```
```typescript
import { NgModule } from '@angular/core';
import * as express from 'express';

@NgModule({})
export class ServerModule {
  constructor(helloWorld: HelloWorldService) {
    const app = express();
    app.get('/', (req, res) => {
      helloWorld.run(req, res);
    });
    app.listen(3000);
  }
}
```
```typescript
import { platformApp } from '@angular/platform-app';
import { ServerModule } from 'server.module';

platformApp().boostrapModule(ServerModule);
```
Ofc modules used in platformApp should only have providers and imports. Declarations will not be supported.

## What is the motivation / use case for changing the behavior?
Ability to use DI in node apps, one DI mechanism that can be used in both front-end and back-end, better code reusability.
All the building blocks are already there. I know one can create `Injector` on it's own and it doesn't require any platform, but `ReflectiveInjector` is deprecated and `StaticInjector` requires lots of boilerplate code for each provider. Also modules are good addition.

**Comment by trotyl** [comment] 2018-05-25 14:38
> Angular dependency injection can be only used in font-end applications

But why do you think Angular DI can only be used in Front-end app?

**Comment by ericmartinezr** [comment] 2018-05-25 14:48
Take a look at https://github.com/mgechev/injection-js/blob/master/README.md, it may help

**Comment by dawidgarus** [comment] 2018-05-25 15:23
@ericmartinezr Although project looks cool, it doesn't keep up with angular. It links to angular guide as documentation, but literally first example won't work because it uses `providedIn`. And modules would be a nice feature to have.
@trotyl what I really meant is that platforms that angular supports are only meant for front-end apps. Event `platformServer` is there to render html. As I said it is possible to use DI without any platform, but using `StaticInjector` is not really user friendly if You have to write provider with all the deps for each service. You can really use angular's DI mechanism to it's full extent, only a subset of it's functionality.

**Comment by trotyl** [comment] 2018-05-25 15:33
@dawidgarus A `Platform` in Angular is just a preset of `Provider`s, you're welcomed to create your own platform other than `platformBrowser`.

**Comment by Toxicable** [comment] 2018-05-25 21:30
I think you're after Nestjs which is loosely based off Angular, specifically their DI model:
https://docs.nestjs.com/providers
They also have modules https://docs.nestjs.com/modules

**Comment by dawidgarus** [comment] 2018-05-28 08:39
@trotyl It's not just collection of any providers. It must also provide a way to bootstrap module (`PlatformRef`) in order to be of any use, otherwise it's just like a module. And angular doesn't make it easy.  For example, `JitCompilerFactory` has `internal` constructor, so You can't create it without using non-public API. Also, for some reason when You create `JitCompilerFactory` and ignore errors, then compile a module, `providedIn` doesn't work. Ofc I don't need to use `JitCompilerFactory` and write a platform from scratch, but that would be pointless, since there already is a code to do this, but it's not properly exposed.

**Comment by trotyl** [comment] 2018-05-28 09:16
@dawidgarus You can already put whatever logic in `ngDoBootstrap`, if you do not mount a component, then it has nothing to do with compiler.

**Comment by dawidgarus** [comment] 2018-05-28 09:46
@trotyl You really don't get it? I've tried using `platformServerDynamic` with custom `ngDoBoostrap` but it requires `Zone.js` (`Error: In this configuration Angular requires Zone.js`) and that's not something I would like to include in my node app. Not to mention it has a lot of unnecessary dependencies for this purpose. Basically, all I want boils down to creation of `Injector` from `NgModule`. As far I know, it can be only done using `JitCompilerFactory`.

**Comment by trotyl** [comment] 2018-05-28 09:51
@dawidgarus If you don't want to rely on Zone.js, of course `ngZone: 'noop'` should be used. 

What I said above is creating your own platform, rather than using `@angular/platform-server` (as it's designed for web-app). What only being required is `@angular/core`, not even `@angular/common`, what's "a lot of"?

You can still have AOT for your node application unless you don't have a build step (then better to not use TypeScript at all).

**Comment by trotyl** [comment] 2018-05-28 11:45
@dawidgarus You don’t need to implement anything when making a new platform, all platforms are children of `platfomCore`, and nothing must be overridden.

Of course it still requires compilation, that’s how Angular works today, sorry for didn’t make it clear.

**Comment by dawidgarus** [comment] 2018-05-28 12:10
@trotyl But You need to provide `CompilerFactory` - that's the real problem. `PlatformRef` is just a simple facade. It would be nice if angular provided a compiler for module with minimal dependencies that ignores declarations so it could be used only for DI.

**Comment by trotyl** [comment] 2018-05-28 13:13
OK, you’re right about JIT, `@angular/compiler` is not even public API, so I just make everything AOT-only. Should be solved by Ivy.

**Comment by KAMAELUA** [comment] 2020-03-06 09:52
2020. Is any new approaches available? I am using `ReflectiveInjector` from `@angular/core` package, but it marked as deprecated in Angular 8. How to use newest version if I want to compile my project for using in NodeJs server side application?

**Comment by pkozlowski-opensource** [comment] 2020-03-22 07:53
Related / duplicate of #19124

**Comment by alxhub** [comment] 2022-04-14 23:57
We have no intention of exposing Angular DI as an independent library at this point.

**Closed by alxhub** 2022-04-14 23:57 UTC
Labels: feature, comp: core, core: di, insufficient votes, votes required
