### ISSUE TITLE
@Keyframes in Media-Queries doesnt work

### ISSUE THREAD

**Issue by Marvv90** [angular/angular#52496] opened 2023-11-02 20:49 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

The Following SCSS Code works in Production Mode & Development Mode:

`span img {
                height: 78px;
                aspect-ratio: 1;
                pointer-events: none;
                user-select: none;
                animation: rotate var(--duration) infinite forwards linear;
}`

When i move the Animation in a Media Querie in Development Mode it also Works but in Production Mode it doesnt Work anymore.

`@media (hover: none) and (pointer: coarse) {
    button.cursor-button {
        display: block;
        span img {
            animation: rotate var(--duration) infinite forwards linear;
        }
    }
}`

The `rotate` Animation: are a simple rotate animation 

### Please provide a link to a minimal reproduction of the bug

Simple Animation with Media Querie

### Please provide the exception or error you saw

```true
None
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.6
Node: 18.18.2
Package Manager: npm 10.2.0
OS: darwin x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.6 (cli-only)
@angular-devkit/core         16.2.6 (cli-only)
@angular-devkit/schematics   16.2.6 (cli-only)
@schematics/angular          16.2.6 (cli-only)
```

**Comment by JoostK** [comment] 2023-11-02 21:13
This is a duplicate of #49378

**Closed by JoostK** 2023-11-02 21:13 UTC
