### ISSUE TITLE
Missing metadata for @angular/common/locales

### ISSUE THREAD

**Issue by Maistho** [angular/angular#20260] opened 2017-11-08 04:00 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The content of every `[locale].metadata.json` file is `[null]`. This seems to break the angular vscode language service, and is probably not intended.

## Expected behavior
Some actual metadata perhaps? I'm not sure what the contents of these files are supposed to be, but it seems like most libraries have objects top-level in the metadata files.

## Minimal reproduction of the problem with instructions
https://github.com/angular/common-builds/blob/master/locales/en-GB.metadata.json

## Environment
<pre><code>
Angular version: 5.0.0+

Browser: N/A
 
For Tooling issues: N/A

**Comment by Maistho** [comment] 2017-11-08 04:01
Related: #20207

**Comment by vicb** [comment] 2017-11-08 23:06
How does it break the lang service ?

**Comment by Maistho** [comment] 2017-11-08 23:13
It stops giving suggestions in templates, and I get the following output in the output console from VS Code.
Changing the contents of sv.metadata.json from `[null]` to `[]` stops the error from occuring.
```
Search path: /home/maistho/prog/convis/src/app/shop/checkout
Failed to read JSON file /home/maistho/prog/convis/node_modules/@angular/common/locales/sv.metadata.json
Config file name: /home/maistho/prog/convis/src/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
Error for getTemplateRefrences:
    TypeError: Cannot read property 'version' of null
    at /home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21442:70
    at Array.find (native)
    at ReflectorHost.BaseAotCompilerHost.readMetadata (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21442:42)
    at ReflectorHost.BaseAotCompilerHost.getMetadataFor (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:21419:29)
    at StaticSymbolResolver.getModuleMetadata (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17910:45)
    at StaticSymbolResolver._createSymbolsOf (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17740:29)
    at StaticSymbolResolver.getSymbolsOf (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:17725:14)
    at /home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16800:30
    at Array.forEach (native)
    at extractProgramSymbols (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:16799:79)
getTemplateRefrences: 1402ms
SERVER ERROR: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at Project.updateFileMap (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:797:94)
    at Project.updateGraph (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:815:14)
    at Project.finishGraph (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:807:14)
    at ProjectService.openConfigFile (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1634:17)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1486:41)
    at ProjectService.openClientFile (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1404:23)
    at /home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:135:47
    at TextDocuments.logErrors (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:131:74
    at handleNotification (/home/maistho/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
[Error - 00:10:30] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'length' of null
Search path: /home/maistho/prog/convis/src/app/shop/checkout
Failed to read JSON file /home/maistho/prog/convis/node_modules/@angular/common/locales/sv.metadata.json
Failed to read JSON file /home/maistho/prog/convis/node_modules/@angular/common/locales/sv.metadata.json
Config file name: /home/maistho/prog/convis/src/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
```

etc.

**Comment by Maistho** [comment] 2017-11-08 23:14
This only appears after importing and registering the locale in my `app.module.ts`.

```typescript
import { registerLocaleData } from '@angular/common';
import svLocale from '@angular/common/locales/sv';
registerLocaleData(svLocale);
```

**Comment by Maistho** [comment] 2017-11-08 23:21
Right now I also tried updating the language service and other dependencies in the vs-code extension to 5.0.1, and the problem still persists.

**Comment by FdezRomero** [comment] 2017-11-08 23:28
Same problem here: importing any locale throws the error above in the Angular Language Service (as it sees an element in the array but null isn't an object), that prevent any checks being completed in the whole project.

After many retries Visual Studio Code just stops trying to the restart the language server due to errors.

**Comment by fpeterdev** [comment] 2017-11-09 12:31
I have the same issue angular 5.0.0. and VSCode 1.17.2
Replacing `[null]` with `[]` in the `[locale].metadata.json` file in `node_modules` seems to solve it; so far everything seems to work. Modifying files in `node_modules` is far from ideal, but at least VS Code is working until a more permanent solution.

**Comment by ikourfaln** [comment] 2017-11-10 17:49
Same issue.
I think the problem occurs because the Angular Language Service extension uses `@angular/language-service@5.0.0-beta.5`. the extension needs to be updated to use `@angular/language-service@5.0.1`

**Comment by Maistho** [comment] 2017-11-10 23:10
@ikourfaln I had the same issue with 5.0.1

**Comment by ikourfaln** [comment] 2017-11-11 12:46
@Maistho 
Yes me too, but as I said maybe the issue is the extension, still uses `language-service@5.0.0-beta.5`

![capture](https://user-images.githubusercontent.com/9744226/32689509-390a45de-c6de-11e7-90c0-673068dc61ff.PNG)

Dependency must be updated to `@angular/`language-service@5.x.x`

**Comment by Maistho** [comment] 2017-11-11 15:23
@ikourfaln: Sorry I was not clear. I updated the vscode extension to use 5.0.1 and still had the same issue.

**Comment by ikourfaln** [comment] 2017-11-12 04:06
@Maistho 
I see, but updating just the package is not enough, I think that the extension must be refactored to follow the break changes after Language Service beta5.

**Comment by victornoel** [comment] 2017-11-20 08:40
That sucks a bit that the extension does not use an implementation based on the node_modules… everytime there are ng update, there are some risks of breaking everything.

**Comment by victornoel** [comment] 2017-11-21 10:00
@vicb any way to get this fixed? There has been two patch releases since this issue was reported and I suppose this could be fixed simply, no? If you have a recommendation on how to do that, I can do a PR :)

**Comment by ashishmulaye** [comment] 2017-11-26 12:32
@victornoel, any update on when your fix will be available?

**Comment by victornoel** [comment] 2017-11-26 12:39
@ashishmulaye ask @chuckjaz or @mhevery :)

**Comment by ashishmulaye** [comment] 2017-11-29 16:17
@chuckjaz, @mhevery, will it be available in next beta release?

**Comment by deniskrafczyk** [comment] 2017-12-01 15:35
are there any further information?

**Comment by ocombe** [comment] 2017-12-14 16:44
Fixed with #20938

**Closed by ocombe** 2017-12-14 16:44 UTC
Labels: comp: i18n, comp: language-service, freq3: high, severity3: broken, type: bug

**Comment by ikourfaln** [comment] 2017-12-14 18:37
Thank you @ocombe 
But this is fixed for which milestone? we are waiting for a version that includes this fix.

**Comment by ocombe** [comment] 2017-12-14 18:40
For the next releases (minor and major)

**Comment by ikourfaln** [comment] 2017-12-15 10:22
Thank you @ocombe 
I'm just wondering how do you manage all commits without milestone!
I think that there is a label to target all next releases.

**Comment by ocombe** [comment] 2017-12-15 10:24
It's a bit of a mess sometimes, but we are starting to change our process and we will be adding milestones soon
And yes, we're using the target label for now
