### ISSUE TITLE
Dynamic templateUrl

### ISSUE THREAD

**Issue by stefandewaard** [angular/angular#17788] opened 2017-06-27 11:13 UTC
Is there a possibility to get a variable templateUrl? Because I'am creating a hybrid application and when the application is in a browser we want to change the html file.

## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Please tell us about your environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by tytskyi** [comment] 2017-06-27 11:33
It is not possible, subscribe to https://github.com/angular/angular/issues/11144 for updates

**Comment by IgorMinar** [comment] 2017-07-11 00:03
Thanks for reporting this issue. However this issue is a duplicate of an existing issue #11144. Please subscribe to that issue for future updates.

**Closed by IgorMinar** 2017-07-11 00:03 UTC
