### ISSUE TITLE
Route to a component without changing path.

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#9949] opened 2016-07-11 06:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When rejecting access to a component in a path using Guards you currently have to redirect to another path otherwise you get a blank page. This is for rc.4 new router.

**Expected/desired behavior**
It would be useful to be able to render a rejection page such as a 403 and not require a redirect or be able to provide a component for rejection.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all ] 
 
* **Language:** [all]

**Comment by zoechi** [comment] 2016-07-19 08:17
dup of #9579

**Comment by vsavkin** [comment] 2016-07-20 21:51
Closing this issue because it is a duplicate of https://github.com/angular/angular/issues/9579

**Closed by vsavkin** 2016-07-20 21:51 UTC
Labels: comp: router
