### ISSUE TITLE
DOM_REFLECT_PROPERTIES_AS_ATTRIBUTES doesn't work for directives

### ISSUE THREAD

**Issue by goderbauer** [angular/angular#3678] opened 2015-08-17 17:48 UTC
internally tracked at b/23155191

**Comment by pkozlowski-opensource** [comment] 2015-08-17 18:15
IMO it would be nice to provide minimal context / reproduce scenario here for people that don't have access to the "internal tracker"....

**Comment by tbosch** [comment] 2015-08-17 18:20
The idea is to mirrors properties that are set on components/directives as attributes on the corresponding DOM elements. E.g.

```
<my-component [name]="someName">
```

Should show the name as an attribute (assuming `someName` has the value `tobias`):
```
<my-component ng-reflect-name="tobias">
```

**Comment by naomiblack** [comment] 2015-08-17 18:21
@jeffbcross this is P1 for our internal folks. Can you have a look?

**Comment by tbosch** [comment] 2015-08-17 18:23
The place to change this is in the change detector, as normally, setting these properties would never reach the renderer. I.e. we need to change the implementation of the change detectors to call the renderer (i.e. `Render.setElementAttribute()`) at the right times.

For `DynamicChangeDetection` this would be here: https://github.com/angular/angular/blob/master/modules/angular2/src/change_detection/dynamic_change_detector.ts#L162

To be discussed with GT: Is it enough to include this logic in dynamic change detection only, or should it also be part of the generated change detectors (probably behind a flag in the pubspec.yaml).

/cc @vsavkin

**Comment by jeffbcross** [comment] 2015-08-17 18:50
@naomiblack yes I will look into this.

**Comment by jeffbcross** [comment] 2015-08-17 18:58
Hmm, I don't seem like the right person to be looking at this as a P1. I'll figure out who would be best.

**Comment by jeffbcross** [comment] 2015-08-17 19:06
@vsavkin is going to take this on. It sounds like a deep change required to change detector and render APIs.

**Comment by naomiblack** [comment] 2015-08-17 22:00
moving to alpha-36 since this sounds like it will take a few days at a minimum to work out.

**Comment by vsavkin** [comment] 2015-08-21 20:44
Closed via https://github.com/angular/angular/commit/a9ce454b2176514e1b655d7b005c32f0aa14ab98

**Closed by vsavkin** 2015-08-21 20:44 UTC
Labels: comp: core/directives, effort2: medium (day), hotlist: GT, P1: urgent, type: bug
