### ISSUE TITLE
Injector.get() issue with "ng test" when code coverage is enabled

### ISSUE THREAD

**Issue by redaxmedia** [angular/angular#34959] opened 2020-01-24 20:25 UTC
# 🐞 bug report

### Affected Package

This issue is properly related to one of these:

+ angular/core
+ karma-coverage-istanbul-reporter
+ karma-jasmine

### Is this a regression?

Nope, I could not find a working combination. I could reproduce this in Angular 8 aswell.

### Description

When running Karma with `--code coverage` flag the `Injector` causes a compile issue:

```
ng test --code-coverage
```

## 🔬 Minimal Reproduction

I released a temporary branch to reproduce the problem, more details in the readme:
https://github.com/redaxmedia/ngx-crud-playground/tree/debug-ngtest-with-code-coverage

## 🔥 Exception or Error

```shell script
TypeError: Cannot read property 'get' of undefined
    at <Jasmine>
    at new CommonService (http://localhost:9876/_karma_webpack_/lib/common.service.ts:24:24)
    at new CrudService (http://localhost:9876/_karma_webpack_/lib/crud.service.ts:25:3)
    at new JokeService (http://localhost:9876/_karma_webpack_/main.js:2995:5)
    at _createClass (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:32626:1)
    at _createProviderInstance (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:32593:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:32538:1)
    at NgModuleRef_.get (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/core.js:33531:1)
    at TestBedViewEngine.inject (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/testing.js:3917:1)
    at http://localhost:9876/_karma_webpack_/node_modules/@angular/core/fesm2015/testing.js:3944:1
    at <Jasmine>
```

## 🌍  Your Environment

**Angular Version:**
```
Angular CLI: 9.0.0-rc.10
Node: 10.15.3
OS: linux x64

Angular: 9.0.0-rc.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

```

**Comment by Zuckjet** [comment] 2020-01-27 16:42
when you run `ng test --code-coverage`, angular cli tool will depend on `istanbul-instrumenter-loader` loader, which cannot recognize decorator syntax。From your code：
```
constructor(protected injector : Injector)
	{
		this.http = injector.get<HttpClient>(HttpClient);
	}
```
Because the loader cannot recognize decorator syntax, the inject `injector` will be `undefined`.
That's why you will see errors:

> Cannot read property 'get' of undefined

I think it is a bug of angular cli not angular, but if you want to make it work now, you can add one line code in tsconfig.spec.json:
```
"compilerOptions":
	{
		"outDir": "./out-tsc/spec",
		"target": "es5",    --- add this line
	},
```
Let me know if i misunderstand this question.

**Comment by redaxmedia** [comment] 2020-01-27 18:15
Thank you so much, that workaround is a life saver. I tried this with `modul` but `target` makes more sense.

However, we should keep this open unless the real issue has been solved.

**Comment by alan-agius4** [comment] 2020-01-30 07:24
Duplicate of https://github.com/angular/angular-cli/issues/14860

**Closed by alan-agius4** 2020-01-30 07:24 UTC
Labels: comp: core
