### ISSUE TITLE
Typed Form + Formbuilder error for initial value null

### ISSUE THREAD

**Issue by EinfachHans** [angular/angular#46917] opened 2022-07-21 06:55 UTC
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I have a form:

```ts
public form: FormGroup<{
  reason: FormControl<number>;
}>;
```

and use the form builder to create it:
```ts
this.form = this.formBuilder.group({
  reason: [null, [Validators.required]]
});
```

This gives the following error:

**TS2322: Type 'FormGroup<{ reason: FormControl<((control: AbstractControl<any, any>) => ValidationErrors)[]>; }>' is not assignable to type 'FormGroup<{ reason: FormControl<number>; }>'.**

What works it describing it like this:

```ts
this.form = this.formBuilder.group({
  reason: new FormControl<number>(null, [Validators.required])
});
```

But i think that is taking the advantage of the form builder away, because i don't want to write `new FormControl<Type>` everytime...

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.1.0
Node: 16.14.2
Package Manager: npm 8.6.0 
OS: darwin x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by lukasmatta** [comment] 2022-07-21 07:27
Hello, there is already an issue for this: Duplicate of #46442

**Closed** 2022-07-21 07:28 UTC
