### ISSUE TITLE
The state of the input field does not match the state of the control, when using ngSwitch

### ISSUE THREAD

**Issue by sergey-malykh** [angular/angular#20908] opened 2017-12-09 10:20 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I use ngSwitch to switch some tabs. Tabs separate by type. First tab has control enabled, second tab of the same type has control disabled . When I change first tab to second tab, input field is disabled. It's right. But when I change second tab to first tab, input field is disabled too. Although, the control of first tab is enabled

## Expected behavior
Input field must match the control state 

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/lbat8ASfSc2xBqMSIcRb

## Environment

<pre><code>
Angular version: 5.1.0

Browser: anyone
- [ x ] Chrome (desktop) version 62
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

</code></pre>

**Comment by kara** [comment] 2017-12-12 23:15
This looks like a duplicate of https://github.com/angular/angular/issues/17806

**Closed by kara** 2017-12-12 23:15 UTC
Labels: comp: forms
