### ISSUE TITLE
when i use ng update i get an error

### ISSUE THREAD

**Issue by amir141592** [angular/angular#54680] opened 2024-03-03 18:31 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

i wanted to check for updates and then update my project that i got this error

### Please provide the exception or error you saw

```true
[error] TypeError: LRUCache is not a constructor
    at Object.<anonymous> (/home/a/Projects/Angular/Muzik/node_modules/@npmcli/git/lib/revs.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/a/Projects/Angular/Muzik/node_modules/@npmcli/git/lib/clone.js:25:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 20.10.0
Package Manager: npm 10.5.0
OS: linux x64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JeanMeche** [comment] 2024-03-03 19:07
From what I understand from npm/cli#6785, this issue is not due to the Anguar  CLI itself.

**Comment by pkozlowski-opensource** [comment] 2024-03-04 09:15
Duplicate of https://github.com/npm/cli/issues/6785

**Closed by pkozlowski-opensource** 2024-03-04 09:15 UTC
