### ISSUE TITLE
string type variable asking for initialize. Behave like const

### ISSUE THREAD

**Issue by Dev-ashraf-ali** [angular/angular#47224] opened 2022-08-23 05:24 UTC
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

If I declare a variable string type then I got error. It saying initialize (assign). If I give some value to that variable then everything goes fine. I am thinking string type is behave like cont keyword.
![Screenshot from 2022-08-23 10-26-16](https://user-images.githubusercontent.com/60649392/186076324-6e62a230-a5eb-45a8-ab7a-c66364825aaa.png)
![Screenshot from 2022-08-23 10-52-14](https://user-images.githubusercontent.com/60649392/186076430-4d755a7e-c414-4095-b279-e3bd2a3d65c3.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.8
Node: 18.4.0 (Unsupported)
Package Manager: npm 8.12.1
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8
@angular/cdk                    13.3.9
@angular/cli                    13.3.8
@angular/material               13.3.9
@schematics/angular             13.3.8
rxjs                            7.5.6
typescript                      4.6.4
```

**Comment by jnizet** [comment] 2022-08-23 06:11
Hi @Dev-ashraf-ali 

This is not an Angular bug or regression. It's just the standard, normal behavior of TypeScript when in strict mode (and in particular, when the strictPropertyInitialization compilation option is true). See https://www.typescriptlang.org/tsconfig#strictPropertyInitialization

**Comment by JoostK** [comment] 2022-08-23 07:41
Indeed, this is due to TypeScript's `strict`/`strictPropertyInitialization` option being enabled. The error is legitimate, as the field will be `undefined` as long as it hasn't been assigned to, however that doesn't satisfy the type declaration that says that the field is of type `string`.

**Closed by JoostK** 2022-08-23 07:41 UTC

**Comment by Dev-ashraf-ali** [comment] 2022-08-23 12:35
Thank you for your response. In previous versions if I declare formgroup
and do not use. It was perfectly fine. But now if I declare so, I have to
use.

That is a good thing.

Thanks again and sorry for annoying you.

Thanks & Regards
Ashraf Alii
