### ISSUE TITLE
Can't use NgFor or NgIf inside the LightDom of a Polymer Web Component

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#3593] opened 2015-08-11 21:39 UTC
Polymer's Shady DOM does its own content projection when a polymer web component is created which destroys our `<template>` tag that is necessary for NgFor and NgIf. The result is the following error from the renderer:
```
EXCEPTION: TypeError: Cannot read property 'parentNode' of undefined in [null]
browser_adapter.js:106 ORIGINAL EXCEPTION: TypeError: Cannot read property 'parentNode' of undefined
browser_adapter.js:106 ORIGINAL STACKTRACE:
browser_adapter.js:106 TypeError: Cannot read property 'parentNode' of undefined
    at BrowserDomAdapter.execute.$__export.parentElement (browser_adapter.js:190)
    at moveNodesAfterSibling (dom_renderer.js:32)
    at execute.$__export.attachFragmentAfterElement (dom_renderer.js:175)
    at execute.$__export._attachRenderView (view_manager.js:168)
    at execute.$__export._createViewInContainer (view_manager.js:158)
    at execute.$__export.createEmbeddedViewInContainer (view_manager.js:136)
    at ViewContainerRef.execute.$__export.createEmbeddedView (view_container_ref.js:41)
    at Function.execute.$__export.bulkInsert (ng_for.js:118)
    at execute.$__export._applyChanges (ng_for.js:83)
    at execute.$__export.onCheck (ng_for.js:68)
```

Full example at: http://plnkr.co/edit/hwj9l34OnZQC061wgi0c

**Comment by mhevery** [comment] 2015-08-20 03:08
@sigmundch Do you know who from polymer could look into this?

**Comment by sigmundch** [comment] 2015-08-20 16:40
@justinfagnani - can you take a look or can forward to the right person?

**Comment by justinfagnani** [comment] 2015-08-20 16:56
Sure

**Comment by tbosch** [comment] 2015-08-20 22:27
@mhevery Sorry, but we already know what the problem is here: 

1. When Angular creates a new `DomView`, it clones an existing template.
2. The web component wakes up and removes it's light dom children
3. Angular does a `querySelectorAll` to find the bound elements in the template. However, the template has changed now, so our elementbinders do no more match the queries elements

This will be fixed automatically with https://github.com/angular/angular/issues/3605, as we then create every element by calling `document.createElement` and therefore already have a reference to it without doing a `querySelectorAll`.

**Comment by mhevery** [comment] 2015-08-21 04:22
@tbosch thanks. @justinfagnani / @sigmundch  looks like noop for you. Thanks.

**Comment by antonmoiseev** [comment] 2015-12-01 20:39
Looks like this is already fixed. But here is the related issue - https://github.com/angular/angular/issues/5531.

**Closed** 2016-07-01 20:30 UTC
Labels: comp: core, effort2: medium (day), hotlist: angular-core-team, P3: important, type: bug
