### ISSUE TITLE
ngFor memory leak

### ISSUE THREAD

**Issue by Priemar** [angular/angular#29053] opened 2019-03-01 10:43 UTC
# 🐞 bug report

### Is this a regression?
Don't think so.

### Description

Structure: `AppComponent` , `OneComponent`, `TwoComponent`, `TestService`

`OneComponent` and `TwoComponent` are displayed in `AppComponent` _(only one component is displayed at the same time -> i added button to switch between those components)._

`OneComponent` and `TwoComponent` contains a TemplateRef, when `OneComponent` or `TwoComponent` is created this TemplateRef is added to a `TestService` which is provided by the `AppComponent`.
If `OneComponent` or `TwoComponent` gets destroyed the will remove their TemplateRef from the `TestService`.

TestService: adding / removing a TemplateRef will add remove it to a behaviorSubject (included in TestService).

The `AppComponent` will bind to this behaviorSubject  async.  and display the TemplateRefs.

I added 4 test cases inside the `AppComponent` - template: (just (un)comment to test this test cases)

- Test1 (memory leak):  _ngFor binding with async pipe and displaying the templateRef in templateOutlet_
- Test 2 (memory leak): _ngFor binding an empty ng-container with async pipe, do not display anything_
- Test 3 (no memory leak): _ngIf binding the first element with async pipe, display the templateRef in templateOutlet_
- Test 4 (no memory leak): _binding the first element with async pipe directly to templateOutlet_

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-grux6a

_*this is just a quick implementation to reproduce this "bug", no error checks not a clean code but that was not the point*_

## 🔥 Exception or Error

Using the browser memory tool (snapshots) shows for Test1 and Test2 that `OneComponent` and `TwoComponent` are still in memory even if they are not displayed.

Expected: `OneComponent` should not be in memory when `TwoComponent` is displayed and vice versa.

## 🌍  Your Environment

**Angular Version:**
7.2.5

**Comment by CharlBest** [comment] 2019-03-03 22:01
I'm not sure if this is related and it is difficult for me to explain but one very specific scenario is freezing my Angular application but only on my phone. I think it has to do with my phone's low memory or CPU capacity. 

Here is a Stackblitz: https://stackblitz.com/edit/angular-zjamn2

When I put *ngFor on ng-container or on my custom component's tag it freezes but when I use a div it doesn't. It was very difficult for me to test as I couldn't use my computer even throttling my CPU x6 in dev tools and I don't have that great a machine so not sure how you or anyone else is going to reproduce this but I can very easily reproduce this just by changing one line in that Stackblitz example. It took me 2 days to debug and I pulled all my hair out. Haha. Would be great if someone could tell my why it works with a div but not <app-example> or <ng-container> as I thought ng-container was perfect for scenarios like this.

I'm using a Samsung Galaxy Note 5 with the latest Chrome for Android (73.0.3683.58) and only had 1 tab open.

**Comment by CharlBest** [comment] 2019-03-03 22:14
Ohhh wow. Even more developments. So....... It looks like it isn't the *ngFor placement.
Look at this Stackblitz: https://stackblitz.com/edit/angular-pakiww

The *ngFor now has a wrapping div (just an empty old div) but that seems to make it work. Removing the div will cause the app to freeze on my phone. I think it is a memory issue because when I decrease the array size to 10 it works but the higher I go the slower it becomes and then just freezes. I have a complex custom element in my *ngFor so when I reach 20 loops it bombs. But when I wrap it in a div everything works.

Hope that helps.

**Comment by Priemar** [comment] 2019-03-04 08:43
@CharlBest i think you issue is not related to the topic, but i tried to reproduce without success. Im often using ngFor on ng-containers which works great, that should not be the reason your app freezes. I dont think your problem is an angular specific problem, but correct me if im wrong.

**Comment by Priemar** [comment] 2019-03-04 08:45
Back to topic:  i wrote my own *ngFor which solved the memory leak, as workaround.

**Comment by CharlBest** [comment] 2019-03-04 10:26
@Priemar Thanks for the reply. I think you're right this issue isn't related to each other so I will create a new issue for it.
Like I said it can't be something in my application as I could replicate it in Stackblitz in a few line of code. It's probably not happening for you because you don't have limited memory or CPU. It's a difficult one to debug.

**Comment by meta-rohit-singhavi** [comment] 2019-05-04 12:47
@Priemar I am facing issues due to memory leak as well and it looks like my case is somewhat similar to yours. It will be very helpful if you could share your custom code of *ngFor. Thanks.

**Comment by Priemar** [comment] 2019-05-04 19:30
@meta-rohit-singhavi my workaround is a specific implementation for this corner case. It is not reusable outside of our project i guess.

It was not my intention to duplicate the ngFor, because i just wanted to fix the memory leak for my specific corner case. and remove it asap when the ngFor memory leak is fixed.

The problem only happend in one particular part of our project (corner case) which. In all other cases i am using the default ngFor.

Here is what i did (as you can see in the example above, i have a service which emits templateRefs)

1) i created a **structural directive** 
2) this structural directive injects the service and subscribes to it
3) after receiving new templateRefs the structural directive will create/replace/remove embedded views based on the templateRefs (thats what structural directives do)
4) removing the templates, unsubscribe from the service when the directive gets destroyed.

-> its super simple, and like a std. usecase for structural directives.

Using a service instead of Input paramters for the structural directive, is just a special case for my project. Maybe you dont have a service and you simply need inputs for your structural directive, or you need the specific template context inside your templates etc.. As i said it depends on your case. 

Hope it will help you. -> if you have any further questions feel free to ask, (a stackblitz would be super helpfull if you wan't help for your particular case)

greetz

**Comment by petebacondarwin** [comment] 2020-05-29 15:22
My initial look at this does see the two components staying in memory - although there is only ever 1 instance of each. So the memory leak is limited in scope.

**Comment by petebacondarwin** [comment] 2020-05-29 16:23
I can confirm that this is due to the previous value being retained by the `DefaultIterableDiffer` and still occurs in both ViewEngine and Ivy, in both dev-mode and prod-mode.

![Screenshot 2020-05-29 at 16 26 21](https://user-images.githubusercontent.com/15655/83282176-22a99f80-a1d1-11ea-959a-dc8809f92684.png)

**Comment by JeanMeche** [comment] 2023-07-04 21:50
This is a dupe of #36878, let's close this one and track the issue over there !

**Closed by JeanMeche** 2023-07-04 21:50 UTC
Labels: type: bug/fix, area: common, freq3: high, memory leak, state: confirmed, P3
