### ISSUE TITLE
Simple API for checking if a path is accessible (would pass all guards)

### ISSUE THREAD

**Issue by childersd** [angular/angular#44556] opened 2021-12-23 15:59 UTC
### Which @angular/* package(s) are relevant/releated to the feature request?

router

### Description

Imagine that you are adding menu entries for pages of your application. The menu includes pages (routes) that are not accessible depending on the user's role. Guards decline navigation to them if necessary.

For better UX, you only show those menu entries that are available to the current user.

### Proposed solution

It would be great if you could ask the router whether a path is accessible based on the guards that are associated with it. For example,

```typescript
this.router.isAccessible("admin");
```

This would return an observable that resolves (completes) to true or false, indicating accessibility. This would be based on any `canActivate`, `canActivateChild` or `canLoad` guards that target the specified path. By calling this method and subscribing to the returned observable you'd essentially perform a "dry-run" navigation event to check if it is cancelled (or altered) by any guards, without updating the view. Documentation should clearly state that guards should not have side effects when making use of this utility.

### Alternatives considered

Alternatively, you could extract the checks from the guards and group them into some service. Then guards and any other logic could ask it whether a given path is accessible.

The problem I have with this is that this partly defeats the purpose of having guards. For me, the power of Angular is that it is opinionated and that in-house solutions are very often unnecessary. Guards are testable in isolation and are the expected location for logic related to authorization of routes. "Where's the logic that checks the permissions of a user before entering a certain page? — Oh, it's in the PermissionsGuard, of course."

I hope this made sense. Thanks for your time and consideration. :)

**Comment by wduminy** [comment] 2022-01-03 13:14
I think this is a great idea and would increase the value of the Guard feature quite a bit.

**Comment by atscott** [comment] 2022-01-04 21:06
Note that at a minimum, this would necessarily trigger the loading of lazy modules in the path.

**Comment by atscott** [comment] 2022-06-15 19:43
duplicate of https://github.com/angular/angular/issues/15750

**Closed by atscott** 2022-06-15 19:43 UTC
Labels: feature, comp: router, insufficient votes
